### ISSUE TITLE
Remove need to modify build.gradle in node_modules

### ISSUE THREAD

**Issue by adamrainsby** [OneSignal/react-native-onesignal#10]

**Comment by avishayil** [comment]
Yep, we're working alongside OneSignal team on this, we'll update this issue when it's resolved.
I think we need @jkasten2 in here to take care of this.

**Comment by csandeep** [comment]
+1

**Comment by jkasten2** [comment]
@avishayil You might be able to simplify the process by not requiring the modification of `node_modules/react-native-onesignal/android/build.gradle`. I am guessing you have already tried leaving the file as is without modification however could you try just setting these to a blank string?

```
manifestPlaceholders = [manifestApplicationId: "",
                        onesignal_app_id: "",
                        onesignal_google_project_number: ""]
```

I believe this may work as `android/app/build.gradle` should override this. I don't have a lot of experience with react-native but I do with gradle so let me know if you need me to dig into this more.

**Comment by avishayil** [comment]
Yeah, I'm on a vacation right now so can't take a look, can you try doing this with the sample project?

**Comment by avishayil** [comment]
OK, it seems to solve the issue. Thanks @jkasten2 !
