### ISSUE TITLE
postNotification contents and data format

### ISSUE THREAD

**Issue by psyzz** [OneSignal/react-native-onesignal#100]
Hi,

i'm trying to user OneSignal.postNotification, but i didn't find an example for contents and data format:

OneSignal.postNotification(contents, data, player_id);

Do i need to set contents like { title: 'Title', message: 'Message' } ?

Thanks for your great work

**Comment by avishayil** [comment]
Hi, you should follow OneSignal documentation for this:
https://documentation.onesignal.com/docs/android-native-sdk#section--postnotification-

Your'e basically passing the same parameters as here:
https://documentation.onesignal.com/reference#create-notification

`data` is responsible for the data you want to transfer.

I.E:

``` javascript
        let data = arr // some array
        let contents = {
            'en': 'You got notification from user'
        }
        OneSignal.postNotification(contents, data, playerId);
```

**Comment by psyzz** [comment]
Thank you !

**Comment by bondanherumurti** [comment]
```
		OneSignal.configure({
			onIdsAvailable(device){
				console.log('what is device', device);
				OneSignal.postNotification({'en': `you just love a deal with this id`}, {}, device.userId);
			}
		});
```

i'm trying to use this code, but i encounter this error

YellowBox.js:67 Possible Unhandled Promise Rejection (id: 1):
Cannot read property 'category' of undefined
TypeError: Cannot read property 'category' of undefined

what did i do wrong?

**Comment by readelobdill** [comment]
Hey there,

Does this library currently support `headings` parameter as outlined in OneSignal create notification documentation?
