### ISSUE TITLE
provide call back after send tag, send tags, delete tag 

### ISSUE THREAD

**Issue by omarDtp** [OneSignal/react-native-onesignal#1005]
**Description:**

please its very confusing when you are using subscribed indicators when you cannot recieve call back if subscribed to tag in one signal
(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Howdy,
Thanks for the request. We will implement this in the next major release of the SDK. Cheers
