### ISSUE TITLE
Do not show notification if certain screen is active

### ISSUE THREAD

**Issue by rcstanciu** [OneSignal/react-native-onesignal#1008]
**Description:**
I have developed a chat system on RN and I'm looking to sending push notifications on each message, like any other chat application does (I'm currently using OneSignal but can switch to basic Firebase if necessary). 

I would like to show the push notifications at any time, even when the user is in app, but hide it **only** when the user is in the same chat room as the message that the push notification was sent for. 

Any ideas here on how I might do that?

**Environment**
React Native 0.62.2
react-native-onesignal 3.7.3
OS: Both Android and iOS

**Comment by rgomezp** [comment]
Howdy,
Good question. This is something we will be providing with our next major release of the SDK.

In the meantime you will have to use native code to handle this by customizing the Android NSE and the iOS `UNNotificattionCenterDelegate`. Cheers.

Enjoy!
