### ISSUE TITLE
InAppMessageClickHandler action inconsistency between iOS and Android

### ISSUE THREAD

**Issue by carloscuesta** [OneSignal/react-native-onesignal#1012]
**Description:**

I'm adding support of deeplinking through In-App Messages

As explained in the docs this could be easily done using the [InAppMessageClickHandler](https://documentation.onesignal.com/docs/sdk-reference#inappmessageclickhandler-handler)

![Screenshot 2020-06-29 at 17 49 35](https://user-images.githubusercontent.com/7629661/86027384-ecaa4600-ba30-11ea-9c22-4965c81ad455.png)

I don't know if this has been fixed on newer versions of the Native SDKs (since I'm using the 3.6.4 version of the library)

However I found that the action that comes to the callback of the addEventListener has different naming conventions on iOS and Android, see:

**iOS**

![Screenshot 2020-06-29 at 17 43 56](https://user-images.githubusercontent.com/7629661/86027999-a6a1b200-ba31-11ea-9d81-5b75a67e26e5.png)

**Android**

![Screenshot 2020-06-29 at 17 33 51](https://user-images.githubusercontent.com/7629661/86027731-5b879f00-ba31-11ea-8bdb-acd34f667fae.png)

**Environment**

* react-native-onesignal: `3.6.4`

Thanks!

**Comment by rgomezp** [comment]
Howdy,
Thank you for bringing this up. We will make it consistent across both platforms.

**Comment by carloscuesta** [comment]
Hey @rgomezp  I'm a little bit confused I want to upgrade the `react-native-onesignal` package and the iOS underneath but I don't know if this issue was addressed. I could see on the iOS release notes that this has been fixed but the PR #1013 is still open ?

**Comment by rgomezp** [comment]
Howdy,
Yeah so we still have to merge the PR in this repository as well. We will get this fix in before the next release.

**Comment by rgomezp** [comment]
Howdy,
This was merged and released. Thanks for your patience.

Enjoy!
