### ISSUE TITLE
[iOS] Notification does not deeplink when app is in closed state

### ISSUE THREAD

**Issue by stu-dev** [OneSignal/react-native-onesignal#1016]
**Description:**

Apologies in advance for not following proper issue-reporting procedures. I had previously commented on another [issue](https://github.com/OneSignal/react-native-onesignal/issues/977) but I'm guessing contributors aren't notified on closed issues.

Below is a matrix to help describe my issue:

```
                                     Android | iOS
              Deep link (app in bg):    ✅   |  ✅
             Deep link (app closed):    ✅   |  ✅
 Notification Deep link (app in bg):    ✅   |  ✅
Notification Deep link (app closed):    ✅   |  ❌

```

`Linking.getInitialURL()` returns `undefined` only when deep linking on iOS from a onesignal push alert in an app-closed state. (Returns a value for all other scenarios)

I'm no iOS developer so I wouldn't know where to start but is there not some native code that could solve this? Adding a listener in the JS seems like an unnecessary/hacky solution when it's only needed to solve 1 in 4 onesignal deep link scenarios.

**Environment**

```
"react-native": "0.62.2",
"react-native-onesignal": "3.8.1"
```

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience.

Take a look at [this thread](https://github.com/facebook/react-native/issues/24429) for a workaround on this issue. Hopefully RN resolves this soon.

Cheers

**Comment by ghost** [comment]
I'm not sure where the problem is, but when I try to open my app via `xcrun` it works properly. In other way when I try it from a Push Notification it doesn't.

> xcrun simctl openurl booted "app://deeplink.url"

@stu-dev Did you find out how to fix it?

**Comment by rgomezp** [comment]
Howdy, 
I will close this issue in this repository since it is not a OneSignal-related problem. Please continue tracking the issue in the above linked thread. 

Thank you

**Comment by ghost** [comment]
I'm not a 100% sure about that @rgomezp. Because when I use `xcrun` to run my closed app with a link, it works perfectly.

**Comment by ghost** [comment]
Any news on this?

**Comment by rgomezp** [comment]
Howdy @emilioheinz ,
If this is indeed a OneSignal problem, it may be fixed by a small change that we recently made to the way the notification open handler works. It will be included in the next major-release version of the SDK. If you could please test your issue with that version when it is released that would be great.

Take a look at our mobile [SDK migration guides](https://documentation.onesignal.com/docs/mobile-2020-api-migration-guide) for more info.

Thank you for your patience and cooperation.

**Comment by ghost** [comment]
Ok, I will do so. Have you any expectation about when the next major-release version of the SDK will be available?

**Comment by tomwhale** [comment]
Hi all, Is there an update on this issue? Surely having deep linking working is quite a major part of OneSignal's offering?

**Comment by ghost** [comment]
@tomwhale I'm not sure if it is an OneSignal or React Native bug. Do you have any idea?

**Comment by stu-dev** [comment]
Yep it definitely is, prior to #1140 being "resolved" deep linking was working fine in all cases (but you had an alert that popped up asking you to "Open website" which is not ideal).

Then #1140 was fixed but this resulted in a regression of the deep linking (now no longer works from closed state). So now we are back to where we started.

Edit: if you read the SDK issue that this started in (https://github.com/OneSignal/OneSignal-iOS-SDK/issues/777) it seems clear that there has been a miscommunication between the issue from a RN perspective vs a native iOS perspective. The iOS devs wanted the "Open website" functionality removed (including auto deeplinking) so they could handle it manually themselves. Whereas the RN issue just wanted it to skip the "Open website" and auto-deeplink.

**Comment by azai91** [comment]
Any update on this issue?

**Comment by dzpt** [comment]
Any update, notification deeplink doesn't work

**Comment by canpoyrazoglu** [comment]
Yup, this bug is preventing from us from going into production (as we use deeplinks in pushes to launch in-app chat and that confirmation dialog is bummer). Any updates at least on what causes it so that we can try to find a workaround/manually patch until an official fix is released?

**Comment by marclester-tang** [comment]
Same issue with flutter's sdk on deep linking

**Comment by rgomezp** [comment]
Please update to version 4.0.6

Enjoy!

**Comment by canpoyrazoglu** [comment]
Tried. I confirm that it's fixed on 4.0.6. Thank you!

**Comment by rgomezp** [comment]
For visibility: related workaround for deep linking problems - https://documentation.onesignal.com/docs/react-native-sdk#setnotificationopenedhandler-function

**Comment by oliviercperrier** [comment]
Im getting this same error using Expo SDK 51 with expo router.
