### ISSUE TITLE
Required react native plugin 'invariant' missing

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/react-native-onesignal#102]
The `invariant` plugin is required by this plugin but it isn't included a dependency or noted in the documentation.

**Comment by avishayil** [comment]
Good catch.

**Comment by avishayil** [comment]
https://github.com/geektimecoil/react-native-onesignal/tree/dev

**Comment by avishayil** [comment]
https://github.com/geektimecoil/react-native-onesignal/blob/27687efeed5fe6322c859c2834edfc74280edb9b/package.json#L10

**Comment by vinceprofeta** [comment]
@avishayil is there a plan to push a release with this?
