### ISSUE TITLE
Doesn't work with HMS

### ISSUE THREAD

**Issue by YozhikM** [OneSignal/react-native-onesignal#1020]
**Description:**

We use your library to work with push notifications. Now we are developing an app for Huawei with HMS. You recently updated the SDK, but the push did not work. We see an error in the admin panel.

There was an attempt to use [this method](https://documentation.onesignal.com/docs/huawei-sdk-setup), but the required class is not imported from `com.onesignal`.

![Example](https://i.gyazo.com/4be471f8e9e4229176b15d81301a4ef2.png)

We use other OneSignal ID for an app version for Huawei.

**Environment**

```
"react-native": "0.61.5",
"react-native-onesignal": "3.9.0"
```

**Steps to Reproduce Issue:**

1. Install latest RNOnesignal
2. Run on Huawei device with HMS
3. Attempt to receive push token etc.

**Anything else:**

[Huawei Docs](https://developer.huawei.com/consumer/en/codelab/HMSPushKit/index.html#4)

**Comment by rgomezp** [comment]
Howdy,
What is the method exactly you are trying to use? I think the link you included is not what you wanted to put.

Please also double check you followed our React-Native specific Huawei [setup documentation](https://documentation.onesignal.com/docs/huawei-react-native-sdk-setup).

Thank you!

**Comment by rgomezp** [comment]
Closing due to no response
