### ISSUE TITLE
[iOS] `opened` does not fire unless clicking on the notification

### ISSUE THREAD

**Issue by mcgomez** [OneSignal/react-native-onesignal#1026]
**Description:**

`received` fires when the application is in the foreground, `opened` only fires when the notification has been selected. Should `opened` fire when the application has been brought back to the foreground (either from in the background or from the closed state)?

**Environment**

`react-native-onesignal`: 3.9.0; using `npm` and pods

**Steps to Reproduce Issue:**

_Note: followed installation steps, and set up the OneSignal extension_

1. Set up listeners in `App.js` using hooks
```js
useEffect(() => {
    setupRootStore().then(trunk => {
      trunk.init().then(() => {
        setRootStore(trunk.store)

        OneSignal.setLogLevel(6, 0)
        OneSignal.init(ONESIGNAL_APP_ID, {
          kOSSettingsKeyAutoPrompt: false,
        })
        OneSignal.inFocusDisplaying(2)

        // Configure Push Notifications here to ensure the code is reachable
        OneSignal.addEventListener("received", onNotificationReceived)
        OneSignal.addEventListener("opened", onNotificationOpened)
        console.log("*** OneSignal event listeners added")
      })
    })

    return () => {
      OneSignal.removeEventListener("received", onNotificationReceived)
      OneSignal.removeEventListener("opened", onNotificationOpened)
      console.log("*** OneSignal event listeners removed")
    }
  }, [])
```
2. Launch application
3. I can see logs in xcode showing OneSignal has been initialized
```
2020-07-27 15:08:02.183675-0400 VCheck24[746:175368] WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead
2020-07-27 15:08:11.075979-0400 VCheck24[746:175368] VERBOSE: HTTP Request (OSRequestGetIosParams) with URL: https://api.onesignal.com/apps/f3319cf0-2b34-4835-a8d7-bccf1edec428/ios_params.js?player_id=66a6200d-7b61-43c9-bcfb-96ff99b844b8, with parameters: {
2020-07-27 15:08:11.079191-0400 VCheck24[746:175368] WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead
2020-07-27 15:08:11.143215-0400 VCheck24[746:175368] VERBOSE: oneSignalDidRegisterForRemoteNotifications:deviceToken:
```
4. Send a push notification using the OneSignal console
5. Receive the push notification with the application in the background (or forced closed)
6. Launch the application (but **not** by clicking the notification)
7. `opened` does not fire

Logs after receiving the notification:
```
2020-07-27 15:12:26.097855-0400 VCheck24[746:175368] VERBOSE: oneSignalApplicationWillResignActive
2020-07-27 15:12:26.141654-0400 VCheck24[746:175898] VERBOSE: HTTP Request (OSRequestOnFocus) with URL: https://api.onesignal.com/players/66a6200d-7b61-43c9-bcfb-96ff99b844b8/on_focus, with parameters: {
2020-07-27 15:12:26.710823-0400 VCheck24[746:175368] VERBOSE: oneSignalApplicationDidEnterBackground
```
Logs after opening the application (**not** by clicking on the notification)
```
2020-07-27 15:13:31.783363-0400 VCheck24[746:175368] VERBOSE: oneSignalApplicationDidBecomeActive
2020-07-27 15:13:31.792224-0400 VCheck24[746:176321] DEBUG: OneSignal SessionManager restartSessionIfNeeded with entryAction:: 1 channelTrackers: (
2020-07-27 15:13:31.794255-0400 VCheck24[746:176321] DEBUG: OneSignal SessionManager restartSessionIfNeeded lastIds: (
2020-07-27 15:13:31.818703-0400 VCheck24[746:176321] DEBUG: OneSignal SessionManager restartSessionIfNeeded lastIds: (
2020-07-27 15:13:31.819206-0400 VCheck24[746:176321] DEBUG: OneSignal SessionManager sendSessionEndingWithInfluences with influences: (
.901905-0400 VCheck24[746:176321] VERBOSE: Calling OneSignal create/on_session
7-27 15:13:31.914757-0400 VCheck24[746:176321] VERBOSE: HTTP Request (OSRequestRegisterUser) with URL: https://api.onesignal.com/players/66a6200d-7b61-43c9-bcfb-96ff99b844b8/on_session, with parameters: {
```

**Anything else:**

Maybe I'm misunderstanding the listeners. From my understanding `received` only fires when the application is in the _foreground_. Is there a listener that can be used when the notification was received, application is in the background OR forced-closed, and the user opens the application normally (not by clicking on the notification).

**Comment by rgomezp** [comment]
Howdy,
This is the expected behavior.

Take a look at the table below ([src](https://documentation.onesignal.com/docs/react-native-sdk#handling-notifications)):
| Event               | Description                                              |
|---------------------|----------------------------------------------------------|
| received            | Fires when a notification is received in the foreground. |
| opened              | Fires when a notification is opened (tapped)             |
| ids                 | Fires when ids are available                             |
| inAppMessageClicked | Fires when In-App message action                         |

In terms of the other receiver you are asking about, that sounds like you wouldn't even need a receiver but rather just take an action on app load. Or perhaps providing the specific use case would be valuable context. Alternatively, you can use the `ids` event which will fire automatically with OneSignal initialization.

Or perhaps you're asking about silent or background notifications? If so, take a look at our [documentation here](https://documentation.onesignal.com/docs/data-notifications).

Thanks again.

Enjoy!

**Comment by mcgomez** [comment]
@rgomezp So my use case is that when a notification is received, I need to add an object to an array stored in mobx. So if the user receives the notification, but doesn't open the application via the notification, I still need to log that they in fact _received_ the notification. This works fine if the application is in the foreground because I can use `recieved`, but doesn't work well if the application is in the background or closed.

**Comment by rgomezp** [comment]
Okay. Indeed, it sounds like you should use Background Notifications for this (see link above). However, note that you cannot wake Android apps that have been forced quit.

**Comment by mcgomez** [comment]
@rgomezp Thanks for the direction!

I have tested (on iOS) using the `content_available` param and it seems like it does what I'd expect when the application is in the background but launched normally (not by clicking on the notification). However, it doesn't seem to be firing any listeners when the app has been swiped away. Is it still the case that this is not supported as stated in https://github.com/OneSignal/react-native-onesignal/issues/982#issuecomment-612186767? 

It states in the docs ([data-notifications#app-states-in-ios-vs-android](https://documentation.onesignal.com/docs/data-notifications#app-states-in-ios-vs-android)):
> Background notifications can wake an iOS and Android app that has been "swiped away" on the device. However, background notifications can not wake Android apps that have been forced-quitted in the app settings.

Here are the logs received when sending a notification while the application is in the background with `content_available`
<details><summary>iOS logs</summary>

```
default	13:13:17.978086-0400	VCheck24	VERBOSE: Called init with app ID: f3319cf0-2b34-4835-a8d7-bccf1edec428
default	13:13:17.980216-0400	VCheck24	VERBOSE: HTTP Request (OSRequestUpdateExternalUserId) with URL: https://api.onesignal.com/players/97a2397f-700f-48cb-a856-6be4d21ec36d, with parameters: {
  "app_id" : "f3319cf0-2b34-4835-a8d7-bccf1edec428",
  "external_user_id" : ""
}
default	13:13:17.985837-0400	VCheck24	VERBOSE: HTTP Request (OSRequestGetIosParams) with URL: https://api.onesignal.com/apps/f3319cf0-2b34-4835-a8d7-bccf1edec428/ios_params.js?player_id=97a2397f-700f-48cb-a856-6be4d21ec36d, with parameters: {
  "player_id" : "97a2397f-700f-48cb-a856-6be4d21ec36d"
}
default	13:13:17.987365-0400	VCheck24	VERBOSE: registerForPushNotifications Called:waitingForApnsResponse: 0
default	13:13:17.992043-0400	VCheck24	VERBOSE: Firing registerForRemoteNotifications
default	13:13:18.000137-0400	VCheck24	VERBOSE: updateNotificationTypes called: 15
default	13:13:18.013833-0400	VCheck24	VERBOSE: startedRegister: 1
default	13:13:18.014946-0400	VCheck24	VERBOSE: getNotificationTypes:mSubscriptionStatus: -1
default	13:13:18.015568-0400	VCheck24	VERBOSE: getNotificationTypes:mSubscriptionStatus: -1
default	13:13:18.020570-0400	VCheck24	VERBOSE: oneSignalDidRegisterForRemoteNotifications:deviceToken:
default	13:13:18.021522-0400	VCheck24	VERBOSE: updateDeviceToken:onSuccess:onFailure:
default	13:13:18.310142-0400	VCheck24	VERBOSE: network response (OSRequestUpdateExternalUserId): {
    success = 1;
}
default	13:13:18.378993-0400	VCheck24	VERBOSE: Set external user id complete
default	13:13:18.435146-0400	VCheck24	VERBOSE: network response (OSRequestGetIosParams): {
    outcomes =     {
        direct =         {
            enabled = 0;
        };
        indirect =         {
            enabled = 0;
            "notification_attribution" =             {
                limit = 10;
                "minutes_since_displayed" = 60;
            };
        };
        unattributed =         {
            enabled = 0;
        };
    };
    "receive_receipts_enable" = 1;
    "uses_provisional_auth" = 0;
}
default	13:14:48.515960-0400	VCheck24	VERBOSE: oneSignalApplicationWillResignActive
default	13:14:49.317495-0400	VCheck24	VERBOSE: HTTP Request (OSRequestOnFocus) with URL: https://api.onesignal.com/players/97a2397f-700f-48cb-a856-6be4d21ec36d/on_focus, with parameters: {
  "net_type" : 0,
  "active_time" : 92.16203498840332,
  "state" : "ping",
  "app_id" : "f3319cf0-2b34-4835-a8d7-bccf1edec428",
  "type" : 1,
  "device_type" : 0
}
default	13:14:49.670375-0400	VCheck24	VERBOSE: network response (OSRequestOnFocus): {
    id = "97a2397f-700f-48cb-a856-6be4d21ec36d";
    success = 1;
}
default	13:14:49.720736-0400	VCheck24	VERBOSE: oneSignalApplicationDidEnterBackground
default	13:15:17.632261-0400	VCheck24	VERBOSE: oneSignalRemoteSilentNotification:UserInfo:fetchCompletionHandler:
default	13:15:17.647496-0400	VCheck24	VERBOSE: handleNotificationReceived lastMessageID: c0a42d5f-b83b-42fb-8c31-5fe4a079a101 displayType: 2

```

</details>


When I try and send a notification to the device after it has been swiped away, I receive the notification, but I don't think any listeners are called. 

Here are the logs received when sending a notification while the application has been swiped away with `content_available`, and the app has been launched normally
<details><summary>iOS logs</summary>

```
default	13:21:28.860541-0400	VCheck24	VERBOSE: Called init with app ID: f3319cf0-2b34-4835-a8d7-bccf1edec428
default	13:21:28.861984-0400	VCheck24	VERBOSE: HTTP Request (OSRequestUpdateExternalUserId) with URL: https://api.onesignal.com/players/97a2397f-700f-48cb-a856-6be4d21ec36d, with parameters: {
  "app_id" : "f3319cf0-2b34-4835-a8d7-bccf1edec428",
  "external_user_id" : ""
}
default	13:21:28.868335-0400	VCheck24	VERBOSE: HTTP Request (OSRequestGetIosParams) with URL: https://api.onesignal.com/apps/f3319cf0-2b34-4835-a8d7-bccf1edec428/ios_params.js?player_id=97a2397f-700f-48cb-a856-6be4d21ec36d, with parameters: {
  "player_id" : "97a2397f-700f-48cb-a856-6be4d21ec36d"
}
default	13:21:28.869139-0400	VCheck24	VERBOSE: registerForPushNotifications Called:waitingForApnsResponse: 0
default	13:21:28.870477-0400	VCheck24	VERBOSE: Firing registerForRemoteNotifications
default	13:21:28.878106-0400	VCheck24	VERBOSE: updateNotificationTypes called: 15
default	13:21:28.879699-0400	VCheck24	VERBOSE: startedRegister: 1
default	13:21:28.880023-0400	VCheck24	VERBOSE: getNotificationTypes:mSubscriptionStatus: -1
default	13:21:28.880531-0400	VCheck24	VERBOSE: getNotificationTypes:mSubscriptionStatus: -1
default	13:21:29.023034-0400	VCheck24	VERBOSE: oneSignalDidRegisterForRemoteNotifications:deviceToken:
default	13:21:29.030170-0400	VCheck24	VERBOSE: updateDeviceToken:onSuccess:onFailure:
default	13:21:29.080617-0400	VCheck24	VERBOSE: network response (OSRequestUpdateExternalUserId): {
    success = 1;
}
default	13:21:29.096770-0400	VCheck24	VERBOSE: Set external user id complete
default	13:21:29.126950-0400	VCheck24	VERBOSE: network response (OSRequestGetIosParams): {
    outcomes =     {
        direct =         {
            enabled = 0;
        };
        indirect =         {
            enabled = 0;
            "notification_attribution" =             {
                limit = 10;
                "minutes_since_displayed" = 60;
            };
        };
        unattributed =         {
            enabled = 0;
        };
    };
    "receive_receipts_enable" = 1;
    "uses_provisional_auth" = 0;
}
```

</details>

**Comment by mcgomez** [comment]
@rgomezp Have you had a chance to look at this?

**Comment by rgomezp** [comment]
@mcgomez ,
Howdy.

> Is it still the case that this is not supported as stated in #982 (comment)?

Yes this is still the case. To clarify, the `onReceived` React Native OneSignal event (and any other event listeners) only applies to notifications while the app is **in focus**. Getting a background notification can be handled natively via the `UNNotificationServiceExtension.didReceive` [method](https://developer.apple.com/documentation/usernotifications/unnotificationserviceextension) so if you choose to go this route be prepared to write some native code!

I hope this helps.

Enjoy!

**Comment by rgomezp** [comment]
@mcgomez ,
Can I go ahead and close out this issue?

**Comment by mcgomez** [comment]
Yes, thank you for the help!

**Comment by rukmanary** [comment]
> @mcgomez ,
> Howdy.
> 
> > Is it still the case that this is not supported as stated in #982 (comment)?
> 
> Yes this is still the case. To clarify, the `onReceived` React Native OneSignal event (and any other event listeners) only applies to notifications while the app is **in focus**. Getting a background notification can be handled natively via the `UNNotificationServiceExtension.didReceive` [method](https://developer.apple.com/documentation/usernotifications/unnotificationserviceextension) so if you choose to go this route be prepared to write some native code!
> 
> I hope this helps.
> 
> Enjoy!

Can you help me with an example on how to do it please? I am not sure the proper way to do it because I don't have any experience on writing native code yet...
