### ISSUE TITLE
Execution failed for task ':react-native-onesignal:processDebugAndroidTestManifest'.

### ISSUE THREAD

**Issue by LaureneFmy** [OneSignal/react-native-onesignal#1027]
**Description:**
I'm facing an issue for few days now when syncing my Android project.
This is an old project and I can't upgrade React Native without breaking it.
The project is running with the 'react-native run-android' command on a physical device but I need the emulator on Android Studio.
I already tried all solutions in this issue : https://github.com/OneSignal/react-native-onesignal/issues/541

**Environment**

"react-native": "0.59.4"
"react-native-onesignal": "3.2.14"

**Comment by rgomezp** [comment]
Howdy,
Thank you for your patience. Please follow our issue template and provide the full details or consider reaching out through our official support channel at OneSignal.com for faster support. Thank you.
