### ISSUE TITLE
Delay .init call possible to avoid Google Play test devices?

### ISSUE THREAD

**Issue by fritzfr** [OneSignal/react-native-onesignal#1030]
**Description:**
I am wondering if it is possible to delay the `.init` call as long as the user is not authenticated (logged in).
The reason is that uploading an app to Google Play Store makes Google test your app on many many devices, and they seem to appear in my OneSignal user list. This is probably because in my top level React Native component, I have the `.init` call.

I tried moving it but I am getting many errors when trying to init later.

**Environment**
1. What version of the OneSignal React-Native SDK are you using? -> 3.9.0
2. How did you add the SDK to your project: npm

**Comment by rgomezp** [comment]
Howdy,
We recommend always initializing OneSignal very first thing specifically because there may be some side effects from doing it after. 

One thing you can do is use the SDK to add an external id to the player/user as soon as they do log in. Or even an email. You can find out more about these functions in our React Native documentation.

Can I ask, why is it a problem with the Google devices appearing for you as OneSignal players?

**Comment by fritzfr** [comment]
@rgomezp 

>One thing you can do is use the SDK to add an external id to the player/user as soon as they do log in. Or even an email. You can find out more about these functions in our React Native documentation.

I am doing that already.

>Can I ask, why is it a problem with the Google devices appearing for you as OneSignal players?

It just seems like a lot of noise in the One Signal Dashboard, having tons of essentially empty/meaningless users in the audience. Makes it difficult to find relevant users, makes it difficult to combine One Signal Audience data via the One Signal REST API with our own backend (as you only allow a maximum of 300 users returned in one call). Confuses non-developers as they don't get what's going on.

**Comment by rgomezp** [comment]
@fritzfr ,
Although it is generally discouraged, you can initialize after the user logs in and then only also call it each time the app is started after that. The reason we don't recommend is it can sometimes lead to unwanted side-effects. 

The noise you're describing would be high for a just released / low number of users app. As your users grow, the device count will inevitably get lower as a proportion and shouldn't be a disturbance to the non technical team members.

Thank you for your patience and I hope that answered your question.

Enjoy using OneSignal!
