### ISSUE TITLE
Received duplicated notification when app is in killed state

### ISSUE THREAD

**Issue by theodorusyoga** [OneSignal/react-native-onesignal#1033]
**Description:**
Received two duplicated notifications when is in killed state

**Environment**
1. React-Native SDK version 3.9.0

**Steps to Reproduce Issue:**

1. Kill the app
2. I am using this endpoint for creating notification: 
`https://onesignal.com/api/v1/notifications`

Example payload:
```
{
    "app_id": "0dbbd81f-f80d-4374-89ee-b32a422cb0f3",
    "external_id": "0dbce81f-f81e-43c5-75ce-b21a965cbfb5",
    "contents": {
        "id": "Anda telah berhasil transfer sebesar Rp 10.000.000"
    },
    "headings": {
        "id": "Transfer sukses!"
    },
    "include_player_ids": [
        "53d3b722-3690-4770-93eb-fe48eb1708c5"
    ],
    "android_channel_id": "8be199be-08ff-49ee-a9fc-870ae89eda74"
}
```
3. Result:
I received two notifications, one from the correct channel and one from the mistakenly created channel. I looked through the app notification settings, there was "Channel Name" under "Other" category. 

I looked everywhere but I didn't find any clue. FYI, I'm using `apply plugin: 'com.google.gms.google-services'` under my `app/build.gradle` and copied `google-services.json` to `android/app` folder.

Screenshots:

1. Duplicated notifications:
![Screenshot_20200817-224905](https://user-images.githubusercontent.com/4055424/90416647-f2d9ac00-e0dc-11ea-8bf4-e3f36008ee10.png)

2. Mistakenly created "Channel Name" under "Other" category
![Screenshot_20200817-225307](https://user-images.githubusercontent.com/4055424/90416690-fff69b00-e0dc-11ea-9576-bff2417f66d3.png)

Any help would be appreciated! Thank you

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience.

**Edit:** it looks like another SDK/library in the app is also displaying our notification payload.

The most common symptom of this is only display the correct title but without the body as well as the wrong notification icon.

Also other features such as adding buttons and images will only show one but not the other if you added them to the notification.

To resolve:
1. Remove the other library / SDK displaying notifications
2. If you need to keep it, then disable the notification / push part
3. If you need to keep the other push SDK, then look for that vendors docs on filtering or report the issue to them

Hope this helps. Cheers and Enjoy!
