### ISSUE TITLE
Id Doesnt Trigger on IOS

### ISSUE THREAD

**Issue by yusufsal** [OneSignal/react-native-onesignal#1035]
Hi everyone,
My OneSignal implementation doesn't work on "some" IOS devices and i can not see in my dashboard these devices.

Thanks and Regards.

My implementation like below;

    OneSignal.init(ONESIGNAL_APP_ID);
    OneSignal.enableSound(true);
    OneSignal.enableVibrate(true);
    OneSignal.configure();
    OneSignal.requestPermissions({ alert: true, badge: true, sound: true });
    OneSignal.registerForPushNotifications();
    OneSignal.inFocusDisplaying(2);
    OneSignal.addEventListener('received', this.onReceived);
    OneSignal.addEventListener('opened', this.onOpened);
    OneSignal.addEventListener('ids', this.onIds);

**Comment by rgomezp** [comment]
Hello, 
Please follow our full issue template and provide full details so that we can better assist you including verbose logs. The above information is not enough for us to be able to narrow the issue down.

Cheers
