### ISSUE TITLE
Consent not withdrawn correctly

### ISSUE THREAD

**Issue by smn-snkl** [OneSignal/react-native-onesignal#1037]
**Description:**
On iOS, when we set `OneSignal.provideUserConsent(false)` the SDK stops executing any calls. However, if we then close our app and start it again, the `api.onesignal.com/players` call is triggered right away. When logging `OneSignal..userProvidedPrivacyConsent()` it still shows `0`. But it still triggered an API call with the Player ID which should not happen if you want to be compliant with GDPR.

**Environment**

1. What version of the OneSignal React-Native SDK are you using?
3.9.0
1. How did you add the SDK to your project (eg. npm)
yarn

**Steps to Reproduce Issue:**

1. Install the OneSignal SDK using yarn into your project
1. Setup project according to [docs](https://documentation.onesignal.com/docs/react-native-sdk-setup)
1. Initialize SDK with

```
OneSignal.provideUserConsent(true);
OneSignal.setRequiresUserPrivacyConsent(true);
OneSignal.init(ONE_SIGNAL_KEY, {
  kOSSettingsKeyAutoPrompt: false,
  kOSSettingsKeyInAppLaunchURL: true,
  kOSSettingsKeyInFocusDisplayOption: 2
});
```

1. Start app and set `OneSignal.provideUserConsent(false)`. You can even log `OneSignal..userProvidedPrivacyConsent()` to make sure it is equal to `0`
1. Close and restart app. It will trigger an API call to `api.onesignal.com/players`

**Anything else:**

I would expect the SDK not to fire any events at all, not even during app start. Right now, it's not possible to implement a GDPR-compliant process as the SDK keeps sending information after the user revoked consent.

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience. Firstly, please make sure to always test the latest release. In this case, that is 3.9.1.

Secondly, are you seeing this issue on Android or iOS or both?

Lastly, what player related function (e.g: `sendTag`) are you calling that is resulting in the call being made? I don't see anything else in the code you provided. If you _aren't_ calling any other function, the request you are seeing might be our "on session" call. Can you please confirm where this call is coming from?

**Comment by rgomezp** [comment]
Closing due to no response.
