### ISSUE TITLE
Soft Prompt doesn't show after first time, getPermissionSubscriptionState issues

### ISSUE THREAD

**Issue by rollsroyc3** [OneSignal/react-native-onesignal#1038]
**Description:**

I have recently integrated the OneSignal React Native SDK into my project, and decided to use the soft prompt for iOS. I followed the [tutorial](https://documentation.onesignal.com/docs/ios-push-opt-in-prompt) and added 2 buttons (Allow Notifications and Maybe Later). I then added the following code to my project to show the soft prompt:

```
OneSignal.getPermissionSubscriptionState((status) => {
    if status.permissionStatus.hasPrompted == false {
      OneSignal.addTrigger("prompt_ios", "true");
    }
});
 ```

2 issues I found 

1.  The permissionStatus does not exist, and I get a `Undefined is not an object` error. When logging the status variable I get the following:

`{"emailAddress": null, "emailSubscribed": false, "emailUserId": null, "hasPrompted": false, "notificationsEnabled": false, "pushToken": null, "subscriptionEnabled": false, "userId": "XX-XX-XX-XX", "userSubscriptionEnabled": true}`

So I guess I'm supposed to be using hasPrompted?

2. If I follow the logic from the walkthrough, and they click `Maybe Later`, the hasPrompted remains false, but upon closing and reopening my app, I do not get the soft prompt again.

My Trigger is set to show forever and also `Every time trigger conditions are satisfied`

**Environment**
1. Using RN 3.9.1
2. Installed using yarn, but then had to link.

Here is the code I am currently using:

```
// App.js
OneSignal.setLogLevel(6, 0);
OneSignal.init('a1ad306b-9a50-40e6-86c1-632a5832ff70', {
      kOSSettingsKeyAutoPrompt: false,
      kOSSettingsKeyInAppLaunchURL: false,
      kOSSettingsKeyInFocusDisplayOption: 2,
    });
OneSignal.inFocusDisplaying(2);

// Home.js - constructor
OneSignal.addEventListener('received', this.onReceived);
    OneSignal.addEventListener('opened', this.onOpened);
    OneSignal.addEventListener('ids', this.onIds);

    if (Platform.OS === 'ios') {
      OneSignal.getPermissionSubscriptionState((status) => {
        console.log('status', status);
        if (status.hasPrompted == false) {
        //if (status.permissionStatus.hasPrompted == false) {
          OneSignal.addTrigger('prompt_ios', 'true');
        }
      });
    }


```

**Comment by rollsroyc3** [comment]
After more testing it seems that when I open the app for the first time from Testflight, it shows every time I go to the Home screen, so if I switch to a different stack then come back to Home, it shows as it should. But when I force close the app, then reopen it, I don't get the notification anymore..

**Comment by rollsroyc3** [comment]
OK, figured out the issue. 

It seems I was setting that trigger before OneSignal had a chance to complete the init process. I added a timeout of 10 seconds to test and it worked every time.

**Comment by rohitkum28** [comment]
@rollsroyc3 Can you post your solution here? Also, is there any better way because adding a timer is not a good solution.
