### ISSUE TITLE
PushToken always null in Android real device

### ISSUE THREAD

**Issue by drop0118** [OneSignal/react-native-onesignal#1039]
I can get "userId" in "onIds" function but the "pushToken" is always null.

**Environment**
React Native 0.63.2
react-native-onesignal 3.9.1

Here is my "bundle.gradle"
![image](https://user-images.githubusercontent.com/3488084/92704332-76f21d00-f385-11ea-841a-e7fdd9ef0bb3.png)

Here is my "app/bundle.gradle"
![image](https://user-images.githubusercontent.com/3488084/92704448-8a04ed00-f385-11ea-9b83-1ab39e4ebe46.png)

Here is the code in App.js
![image](https://user-images.githubusercontent.com/3488084/92704635-a7d25200-f385-11ea-8d7a-502156f16344.png)

I just got this debug infomation:
Device info:  {"pushToken": null, "userId": "3609a038-1e9c-4b49-8eb4-6da2ce5c152c"}

**Comment by drop0118** [comment]
Anybody could help me?

**Comment by rgomezp** [comment]
Howdy,
Are you able to reproduce this also on iOS?

Also please provide us with a log with the [log level set to VERBOSE](https://documentation.onesignal.com/docs/sdk-reference#setloglevel-method).

Cheers

**Comment by drop0118** [comment]
> Howdy,
> Are you able to reproduce this also on iOS?
> 
> Also please provide us with a log with the [log level set to VERBOSE](https://documentation.onesignal.com/docs/sdk-reference#setloglevel-method).
> 
> Cheers

 @rgomezp  This working well on iOS.

**Comment by rgomezp** [comment]
Can you please provide a log?

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by serhiiharbo** [comment]
@drop0118 man did you find a solution? I've faced the same issue here, pushToken is null on Android real device

**Comment by mehmetdelikaya** [comment]
@drop0118 @serhiiharbo same issue
