### ISSUE TITLE
DeepLink with Firebase DynamicLink

### ISSUE THREAD

**Issue by vishnau31** [OneSignal/react-native-onesignal#1040]
When I attach a url in the notification created with Rest API, when I click on the notification, the browser opens up and then redirection to app is done. I am using FireBase DynamicLink for deep-linking, So is there a way to not go to the browser and directly go in to the app.

**Comment by rgomezp** [comment]
Howdy,
I'm not sure about how it would work with Firebase Dynamic Link but it is possible to deep link directly into the app. You can learn more about how to implement that [here](https://documentation.onesignal.com/docs/links).

Enjoy
