### ISSUE TITLE
react-native-onesignal not working on react-native 0.62 + 0.63

### ISSUE THREAD

**Issue by omars94** [OneSignal/react-native-onesignal#1041]
**Description:**

react-native-onesignal not working on react-native 0.62 or 0.63

tried installing v3.7.3
v3.8.1
v3.9.3
nothin is working

android log error Onesignal appid not valid uuid format while it is correct
ios log not showing anything and simulator not showing in onesignal audience
(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Howdy,
Unfortunately we cannot help you without more details. Please make sure you have followed [these steps](https://documentation.onesignal.com/docs/react-native-sdk-setup) carefully. For support regarding setup, please reach out through our official support channel at OneSignal.com.
