### ISSUE TITLE
Issue on Android 10 Users get unsubscribe after sending a notification

### ISSUE THREAD

**Issue by kanhrithfz** [OneSignal/react-native-onesignal#1045]
Description:

The test user's subscription appears as inactive after seding the first notification.

Environment

{ "react": "16.9.0","react-native": "0.61.5", "react-native-onesignal": "3.8.1" }

Steps to Reproduce Issue:

When I run my app on development or even generating the APK, my users has an active subscription, but after sending the first notification, the user's subscription appears inactive, and If I compile the application again it appears active again.

Noted : Issue on Android 10

**Comment by rgomezp** [comment]
Howdy,
Can you please include the full log? Make sure to set the [log level to VERBOSE.](https://documentation.onesignal.com/docs/sdk-reference#setloglevel-method)

**Comment by rgomezp** [comment]
Closing due to no response.
