### ISSUE TITLE
OneSignal.deleteTags doesn't exist

### ISSUE THREAD

**Issue by canpoyrazoglu** [OneSignal/react-native-onesignal#1047]
**Description:**
I'm trying to delete all the tags using the function documented here: 
https://documentation.onesignal.com/docs/sdk-reference#deletetags-method

However, I'm getting an error saying that `deleteTags` doesn't exist on `OneSignal`. The `.m` files contain the appropriate methods, however, the JS file doesn't contain that method.

**Environment**
React Native 0.63.2
react-native-onesignal: 3.9.0

**Steps to Reproduce Issue:**

1. Have OneSignal in your React Native iOS project
1. Initialize the SDK, have some tags associated with your device. (doesn't really matter as the JS method itself doesn't exist)
1. Call `OneSignal.deleteTags` to delete tags.

**Comment by rgomezp** [comment]
Howdy @canpoyrazoglu ,
Wow! Nice catch. It's hard to believe this had never come up previously. We will get this fixed in the next release. Apologies for the inconvenience.

In the meantime, you can use `deleteTag` repeatedly over the tags you wish to delete.

Cheers
