### ISSUE TITLE
Change language from react-native sdk

### ISSUE THREAD

**Issue by rohitkum28** [OneSignal/react-native-onesignal#1054]
**Description:**

I have a react-native application which gives the user an option to change the language of the application. This is in app and different from the locale of the phone. I want to update the preferred language of the user on onesignal too when this happens. Is there any way to do this from SDK?

**Environment**

"react-native-onesignal": "^3.9.1"
"react-native": "0.63.2"

**Comment by rgomezp** [comment]
Howdy,
Yes. You can do this in several ways. 

If you do not see the language you want to support on our list or you allow users to set their own language, then you will need to differentiate the users and target separately.

One option is to tag users with the language, then create segments by each tag. Then send notifications separately by adding the language to the "en" or English field.

If you track this data in your CRM or Database, you can target via our API as well. See Internal Database, DMP, & CRM.

You can read more [here](https://documentation.onesignal.com/docs/language-localization#how-do-i-use-a-different-language-than-the-device-settings).

Thank you for your question.

Enjoy!
