### ISSUE TITLE
Android notification produces 403 error modal when app is open - Cloudflare blocks api.onesignal.com

### ISSUE THREAD

**Issue by xeroxoid** [OneSignal/react-native-onesignal#1056]
**Description:**

Notification on Android while the app is open produces a modal that displays raw HTML and states that api.onesignal.com is not accessible because CloudFlare blocks it.

**Environment**

1. What version of the OneSignal React-Native SDK are you using?
"react-native-onesignal": "^3.9.1",
1. How did you add the SDK to your project (eg. npm)
yarn add react-native-onesignal
followed the installation steps

**Steps to Reproduce Issue:**

1. Open the app
1. Send a notification to the user via OneSignal test users

**Note**
Notifications worked fine for months now and also work fine in iOS. Also I saw [this issue](https://github.com/OneSignal/react-native-onesignal/issues/746) but I assume Greece is supported as a country (in the EU mind you :p)

The error is the one in the screenshot below:
![Screenshot!UNITO-UNDERSCORE!1602759923](https://user-images.githubusercontent.com/1199451/96115773-258efd80-0ef0-11eb-969f-372187c198ec.png)

**Comment by rgomezp** [comment]
Howdy,
Confirmed Deliveries / Receive Receipts are undergoing maintenance and will not be turned back on for a couple weeks.

If you are a free customer, this shouldn't impact you at all. Make sure that you don't have your `setLogLevel` (visual level) set to VERBOSE in a production environment ([documentation](https://documentation.onesignal.com/docs/sdk-reference#setloglevel-method)).

We apologize for the inconvenience. If you would like further assistance, please reach out via our official support channel at OneSignal.com.

Cheers.
