### ISSUE TITLE
gradle:4.0.2 - OK => gradle:4.1.0 => crashes on build

### ISSUE THREAD

**Issue by rares-lupascu** [OneSignal/react-native-onesignal#1063]
**Description:**

gradle:4.0.2 => all ok

gradle:4.1.0 => build crashes

**Environment**
"react-native": "^0.63.3",
"react-native-onesignal": "^3.9.2",

**Steps to Reproduce Issue:**

1. clean react native app
1. upgrade gradle to 4.1.0
1. install react-native-onesignal
1. compile

**Anything else:**

```
/android/app/src/main/AndroidManifest.xml Error:
        Attribute meta-data#onesignal_app_id@value at AndroidManifest.xml requires a placeholder substitution but no value for <onesignal_app_id> is provided.
/android/app/src/main/AndroidManifest.xml Error:
        Attribute meta-data#onesignal_google_project_number@value at AndroidManifest.xml requires a placeholder substitution but no value for <onesignal_google_project_number> is provided.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
```

* one other details is that I am using fastlane to deploy the app
* if u r trying to replicate use also Gradle Version: 6.7

**Comment by rgomezp** [comment]
Howdy,
What does your manifest file look like? If you are using react native, the `onesiganl_app_id` shouldn't even be in your AndroidManifest.xml. Was that something you added yourself?

If so, please take another look at the [React Native setup guide](https://documentation.onesignal.com/docs/react-native-sdk-setup) to confirm your setup steps.

Cheers

**Comment by rares-lupascu** [comment]
I had to add it otherwise it would not compile ... that is the bug
the error messages I pasted in the ticket happen when I do not add those fields in the Gradle file.

just FYI ... downgrading to 4.0.2 makes every error related to this go away

**Comment by rgomezp** [comment]
@rares-lupascu ,
Are you also using the [OneSignal Gradle Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin)?

**Comment by rares-lupascu** [comment]
yes 👍 
I keep telling u ... everything works if I downgrade ... if my setup was wrong I would have issues no matter if I downgrade or not :-)

**Comment by marcinkornek** [comment]
I have the same error after upgrading gradle:4.0.1 to gradle:4.1.0

**Comment by escobar022** [comment]
Same here, upgrading to 4.1 renders the same error. It's possible that 4.1 does not support this:



`
class DefaultManifestPlaceHolders {

    static final MANIFEST_PLACEHOLDERS_DEFAULTS = [
        onesignal_app_id: '',
        onesignal_google_project_number: 'REMOTE'
    ]

    static void addManifestToAppProject(Project proj) {
        def androidApp = proj.android
        MANIFEST_PLACEHOLDERS_DEFAULTS.each { defKey, defValue ->
            if (!androidApp.defaultConfig.manifestPlaceholders.containsKey(defKey)) {
                androidApp.defaultConfig.manifestPlaceholders[defKey] = defValue

                androidApp.buildTypes.each { buildType ->
                    if (!buildType.manifestPlaceholders.containsKey(defKey))
                        buildType.manifestPlaceholders[defKey] = defValue
                }
            }
        }
    }
}
`

**Comment by jkasten2** [comment]
@escobar022 The [block of groovy code you listed](https://github.com/OneSignal/react-native-onesignal/blob/master/android/build.gradle#L32-L68) should be properly filling in the required `onesignal_app_id` and `onesignal_google_project_number` manifest values as required by the OneSignal-Android-SDK 3.x.x branch this react-native-onesignal SDK uses. I don't know of any change to Gradle 4.1.0 that would have broken this.

Any other changes to your project other than going from gradle:4.0.1 to gradle:4.1.0? Same react native version, same `com.android.tools.build:gradle`, ect?

There are no more manifest placeholders with the onesignal-react-native 4.0.0 SDK that is currently in beta right now so this won't be an issue going forward.
See this issue on more details on using the beta and how to upgrade to it.
https://github.com/OneSignal/react-native-onesignal/issues/1079

A work around for the  onesignal-react-native 3.x.x branch of this SDK is you can add these manifest placeholder themselves to your `app/build.gradle`.
You need to add it under android > defaultConfig in it.
```gradle
android {
    // ... 
    defaultConfig {
        manifestPlaceholders = [
           onesignal_app_id: '', // Blank as this will be defined from your app's .ts / .js code at runtime.
           onesignal_google_project_number: 'REMOTE'
        ]
       
       // ... 
    }
}
```
Full example here from a native Android app for more context on where this goes.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.15.6/Examples/AndroidStudio/app/build.gradle#L25-L27

**Comment by rgomezp** [comment]
Closing due to no response.
