### ISSUE TITLE
How do I upgrade to beta 4.0

### ISSUE THREAD

**Issue by ghost** [OneSignal/react-native-onesignal#1068]
**Description:**

Instructions required for react native beta upgrade. As per docs, it's coming soon.

Please provide instruction on the JS side methods if changes.

**Steps to Reproduce Issue:**

1. Upgraded Android SDK as per new instructions
1. Upgraded onesignal react native to 4.0.0-beta.2
1. Gives error init method not found at js end

**Comment by rgomezp** [comment]
Howdy @crushy26 ,
Thank you for the question.

We are adding the migration guide to our public documentation very soon. For now, you can [take a look](https://documentation.onesignal.com/docs/react-native-40-api-reference) to start making changes, but please note that some of the parameter names are still being finalized.

We are looking for feedback so please don't hesitate to point out anything in the beta or the docs that you feel could be improved. Cheers.

Enjoy!
