### ISSUE TITLE
Best Practice for Login/Logout/Relog

### ISSUE THREAD

**Issue by fritzfr** [OneSignal/react-native-onesignal#1069]
Hey,

I was wondering about the best practices you would recommend for keeping the SDK in the know if the user logged out/relogged and logged in.
Currently, when loggin in, we ask the trigger the prompt and then we set the subscription:

Login:

```js
// first check if already prompted or already enabled
OneSignal.getPermissionSubscriptionState(({ notificationsEnabled, hasPrompted }) => {
	if (!notificationsEnabled && !hasPrompted) {
		askForPush();
	}
});

const askForPush = () => {
	OneSignal.promptForPushNotificationsWithUserResponse((accepted) => {
		OneSignal.setSubscription(accepted);
	});
}
```

Question 1: What should I call upon log out so that the user does not receive the pushes anymore?
Question 2: If a user logs out, and then logs in again, `notificationsEnabled` and `hasPrompted` will both be true, so how can I ask him again to enable it? What is the best practice here?

**Comment by rgomezp** [comment]
@fritzfr ,
Apologies for the delay.

**Question 1:**
Using the new Beta API, you will want to log out from your app as you normally would (nothing to do with OneSignal) and then to disable push, you can call `OneSignal.disablePush(true)`.

**Question 2:**
Simply call the opposite of the above: `OneSignal.disablePush(false)`

I noticed you are using `setSubscription`. Please note that this function is deprecated in the next release.

**Comment by rgomezp** [comment]
Closing due to no response
