### ISSUE TITLE
ios image media not show

### ISSUE THREAD

**Issue by yusfarhanchepa** [OneSignal/react-native-onesignal#1070]
<img width="673" alt="Screenshot 2020-10-27 at 10 30 51 AM" src="https://user-images.githubusercontent.com/23738500/97249771-7e8b5980-183f-11eb-83e4-c7f9e944a090.png">
Image not show in ios push notification onesignal. Already follow step by step..
Text are working fine. tested on ios 13.3  and 14.0.1

i also already build from scratch project. but still not working. image not show.
please help me.. thanks

Environemnt
react-native : 0.63.3
react-native-onesignal : 3.9.2
CocoPods : 1.10.0

#This is my pod file
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'SMEColony' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  target 'SMEColonyTests' do
    inherit! :complete
  end

  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end

target 'SMEColony-tvOS' do

  target 'SMEColony-tvOSTests' do
    inherit! :search_paths
  end
end

<img width="682" alt="Screenshot 2020-10-27 at 10 31 45 AM" src="https://user-images.githubusercontent.com/23738500/97249835-9fec4580-183f-11eb-98fd-0974a586c281.png">

**Comment by yusfarhanchepa** [comment]
<img width="935" alt="Screenshot 2020-10-27 at 11 40 19 PM" src="https://user-images.githubusercontent.com/23738500/97325759-47a05c80-18ae-11eb-9427-0e93277f9670.png">

" 4.4.3 Repeat this process for the OneSignalNotificationServiceExtension
Make sure the "App Groups" container is the same for both targets! Do not include OneSignalNotificationServiceExtension. Then press OK.  "

is it need to remove "OneSignalNotificationServiceExtension" from bundle identifier   OneSignalNotificationExtension Target too?

**Comment by yusfarhanchepa** [comment]
Provisioning profile “**” has app ID “**”, which does not match the bundle ID “**OneSignalNotificationServiceExtension”
how to resolve ?

**Comment by tyang1** [comment]
Hi @yusfarhanchepa ,
Thank you for providing the details.
For support regarding setup, please reach out through our official support channel at OneSignal.com.

> <img alt="Screenshot 2020-10-27 at 11 40 19 PM" width="935" src="https://user-images.githubusercontent.com/23738500/97325759-47a05c80-18ae-11eb-9427-0e93277f9670.png">
> 
> " 4.4.3 Repeat this process for the OneSignalNotificationServiceExtension
> Make sure the "App Groups" container is the same for both targets! Do not include OneSignalNotificationServiceExtension. Then press OK. "
> 
> is it need to remove "OneSignalNotificationServiceExtension" from bundle identifier OneSignalNotificationExtension Target too?

Please keep the "OneSignalNotificationServiceExtension" for the bundle identifier. The step 4.4.3 is meant to address the "App Groups" container => Make sure the "App Groups" container is the same for both targets! Do not include OneSignalNotificationServiceExtension

Thanks!
