### ISSUE TITLE
onReceived not getting triggered if the app is closed (swipe out)

### ISSUE THREAD

**Issue by jeanlambert17** [OneSignal/react-native-onesignal#1074]
I am trying to store the notification via OneSignal and the "received" listener, I have a function that writes to the device storage. Everything works as it is supposed to when the app is in the background or in the foreground but when the app is swiped away, the notification is displayed on the status bar but the "received" listener function is not getting called

**Comment by rgomezp** [comment]
Howdy,
Thanks for the question. The `onReceived` event only fires if the app is in the foreground. This is changing in the upcoming major release where you will be able to set a dedicated handler for the notification showing in the forgeround.

To get a head start on the migration, click [here.](https://documentation.onesignal.com/docs/step-by-step-react-native-3x-to-400-upgrade-guide)

To learn about Background Notifications click [here](https://documentation.onesignal.com/docs/data-notifications).

In the future, please reach out to our support channel at OneSIgnal.com for these types of questions.

Enjoy!

**Comment by jeanlambert17** [comment]
Thanks for the quick answer!
