### ISSUE TITLE
Permission asked automatically when the app starts

### ISSUE THREAD

**Issue by mtt87** [OneSignal/react-native-onesignal#108]
For some reason the popup asking permission for the push notifications is showing automatically when the app is opened for the first time even if I'm not calling OneSignal anywhere inside my JS code.
Is this the expected behaviour?
I'd like to be able to ask for permission inside the app at some point, not on the first loading (which is very bad).

Package version:
```js
"react-native": "0.37.0",
"react-native-onesignal": "^1.2.3",
```
app.js
```js
import React from 'react';
import { Text } from 'react-native';
// import OneSignal from 'react-native-onesignal';

// const pendingNotifications = [];

// const handleNotification = (notification) => {
//   console.log(pendingNotifications);
//   alert(notification.message);
// };

// OneSignal.configure({
//   onIdsAvailable(device) {
//     console.log('UserId = ', device.userId);
//     console.log('PushToken = ', device.pushToken);
//   },
//   onNotificationOpened(message, data, isActive) {
//     const notification = {
//       message,
//       data,
//       isActive,
//     };
//     pendingNotifications.push(notification);
//     handleNotification(notification);
//   },
//   enableInAppAlertNotification: true,
// });
const WelcomeScreen = () => <Text>Hello world</Text>;
export default WelcomeScreen;
```

**Comment by mtt87** [comment]
Anyone here can give me some hint to where to start debugging? (given the fact that I'm not iOS dev but JS dev, I'm not much familiar with Xcode/Swift/Obj-c)

Thank you

**Comment by psyzz** [comment]
@mtt87 in your AppDelegate.m: add "autoRegister: false":

```
self.oneSignal = [[RCTOneSignal alloc] initWithLaunchOptions:launchOptions appId:@"<app id>" autoRegister: false];
```

then in your js when you want to ask permission:

```
OneSignal.registerForPushNotifications();
```

**Comment by mtt87** [comment]
@arshavinho seems like it worked, the permission is now asked when I trigger 
`OneSignal.registerForPushNotifications();`

I do a double check and see if the notifications are working fine and then I think I can add this to README since it's never mentioned.

**Comment by mtt87** [comment]
Confirmed! Works like a charm adding `autoRegister: false`! 👍

**Comment by goldengecko** [comment]
They have changed the API and now you have to pass a dictionary instead:

```
  self.oneSignal = [[RCTOneSignal alloc] initWithLaunchOptions:launchOptions
                                                         appId:@"your-app-id"
                                                      settings:@{kOSSettingsKeyAutoPrompt : @NO}];
```

**Comment by Luckygirlllll** [comment]
@goldengecko When I'm adding this line of code to AppDelegate.m, I'm getting this Xcode error: "Property 'oneSignal' not found on object of type 'AppDelegate *'". What should I do?

**Comment by Luckygirlllll** [comment]
Here is how my AppDelegate.m file look like (I have ExpoKit project):

```
#import "AppDelegate.h"
#import <React/RCTPushNotificationManager.h>


@implementation AppDelegate

// Put your app delegate methods here. Remember to also call methods from EXStandaloneAppDelegate superclass
// in order to keep Expo working. See example below.

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    self.oneSignal = [[RCTOneSignal alloc] initWithLaunchOptions:launchOptions
                                                           appId:@"your-app-id"
                                                        settings:@{kOSSettingsKeyAutoPrompt : @NO}];

    return [super application:application didFinishLaunchingWithOptions:launchOptions];

}

@end
```

**Comment by goldengecko** [comment]
You haven't declared that variable anywhere. Suggest `@synthesize oneSignal = _oneSignal;`

**Comment by Luckygirlllll** [comment]
@goldengecko If I'm adding `@synthesize oneSignal = _oneSignal;` I'm getting an error` Property implementation must have its declaration in interface 'AppDelegate' or one of its extensions`

**Comment by goldengecko** [comment]
Yes, you would need to declare it in the header `@property (strong, nonatomic) RCTOneSignal* oneSignal;` and have the synthesize in the implementation. Just the normal style of variable handling

**Comment by chiragpatel3131** [comment]
any suggestion for Android SDK i am facing the same.

**Comment by MaganAnkur** [comment]
I am not using OneSignal but still getting the same issue, Any idea how to solve?
