### ISSUE TITLE
🔥 OneSignal breaks Firebase Phone Auth 

### ISSUE THREAD

**Issue by taschik** [OneSignal/react-native-onesignal#1080]
**Description:**

Onesignal breaks Firebase Phone Auth which leads to a not functioning background push and being redirected to an empty page when selecting the captchas in the authentication progress.
 
**Environment**

**Onesignal: 3.9.2
Installed via: npm**

Firebase:

```
"@react-native-firebase/app": "^8.4.6",
"@react-native-firebase/auth": "^9.3.1",
```

    info Fetching system and libraries information...
    (node:76962) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
    (Use `node --trace-warnings ...` to show where the warning was created)
    System:
        OS: macOS 10.15.7
        CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
        Memory: 3.00 GB / 32.00 GB
        Shell: 5.7.1 - /bin/zsh
      Binaries:
        Node: 14.8.0 - /usr/local/bin/node
        Yarn: 1.22.4 - /usr/local/bin/yarn
        npm: 6.14.8 - /usr/local/bin/npm
        Watchman: 4.9.0 - /usr/local/bin/watchman
      Managers:
        CocoaPods: 1.9.3 - /usr/local/bin/pod
      SDKs:
        iOS SDK:
          Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
        Android SDK:
          API Levels: 23, 26, 27, 28, 29
          Build Tools: 23.0.1, 25.0.0, 26.0.3, 27.0.3, 28.0.1, 28.0.2, 28.0.3
          System Images: android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
          Android NDK: Not Found
      IDEs:
        Android Studio: 3.6 AI-192.7142.36.36.6308749
        Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
      Languages:
        Java: 1.8.0_221 - /usr/bin/javac
        Python: 3.8.5 - /usr/local/opt/python/libexec/bin/python
      npmPackages:
        @react-native-community/cli: Not Found
        react: 16.13.1 => 16.13.1
        react-native: 0.63.3 => 0.63.3
        react-native-macos: Not Found
      npmGlobalPackages:
        *react-native*: Not Found**Steps to Reproduce Issue:**

1. Setup firebase phone auth and verify it is working
1. Integrate OneSignal following this [guide](https://documentation.onesignal.com/docs/react-native-sdk-setup)
1. Log out the user and try to relogin
1. You either automatically or after doing some captcha get redirected to an empty page:
![download](https://user-images.githubusercontent.com/351623/97755439-6709d600-1ab6-11eb-8874-85b71a107275.png)
1. Removing OneSignal integration makes phone auth work again.

**Comment by taschik** [comment]
I tested today with the new 4.0 beta and the issue persists here too.

**Comment by rgomezp** [comment]
Since this was reported in multiple wrapper SDKs, we will consolidate the issue into the native iOS repository. Please continue discussion there.

[Link](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/790)
---

**Comment by emawby** [comment]
This is likely a swizzling issue That might be resolved as described [here](https://firebase.google.com/docs/auth/ios/phone-auth) but also might require a non-swizzled option from OneSignal
