### ISSUE TITLE
Handling notification when app's in foreground - local notification?

### ISSUE THREAD

**Issue by blueberry6401** [OneSignal/react-native-onesignal#1081]
**Description:**
Hi, considering this situation: I have some notifications pushed to the app, but one of them I want to handle it manually if app's in foreground. The other notifications are always show no matter what.
So I set inFocusDisplaying(None) and listen to 'received' event. Now I'm able to handle that notification manually, but how do I continue push the other notifications locally? Does react-native-onesignal support this or I have to use another library to do it?

**Comment by rgomezp** [comment]
Howdy,
Thanks for the question. You're in luck. This functionality was recently added to this SDK and is currently in the major release beta. With the new version, you will be able to dynamically decide to show or silence notifications based on whether the app is in the foreground as well as on other things like additional data values and more.

Take a look at [this issue](https://github.com/OneSignal/react-native-onesignal/issues/1079) to learn more.

Enjoy!

**Comment by empiteranga** [comment]
@rgomezp Is there any way to display a local notification when the app is in foreground android

**Comment by jkasten2** [comment]
@empiteranga The SDK displays a push notification automatically, even when the app is in the foreground. If you do want to suppress this and display your own notification you can use `OneSignal.Notifications.addEventListener('foregroundWillDisplay',(event) => {} )` to do this. More details here:
https://documentation.onesignal.com/docs/mobile-sdk#handling-notifications-before-theyre-presented-when-the-app-is-in-the-foreground

Due note if you use `event.preventDefault();` and display your own local notification instead then you will need to handle the click event with your own code. The OneSignal SDK won't be able to receive the click event.

**Comment by maiznadeem** [comment]
@jkasten2 Hello, I have a question. How can I use `foregroundWillDisplay` listener for only certain notifications. Currently, If I add the listener, it'll not show any notification when app is open. However I only want selected notifications to not be displayed based on the notification payload.
