### ISSUE TITLE
[v4] notifReceivedEvent.complete() => crash

### ISSUE THREAD

**Issue by blueberry6401** [OneSignal/react-native-onesignal#1082]
**Description:**

Hi, I'm using v4, following this example in the docs:
```
OneSignal.setNotificationWillShowInForegroundHandler(notifReceivedEvent => {
    console.log("OneSignal: notification will show in foreground:", notifReceivedEvent);
    let notif = notifReceivedEvent.getNotification();
});
```
App's crashed when I call `notifReceivedEvent.complete()` (no arguments). 
Take a look at the source code, I think I found the issue, in `src/NotificationReceivedEvent.js`, it's trying to access notificationId of null:
![image](https://user-images.githubusercontent.com/7337535/97844294-57d89180-1d1d-11eb-98c4-dc11c9940fb1.png)

**Environment**

1. What version of the OneSignal React-Native SDK are you using? v4 beta 2
2. How did you add the SDK to your project (eg. npm)

**Comment by rgomezp** [comment]
Howdy,
Thank you for reporting this. The bug should now be fixed and is merged into the branch `major-release`. We will have to create a new beta release but in the meantime feel free to point your dependency to that branch or run our example app which now includes Typescript typings as an added bonus.

Thanks again for surfacing this.

Enjoy!
