### ISSUE TITLE
Undefinded symbols for architecture arm64

### ISSUE THREAD

**Issue by minhnghiadev** [OneSignal/react-native-onesignal#1083]
**Description:**

My app appear error when built it. 
The message is: "**Undefinded symbols for architecture arm64**"
But I try to remove Onesignal, my app is build normal.

(your description here)

**Environment**

OneSignal React-native SDK 3.9.2
I added SDK step by step in Onesignal Documentation. 

**Steps to Reproduce Issue:**

**Anything else:**

(crash stacktraces, as well as any other information here)

![Inkedone-signal-error!UNITO-UNDERSCORE!LI](https://user-images.githubusercontent.com/12292792/97957659-3ee3e500-1dde-11eb-8dda-bdadedc8126d.jpg)

**Comment by rgomezp** [comment]
Howdy,
Are you using Cocoapods?

Did you try running `pod deintegrate && pod install` in the ios directory?

**Comment by rgomezp** [comment]
Closing due to no response
