### ISSUE TITLE
Unable to dismiss Push In-App Messages on 3.9.2

### ISSUE THREAD

**Issue by escobar022** [OneSignal/react-native-onesignal#1087]
**Description:**

It looks like the changes made in the latest version [here](https://github.com/OneSignal/react-native-onesignal/compare/3.9.2...master#diff-153b24fed9bd79fc91c7ca30ccccdd37f29859785574f541911460e7a4cbdd6cL408-L414) are causing issues dismissing or using the exit button when using In-App messages. 
The message box wont disappear.

**Environment**
React Native SDK Version: 3.9.2

**Steps to Reproduce Issue:**
1. Setup SDK as instructed [here](https://documentation.onesignal.com/docs/react-native-sdk-setup) and [here](https://documentation.onesignal.com/docs/ios-push-opt-in-prompt) 
1. Set up in-app push notification prompt with these options (as instructed) and add a timer so it doesn't trigger right away.
![](https://user-images.githubusercontent.com/6199499/98619078-7c5ddc00-22d0-11eb-8ff9-6ac00551a5b3.png)
1. Set up advanced conditions.
![](https://user-images.githubusercontent.com/6199499/98620102-a0222180-22d2-11eb-893e-f9b7c8803c69.png)
1. Removing the "Every time trigger conditions are satisfied" selection stops the issue. Removing the time condition stops this issue even if "Every time trigger conditions are satisfied" is set.
1. Downgrading to 3.9.1 also fixes this problem.
1. Accepting it enabling does not stop the in-app message from reappearing.

Expected Behavior:
Have the push notification in-app message appear after 15 seconds per session, if accepted activate set the 'prompt_ios' as true and never show the notification again.

**Comment by rgomezp** [comment]
Howdy,
Thanks for reporting this. While I haven't seen this exact IAM issue before, there were some changes and minor bug fixes that were done on the native releases now in Beta. Luckily you can test these by upgrading to the major release in beta version 4 (#1079). Can you please try reproducing in the upcoming major release version?

**Comment by rgomezp** [comment]
Closing due to no response
