### ISSUE TITLE
Android Badge Count Not Resetting

### ISSUE THREAD

**Issue by bendellarocco** [OneSignal/react-native-onesignal#109]
I am having multiple reports of android users badge counts not resetting.  I am not seeing this issue on iOS.  I do not want to disable the badge numbers completely.  But is there a way to force reset them to zero when the app opens?  Maybe I missed a special android step to clear out the notification count.

**Comment by bendellarocco** [comment]
will `OneSignal.clearOneSignalNotifications();` reset them?

**Comment by jkasten2** [comment]
@bendellarocco Can you ensure your app has 2.5.0 or later of the native Android SDK? There was a badge syncing issue fixed in this version.
https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/2.5.0

**Comment by kelset** [comment]
I'm facing the same issue, on a real device running Android 5.0.1.

@jkasten2 how can I check the version of the native Android SDK? I've installed `react-native-onesignal 3.0.3` and in the README.md there is no reference to the native Android SDK.

---
Ok no my fault: basically, the counter only gets resetted once the notifications are "swiped" from the top system drawer.
