### ISSUE TITLE
[Beta] Wrong permission status on iOS

### ISSUE THREAD

**Issue by KDederichs** [OneSignal/react-native-onesignal#1091]
**Description:**

According to your Beta Documentation Approved permission on iOS is supposed to be 1, it's returning 2 though (even though it's enabled and subscribed and I clicked Allow)

**Environment**

react-native-onesignal: beta 4
Native version should be Beta 3

**Steps to Reproduce Issue:**

1. Install latest rn-onesignal beta (4)
1. add a permission observer
1. approve permission and look at status 

**Anything else:**

RN 0.63.3
iOS 14.2

Edit:
It also doesn't seem to display the notifications (even though it shows them as enabled in the settings)

Edit2: Ok it showed up after like 3 minutes, maybe an apple issue or something

**Comment by rgomezp** [comment]
Howdy,
Thank you for reporting this issue. Could you please include the exact code you have in your app, including initialization?This would help us reproduce this as your instructions aren't specific enough and the issue didn't come up in testing.

Cheers

**Comment by KDederichs** [comment]
Sure:
```
// Out of component, while I post this, the TS typings are wrong btw, event.complete doesn't take no args and params 
// shouldn't be an object
const showInForegroundHandler = (event: NotificationReceivedEvent) => {
  const notification = event.getNotification();
  // @ts-ignore
  if (notification.additionalData?.type === 'message') {
    const currentRoute = NavigationService.navigationRoute();
    Logger.log({ currentRoute, notification }, 'Current Route');
    if (currentRoute && currentRoute.name === 'Chat') {
      // @ts-ignore
      if (currentRoute.params?.userId === notification.additionalData?.user) {
        // @ts-ignore
        event.complete();
        return;
      }
    }
  }
  event.complete(notification);
};

  const onPushOpenCallback = useCallback((notification: OpenedEvent): void => {
    Logger.log(notification, 'onOpened called');
    const payload = notification.notification;
    //Do something with that as well.
  }, []);

  const permissionObserver = useCallback(
    (event: ChangeEvent<PermissionChange>) => {
      Logger.log({ event }, 'OneSignal Permission Observer');
      if (event.to.hasPrompted === false) {
        // Do something with that
      }
    },
    [],
  );

  useEffect(() => {
    OneSignal.setAppId(ONE_SIGNAL_KEY);
    OneSignal.setNotificationOpenedHandler(onPushOpenCallback);
    OneSignal.addPermissionObserver(permissionObserver);
    OneSignal.getDeviceState().then((devState: DeviceState) => {
      setDevicePushId(devState.userId);
    });
    OneSignal.setNotificationWillShowInForegroundHandler(
      showInForegroundHandler,
    );

    return () => {
      OneSignal.clearHandlers();
    }
  }, []);
```

Here's also a screenshot of the device status:


<img width="678" alt="Screenshot 2020-11-17 at 10 31 38" src="https://user-images.githubusercontent.com/24696606/99372338-4d42fe00-28c0-11eb-9594-45bca407c032.png">

It's 2 as well but push is enabled on the device and it's getting notifications.

I also have the NotificationExtension set up as per your documentation

**Comment by rgomezp** [comment]
Howdy,
Great catch on that optional argument in the typings.

In terms of the permission observer, this merits a bit of a deeper investigation. We appreciate your patience in the meantime and thank you for your detailed reporting and contributions in order to improve the SDK. 

Cheers

**Comment by rgomezp** [comment]
Howdy @KDederichs ,
We are still investigating any issue with the observer. That said, the typings should now be fixed and available in the beta 5 release.

Thank you for your patience.

Enjoy!

**Comment by rgomezp** [comment]
Howdy,
I managed to reproduce this issue in the `ts_example_app` branch example project. It seems like a problem most likely with the underlying native SDK. I will surface this with @emawby and the rest of the team. Thanks for your patience.


---
From the log:

```
[Tue Dec 15 2020 19:03:17.432]  LOG      OneSignal: permission changed:{"to":{"hasPrompted":true,"provisional":false,"status":1},"from":{"hasPrompted":true,"provisional":false,"status":0}}
[Tue Dec 15 2020 19:03:17.441]  LOG      Prompt response:
[Tue Dec 15 2020 19:03:17.441]  LOG      OneSignal: permission changed:{"to":{"hasPrompted":true,"provisional":false,"status":2},"from":{"hasPrompted":true,"provisional":false,"status":1}}
```

It looks like the permission observer fires twice, once going from `0` to `1` and once going from `1` to `2` meaning the permission is changing twice.

Here is the result of `getDeviceState`:
```
[Tue Dec 15 2020 19:10:06.950]  LOG      Device State: {"userId":"f618a47d-1a83-4186-992b-a454783efa2c","isSubscribed":true,"hasNotificationPermission":true,"isPushDisabled":false,"pushToken":"1e6fdd3e27540a64f8ecd36a9fbd9cc6cd1afe1bd9db1b9c0976d06589badb50","notificationPermissionStatus":2,"isEmailSubscribed":false}
```

**Comment by rgomezp** [comment]
Howdy,
It looks like this was a documentation error. The values of 1 and 2 were flipped. The values are the following:

0 - not determined
1 - denied
2 - authorized
3 - provisional
4 - ephemeral

The documentation has been [updated](https://documentation.onesignal.com/docs/react-native-40-api-reference#addpermissionobserver-function). Our apologies for the mistake.
