### ISSUE TITLE
Build failing due to Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by BenjErgizerBunny** [OneSignal/react-native-onesignal#1098]
**Description:**

I have had OneSignal installed in my react native project for over a year now.  It was working perfectly two months ago, however when I tried to boot my app today, I'm getting the error listed under **anything else**.  The only change I have made is that I updated my Apple Push Notifications service (APNs) since I last launched the app

**Environment**

1. started with npm 
1.  "react-native-onesignal": "^3.3.2"
1.  "react-native": 0.60.4

**Steps to Reproduce Issue:**

1. install OneSignal SDK
1. Try to boot app on iOS
1. 

**Anything else:**

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_WKWebViewConfiguration", referenced from:
      objc-class-ref in OneSignal(OneSignal-x86_64-master.o)
  "_OBJC_CLASS_$_WKWebView", referenced from:
      objc-class-ref in OneSignal(OneSignal-x86_64-master.o)
  "_CGAffineTransformIdentity", referenced from:
      ___49-[OSInAppMessageViewController animateAppearance]_block_invoke in OneSignal(OneSignal-x86_64-master.o)
  "_CGAffineTransformMakeScale", referenced from:
      -[OSInAppMessageViewController addConstraintsForMessage] in OneSignal(OneSignal-x86_64-master.o)

**Comment by minhnghiadev** [comment]
I have this issue too. 
Before, I used Xcode v11.x, it is work perfect.
When I upgrade to Xcode 12.xx, I rebuild my application, it appear error in OneSignalNotificationService:
"Undefined symbols for architecture arm64:..."

**Comment by BenjErgizerBunny** [comment]
@minhnghiadev  I think my error is also due to upgrading from xCode 11.x to 12.x

Were you able to find a solution?

**Comment by rgomezp** [comment]
Howdy,
We are investigating this issue. Thanks for your patience.

**Comment by rgomezp** [comment]
Howdy,
Thank you for your patience. Can you either confirm or deny whether you're still seeing the issue? Cheers

**Comment by rgomezp** [comment]
Closing due to no response.

**Comment by 77TecShaeer** [comment]
+++
