### ISSUE TITLE
build fail on react native 0.63

### ISSUE THREAD

**Issue by mannat26** [OneSignal/react-native-onesignal#1099]
**Description:**
build fail on react native 0.63

error: OneSignalNotificationServiceExtension/NotificationService.m:9:9: fatal error: 'OneSignal/OneSignal.h' file not found

**Environment**
  One signal version: 3.9.2
  react native: 0.63.3
  Xcode: 12.2

 using pod install

**Steps to Reproduce Issue:**

1. cd ios/
2. pod install

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience. Unfortunately your issue doesn't include enough information for us to be able to reproduce. Can you please include your Podfile?

Also, please see our [Troubleshooting Section](https://documentation.onesignal.com/docs/troubleshooting-react-native) for potential solutions.

**Comment by rgomezp** [comment]
Closing due to no response.
