### ISSUE TITLE
postNotification with ios_badgeType & ios_badgeCount

### ISSUE THREAD

**Issue by psyzz** [OneSignal/react-native-onesignal#110]
Hello,

is it possible to use postNotification with ios_badgeType & ios_badgeCount ?

i'm trying to add it to contents, data but doesn't increase the badge account, in fact no badge appears on my App icon :(. The notification workd.

OneSignal.postNotification(contents, data, player_id);

**Comment by avishayil** [comment]
I think it's not currently possible, but we'll consider this.
Thanks!

**Comment by leoskyrocker** [comment]
It's now possible. See https://github.com/geektimecoil/react-native-onesignal/issues/367 and https://github.com/geektimecoil/react-native-onesignal/pull/266
