### ISSUE TITLE
SDK setup doc outdated

### ISSUE THREAD

**Issue by tomlobato** [OneSignal/react-native-onesignal#1100]
**Description:**

The doc https://documentation.onesignal.com/docs/react-native-sdk-setup is outdated, leaving no glues to setup this up.

**Environment**

1. What version of the OneSignal React-Native SDK are you using?

3.9.2

1. How did you add the SDK to your project (eg. npm)

yarn add react-native-onesignal

**Steps to Reproduce Issue:**

1. Section 3.2 of https://documentation.onesignal.com/docs/react-native-sdk-setup refers to buildscript section of app/build.gradle, that doesnt exists in RN 0.63

**Anything else:**

Tried to find something in this issues, stackoverflow and google but without success.

**Comment by jfbn** [comment]
How did you get pas this @tomlobato? 

I am also at the step:

> 3.2 At the very top of your Android project's app/build.gradle, add the following code to the very top of the file:
```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal 
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.9, 0.99.99]'
    }
}
```

But this does not seem right..? The buildscript with repositories and dependencies are located in the project level build.gradle, not in the app/build.gradle. What should I do?

**Comment by sami-99** [comment]
> How did you get pas this @tomlobato?
> 
> I am also at the step:
> 
> > 3.2 At the very top of your Android project's app/build.gradle, add the following code to the very top of the file:
> 
> ```
> buildscript {
>     repositories {
>         maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal 
>     }
>     dependencies {
>         classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.9, 0.99.99]'
>     }
> }
> ```
> 
> But this does not seem right..? The buildscript with repositories and dependencies are located in the project level build.gradle, not in the app/build.gradle. What should I do?

same for me, any suggestions?

**Comment by tomlobato** [comment]
@jfbn @sami-99 hi guys, sorry for the long delay.
I ended up leaving onesignal. We have high stability standard, which onesignal definetly cannot fullfill, even in the paid plans. Each 2-3 months it has 2-3 hours of downtime, plus monthly 30min downtimes.

**Comment by sami-99** [comment]
> @jfbn @sami-99 hi guys, sorry for the long delay. I ended up leaving onesignal. We have high stability standard, which onesignal definetly cannot fullfill, even in the paid plans. Each 2-3 months it has 2-3 hours of downtime, plus monthly 30min downtimes.

Got it, 
What do you use now for pushing notifications if you don't mind me asking, thanks for replying.

For anyone having this issue I just had to ignore this step which seems to be unnecessary.

**Comment by tomlobato** [comment]
Good to see you made it!
Here, I cut onesignal and made my own middleware with sidekiq/redis/ruby.
If there is quorum I could pusblish it. On the app side, just used the
popular rn push libs. Now it’s running great for 100k pushs/day.

Em sáb., 25 de dez. de 2021 às 12:01, sami-99 ***@***.***>
escreveu:
