### ISSUE TITLE
build failed due to Library not found for -lPods-OneSignalNotificationServiceExtension error

### ISSUE THREAD

**Issue by jaime-mp** [OneSignal/react-native-onesignal#1103]
**Description:**

build failed due to Library not found for -lPods-OneSignalNotificationServiceExtension error

I have tried to run pod deintegrate and then pod install, and I get a warning that says the following:

[!] The `OneSignalNotificationServiceExtension [Debug]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in` Pods / Target Support Files / Pods-OneSignalNotificationServiceExtension / Pods-OneSignalNotificationServiceExtension.debug.xcconfig '. This can lead to problems with the CocoaPods installation
    - Use the `$ (inherited)` flag, or
    - Remove the build settings from the target.

**Environment**

I'm using react-native-cli 2.0.2
I use yarn to add the SDK to my project

Regards.

**Comment by markovdigital** [comment]
Encountered same issue after upgrading sdk from 3.x, already tried literally everything
react-native-onesignal: 4.0.0-beta.4

**Comment by DzmitrySakalouski** [comment]
I also have such issue. Any updates?

**Comment by markovdigital** [comment]
Seems like I got successful release build

1) Exclude arm64 for Simulator SDK for all targets (Root project, your app target and NotificationServiceExtension)
![image](https://user-images.githubusercontent.com/15268617/101288825-6d5c4200-381a-11eb-9bdb-d4026dbffebb.png)

2) Paste this fragment

```ruby
installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
end
```
inside of this block of Podfile

```ruby
use_flipper!
post_install do |installer|
    ...
end
```

3) inside of ios folder

```console
rm -rf Pods Podfile.lock && pod install
```

4) Clean & build again

**Comment by DzmitrySakalouski** [comment]
Thanks a lot but it didn't work for me =(

**Comment by DzmitrySakalouski** [comment]
Small update - check your version of iOS target version in Podfile and in Xcode (OneSignal target tab) - there was mismatch in my case. After fixing it I was able to build the app

**Comment by rgomezp** [comment]
@jaime-hub ,
Can you please try the above and respond with your results?

Cheers

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by hugoh59** [comment]
Same issue for me still even tho I do have the same version everywhere.

**Comment by bakehouseone** [comment]
Still experience the same issue

**Comment by lordival** [comment]
still here too

**Comment by lordival** [comment]
how did you guys get around this issue?

**Comment by rgomezp** [comment]
@hugoh59 @bakehouseone @lordival ,
Did you make sure the iOS deployment targets match as mentioned above?

If you are using the Expo plugin, please upgrade to the latest beta release which includes a fix for this issue.

Enjoy!

**Comment by munsifhayat** [comment]
> Small update - check your version of iOS target version in Podfile and in Xcode (OneSignal target tab) - there was a mismatch in my case. After fixing it I was able to build the app

This worked for me after spending couple of hours.

**Comment by augustovicente** [comment]
I was having this issue on Mac M1.
My solution was add arm64 inside Excluded Architectures inside OneSignalNotification tab.
<img width="639" alt="image" src="https://user-images.githubusercontent.com/41742354/210864961-77e3a60b-3450-45d7-b661-b744973e6ad6.png">

I did that before on my project target, but it was not enough.

**Comment by ebellumat** [comment]
Your notifications still working after this change?

**Comment by Biswo2002** [comment]
Library 'Pods-OneSignalNotificationServiceExtension' not found
I'm facing this issues
