### ISSUE TITLE
registerForProvisionalAuthorization support

### ISSUE THREAD

**Issue by TheRusskiy** [OneSignal/react-native-onesignal#1106]
Are there any plans to add support for `registerForProvisionalAuthorization`?
iOS version of the SDK supports it.

**Comment by jkasten2** [comment]
@TheRusskiy Thanks for digging in to the OneSignal-iOS-SDK to check this. We will consider adding this in the future.

There is a dashboard option to enable Provisional Notifications by default if you don't need to conditionally enable this might be all you need.
https://documentation.onesignal.com/docs/ios-customizations#provisional-push-notifications

Does this meet your requirements? Or do you need a method to trigger when when provisional is enabled for a specific use case?

**Comment by rgomezp** [comment]
Closing. This issue will be tracked internally and will still be considered.
