### ISSUE TITLE
Triggers asking for push permissions won't show when "Enable iOS 12 Direct To History" is set

### ISSUE THREAD

**Issue by TheRusskiy** [OneSignal/react-native-onesignal#1107]
**Description:**

When an app has "Enable iOS 12 Direct To History" set to true, then In-App messages asking for Push permissions aren't showing.

**Environment**

Tried this on `3.9.2` and `4.0.0-beta.4` versions.
Added via yarn.

**Steps to Reproduce Issue:**

1. Configure In-App message to show when a trigger is present
1. Set `"Enable iOS 12 Direct To History"` to true in app settings
1. Call `OneSignal.addTrigger("my_trigger", "true")`

**Anything else:**

When the following code is called
`OneSignal.addTrigger("my_trigger", "true")`
I can see triggers being processed in debug mode, but the in-app message won't show.
When "Enable iOS 12 Direct To History" is disabled it starts working.

**Comment by rgomezp** [comment]
Howdy,
Can you please provide us with a log after setting the OneSignal `setLogLevel` debug setting to VERBOSE?

Cheers

**Comment by TheRusskiy** [comment]
@rgomezp it says that it's processing triggers, but then nothing happens

**Comment by rgomezp** [comment]
@TheRusskiy 
Howdy, we would like to see the logs themselves if possible to better assist you. 

Thank you.

**Comment by TheRusskiy** [comment]
@rgomezp here's a shortened version because it's masochistic trying to write down all messages from system dialog and nothing is sent to console.

console logs:
{"emailAddress": null, "emailSubscribed": false, "emailUserId": null, "hasPrompted": false, "notificationsEnabled": false, "pushToken": "<REDACTED>", "subscriptionEnabled": false, "userId": "<REDACTED>", "userSubscriptionEnabled": true}

System dialog logs:
<APP STARTUP>
Called init with appId...
Downloading iOS parameters for this application
HTTP Request (ORequestGetIosParams)...
Firing registerForRemoteNotifications
registerUser:waitingForApnsResponse:1
registerUser:InitializationTime...
registerUserAfterDelay
oneSignalDidRegisterForRemoteNotifications:deviceToken:
device registered with apple:...
updateDeviceToken:onSuccess:onFailure:
shouldRegisterNow:waitingForOneSeg:0
shouldRegisterNow:waitingForOneSeg:isImmediatePlayerCreateOrOnSession:0
shouldRegisterNow:waitingForOneSeg:isOnSessionSuccesffulForCurrentState:0
shouldRegisterNow: lastTimeClosed:...
networkResponse...
registerUser:waitingForApnsResponse:0
registerUser:InitializationTime...
registeruserNow
registeruserInternal
shouldRegisterNow:waitingForOneSeg:0
shouldRegisterNow:waitingForOneSeg:isImmediatePlayerCreateOrOnSession:0
shouldRegisterNow:waitingForOneSeg:isOnSessionSuccesffulForCurrentState:0
...
onesignal session manager restartSessionIfNeeded....
OSChannelTracker for...
...
getNotificationSubscriptionStatus: -1
provision: ...
calling onesignal create/on_session
...
on_session result: { id: ... }
getNotificationSubscriptionStatus: -1
application/scene willResignActive
...
<a whole lot of more system messages (something about foreground, background...)>
...
evaluating in app messages
<NO MORE MESSAGES>

Tried the following code, different trigger names, but no more logs:
OneSignal.removeTriggerForKey("my_trigger")
OneSignal.addTrigger("my_trigger", "true")

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience. This has been resolved so if you could please update to the latest SDK version you should get the fix. Please let us know if you encounter any further problems.

**Note:** also, please go into your OneSignal dashboard and simply re-save your In App Message. That should do the trick.

Enjoy!
