### ISSUE TITLE
App Crash while setting external user

### ISSUE THREAD

**Issue by crzycoder** [OneSignal/react-native-onesignal#1109]
**Description:**
onesignal.setexternaluserid got 2 arguments, expected 3

**Environment**

```
"react": "16.13.1",
"react-native": "0.63.4",
"react-native-onesignal": "^3.9.3",
```

**Code**

```
OneSignal.setLogLevel(6, 0);

    OneSignal.init(config.ONESIGNAL_APP_ID,
        {
          kOSSettingsKeyAutoPrompt: false,
          kOSSettingsKeyInAppLaunchURL: false,
          kOSSettingsKeyInFocusDisplayOption: 2
        });

    OneSignal.inFocusDisplaying(2);

    OneSignal.promptForPushNotificationsWithUserResponse(myiOSPromptCallback);

let User  = {
"email":"client@example.com",
"id":4,
"name":"Bilal Hussain Shah",
"status":true,
} // This is User.

OneSignal.setExternalUserId(User.id.toString(), (results) => {
    console.log('Results of setting external user id');
    console.log(results);
});
```

![Screenshot!UNITO-UNDERSCORE!20201208-172708](https://user-images.githubusercontent.com/43851308/101483881-9dbaf200-397a-11eb-8a44-675f6d8304f8.png)

**Comment by rgomezp** [comment]
Howdy,
Thank you for opening this issue. This looks like a bug.

We will investigate. If you could please provide us with a stack trace or log from your logcat with the OneSignal `setLogLevel` setting set to VERBOSE ([reference](https://documentation.onesignal.com/docs/sdk-reference#setloglevel-method)) we would greatly appreciate it.

Thank you for your patience.

**Comment by markhalonen** [comment]
Hello @rgomezp I cannot reproduce it locally, when I install from XCode to my phone, everything works perfectly. 

It's only when I go through TestFlight or App Store that I have issues

**Comment by crzycoder** [comment]
Thanks for the reply @rgomezp here is the trace .. In your previous version like 3.9.2 setExternalUserId use 2 parameters now it's require 3 parameter in 3.9.3 .. but passing 3 parameter did not solved the error . it's keep crashing .
for now I'm using 3.9.2 sdk.

```
trying these options ==>> //0 = NONE, 1 = FATAL, 2 = ERROR, 3 = WARN, 4 = INFO, 5 = DEBUG, 6 = VERBOSE
OneSignal.setLogLevel(6, 0);
```

**Please check your setExternalUserId Method in android**

```
static setExternalUserId(externalId, varArg1, varArg2) {
        if (!checkIfInitialized()) return;

        if (typeof varArg1 === "function") {
            RNOneSignal.setExternalUserId(externalId, null, varArg1);
            return;
        }

        RNOneSignal.setExternalUserId(externalId, varArg1, varArg2 || function(){});

}
```
<details><summary>screenshot</summary>

![Screenshot_20201209-115407](https://user-images.githubusercontent.com/43851308/101595948-0d31ef80-3a16-11eb-8499-7e7719adafe6.png)

</details>

<details><summary>screenshot</summary>

![Screenshot_20201209-115451](https://user-images.githubusercontent.com/43851308/101596043-3783ad00-3a16-11eb-9f5e-7ab1e53c548d.png)

</details>

<details><summary>screenshot</summary>

![Screenshot_20201209-115659](https://user-images.githubusercontent.com/43851308/101596083-49655000-3a16-11eb-82b1-5bf4825faba5.png)

</details>

<details><summary>screenshot</summary>

![Screenshot_20201209-115916](https://user-images.githubusercontent.com/43851308/101596097-4ec29a80-3a16-11eb-9ee7-cac8f467f44a.png)

</details>

<details><summary>screenshot</summary>

![Screenshot_20201209-115929](https://user-images.githubusercontent.com/43851308/101596107-55511200-3a16-11eb-844a-e24ba5c41b0f.png)

</details>

<details><summary>screenshot</summary>

![Screenshot_20201209-115925](https://user-images.githubusercontent.com/43851308/101596118-597d2f80-3a16-11eb-9500-351498f1d4d9.png)

</details>

**Comment by rgomezp** [comment]
Howdy,
Thanks for the details.

Your screenshots include an issue related to IAM that seems unrelated to the original issue.

It seems the error resulted from getting changes to the Android bridge (RNOneSignal.java) of the SDK but not the JS side of the bridge (index.js).

Can you please look in your `node_modules` to confirm the `setExternalUserId` functions in these two files match these files on `master` of this repository?

Master Files:
1. [`RNOneSignal.java`](https://github.com/OneSignal/react-native-onesignal/blob/ebcadbd33f7bd0c1041c8ae84176c677002c337a/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java#L379)
2. [`index.js`](https://github.com/OneSignal/react-native-onesignal/blob/ebcadbd33f7bd0c1041c8ae84176c677002c337a/index.js#L438)

If there is any sort of mismatch between these files in your `node_modules` you may want to do a clean build including rebuilding your `node_modules` directory and perhaps even clearing your local package cache (e.g: `yarn cache clean`).

**Comment by haris523** [comment]
I'm having the same issue, right after updating npm (Before updating npm I couldn't even run the proct that worked this morning)

**Comment by rgomezp** [comment]
@haris523 , 
Can you please respond to my [above comment](https://github.com/OneSignal/react-native-onesignal/issues/1109#issuecomment-742069104) and confirm or deny the files matching in your node_modules?

Also, it sounds like you're not even being able to run the project whereas other folks only saw this issue in production environments?

**Comment by haris523** [comment]
@rgomezp Ok so I can run the project, it just crashes as soon as it encounters the set external id function. It's in debug environment. This project has been in development for about 2 months and this was used for at least the past month without any issues untill today. 

This is the setExternalUserId functirom RNOneSignal.java
![image](https://user-images.githubusercontent.com/33039018/101697440-21a6d400-3a78-11eb-8742-5fcd9e62e69e.png)

setExternalUserId in index.js
![image](https://user-images.githubusercontent.com/33039018/101697587-60d52500-3a78-11eb-89be-7bedc1ab5bae.png)

**Comment by rgomezp** [comment]
@haris523 ,
Looks right to me. The underlying native SDK should be 3.15.6 as noted by the [`build.gradle`](https://github.com/OneSignal/react-native-onesignal/blob/master/android/build.gradle#L27) file. You should also be able to confirm the version via the `android/build.gradle` file in the package inside of `node_modules`.

Can you please include the code you're actually using to call the function?

**Comment by rgomezp** [comment]
For all: What version of Android is this occurring on?

**Comment by crzycoder** [comment]
**App.tsx**

```
import React from 'react';
import { LogBox,View } from 'react-native';
import Screens from './navigation/Screens';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { SharedStateProvider } from './store/store';
import OneSignal from 'react-native-onesignal';
import config from './config';

LogBox.ignoreAllLogs();

export default function App() {

    function myiOSPromptCallback(permission: Boolean){
        // do something with permission value
    }

    React.useEffect(() => {
        OneSignal.setLogLevel(6, 0);

        OneSignal.init(config.ONESIGNAL_APP_ID,
            {
                kOSSettingsKeyAutoPrompt: false,
                kOSSettingsKeyInAppLaunchURL: false,
                kOSSettingsKeyInFocusDisplayOption: 2
            });

        OneSignal.inFocusDisplaying(2);

        OneSignal.promptForPushNotificationsWithUserResponse(myiOSPromptCallback);

        OneSignal.addEventListener('received', onReceived);
        OneSignal.addEventListener('opened', onOpened);
        OneSignal.addEventListener('ids', onIds);

        return () => {
            OneSignal.removeEventListener('received', onReceived);
            OneSignal.removeEventListener('opened', onOpened);
            OneSignal.removeEventListener('ids', onIds);
        }
    }, [])

    async function setExternalUserId (device: any) {
        let userJSON = await AsyncStorage.getItem('user');
        if (Boolean(userJSON)) {
            if (typeof userJSON === "string") {
                let parsedUser = JSON.parse(userJSON)
                await OneSignal.setExternalUserId(parsedUser.id.toString(), (results: any) => {});
            }
        }
    }

    function onReceived(notification: Object) {
        console.log("Notification received: ", notification);
    }

    function onOpened (openResult: Object) {
        // console.log('Message: ', openResult.notification.payload.body);
        // console.log('Data: ', openResult.notification.payload.additionalData);
        // console.log('isActive: ', openResult.notification.isAppInFocus);
        // console.log('openResult: ', openResult);
    }

    function onIds(device: any) {
        console.log('Device info: ', device);
        setExternalUserId(device);
    }

    return (
        <View style={{flex:1}}>
            <SharedStateProvider>
                <Screens />
            </SharedStateProvider>
        </View>
    );
}
```

**Android build.gradle**

```
buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 19
        compileSdkVersion = 29
        targetSdkVersion = 29
        googlePlayServicesVersion = "17.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        classpath 'com.google.gms:google-services:4.3.3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

**Description**

as my `RNOneSignal.java` file and `setExternalUserId` method are the same as mentioned in @haris523  comment `https://github.com/OneSignal/react-native-onesignal/issues/1109#issuecomment-742110327` 
I've also clean my cache and reinstall the `node_module` but nothing happened .. This works in `IOS` but not working fine in `Android` after upgrade `3.9.2` to `3.9.3` .

**Comment by rgomezp** [comment]
@ crzycoder,
Thank you for the information.

What device and which version of Android are you seeing this issue on? We have tested this thoroughly and have not been able to reproduce.

**Comment by jkasten2** [comment]
@crzycoder @haris523 The error definitely indicates that the Java part of the SDK is not the most recent on the device / emulator you're testing on.
Here are all the parts the could be the issue.
1. `RNOneSignal.java` out of date
   - @haris523 Thanks for the screenshot, I see this is the latest.
2. APK did not get rebuilt
   - Run `ls -lh android/app/build/outputs/apk/debug/` from your project root and check the timestamp on `app-debug.apk`.
   - `debug` is assuming you are testing a development build
3. Ensure you have installed the latest APK
   - With this the one you can just redeploy the Android app. Though Android Studio or `npx react-native run-android`
   - You can also try uninstalling the app on your device and reinstalling through this process to ensure it isn't skipping the APK update.

**Comment by crzycoder** [comment]
`OneSignal.setExternalUserId(parsedUser.id.toString(), (results) => {});`

**changed to**

`OneSignal.setExternalUserId(parsedUser.id + '', (results) => {});`

Solved my issue.. I don't why `toString` not converting my value but in log it's showing it's type `String`.

**Comment by crzycoder** [comment]
`OneSignal.setExternalUserId(parsedUser.id.toString(), (results) => {});`

changed to

`OneSignal.setExternalUserId(parsedUser.id + '', (results) => {});`

Solved my issue.. I don't why `toString` not converting my value but in log it's showing it's type `String`.

**Comment by jkasten2** [comment]
@crzycoder Very strange in two regards;
a. `parsedUser.id.toString()` and `parsedUser.id + ''` should result in the same thing. Expect that `.toString()` will throw if ``parsedUser.id` is `null` or `undefined`, as these will be come strings with `+ ''`.
b. Your noted error error was "onesignal.setexternaluserid got 2 arguments, expected 3" so I would expect a type error instead of a number of params mismatch if anything.

I think any rebuild steps / redeploy steps you was ultimately what fixed it for and glad you got it working!

**Comment by jkasten2** [comment]
@haris523 Let us know if my https://github.com/OneSignal/react-native-onesignal/issues/1109#issuecomment-742973867 does not slove your issue.
