### ISSUE TITLE
Example for P2P Notifications

### ISSUE THREAD

**Issue by forki** [OneSignal/react-native-onesignal#111]
https://github.com/geektimecoil/react-native-onesignal#post-notification-peer-to-peer-notifications

I'm trying to send notifications from within my app, but can't get it to work. Is there a sample somewhere?

**Comment by psyzz** [comment]
https://github.com/geektimecoil/react-native-onesignal/issues/100 :)

**Comment by forki** [comment]
thx. since it'S FAQ I put it in readme: https://github.com/geektimecoil/react-native-onesignal/pull/112
