### ISSUE TITLE
When will 4.0 be released for production app use?

### ISSUE THREAD

**Issue by pweisensee** [OneSignal/react-native-onesignal#1114]
**Description:**

Wondering if/when `react-native-onesignal` v4 will be ready for production use. Since [OneSignal-Android-SDK](https://github.com/OneSignal/OneSignal-Android-SDK) and [OneSignal-iOS-SDK](https://github.com/OneSignal/OneSignal-iOS-SDK) recently released v4.0 and v3.0 respectively, can this library be updated to 4.0 too? 

We're attempting to integrate this into an existing app and wondering if we should integrate with v3 or v4-beta of react`-native-onesignal`?

**Environment**

1. currently installing `react-native-onesignal` `v4.0.0-beta.4`
1. installing using `yarn`

**Steps to Reproduce Issue:**
Not currently having an issue, looking for version clarification, rough timeline, and reliability advice.

**Anything else:**

**Comment by rgomezp** [comment]
Howdy,
There are still several minor improvements we would like to fix in React Native before we release version 4. We may release it very soon. That said, if you would like to go ahead and use the current version but update the underlying native SDKs, you can do so by modifying the SDK versions in the `android/build.gradle` and `react-native-onesignal.podspec` files in the package.

Enjoy!

**Comment by rgomezp** [comment]
Just updating this issue, the beta 5 version of the SDK now includes the major release versions of the native SDKs automatically. Simply upgrade to `4.0.0-beta.5` for the latest changes.

**Comment by pweisensee** [comment]
Great, I think that answers my question. I'll install the latest beta and continue to look forward to the future releases and fixes!

**Comment by rgomezp** [comment]
Enjoy!
