### ISSUE TITLE
User gets automatically unsubscribe after connecting to onesignal

### ISSUE THREAD

**Issue by neilakoh** [OneSignal/react-native-onesignal#1124]
**Description:**
This issue only happens in **_Latest_** Huawei mobile devices. For some reason, the user gets automatically unsubscribe by the time it connects to onesignal. I tried talking to Tiffany (your chat support) and provided her everything she needs. She asked for the verbose logs and here it is:

12-16 09:52:16.405 24381 25026 V OneSignal: OneSignalRestClient: After con.getResponseCode to: https://api.onesignal.com/players
12-16 09:52:16.406 24381 25026 D OneSignal: OneSignalRestClient: Successfully finished request to: https://api.onesignal.com/players
12-16 09:52:16.416 24381 25026 D OneSignal: OneSignalRestClient: POST RECEIVED JSON: {"success":true,"id":"57bf0e42-ac4f-4bf8-b390-82b5437156f4"}
12-16 09:52:16.421 24381 25027 D OneSignal: doCreateOrNewSession:response: {"success":true,"id":"57bf0e42-ac4f-4bf8-b390-82b5437156f4"}
12-16 09:52:16.423 24381 25027 I OneSignal: Device registered, UserId = 57bf0e42-ac4f-4bf8-b390-82b5437156f4
12-16 09:52:16.433 24381 24962 I ReactNativeJS: 'userId', '57bf0e42-ac4f-4bf8-b390-82b5437156f4'

12-16 09:54:27.168 24381 25161 V OneSignal: OneSignalRestClient: After con.getResponseCode to: https://api.onesignal.com/players/57bf0e42-ac4f-4bf8-b390-82b5437156f4/on_session
12-16 09:54:27.168 24381 25161 D OneSignal: OneSignalRestClient: Successfully finished request to: https://api.onesignal.com/players/57bf0e42-ac4f-4bf8-b390-82b5437156f4/on_session
12-16 09:54:27.171 24381 25161 D OneSignal: OneSignalRestClient: POST RECEIVED JSON: {"success":true,"id":"57bf0e42-ac4f-4bf8-b390-82b5437156f4"}
12-16 09:54:27.173 24381 25162 D OneSignal: doCreateOrNewSession:response: {"success":true,"id":"57bf0e42-ac4f-4bf8-b390-82b5437156f4"}
12-16 09:54:27.174 24381 25162 I OneSignal: Device registered, UserId = 57bf0e42-ac4f-4bf8-b390-82b5437156f4
12-16 09:54:27.179 24381 24962 I ReactNativeJS: 'userId', '57bf0e42-ac4f-4bf8-b390-82b5437156f4'

12-16 09:54:45.521 24381 25236 D OneSignal: OneSignalRestClient: Making request to: https://api.onesignal.com/players/57bf0e42-ac4f-4bf8-b390-82b5437156f4
12-16 09:54:45.904 24381 25236 V OneSignal: OneSignalRestClient: After con.getResponseCode to: https://api.onesignal.com/players/57bf0e42-ac4f-4bf8-b390-82b5437156f4
12-16 09:54:45.905 24381 25236 D OneSignal: OneSignalRestClient: Successfully finished request to: https://api.onesignal.com/players/57bf0e42-ac4f-4bf8-b390-82b5437156f4

12-16 09:54:55.608 24693 25518 D OneSignal: registerUser:registerForPushFired:false, locationFired: true, remoteParams: null, appId: fccb57c6-6695-4ef7-b18f-7e451a7b79e9
12-16 09:54:55.608 24693 25518 D OneSignal: Starting request to get Android parameters.
12-16 09:54:55.611 24693 25570 D OneSignal: OneSignalRestClient: Making request to: https://api.onesignal.com/apps/fccb57c6-6695-4ef7-b18f-7e451a7b79e9/android_params.js?player_id=57bf0e42-ac4f-4bf8-b390-82b5437156f4
12-16 09:54:55.611 24693 25570 D OneSignal: OneSignalRestClient: Adding header if-none-match: W/"2df8bf4e9e35a1a1fcb5de188b64bf35"

I tried using an old Huawei device and it works fine, I checked the subscription status and this is the returned data.

![Screen Shot 2020-12-16 at 1 35 35 PM](https://user-images.githubusercontent.com/15863359/102433961-bc8e4800-404e-11eb-9e4e-203a0c7e9228.png)

I noticed that the "**_subscriptionEnabled_**" field is true and there is a push token while on the "_**LATEST HUAWE**_I" devices I noticed that the subscription data only provides this:

`{"notificationsEnabled":true,"subscriptionEnabled":false,"userSubscriptionEnabled":true,"userId":"102d3d67-c7b5-451a-9570-b594598a1e0e"}`

Notice the "subscriptionEnabled":false

I already setup the Huawei React Native SDK and followed the steps provided by the guide below:

https://documentation.onesignal.com/docs/huawei-react-native-sdk-setup

I already added **_agconnect-services.json_** in my project and repeatedly went through the setup guide to make sure I did not skip something but still I get the same result. Not sure what went wrong.

**Environment**

"react-native": "0.61.5",
"react-native-onesignal": "3.9.3",

```
buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url 'https://plugins.gradle.org/m2/' }
        maven { url 'http://developer.huawei.com/repo/' }
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.9, 0.99.99]'
        classpath 'com.huawei.agconnect:agcp:1.2.1.301'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

```
allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven { url 'http://developer.huawei.com/repo/' }

        google()
        jcenter()
        maven { url 'https://maven.google.com' }
        maven { url 'https://jitpack.io' }
    }
}
```

`distributionUrl=https\://services.gradle.org/distributions/gradle-6.0-all.zip`

openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)

**Comment by neilakoh** [comment]
The reason why it is automatically unsubscribed is because it can not generate a push token, I just don't know why it can not generate because I already enabled the push kit, added the agconnect-services.json inside android/app

**Comment by tyang1** [comment]
Hi @neilakoh ,
Thank you for reaching out to us and providing the thorough details.
Can you try updating this in your build configuration (replacing 1.2.1.301 with 1.3.1.300 configuration:

buildscript {
    dependencies {
        classpath 'com.huawei.agconnect:agcp:1.3.1.300'
    }
}

Please let us know if this helps, we will take a closer at this.

Thanks

**Comment by neilakoh** [comment]
@tyang1 Thank you so much, I got it all sorted out . . it was my mistake . . I forgot to the add the debug keystore SHA256 in the huawei console config . . it is all working now . . sorry, case closed
