### ISSUE TITLE
Background Color on Push Notification

### ISSUE THREAD

**Issue by jordyandreas** [OneSignal/react-native-onesignal#1132]
**Description:**
Hello, I'm trying to fill the background notification with color, but on the docs, it told me to use image rather than code it within use the color. here you can check it, https://documentation.onesignal.com/docs/android-customizations#background-images
So, I already use it, and didnt fill all at once. Anyone can help? please 
here some image that I want to implement on my push notification,
![photo!UNITO-UNDERSCORE!2021-01-06!UNITO-UNDERSCORE!09-59-53](https://user-images.githubusercontent.com/44167609/103724041-09d65780-5006-11eb-9de6-1685bf644887.jpg)

here my push notification after implement the background images,
![image](https://user-images.githubusercontent.com/44167609/103724088-22df0880-5006-11eb-93a2-2153e7d36eb8.png)

(your description here)

**Environment**
"react": "16.8.6",
"react-native": "0.60.5",
"react-native-onesignal": "^3.6.3",

**Steps to Reproduce Issue:**

* send new message push from app.onesignal.com or backend
* notification background color is always white

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Howdy,
I'm not sure what the issue is here. Can you please provide more information?

It looks from your screenshots like the background is being changed successfully.

**Comment by jordyandreas** [comment]
> Howdy,
> I'm not sure what the issue is here. Can you please provide more information?
> 
> It looks from your screenshots like the background is being changed successfully.

the first screenshot is example from another apps myIM3,
and the sec screenshot is my app notification, but does not cover the whole section like the first screenshoot.

actually I've done it using image background from documentation onesignal [https://documentation.onesignal.com/docs/android-customizations#background-images](url)
on android version 6 below and its fully cover the whole notification.
here's the screenshot:
![image](https://user-images.githubusercontent.com/44167609/104555497-93260380-5670-11eb-931f-b806b7e6d290.png)

!but when implementation on android version 8 above, it does not cover whole section like my sec screenshot.

**Comment by rgomezp** [comment]
Howdy,
Unfortunately there will always be limitations unique to specific Android OS versions. Presumably this is an issue with the notifications for newer Android versions.

**Comment by rgomezp** [comment]
Closing due to no response
