### ISSUE TITLE
[4.0.2] iOS: Argument 2 (RCTResponseSenderBlock) of setExternalUserId must not be null

### ISSUE THREAD

**Issue by diego-paired** [OneSignal/react-native-onesignal#1139]
**Description:**
Since upgrading to 4.0.2 from 4.0.1, the following error appears when calling `setExternalUserId`:
![image](https://user-images.githubusercontent.com/55058765/104091040-c2a0ce80-5272-11eb-8d62-443b310b4d24.png)

This error did not happen on 4.0.1, and the typescript definitions mark the second argument as optional.

**Environment**

    react: 17.0.1 => 17.0.1 
    react-native: ^0.64.0-rc.2 => 0.64.0-rc.2 
   "react-native-onesignal": "^4.0.2"

**Comment by rgomezp** [comment]
Howdy Diego,
Can you please include more information regarding the environment? e.g: iOS or Android, what version?

Also, including a code snippet would be useful.

In the meantime, please consider reverting back to `4.0.1`. 


Cheers

**Comment by rgomezp** [comment]
Howdy Diego,
Thank you for reporting this issue. Can you please provide more information regarding the exact environment?

Also, what does your call look like? Can you please include a code snippet?

From looking at the code, it looks like your issue might be able to be resolved by passing an empty callback for now as a temporary workaround:

```js
()=>{}
```

We will look to implement a long term fix for this in the future. 

Cheers

**Comment by alimek** [comment]
Faced the same issue when fast-refresh happened, but not every time 🤔  passing empty handler fixing issue for now

**Comment by rgomezp** [comment]
Howdy,
This should now be resolved in `4.0.3`

Enjoy!
