### ISSUE TITLE
ITMS-90683: Missing Purpose String in Info.plist in latest 4.0.3

### ISSUE THREAD

**Issue by Iamscaredofcode** [OneSignal/react-native-onesignal#1146]
After uploading apple sends you the mail with the following warning message:

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data.

The mail does not state that it is this package but I always keep my packages up2date and just added this package before releasing. Does anyone else experience this?

**Comment by rgomezp** [comment]
Howdy, please follow our full issue template when opening issues
