### ISSUE TITLE
Android, lib version 4.0.3: setNotificationOpenedHandler does not capture events when app in closed state

### ISSUE THREAD

**Issue by kurtgn** [OneSignal/react-native-onesignal#1148]
**Description:**

When the app is in closed state, the device receives a notification, and I tap a notification to open the app, a handler set by the `setNotificationOpenedHandler` method does not fire.

**Environment**

I am using `react-native-onesignal 4.0.3`. My device is `Samsung A10` running `Android 10`.

I migrated from 3.9.3, where I had a handler set by

```
OneSignal.addEventListener('opened', openResult => {
  console.log('OneSignal.opened');
  ....
});
```

and this handler got fired even when the app gets open from a closed state after tapping on notification. Now it does not.

**Steps to Reproduce Issue:**

1. npm install react-native-onesignal@4.0.3 
1. add to index.js the following:

```
OneSignal.setAppId('....');
OneSignal.setNotificationOpenedHandler(openResult => {
  console.log('setNotificationOpenedHandler', openResult);
});
```

1. swipe away the app to close it;
1. send yourselves a notification, receive it and tap on it.

**Anything else:**

Also, what's up with the `received` listener? the one that was configured like so

```
OneSignal.addEventListener('received', .... );
```

It seems this feature has completely gone starting from version 4, am I right?

**Comment by kurtgn** [comment]
created a brand new app where this issue is not reproducible. There's something with my old app. Closing

**Comment by joelrorseth** [comment]
@kurtgn Did you end up identifying or resolving your issue? I also can't seem to get `setNotificationOpenedHandler` to fire, when the app is open or closed. I am using `iOS Simulator (iOS 14.3)`, `react-native-onesignal 4.0.3`,

**Comment by kurtgn** [comment]
@joelrorseth well, in my case I had errors when setting this handler in `index.js`, and fixed them by setting it inside `componentDidMount` of `App.js`. Hope this helps.
