### ISSUE TITLE
How do I send silent notifications on Android?

### ISSUE THREAD

**Issue by anttitakalahti** [OneSignal/react-native-onesignal#115]
Do you plan to add support for silent notifications?

I would love to send notifications to the App to tell it to reload the data like it works on iOS with empty data and content_available=true

I asked about it from OneSignal and I got a reply from them:
"You can follow our Background Data and Notification Overriding guide for Android silent notifications but this can only be used with Native Java code." https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding

**Comment by anttitakalahti** [comment]
perhaps my real issue is that the onNotificationOpened does not fire when sending an empty notification to android. it works fine on iOS when also sending content_available: true

**Comment by deepmehtait** [comment]
@anttitakalahti : onNotificationOpened is not fired on android when we get notifications. It only gets fired up when we click on actual notifications. Any one planning to implement this silent notification? I am looking for someone who can help me out in implementing silent notifications.

**Comment by anttitakalahti** [comment]
I would love to hear someones comment on this. Is this an issue with react native or what? I don't see any reason why this should filter out notifications where content is empty (from RNOneSignal.java):

https://github.com/geektimecoil/react-native-onesignal/blob/master/android/src/main/java/com/geektime/reactnativeonesignal/RNOneSignal.java#L150

**Comment by avishayil** [comment]
It is a feature that currently not available using the current SDK.
We'll consider adding this in the next versions if the RN platform allows it.
Thanks!

**Comment by anttitakalahti** [comment]
Thanks Avishay! I really hope that you will support this soon. It works great on iOS and I can refresh the Customer View without disturbing them and without needing to poll for new data.

**Comment by tapz** [comment]
@avishayil Any plans to implement this soon? It's been several months since this was asked and this should be trivial to implement.

**Comment by bitsal** [comment]
Please take a look at my PR https://github.com/geektimecoil/react-native-onesignal/pull/266
