### ISSUE TITLE
error: cannot find symbol import com.onesignal.OSNotificationPayload; 

### ISSUE THREAD

**Issue by jallakalyan** [OneSignal/react-native-onesignal#1151]
**Description:**

I am trying to extend the Notification Service with OneSignal.
Followed this link : https://documentation.onesignal.com/docs/service-extensions#android-notification-extender-service

Covered all the fixes given here:
https://github.com/OneSignal/react-native-onesignal/issues/764
https://github.com/OneSignal/react-native-onesignal/pull/824

None of the fixes works for me.

Kindly help as I am new to React Native.

**Environment**

"react-native": "^0.63.3",
"react-native-onesignal": "^4.0.3",

**Steps to Reproduce Issue:**

Created a new file in \android\app\src\main\java\com\[package_name]\NotificationExtenderExample.java

added below service under AndroidManifest.xml as below :
   <service android:name=".NotificationExtenderExample" 
   android:permission="android.permission.BIND_JOB_SERVICE" 
   android:exported="false">
  <intent-filter>
    <action android:name="com.onesignal.NotificationExtender" />
  </intent-filter>
</service>

react-native run-android
gives me following error:
\android\app\src\main\java\com\name\NotificationExtenderExample.java:9: error: cannot find symbol
import com.onesignal.OSNotificationPayload;
                    ^
  symbol:   class OSNotificationPayload
  location: package com.onesignal
\android\app\src\main\java\com\name\NotificationExtenderExample.java:10: error: cannot find symbol
import com.onesignal.NotificationExtenderService;
                    ^
  symbol:   class NotificationExtenderService
  location: package com.onesignal
\android\app\src\main\java\com\name\NotificationExtenderExample.java:11: error: cannot find symbol
import com.onesignal.OSNotificationReceivedResult;
                    ^
  symbol:   class OSNotificationReceivedResult
  location: package com.onesignal

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience.

Try updating to the latest SDK version and make sure to open Android Studio to allow a gradle sync.

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by drajat824** [comment]
I updated react-native-onesignal to 4.1.0 with latest SDK 4.3.4, but the problem is still same. Is there any solution ??

**Comment by drajat824** [comment]
> Closing due to no response

Hi @rgomezp, I updated react-native-onesignal to 4.1.0 with latest SDK 4.3.4, but the problem is still same. Is there any solution ??
