### ISSUE TITLE
Does not work or I don't know what can be

### ISSUE THREAD

**Issue by luan-nvg** [OneSignal/react-native-onesignal#1153]
no error, nothing arrives on the oneignal website https://app.onesignal.com/apps/XXX/players

Versão do React:
``` "react-native": "^0.60.6", ```

I didn't make the change in android/build.gradle because it broke the project when I put it as described in the documentation
 ``` classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.9, 0.99.99]'  ``` etc..

I added (not knowing if it works but I didn't see a change) in

```manifestPlaceholders
                             onesignal_google_project_number: "REMOTE"] ```

```

await OneSignal.getDeviceState()

```
   hasNotificationPermission: true
   isEmailSubscribed: false
   isPushDisabled: false
   isSubscribed: false
   userId: "xxxxx"
```

**Comment by rgomezp** [comment]
Howdy,
Please follow our issue template when opening issues.

Regardless this sounds like something that our support team could help you resolve. Head over to our support channel at OneSignal.com for further assistance.
