### ISSUE TITLE
How to not show notification with setNotificationWillShowInForegroundHandler

### ISSUE THREAD

**Issue by myckhel** [OneSignal/react-native-onesignal#1158]
**Description:**

From the doc [setnotificationwillshowinforegroundhandler](https://documentation.onesignal.com/docs/react-native-40-api-reference#setnotificationwillshowinforegroundhandler-function)
it stated that `Use this handler to decide if the notification should show or not.`

|Field | Description|
|----|----|
|complete() |**Show Notification**: Pass the notification to this function in order to display it while the app is in the foreground. **Silence Notification**: If you would like to silence the notification, call complete() with no argument.|
|getNotification() | Retrieves the notification object. This returned object is of class (OSNotification).|

But the doc never mentioned hiding the notification.
then i assumed not invoking the `complete()` method will make the notification not to show but it didn't work and still shows the notification after some delayed time.

**Environment**

**Steps to Reproduce Issue:**

Try not to invoke the `complete` method and the notification will show after some delayed time

```js
OneSignal.setNotificationWillShowInForegroundHandler(notifReceivedEvent => {
    console.log("OneSignal: notification will show in foreground:", notifReceivedEvent);
});
```

**Anything im missing?**

**Comment by rgomezp** [comment]
Howdy,
Indeed. The problem is you did not call the `complete` function.

It should be:

```js
OneSignal.setNotificationWillShowInForegroundHandler(notifReceivedEvent => {
    notifReceivedEvent.complete();
    console.log("OneSignal: notification will show in foreground:", notifReceivedEvent);
});
```
