### ISSUE TITLE
iOS Permissions Prompt does not allow for Sounds & Badges

### ISSUE THREAD

**Issue by fedenelli** [OneSignal/react-native-onesignal#1161]
**Description:**
After upgrading to v4, using the promptForPushNotificationsWithUserResponse() method only gives app permission to alert on Notification Center, without Lock Screen or Banners.
In addition to that, Sounds & Badges permissions are also missing.

**Environment**
react-native 0.63.4
react-native-onesignal 4.0.3

**Steps to Reproduce Issue:**

1. Initialize onesignal using setAppId()
1. Check permission status using getDeviceState()
1. Ask for permissions using promptForPushNotificationsWithUserResponse()

![s](https://user-images.githubusercontent.com/28237870/107532932-27668600-6b9d-11eb-94d4-bcc573964a00.png)

**Comment by rgomezp** [comment]
Howdy,
Are you using provisional push notifications only?

![IMG_0014](https://user-images.githubusercontent.com/11739227/109877075-312d5780-7c38-11eb-8fd2-ca9c7250a3d1.jpg)

Also, are you seeing a prompt like this one? And what capabilities are listed if so?

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by empato-limited** [comment]
@rgomezp hey ... same things happened to us ... when u r asking about provisional notifications are u asking if we checked 
```
Enable iOS 12 direct to history
```
on the setup process?
