### ISSUE TITLE
Update IOS Dependency to 3.2.0

### ISSUE THREAD

**Issue by azai91** [OneSignal/react-native-onesignal#1163]
**Description:**
Onesignal-IOS-SDK 3.2.0 came out today (https://github.com/OneSignal/OneSignal-iOS-SDK). Can we bump the iOS version in this library?

**Comment by tomwhale** [comment]
Would be great to see this happen too. The current version of the SDK is causing deep-linking issues for us.

This specifically: https://github.com/OneSignal/OneSignal-iOS-SDK/issues/777

**Comment by luco** [comment]
Isn't just updating the podspec version?

> https://github.com/OneSignal/react-native-onesignal/blob/master/react-native-onesignal.podspec#L25
