### ISSUE TITLE
How can I get all onesignal notifications? (Android)

### ISSUE THREAD

**Issue by akhlopyk** [OneSignal/react-native-onesignal#1165]
Hi!

I need to get all onesignal notifications from react-native to be able to dismiss the correct one using its ID. 

Any advice?

**Comment by rgomezp** [comment]
Howdy,
If you only care about ones that were displayed by using the app you can use `setNotificationWillShowInForegroundHandler` to get the id.

If you really want all notifications currently in the notification shade for your app you can use the Android Native API [`getActiveNotifications`](https://developer.android.com/reference/android/app/NotificationManager#getActiveNotifications())
