### ISSUE TITLE
OneSignal.sendTag successful but it does not change the tags at onesignal

### ISSUE THREAD

**Issue by bitcoinvsalts** [OneSignal/react-native-onesignal#117]
I run OneSignal.sendTag and verify the tags are changed with 

        OneSignal.getTags((receivedTags) => {
          console.log(receivedTags);
        })

I can see it did the change 

but when I look at https://onesignal.com/apps/axbe-2axxxa4-4c9d-a1b3-38d630926927/players

the tags did not change.

It works fine with ios but not with android.

**Comment by elmato** [comment]
I'm running into the same problem on android.

```
		OneSignal.configure({
			onIdsAvailable: function(device) {
				console.log('UserId = ', device.userId);
				console.log('PushToken = ', device.pushToken);

				OneSignal.sendTags({"account" :"test-test"});
				OneSignal.getTags((receivedTags) => {
					console.log('TAGS=>', receivedTags);
				});
			
			},
			onNotificationOpened: function(message, data, isActive) {
				console.log('MESSAGE: ', message);
				console.log('DATA: ', data);
				console.log('ISACTIVE: ', isActive);
			}
		});
```


The OneSignal.getTags function returns the tags ok, but they don't appear in the onesignal dashboard.

It is ok to call **sendTags** inside the **onIdsAvailable** callback?

@jsappme can you post your details on when are you calling sendTags?

**Comment by bitcoinvsalts** [comment]
If you change one tag you need to use sendtag() instead of sendtags().

Hervé

**Comment by avishayil** [comment]
Thanks for clarifying that :>

**Comment by gezamiklo** [comment]
sendTags is executed asynchronously. If getting tags immediately there's almost no chance to see the new tags.

**Comment by Nickersoft** [comment]
I'm running into this same issue, even after adding a 30-second timeout around my `.getTags()` call, two years later.. was this issue ever formally resolved? Is it a confirmed bug? What's the fix?

**Comment by gezamiklo** [comment]
@Nickersoft Please see the reference: https://documentation.onesignal.com/docs/ios-native-sdk#section--sendtag-

As you can see, there are two optional parameters: onSuccess, onFailure. Using them you can handle if the response has finished and also see it's success or failure.

Yeah, it can take quiet much time to respond. Hope this helps you at least to debug the requests. An ugly solution would be to block the UI (ouch!).

One viable solution is to store flags locally (CoreData or UserDefaults). When you need to deal with switches to show if the notification is active, you can rely on those flags. When the refresh completed, you can update those flags locally, even by executing getTags(). This helps to keep the UI fluent and quick. Just be sure to sync those flag when appropriate.

**Comment by Nickersoft** [comment]
Hey @gezamiklo! Thanks for the quick response, and for pointing out those callbacks I seemed to have missed. However, checking this repo's code, it would seem that [those parameters are never actually passed from JS to the iOS SDK](https://github.com/geektimecoil/react-native-onesignal/blob/master/index.js#L194), so I'm wondering if that's functionality this repo is missing...? 

Additionally, could you elaborate on what you mean by flags?

**Comment by Nightsd01** [comment]
@Nickersoft unfortunately iOS has these callbacks but Android does not. To keep the React-Native SDK consistent, we don’t implement the callbacks in iOS. 

Because of the way the Android SDK adds the request to a queue and doesn’t execute immediately (iOS does something similar), it can take a relatively long amount of time for the request to actually execute and complete. 

Some developers call this method _far_ too frequently, so we don’t immediately execute the request. 

We have been considering implementing callbacks for `sendTags()` in Android but it adds some complications we need to consider.

**Comment by Nickersoft** [comment]
Hm, I suppose that makes sense. However, regardless of how long I wait, new tags never actually appear in the OneSignal console. How long should I be waiting for those tags to send? I send out tags one a user logs in, and theoretically once the app stays open those requests should all complete.

**Comment by gezamiklo** [comment]
Hi @Nickersoft! Flag is an old fashioned name of a Boolean variable. Guess it's easier to show than to explain:

    // Storing
    UserDefaults.standard.set(true/false, forKey: "DefaultKeys.MyFirstNotification")
    UserDefaults.standard.synchronize()
    
    //Reading
    UserDefaults.standard.bool(forKey: "DefaultKeys.MyFirstNotification")

I always create enums for keys, because it is very easy to type with code completion and yout avoid mistyping.

**Comment by Nickersoft** [comment]
@gezamiklo What exactly does this achieve in the context of the original ticket? Not sure I'm following completely..

**Comment by gezamiklo** [comment]
@Nickersoft you asked what did I mean by flags.

I guess you want to keep track of active tags. Storing the state of each locally can help reducing the amount of network requests. All my apps have a Settings screen on which the user can manage the notification subscriptions. If the user changes some tags, these flags are changed locally and the tags are sent to OneSignal. If the callback fails I reset the corresponding flag to the original state, so the local state is in sync with the remote one.

**Comment by Nickersoft** [comment]
@gezamiklo Haha I realize that.. I guess I was confused as to why they were brought up in the first place. While that advice is sound, my bigger issue right now though is the fact that calling `.sendTag` or `.sendTags` isn't sending any tags to the server at all, no matter how long I wait. They never appear in the OneSignal player list, and I'm not exactly sure if this still is still a bug or how to even approach debugging the issue.

Once tags *are* working, I most likely will use a similar structure to reduce network requests, as you mentioned.

**Comment by ivanchimeno** [comment]
@gezamiklo Are you sure this is a OneSignal issue? I'm debugging my Android app right now and both`.sendTag` and `.sendTags` seem to be working correctly.

**Comment by gezamiklo** [comment]
@ivanchimeno I did not say that. For me OneSignal works well too. What I faced is the delay between sending tags and calling completion handlers. I do not consider this as a problem. It works, you just need to wait the request to finish before trying to get the tags back.

@Nickersoft I misunderstood your problem though. You say yout tags never appear on OneSignal's end. :(

**Comment by ivanchimeno** [comment]
@gezamiklo  Oh, my bad I must've misunderstood :)

**Comment by zh3ngyuan** [comment]
android works correctly for me, but ios not working when using react-native-onesignal@3.1.4, any update?

**Comment by jkasten2** [comment]
@ALexander4295502 Can you try the latest 3.2.4 version?
If you are still seeing issue you can use `setLogLevel` to see the network calls OneSignal is making in the Xcode log.
https://documentation.onesignal.com/docs/react-native-sdk#section--setloglevel-

**Comment by rahamin1** [comment]
- I have been using version 3.1.4 on Android until now.
- Tried to upgrade to 3.2.6, tags are not set. 
- Went back to 3.1.4, works again.

**Comment by magick93** [comment]
> Tried to upgrade to 3.2.6, tags are not set.
> Went back to 3.1.4, works again.

Same
