### ISSUE TITLE
IOS Build Failing with: "ld: library not found for -lreact-native-onesignal"

### ISSUE THREAD

**Issue by quinlanjager** [OneSignal/react-native-onesignal#1170]
**Description:**

Followed the [React Native & Expo SDK Setup guide](https://documentation.onesignal.com/docs/react-native-sdk-setup). After completing step 5, I attempted to build my app in XCode. The build failed with the following error:

```
ld: library not found for -lreact-native-onesignal
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I tried following the [manual linking steps](https://github.com/OneSignal/react-native-onesignal/issues/604) but hit the same error. Wondering anyone figured out a solution to this?

Thanks!

**Environment**

* Added SDK to project with `yarn add react-native-onesignal`
* react-native-onesignal: 4.0.3
* react-native: 0.63.3
* XCode: 12.4
* Cocoapods: 1.10.1

**Podfile**

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 3.0', '< 4.0'
end

target 'WellnessReactNative' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'Stripe', '~> 19.0.1'
  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-config'
        phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
        phase.shell_script = "cd ../../"\
        " && RNC_ROOT=./node_modules/react-native-config/"\
        " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
        " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"

        target.build_phases << phase
        target.build_phases.move(phase,0)
      end
    end
    # flipper_post_install(installer)
  end
end
```

**Steps to Reproduce Issue:**

1. Follow the [React Native & Expo SDK Setup guide](https://documentation.onesignal.com/docs/react-native-sdk-setup)
1. Build the app in XCode

**Comment by rgomezp** [comment]
Howdy,
Try running `pod deintegrate && pod install` from your `ios` directory. If that doesn't work, try running a clean build. If none of those work, try deleting your Derived Data.

**Comment by quinlanjager** [comment]
Hi @rgomezp,

Thanks for replying! I gave your suggestions a shot but encountered the same error. 

I'm thinking at this point I need to link the library manually because the autolinking isn't working. I set up the manual linking after clearing everything. And I'm seeing the following error in RCTOneSignalExtensionService.m:

```
node_modules/react-native-onesignal/ios/RCTOneSignal/RCTOneSignalExtensionService.m:4:9: 'OneSignal.h' file not found
```
Checking out the "Frameworks" directory in the `RCTOneSignal.xcodeproj` it seems like the `OneSignal.h` reference is pointing to `node_modules/react-native-onesignal/ios/OneSignal.h`. But this file doesn't exist. Could that be effecting the manual linking?

**Comment by hugoh59** [comment]
Any update on this ? Facing the same issue after updating to Xcode 12.

**Comment by quinlanjager** [comment]
Hi @hugoh59,

The issue for me was that my Cocoapods didn't update my library search paths. Still not sure why...

I fixed my install by manually adding `${PODS_CONFIGURATION_BUILD_DIR}/react-native-onesignal` to the **Library Search Paths**  (Build Settings > Search Paths > Library Search Paths) in my main target.

Hope this helps!

**Comment by vokecodes** [comment]
You need to check the platform version in your Podfile and make it match your main target deployment info and one signal target

**Comment by Svarto** [comment]
> You need to check the platform version in your Podfile and make it match your main target deployment info and one signal target

could you expand on this a bit more? I am running into the same issue... what do you mean platform version in Podfile?

**Comment by vokecodes** [comment]
Here's a screenshot with the platform version highlighted

<img width="614" alt="Screenshot 2021-08-29 at 7 09 18 AM" src="https://user-images.githubusercontent.com/24590058/131240593-ad71e717-8557-4595-ba8a-589dc4f80848.png">

**Comment by mszczotarz-dev** [comment]
Your OneSignalNotificationServiceExtension iOS version has to match your app iOS version. In OneSignal docs they said to set it to 10.0 but if your app has higher version it will produce that error. I've just bumped up this to 11.0 like my app and worked like a charm. 👍

**Comment by kanyo33** [comment]
The "library not found" errors occur most of the time because installing the react-native node package and running pod install is often not enough. 
The error might go away after running a clean build in xcode using the xcworkspace file. After that running "npm run ios" or "npm start" in your termal should work again. It sounds like the above answer helped a lot of people, which is great. Just wanted to highlight that this solution is related since you need to run a clean build using the xcworkspace folder to update the IOS version.
