### ISSUE TITLE
Native module cannot be nul

### ISSUE THREAD

**Issue by arnaudambro** [OneSignal/react-native-onesignal#1171]
**Description:**

Hi there, 

when I try to `import OneSignal from 'react-native-onesignal';`, I get this error

```error
Requiring module "node_modules/react-native-onesignal/src/index.js", which threw an exception: Invariant Violation: Native module cannot be nul
```

**Environment**

1. What version of the OneSignal React-Native SDK are you using? 4.0.3

**Comment by rgomezp** [comment]
Howdy,
Is this just occurring in iOS?

Try running `pod install` from your `ios` directory.

[Similar issue](https://github.com/react-native-push-notification-ios/push-notification-ios/issues/43)

**Comment by arnaudambro** [comment]
I think I found my bug

![image](https://user-images.githubusercontent.com/31724752/110347966-71724880-8031-11eb-9d47-35a870b2d548.png)

I don't know how it happened, but I had in my `/ios/myapp.xcodeproj/project.pbxproj` file, for the Debug config of `OneSignalNotificationServiceExtension` target and the `Release`, I didn't have the same Bundle Identifier.

I changed to have it, now it seems to work.
