### ISSUE TITLE
postNotification throw error when using playerId

### ISSUE THREAD

**Issue by anwersolangi** [OneSignal/react-native-onesignal#1174]
**Description:**

On android when passing playerId in the  in postNotification, i am receiving an error of `com.facebook.react.bridge.readablenativemap cannot be cast to java.lang.string` i have googled the issue and already found this issue but the solution did not work for me, i have also tried to pass the array of string and only a string but did not help out.
here are my codes: 
`let contents = {en: auth().currentUser.displayName};
            let data = msgs[0].text;
            OneSignal.postNotification(
              contents,
              data,
              [onesignalId.toString()],
              {},
            );`

**Environment**
"react-native-onesignal": "^4.0.3"
"react-native": "0.63.4"
Android: Physical Device.

**Steps to Reproduce Issue:**

1. Install the OneSignal SDK using npm into your project
1. Initialize the SDK in Android
1. Save the playerId.
1. Send the postNotification.

**Comment by rgomezp** [comment]
Howdy,
You need to stringify your payload. The function was changed in the major release (v4) to accept a payload fit for our REST API. 

Please read more about this [here](https://documentation.onesignal.com/docs/react-native-40-api-reference#postnotification-function-as-of-beta4).

Enjoy!
