### ISSUE TITLE
Does `OneSignal.removeNotification(id)` remove the sent-messages in the onesignal website dashboard?

### ISSUE THREAD

**Issue by astroana** [OneSignal/react-native-onesignal#1176]
Does 

`OneSignal.removeNotification(id);`

removed the sent-messages in the onesignal website dashboard?

if not how can I clear the one on the website dashboard?

i tried to implement it on open handler like this

```
OneSignal.setNotificationOpenedHandler(openedEvent => {
    console.log("OneSignal: notification opened:", openedEvent);
    const { action, notification } = openedEvent;
    const id = notification.notificationId;
    
    OneSignal.removeNotification(id);
    console.log('removed notification', id);
  });
```

I get the correct id of the notification in the dashboard but in the app I get this error when I click the notification.

`java.lang.String cannot be cast to java.lang.Double`

But if I use 

`notification.androidNotificationId`

I dont get any error it opens the app but nothing happens nothing gets removed.

what is the right way to remove the notification? and 
How long does sent messages is stored in the dashboard? 

React Native ver: 0.63.4
Platform: Android

**Comment by rgomezp** [comment]
Howdy,
No. This removes the notification from the notification shade.

[Function reference](https://documentation.onesignal.com/docs/react-native-sdk#removenotification-function)
---

The reason you're getting that error is Android IDs are number values whereas OneSignal notification identifiers are strings (UUIDs).

I will have our support team respond regarding what you're really trying to do which is remove notifications from the dashboard. In the meantime, can you please provide some context as to why you're trying to do that? Any feedback is always welcome.

**Comment by astroana** [comment]
> In the meantime, can you please provide some context as to why you're trying to do that?

It's because most of my notifications comes from Incoming calls and missed calls and those data are already stored in firestore, I don't want to populate my onesignal sent messages with too many notifications messages that is why I want to delete the notifications in the dashboard once I click the notification banner. And the clear button on the sent messages dashboard does not clear all the messages, I can only delete it one by one manually.

**Comment by rgomezp** [comment]
I see. But why is it a problem that you have messages stored there? You can send unlimited notifications with OneSignal.

Update: I checked with the team and there is no way to delete all notifications currently.

**Comment by astroana** [comment]
didn't know it was unlimited, then it's not going to be a problem no matter how many sent messages is stored there. I thought there is going to be a limit at some point. Now I understand, thanks.
