### ISSUE TITLE
In IOS- my One signal prod app user's session is recorded in the one signal dev app when installing prod build on my iPhone/simulators

### ISSUE THREAD

**Issue by Shashank123sprive** [OneSignal/react-native-onesignal#1177]
I've created two different one signal apps, one for production and the other for development which are Myapp-Dev and Myapp-Prod, and these two one signal apps are configured in the production scheme with production one signal app id, and in the development scheme with the dev one signal app id. Also, the bundle ids are different for these two schemes, and the apple push certificates are different and uploaded in the one signal Myapp-Dev and Myapp-Prod app according to the schemes. Now if I install the prod scheme in my iOS device, then I can see the user session is being recorded in the one signal dev app, but it should be recorded into the OneSignal prod app. This is very confusion, how this cross over can happen? and due to this the user's details from production is getting accumulated into the one signal dev app i.e Myapp-Dev.

Can anyone help me on this?

FYI, I've used different CSR in order to generate the dev and prod apple push certificates(with different bundle ids), therefore each scheme is pointing to a different app in TestFlight, so there isn't any connection between these two one signal applications, which are Myapp-Dev and Myapp-Prod.

Any help/suggestions would be really appreciable!

**Comment by rgomezp** [comment]
Howdy,
**When you say "recorded" what are you referring to exactly?** Is it the _session count_?

Also, how are you installing the apps? Have you tried installing an app, testing it, uninstalling it, and then installing the second app to see if you still see the problem?

**Comment by Shashank123sprive** [comment]
hi @rgomezp ,

Thanks for your response. 

The issue which I've specified earlier is not happening anymore, but I've another issue with one signal, which is as follows:

When we're installing the app(on iOS device with OneSignal SDK configured i.e **react-native-onesignal- ^3.6.3**) the device session is getting populated in one signal's dashboard under Audience->All Users, but the **external user id** is not populating for my **player id**. I have set the log level to verbose in order to check the what is happening when I'm initiating the one signal listener, and setting the one signal **external user id**.
**but I can see that the one signal app id which I've defined in the AppDelegate.m file (**813aa25-8bd8-41e5-9d3f-387e6XXXX**) is not matching with the one signal app id which is coming in the log** i.e at 

VERBOSE:HTTP Request (OSRequestRegisterUser) with URL: https://api.onesignal.com/players, with parameters: {
  "app_id" : "405f33b8-ab67-4f30-95ab-75182574XXS",
  "net_type" : 0,
  "test_type" : 1,
  "ios_bundle" : "com.sprive.mobile.ios",
  "device_type" : 0,
  "sdk_type" : "react",
  "sdk" : "021601",
  "identifier" : "IIIIIIIIII",
  "language" : "en-IN",
  "device_os" : "12.4.2",
  "game_version" : "8",
  "timezone" : 19800,
  "ad_id" : "XXXXXXXX",
  "notification_types" : 31,
  "device_model" : "iPhone6,2",
  "carrier" : "AirTel"
}

VERBOSE: network response (OSRequestRegisterUser): {
errors = (
"App with id: 405f33b8-ab67-4f30-95ab-75182574XXS does not exist"
);
}

So, at the above line I can see the app id is different than the one I've defined in AppDelegate.m which is correct wrt the app I've created in one signal platform. FYI the same code base is working fine in android platform.

Would you please let me know what is the reason behind the external user id not appearing, and due to this I can't send push notifications to the subscribed users(on iOS platform). FYI in case of android platform with the same codebase the external user id is getting populated: 

The code to set the external user id : 

**OneSignal.setExternalUserId(myExternalUserID);**

It would be really helpful, if you can help me to resolve this.

**Comment by rgomezp** [comment]
Howdy,
Please check your implementation and perhaps search for the APP id you are seeing in the logs. Somehow some extra characters (XXS) are getting concatenated there.

The app id should be a UUID format.

405f33b8-ab67-4f30-95ab-75182574XXS is [not a UUID](https://www.freecodeformat.com/validate-uuid-guid.php)

**Comment by rgomezp** [comment]
Closing due to no response
