### ISSUE TITLE
setNotificationWillShowInForegroundHandler is not triggered on Huawei for silent notifications

### ISSUE THREAD

**Issue by razvanbretoiu** [OneSignal/react-native-onesignal#1180]
**Description:**

Hello, 

I integrate OneSignal into my App to be used on Huawei devices and the `setNotificationWillShowInForegroundHandler` is not triggered when I'm sending a silent notification. I've tested with normal notification and those are working fine.

I looked over the documentation and I don't understand the l[imitation for react-native](https://documentation.onesignal.com/docs/data-notifications#limitations-of-non-native-sdks), there is no way to have silent notifications without having native code?

I've tried with the exemple from docs:

```
OneSignal.provideUserConsent(true);
      OneSignal.setLogLevel(6, 0);
      OneSignal.setAppId('0d16b016-09d9-4edf-b701-69cce985d80e');
      
      /* O N E S I G N A L  H A N D L E R S */
      
      OneSignal.setNotificationWillShowInForegroundHandler(
        (notifReceivedEvent) => {
          console.log('OneSignal: notification will show in foreground:', notifReceivedEvent );
          let notif = notifReceivedEvent.getNotification();
          
          const button1 = {
            text: 'Cancel',
            onPress: () => { notifReceivedEvent.complete() },
            style: 'cancel',
          };
          
          const button2 = {
            text: 'Complete',
            onPress: () => { notifReceivedEvent.complete(notif) },
          };
          
          Alert.alert('Complete notification?', 'Test', [button1, button2], { cancelable: true });
        },
      );
```

**Environment**

```
"react-native-onesignal": "^4.0.4",
"react-native": "0.63.3",
```

**Steps to Reproduce Issue:**

1. Create a simple react-native project
1. Install the OneSignal SDK using npm into your project
1. Configure OneSignal for Huawei
1. Create a silent notification with this payload

```
{
    "app_id": "<app_id>",
    "include_player_ids": ["<user_id>"],
    "data": {"test": "test"},
    "huawei_msg_type": "data",
    "content_available": 1
}
```

**Anything else:**

### Android Logs
```
W/OneSignal: remoteNotificationReceivedHandler not setup, displaying normal OneSignal notification
D/OneSignal: Running destroyTimeout with runnable: com.onesignal.OSNotificationReceivedEvent$1@12c7fd0
D/OneSignal: Saving Notification job: OSNotificationGenerationJob{jsonPayload={"custom":"{\"i\":\"d29d48a3-aa91-4ca5-85a9-120d47ff41a9\",\"a\":{\"abc\":1}}"}, isRestoring=false, isIamPreview=false, shownTimeStamp=1614889769, overriddenBodyFromExtender=null, overriddenTitleFromExtender=null, overriddenSound=null, overriddenFlags=null, orgFlags=null, orgSound=null, notification=OSNotification{notificationExtender=null, groupedNotifications=null, androidNotificationId=-1, notificationId='d29d48a3-aa91-4ca5-85a9-120d47ff41a9', templateName='', templateId='', title='null', body='null', additionalData={"abc":1}, smallIcon='null', largeIcon='null', bigPicture='null', smallIconAccentColor='null', launchURL='null', sound='null', ledColor='null', lockScreenVisibility=1, groupKey='null', groupMessage='null', actionButtons=null, fromProjectNumber='null', backgroundImageLayout=null, collapseId='null', priority=0, rawPayload='{"custom":"{\"i\":\"d29d48a3-aa91-4ca5-85a9-120d47ff41a9\",\"a\":{\"abc\":1}}"}'}}
D/OneSignal: Notification saved values: full_data={"custom":"{\"i\":\"d29d48a3-aa91-4ca5-85a9-120d47ff41a9\",\"a\":{\"abc\":1}}"} notification_id=d29d48a3-aa91-4ca5-85a9-120d47ff41a9 opened=1 expire_time=259200
D/OneSignal: Running destroyTimeout with runnable: com.onesignal.OSNotificationOpenedResult$1@9c3fbc9
    Running startTimeout with timeout: 5000 and runnable: com.onesignal.OSNotificationOpenedResult$1@9c3fbc9
I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=d98c472d-5a4f-42a3-97ff-f241f9e515e1, tags={ com.onesignal.OSNotificationWorkManager$NotificationWorker } ]
D/OneSignal: Running complete from OSNotificationOpenedResult timeout runnable!
    OSNotificationOpenedResult complete called with opened: false

```

**Comment by razvanbretoiu** [comment]
I've ended up creating a `NotificationServiceExstension` that just emits the event `OneSignal-notificationWillShowInForeground`, but I'm curious why `notificationWillShowInForegroundHandler` is not called when there is a silent notification?

**Comment by rcidt** [comment]
I am seeing the same thing in my application. 

```java
if (clazzInstance instanceof OneSignal.OSRemoteNotificationReceivedHandler && OneSignal.remoteNotificationReceivedHandler == null) {
    OneSignal.setRemoteNotificationReceivedHandler((OneSignal.OSRemoteNotificationReceivedHandler) clazzInstance);
}
```

For some reason the expression `OneSignal.remoteNotificationReceivedHandler == null` is returning `false`

It's as if the handler is being defined somewhere else. I also triple-checked that `OneSignal.setRemoteNotificationReceivedHandler` is not being called at any point.

---

Unfortunately `notificationWillShowInForegroundHandler` does not work for my use case because I need to perform actions on the notification even when the app is in the background or killed.

---

Any help is greatly appreciated.

**Comment by rgomezp** [comment]
@razvanbretoiu ,
Thanks for opening the issue.

Please see our [documentation](https://documentation.onesignal.com/docs/react-native-sdk#setnotificationwillshowinforegroundhandler-function). As you can see, we were explicit about the naming of the function/handler: `notificationWillShowInForegroundHandler`. A silent notification doesn't "show" in the first place.

Were you able to achieve the full functionality you were looking for by using the service extension?

Also, you mentioned this only happens for Huawei devices? That doesn't sound right to me. Can you please confirm? If so, we will have to dig into that further.

---
@rcidt ,
Yes, as the naming implies, it only works for the **Foreground**. We have some feature requests about adding the functionality you are requesting for in the future.

You can track this in #1154

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by MariaLuiza-CS** [comment]
> 
hi, can you help me?
did you figure it out? i am with the same problem. I am using a diferent class that implements OSRemoteNotificationReceivedHandler, and for some reason the expression OneSignal.remoteNotificationReceivedHandler == null is returning false

**Comment by MariaLuiza-CS** [comment]
@rgomezp @rcidt 
hi, can someone help me?
did you figure it out? i am with the same problem. I am using a diferent class that implements OSRemoteNotificationReceivedHandler, and for some reason the expression OneSignal.remoteNotificationReceivedHandler == null is returning false.

**Comment by anniewey** [comment]
@rgomezp which listener should be used to receive the silent notification payload? i've implemented `NotificationServiceExtension` and able to receive the notification but couldn't get the payload on the JS side.

```
@SuppressWarnings("unused")
public class NotificationServiceExtension implements OSRemoteNotificationReceivedHandler {
    @Override
    public void remoteNotificationReceived(Context context, OSNotificationReceivedEvent notificationReceivedEvent) {
        OSNotification notification = notificationReceivedEvent.getNotification();
        notificationReceivedEvent.complete(notification)
     }
}
```

**Comment by artherrer** [comment]
@razvanbretoiu 

Can you show me the part of code to do your workaround?
