### ISSUE TITLE
[iOS] OneSignal.setEmail when email is null: bug in prod, no problem in dev

### ISSUE THREAD

**Issue by arnaudambro** [OneSignal/react-native-onesignal#1184]
**Description:**
`OneSignal.setEmail`:
In dev mode, no problem, never, even when the email is null.
But in production, when email is null, a bug is making the app crash

`NSInvalidArgumentException: *** -[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: nil argument`

It took me a few hours to find out that this was the problem. It would be nice to have also the crash in dev !

**Environment**

1. What version of the OneSignal React-Native SDK are you using? **4.0.5**
1. How did you add the SDK to your project (eg. npm) **npm**
1. Which platform ? **iOS**

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience.

Can you please include a full log with loglevel set to VERBOSE?

[Log reference](https://documentation.onesignal.com/docs/troubleshooting-ios#how-to-get-a-crash-log-from-an-ios-device)

**Comment by rgomezp** [comment]
Closing due to no response
