### ISSUE TITLE
Testing  logic Onesignal with detox

### ISSUE THREAD

**Issue by ToyboxZach** [OneSignal/react-native-onesignal#1187]
**Description:**
I am trying to test the logic with launching from a notification with detox and cannot get the setNotificationOpenedHandler to get called.

(your description here)

**Environment**
I am on 4.0.5 with NPM

I have the detox test:

```
describe.only("Run Notifications", () => {
 
  it("should open notification correctly", async () => {
    await device.relaunchApp({
      permissions: { notifications: "YES" },
      userNotification: {
        title: "hello",
        body: "test",
        trigger: {
          type: "push",
        },
        payload: "payload",
      },
    });
    await waitFor(element(by.id("NotificationsPage")))
      .toBeVisible()
      .withTimeout(1000);
  });
});
```

And I would expect this to call my handler

```

function onNotificationOpened(openResult) {
  console.log(payload)
  OpenNotificationsPage()
}

OneSignal.setNotificationOpenedHandler(onNotificationOpened);
```

This works normally but I want to be able to test it with detox, is there a way to do this with this package? Its not quite acting how I would expect it to.

**Comment by rgomezp** [comment]
Howdy,
I am not familiar with this testing framework.

That said, how are you causing the clicking of the notifications?

Also, what notification is being sent here? Is it a real OneSignal notification? If so, the network request needs to be made to OneSignal servers, then to Firebase/APNS, and then down to the device. This may take longer than 1 second if network conditions are slow.

Try running the single test and make sure you are getting the notification.

Also note: push notifications don't work on the iOS simulator.

**Comment by ToyboxZach** [comment]
This is a local testing framework so it should have nothing to do with hitting the server. What I want to test is just my onNotificationOpened callback within Onesignal. Based on your answer it seems that is based on loading stuff from the onesignal server and so there is no local testing equivalent? 

Based on your answer and its behavior, I'm assuming Detox is plugging into a different API on the app than OneSignal is listening to, so now I guess this is a feature request, having some way to mock locally the notifications so we can have a better end to end test would be super helpful.

In the meantime I'm sure I can find a way around the onesignal library and just find the method that detox ends up calling with their fake notification and running the same logic I do with the onesignal handler.

**Comment by rgomezp** [comment]
Howdy,
OneSignal does not use local notifications. Notification delivery requires network usage. You may not even be getting notifications in the first place. That's the first thing I would check.

**Comment by rgomezp** [comment]
Closing due to no response
