### ISSUE TITLE
setExternalUserId() is not working

### ISSUE THREAD

**Issue by EventFalconApp** [OneSignal/react-native-onesignal#1199]
I am sending UserId by using **setExternalUserId()**

```
OneSignal.setExternalUserId(userId.toString(), (r) => {
            console.log(r);
        });
```

After sent, I was getting below response

`{"push":true}`

But I don't get this response now. Event when I sent message from onesignal website. I didn't get any message in mobile.

Please help me to resolve 

FYI: I am using 4.0.6 version

**Comment by EventFalconApp** [comment]
Worked well now. Just forget to add  **OneSignal.setRequiresUserPrivacyConsent(false);** before SDK init

**Comment by MursiDirect** [comment]
> Worked well now. Just forget to add **OneSignal.setRequiresUserPrivacyConsent(false);** before SDK init

Thanks so much, you made my day
