### ISSUE TITLE
build-tools error

### ISSUE THREAD

**Issue by sercanov** [OneSignal/react-native-onesignal#12]
Throws "com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/local/opt/android-sdk/build-tools/23.0.1/aapt''

react native 0.21
on android

And readme is really need to should be checked.

**Comment by avishayil** [comment]
Thanks, we'll take a look on this.

**Comment by avishayil** [comment]
Hi @sercanov, the latest package should solve this issue.
Can you check?
Thanks!

**Comment by sercanov** [comment]
Yeah it solved the issue @avishayil thanks!
