### ISSUE TITLE
Is there a way to run code when notification is received?

### ISSUE THREAD

**Issue by senorgeno** [OneSignal/react-native-onesignal#120]
I need to sound an alarm when the app receives a notification and the app is in the background/phone is on lock screen. Would there be a way to do this? I was looking at the One Signal docs and saw this - https://documentation.onesignal.com/docs/ios-native-sdk#section--oshandlenotificationreceivedblock-

Would it be a matter of exporting this callback?

**Comment by avishayil** [comment]
Of course, you have the `onNotificationReceived` method.
