### ISSUE TITLE
Collision with android flipper

### ISSUE THREAD

**Issue by hyochan** [OneSignal/react-native-onesignal#1203]
**Description:**
After installing `"react-native-onesignal": "^4.0.6"`, android app crashed immediately on launch (fine in `iOS`) . I've discovered that the `Flipper` was the problem. I've tried to debug this but couldn't resolve this. After removing it with [guide here](https://github.com/facebook/flipper/issues/1326#issuecomment-653470251), I was able to make the build successes.

I could found out the issue after I've tried building in `release` mode which did not use the Flipper.

**Environment**

1. What version of the OneSignal React-Native SDK are you using?
  * 4.0.6
1. How did you add the SDK to your project (eg. npm)
  * `yarn`

**Steps to Reproduce Issue:**

1. Install the OneSignal SDK using yarn into your project
1. Try to run this in `React Native 0.64` project

**Comment by rgomezp** [comment]
Howdy,
Thank you for reporting the compatibility issue.

What version of Flipper is this issue occurring on?

**Comment by hyochan** [comment]
@rgomezp We were using flipper version `0.75.1`

**Comment by rgomezp** [comment]
Howdy,
We were able to resolve Android Flipper issues by updating React Native 0.64.1.

Please give that a try.

**Comment by rgomezp** [comment]
Closing due to no response
