### ISSUE TITLE
return a promise upon calling disablePush

### ISSUE THREAD

**Issue by Elabar** [OneSignal/react-native-onesignal#1207]
**Description:**

Is it possible to let disablePush function to return a promise instead of void? For now, I don't know whether the user actually disable the push successfully or not. 

I have a switch to let the user toggle notification on/off, right now, I just setState regardless. But sometime, disablePush call will fail. I tried to use addSubscriptionObserver to detect the change, but it looks like the observer is having some [bugs](https://github.com/OneSignal/OneSignal-Android-SDK/issues/749)?

**Environment**

1. OneSignal React-Native SDK version: 4.0.7
2. Installed via yarn

**Steps to Reproduce Issue:** N/A

**Anything else:** N/A

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Howdy,
Thanks for the report. I don't foresee us implementing this feature request due to the ability to add the subscription observer as you mentioned. We will try to get it fixed rather than adding this extra feature.

Cheers
