### ISSUE TITLE
[Android] Notifications not delivered when phone locked.

### ISSUE THREAD

**Issue by Abonive** [OneSignal/react-native-onesignal#121]
I get notification when the app is running. But when i lock the screen the notifications are not delivered. Can I configure it to get notifications on when the screen is locked?

**Comment by jkasten2** [comment]
@Abonive Can you list the Android version and device model?

Please see the following guide as well.
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown

**Comment by bitsal** [comment]
I have the same issue.
Android 5.0.2, Xaiomi Mi4i, auto-start configured properly based on doc you shared.

Even when my device is not locked, the application is not running.

**Comment by Abonive** [comment]
My bad, i haven't read find the part in onesignal docs. Solved

**Comment by bitsal** [comment]
@Abonive does it work for you in case the app is not opened?

**Comment by Abonive** [comment]
Well, when you once open app it works even when the app isn't active but app has to be working in the background.

**Comment by bitsal** [comment]
@Abonive it's clear but what about use case when the app is closed. Won't it work at all or are there any dancing with settings? Or probably it doesn't work only with react native and works for native Android or iOS application. Any thoughts?

Thank you in advance!

**Comment by Abonive** [comment]
I haven't looked into that, that much. But i wonder too if you can make it listen for notifications when the app is totally closed.

**Comment by bitsal** [comment]
@jkasten2 do you have any answer?
