### ISSUE TITLE
notifications received on android do not appear "floating alert" with open application (appears only in the notifications tab)

### ISSUE THREAD

**Issue by Luccasoli** [OneSignal/react-native-onesignal#1211]
**Description:**

Hello! I'm having this problem with sdk version 4:
"InAppAlert" notification does not work, the phone vibrates / emits sound, however the notification only appears with an icon in the notification area, but before, when it ran "OneSignal.inFocusDisplaying (1);" the notification appears "floating" even with the app open

**Environment**
Using yarn
"react-native-onesignal": "^4.0.8"
"react-native": "~0.63.3",

**Steps to Reproduce Issue:**
Just follows any minimal example and test in a android device

**Anything else:**

![image](https://user-images.githubusercontent.com/31039396/117313387-3ab38580-ae5c-11eb-87ed-451e7495579b.png)
```
OneSignal.setNotificationWillShowInForegroundHandler(
        (notifReceivedEvent) => {
          let notif = notifReceivedEvent.getNotification();
          notifReceivedEvent.complete(notif);
        },
      );
```
The documentation only suggests using "setNotificationWillShowInForegroundHandler" with "notifReceivedEvent.complete (notif);" to perform the same action as in version 3 of the sdk, but the same thing does not happen, I would like to have the same behavior caused by this code: "OneSignal.inFocusDisplaying (1);"

**Comment by rgomezp** [comment]
Howdy,
Thanks for the question.

We no longer support the `InAppAlert`. If you would like to show it, you can still do so by using something like a [React Native Alert](https://reactnative.dev/docs/alert) in the callback for the handler shown above.

Thanks in advance for your understanding

Enjoy

**Comment by beqramo** [comment]
Hi @rgomezp why did you stop supporting inAppAlert? it is only for Android? if so why didn't you stop it for ios too? for the sake of consistency on both platforms?

thanks
