### ISSUE TITLE
Foreground notifications do not show consistently; curious about setTimeout used in setNotificationWillShowInForegroundHandler

### ISSUE THREAD

**Issue by gtsec** [OneSignal/react-native-onesignal#1217]
**Description:**
Unsure why `setTimeout` is needed for https://documentation.onesignal.com/docs/react-native-40-api-reference#foreground-notification-control; notifications don't show up consistently

**Environment**
React Native 0.61.5 + `"react-native-onesignal": "4.0.6"`

**Steps to Reproduce Issue:**
1. I expect a notification in the foreground
2. inconsistently shows in foreground; maybe 1 out of every 20 messages and once in a 5 minute window

**Anything else:**
n/a

**Comment by rgomezp** [comment]
Howdy,
The `setTimeout` is not needed. It is there only for the purposes of demonstration that you _can_ delay the notification if you want. We will try to make this more clear.

In terms of the inconsistency, we will look into this. Are you seeing the issue across both ios and android?

**Comment by rgomezp** [comment]
Closing due to no response
