### ISSUE TITLE
Is it possible to open a url in the browser instead of open the app when pressing notification?

### ISSUE THREAD

**Issue by fabyeah** [OneSignal/react-native-onesignal#1219]
I've been testing a couple notification packages, but couldn't get this to work so far. So just wanted to ask if this is possible with OneSignal:

When the user presses a remote push notification, I want to open a URL in the browser and not open the app. This needs to work when the app is in the background or killed. On Android and iOS. Is this possible?

I've seen `launchUrl` mentioned here and in the docs, but isn't that only relevant when the app is in focus (currently in foreground) for `setNotificationWillShowInForegroundHandler`?

When I open the url in the `setNotificationOpenedHandler`, can I prevent opening the app?

Thanks for any hints 🙏

**Comment by rgomezp** [comment]
Howdy,
Yes this is possible.

Simply put the URL you want to open in the Launch URL field.

Enjoy!

**Comment by fabyeah** [comment]
@rgomezp Thanks for the quick reply! I set everything up, the docs are very clear 👍. This works as desired in Android, but sadly not on iOS. On iOS it will always open the app first and then open a smaller browser window within the app. This window will frequently reload and reset the user back to the initial url whenever it is moved the tiniest bit down, which happens quite frequently when navigating and scrolling around. There's also other problems caused by this browser in app system, like videos not autoplaying and having to tap them twice to play them. These do not occur in the normal browser. 😢 Is there any way to open the link in the actual device browser and not within the app?

As a fallback solution, is it maybe possible to catch the event on iOS and prevent the default behavior and open an external browser window instead? (while keeping the nice current behavior for android!)
Not ideal as the app is still opened on iOS, but much better than the current behavior.

**Comment by fabyeah** [comment]
Update: I tried `OneSignal_suppress_launch_urls: true` in Info.plist, as described in the docs (https://documentation.onesignal.com/docs/links#launch-url). Now the app opens without anything happening.

I also tried downgrading to 2.0.0 and setting `kOSSettingsKeyInAppLaunchURL: false`. But then I get build errors. But

>set kOSSettingsKeyInAppLaunchURL to false to open Safari.

seems to be what I want, but setting this in the current SDK version, doesn't change anything. Is this option not supported anymore? Downgrading to a version from four years ago is probably not a good idea 🙁

**Comment by fabyeah** [comment]
>As a fallback solution, is it maybe possible to catch the event on iOS and prevent the default behavior and open an external browser window instead? (while keeping the nice current behavior for android!)
Not ideal as the app is still opened on iOS, but much better than the current behavior.

I have implemented this with

```
  OneSignal.setNotificationOpenedHandler(async (openedEvent) => {
    const { notification } = openedEvent;
    if (Platform.OS === 'ios') {
      await Linking.openURL(notification.launchURL);
    }
  });
```

Opens the browser, but still the app will be opened first whenever tapping on a notification. 😕
Is there any way to open Safari directly without the app?

**Comment by emawby** [comment]
Hello @fabyeah. Unfortunately as far as I am aware there is no way on iOS to launch a browser directly from an Application's push notification without first opening the app. As you mentioned OneSignal allows you to open the app and then open the browser, but we are unable to provide the functionality you want

**Comment by fabyeah** [comment]
@emawby Thanks for your answer, that's good to know. Then I'll have to work with that.

**Comment by aneena-thomas** [comment]
@emawby but for me, it always opens the browser instead of the app when clicking push notification.
