### ISSUE TITLE
Expo: Issue with RNOneSignal.setAppId 

### ISSUE THREAD

**Issue by isidor99** [OneSignal/react-native-onesignal#1220]
Hi, I am creating an app using Expo bare workflow. I installed this library following documentation and now I constantly get this warning:
`[Unhandled promise rejection: TypeError: null is not an object (evaluating 'RNOneSignal.setAppId')]`

I tried to reinstall library, created new Onesignal app, created new Firebase app with new server key, but nothing helped me.  Does anyone know why this happens?

I created new empty expo bare workflow project and installed this library following official OneSignal documentation and still getting the same issues.

**Comment by MAhtishamShahzad** [comment]
same error

**Comment by riyaztechuz** [comment]
I'm Facing the same issue

**Comment by rgomezp** [comment]
Howdy,
To everyone in this thread, please comment whether you are using Expo bare workflow as well.

I looked into this a bit and did manage to reproduce the issue. It seems that `RNOneSignal` is undefined at this line [here](https://github.com/OneSignal/react-native-onesignal/blob/master/src/index.js#L16).

I'm not too familiar with Bare workflow but from a quick search it seems like you may need to install something called **unimodules**: https://docs.expo.io/bare/installing-unimodules/

Please make sure you have those installed as well.

Cheers

**Comment by isidor99** [comment]
The problem was in running the application. When I start app with `expo start` there is that warning, and OneSignal can't see subscribed user. However, when I start app with `npx react-native run-android` everything works just fine.
