### ISSUE TITLE
OneSignal SDK not certified for "Designed for Families" on Google Play

### ISSUE THREAD

**Issue by jespejoh** [OneSignal/react-native-onesignal#1221]
**Description:**
Google seems to be making some changes in their privacy policies and now they do not allow certain SDKs that are not certified for that program – OneSignal SDK among them. Normally this would not be an issue as the apps are mainly not designed for kids, but for those apps for audiences below 13 years old that use OneSignal SDK, Google is starting to reject them and giving 90 days notice either remove the non-compliant SDK (OneSignal SDK) or make it compliant. 

I have engaged in some email talks with some people at Google and this was their answer on how to fix such issue, but of course removing OneSignal seems like a drastic solution which we would rather not do (we're happy with OneSignal, we don't want to move to another provider):

![image](https://user-images.githubusercontent.com/3984011/118804851-7b23f200-b8a5-11eb-80d4-a986e743dd46.png)

Making it compliant seems to be an easy task, according to their guidelines (last paragraph here: https://support.google.com/googleplay/android-developer/answer/9283445):

> In order for an ad SDK to be included on the above list, the ad SDK must self-certify that they are compliant with Play’s Families Ad Program policies and all applicable local laws and regulations. If you would like an ad SDK to be considered for this program, please [share this interest form with them](https://support.google.com/googleplay/android-developer/?p=adnet). Completion of this form does not guarantee that an ad SDK will be certified. Until an ad network has been added to this list, it will not be considered certified. Please be sure to check this list periodically for any change in certification status of the ad SDKs that you may be using. 

Is this something that you would be willing to consider adding to your roadmap or is this something that would be completely out of your scope?  

**Environment**
 
- Platform: Android (Google Play). Please note that you will face this issue **on Google Play and only when submitting for reviewal an app targeted at users below 13 years old**.
- RN Version: 0.61.2
- Current version used when submitting: 3.9.3
- Adding the SDK via yarn

**Steps to Reproduce Issue:**

1. Include OneSignal SDK.
2. Build app for release on Android.
3. Select target audience below 13 years old.
3. Submit app for reviewal and wait for Google's answer.
4. Google will reject the app for targeting kids and including SDKs not complaint with their "Designed for families" policy.

**Comment by jmadler** [comment]
Thanks for reaching out Jesús.

Based on my understanding of the  "Google Play Families Ads Program", I don't think it would be appropriate for us to to participate.  We neither collect data for advertisers, nor traffic/display advertising. 

I believe our SDK being flagged here is related to historical use of data collection, which has ceased as of mid-2019.  We had not yet fully removed the advertising-related symbols in our SDK until this past month.  This has been reported on our [Android SDK](https://github.com/OneSignal/OneSignal-Android-SDK/issues/1311) and since then we've reached out to folks at the Play Store to dig in.

Can you please update to [4.1.0](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.1.0) and retry submission?  This update includes the [Android SDK 4.3.4](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.3.4) update, which eliminates the final advertising symbol (play-services-ads-identifier).

If you encounter remaining issues at that point, we'll re-review with our partners at Google Play.

**Comment by jespejoh** [comment]
Hi Jordan,

Thanks for your prompt answer! That sounds like a feasible option, maybe that fixes it. I thought the same and asked Google about it but their answer was very vague and basically not answering my original question, so I'll just give it a try and will post my results here.

Cheers!

**Comment by ArnauKokoro** [comment]
@jespejoh have you tried to submit an app with new One Signal SDK version? Have it passed Google reviewers?

Thanks!!

**Comment by jespejoh** [comment]
@ArnauKokoro We are working on other updates and planning to submit everything this week – I'll keep the issue updated with the results.

**Comment by rodrigohgpontes** [comment]
Hello @jmadler , I just submitted an update to my children's stories app using `"react-native-onesignal": "^4.1.1"` (OneSignal was the only major change in this update), and it got rejected for the same reasons as @jespejoh . I also appealed and got no useful new info or direction (outside of removing OneSignal SDK).

Do you have any updates on that front? Thanks!

**Comment by jmadler** [comment]
I'm afraid no updates at this time.  I check back-in with Google regularly and hope to hear something soon.

**Comment by jespejoh** [comment]
Any updates at this point? We really need to ship push notification updates so we would like to know if this is part of your roadmap or not. I totally understand if this is not high prio on your side, but then please let me/us know so we can look for alternatives as we really need to integrate push notifications back in our app.

Thanks in advance & best regards.

**Comment by rodrigohgpontes** [comment]
I would also appreciate if this issue gets a higher priority. I implemented notifications on iOS and it is working great for my business case, now I need it on Android. It is crucial for my business that I can have push notifications on Android.

**Comment by nan-li** [comment]
Hi @jespejoh and @rodrigohgpontes, this is a high priority item for us and I wish I had better updates to give you. We are still checking in with Google regularly and awaiting updates from them.

**Comment by rodrigohgpontes** [comment]
Hey @jmadler and @nan-li , here for my customary reminder that I need OneSignal SDK to work on Android for kids apps :)

**Comment by rgomezp** [comment]
Howdy,
This has now been resolved. Please make sure you're on the latest version of the SDK.

UPDATE: OneSignal SDK is approved to be used by apps in the Families program but this may not take effect for 2-3 weeks.. will follow up then.

**Comment by adrienpoly** [comment]
Thanks for the update @rgomezp this is a great news

**Comment by rodrigohgpontes** [comment]
Hi @rgomezp, I just had my app rejected because of OneSignal SDK (latest version), could you please reopen this issue and verify that is solved with Google?

The only change that I made was to include OneSignal SDK (version 4.3.3) to my Android app and submit it to the Play Store. Yesterday I got this reject message:

> "issue: Violation of Families Policy Requirements

> We have detected that your app includes non-certified ad SDKs or SDKs that are not approved for use in child-directed services. Any SDKs used in the app must be appropriate for use in child-directed services. Additionally, apps that solely target children must not contain any SDKs that are not approved for use in child-directed services, including ads SDKs. Apps in the Designed for Families program must only use ad SDKs that have certified their compliance with the Families Ads Program.

It seems the issue is exactly the same as reported at the beginning of this issue.

If you think it is a Google mistake (some reviewer not checking the updated list of allowed SDKs or something), let me know what should I say in an appeal to this rejection to the Play Store.

Thanks!

**Comment by nan-li** [comment]
Hi @rodrigohgpontes, sorry we were too eager on this.. Just clarified that the OneSignal SDK is approved to be used by apps in the Families program but this may not take effect for 2-3 weeks, and then apps will be approved. We'll follow up when we hear it has been implemented.

**Comment by rodrigohgpontes** [comment]
Ok, good to know, thanks for the quick response @nan-li . I have no problem waiting a few more weeks.

**Comment by rodrigohgpontes** [comment]
Hi @nan-li , any update if Google is approving OneSignal SDK already?

**Comment by jmadler** [comment]
Hey @rodrigohgpontes (et al) --

Google have let us know that we are now approved for use in the Designed for Families program.  Please make sure you're using the latest version of the SDK, and submit for review.  If you encounter any issues, please reach out to OneSignal support so we can escalate with our contacts at Google.

Thanks!
Jordan
