### ISSUE TITLE
Build fails with react-native 0.64.1 under Xcode 12.5

### ISSUE THREAD

**Issue by pnogier** [OneSignal/react-native-onesignal#1223]
Hi there,

I just upgraded to Xcode 12.5,
Upgraded react-native from 0.62.2 to 0.64.1,
Upgraded react-native-onesignal from 3.9.0 to 4.1.0

Now when I try to build my app, I get the following error : 
`ld: library not found for -lPods-OneSignalNotificationServiceExtension`

None on the solutions listed in #1179 or #1103 solved my issue.

Here is my Podfile
```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'Spacial' do
  # Pods for Spacial
  pod 'Stripe', '~> 21.5.1'
  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

  #pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  
  target 'SpacialTests' do
    inherit! :complete
    # Pods for testing
  end

  use_flipper!()
  
  
  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
     end
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 3.0', '< 4.0'
end

```

Did some of you already faced this issue and find a solution ? 

Thank you,

Cheers

**Comment by pnogier** [comment]
Well, I guess I found why this happened : 

Each time I run a `pod install`, it automatically add the `libPods-OneSignalNotificationServiceExtension.a` under Framework and Libraries in my `OneSignalNotificationServiceExtension` Target. I juts had to remove it manually and everything builds properly now. 

However I now have to find why this library automatically adds itself and fix it. 🤗

Closing for now.

**Comment by MathiasMoralesDixtra** [comment]
> Well, I guess I found why this happened :
> 
> Each time I run a `pod install`, it automatically add the `libPods-OneSignalNotificationServiceExtension.a` under Framework and Libraries in my `OneSignalNotificationServiceExtension` Target. I juts had to remove it manually and everything builds properly now.
> 
> However I now have to find why this library automatically adds itself and fix it. 🤗
> 
> Closing for now.

Do you have news about that? I have the same issue.

**Comment by MathiasMoralesDixtra** [comment]
In my case, I fixed when I set the same version on Podfile`platform :ios, '11.0'` that on Target in OneSignal notification and Project.
<img width="177" alt="Screen Shot 2021-08-04 at 15 30 18" src="https://user-images.githubusercontent.com/59056508/128235255-da3c2f3b-cecf-4102-b3d1-bda65858c499.png">

<img width="454" alt="Screen Shot 2021-08-04 at 15 30 06" src="https://user-images.githubusercontent.com/59056508/128235220-21e59ce5-4f2b-4b2a-8108-35bdc85f86e7.png">

**Comment by pnogier** [comment]
Hi @MathiasMoralesDixtra, 
Thank you for the suggestion, I'll give it a try soon :)

**Comment by vokecodes** [comment]
You need to check the platform version in your Podfile and make it match your main target deployment info and one signal target

**Comment by pisacode** [comment]
I accidentally opened .xcodeproject file instead of .xcworkspace  and the same error appeared. Got me 30 minutes to figure out to open the correct file.
