### ISSUE TITLE
Android crashed with Fatal Exception: java.lang.ClassCastException at com.onesignal.TrackAmazonPurchase

### ISSUE THREAD

**Issue by zsliu** [OneSignal/react-native-onesignal#1225]
**Description:**

This happens when I started to integrate react-native-iap

Fatal Exception: java.lang.ClassCastException
f.a.a.a.c.f cannot be cast to f.a.a.a.a

com.onesignal.TrackAmazonPurchase. (TrackAmazonPurchase.java:58)
com.onesignal.OneSignal.handleAmazonPurchase (OneSignal.java:9)
com.onesignal.OneSignal.k (OneSignal.java:93)
com.onesignal.OneSignal.j (OneSignal.java:87)
com.onesignal.OneSignal.reassignDelayedInitParams (OneSignal.java:58)
com.onesignal.OneSignal.onRemoteParamSet (OneSignal.java)
com.onesignal.OneSignal$5.complete (OneSignal.java:29)
com.onesignal.OneSignalRemoteParams.b (OneSignalRemoteParams.java:10)
com.onesignal.OneSignalRemoteParams.access$000 (OneSignalRemoteParams.java)
com.onesignal.OneSignalRemoteParams$1.a (OneSignalRemoteParams.java:2)
com.onesignal.OneSignalRestClient$5.run (OneSignalRestClient.java:4)
java.lang.Thread.run (Thread.java:784)

(your description here)

**Environment**

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 29 // 27 or up for onesignal
        targetSdkVersion = 29
        // supportLibVersion = "29.0.0"
        googlePlayServicesAuthVersion = "16.0.1"
        androidXAnnotation = "1.1.0"
        androidXBrowser = "1.0.0"
    }
...
}

**Steps to Reproduce Issue:**

1. npm install react-native-iap
2. start app then OneSignal crash the app with the following stack trace
3.

**Anything else:**

(crash stacktraces, as well as any other information here)
com.onesignal.TrackAmazonPurchase. (TrackAmazonPurchase.java:58)
com.onesignal.OneSignal.handleAmazonPurchase (OneSignal.java:9)
com.onesignal.OneSignal.k (OneSignal.java:93)
com.onesignal.OneSignal.j (OneSignal.java:87)
com.onesignal.OneSignal.reassignDelayedInitParams (OneSignal.java:58)
com.onesignal.OneSignal.onRemoteParamSet (OneSignal.java)
com.onesignal.OneSignal$5.complete (OneSignal.java:29)
com.onesignal.OneSignalRemoteParams.b (OneSignalRemoteParams.java:10)
com.onesignal.OneSignalRemoteParams.access$000 (OneSignalRemoteParams.java)
com.onesignal.OneSignalRemoteParams$1.a (OneSignalRemoteParams.java:2)
com.onesignal.OneSignalRestClient$5.run (OneSignalRestClient.java:4)
java.lang.Thread.run (Thread.java:784)

**Comment by rgomezp** [comment]
This is not a OneSignal issue, please see this issue in the other repository for more info: https://github.com/dooboolab/react-native-iap/issues/1291

Enjoy!

**Comment by jkasten2** [comment]
From the stacktrace this looks to be happening from OneSignal, due to a new version of the Amazon IAP that OneSignal is not compliable with.

This is the same as https://github.com/OneSignal/OneSignal-Android-SDK/issues/1344 where details will be tracked.

This issue will be closed once a version of react-native-onesignal includes this fix.

**Comment by rgomezp** [comment]
[Fixed](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.2.0)
