### ISSUE TITLE
'RCTOneSignal.h' file not found

### ISSUE THREAD

**Issue by kiranraj2k** [OneSignal/react-native-onesignal#123]
Xcode: 8.2.1
macOS: 10.12.2
react-native: 0.39
react-native-onesignal: 1.2.3
![screenshot](https://cloud.githubusercontent.com/assets/20181550/21419455/b0f59674-c84d-11e6-94a2-273d7a86dfaa.png)

What am I possibly missing?

**Comment by Etheryte** [comment]
You missed the following line in the [readme](https://github.com/OneSignal/react-native-onesignal/blob/master/README.md#ios-installation):

> Ensure that `Header Search Paths` on `Build Settings` has the path `$(SRCROOT)/../node_modules/react-native-onesignal` set to `recursive`.
