### ISSUE TITLE
Get all player_id.

### ISSUE THREAD

**Issue by sourabhCofoundry** [OneSignal/react-native-onesignal#1230]
Hello I have one query How to get all player_id . Please provide any solution

**Comment by rgomezp** [comment]
Howdy,
If you're looking for an entire list of your subscribers' player_ids you can get those via the [view devices endpoint](https://documentation.onesignal.com/reference/view-devices). Hope that helps. 

In the future, you can get a quick response for these types of questions via our support channels at OneSignal.com (red bubble in corner).

Enjoy!

**Comment by SourabhDhiman77** [comment]
Thank you .

**Comment by FazilMuhammed** [comment]
how to get player_id recent react native OneSignal version 5.0.2

    const state = await OneSignal.getDeviceState();
    const userID = state.userId;

this is not working latest version please find a solution @rgomezp
