### ISSUE TITLE
building for iOS, but linking in dylib file xcode 12 build error

### ISSUE THREAD

**Issue by SamyOptimize** [OneSignal/react-native-onesignal#1234]
**Description:**

Following the official instructions for adding Onesignal to react native, I'm running into this build error for Xcode 12 for real ios devices .

**Environment**

 1. What version of the OneSignal React-Native SDK are you using?   "react-native-onesignal": "^4.1.1",
2. How did you add the SDK to your project (eg. npm)    Used yarn add react-native-onesignal

**Steps to Reproduce Issue:**

1. Install the OneSignal SDK as per the documentation
2. Try to build app on a real device 
3. Xcode throws a build error

**Anything else:**

(crash stacktraces, as well as any other information here)
Error:
```
building for iOS, but linking in dylib file (/Users/****/Library/Developer/Xcode/DerivedData/{APP_NAME}-anpmvxoyhdefzbdeknrtvkblmeie/Build/Products/Debug-iphoneos/OneSignal.framework/OneSignal) built for Mac Catalyst, file '/Users/****/Library/Developer/Xcode/DerivedData/{APP_NAME}-anpmvxoyhdefzbdeknrtvkblmeie/Build/Products/Debug-iphoneos/OneSignal.framework/OneSignal' for architecture arm64
```

**Comment by rgomezp** [comment]
Howdy,
Can you please try deintegrating the pod and re-installing?

**Comment by venomtl** [comment]
I have the same problem.  Do you know how to solve?

**Comment by rgomezp** [comment]
Try clearing the derived data folder and cache.

Also please provide your Podfile if possible

**Comment by rgomezp** [comment]
Closing due to no response
