### ISSUE TITLE
Linking error on Xcode 8.1

### ISSUE THREAD

**Issue by IronTony** [OneSignal/react-native-onesignal#124]
Hi all,
I created an RN 0.39 and added your library following the tutorials.
Unfortunately when I compile the app I got these problems:
<img width="262" alt="screen shot 2016-12-22 at 12 53 45" src="https://cloud.githubusercontent.com/assets/3645225/21425309/b0655d2a-c848-11e6-94e8-e2666451759b.png">

Here is how I added everything:
<img width="260" alt="screen shot 2016-12-22 at 12 54 05" src="https://cloud.githubusercontent.com/assets/3645225/21425310/b065bb12-c848-11e6-8a1f-2600eec5ef9d.png">

Thank you in advance.

**Comment by IronTony** [comment]
Possible solution:
Add -lc++ in Other Linker Flags in Linking in Build Setting

**Comment by mdgozza** [comment]
Hey IronTony, how did you solve this issue? I have -lc++ in my Flags but am having the same issue.

**Comment by IronTony** [comment]
Hey @mdgozza sorry for the late, I don't have the mac with me now. I will answer you back asap

**Comment by mdgozza** [comment]
Thanks for getting back to me!! Actually I just figured it out about an hour ago. I needed to add the flag to the other linker flags of the Tests and not the project, thanks again!!

**Comment by IronTony** [comment]
Glad you fixed.
