### ISSUE TITLE
c.initWithAppId is not a function. (In 'c.initWithAppId(n,o)', 'c.initWithAppId' is undefined)

### ISSUE THREAD

**Issue by lulmichal** [OneSignal/react-native-onesignal#1242]
**Description:**

Hello Everyone. One of our clients experienced the app crash during testing. Crashlytics says this:

``c.initWithAppId is not a function. (In 'c.initWithAppId(n,o)', 'c.initWithAppId' is undefined)``

**Environment**

 "react-native-onesignal": "^4.1.0" (recently upgraded from 3.8.1)
 "react-native": "^0.63.4",
 
 OS: iOS 14.2.0 (iOS Simulator)

**Steps to Reproduce Issue:**

I couldn't reproduce the issue myself. Unfortunately it happened only once during testing and not for me.

**Anything else:**

I tracked the main.jsbundle line:
``{key:"init",value:function(n,o){b()&&('ios'===u.Platform.OS?c.initWithAppId(n,o):c.init(n))}}``

I'm sorry if that's not sufficient but I'm new in programming, so if there's any additional info I can attach then please let me know.

Thank you and have a nice day!

**Comment by rgomezp** [comment]
Howdy,
Unfortunately the iOS Simulator does not support certain things including push notifications / OneSignal. 

I can't tell from the info you provided, but that might be the issue. Give it a shot on a real device.

**Comment by lulmichal** [comment]
Got it, thank you very much!
