### ISSUE TITLE
[iOS] Can't deploy Ad-hoc app due to signing app that fail ?

### ISSUE THREAD

**Issue by Pandazaur** [OneSignal/react-native-onesignal#1243]
Hello,

**Description:**
I'm developing an app with React Native 0.64 that I build through Microsoft AppCenter. I'm using the react-native-one-signal sdk for the push notifications but I'm facing some issues when I'm trying to sign my OneSignalExtension for **Adhoc distribution** with my extension "Provisioning profile" (no problems for the production build in the AppStore).

> error: "OneSignalServiceExtension" requires a provisioning profile with the App Groups feature. Select a provisioning profile in the Signing & Capabilities editor. (in target 'OneSignalServiceExtension' from project 'FrenchFounders')

But the thing is I'm using a provisioning profile that includes the "App Groups" feature. 
![image](https://user-images.githubusercontent.com/10389473/121214471-6f619500-c87f-11eb-9e92-b5caaef77ab5.png)

**Environment**
React Native: 0.64
react-native-onesignal: "^3.9.3" (using npm)
Podfile: `pod 'OneSignal', '>= 2.9.3', '< 3.0'`

**Steps to Reproduce Issue:**

1. I followed all the instructions here: https://documentation.onesignal.com/docs/react-native-sdk-setup (everything is fine)
2. I created a staging env (using a new scheme) to deploy **Ad-hoc builds** with *AppCenter*
3. I selected the "Staging" build configuration for this scheme
4. I added the bundle identifier `li.wasapp.frenchfounders.staging.OneSignalServiceExtension`for the staging build configuration
5. I made a "Ad-hoc" provisioning profile for the extension but my error (see above) is happening everytime.

How can I get out of this problem ?

**Anything else:**

![image](https://user-images.githubusercontent.com/10389473/121215202-19d9b800-c880-11eb-8b4c-f89d9cddcd9a.png)
⬆️ My config for the OneSignalExtension that should match the provisioning profile

**Comment by rgomezp** [comment]
Howdy,
Firstly I would recommend upgrading your OneSignal SDK version.

Secondly, I see that you have two different app groups. Have you tried only using one at a time? 

Also, double check that the app groups match between the service extension and the main target.

Nothing else quite comes to mind but you could certainly try creating a new provisioning profile

**Comment by rgomezp** [comment]
Closing due to no response
