### ISSUE TITLE
Cant get ReactApplicationContext in NotificationExtensionService

### ISSUE THREAD

**Issue by anwersolangi** [OneSignal/react-native-onesignal#1244]
**Description:**

I am trying to access `ReactApplicationContext` as there is no **backgroundListener** for this so going with **NSE** is the only way, what i am trying to do is showing a react-custom package which requires reactapplicationcontext for its initializing, i have also tried to extend the class ith ReactApplicationContext but it throw an error.
So, I want ReactApplicationContext inside the NSE class.

**Environment**

1. react-native-onesignal: 4.1.1
2. react-native: 0.63.4

**Steps to Reproduce Issue:**

  1. create react-native project, install Onesignal with npm package.
  2. Configure the project with NotificationExtensionService class with onReaceiveHandlerMethod.
  3. Launch a react-native package with ReactApplicationContext.

**Anything else:**

I have found a similar issue in stackoverflow but dont know how to implement it with Onesignal.
https://stackoverflow.com/questions/63303616/how-do-i-send-react-application-context-from-non-react-class

**Comment by rgomezp** [comment]
Howdy,
I didn't quite understand what you're trying to do. Can you please provide a bit more info regarding what exactly you're trying to do? e.g: why do you need the ReactApplicationContext?

`import com.facebook.react.bridge.ReactApplicationContext;`

Also, I'm not familiar with the `react-custom` package nor could I find any info regarding it. Can you please provide a link? 

Normally we recommend you simply add the NSE via native code.

**Comment by rgomezp** [comment]
Closing due to no response
