### ISSUE TITLE
[Crash] OneSignalUserDefaults getSavedCodeableDataForKey:defaultValue

### ISSUE THREAD

**Issue by Ahmed-Imam** [OneSignal/react-native-onesignal#1249]
**Description:**
App crashes on some devices upon updating.

**Environment**
react-native: v0.63.4
react-native-onesignal : v3.8.0
oneSignal SDK: v2.14.3
ios: v14.4.2

**Steps to Reproduce Issue:**
Replicated on production only

**Crash logs**

> Fatal Exception: NSInvalidArgumentException
0 CoreFoundation 0x191a5186c __exceptionPreprocess
1 libobjc.A.dylib 0x1a6a6ac50 objc_exception_throw
2 CoreFoundation 0x19195895c -[NSOrderedSet initWithSet:copyItems:]
3 CoreFoundation 0x191a54438 forwarding
4 CoreFoundation 0x191a56740 _CF_forwarding_prep_0
5 Foundation 0x192c7ecc8 -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]
6 Foundation 0x192ccbff4 -[NSKeyedUnarchiver initForReadingWithData:]
7 Foundation 0x192ccc618 +[NSKeyedUnarchiver unarchiveObjectWithData:]
8 happyseason 0x1009b4a48 -[OneSignalUserDefaults getSavedCodeableDataForKey:defaultValue:]
9 happyseason 0x100980f30 -[OSMessagingController init]
10 happyseason 0x100980bcc __39+[OSMessagingController sharedInstance]_block_invoke
11 libdispatch.dylib 0x191645db0 _dispatch_client_callout
12 libdispatch.dylib 0x1916475c8 _dispatch_once_callout
13 happyseason 0x100980b8c +[OSMessagingController sharedInstance]
14 happyseason 0x10097ae54 +[OneSignal receivedInAppMessageJson:]
15 happyseason 0x1009a8338 +[OneSignalTracker applicationForegrounded]
16 happyseason 0x1009a2f78 -[OneSignalAppDelegate oneSignalApplicationDidBecomeActive:]
17 UIKitCore 0x194401e2c -[UIApplication _stopDeactivatingForReason:]
18 UIKitCore 0x193a612a0 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:]
19 UIKitCore 0x193a6161c -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]
20 UIKitCore 0x193a60e58 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:]
21 UIKitCore 0x193a693a4 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke
22 UIKitCore 0x193edb60c +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:]
23 UIKitCore 0x193fe76c4 _UISceneSettingsDiffActionPerformChangesWithTransitionContext
24 UIKitCore 0x193a6909c -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]
25 UIKitCore 0x1938905a0 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke
26 UIKitCore 0x19388ef14 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:]
27 UIKitCore 0x1938901c8 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:]
28 UIKitCore 0x193f052e8 -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:]
29 FrontBoardServices 0x1a17bac94 -[FBSScene updater:didUpdateSettings:withDiff:transitionContext:completion:]
30 FrontBoardServices 0x1a17e7504 __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke_2
31 FrontBoardServices 0x1a17c94a0 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
32 FrontBoardServices 0x1a17e7430 __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke
33 libdispatch.dylib 0x191645db0 _dispatch_client_callout
34 libdispatch.dylib 0x191649738 _dispatch_block_invoke_direct
35 FrontBoardServices 0x1a180e250 FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK
36 FrontBoardServices 0x1a180dee0 -[FBSSerialQueue _targetQueue_performNextIfPossible]
37 FrontBoardServices 0x1a180e434 -[FBSSerialQueue _performNextFromRunLoopSource]
38 CoreFoundation 0x1919cd76c CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION
39 CoreFoundation 0x1919cd668 __CFRunLoopDoSource0
40 CoreFoundation 0x1919cc960 __CFRunLoopDoSources0
41 CoreFoundation 0x1919c6a8c __CFRunLoopRun
42 CoreFoundation 0x1919c621c CFRunLoopRunSpecific
43 GraphicsServices 0x1a9590784 GSEventRunModal
44 UIKitCore 0x194406ee8 -[UIApplication _run]
45 UIKitCore 0x19440c75c UIApplicationMain
46 happyseason 0x10057b688 main + 18 (AppDelegate.swift:18)
47 libdyld.dylib 0x1916866b0 start

**Comment by rgomezp** [comment]
It sounds like this issue is safe to close. Is there anything else?
