### ISSUE TITLE
Google Play services error

### ISSUE THREAD

**Issue by ArkaneKhan** [OneSignal/react-native-onesignal#1250]
After adding @react-native-firebase/app library i was getting google play services error on one signal dashboard for android devices and was getting push token null. 

I am adding this issue so if some one else faces this. It can be of help for them.

After viewing logcat i found this was missing
implementation "com.google.firebase:firebase-iid"

so i added this line on android/app/build.gradlew file in dependencies section and that solved my issue

**Comment by ArkaneKhan** [comment]
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation "com.google.firebase:firebase-iid"  *******************// here i added this line
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

**Comment by syuhadazulkifli** [comment]
> After adding @react-native-firebase/app library i was getting google play services error on one signal dashboard for android devices and was getting push token null.
> 
> I am adding this issue so if some one else faces this. It can be of help for them.
> 
> After viewing logcat i found this was missing
> implementation "com.google.firebase:firebase-iid"
> 
> so i added this line on android/app/build.gradlew file in dependencies section and that solved my issue

I appreciate your effort on explaining your issue and together with the solution! It helped me fix my issue too. Thank you!
