### ISSUE TITLE
OneSignal-smsSubscriptionChanged is not a supported event type for RCTOneSignalEventEmitter

### ISSUE THREAD

**Issue by likeaj6** [OneSignal/react-native-onesignal#1254]
**Description:**

Getting the error below upon app start

**Environment**
1. What version of the OneSignal React-Native SDK are you using? 4.0.7
2. How did you add the SDK to your project (eg. npm) yarn

**Steps to Reproduce Issue:**

  1. Unsure how to reproduce, issue started appearing upon updating to 4.0.7
**Anything else:**
(crash stacktraces, as well as any other information here)

 ![Screen Shot 2021-07-06 at 4 28 40 PM](https://user-images.githubusercontent.com/13268856/124678376-3bc25c80-de77-11eb-91f5-6ae3b8cd7fc0.png)

**Comment by rgomezp** [comment]
Howdy,
4.0.7 doesn't have any SMS-related changes.

Can you please try updating to the latest SDK again to see if you're still seeing the issue?

**Comment by chramos** [comment]
same issue here
I'm using the latest version `4.2.0`

EDIT:
solved after run `pod install` again

**Comment by rgomezp** [comment]
Closing since this seems resolved
