### ISSUE TITLE
App doesnt respond after click on notification

### ISSUE THREAD

**Issue by vt978** [OneSignal/react-native-onesignal#1261]
**Description:**
I was expecting the app would open after clicking on notification while the app is closed but there were no respond. Not sure if i miss anything that will cause this problem.

**Environment**
react-native-onesignal - 4.0.6

**Steps to Reproduce Issue:**
1. Followed all the steps to implement onesignal
2. Close app, click on notification

**Anything else:**
this is the app logcat after pressing the notification

07-14 16:38:59.572 26526  9991 D SystemUIAnalytics: sendEventLog 201, 1111, com.hrapp, 1
07-14 16:38:59.583  3239  3526 I ActivityManager: START u0 {act=null typ=null flg=0x24000000 cmp=ComponentInfo{com.hrapp/com.onesignal.NotificationOpenedReceiver}} from uid 10463
07-14 16:38:59.592  3239  3526 W ActivityManager: startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { flg=0x24000000 cmp=com.hrapp/com.onesignal.NotificationOpenedReceiver (has extras) }
07-14 16:38:59.592  3239  3526 I ActivityManager: [IOP] sourceDir : /data/app/com.hrapp-_cxuKRM8FZGaZxpTqjwMYA== in ActivityStacksupervisor
07-14 16:38:59.606  2806  2806 I SurfaceFlinger: id=119073 createSurf (3840x3840),2 flag=4, AppWindowToken{db3d50f token=Token{2d67a6e ActivityRecord{af6ede9 u0 com.hrapp/com.onesignal.NotificationOpenedReceiver t1757}}}#0
07-14 16:38:59.616  3239  3526 D ActivityManager: Received ACTIVITY intent in key u0 {c6e9c3f act=nullstartActivity cmp=ComponentInfo{com.hrapp/com.onesignal.NotificationOpenedReceiver} res=0} from uid 10006
07-14 16:38:59.621  3239  3239 D GameManagerService: MultiWindowEventListener.onFocusStackChanged(), state=0, top=ComponentInfo{com.hrapp/com.onesignal.NotificationOpenedReceiver}
07-14 16:38:59.628  3239  5779 D GamePkgDataHelper: notifyAppCreate(), pkgName: com.hrapp, sendRet: true
07-14 16:38:59.628  3239  3496 D GamePkgDataHelper: getGamePkgData(). com.hrapp
07-14 16:38:59.628  3239  3496 D GameManagerService: handleMessage(), MSG_APP_CREATE. ignore. pkgName: com.hrapp
07-14 16:38:59.632  3239  5779 D GameManagerService: noteResumeComponent(), resumeComponent: com.hrapp
07-14 16:38:59.632  3239  5779 D GamePkgDataHelper: getSosPolicy(). com.hrapp
07-14 16:38:59.633  3239  3496 D GameManagerService: handleForegroundChange(). pkgName: com.hrapp, clsName: com.onesignal.NotificationOpenedReceiver,FgActivityName:com.hrapp/com.onesignal.NotificationOpenedReceiver,userID:0
07-14 16:38:59.633  3239  3496 D GameManagerService:   handleForegroundChange(). set mFgApp: com.hrapp
07-14 16:38:59.633  3239  5779 D GameManagerService: identifyGamePackage. com.hrapp, mCurrentUserId: 0, callerUserId: 0
07-14 16:38:59.633  3239  5779 D GamePkgDataHelper: getGamePkgData(). com.hrapp
07-14 16:38:59.633  3239  7271 D GamePkgDataHelper: getGamePkgDataIncServer(). com.hrapp
07-14 16:38:59.634  3239  3496 D GameManagerService: notifyResumePause(). pkg: com.hrapp, type: 4, isMinimized: false, isTunableApp: false
07-14 16:38:59.634  3239  5779 D MARsPolicyManager: onPackageResumedFG pkgName = com.hrapp, userId = 0
07-14 16:38:59.640  3239  3526 D GamePkgDataHelper: getSosPolicy(). com.hrapp
07-14 16:38:59.642  3239  3239 V MARsPolicyManager: onNotificationBarClicked pkgName = com.hrapp, userId = 0
07-14 16:38:59.643  3239  3239 D Telecom:SamsungPrebindingServiceImpl: onTopActivityChanged : ComponentInfo{com.hrapp/com.onesignal.NotificationOpenedReceiver}
07-14 16:38:59.646  3239  3256 D CodecSolution: isMaxAspectPackageEx: com.hrapp : false(0)
07-14 16:38:59.658  4567  4567 D Notification.Badge: [valid] onNotificationRemoved : StatusBarNotification(pkg=com.hrapp user=UserHandle{0} id=69364839 tag=null key=0|com.hrapp|69364839|null|10463: Notification(channel=fcm_fallback_notification_channel pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x10 color=0x00000000 vis=PUBLIC semFlags=0x0 semPriority=0 semMissedCount=0))
07-14 16:38:59.658  4567  4567 D Notification.Badge: notificationKey : 0|com.hrapp|69364839|null|10463, count : 0, this.count : 1
07-14 16:38:59.658  4567  4751 D Notification.Badge: LauncherModel:onNotificationRemoved() : com.hrapp
07-14 16:38:59.658  3239  3526 D GameManagerService: identifyGamePackage. com.hrapp, mCurrentUserId: 0, callerUserId: 0
07-14 16:38:59.659  3239  3526 D GamePkgDataHelper: getGamePkgData(). com.hrapp
07-14 16:38:59.659  4567  4751 D Notification.Badge: updateLauncherIconBadges() item : [IconInfo(title=SIDC HR intent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.hrapp/.MainActivity (has extras) } id=543 type=0 container=-102 screen=2 cellX=0 cellY=2 spanX=1 spanY=1 rank=10 hidden=0 dropPos=null user=UserHandle{0} screenType=0)], mShowBadge : [false], item.mBadgeCount : [0]
07-14 16:38:59.660  4567  4567 D RecommendedView: updateBadgeItems: [IconInfo(title=SIDC HR intent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.hrapp/.MainActivity (has extras) } id=543 type=0 container=-102 screen=2 cellX=0 cellY=2 spanX=1 spanY=1 rank=10 hidden=0 dropPos=null user=UserHandle{0} screenType=0)]
07-14 16:38:59.668  9872  9872 D BadgeCountReceiver: packageName: com.hrapp, className: com.hrapp.MainActivity, count: 0
07-14 16:38:59.691  3239  3526 V WindowManager: defer hiding client AppWindowToken{db3d50f token=Token{2d67a6e ActivityRecord{af6ede9 u0 com.hrapp/com.onesignal.NotificationOpenedReceiver t1757}}}, caller=com.android.server.am.ActivityRecord.setVisibility:1989 com.android.server.am.ActivityStack.resumeTopActivityInnerLocked:3011 
07-14 16:38:59.691  3239  3526 V WindowManager: defer hiding client AppWindowToken{db3d50f token=Token{2d67a6e ActivityRecord{af6ede9 u0 com.hrapp/com.onesignal.NotificationOpenedReceiver t1757}}}, caller=com.android.server.am.ActivityRecord.setVisibility:1989 com.android.server.am.ActivityStack.resumeTopActivityInnerLocked:3063 
07-14 16:38:59.716  3239  9633 I WindowManager: Cancelling animation restarting=false, leash=null, surface=Surface(name=AppWindowToken{db3d50f token=Token{2d67a6e ActivityRecord{af6ede9 u0 com.hrapp/com.onesignal.NotificationOpenedReceiver t1757}}})/@0xb085ca3, parent=Surface(name=Task=1757)/@0x7db4ba0
07-14 16:38:59.721  2806  3885 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{db3d50f token=Token{2d67a6e ActivityRecord{af6ede9 u0 com.hrapp/com.onesignal.NotificationOpenedReceiver t1757}}}#0
07-14 16:38:59.730  2806  2806 I Layer   : id=119073 onRemoved AppWindowToken{db3d50f token=Token{2d67a6e ActivityRecord{af6ede9 u0 com.hrapp/com.onesignal.NotificationOpenedReceiver t1757}}}#0 
07-14 16:38:59.885  4567  4751 D BadgeCache: 1. pkgName : com.hrapp = 0
07-14 16:39:00.629 26526 26526 W NotificationEntryMgr: removeNotification for unknown key: 0|com.hrapp|69364839|null|10463
07-14 16:39:01.123  3239  3496 D GameManagerService: handleForegroundChange(). pkgName: com.hrapp, clsName: com.onesignal.NotificationOpenedReceiver,FgActivityName:com.hrapp/com.onesignal.NotificationOpenedReceiver,userID:0
07-14 16:39:01.123  3239  3496 D GameManagerService:   handleForegroundChange(). set mFgApp: com.hrapp
07-14 16:39:01.123  3239  3496 D GameManagerService: notifyResumePause(). pkg: com.hrapp, type: 4, isMinimized: false, isTunableApp: false
07-14 16:39:01.994  3503  3503 D ImsResolver: maybeAddedImsService, packageName: com.hrapp
07-14 16:39:01.997 26526 26526 D MetaDataParser: updatePackage() com.hrapp false
07-14 16:39:01.999 26526 26526 D MetaDataParser: removePackage() key = com.hrapp
07-14 16:39:02.039 22898 10002 I Fitness : OnPackageChangedOperation got intent: Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:com.hrapp flg=0x45000010 pkg=com.google.android.gms cmp=com.google.android.gms/.chimera.PersistentIntentOperationService (has extras) } [CONTEXT service_id=17 ]
07-14 16:39:02.293  3239  3239 I PersonaManagerService::Proxy: newPackage is com.hrapp
07-14 16:39:02.606  3239  3254 D MediaSessionService: Received change in packages, intent=Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:com.hrapp flg=0x45000010 (has extras) }
07-14 16:39:02.606  3239  3254 I GameManagerService: PkgInstallationReceiver, onPackageChanged : com.hrapp uid : 10463 userID : UserHandle{0}
07-14 16:39:02.608  4567  4567 D Launcher.Model: onPackageChanged:com.hrapp, user:UserHandle{0}, isUpsModeEnabled = false, isEmergencyEnabled = false
07-14 16:39:02.608  4567  4567 D SuggestedItemsProvider: onPackageChanged: com.hrapp / UserHandle{0}
07-14 16:39:02.608  4567  4567 D SuggestedItemsProvider: onPackageRemoved: com.hrapp / UserHandle{0}
07-14 16:39:02.608  4567  4751 D Launcher.Model: Loader.updatePackage com.hrapp
07-14 16:39:02.609  4567  4567 D SuggestedItemsProvider: onPackageAdded: com.hrapp / UserHandle{0}
07-14 16:39:02.618  3239  3599 D PackageManager: getComponentMetadataForIconTray : com.hrapp.MainActivity does not exist in mServices
07-14 16:39:02.618  3239  3599 D PackageManager: getComponentMetadataForIconTray : com.hrapp.MainActivity does not exist in mProviders
07-14 16:39:02.618  3239  3599 D PackageManager: getComponentMetadataForIconTray : com.hrapp.MainActivity does not exist in mReceivers
07-14 16:39:02.628  4567  4751 D LauncherActivityInfo: packageName: com.hrapp, supportTheme: false, height: 192, width: 192, density: 640
07-14 16:39:02.660  4567  4751 D DataLoader: updatePackage:com.hrapp
07-14 16:39:02.660  4567  4751 D DataLoader: updatePackageActivities, modified : IconInfo(title=SIDC HR intent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.hrapp/.MainActivity (has extras) } id=543 type=0 container=-102 screen=2 cellX=0 cellY=2 spanX=1 spanY=1 rank=10 hidden=0 dropPos=null user=UserHandle{0} screenType=0)
07-14 16:39:02.663  4567  4751 I AppsLoader: addOrUpdater cn = ComponentInfo{com.hrapp/com.hrapp.MainActivity}, UserHandle{0}, screenType = 0
07-14 16:39:02.668  4567  4751 I AppsLoader: addOrUpdater update item = IconInfo(title=SIDC HR intent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.hrapp/.MainActivity (has extras) } id=543 type=0 container=-102 screen=2 cellX=0 cellY=2 spanX=1 spanY=1 rank=10 hidden=0 dropPos=null user=UserHandle{0} screenType=0)

**Comment by chzappsinc** [comment]
Hi @vt978  Which **platform** its not opening?
