### ISSUE TITLE
Android App Crashed due to Fatal Exception: java.lang.ClassCastException at com.onesignal.TrackAmazonPurchase

### ISSUE THREAD

**Issue by zsliu** [OneSignal/react-native-onesignal#1263]
**Description:**

App crashed due to the following exception

Fatal Exception: java.lang.ClassCastException
f.a.a.a.c.f cannot be cast to f.a.a.a.a

com.onesignal.TrackAmazonPurchase.<init> (TrackAmazonPurchase.java:58)
com.onesignal.OneSignal.handleAmazonPurchase (OneSignal.java:9)
com.onesignal.OneSignal.k (OneSignal.java:93)
com.onesignal.OneSignal.j (OneSignal.java:87)
com.onesignal.OneSignal.reassignDelayedInitParams (OneSignal.java:58)
com.onesignal.OneSignal.onRemoteParamSet (OneSignal.java)
com.onesignal.OneSignal$5.complete (OneSignal.java:29)
com.onesignal.OneSignalRemoteParams.b (OneSignalRemoteParams.java:10)
com.onesignal.OneSignalRemoteParams.access$000 (OneSignalRemoteParams.java)
com.onesignal.OneSignalRemoteParams$1.a (OneSignalRemoteParams.java:2)
com.onesignal.OneSignalRestClient$5.run (OneSignalRestClient.java:4)
java.lang.Thread.run (Thread.java:919)

**Environment**

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 29 // 27 or up for onesignal
        targetSdkVersion = 29
        supportLibVersion = "29.0.0"
        googlePlayServicesAuthVersion = "16.0.1"
        // androidXAnnotation = "1.1.0"
        // androidXBrowser = "1.0.0"
    }
...
}

**Steps to Reproduce Issue:**

1. npm install react-native-iap
and OneSignal.setAppId crashed due the above exception. Stack trace enclosed
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)
com.onesignal.TrackAmazonPurchase.<init> (TrackAmazonPurchase.java:58)
com.onesignal.OneSignal.handleAmazonPurchase (OneSignal.java:9)
com.onesignal.OneSignal.k (OneSignal.java:93)
com.onesignal.OneSignal.j (OneSignal.java:87)
com.onesignal.OneSignal.reassignDelayedInitParams (OneSignal.java:58)
com.onesignal.OneSignal.onRemoteParamSet (OneSignal.java)
com.onesignal.OneSignal$5.complete (OneSignal.java:29)
com.onesignal.OneSignalRemoteParams.b (OneSignalRemoteParams.java:10)
com.onesignal.OneSignalRemoteParams.access$000 (OneSignalRemoteParams.java)
com.onesignal.OneSignalRemoteParams$1.a (OneSignalRemoteParams.java:2)
com.onesignal.OneSignalRestClient$5.run (OneSignalRestClient.java:4)
java.lang.Thread.run (Thread.java:919)

**Comment by jkasten2** [comment]
@zsliu The crash is now fixed in [react-native-onesignal 4.2.0](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.2.0).
