### ISSUE TITLE
[Bug] Can't clear badge count by myself

### ISSUE THREAD

**Issue by wuchengyu** [OneSignal/react-native-onesignal#1266]
**Description:**

**I want to clear badge at specific page instead of open App and auto increase badge.**

I push notification from [website](https://app.onesignal.com/) and set iOS badge `increase by 1` many times

Steps:
1. app badge 0
2. push notification
3. app badge 1
4. open App to specific page
5. call `PushNotification.setApplicationIconBadgeNumber(0)`
6. push notification > app badge 2 (expect 1)

**Environment**

- react-native: 0.64.2
- react-native-onesignal: 4.0.8
- OneSignal: 3.4.3
- info.plist: `OneSignal_disable_badge_clearing=true`
- iOS: 14.7.1

I try to upgrade `react-native-onesignal` to 4.2.0 but it still occur.

**Steps to Reproduce Issue:**

1. Push notification from [website](https://app.onesignal.com/) and set iOS badge `Set to 1` is working

**Comment by jkasten2** [comment]
@wuchengyu Thanks for providing steps to reproduce the issue. This is a symptom of something not correct with your App Groups setup in Xcode.

Please double check you have the same App Group setup for both your targets noted in all parts of the steps under 4.4:
https://documentation.onesignal.com/docs/react-native-sdk-setup#step-4-install-for-ios-using-cocoapods-for-ios-apps

More details with troubleshooting for App Groups below:
https://documentation.onesignal.com/docs/ios-sdk-app-groups-setup

**Comment by wuchengyu** [comment]
@jkasten2  Thank you so much, it solved.

We forgot to add different environment bundle id to App group.
