### ISSUE TITLE
`RCTOneSignal.h file not found` build error

### ISSUE THREAD

**Issue by mnmeyers** [OneSignal/react-native-onesignal#127]
I know this is a common issue but I tried everything many times and I keep getting the same error, not sure what to try next. 

![image](https://cloud.githubusercontent.com/assets/10369508/21584110/323382dc-d050-11e6-9c59-1071a3c20bf4.png)

![image](https://cloud.githubusercontent.com/assets/10369508/21584122/a984668a-d050-11e6-8b65-954d9b699736.png)

![image](https://cloud.githubusercontent.com/assets/10369508/21584126/c5620f74-d050-11e6-94b9-b359ff638aaf.png)

![image](https://cloud.githubusercontent.com/assets/10369508/21584142/19b8ed2c-d051-11e6-8316-4f88e35e67c4.png)

this is the contents of my Podfile

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloWorld' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HelloWorld
pod 'OneSignal', '1.13.3'


end
 target 'HelloWorldTests' do
    inherit! :search_paths
    # Pods for testing
  end
```

using    react-native 0.35.0, react-native-onesignal ^1.2.3
using xcode v. 8.2
thank you!!!

**Comment by mnmeyers** [comment]
I upgraded to beta version of react-native-onesignal and v 2.2.0 of OneSignal pod, same issue still persists

**Comment by avishayil** [comment]
Do you still encounter this issue?
Are you sure you're using the latest version and pod as mentioned in the docs?

**Comment by nilsers** [comment]
Hi!

I'm having the same issue and I have installed the pod as mentioned in the docs.

The build fails with error:

    AppDelegate.h:11:9: fatal error: 'RCTOneSignal.h' file not found
    #import <RCTOneSignal.h>

I'm using pod version 1.1.1 and Xcode Version 8.2.1 (8C1002) on a macOS 10.12

I have uploaded a demo React Native project which has this issue to my repo [onesignal-issuedemo](https://github.com/nilsers/onesignal-issuedemo) if it helps you. 

Thank you for your help!

**Comment by mnmeyers** [comment]
yes I still have this issue. I'm using one signal pod 2.2.0. pod version 1.1.1. , mac osx 10.11.6

react-native-onesignal version: git://github.com/geektimecoil/react-native-onesignal.git#dev

react-native version 0.35.0

**Comment by avishayil** [comment]
@nilsers i'll try running your project and will let you know.

**Comment by avishayil** [comment]
@nilsers,
Please add the following to your target `Header Search Paths` under `Build Settings` on your XCode workspace:
`$(SRCROOT)/../node_modules/react-native-onesignal/ios/RCTOneSignal`
Should build fine, as I tested on your repository.

**Comment by GeoffreyPlitt** [comment]
@mnmeyers Did you ever get it working? I'm having same probs as you, tried everything here, no dice.

**Comment by mnmeyers** [comment]
@GeoffreyPlitt I'm getting a bunch of different errors now, pasted below. still debugging. I may try just starting on a new branch, and starting over again. will report back. are you still getting the same error or different ones?

![image](https://cloud.githubusercontent.com/assets/10369508/22090755/c16cc2c8-dda8-11e6-959b-a67895aecefe.png)

**Comment by GeoffreyPlitt** [comment]
Thanks so much for the help! I don't get these errors, no. By the way I'm on XCode 8.2.1, not sure if that makes a difference.

Yes feel free to fork the master branch of https://github.com/GeoffreyPlitt/react_native_minimal to try yourself.

**Comment by GeoffreyPlitt** [comment]
By the way, I have another branch you can fork, which uses v1.2.3 of this lib, and still has those same errors:

https://github.com/GeoffreyPlitt/react_native_minimal/tree/onesignal_123

```
In file included from /Users/giro/react_native_minimal/ios/react_native_minimal/AppDelegate.m:10:
In file included from /Users/giro/react_native_minimal/ios/react_native_minimal/AppDelegate.h:11:
../node_modules/react-native-onesignal/ios/RCTOneSignal/RCTOneSignal.h:3:9: fatal error: 'OneSignal/OneSignal.h' file not found
#import <OneSignal/OneSignal.h>
        ^
```

**Comment by mnmeyers** [comment]
@GeoffreyPlitt so I realized that those errors I was getting were all in the tests folder so I just deleted them  (right click > delete) from xcode (the remove references option, not true delete) and then the build succeeded. probably those tests are needed for something but.... that's for another day haha

**Comment by davidfekke** [comment]
I am DOA. I am having the same error.

**Comment by mnmeyers** [comment]
@davidfekke which version of one signal and react-native-one-signal are you using and did you try adding the header search paths as suggested above, did that change anything?

**Comment by avishayil** [comment]
@mnmeyers @davidfekke @GeoffreyPlitt Can you share repositories with the errors reproduceable?

**Comment by GeoffreyPlitt** [comment]
Yes, my repo that reproduces header issues is at https://github.com/GeoffreyPlitt/react_native_minimal/tree/onesignal. Note: Part of my specific problem is that I'm trying to get it working WITHOUT cocoapods; and the error I'm getting is slightly different than the title of this issues, it's about "OneSignal/OneSignal.h" not being found.

Also: Just saw a suggestion on #153  I'm going to try.

**Comment by egunsoma** [comment]
Hello guys,

@mnmeyers @davidfekke @GeoffreyPlitt

I had the same issue, and adding 
```$(SRCROOT)/../node_modules/react-native-onesignal/ios/RCTOneSignal```
to ```Header Search Paths``` in ```Build Settings``` solved my problem. 

Make sure you set them for ***recursive***!!! Did not worked until I changed that.

**Comment by passabilities** [comment]
@egunsoma I've done this. Set to recursive. Still saying 
```
/path/to/project/AppDelegate.h:11:9: fatal error: 'RCTOneSignal.h' file not found
```

**Comment by Pampounet** [comment]
I have followed the same steps as you, and I keep having the same error than @passabilities : 
`path/AppDelegate.h:11:9: 'RCTOneSignal.h' file not found`

**Comment by jkasten2** [comment]
@Pampounet I recommend updating to the latest 3.0.3 version of this SDK. It greatly simplifies the iOS setup process.
https://github.com/geektimecoil/react-native-onesignal#ios-installation

Most of the above comments do not apply to version 3.0.3 as paths have changed and the iOS native source is now included with this SDK.

**Comment by Pampounet** [comment]
@jkasten2 Thanks for your help ! Now I'm getting a new error that makes build failing : 
`ld: 102 duplicate symbols for architecture x86_64`
I'm going to seek help about it now !

**Comment by jkasten2** [comment]
@Pampounet Make sure to remove all other copies of the OneSignal iOS native SDK. Such as from cocoapods, manual, or carthage.

**Comment by Pampounet** [comment]
@jkasten2 Finally, I had to remove $(inherited) flag in Other Files Flag in my target Build Settings : the build succeeded, but my app is not working anymore... Still working on it !

**Comment by jkasten2** [comment]
@Pampounet You might want to start over with a new react project and get the OneSignal SDK up and running. Then copy in your existing javascript code.

**Comment by Pampounet** [comment]
@jkasten2 I will try this way, since I don't succeed running anything... but Android version works well, so I keep developing on it for the moment !
Thanks !

**Comment by Pampounet** [comment]
@jkasten2 So I tried, and did not manage making it working :'(

**Comment by therahuls1ngh** [comment]
im getting this error after i solved architecture one 
Cannot find protocol declaration for 'OSSubscriptionObserver'

**Comment by HananeAlSamrout** [comment]
add "$(SRCROOT)/../node_modules/react-native-onesignal/ios" non-recursive in Framework Search paths
and 
add "$(SRCROOT)/../node_modules/react-native-onesignal/ios" recursive in Header search paths

**Comment by andreechristian** [comment]
@HananeAlSamrout solution works for me! Thanks

**Comment by 25matt12** [comment]
@HananeAlSamrout worked for me too! :)

Thanks

**Comment by vadermemo** [comment]
work! Even when is to candidate release
Thanks @HananeAlSamrout

**Comment by tlloydukdev** [comment]
I had to comment out the podfile entry for onesignal to get this to work

**Comment by Assiance** [comment]
I found the issue. When adding $(SRCROOT)/../node_modules/react-native-onesignal/ios. I noticed that in the project.pbxproj file the entry was placed using { instead of ( in $(SRCROOT). Whenever I add through xCode the string would be wrong. I manually modified the file and now everything works correctly

**Comment by Jeet007das** [comment]
> @egunsoma I've done this. Set to recursive. Still saying
> 
> ```
> /path/to/project/AppDelegate.h:11:9: fatal error: 'RCTOneSignal.h' file not found
> ```

i also have same issue in NativeBridgeModel.m that AppDelegate.h not found
