### ISSUE TITLE
Doesn't build with React Native >=0.65.0

### ISSUE THREAD

**Issue by reichhartd** [OneSignal/react-native-onesignal#1270]
**Description:**

Doesn't build with React Native >=0.65.0, since this version requires `platform :ios, '11.0'` in the Podfile. It does work with `platform :ios, '10.0'`

**Environment**

```
"react-native": "0.65.1",
"react-native-onesignal": "^4.3.0",
```

**Steps to Reproduce Issue:**

1. Install the OneSignal SDK using npm into your project
2. Open XCode
3. Product > Archive

**Anything else:**

(crash stacktraces, as well as any other information here)

```
Showing Recent Messages
/Users/<USER>/workspace/<APP>/ios/OneSignalNotificationServiceExtension/NotificationService.swift:10:8: No such module 'OneSignal'
```

**Comment by jkasten2** [comment]
@reichhartd Can you check in Xcode what you have the iOS version under "Deployment info" set to? It should match what you have in the `Podfile`.
![image](https://user-images.githubusercontent.com/645861/130669690-145e5f70-3560-469a-9429-1648586fb683.png)

If that does not help could you share your full `Podfile`?

**Comment by reichhartd** [comment]
My fault. Didn't know that it has to match, but makes definitely sense. Fixed my issue.
Thank you very much for your help!

**Comment by fkapsahili** [comment]
> @reichhartd Can you check in Xcode what you have the iOS version under "Deployment info" set to? It should match what you have in the `Podfile`. ![image](https://user-images.githubusercontent.com/645861/130669690-145e5f70-3560-469a-9429-1648586fb683.png)
> 
> If that does not help could you share your full `Podfile`?

This was the problem for me after I updated my React Native version. I got a 'No Such Module "OneSignal"' error on my Intel Mac only when archiving the app (any iOS Device arm64). With switching to iOS 11 in Xcode according to the new Podfile since the RN update, it works again.
