### ISSUE TITLE
an error occured when trying to build android

### ISSUE THREAD

**Issue by m7amad-7asan** [OneSignal/react-native-onesignal#1271]
Could not determine the dependencies of task ':react-native-onesignal:compileReleaseRenderscript'.
> Could not resolve all task dependencies for configuration ':react-native-onesignal:releaseCompileClasspath'.
   > Could not find any matches for com.google.firebase:firebase-messaging:[10.2.1, 17.3.99] as no versions of com.google.firebase:firebase-messaging are available.
     Required by:
         project :react-native-onesignal > com.onesignal:OneSignal:3.15.3

**Comment by jkasten2** [comment]
@m7amad-7asan Thanks for reporting. Could you include your full root `build.gradle` and your `app/build.gradle` files?

Also if you could provide your `package.json` file so we can try to reproduce the issue with a new project with the same plugins.

Lastly if you can include the full error from the terminal so we have the full details of the error.

**Comment by rgomezp** [comment]
Closing due to no response
