### ISSUE TITLE
Badge number not incrementing as expected with a cancelled notification

### ISSUE THREAD

**Issue by pkpbynum** [OneSignal/react-native-onesignal#1273]
**Description:**
The app badge number is not incrementing as expected when calling `event.complete(null)` instead of `event.complete(notification)` in `OneSignal.setNotificationWillShowInForegroundHandler(event => { ... })`.

For example:
If your app has `badgeCount = 0` and you call `event.complete(null)` on an incoming notification which increments the badge number by `1`, the visual `badgeCount` on the iOS Home Screen remains at `0` as expected. HOWEVER, when you receive a _second_ notification which increments the badge, the `badgeCount` is set to `2`, whereas it should be set to `1` (as if the first notification never happened). My guess is that's caused by the NSE aways incrementing the internal state even when the notification is cancelled with `event.complete(null)`?

This is slightly subjective, but I expected that calling `event.complete(null)` on a notification that is set to increment a badge would fully cancel it--i.e. the visual badge number and internal counter will NOT increment.

**Environment**
Installed with yarn
```
"react-native": "0.63.3",
"react-native-onesignal": "^4.2.0",
```

Podfile (this is the only OneSignal-related thing):
```
platform :ios, '12.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.4.3', '< 4.0'
end
```

**Steps to Reproduce Issue:**

1. Install and set up the OneSignal SDK using yarn, as well as the NSE and app groups to support badge icons
2. Open the app
3. Send a push notification set to increment the badge number by 1 and call `event.complete(notification)` in the `OneSignal.setNotificationWillShowInForegroundHandler` (here the app badge number should say 1)
4. Still with the app open, send another push notification set to increment the badge number by 1 but call `event.complete(null)` (the app badge number should still be 1)
5. Now exit the app and send another push notification to increment the badge number
Result: The app badge number now says 3 instead of 2

**Reproduction recording**
In the below video the app badge number starts at 0. I'm then doing the following:
1. With app open, sent a notification to increment the badge, calling `event.complete(notification)`
2. Opened a new screen where notifications are cancelled with `event.complete(null)`
3. Sent another notification which increments the badge
4. Left the app -- here you can see the badge is at `1` because the second notification was cancelled
5. Sent one more notification to increment the badge number again
6. The badge number reads 3 instead of 2

https://user-images.githubusercontent.com/34200453/130857713-f0b3e886-6984-4ff3-89af-b8eaa50c8cba.MP4

**Comment by rgomezp** [comment]
Howdy,
Thank you for reporting this. It sounds like it could be a bug. Thanks for your patience in advance while we investigate.

**Comment by rgomezp** [comment]
Howdy,
We have confirmed this is a bug. Thanks for reporting.

**Comment by rgomezp** [comment]
Howdy,
This has been resolved. Please update to the latest.

**Comment by FayyazAliKhan1** [comment]
@pkpbynum I have tried alot but badge is not incrementing in iOS, I have posted an issue as well, kindly look into it if you can help [https://github.com/OneSignal/react-native-onesignal/issues/1408](1408)
