### ISSUE TITLE
OneSignalNotificationServiceExtension is faild while building in app center

### ISSUE THREAD

**Issue by Bayramito** [OneSignal/react-native-onesignal#1280]
I'm getting this error on appcenter while building in IOS. 

In my local PC i dont get any errors in xcode and can build the app successfully.

** ARCHIVE FAILED **

```
The following build commands failed:
	Ld /Users/runner/Library/Developer/Xcode/DerivedData/omuzreact-hcixjlvunigeysgolbdoikjyfeus/Build/Intermediates.noindex/ArchiveIntermediates/omuzreact/IntermediateBuildFilesPath/omuzreact.build/Release-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/armv7/Binary/OneSignalNotificationServiceExtension normal armv7
(1 failure)`

```

**Environment**

    "react-native-onesignal": "^4.0.4",
    "react-native": "0.64.2",

**Comment by KestasVenslauskas** [comment]
@Bayramito Did you find a solution?

**Comment by rgomezp** [comment]
Howdy,
This doesn't seem to be a OneSignal issue. Please take a look at [this thread here](https://github.com/microsoft/appcenter-sdk-react-native/issues/837).

Cheers
