### ISSUE TITLE
Android build fails because of  androidx.browser:browser

### ISSUE THREAD

**Issue by wbroek** [OneSignal/react-native-onesignal#1283]
**Description:**
Building an Android app with the latest OneSignal React Native SDK results in a failure:
```
Execution failed for task ':app:checkSANDBOXDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.browser:browser:1.4.0-alpha01.
     AAR metadata file: /Users/wouter/.gradle/caches/transforms-3/a242e370124337b50dcc631ad961c935/transformed/browser-1.4.0-alpha01/META-INF/com/android/build/gradle/aar-metadata.properties.

```

Why I say it's de OneSignal SDK, it's the only dependency with androidx.browser in my project:
```
+--- project :react-native-onesignal
|    \--- com.onesignal:OneSignal:4.5.1
|         +--- com.google.firebase:firebase-messaging:[19.0.0, 22.0.99] -> 20.2.4 (*)
|         +--- androidx.cardview:cardview:[1.0.0, 1.0.99] -> 1.0.0
|         |    \--- androidx.annotation:annotation:1.0.0 -> 1.3.0-alpha01
|         +--- androidx.legacy:legacy-support-v4:[1.0.0, 1.0.99] -> 1.0.0 (*)
|         +--- androidx.browser:browser:[1.0.0, 1.3.99] -> 1.4.0-alpha01
```

**Environment**
React Native 0.65.1
react-native-onesignal: 4.3.0
Android Studio 2020.3.1

**Steps to Reproduce Issue:**
npx react-native init AwesomeProject
cd AwesomeProject
npm install react-native-onesignal
(other one signal sdk instructions)
build app

**Anything else:**

In search in the internet found https://stackoverflow.com/questions/69208613/getting-error-while-running-react-native-app and gives explanation why:
_From September 15, 2021 a new version released for androidx.browser:1.4.0-alpha01 it contains minSDK version 31_

The solution below works for us for now:
Add in `android/app/build.gradle`
```
configurations.all {
    resolutionStrategy {
        force 'androidx.browser:browser:1.3.0'
    }
}
```

**Comment by Aryan6290** [comment]
https://stackoverflow.com/a/69030792/13755957
This might help

**Comment by rgomezp** [comment]
Howdy, please try @Aryan6290 's suggestion.

Cheers

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by ger-lm** [comment]
any clue on this?
