### ISSUE TITLE
Duplicated Notifications Android only, Intermittently

### ISSUE THREAD

**Issue by geun** [OneSignal/react-native-onesignal#1284]
**Description:**

(your description here)

Our Android customer received duplicated notifications. 
I already read https://documentation.onesignal.com/docs/duplicated-notifications but It looks like a sever-side errors. 
I report to support channel too

I use api with Send to segments(Subscribed Users)

Total number of recipients 896 / Sent 3, Duplicated notifications on Android.

<img width="1185" alt="Screen Shot 2021-09-18 at 7 03 58 PM" src="https://user-images.githubusercontent.com/1306061/133885612-30114621-f3c5-4650-824d-03f6604fe209.png">

Total number of recipients 1047 / Sent 1047, No Error(Just one notification on Android)

<img width="1201" alt="Screen Shot 2021-09-18 at 7 18 32 PM" src="https://user-images.githubusercontent.com/1306061/133885645-9fa8a789-667c-43a8-8b57-81ba3cd535b8.png">

**Environment**

React-Native: 0.63.4
Onesignal RN SDK: 4.3.0
Using Yarn 

**Steps to Reproduce Issue:**

I tested, 
1) Single player id 
2) Single External User Id
3) Multiple External User Id

Errors occur intermittently with Send to segments(Subscribed Users)
`"included_segments": ["Subscribed Users"]`
Duplicate messages come about once in seven cases. It's not always repeated.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Duplicate of https://github.com/OneSignal/OneSignal-Android-SDK/issues/1419
