### ISSUE TITLE
Device unsubscribe after sending notification

### ISSUE THREAD

**Issue by HunterJS-bit** [OneSignal/react-native-onesignal#1289]
The android device gets unsubscribed after sending notification 

**Description:**

I register the device to **one-signal**, 

```
import DeviceInfo from 'react-native-device-info';

    const date = new Date();
    const timeZoneOffset = date.getTimezoneOffset();


    const deviceInfo = {
        app_id: "", // load from env
        identifier: "1",
        language: de',
        timezone: timeZoneOffset,
        game_version: "1.0",
        device_os: '1.0',
        device_type: 1,
        device_model: DeviceInfo.getModel(),
        tags: {"user_id":"2333","foo":"bar"}
    };

// on route
// https://onesignal.com/api/v1/players

```

The device is successfully registered on One Signal I see the device in the Users List

I use the following code below to register a new device 

```

import React, { useEffect } from 'react';
import {Provider} from 'react-redux';

import {RootNavigation} from '_navigation';
import {store} from '_store/configureStore';
import {LocalizationProvider} from '_services/localization/LocalizationContext';
import OneSignal from 'react-native-onesignal';
import {enableScreens} from 'react-native-screens';

enableScreens();

const App = () => {


    useEffect(() => {
        console.log('LOAD ONE SIGNAL');


        OneSignal.setLogLevel(6, 0);
        OneSignal.setAppId("", { kOSSettingsKeyAutoPrompt: true }); // move to env

        OneSignal.setRequiresUserPrivacyConsent(true);

        //Method for handling notifications received while app in foreground
        OneSignal.setNotificationWillShowInForegroundHandler(notificationReceivedEvent => {
            console.log("OneSignal: notification will show in foreground:", notificationReceivedEvent);
            let notification = notificationReceivedEvent.getNotification();
            console.log("notification: ", notification);
            const data = notification.additionalData
            console.log("additionalData: ", data);
            // Complete with null means don't show a notification.
            notificationReceivedEvent.complete(notification);
        });


        //Method for handling notifications opened
        OneSignal.setNotificationOpenedHandler(notification => {
            console.log("OneSignal: notification opened:", notification);
        });

        OneSignal.addSubscriptionObserver(event => {
            console.log('Subscribtion observer');
        });

        return (() => {
            OneSignal.clearHandlers();
        })
    }, [])

  return (
    <LocalizationProvider>
      <Provider store={store}>
        <RootNavigation />
      </Provider>
    </LocalizationProvider>
  );
};

export default App;
```

But when I send a notification from OneSignal, I get 
**Failed (Unsubscribed)**, and when I view the device in the list I get _Not Subscribed_ in Subscription header

**Comment by rgomezp** [comment]
Howdy,
Can you please include the details outlined in the Issue template? Mainly, the SDK version as well as all other relevant environment info.

Cheers

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by ukgrafix** [comment]
I have the same issue.
After installing the SDK and generating the dev build.
On Opening the App on Mobile. The Subscribers count increases on OneSignal Dashboard.
After creating a new Push, on clicking on Send Test Push or deliver Push.
Nothing happens, No notifications received on mobile, and on refreshing the Onesignal Subscriptions page, the Tick symbol on the mobile subscribers shows as 'Not Subscribed'..

Tried multiple times but the same results..

Hers is my code to Initialize the Onesignal on React Native expo app


``import { LogLevel, OneSignal } from 'react-native-onesignal';
import Constants from "expo-constants";

export const InitializeOneSignalNotifications = () => {
    OneSignal.Debug.setLogLevel(LogLevel.Verbose);
    OneSignal.initialize(Constants.expoConfig.extra.oneSignalAppId);

    OneSignal.Notifications.requestPermission(true);

    OneSignal.Notifications.addEventListener('click', (event) => {
      console.log('OneSignal: notification clicked:', event);
    });
}``
