### ISSUE TITLE
Error when installing react-native-onesignal

### ISSUE THREAD

**Issue by adrianha** [OneSignal/react-native-onesignal#129]
HiHi,
I'm using react-native v0.38.0 and react-native-onesignal v1.2.3.. I got this error when rebuild the app.
![Error message](https://cloud.githubusercontent.com/assets/5382429/21675624/16846980-d365-11e6-8213-d992787a5b35.png)
What did i miss?

**Comment by avishayil** [comment]
Solved on version 2.
Please try it and let me know if you have any trouble.
Thanks!

**Comment by adrianha** [comment]
![I got this error message](https://cloud.githubusercontent.com/assets/5382429/22006025/6a7307d4-dc9a-11e6-9fa8-7aa40a4de191.png)
Hi @avishayil ,
I got another problem when using react-native-onesignal@3.0.0.
it raises an error when importing this "import com.geektime.reactnativeonesignal.ReactNativeOneSignalPackage;"
it appears that this project cannot resolve 'reactnativeonesignal'
what should i do?
Thank you very much

**Comment by adrianha** [comment]
hi, i got this error when installing on fresh react-native app.
![Err](https://cloud.githubusercontent.com/assets/5382429/22090487/95b80d5a-de24-11e6-994e-ed267d2de2de.png)
I'm using:
+ react-native v0.40.0
+ react-native-onesignal v3.0.0
cc: @avishayil , @jkasten2

**Comment by avishayil** [comment]
Could you please post a repo for this?

**Comment by adrianha** [comment]
I'm sorry @avishayil. There's some mismatch configuration, its working now.
Thank you for your attention.

**Comment by dcalogue** [comment]
@adrianha can you share how you solved this issue? I'm seeing the same thing here.

Thanks!

**Comment by adrianha** [comment]
hi @dcalogue ,

Last time i encountered this,
i replace distributionUrl on gradle-wrapper.properties to `distributionUrl=https://services.gradle.org/distributions/gradle-2.14.1-all.zip`
and also delete test project on react-native-onesignal

hope it helps!
