### ISSUE TITLE
OneSignal Notification App openning issues

### ISSUE THREAD

**Issue by LoknathPandit** [OneSignal/react-native-onesignal#1292]
"react-native-onesignal": "^4.3.1",
"react-native": "^0.64.1",

**Comment by LoknathPandit** [comment]
Nothing happen on click notification in android while app is in kill state i.e app is not running in foreground and background
but it is working in firebase notification

**Comment by sclavijo93** [comment]
Maybe is related to https://github.com/OneSignal/react-native-onesignal/issues/1288

**Comment by nickksm** [comment]
"react-native": "0.64.2",
"react-native-onesignal": "^4.3.1",

Same here. On Android nothing happens when the app is in kill state. On IOS the app still opens but the deep linking doesn't navigate to the screen I specify.

**Comment by nickksm** [comment]
I reverted back to react-native-onesignal@4.1.1 and everything works as expected. The app opens even on kill state for Android, and the deep linking works as expected as well. 

I haven't checked for IOS but I think it will work too because my other app is working fine using 4.1.1.

**Comment by rgomezp** [comment]
Duplicate of #1288
