### ISSUE TITLE
How to automatically enable Autostart permission for xiaomi device? Other devices work well.

### ISSUE THREAD

**Issue by minhtet-BeeComTech** [OneSignal/react-native-onesignal#1297]
Description:

How to automatically enable Autostart permission for xiaomi device? Other devices work well.

Environment

 "react-native": "0.64.2"
 "react-native-onesignal": "^4.3.1"

**Comment by rgomezp** [comment]
Howdy,
Based on [this thread](https://stackoverflow.com/questions/39366231/how-to-check-miui-autostart-permission-programmatically), it sounds like this is a limitation of Xiaomi devices. We can likely presume that if there is no read permission (subject of thread) then there is unlikely to be a write permission or setter functionality.

Thanks for your question
