### ISSUE TITLE
Can't find variable: OneSignal  @ index.js

### ISSUE THREAD

**Issue by lucholabs** [OneSignal/react-native-onesignal#1302]
Hello everyone! I did everything as is explained at OneSignal React Native SDK, im using expo bare workflow.  but after compile successful im getting this error: **Can't find variable: OneSignal**       

Error comes from file  index.js

[Sat Oct 16 2021 22:37:10.460]  BUNDLE  ./index.js 
[Sat Oct 16 2021 22:37:13.690]  LOG      Running "main" with {"rootTag":1,"initialProps":{}}
**[Sat Oct 16 2021 22:37:13.710]  ERROR    ReferenceError: Can't find variable: OneSignal**

I try some stuff but no luck.. I need help please! thanks!
<img width="354" alt="Captura de pantalla 2021-10-16 a las 22 31 09" src="https://user-images.githubusercontent.com/87378208/137601704-51ff92e1-3521-40bb-b385-3c6a9b1b1ffd.png">

**Comment by longtqdayma** [comment]
I am use App.js
import OneSignal from 'react-native-onesignal';
Have you imported to index.js?

`
import 'react-native-gesture-handler';
import OneSignal from 'react-native-onesignal';
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
`

**Comment by lucholabs** [comment]
Thanks!!   I was placing wrong the import like this: import { OneSignal } from 'react-native-onesignal';

I tryied without {} work perfect.... This importa line should be in the documentation anyway. 

> I am use App.js import OneSignal from 'react-native-onesignal'; Have you imported to index.js?
> 
> ` import 'react-native-gesture-handler'; import OneSignal from 'react-native-onesignal'; import {AppRegistry} from 'react-native'; import App from './App'; import {name as appName} from './app.json';
> 
> AppRegistry.registerComponent(appName, () => App); `

**Comment by nan-li** [comment]
Happy to hear it is figured out and thank you for bringing this up. We are updating the code example to include the import.
