### ISSUE TITLE
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.

### ISSUE THREAD

**Issue by longtqdayma** [OneSignal/react-native-onesignal#1303]
I use
React native 0.66.1

 "react": "17.0.2",
 "react-native": "0.66.1",
 "react-native-onesignal": "^4.3.1",

Only on android

 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.

```
useEffect(() => {
    OneSignal.setLogLevel(6, 0);
    OneSignal.setAppId(Platform.OS === 'android'? 'android-app-id': 'ios-app-id');
    OneSignal.setNotificationWillShowInForegroundHandler(notificationReceivedEvent => {
      console.log('OneSignal: notification will show in foreground:', notificationReceivedEvent);
      let notification = notificationReceivedEvent.getNotification();
      console.log('notification: ', notification);
      const data = notification.additionalData
      console.log('additionalData: ', data);
      notificationReceivedEvent.complete(notification);
    });
    OneSignal.setNotificationOpenedHandler(notification => {
      console.log('OneSignal: notification opened:', notification);
    });
    OneSignal.setExternalUserId("Longdv.RN661");
  }, []);
```

using v8.
<img width="326" alt="Screenshot 2021-10-17 at 10 08 39" src="https://user-images.githubusercontent.com/1575246/137609287-4ce6b81e-d71f-4511-8021-b20114c01ef8.png">

![image](https://user-images.githubusercontent.com/1575246/137609584-2a5ec9f4-2c24-4310-87e3-2b920b95f504.png)

**Comment by rgomezp** [comment]
Howdy,
It seems to be coming from [here](https://github.com/facebook/react-native/blob/77ecc7ede1da8fc590d7bc238a2fc02daa736746/Libraries/EventEmitter/NativeEventEmitter.js#L58-L72), a new requirement added recently by React Native.

Thanks for surfacing this, we'll try to get it fixed.

**Comment by LahmerIlyas** [comment]
When will we have this fixed. I dont want to downgrade react native version in order to use onesignal ?

**Comment by rgomezp** [comment]
This is fixed. Please upgrade to the latest version.
