### ISSUE TITLE
 executing service com.appName/com.onesignal.FocusDelaySyncJobService

### ISSUE THREAD

**Issue by invyctus92** [OneSignal/react-native-onesignal#1308]
Error from Bugsnag 

executing service com.appName/com.onesignal.FocusDelaySyncJobService         at com.onesignal.LocationController.onFocusChange(LocationController.java:324)         at com.onesignal.OneSignal.onAppFocus(OneSignal.java:1355)         at com.onesignal.ActivityLifecycleHandler.handleFocus(ActivityLifecycleHandler.java:182)         at com.onesignal.ActivityLifecycleHandler.onActivityResumed(ActivityLifecycleHandler.java:88)         at com.onesignal.ActivityLifecycleListener.onActivityResumed(ActivityLifecycleListener.java:91)         at android.app.Application.dispatchActivityResumed(Application.java:438)         at android.app.Activity.dispatchActivityResumed(Activity.java:1445)         at android.app.Activity.onResume(Activity.java:1984)         at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:433)         at com.facebook.react.ReactActivity.onResume(ReactActivity.java:57)         at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)         at android.app.Activity.performResume(Activity.java:8297)         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4577)         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4619)         at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)         at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2173)         at android.os.Handler.dispatchMessage(Handler.java:106)         at android.os.Looper.loop(Looper.java:236)         at android.app.ActivityThread.main(ActivityThread.java:8043)         at java.lang.reflect.Method.invoke(Method.java:-2)         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

--

**Environment**
    "react": "17.0.2",
    "react-native": "0.66.1",
    "react-native-onesignal": "4.3.1",

Device Redmi Note 8 Pro with
"androidApiLevel": "30",   "osBuild": "RP1A.200720.011",   "reactNative": "0.66.1",   "reactNativeJsEngine": "hermes"

**Comment by rgomezp** [comment]
Howdy,
What exactly is the error here?

I see `executing service com.appName/com.onesignal.FocusDelaySyncJobService` but that doesn't sound like an error. 

Did you include the full logs?

**Comment by invyctus92** [comment]
Bugsnag does not give me details of the error, in fact it says ANR

`ANR:  executing service com.appName/com.onesignal.FocusDelaySyncJobService         at com.onesignal.LocationController.onFocusChange(LocationController.java:324)         at com.onesignal.OneSignal.onAppFocus(OneSignal.java:1355)         at com.onesignal.ActivityLifecycleHandler.handleFocus(ActivityLifecycleHandler.java:182)         at com.onesignal.ActivityLifecycleHandler.onActivityResumed(ActivityLifecycleHandler.java:88)         at com.onesignal.ActivityLifecycleListener.onActivityResumed(ActivityLifecycleListener.java:91)         at android.app.Application.dispatchActivityResumed(Application.java:438)         at android.app.Activity.dispatchActivityResumed(Activity.java:1445)         at android.app.Activity.onResume(Activity.java:1984)         at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:433)         at com.facebook.react.ReactActivity.onResume(ReactActivity.java:57)         at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)         at android.app.Activity.performResume(Activity.java:8297)         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4577)         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4619)         at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)         at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2173)         at android.os.Handler.dispatchMessage(Handler.java:106)         at android.os.Looper.loop(Looper.java:236)         at android.app.ActivityThread.main(ActivityThread.java:8043)         at java.lang.reflect.Method.invoke(Method.java:-2)         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)`

**Comment by rgomezp** [comment]
Howdy,
Could you please turn on OneSignal logging with `setLogLevel` and include the full native logs when the issue occurs? It seems the bugsnag doesn't include enough info to fully diagnose the problem.

**Comment by rgomezp** [comment]
Closing due to no response
