### ISSUE TITLE
xiaomi notification cannot open app due to permissions

### ISSUE THREAD

**Issue by mehmetcansahin** [OneSignal/react-native-onesignal#1309]
**Description:**
xiaomi notification cannot open the app due to permissions. As far as I have researched, it is necessary to allow "display pop-up window in foreground and in background" from the application settings.

**Environment**
Device: xiaomi redmi s2
Package version: 4.3.1

**Steps to Reproduce Issue:**
1. close your app
2. send your notification
3. open notification (app not opening)

**Comment by rgomezp** [comment]
Howdy,
I found the following thread: https://github.com/zoontek/react-native-permissions/issues/412#issuecomment-655601294 that might be related.

Thanks for your patience while we continue investigating.

**Comment by mehmetcansahin** [comment]
You are directed to the permission page with the module below. However, I could not see a control mechanism for this permission unfortunately.

```java
package com.package.name;

import android.content.Intent;
import android.net.Uri;
import android.os.Build;
import android.os.Environment;
import android.provider.Settings;
import android.util.Log;

import com.facebook.react.bridge.NativeModule;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Map;
import java.util.HashMap;
import java.util.Properties;

public class MIUIPopupPermission extends ReactContextBaseJavaModule {
    MIUIPopupPermission(ReactApplicationContext context) {
        super(context);
    }

    @Override
    public String getName() {
        return "MIUIPopupPermission";
    }

    @ReactMethod
    private void onDisplayPopupPermission() {
        ReactApplicationContext context = getReactApplicationContext();
        try {
            // MIUI 8
            Intent localIntent = new Intent("miui.intent.action.APP_PERM_EDITOR");
            localIntent.setClassName("com.miui.securitycenter",
                    "com.miui.permcenter.permissions.PermissionsEditorActivity");
            localIntent.putExtra("extra_pkgname", getPackageName());
            localIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            context.startActivity(localIntent);
            return;
        } catch (Exception ignore) {
        }
        try {
            // MIUI 5/6/7
            Intent localIntent = new Intent("miui.intent.action.APP_PERM_EDITOR");
            localIntent.setClassName("com.miui.securitycenter",
                    "com.miui.permcenter.permissions.AppPermissionsEditorActivity");
            localIntent.putExtra("extra_pkgname", getPackageName());
            localIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            context.startActivity(localIntent);
            return;
        } catch (Exception ignore) {
        }
        // Otherwise jump to application details
        Intent intent = new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
        Uri uri = Uri.fromParts("package", getPackageName(), null);
        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        intent.setData(uri);
        context.startActivity(intent);
    }

    private String getPackageName() {
        return "com.package.name";
    }

}
```

**Comment by KestasVenslauskas** [comment]
Having same issue, any solutions for this?

**Comment by anniewey** [comment]
Having the same issue as app wasn't opening in XiaoMi devices after clicking on the notification. Above reference only can directly open the permission settings but unable to check if the permission has been enabled. This approach will open the permission settings every time app launched, even though user already give permission. Couldn't find way to enable the permission by default either.

```
Linking.sendIntent(
      'miui.intent.action.APP_PERM_EDITOR', 
      [
        {'com.miui.securitycenter': 'com.miui.permcenter.permissions.PermissionsEditorActivity'},
        {'extra_pkgname': 'com.myapp'}
      ]
    )
```

**Comment by AndrewShapovalov** [comment]
The same issue. We use the latest package version: `4.3.5`.  Reproduced on:
- Mi 9T, Android 10, MIUI Global 11.0.5
- Redmi Note 7,  Android 10, MIUI Global 12.5.3

`adb logcat '*:E' ` output while push-notification is pressing:
```
01-27 11:20:07.448  1757  3730 E ANDR-PERF-JNI: com_qualcomm_qtiperformance_native_perf_io_prefetch_start
01-27 11:20:07.452  2057  2069 E ANDR-IOP: io prefetch is disabled
01-27 11:20:07.561   749   749 E ANDR-PERF-MPCTL: No valid timer value for perflock request
01-27 11:20:07.820  2753  2753 E Launcher: changeViewByFsGestureState,  view=FitSystemWindowView,  alpha=1.0,  scale=1.0
01-27 11:20:07.820  2753  2753 E Launcher: changeViewByFsGestureState,  view=ShortcutMenuLayer,  alpha=1.0,  scale=1.0
```

`adb logcat -s OneSignal` output while push-notification is pressing:
```
01-27 11:46:17.181 23181 23181 V OneSignal: initWithContext called with: com.app.MainApplication@
01-27 11:46:17.181 23181 23181 V OneSignal: Starting OneSignal initialization!
01-27 11:46:17.188 23181 23181 V OneSignal: No class found, not setting up OSRemoteNotificationReceivedHandler
01-27 11:46:17.188 23181 23181 D OneSignal: OneSignal SDK initialization already completed.
01-27 11:46:17.206 23181 23181 D OneSignal: processIntent from context: com.onesignal.NotificationOpenedReceiver@ and intent: Intent { flg=0x34800000 cmp=com.app/com.onesignal.NotificationOpenedReceiver (has extras) }
01-27 11:46:17.206 23181 23181 D OneSignal: processIntent intent extras: Bundle[{androidNotificationId="androidNotificationId", onesignalData={"google.delivered_priority":"high","google.sent_time":1643276756189,"google.ttl":259200,"google.original_priority":"high","custom":"{\"a\":{},\"i\":\"id\"}","pri":"10","vis":"1","from":"from","alert":"😱","title":"Title-5","google.message_id":"google.message_id","google.c.sender.id":"google.c.sender.id","androidNotificationId":"androidNotificationId"}}]
01-27 11:46:17.208 23181 23181 D OneSignal: Running destroyTimeout with runnable: com.onesignal.OSNotificationOpenedResult$1@
01-27 11:46:17.208 23181 23181 D OneSignal: Running startTimeout with timeout: 5000 and runnable: com.onesignal.OSNotificationOpenedResult$1@
01-27 11:46:17.212 23181 23181 D OneSignal: OneSignal SessionManager onDirectInfluenceFromNotificationOpen notificationId: "notificationId"
01-27 11:46:17.212 23181 23181 D OneSignal: OneSignal SessionManager attemptSessionUpgrade with entryAction: NOTIFICATION_CLICK
01-27 11:46:17.212 23181 23181 D OneSignal: OSChannelTracker changed: notification_id
01-27 11:46:17.212 23181 23181 D OneSignal: from:
01-27 11:46:17.212 23181 23181 D OneSignal: influenceType: DIRECT, directNotificationId: "directNotificationId", indirectNotificationIds: null
01-27 11:46:17.212 23181 23181 D OneSignal: to:
01-27 11:46:17.212 23181 23181 D OneSignal: influenceType: DIRECT, directNotificationId: "directNotificationId", indirectNotificationIds: null
01-27 11:46:17.212 23181 23181 D OneSignal: Trackers changed to: [OSChannelTracker{tag=notification_id, influenceType=DIRECT, indirectIds=null, directId="directId"}, OSChannelTracker{tag=iam_id, influenceType=UNATTRIBUTED, indirectIds=null, directId=null}]
01-27 11:46:17.212 23181 23181 D OneSignal: OneSignal SessionManager attemptSessionUpgrade channel updated, search for ending direct influences on channels: [OSChannelTracker{tag=iam_id, influenceType=UNATTRIBUTED, indirectIds=null, directId=null}]
01-27 11:46:17.212 23181 23181 D OneSignal: OneSignal SessionManager attemptSessionUpgrade try UNATTRIBUTED to INDIRECT upgrade
01-27 11:46:17.212 23181 23181 D OneSignal: OneSignal ChannelTracker getLastReceivedIds lastChannelObjectReceived: []
01-27 11:46:17.212 23181 23181 D OneSignal: Trackers after update attempt: [OSChannelTracker{tag=notification_id, influenceType=DIRECT, indirectIds=null, directId=directId}, OSChannelTracker{tag=iam_id, influenceType=UNATTRIBUTED, indirectIds=null, directId=null}]
01-27 11:46:17.212 23181 23181 D OneSignal: OneSignal SessionManager sendSessionEndingWithInfluences with influences: [SessionInfluence{influenceChannel=notification, influenceType=DIRECT, ids=["ids"]}]
01-27 11:46:17.213 23181 23181 D OneSignal: Running destroyTimeout with runnable: com.onesignal.OSNotificationOpenedResult$1@
01-27 11:46:17.213 23181 23181 D OneSignal: Running startTimeout with timeout: 5000 and runnable: com.onesignal.OSNotificationOpenedResult$1@
01-27 11:46:17.214 23181 24711 D OneSignal: OneSignal cleanOutcomes for session
01-27 11:46:17.214 23181 24711 D OneSignal: OneSignal save unattributedUniqueOutcomeEvents: []
01-27 11:46:17.215 23181 24711 D OneSignal: FocusTimeProcessorAttributed sendTime with: END_SESSION
01-27 11:46:17.215 23181 24711 D OneSignal: FocusTimeProcessorAttributed:getUnsentActiveTime: 0
01-27 11:46:17.228 23181 24712 D OneSignal: OneSignalRestClient: Making request to: https://api.onesignal.com/notifications/id
01-27 11:46:17.230 23181 24712 D OneSignal: OneSignalRestClient: PUT SEND JSON: {"app_id":"app_id","player_id":"player_id","opened":true,"device_type":1}
01-27 11:46:17.241 23181 23181 D OneSignal: onActivityDestroyed: com.onesignal.NotificationOpenedReceiver@
01-27 11:46:17.241 23181 23181 D OneSignal: curActivity is NOW: null
01-27 11:46:17.455 23181 24712 V OneSignal: OneSignalRestClient: After con.getResponseCode to: https://api.onesignal.com/notifications/id
01-27 11:46:17.455 23181 24712 D OneSignal: OneSignalRestClient: Successfully finished request to: https://api.onesignal.com/notifications/id
01-27 11:46:17.459 23181 24712 D OneSignal: OneSignalRestClient: PUT RECEIVED JSON: {"success":true}
01-27 11:46:22.212 23181 23713 D OneSignal: Running complete from OSNotificationOpenedResult timeout runnable!
01-27 11:46:22.213 23181 23713 D OneSignal: OSNotificationOpenedResult complete called with opened: false
01-27 11:46:22.213 23181 23713 D OneSignal: Running destroyTimeout with runnable: com.onesignal.OSNotificationOpenedResult$1@
01-27 11:46:22.213 23181 23713 D OneSignal: Running complete from OSNotificationOpenedResult timeout runnable!
01-27 11:46:22.213 23181 23713 D OneSignal: OSNotificationOpenedResult complete called with opened: false
01-27 11:46:22.214 23181 23713 D OneSignal: Running destroyTimeout with runnable: com.onesignal.OSNotificationOpenedResult$1@
```

**Comment by saurabhdtu** [comment]
Facing the same issue with flutter sdk `3.2.8` which is using android sdk `4.6.6` on miui 12
Any workaround for this at the moment, or any timeline for the fix?

**Comment by saurabhdtu** [comment]
Temporary solution for android or flutter devs
Removed the flutter dependency and using the android dependency of One Signal
Using the `OneSignal.setNotificationOpenedHandler` to start my activity with **NEW_TASK** flag from Application class

**Comment by shukerullah** [comment]
Any workaround for react native devs?

**Comment by kaanaksac** [comment]
Problem:
xiaomi notification cannot open the app due to permissions. As far as I have researched, it is necessary to allow "display pop-up window in foreground and in background" from the application settings.

Environment
react-native: 0.62.2
Device: xiaomi mi 9 lite
Package version: 4.3.7

Hi, any progress on the subject?

Note: what I don't understand is that I was getting this error from time to time in 4.1.1. But now the application is not triggered unless I give this permission in 4.3.7.

**Comment by RizqiSyahrendra** [comment]
Having same problem, any solution?

**Comment by saurabhdtu** [comment]
> Having same problem, any solution?
Follow my above solution
https://github.com/OneSignal/react-native-onesignal/issues/1309#issuecomment-1028649564

**Comment by RizqiSyahrendra** [comment]
> > Having same problem, any solution?
> > Follow my above solution
> > [#1309 (comment)](https://github.com/OneSignal/react-native-onesignal/issues/1309#issuecomment-1028649564)

I cann't do that, because I need to pass some parameter to my react screen component

**Comment by saurabhdtu** [comment]
@RizqiSyahrendra In my case I am doing this in flutter. May be this could work on your end too
``` 
    OneSignal.setNotificationOpenedHandler { result ->
       
            val intent = Intent(applicationContext, MainActivity::class.java)
            intent.flags =
                Intent.FLAG_ACTIVITY_REORDER_TO_FRONT or Intent.FLAG_ACTIVITY_CLEAR_TASK or Intent.FLAG_ACTIVITY_NEW_TASK
            intent.putExtra(IntentKeys.NOTIFICATION_CLICKED, true)
            if (result.notification.additionalData != null)
                intent.putExtra("metaData", result.notification.additionalData.toString())
            startActivity(intent)

        }

And from the MainActivity I am passing this data to Flutter via MethodChannel..

**Comment by fmdogan** [comment]
> Removed the flutter dependency and using the android dependency of One Signal

I  face this issue on a flutter project which i develop for both iOS and android. in my case, i will need both flutter and android integration of OneSignal, i think.
How did you manage to integrate the android dependency of OneSignal ? can you share a github repo, article or any kind of tutorial, please

**Comment by fmdogan** [comment]
@saurabhdtu 
> Removed the flutter dependency and using the android dependency of One Signal

I  face this issue on a flutter project which i develop for both iOS and android. in my case, i will need both flutter and android integration of OneSignal, i think.
How did you manage to integrate the android dependency of OneSignal ? can you share a github repo, article or any kind of tutorial, please

**Comment by komelabbbas** [comment]
Having same problem, any solution?

**Comment by komelabbbas** [comment]
> You are directed to the permission page with the module below. However, I could not see a control mechanism for this permission unfortunately.
> 
> ```java
> package com.package.name;
> 
> import android.content.Intent;
> import android.net.Uri;
> import android.os.Build;
> import android.os.Environment;
> import android.provider.Settings;
> import android.util.Log;
> 
> import com.facebook.react.bridge.NativeModule;
> import com.facebook.react.bridge.ReactApplicationContext;
> import com.facebook.react.bridge.ReactContext;
> import com.facebook.react.bridge.ReactContextBaseJavaModule;
> import com.facebook.react.bridge.ReactMethod;
> 
> import java.io.File;
> import java.io.FileInputStream;
> import java.io.IOException;
> import java.util.Map;
> import java.util.HashMap;
> import java.util.Properties;
> 
> public class MIUIPopupPermission extends ReactContextBaseJavaModule {
>     MIUIPopupPermission(ReactApplicationContext context) {
>         super(context);
>     }
> 
>     @Override
>     public String getName() {
>         return "MIUIPopupPermission";
>     }
> 
>     @ReactMethod
>     private void onDisplayPopupPermission() {
>         ReactApplicationContext context = getReactApplicationContext();
>         try {
>             // MIUI 8
>             Intent localIntent = new Intent("miui.intent.action.APP_PERM_EDITOR");
>             localIntent.setClassName("com.miui.securitycenter",
>                     "com.miui.permcenter.permissions.PermissionsEditorActivity");
>             localIntent.putExtra("extra_pkgname", getPackageName());
>             localIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
>             context.startActivity(localIntent);
>             return;
>         } catch (Exception ignore) {
>         }
>         try {
>             // MIUI 5/6/7
>             Intent localIntent = new Intent("miui.intent.action.APP_PERM_EDITOR");
>             localIntent.setClassName("com.miui.securitycenter",
>                     "com.miui.permcenter.permissions.AppPermissionsEditorActivity");
>             localIntent.putExtra("extra_pkgname", getPackageName());
>             localIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
>             context.startActivity(localIntent);
>             return;
>         } catch (Exception ignore) {
>         }
>         // Otherwise jump to application details
>         Intent intent = new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
>         Uri uri = Uri.fromParts("package", getPackageName(), null);
>         intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
>         intent.setData(uri);
>         context.startActivity(intent);
>     }
> 
>     private String getPackageName() {
>         return "com.package.name";
>     }
> 
> }
> ```

I am new in react native, where can I add this file..?

**Comment by jkasten2** [comment]
There is an issue for the Android-OneSignal-SDK (that this library uses under the hood) about this Xiaomi specific problem.
https://github.com/OneSignal/OneSignal-Android-SDK/issues/1494

Please follow the thread above for more details. We will keep this issue open until there is an update SDK to address this repo.

**Comment by Ansh-Rathod** [comment]
> Temporary solution for android or flutter devs Removed the flutter dependency and using the android dependency of One Signal Using the `OneSignal.setNotificationOpenedHandler` to start my activity with **NEW_TASK** flag from Application class

Please can you show example of your fix that would be great cause I'm facing this issue from long time : )

**Comment by saurabhdtu** [comment]
@Ansh-Rathod @komelabbbas 
```
class MyApp : Application() {
.
.
.
   override fun onCreate() {
        super.onCreate()
        instance = this
        OneSignal.setLogLevel(OneSignal.LOG_LEVEL.VERBOSE, OneSignal.LOG_LEVEL.NONE)

        // OneSignal Initialization
        OneSignal.initWithContext(this)
        OneSignal.setAppId(BuildConfig.ONE_SIGNAL_KEY)
        OneSignal.setNotificationOpenedHandler { result ->
            val intent = Intent(applicationContext, MainActivity::class.java)
            intent.flags =
                Intent.FLAG_ACTIVITY_REORDER_TO_FRONT or Intent.FLAG_ACTIVITY_CLEAR_TASK or Intent.FLAG_ACTIVITY_NEW_TASK
            intent.putExtra(IntentKeys.NOTIFICATION_CLICKED, true)
            if (result.notification.additionalData != null)
                intent.putExtra("metaData", result.notification.additionalData.toString())
            startActivity(intent)

        }
}
.
.

class MainActivity{
.
.
.
override fun onFlutterUiDisplayed() {
        super.onFlutterUiDisplayed()
       if (intent.hasExtra(IntentKeys.NOTIFICATION_CLICKED)) {
            if (intent.hasExtra("metaData")) {
                val metaData = intent.getStringExtra("metaData")
// Do whatever you want with the meta data in notification payload
// I am passing it down to flutter
                methodChannel.invokeMethod("notification_clicked", mapOf("metaData" to metaData))
            }
        }
}
}

//.on Flutter side 
/// implement the method channel to get the data
Constants.PLATFORM_CHANNEL.setMethodCallHandler((methodCall) async {
      switch (methodCall.method) {
        case "notification_clicked":
          {
            args = jsonDecode(methodCall.arguments['metaData'].toString());
            debugPrint("notification-metadata---> ${args.toString()}");
          }
          break;

**Comment by jpdik** [comment]
https://github.com/OneSignal/OneSignal-Android-SDK/issues/1494#issuecomment-1130816443

**Comment by kaanaksac** [comment]
is there any solution?

**Comment by Ansh-Rathod** [comment]
@kaanaksac yep i found solution

**Comment by Ansh-Rathod** [comment]
i created my own onesignal sdk from this repo, i'm gonna use it until officially onesignal sdk fixes.

**Comment by Ansh-Rathod** [comment]
just upgrade version in build.gradle file they have fixed in new android library 4.5.1

**Comment by nan-li** [comment]
Thank you for waiting, the react-native-onesignal SDK [version 4.3.10](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.3.10) has been released with this fix.

I will close this issue, but please reach out if you are experiencing any problems.

**Comment by indapublic** [comment]
Version is 5.2.8, but seems like I have [same issue](https://github.com/OneSignal/react-native-onesignal/issues/1828)
