### ISSUE TITLE
Property 'addEventListener' does not exist on type 'OneSignal'

### ISSUE THREAD

**Issue by ROG3R-DEV** [OneSignal/react-native-onesignal#1317]
**Description:**

hello I recently purchased oneSignal for testing, I was frustrated that it doesn't provide good support for typescript and hooks.
I saw some examples with hooks and listeners but it doesn't work with typescript

```typescript
 useEffect(() => {
    OneSignal.addEventListener('received', onReceived);
    OneSignal.addEventListener('opened', onOpened);
  }, []);

  const onOpened = openResult => {
    if (openResult) {
      console.log('Message: ', openResult.notification.payload.body);
      console.log('Data: ', openResult.notification.payload.additionalData);      
    }
  };

  const onReceived = notification => {
    console.log("Notification received: ", notification);
  };
```

<img src="https://i.imgur.com/CvKLhsy.png" />

the example in the official documentation does not work as it should, in addition to leaking memory
<img src="https://i.imgur.com/zf8EYtO.png" />

I can use firebase easily with react native and typescript, I don't understand why with a OneSignal it's so difficult :(

**Environment**

Latest version

**Comment by rgomezp** [comment]
Howdy,
This should be fixed in the latest release. Please upgrade and make sure you are using the latest API. `addEventListener` was deprecated in the latest major release.
