### ISSUE TITLE
Using Onesignal alongside with strict-version-matcher-plugin

### ISSUE THREAD

**Issue by adoniscoder** [OneSignal/react-native-onesignal#1323]
**Description:**

Hi, I'm trying to use OneSignal but it seems that the version of the firebase that being used by onesignal is different than the one that the `com.google.android.gms.strict-version-matcher-plugin` brings.

`

    In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[19.0.0, 
      22.0.99]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

    Dependency failing: com.onesignal:OneSignal:4.6.3 -> com.google.firebase:firebase-messaging@[19.0.0, 22.0.99], but fireb
     ase-messaging version was 22.0.0.
  
    The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
     ifact with the issue.
     -- Project 'app' depends on project 'react' which depends onto com.onesignal:OneSignal@4.6.3
     -- Project 'app' depends on project 'react' which depends onto com.onesignal:OneSignal@{strictly 4.6.3}
      -- Project 'app' depends on project 'react' which depends onto com.google.firebase:firebase-messaging@{strictly 22.0.0}
     -- Project 'app' depends on project 'intercom_intercom' which depends onto com.google.firebase:firebase-messaging@20.2.+
     -- Project 'app' depends on project 'intercom_intercom' which depends onto com.google.firebase:firebase-messaging@{stric
     tly 20.2.4}
`

**Environment**
react-native-onesignal: 4.3.3
react-native: 0.66.1

**Comment by jkasten2** [comment]
@adoniscoder Thanks for reporting. The `strict-version-matcher-plugin` seems to be miss reporting the issue. 
```
Dependency failing: com.onesignal:OneSignal:4.6.3 -> com.google.firebase:firebase-messaging@[19.0.0, 22.0.99], but fireb
 ase-messaging version was 22.0.0.
```
Version `22.0.0` is within the `[19.0.0, 22.0.99]` version range so it isn't clear why `strict-version-matcher-plugin` is reporting this as an error.

There might be an incompatibly between  `strict-version-matcher-plugin` and `onesignal-gradle-plugin`, since `onesignal-gradle-plugin` will change versions used during the build process to prevent issues.

**Comment by shelzTimesignature** [comment]
so how to we solve this

**Comment by guilhermefmt** [comment]
Any news on this issue ?

**Comment by shelzTimesignature** [comment]
Solution:
https://github.com/OneSignal/react-native-onesignal/issues/1295#issuecomment-982196516
