### ISSUE TITLE
How to push segment  "All" but exclude some playerid ?

### ISSUE THREAD

**Issue by khanhnn09** [OneSignal/react-native-onesignal#1325]
Hi All,
I want  push all segment but exclude some playerid, please guide me the solution to this problem

**Comment by jennantilla** [comment]
Hey there @khanhnn09 -- you should create another segment for those Player IDs and exclude that segment in the push. You can also target specific Player IDs with the `include_player_ids` parameter of our [Create Notification API call](https://documentation.onesignal.com/reference/create-notification#send-to-specific-devices). Thanks!
