### ISSUE TITLE
Multiple SDK initializing

### ISSUE THREAD

**Issue by antoxi4** [OneSignal/react-native-onesignal#1326]
**Description:**
When i call the requestMultiple method from PermissionAndroid.
Android was catch exception 
E/OneSignal: Already initialized the OneSignal React-Native SDK

**Environment**
react-native  0.65.1
react-native-onesignal 4.3.3

```ts
import React from 'react'
import { PermissionsAndroid } from 'react-native'

const App: React.FC = () => {

  React.useEffect(() => {
    PermissionsAndroid.requestMultiple([
      'android.permission.ACCESS_COARSE_LOCATION',
      'android.permission.ACCESS_FINE_LOCATION',
      'android.permission.ACCESS_BACKGROUND_LOCATION',
    ])
  }, [])

  return (
    <View>
    </View>
  )
}

export default App
```

<img width="1113" alt="Screenshot 2021-11-20 at 21 44 09" src="https://user-images.githubusercontent.com/11519065/142739070-1caeaa85-769c-4f79-9ce1-860823c65ff7.png">

**Comment by KrishnarajS-FSP** [comment]
How you resolve this?
