### ISSUE TITLE
Cannot pod install in M1

### ISSUE THREAD

**Issue by anditorx** [OneSignal/react-native-onesignal#1330]
I try to pod install in Apple M1, but still error like this 

`[!] CocoaPods could not find compatible versions for pod "OneSignalXCFramework":
  In snapshot (Podfile.lock):
    OneSignalXCFramework (= 3.8.1)

  In Podfile:
    react-native-onesignal (from `../node_modules/react-native-onesignal`) was resolved to 4.3.3, which depends on
      OneSignalXCFramework (= 3.9.1)

Specs satisfying the `OneSignalXCFramework (= 3.8.1), OneSignalXCFramework (= 3.9.1)` dependency were found, but they required a higher minimum deployment target.`

Any solution for this issue?

**Comment by jkasten2** [comment]
@anditorx Can you share you `Podfile` and your `Podfile.lock`?

**Comment by anditorx** [comment]
This my Podfile
<img width="810" alt="Screen Shot 2021-11-30 at 20 02 37" src="https://user-images.githubusercontent.com/23007629/144052234-b6d174e0-4b9c-4c9a-a334-d47de5f0ab43.png">

And this my Podfile.lock => https://gist.github.com/anditorx/4c3ba9dc980cda7af081bf8e9e3ee26a


@jkasten2

**Comment by akhilsanker** [comment]
@jkasten2 ,

Facing the same issue with:
"react-native-onesignal": "^4.3.3",
"react-native": "0.66.2",
iOS: 15
Xcode: 13

Thanks

**Comment by ZentPeople** [comment]
+1

**Comment by ZentPeople** [comment]
@jkasten2 Kindly share if there are any updates on this issue as we are stuck here to send notifications to ios

**Comment by omar-bear** [comment]
same it not working for me too

**Comment by jkasten2** [comment]
@anditorx Thanks for providing both files. 

`pod 'OneSignal'` is not compatible with the the iOS Simulator with macs using an Arm CPU (M1).
Please use `pod 'OneSignalXCFramework'` instead in your `Podfile`
```ruby
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end
```

If a clean build does not fix this you may need to run `pod install` from your `ios` folder.

If you next run into a different error about mixed versions of `OneSignalXCFramework` then you may need to run `pod update OneSignalXCFramework`

**Comment by omar-bear** [comment]
Works for me on mac m1 pro 2021

**Important**: Open finder > applications > right click on xcode icon > get info > check **open with rosetta**
_if you dont find this checkbox you have to install rosetta on your mac and reboot it with this command: 
`softwareupdate --install-rosetta`_

quit xcode and reboot the mac thats better

use this command instead of pod install 

## 1 Install ffi
`sudo arch -x86_64 gem install ffi`


## 2 Re-install dependencies
`arch -x86_64 pod install`

## 3 change alias to use only pod install
`alias pod='arch -x86_64 pod'`

**Comment by rusakovic** [comment]
Confirm this issue on M1 chip.
Unfortunately, changes in `podfile` don't help until you start using Rosetta. But, sure, it's not the best decision to use Rosetta only because of one extension.

Maybe the team could help to fix it.

Thank you

**Comment by jkasten2** [comment]
After the following change in your `Podfile` can you share the exact error you are seeing now?
```ruby
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end
```

Also check your `Podfile.lock` to ensure you only have `"OneSignalXCFramework"` now, make sure `"OneSignal"` is gone.

**Comment by jacksperrow126** [comment]
I found this answer https://github.com/CocoaPods/CocoaPods/issues/10684#issuecomment-851273993
Maybe you should try `arch -x86_64 pod install --repo-update` 
It works for me!

**Comment by rgomezp** [comment]
Thanks for the solution @anbrunonguyen !

Enjoy!
