### ISSUE TITLE
App is draining battery in background (PARTIAL_WAKE_LOCK)

### ISSUE THREAD

**Issue by MujtabaFR** [OneSignal/react-native-onesignal#1331]
**Description:**

I'm having an issue with **Android** devices, it gives me and all users a notification that my app **is draining battery in the background**.
After further investigation using `adb shell dumpsys power` I found the following issue

```
Wake Locks: size=3
  PARTIAL_WAKE_LOCK              '*job*/com.myapp/com.onesignal.FocusDelaySyncJobService' ACQ=-6m16s232ms LONG (uid=1000 pid=2050 ws=WorkSource{10561})
```

this partial wake lock stills active for 10 minutes, and I couldn't find the reason behind it, or how to stop it.

**Environment**

Android: 11
react-native: 0.63.4,
react-native-onesignal: 4.0.4,

**Steps to Reproduce Issue:**

1. Insure that battery saving is off and the app is not restricted when in background
2. launch the app and then minimize it to the background
3. A notification will be shown to the user after few minutes

**Comment by rgomezp** [comment]
Howdy,
We are investigating. Thanks for your patience.

**Comment by nan-li** [comment]
Hi @MujtabaFR,

The `FocusDelaySyncJobService` that is causing this warning has been changed in the latest `react-native-onesignal`  [release 4.3.6](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.3.6). You can update to this version to fix this issue.
