### ISSUE TITLE
Library not loaded: @rpath/OneSignal.framework/OneSignal, IOS black screen on app initialisation 

### ISSUE THREAD

**Issue by PaulOskarSoe** [OneSignal/react-native-onesignal#1332]
**Description:**

IOS build is returning black screen after upgrading react-native-onesignal to version **4.3.3**. 

**Environment**

``` "react-native": "^0.63.4", "react-native-onesignal": "^4.3.3"```

**Steps to Reproduce Issue:**

1. Upgrage onesignal version from 4.1.0 to 4.3.3.
2. Build IOS app

**Anything else:**

App is compiled successfully, but once apps initialisation starts loading Onesignal library, I receive a black screen. I have tried several times clearing cache, derived data, reinstalling pods and node packages but error stays the same. Also related git threads as https://github.com/OneSignal/react-native-onesignal/issues/1179 do not resolve the issue. I validated that platform development versions are the same on app and OneSignalNotificationService. I also did the whole OneSignal set up again from latest docs, but nothing changed. 

 
This is the error that I am getting from Xcode.

```dyld[14896]: Library not loaded: @rpath/OneSignal.framework/OneSignal
  Reason: tried: '/usr/lib/swift/OneSignal.framework/OneSignal' (no such file), '/usr/lib/swift/OneSignal.framework/OneSignal' (no such file), '/usr/lib/swift/OneSignal.framework/OneSignal' (no such file), '/usr/lib/swift/OneSignal.framework/OneSignal' (no such file), '/usr/lib/swift/OneSignal.framework/OneSignal' (no such file), '/usr/lib/swift/OneSignal.framework/OneSignal' (no such file), '/System/Library/Frameworks/OneSignal.framework/OneSignal' (no such file)
Library not loaded: @rpath/OneSignal.framework/OneSignal
  Reason: tried: '/usr/lib/swift/OneSignal.framework/OneSignal' (no such file), '/usr/lib/swift/OneSignal.framework/OneSignal' (no such file), '/usr/lib/swift/OneSignal.framework/OneSignal' (no such file), '/usr/lib/swift/OneSignal.framework/OneSignal' (no such file), '/usr/lib/swift/OneSignal.framework/OneSignal' (no such file), '/usr/lib/swift/OneSignal.framework/OneSignal' (no such file), '/System/Library/Frameworks/OneSignal.framework/OneSignal' (no such file)
(lldb) ```

**Comment by PaulOskarSoe** [comment]
Might be related with this issue: https://github.com/OneSignal/react-native-onesignal/issues/1293

**Comment by PaulOskarSoe** [comment]
I validated that this issue is not version related, created a new react-native app with version 0.63.4 and installed latest version of OneSignal, and everything was working fine. I had issue with Frameworks initialisation, so I will close this issue since it's not SDK related

**Comment by gokugen** [comment]
What was the problem ? I'm getting the same error.
