### ISSUE TITLE
bitcode build failed

### ISSUE THREAD

**Issue by disko998** [OneSignal/react-native-onesignal#1337]
**Description:**

Release and Debug variants are working but when distributing app bitcode build failed, if I disable bitcode then it works. Does anyone have any idea what could be the issue?

**Environment**

1. What version of the OneSignal React-Native SDK are you using? 4.3.3
2. How did you add the SDK to your project? NPM
3. React Native version? 0.66.1
4. Xcode version? 12.3

**Steps to Reproduce Issue:**

  1. Install and setup the OneSignal SDK using npm into your project
  2. Run archive on ios
  3. Distribute the app with bitcode enabled

**Anything else:**

<img width="740" alt="Screenshot 2021-12-23 at 17 24 31" src="https://user-images.githubusercontent.com/45342884/147268619-8f005b16-2e96-4832-bfa5-19f93df90af7.png">

**Comment by rgomezp** [comment]
Howdy,
See [this similar issue](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/659).

1. Is it imperative that you leave Bitcode on?
2. Could you please include your Podfile?

**Comment by disko998** [comment]
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/@nrwl/react-native/nx_post_install'

platform :ios, '11.0'

target 'Mobile' do
  config = use_native_modules!
  
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    nx_post_install(installer)
  end
end

target 'OneSignalNotificationServiceExtension' do
	pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end
```

@rgomezp

**Comment by disko998** [comment]
Works fine on Xcode 13!
