### ISSUE TITLE
IOS push notification not showing in real devices

### ISSUE THREAD

**Issue by jeet-mehta** [OneSignal/react-native-onesignal#1339]
**Description:**
I am getting the push notifications in android devices but unable to receive push notifications in IOS devices. In the one-signal dashboard I am able to see the notification is delivered successfully but unable to see in the IOS notification center. I have also checked the certificates required for the same.

(your description here)

**Environment**
"react-native-onesignal": "^4.3.1",
2. How did you add the SDK to your project (eg. npm)
 --> yarn 

 Here I am also sharing the code snippet for sending the notification. 

`const notificationObj = {
	contents: {
		'en': 'jack is hjererere'
	},
	//here considering my other device id for understanding purpose
	include_player_ids: ['c2688640-67e0-11ec-b3c7-e294da84a8ca'],
	android_channel_id: 'channel_id',
	headings: {
		'en': 'heading'
	},
	data: {
		navigationPath: 'navOptions'
	},
	content_available: true,
	mutable_content: true,
	priority: 10,
	subtitle: {
		'en': 'subtile'
	}
}

const jsonString = JSON.stringify(notificationObj)

OneSignal.postNotification(jsonString, (success) => {
	if (__DEV__) console.log('notification sent successfully', success)
}, (err) => {
	if (__DEV__) console.log('notification failed to sent', err);
})`

**Comment by Antonyodu** [comment]
The issue is "android_channel_id" 
It's bug with onesignal
