### ISSUE TITLE
getting delay in receiving push notification

### ISSUE THREAD

**Issue by laxman2694** [OneSignal/react-native-onesignal#1342]
**Description:**

(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by emawby** [comment]
@laxman2694 Thank you for reaching out. Please reopen once you have provided more information on what you are seeing and how to reproduce the issue
