### ISSUE TITLE
Could not load RNOneSignal native module. Make sure native dependencies are properly linked.

### ISSUE THREAD

**Issue by 4quarenta** [OneSignal/react-native-onesignal#1345]
Hi there,

when I try to `OneSignal.setAppId('APP_ID')`,  I get this error:

```
Could not load RNOneSignal native module. Make sure native dependencies are properly linked.
at node_modules\expo\build\logs\LogSerialization.js:156:14 in _captureConsoleStackTrace
at node_modules\expo\build\logs\LogSerialization.js:41:26 in serializeLogDataAsync
- ... 9 more stack frames from framework internals
```

**Comment by rgomezp** [comment]
Howdy,
Are you using Expo?

See the [RN troubleshooting guide](https://documentation.onesignal.com/docs/troubleshooting-react-native#check-link-step-worked-correctly).

**Comment by 4quarenta** [comment]
> RNOneSignal

I didn't find anything about this error, I even followed all the steps and I keep getting the same error

![image](https://user-images.githubusercontent.com/70922568/149605891-9f7600bf-0070-4051-a2c4-6b36724c4cae.png)

**Comment by rpaggi** [comment]
Same error here
![image](https://user-images.githubusercontent.com/1770406/149819569-6e6d7f64-3e91-4150-8ff6-a660aa81faac.png)

**Comment by rgomezp** [comment]
Please follow the issue template so I can help you better.

Are you using Expo?

**Comment by 4quarenta** [comment]
> Please follow the issue template so I can help you better.
> 
> Are you using Expo?

Yes

**Comment by rgomezp** [comment]
That's the problem. If you want to use Expo you need to use the OneSignal Expo Plugin or eject into the bare workflow.

See [this discussion thread](https://github.com/OneSignal/onesignal-expo-plugin/discussions/45) for more info.

Cheers

**Comment by Adlai-1** [comment]
Still doesn't work...

**Comment by brunolcarlos** [comment]
Same error



```
"dependencies": {
    "expo": "~44.0.0",
    "expo-device": "~4.1.0",
    "expo-file-system": "~13.1.4",
    "expo-media-library": "~14.0.0",
    "expo-splash-screen": "~0.14.1",
    "expo-status-bar": "~1.2.0",
    "expo-system-ui": "~1.1.0",
    "expo-web-browser": "~10.1.0",
    "onesignal-expo-plugin": "^1.0.2",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-device-info": "^9.0.2",
    "react-native-navigation-bar-color": "^2.0.1",
    "react-native-onesignal": "^4.3.11",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-web": "0.17.7",
    "react-native-webview": "11.15.0"
  },
```

Could not load RNOneSignal native module. Make sure native dependencies are properly linked.
at node_modules/react-native-onesignal/dist/helpers.js:15:8 in isNativeModuleLoaded
at node_modules/react-native-onesignal/dist/index.js:286:29 in __generator$argument_1
at node_modules/react-native-onesignal/dist/index.js:33:17 in step
at node_modules/react-native-onesignal/dist/index.js:8:13 in <anonymous>
at node_modules/react-native-onesignal/dist/index.js:4:11 in <anonymous>
at src/pages/Home/index.js:33:8 in useEffect$argument_0
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:58:4 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:117:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:202:4 in runApplication

**Comment by Lucashb** [comment]
Someone fix this ?

**Comment by 4quarenta** [comment]
> Someone fix this ?

I managed to solve using the specific plugin for expo:

[https://github.com/OneSignal/onesignal-expo-plugin](url)

**Comment by alicanso** [comment]
even your example project is same. need fix

**Comment by gpolanco** [comment]
Has anyone found a solution to the problem?

**Comment by mohammad6vakili** [comment]
Someone fix this ?

**Comment by badinenisaivardhan** [comment]
Just Include this code In andriod/settings.gradle 
`include ':react-native-onesignal'` 
`project(':react-native-onesignal').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-onesignal/android')  `

clean npm and gradlew 
npx react-native clean 
npm install --save
npx react-native run-android

**Comment by gpolanco** [comment]
> Just Include this code In andriod/settings.gradle `include ':react-native-onesignal'` `project(':react-native-onesignal').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-onesignal/android') `
> 
> clean npm and gradlew npx react-native clean npm install --save npx react-native run-android

I have seen that solution, but I have to eject project and I don't want

**Comment by badinenisaivardhan** [comment]
> > Just Include this code In andriod/settings.gradle `include ':react-native-onesignal'` `project(':react-native-onesignal').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-onesignal/android') `
> > clean npm and gradlew npx react-native clean npm install --save npx react-native run-android
> 
> I have seen that solution, but I have to eject project and I don't want

if you are using RN above code will work... because i am moving my code from expo to RN, today and it is working fine...!
if u are using EXPO: onesignal-expo-plugin (https://github.com/OneSignal/onesignal-expo-plugin) use this..

**Comment by HamzaKV** [comment]
Seems like latest version(1.2.0) of `onesignal-expo-plugin` does not seem to work with latest version(4.4.1) of `react-native-onesignal` as I get the same error.

**Comment by davidcort** [comment]
> Just Include this code In andriod/settings.gradle `include ':react-native-onesignal'` `project(':react-native-onesignal').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-onesignal/android') `
> 
> clean npm and gradlew npx react-native clean npm install --save npx react-native run-android

Thanks, this works.
I started my project with expo, after I run expo run:android. 
Install one signal, this problem occurs after that.
I add the code in the settings gradle.
clean yarn and gradle.
run npx expo run android
Sucess !!

**Comment by mohammad6vakili** [comment]
> Seems like latest version(1.2.0) of `onesignal-expo-plugin` does not seem to work with latest version(4.4.1) of `react-native-onesignal` as I get the same error.

So what should we do now?

**Comment by mohammad6vakili** [comment]
I don't want to eject my app. what should I do? OneSignal Expo Plugin doesn't work !!!

**Comment by HamzaKV** [comment]
I used `react-native-onesignal` version 4.3.3 with version 1.2.0 of `onesignal-expo-plugin`. It did give me build errors on Android, but I resolved it using `expo prebuild`.

> > Seems like latest version(1.2.0) of `onesignal-expo-plugin` does not seem to work with latest version(4.4.1) of `react-native-onesignal` as I get the same error.
> 
> So what should we do now?

**Comment by MehmoodAlam632** [comment]
> Please follow the issue template so I can help you better.
> 
> Are you using Expo?

Yes

**Comment by trinityblade** [comment]
I had the same error show up when launching the app on Expo Go. After chatting to OneSignal support, this is their response below (long story, short: this error will only show up when launching the app on Expo Go. The final build tested on your native device will work just fine)
"Are you building this app through Expo Go? if so, you will not be able to run on Expo Go since it doesn't come with the native dependencies required by OneSignal. You can think of the config plugin as adding some custom native code to your application. To get those native changes into your build, Expo needs to bundle it into a custom client that includes those changes. Think of it as building your own Expo Go app to run the application. Since the Go app is prebuilt, it will not include any native customizations. That is why this does not work."

**Comment by Madhusankamsk** [comment]
Did you fix the issue for Expo

**Comment by nusendra** [comment]
I managed to make it work in Expo. Just follow this steps

https://documentation.onesignal.com/docs/react-native-expo-sdk-setup

The most important part is you guys need to run `npx expo prebuild`. Then run the app with emulator `npx expo run:android`. Unfortunately, this is not working with real device (`yarn start`)

**Comment by 3moz** [comment]
> I managed to make it work in Expo. Just follow this steps
> 
> https://documentation.onesignal.com/docs/react-native-expo-sdk-setup
> 
> The most important part is you guys need to run npx expo prebuild. Then run the app with emulator npx expo run:android. Unfortunately, this is not working with real device (yarn start)

This worked for me.

In other words:
`npx create-expo-app app_name [any flags]`
<follow .../react-native-expo-sdk-setup>
`npx expo run:android`

I don't think i ran `npx expo prebuild` but that doesn't appear to have blocked except my `run:android` might've taken longer to build.
