### ISSUE TITLE
Is it possible to get current player id for 4 version SDK?

### ISSUE THREAD

**Issue by indapublic** [OneSignal/react-native-onesignal#1354]
Seems like `OneSignal.addEventListener('ids', this.onIds)` was before but cannot find which event should be used in 4th version

**Comment by pierroo** [comment]
They removed it in latest versions, you should now be using:

```
const deviceState = await OneSignal.getDeviceState()
const { userId } = deviceState
```

userId being the playerId you are looking for

**Comment by nan-li** [comment]
Thanks @pierroo for providing this information, [here](https://documentation.onesignal.com/docs/sdk-reference#getdevicestate-method) is the documentation on `getDeviceState` for reference.

I will close this issue then.
