### ISSUE TITLE
badge count is wiped after clear the notification

### ISSUE THREAD

**Issue by prakash-thinroot** [OneSignal/react-native-onesignal#1355]

**Comment by prakash-thinroot** [comment]
I am using onesignal for push notification , I wants to display the badge count and it is displaying once the user received the push notification . But the count is cleared when the user cleared the notifications from notification bar .

Is there any way to hold the count until the user opens the particular notification inside the app ?

**Comment by prakash-thinroot** [comment]
I am using onesignal for push notification , I wants to display the badge count and it is displaying once the user received the push notification . But the count is cleared when the user cleared the notifications from notification bar .

Is there any way to hold the count until the user opens the particular notification inside the app ?

**Comment by jfishman1** [comment]
This is the default behavior for badges and is controlled by the Operating System. There is not a way to force badges to stay on the app after notifications are cleared.

For more details on Badges, please see our docs on Badges here: https://documentation.onesignal.com/docs/badges

If you have any other questions related to features and "how things work", feel free to contact our support team at support@onesignal.com
