### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_RCTInspectorDevServerHelper

### ISSUE THREAD

**Issue by allemanfredi** [OneSignal/react-native-onesignal#1359]
**Description:**

Hello everyone, After having followed your [documentation](https://documentation.onesignal.com/docs/react-native-sdk-setup) and after having set `config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'` within the `Podfile`, i started to receive the following errors during the build.

```
Undefined symbol: vtable for facebook::react::HermesExecutorFactory
Undefined symbol: _OBJC_CLASS_$_RCTInspectorDevServerHelper
```

If i don't set `config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'`, i receive this error:

```
 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
 ```

**Environment**

* react-native-onesignal: 4.3.2
* react-native: 0.66.3

**Comment by mdeliadi** [comment]
Hi everyone!

I have the same issue since this morning; the awful part of my story is that my codebase built without errors until yesterday evening, but today not anymore.

I've tried to use a notification service extension written in both Objective-C and Swift, re-installed cocoapods, removed its cache, changed its version, re-installed the pods an enormous amount of times, set APPLICATION_EXTENSION_API_ONLY to NO first for all the pods, and then for React-Core and RNPermissions pods only, added missing dependencies when able but in the end I'm still stuck with the same errors above.

Please help, I would like to have this working and I'm tired of reading "please reinstall your pods, you will be fine" :(

**Comment by jkasten2** [comment]
@mdeliadi @allemanfredi Thanks for the details! Looking to narrow down this issue, to specific react-native versions and settings.

@mdeliadi You noted you did not have the issue originally with OneSignal, but then broke the next day. Did you upgrade your version of react-native or anything else?

@mdeliadi @allemanfredi Could you share your `Podfile` as well?

This issue looks like it could be related #1360.

**Comment by mdeliadi** [comment]
Hi @jkasten2 !

React Native version should be 0.66.3, the next day I've not updated anything, I've just removed my `Pods` and `node_modules` folders, `Podfile.lock`, `package-lock.json`, run `npm i` and after `pod install`!

Podfile:
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)

      if text != replace
          puts "Fix: " + name
          system("chmod +w " + name)
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end

def react_native_post_install(installer)
  installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
		  # Set 9.0 as min version for all
		  if Gem::Version.new('11.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
			  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
		  end
		end
	end
end

permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
pod 'MultiplatformBleAdapter', :git => 'https://github.com/below/MultiPlatformBleAdapter', :tag => '0.1.9'

target 'MyApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )



  target 'MyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  use_flipper!({ 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3' , 'Flipper' => '0.88.0' })

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end
```

Thanks for your help! Any suggestion will be very appreciated!

**Comment by mdeliadi** [comment]
Hi @jkasten2 ! Any news, please? I'm still blocked on this issue! Thanks.

**Comment by jkasten2** [comment]
@mdeliadi @allemanfredi Can you try moving `OneSignalNotificationServiceExtension` inside your main target?
Example:
Change this:
```Ruby
target 'MyApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )



  target 'MyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  use_flipper!({ 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3' , 'Flipper' => '0.88.0' })

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end
```

To this:
```Ruby
target 'MyApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )



  target 'MyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  use_flipper!({ 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3' , 'Flipper' => '0.88.0' })

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

  target 'OneSignalNotificationServiceExtension' do
    pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
  end
end
```

This worked for another developer (noted in https://github.com/OneSignal/react-native-onesignal/issues/1360#issuecomment-1055983842) but not sure exactly why it is required in this scenario when `hermes_enabled` is set to `true`.

**Comment by mdeliadi** [comment]
@jkasten2 Hi! Thanks for your suggestion, unfortunately it's still not working. Any other suggestion, please?

Something that maybe it is interesting to point out, depending on where you put the `OneSignalNotificationServiceExtension`, inside or outside the main target, the build process raises two (inside) or one (outside) errors, always `'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.`.

**Comment by jkasten2** [comment]
@mdeliadi For the "'sharedApplication' is unavailable" issue see the following:
* https://stackoverflow.com/a/56789751
* https://github.com/OneSignal/OneSignal-iOS-SDK/issues/965

**Comment by allemanfredi** [comment]
i tried to add the code below but it does not work.

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
    end
  end
end
```

I get 2 errors:

```
Undefined symbol: vtable for facebook::react::HermesExecutorFactory
Undefined symbol: _OBJC_CLASS_$_RCTInspectorDevServerHelper
```

**Comment by yoannes** [comment]
https://github.com/OneSignal/react-native-onesignal/issues/1359#issuecomment-1055985717

After moving `OneSignalNotificationServiceExtension` inside target I got the `'sharedApplication' is unavailable` error and what worked for me was to set the `Require Only App-Extension-Safe API` to `No`

![image](https://user-images.githubusercontent.com/11369576/173856188-d1228256-66d8-44e0-b98f-42bff3da68aa.png)

**Comment by jpangan** [comment]
Which solution worked? I have been in this situation for 2 days now. I tried multiple approaches but still didn't get it. The last approach I tried is this https://github.com/OneSignal/react-native-onesignal/issues/1360#issuecomment-1044787027 but still didn't work for me.

**Comment by adapptor-kurt** [comment]
For anyone who comes across this issue, the reason for the linking issue here is that the pods declared at the top level are being inherited by all targets. Move all React Native pod definitions (and any other calls that add pods, like use_flipper!) into the app's target so that the OneSignal target won't try to link those RN dependencies.

**Comment by jennantilla** [comment]
Hello everyone! Since it has been quite some time since this issue has seen activity, I'm going to close it as stale. Please @ mention me if anyone is still experiencing this on the latest Player Model (4.5.2) or User Model (5.0.5) releases and we'll be happy to give it some fresh eyes. Thanks!

**Comment by Faisalnawaz953** [comment]
Placing 
 ```
$NotifeeExtension = true
  target 'NotifeeNotificationService' do
    pod 'RNNotifeeCore', :path => '../node_modules/@notifee/react-native/RNNotifeeCore.podspec'
  end
```
before post_install work for me



```

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '14.0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
pod 'Firebase', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseCrashlytics', :modular_headers => true
pod 'FirebaseInstallations', :modular_headers => true
pod 'GoogleDataTransport', :modular_headers => true
pod 'nanopb', :modular_headers => true
pod 'FirebaseCoreExtension',:modular_headers=>true


target 'MyApp' do
  permissions_path = '../node_modules/react-native-permissions/ios'
  
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways/Permission-LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec"

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MyAppTest' do
    inherit! :complete
  end

  pre_install do |installer|
    installer.analysis_result.specifications.each do |spec|
      if spec.name == 'React-Core' || spec.name.start_with?('RCT-Folly')
        spec.resource_bundles = {}  # Prevents privacy-related bundles from being created
      end
    end
  end
  $NotifeeExtension = true
  target 'NotifeeNotificationService' do
    pod 'RNNotifeeCore', :path => '../node_modules/@notifee/react-native/RNNotifeeCore.podspec'
  end
  post_install do |installer|
    # This removes all privacy-related bundle conflicts in React-Core and RCT-Folly
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
       end
    end

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
 
end


```
