### ISSUE TITLE
onNotificationOpened doesn't get fired on Android

### ISSUE THREAD

**Issue by arhmnsh** [OneSignal/react-native-onesignal#136]
URGENT ISSUE

Guys please help,
When Android app is in background and receives notification, `this.setState` to update state inside `onNotificationOpened` doesn't get fired. Even an alert doesn't work. 
But it works fine when the app is in foreground.
What I observed is the functions inside `onNotificationOpened` are getting fired before the app initializes, as seen from the Android Studio logs:

`I/ReactNativeJS: 'ON NOTIFICATION OPENED'`
`W/unknown:React: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.`
`I/ReactNativeJS: Running application "MarcomJo" with appParams: {"initialProps":{},"rootTag":51}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF`
`I/ReactNativeJS: 'UserId = ', 'a0e6cbe6-7289-44e7-8910-f7989493ed10'`
`I/ReactNativeJS: 'PushToken = ', 'APA91bFcyedYRnVvIdgKPOaMFAhAaQXtKHPwUOK-VWX3gxlnubeVK4WiYxpjqlmZMhm1LiNH3MuIWRfkOmhjOeHCs-AmLWGD25S2FFMiLONdO258vatOYOqp_HQfpIZgMWw5b3r6ZHNS'`

As you can see from the log above, `ON NOTIFICATION OPENED` is getting logged before the app is initialized (foregrounded by tapping on the notification); but I am logging `ON NOTIFICATION OPENED` inside `onNotificationOpened` as shown below.

Sometimes I also get `calling js function after bridge has been destroyed` when I try to call setState. Similar to this [issue](https://github.com/oney/react-native-gcm-android/issues/12).

Any help would be very much appreciated, as I am using this in a current production app. 

```ComponentDidMount() {
    OneSignal.configure({
      onIdsAvailable: (device) => {
        console.log('UserId = ', device.userId);
        console.log('PushToken = ', device.pushToken);
      },
      onNotificationOpened: (message, data, isActive) => {
          var notification = {message: message, data: data, isActive: isActive};
            console.log('ON NOTIFICATION OPENED);
            this.setState({
              textViewVisibility: true  ,
            });
      }
    });
    OneSignal.enableInAppAlertNotification(false);
  }```

**Comment by arhmnsh** [comment]
I have created a new project, but still getting the same issue.
I have uploaded the project which just contains OneSignal for Android configured: https://github.com/arhmnsh/MarcomJo/tree/master

Error I am getting in the above project:
<img width="1425" alt="screen shot 2017-01-11 at 7 29 56 am" src="https://cloud.githubusercontent.com/assets/1363724/21835732/68b4737a-d7d0-11e6-805b-734f09d36ef4.png">

**Comment by avishayil** [comment]
Please try version 2, which uses updated SDK and let me know if the problem persists.

**Comment by arhmnsh** [comment]
Thanks for the reply @avishayil 
But I don't see v2 in releases.

**Comment by avishayil** [comment]
Just published to NPM.

**Comment by DibPuelma** [comment]
The problem persists. I have followed de guide to install one signal for android, copied this:

```
import OneSignal from 'react-native-onesignal'; // Import package from node modules

OneSignal.configure({
  onIdsAvailable: function(device) {
    console.log('UserId = ', device.userId);
    console.log('PushToken = ', device.pushToken);
  },
  onNotificationReceived: function(notification) {
    console.log("notification received: ", notification);
  },
  onNotificationOpened: function(openResult) {
    console.log("ABIERTAAAAAAAAAA");
    console.log('MESSAGE: ', openResult.notification.payload.body);
    console.log('DATA: ', openResult.notification.payload.additionalData);
    console.log('ISACTIVE: ', openResult.notification.isAppInFocus);
    console.log('openResult: ', openResult);
    // Do whatever you want with the objects here
    // _navigator.to('main.post', data.title, { // If applicable
    //  article: {
    //    title: openResult.notification.payload.body,
    //    link: openResult.notification.payload.launchURL,
    //    action: data.openResult.notification.action.actionSelected
    //  }
    // });
  }
});

```
And only the onNotificationReceived is called. I still don´t get the logs to print after I click on the notification and open de app

**Comment by arhmnsh** [comment]
Any updates on this guys?

**Comment by stefanoTron** [comment]
did anyone make it work? thanks

EDIT:
My bad, forgot to set the ```sender id``` in ```android/build/app/build.gradle```

**Comment by avishayil** [comment]
I'll try to test your repo and will let you know.

**Comment by arhmnsh** [comment]
I tried v3, and it seemed to work fine.
But since most of the other plug-ins don't support rn0.40, it'll be
difficult to use it for now.

**Comment by arhmnsh** [comment]
@littletower did it work for you?
Which version are you using?

**Comment by avishayil** [comment]
@arhmnsh I just duplicated your repo on RN 0.39 and `react-native-onesignal` v1.2.3 and it `onNotificationOpened` works just fine.

Please let me know if you have more issues?

**Comment by stefano-DM** [comment]
@arhmnsh yes it works, I'm using v3 with RN 0.40.
make sure you are using the right ```OneSignal id``` and ```Google Sender id```. And make sure your device is connected to the internet, cost me 10min :)
I had some issues with ios at first though, needed to ```pod update OneSignal```

**Comment by stefanoTron** [comment]
@arhmnsh yes it works, I'm using v3 with RN 0.40.
make sure you are using the right ```OneSignal id``` and ```Google Sender id```. And make sure your device is connected to the internet, cost me 10min 😄
I had some issues with ios at first though, needed to ```pod update OneSignal```

**Comment by arhmnsh** [comment]
@avishayil onNotificationOpened works fine, but when you try to setState in there, it doesn't work.

**Comment by arhmnsh** [comment]
@littletower Yes, it v3 works fine. But the previous versions have this issue. 😲
