### ISSUE TITLE
Undefined symbol: vtable for facebook::react::HermesExecutorFactory with Hermes enable in iOS

### ISSUE THREAD

**Issue by invyctus92** [OneSignal/react-native-onesignal#1360]
**Description:**

I have enabled Hermes on iOS with react native 0.67.2.After performing the pod install, I get the following error:
If I remove OneSignalNotificationServiceExtension, the app compiles and works.

Undefined symbol: vtable for facebook::react::HermesExecutorFactory in OneSignalNotificationServiceExtension

ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/angelone/Library/Developer/Xcode/DerivedData/muv-bdflnusdodpqrrafdzngcjxfbsou/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignal.framework/OneSignal
Undefined symbols for architecture x86_64:
  "vtable for facebook::react::HermesExecutorFactory", referenced from:
      facebook::react::HermesExecutorFactory::HermesExecutorFactory(std::__1::function<void (facebook::jsi::Runtime&)>, std::__1::function<void (std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>)> const&, hermes::vm::RuntimeConfig) in libReact-Core.common.a(RCTCxxBridge.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Environment**

"react-native-onesignal": "4.3.6"

Podfile 

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
# pod 'WCPhotoManipulator', :git => 'https://github.com/guhungry/ios-photo-manipulator.git', :tag => 'v1.0.0'


$RNFirebaseAnalyticsWithoutAdIdSupport=true



pod 'react-native-image-manipulator', :path => '../node_modules/react-native-image-manipulator/ios/react-native-image-manipulator.podspec'

platform :ios, '11.0'

target 'muv' do
  config = use_native_modules!

  use_react_native!(
    	    :path => config[:reactNativePath],
    	    # to enable hermes on iOS, change `false` to `true` and then install pods
   	    :hermes_enabled => true
    	  )

  target 'muvTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

  # fix Flipper perche non compila . FlipperRSocketResponder.o

  #use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })

  # you should disable the next line.
  # use_flipper!()

   post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|

      # if target.name == 'React-Core.common-CoreModulesHeaders-AccessibilityResources'
      #   target.remove_from_project
      # end

      # if target.name == "React-Core.common-AccessibilityResources"
      #   target.remove_from_project
      # end

      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end

  end

end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end
```

**Steps to Reproduce Issue:**

1.  :hermes_enabled => true in Podfile
2. pod install
3. react-native run-ins

**Comment by jkasten2** [comment]
@invyctus92 The issue is that Hermes is being added to the `OneSignalNotificationServiceExtension` target when it should not be, as this target is native code only, no react libraries should be added to it. I am not sure exactly how it is being added but I was able to track down what the `hermes_enabled` flag does from the react native end:
https://github.com/facebook/react-native/blob/bcd2d0f1a930644e2f58c1d2f77b269f236f267a/scripts/react_native_pods.rb#L110-L114
It seems to just add 3 pods, this should be fine since the call to `use_react_native!` is on your main target it shouldn't be affecting the `OneSignalNotificationServiceExtension` target.

I am not sure what the fix is yet, but hopeful this provides some helpful details.

**Comment by invyctus92** [comment]
I solved it, I changed the podfile and associated the OneSignalNotificationServiceExtension only to the muv target and it doesn't have the whole project

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
# pod 'WCPhotoManipulator', :git => 'https://github.com/guhungry/ios-photo-manipulator.git', :tag => 'v1.0.0'

$RNFirebaseAnalyticsWithoutAdIdSupport=true

pod 'react-native-image-manipulator', :path => '../node_modules/react-native-image-manipulator/ios/react-native-image-manipulator.podspec'

platform :ios, '11.0'

target 'muv' do
  config = use_native_modules!

  use_react_native!(
    	    :path => config[:reactNativePath],
    	    # to enable hermes on iOS, change `false` to `true` and then install pods
   	    :hermes_enabled => true
    	  )

# add this here
      target 'OneSignalNotificationServiceExtension' do
        pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
      end

  target 'muvTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

  # fix Flipper perche non compila . FlipperRSocketResponder.o

  #use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })

  # you should disable the next line.
  # use_flipper!()

   post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|

      # if target.name == 'React-Core.common-CoreModulesHeaders-AccessibilityResources'
      #   target.remove_from_project
      # end

      # if target.name == "React-Core.common-AccessibilityResources"
      #   target.remove_from_project
      # end

      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end

  end

end


```

**Comment by jkasten2** [comment]
@invyctus92 Thanks for reporting back! Interesting that adding `OneSignalNotificationServiceExtension` under your main target fixes the issue for you. It shouldn't be required but I don't think it should create any other issues either.

**Comment by adapptor-kurt** [comment]
For anyone who comes across this issue, the reason for the linking issue here is that the `pod`s declared at the top level are being inherited by all targets.  Move all React Native `pod` definitions (and any other calls that add pods, like `use_flipper!`) into the app's `target` so that the OneSignal target won't try to link those RN dependencies.
