### ISSUE TITLE
Native module cannot be null  (IOS)

### ISSUE THREAD

**Issue by AchrafBn** [OneSignal/react-native-onesignal#1363]
**Description:**

Hello,i followed all steps that are mentioned in doc OneSignal React Native SDK, i'm using  Expo Managed Workflow,i'm getting  this error message "Native module cannot be null" only when i initial  OneSignal
 Any suggestions  ? thanks

**Environment**

- i'm using latest version of OneSignal React-Native SDK 
- I installed the SDK using Yarn and version of expo  is  44.0.0

*App.js *

```
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from "react-native";
import OneSignal from "react-native-onesignal";

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}
```
 Here is my package.json

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~44.0.0",
    "expo-status-bar": "~1.2.0",
    "onesignal-expo-plugin": "^1.0.0-beta11",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-onesignal": "^4.3.7",
    "react-native-web": "0.17.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}

```

**Screenshot**

![Image d’iOS (1)](https://user-images.githubusercontent.com/11798130/155752190-215dfbbd-725a-4fbf-8204-f7afa3c683aa.png) ![Image d’iOS](https://user-images.githubusercontent.com/11798130/155752202-21e2a701-77b5-46b9-b934-a874d9bf1f60.png)

**Comment by rgomezp** [comment]
Are you running this on the Expo Go app? If so, this won't work. See our README for supported environment info.

**Comment by tony-schumacher** [comment]
@rgomezp
What is the recommended way of not loading the node module when still having to work in Expo Go?
This works but the problem is not having typescript support:

```Javascript
if(isNotExpoGo){
   const OneSignal = require('react-native-onesignal').default;
}
 ```
 
 Thank you!
