### ISSUE TITLE
Android foreground notification only goes into system tray and not presented

### ISSUE THREAD

**Issue by MorganTrudeau** [OneSignal/react-native-onesignal#1367]
**Description:**

I am trying to show a notification in the foreground of my Android app. This is working in iOS but in Android the notification just goes into the system drawer but doesn't get shown to the user. I looked around the internet for a common issue, but I can't find anything. 

My question is should I expect the notification to show while I am inside the app or is it the expected behaviour for the notification to just go into the system drawer when the app is open.

If it is expected to just go into the drawer then is there some recommendation for actually display the notification banner when the app is open? Should I be extending the notification service to do this?

**Environment**

I am on `react-native-onsignal version 4.3.7`
I added to my project with `npm install`

**Steps to Reproduce Issue:**

1. Set up SDK
2. Implement `OneSignal.setNotificationWillShowInForegroundHandler` and call `complete` callback with notification.
3. Send push notification from dashboard.

Expected:
Notification banner shows in Android app when app is open.

Actual Result:
Sound is heard and notification is stored in system tray but is not seen.

**Comment by nan-li** [comment]
Hi @MorganTrudeau,

I believe what you are looking for are heads-up notifications, and on Android 8.0+, they require Android Categories / Channels to be setup and used on every notification. 

See OneSignal's documentation below and setup them up and using them here:
https://documentation.onesignal.com/docs/android-notification-categories

Hope this solves your question, please reach out if you are still having trouble.
