### ISSUE TITLE
Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS

### ISSUE THREAD

**Issue by A-Kasaaian** [OneSignal/react-native-onesignal#1368]
**Description:**

My project is React-native cli + Expo bare workflow. I get notification and it works well. the problem is action buttons. App crashes when user tap on one of the action buttons. It happens in Android. I have the logcat from onesignal and it shows nothing but there is an exception error

**Environment**

React-Native SDK version 4.3.7.
I used `yarn add react-native-onesignal`. I also tried `expo install react-native-onesignal`

these expo packages are installed:
```
    "expo": ">=44.0.0-0 <45.0.0",
    "expo-linking": "~3.0.0",
    "expo-secure-store": "^11.1.1",
    "expo-web-browser": "~10.1.0",
```

**Anything else:**
```

03-07 12:41:00.599 22155 22155 E AndroidRuntime: FATAL EXCEPTION: main
03-07 12:41:00.599 22155 22155 E AndroidRuntime: Process: [packageName], PID: 22155
03-07 12:41:00.599 22155 22155 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{[packageName]/com.onesignal.NotificationOpenedReceiver}: java.lang.SecurityException: Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from [packageName] (pid=22155, uid=10538) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.
```

**Comment by jkasten2** [comment]
@A-Kasaaian Thanks for reporting!

## Issue
I did some digging and found that `Intent.ACTION_CLOSE_SYSTEM_DIALOGS` is being used by the OneSignal-Android-SDK (latest - [4.7.0](https://github.com/OneSignal/OneSignal-Android-SDK/blob/4.7.0/OneSignalSDK%2Fonesignal%2Fsrc%2Fmain%2Fjava%2Fcom%2Fonesignal%2FNotificationOpenedProcessor.java#L77) at the time of writing).

As of Android 12 (API Level 31) this requires a permission:
https://developer.android.com/reference/android/content/Intent#ACTION_CLOSE_SYSTEM_DIALOGS

## Workaround
Set your project's `targetSdkVersion` to `30`, doing so puts your app into a backwards compatibility mode (targeted as Android 11) when running on Android 12 devices and will most likely bypass this issue for now. This will be allowed by Google Play for a while until they start requiring 31.

## Related
I have created an issue on the OneSignal-Android-SDK repo to address fixing the root issue there.
* https://github.com/OneSignal/OneSignal-Android-SDK/issues/1543

## Solution
Once https://github.com/OneSignal/OneSignal-Android-SDK/issues/1543 is resolved and is released a follow up release will be made for this repo to also include the fix.

**Comment by A-Kasaaian** [comment]
OMG, thanks a million. You saved me. I was struggling for more than 2 days. 
Changing `targetSdkVersion` from 31 to 30 worked. I hope it gets resolved when new version comes.

**Comment by nan-li** [comment]
Hi @A-Kasaaian and others running into this,

There is a new release of `react-native-onesignal` version [4.3.8](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.3.8) that includes the native fix.
