### ISSUE TITLE
ld: library not found for -lPods-OneSignalNotificationServiceExtension

### ISSUE THREAD

**Issue by dovydas-s** [OneSignal/react-native-onesignal#1369]
**Description:**

Unable to run/build react native project  since adding one signal as a dependency.
Same configuration works for my colleague, I even tried to copy his `ios` folder
Tried with xcode, tried via react native, nothing gives
Followed all steps in setup guide 

Reinstalled pods, packages, node, xcode, npm, nothing works

Crashes on step "Link OneSignalNotificationServiceExtension" (arm64)

**Environment**

M1 Mac
react-native-onesignal": "^4.3.4",
XCode 13.2.1 (13C100)

**Steps to Reproduce Issue:**

cannot provide

**Anything else:**

Full crash log from xcode

Ld /Users/mac/Library/Developer/Xcode/DerivedData/PinginSpace-gqubvlxbuxnyxcdagldclpjybagi/Build/Products/Release-iphonesimulator/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension normal (in target 'OneSignalNotificationServiceExtension' from project 'PinginSpace')
    cd /Users/mac/dev/pingin-app/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios10.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.2.sdk -L/Users/mac/Library/Developer/Xcode/DerivedData/PinginSpace-gqubvlxbuxnyxcdagldclpjybagi/Build/Products/Release-iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphonesimulator -F/Users/mac/Library/Developer/Xcode/DerivedData/PinginSpace-gqubvlxbuxnyxcdagldclpjybagi/Build/Products/Release-iphonesimulator -F/Users/mac/dev/pingin-app/ios/Pods/OneSignalXCFramework/iOS_SDK/OneSignalSDK/OneSignal_XCFramework -F/Users/mac/Library/Developer/Xcode/DerivedData/PinginSpace-gqubvlxbuxnyxcdagldclpjybagi/Build/Products/Release-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework -filelist /Users/mac/Library/Developer/Xcode/DerivedData/PinginSpace-gqubvlxbuxnyxcdagldclpjybagi/Build/Intermediates.noindex/PinginSpace.build/Release-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/arm64/OneSignalNotificationServiceExtension.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../../Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/PinginSpace-gqubvlxbuxnyxcdagldclpjybagi/Build/Intermediates.noindex/PinginSpace.build/Release-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/arm64/OneSignalNotificationServiceExtension_lto.o -Xlinker -objc_abi_version -Xlinker 2 -fapplication-extension -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/PinginSpace-gqubvlxbuxnyxcdagldclpjybagi/Build/Intermediates.noindex/PinginSpace.build/Release-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/arm64/OneSignalNotificationServiceExtension.swiftmodule -ObjC -framework OneSignal -e _NSExtensionMain -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/PinginSpace-gqubvlxbuxnyxcdagldclpjybagi/Build/Intermediates.noindex/PinginSpace.build/Release-iphonesimulator/OneSignalNotificationServiceExtension.build/OneSignalNotificationServiceExtension.appex-Simulated.xcent -lPods-OneSignalNotificationServiceExtension -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/PinginSpace-gqubvlxbuxnyxcdagldclpjybagi/Build/Intermediates.noindex/PinginSpace.build/Release-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/arm64/OneSignalNotificationServiceExtension_dependency_info.dat -o /Users/mac/Library/Developer/Xcode/DerivedData/PinginSpace-gqubvlxbuxnyxcdagldclpjybagi/Build/Products/Release-iphonesimulator/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension

ld: library not found for -lPods-OneSignalNotificationServiceExtension
clang: error: linker command failed with exit code 1 (use -v to see invocation)

![2022-03-09_15-55-56 (22)](https://user-images.githubusercontent.com/17228130/157455776-98c6e9f7-22cb-4d5c-a6d3-587450895269.png)

**Comment by nan-li** [comment]
Hi @soblinskas,

Can you check your `Deployment Target` following this comment? https://github.com/OneSignal/react-native-onesignal/issues/838#issuecomment-665205966.

Confirm that the ios version in Deployment Info of your project target, OneSignalNotificationService, and podfile is the same.

**Comment by dovydas-s** [comment]
> Hi @soblinskas,
> 
> Can you check your `Deployment Target` following this comment? [#838 (comment)](https://github.com/OneSignal/react-native-onesignal/issues/838#issuecomment-665205966).
> 
> Confirm that the ios version in Deployment Info of your project target, OneSignalNotificationService, and podfile is the same.

did that, no change

**Comment by wmarsey** [comment]
Getting this same problem and its hindering development. Deployment targets are all correct. Did anyone here work out a fix?

**Comment by KestasVenslauskas** [comment]
Same problem here after trying to setup project on M1 mac, any update on this?
If I open xcode using Rosetta it builds fine.

**Comment by KestasVenslauskas** [comment]
So I got past by this issue by updating Framework search paths with new entry:
`"${PODS_ROOT}/OneSignalXCFramework/iOS_SDK/OneSignalSDK/OneSignal_XCFramework"`

Same for Library search paths.

But the main issue was to remove everything under "Excluded Architectures" I had "arm64" excluded which is saying to not build for M1

**Comment by KestasVenslauskas** [comment]
Another thing that helped is to have arm64 exluded on all project targets and also pods project (which I forgot about).

**Comment by znanick** [comment]
+1
Mac M1

**Comment by rgomezp** [comment]
Duplicate of https://github.com/OneSignal/react-native-onesignal/issues/1260
