### ISSUE TITLE
setNotificationWillShowInForegroundHandler not triggered when omitting content

### ISSUE THREAD

**Issue by curtisy1** [OneSignal/react-native-onesignal#1375]
**Description:**
When the app is in foreground and receives a silent notification (as in no `contents` set, as advised [here](https://documentation.onesignal.com/reference/create-notification#content--language) and `content_available` set to `true`) the callback for `OneSignal.setNotificationWillShowInForegroundHandler` does not get called

**Environment**
##### Installed package versions
react-native: 0.64.2
react-native-onesignal: 4.3.7,
react: 17.0.1

Dependencies were installed using `yarn add [package]`
Native code was added as per [the guide](https://documentation.onesignal.com/docs/react-native-sdk-setup)

**Steps to Reproduce Issue:**

1. Install and initalize the OneSignal SDK
2. Start the app and keep it in foreground
3. Send a silent notification to a device using the OneSignal api. Sample payload below

**Anything else:**
##### Sample payload (player ids and app id omitted for security)
```json
{"app_id":"xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx","include_player_ids":["xxxx-xxxx-xxxx-xxxx-xxxx"],"content_available":true,"data":{"type":"abc","id":"645643t","action":"update"},"ios_badgeCount":0}
```

##### Sample code for handler
```ts
OneSignal.setNotificationWillShowInForegroundHandler((notificationReceivedEvent: NotificationReceivedEvent) => {
    console.debug("received message"); // does not get triggered
	// custom logic
    notificationReceivedEvent.complete();
  });
```

##### Logcat logs
```
10:48:24.532
remoteNotificationReceivedHandler not setup, displaying normal OneSignal notification

10:48:24.532
Running destroyTimeout with runnable: com.onesignal.OSNotificationReceivedEvent$1@b4d8ce7

10:48:24.532
Saving Notification job: OSNotificationGenerationJob{jsonPayload={"google.delivered_priority":"normal","google.sent_time":1649407705841,"google.ttl":259200,"google.original_priority":"normal","custom":"{\"a\":{\"action\":\"update\",\"id\":\"2922412\",\"type\":\"tours\"},\"i\":\"xxxx-xxxx-xxxxx-xxxxx-xxxxxx\"}","from":"xxxxxx","google.message_id":"0:xxxx%xxxx","google.c.sender.id":"xxxxx"}, isRestoring=false, shownTimeStamp=1649407704, overriddenBodyFromExtender=null, overriddenTitleFromExtender=null, overriddenSound=null, overriddenFlags=null, orgFlags=null, orgSound=null, notification=OSNotification{notificationExtender=null, groupedNotifications=null, androidNotificationId=-1, notificationId='xxxx-xxxxx-xxxxx-xxxxx-xxxxxx', templateName='', templateId='', title='null', body='null', additionalData={"action":"update","id":"2922412","type":"tours"}, smallIcon='null', largeIcon='null', bigPicture='null', smallIconAccentColor='null', launchURL='null', sound='null', ledColor='null', lockScreenVisibility=1, groupKey='null', groupMessage='null', actionButtons=null, fromProjectNumber='xxxxx', backgroundImageLayout=null, collapseId='null', priority=0, rawPayload='{"google.delivered_priority":"normal","google.sent_time":1649407705841,"google.ttl":259200,"google.original_priority":"normal","custom":"{\"a\":{\"action\":\"update\",\"id\":\"2922412\",\"type\":\"tours\"},\"i\":\"xxxxx-xxxx-xxxx-xxxxx-xxxxx\"}","from":"xxxxx","google.message_id":"0:xxxxx%xxxxx","google.c.sender.id":"xxxxx"}'}}

10:48:24.535
Notification saved values: full_data={"google.delivered_priority":"normal","google.sent_time":1649407705841,"google.ttl":259200,"google.original_priority":"normal","custom":"{\"a\":{\"action\":\"update\",\"id\":\"2922412\",\"type\":\"tours\"},\"i\":\"xxxx-xxxx-xxxx-xxxx-xxxxx\"}","from":"xxxxx","google.message_id":"0:xxxxx%xxxxxx","google.c.sender.id":"xxxxx"} notification_id=xxxxx-xxxxx-xxxx-xxxxx-xxxx opened=1 expire_time=1649666905

10:48:24.536
Worker result SUCCESS for Work [ id=xxxx-xxxx-xxxx-xxxx-xxxx, tags={ com.onesignal.OSNotificationWorkManager$NotificationWorker } ]

10:48:29.541
Running complete from OSNotificationOpenedResult timeout runnable!

10:48:29.541
OSNotificationOpenedResult complete called with opened: false

10:48:29.541
Running destroyTimeout with runnable: com.onesignal.OSNotificationOpenedResult$1@29d9094
```

**Comment by curtisy1** [comment]
Pinging @Farami to handle responses while I'm on vacation 🏝

**Comment by jkasten2** [comment]
@curtisy1 @Farami The [`setNotificationWillShowInForegroundHandler`](https://documentation.onesignal.com/docs/sdk-notification-event-handlers#setnotificationwillshowinforegroundhandler-method) will only fire for visible notifications, as it only runs your handler just before showing a notification. Since you noted you omitted the message body it will not be shown.

Depending on your use case you may instead want to check in with your server to pull down data when the user opens the app. If you do really need something more real time you can check out this OneSignal guide:
https://documentation.onesignal.com/docs/rn-android-native-module-setup-for-notification-service-extension

If none of the above covers your use cases then please let us know your specific use case and we can try to suggest something else or take note to account for it with a future API.

**Comment by Farami** [comment]
@jkasten2 We were forced to upgrade OneSignal from **3.9.2** to **4.3.7** due to incompatibility with Android 12.
We have been using **3.9.2** in the way @curtisy1 described above, `OneSignal.addEventListener("received", ...)` triggered on silent notifications as well.
Has this functionality simply been removed?

**Comment by jkasten2** [comment]
@Farami Correct, silent (data only push) has been removed from JS layer here.

The [setNotificationWillShowInForegroundHandler](https://documentation.onesignal.com/docs/sdk-notification-event-handlers#setnotificationwillshowinforegroundhandler-method) function [I noted above](https://github.com/OneSignal/react-native-onesignal/issues/1375#issuecomment-1094112675) does fire when your app is in focus. This allows you to suppress notifications for your app if say they are already viewing the same information you want to convey to your Users.

Background silent push require native code in the 4.x.x release:
https://documentation.onesignal.com/docs/rn-android-native-module-setup-for-notification-service-extension

Please let us know your use cases for silent push and we can consider handling those natively in the SDK.

**Comment by curtisy1** [comment]
@jkasten2 This is certainly a breaking change. Would be great if it was documented anywhere in the release notes or migration guides.

I implemented a notification service extension module like in the docs but I have a question (or two) left:

Am I correct to assume this module gets called (and does trigger) on _every_ notification, even if it's not a silent one? If so, could we omit `setNotificationWillShowInForegroundHandler` entirely? From my quick tests it seems that is the case

---

As for our use case, we use our app mainly as a frontend for a variety of features including delivery management, time tracking, etc. Users have the option to toggle some of these features themselves (in a standalone web app), effectively "hiding" the relevant app portion from the end user. We previously solved this using silent notifications (since seeing a "your supervisor disabled your right for time tracking" kind of notification is unfeasible)

**Comment by jkasten2** [comment]
> Am I correct to assume this module gets called (and does trigger) on every notification, even if it's not a silent one? If so, could we omit setNotificationWillShowInForegroundHandler entirely? From my quick tests it seems that is the case

That is correct, the [`NotificationServiceExtensionModule` in the OneSignal instructions](https://documentation.onesignal.com/docs/rn-android-native-module-setup-for-notification-service-extension) will fire for both notifications with a body or without a body, as well as if the app is in the foreground or background.


> As for our use case, we use our app mainly as a frontend for a variety of features including delivery management, time tracking, etc. Users have the option to toggle some of these features themselves (in a standalone web app), effectively "hiding" the relevant app portion from the end user. We previously solved this using silent notifications (since seeing a "your supervisor disabled your right for time tracking" kind of notification is unfeasible)

Thanks for the extra detail, in this case you basically are using silent push to make responsive updates to your app while it is in the foreground? Or is something you were using to send data to the app so the change take effect as soon as the user opens the app?

**Comment by curtisy1** [comment]
> That is correct, the [NotificationServiceExtensionModule in the OneSignal instructions](https://documentation.onesignal.com/docs/rn-android-native-module-setup-for-notification-service-extension) will fire for both notifications with a body or without a body, as well as if the app is in the foreground or background.

Understood, thanks for clarifying 👍

> Thanks for the extra detail, in this case you basically are using silent push to make responsive updates to your app while it is in the foreground?

If by foreground you mean that the app is focused, then not necessarily. We also use silent push to make these updates while the app is running in the background (background in this case means still active and not killed/closed by the user)

**Comment by curtisy1** [comment]
@jkasten2

I tried implementing the iOS equivalent using [the basic setup](https://documentation.onesignal.com/docs/react-native-sdk-setup#step-4-install-for-ios-using-cocoapods-for-ios-apps) but I am unable to build the app after adding the `OneSignalNotificationServiceExtension`. Getting `'sharedApplication' is unavailable: not available on iOS (App Extension)` on build in XCode.
EDIT: Nevermind, I think I fixed it somehow


Leaving that aside, when I try modifying the [AppDelegate](https://documentation.onesignal.com/docs/rn-android-native-module-setup-for-notification-service-extension#sending-events-to-javascript-1) I get unresolved imports of `EXUpdates/EXUpdatesAppController.h`. This seems to be some Expo related header? Does the NotificationServiceExtensionModule also work in non-expo environments? Would be happy for any insight on these two issues since I'm at a loss

**Comment by jkasten2** [comment]
> If by foreground you mean that the app is focused, then not necessarily. We also use silent push to make these updates while the app is running in the background (background in this case means still active and not killed/closed by the user)

I see, so basically you want to make sure the UI can update as soon as they foreground the app again? Or is it you are trying to limit the number of network calls to your server to refresh the data?

> Leaving that aside, when I try modifying the [AppDelegate](https://documentation.onesignal.com/docs/rn-android-native-module-setup-for-notification-service-extension#sending-events-to-javascript-1) I get unresolved imports of EXUpdates/EXUpdatesAppController.h. This seems to be some Expo related header? Does the NotificationServiceExtensionModule also work in non-expo environments? Would be happy for any insight on these two issues since I'm at a loss

hmm, the docs are a bit confusing here, you shouldn't have to touch your `AppDelegate.h`, only your `AppDelegate.m`. Let me know if leaving  `AppDelegate.h` as-is result in things working.

**Comment by curtisy1** [comment]
> I see, so basically you want to make sure the UI can update as soon as they foreground the app again?

Correct

> Or is it you are trying to limit the number of network calls to your server to refresh the data?

That's also a concern, yes. Since the data we would have to fetch could get quite large, I'd like to avoid fetching it whenever the app comes to the foreground.

> hmm, the docs are a bit confusing here, you shouldn't have to touch your AppDelegate.h, only your AppDelegate.m. Let me know if leaving AppDelegate.h as-is result in things working.

Yup, that fixed it to the point where I can build the app again. Thank you!

**Comment by BhuwaneshSisodia** [comment]
hey @curtisy1 

How did you resolved this issue "'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead." ?

- Setting "NO" in "Require Only App-Extension-Safe API" - build setting also not working.

<img width="502" alt="Screenshot 2024-07-04 at 9 48 20 PM" src="https://github.com/OneSignal/react-native-onesignal/assets/19169880/cb1f2248-f219-4a02-a394-54f23ddd2e7c">

I also just followed onesignal's documentation, and got this in the end. I'm using latest RN, Xcode & CocoaPods versions.

**Comment by curtisy1** [comment]
Hey @BhuwaneshSisodia 

To be honest, I don't remember the steps we took to resolve this (apart from those outlined in this issue). 
Since then a lot of stuff has changed in RN OneSignal, so most of it probably doesn't apply anymore.
I'd suggest opening a new issue so the developers can take a fresh look at this
