### ISSUE TITLE
Correct way of calling setExternalUserId and setEmail for both email and push

### ISSUE THREAD

**Issue by yuvital-render** [OneSignal/react-native-onesignal#1376]
react-native-onesignal@4.3.7

Hi (-:

We are having a hard time getting the same externalUserId to appear on multiple player ids (one for push and one for email).
This is mentioned in the docs here and there but there is no single place where you can find a complete code example of doing this the right way. Having both email and push is a very common use case.

Is this the right way of doing this in React Native?

![CleanShot 2022-04-10 at 10 30 46@2x](https://user-images.githubusercontent.com/89977727/162607588-c3ffd010-2fbb-4279-bf28-e0867811b817.jpg)

If not, it will be very appreciated if you can provide us with code for doing it the right way AND also add this to the docs so other devs won't get stuck on this issue.

Thanks for any help on the matter!

**Comment by jkasten2** [comment]
@yuvital-render Thanks for reporting, we will look into making the documentation more clear on this.

The correct way is to create the player (aka subscription) first, then set the external user id.
```js
OneSignal.setEmail(email, null, () => {
   OneSignal.setExternalUserId(userId);
});
```

Are you currently seeing any issues? If so with iOS or Android?

There is an issue the sometimes the callback can fire to soon on Android, and this was address in the [OneSignal-Android-SDK 4.7.1](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.7.1)
> Fix the onSuccess callback from being invoked too early when setting email or SMS by @nan-li in https://github.com/OneSignal/OneSignal-Android-SDK/pull/1555

**Comment by yuvital-render** [comment]
Thanks for the code example!

**Comment by nan-li** [comment]
Hi @yuvital-render,

There is a new release of `react-native-onesignal` version [4.3.8](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.3.8) that includes the fix mentioned above. This release will fix this code below and set the email successfully. Sometimes before, it didn't set the email player.

```javascript
OneSignal.setEmail(email, null, () => {
   OneSignal.setExternalUserId(userId);
});
```

**Comment by philip-withpara** [comment]
@nan-li hi, what if i want to also add SMS subscription, but there are conditions if email/phone number exists?

```js
 if (userProfile.email) {
    OneSignal.setEmail(userProfile.email, null, () => {
      OneSignal.setExternalUserId(userProfile.userId)
    })
  }
  if (userProfile.phoneNumber) {
    OneSignal.setSMSNumber(userProfile.phoneNumber, null, () => {
      OneSignal.setExternalUserId(userProfile.userId)
    })
  }

  OneSignal.setExternalUserId(userProfile.userId)
```

is that the right way to do it?

**Comment by rgomezp** [comment]
Howdy,
You shouldn't need to call it so many times, though it's not too detrimental to do so -- you'll just be performing a redundant task.

You can perhaps nest the calls so as to only have one, or resolve promises in the callbacks that will cause the calling of a single `setExternalUserId` call.

Hope that helps.

**Comment by brunapereira** [comment]
@rgomezp thanks for the response. I'm having a similar issue.

If I just do this:

```
 if (userProfile.email) {
    OneSignal.setEmail(userProfile.email, null)
  }
  if (userProfile.phoneNumber) {
    OneSignal.setSMSNumber(userProfile.phoneNumber, null)
  }

  OneSignal.setExternalUserId(userProfile.userId)
```

I end up having 3 player ids:
1. SMS subscription - Player ID 1 - External ID null
2. Email subscription - Player ID 2 - External ID null
3. Push subscription - Player ID 3 - External ID XXXX

And my goal is to have:
1. SMS subscription - Player ID 1 - External ID XXXX
2. Email subscription - Player ID 2 - External ID XXXX
3. Push subscription - Player ID 3 - External ID XXXX

which is why I'm going to try @philip-withpara's approach. 

How would you recommend achieving this without multiple calls to setExternalId?
