### ISSUE TITLE
Android Notification icon customization

### ISSUE THREAD

**Issue by Kowaio** [OneSignal/react-native-onesignal#138]
Hi guys,

I'm struggling trying to customize the notification icon using react-native and your package. Indeed, I'd like to be able to change the accent color of the icon but I didn't find a clue about that yet. The official documentation is giving some code to do that in java but installing your react native package and their java sdk is conflicting so I'm in a dead-end. Did you encounter this issue and know a way to resolve this?

Thanks again for your time.

**Comment by avishayil** [comment]
Hi,
Please follow the instructions here:
https://documentation.onesignal.com/docs/customize-notification-icons

**Comment by Kowaio** [comment]
Hi @avishayil,
Thanks for your answer. Yes I already used this page of the documentation to generate the icons and add them into my project with the `ic_stat_onesignal_default` name, and it's working properly. However, icons are white with a transparent background. I wanted to add some blue color as background programmatically for those who can display it, using accent color.

For instance Batch is doing so with the call `Batch.Push.setNotificationsColor(0x3b8dd0);` and I was wondering if it was possible using your lib.

**Comment by avishayil** [comment]
@Kowaio Never tried it myself in my apps actually, but it could be interesting to try. I'll try finding some time to try it and would let you know my findings.

**Comment by jkasten2** [comment]
@Kowaio @avishayil Just added details for this in a new section on the bottom of the page.
https://documentation.onesignal.com/docs/customize-notification-icons#section-small-icon-color

**Comment by avishayil** [comment]
@Kowaio did you have a chance to check @jkasten2 reference?

**Comment by Kowaio** [comment]
Hi @avishayil,

Sorry for the delay. Yes, I tried the first section `To set a default color add the following line to your AndroidManifest.xml.` but didn't see a change after rebuilding the app. Since it can take a while to propagate, I'll retry that in the next few days to be sure it's okay. Thanks again to both of you for adding that feature so quickly though :)

**Comment by avishayil** [comment]
@Kowaio did you manage to sort this out?

**Comment by Kowaio** [comment]
Hello @avishayil,
So sorry, I forgot to get back to you. So yeah it worked as expected. Thanks again to both of you. Closing this one now!

**Comment by avishayil** [comment]
Great!

**Comment by ShridharCodewave** [comment]
Iam getting the android default notification icon (bell icon) and I already tried the steps to create icon which are specified at https://documentation.onesignal.com/docs/customize-notification-icons but its not working. Is there any way to set small_icon in REST API?

**Comment by anastely** [comment]
@ShridharCodewave are you solve it :D?
