### ISSUE TITLE
'RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by bitcoinvsalts** [OneSignal/react-native-onesignal#139]
I am getting this xcode error:
RCTOneSignal.h:1:9: 'RCTBridgeModule.h' file not found

any idea why?

I am using xcode 8.2.1 and rn 0.38.0

here is my podifle:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fishii' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Fishii
  pod 'Firebase/Core'
  pod 'OneSignal', '~> 1.13.3'

  #target 'FishiiTests' do
  #  inherit! :search_paths
    # Pods for testing
  #end

end

```

**Comment by avishayil** [comment]
Are you sure you're using the latest version and pod as mentioned in the docs?

**Comment by bitcoinvsalts** [comment]
yes I do

**Comment by johnsonsu** [comment]
What's the version of `react-native-onesignal` you using? The one in your `package.json`. I think you should be using `^2.0.0`.

**Comment by MEDLJosh** [comment]
I had the same issue. I was able to fix it by changing the import statements from 
#import <React/RCTBridgeModule.h
to
#import "RCTBridgeModule.h

I had to do this for a couple of different import statements. Once I changed them, the project build fine.

**Comment by GeoffreyPlitt** [comment]
@MEDLJosh What file did you find these imports in?

**Comment by GeoffreyPlitt** [comment]
Also, can we get a concensus about which version of this library to use? I've seen conflicting suggestions, some people say "everyone should use 3.0.0" and here you say to use 2.0.0. Doesn't it depend on which version of RN we're using?

**Comment by avishayil** [comment]
Everything is in the docs. RN 40 and up should use v3, RN up to 0.39 should use v2.

**Comment by GeoffreyPlitt** [comment]
I am still having these errors with RN=0.39 and v2.0.0 of this lib.
```
In file included from /Users/giro/react_native_minimal/node_modules/react-native-onesignal/ios/RCTOneSignal/RCTOneSignal.m:1:
/Users/giro/react_native_minimal/node_modules/react-native-onesignal/ios/RCTOneSignal/RCTOneSignal.h:1:9: fatal error: 'React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>
```

I created a branch of a minimal RN project here, where you can run ```react-native run-ios``` to see these errors: https://github.com/GeoffreyPlitt/react_native_minimal/tree/onesignal

**Comment by jakecraige** [comment]
I recently discovered the the header wasn't being properly added to the `ios/Pods/Headers/Public/OneSignal` path which is why I got this error. I had to remove `use_frameworks!` from my Podfile to get it working. Thankfully I didn't need that yet but not sure which approach I'd take if I did.
