### ISSUE TITLE
Xiaomi - Notification cannot open the app due to permissions. Requires"display pop-up window in foreground and in background"

### ISSUE THREAD

**Issue by kaanaksac** [OneSignal/react-native-onesignal#1393]
Problem:
xiaomi notification cannot open the app due to permissions. As far as I have researched, it is necessary to allow "display pop-up window in foreground and in background" from the application settings.

Environment
react-native: 0.62.2
Device: xiaomi mi 9 lite
Package version: 4.3.7

Hi, any progress on the subject?

Note: what I don't understand is that I was getting this error from time to time in 4.1.1. But now the application is not triggered unless I give this permission in 4.3.7.

_Originally posted by @kaanaksac in https://github.com/OneSignal/react-native-onesignal/issues/1309#issuecomment-1057707288_

**Comment by jkasten2** [comment]
The react-native-onesignal SDK [version 4.3.10](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.3.10) has been released with this fix.
