### ISSUE TITLE
[IOS] Notification does not Deeplink if app closed

### ISSUE THREAD

**Issue by ImersivDev** [OneSignal/react-native-onesignal#1397]
**Description:**

When iOS app is closed, if user click on notification the deeplink does not work (the app is just opens).

**Environment**

```
## Yarn
"react-native": "0.66.0",
"react-native-onesignal": "4.3.8",
"react-navigation": "4.4.4",
```

**Steps to Reproduce Issue:**

1. Install the OneSignal SDK using yarn into your project by following this [tutorial](https://documentation.onesignal.com/docs/ios-sdk-setup)
2. Add your deeplink with React Navigation
3. Install your app in physic iOS device or push your build on TestFlight
4. Open your app to allow notifications and initialize your player id
5. Close the app
6. Send push notification with OneSignal Dashboard with your deeplink
7. Click on notification

The application opens and the deeplink does not work

**Anything else:**

If you try to put your deeplink in safari with the app closed, all works fine.

**Comment by kesheshyan** [comment]
Thanks for reporting! We are looking into this issue.

**Comment by marcshilling** [comment]
Same issue for me I think. I updated from 4.2.0 (where this was working fine) to 4.3.11 and started experiencing this. All good when the app was alive in the background, but when cold booting from a push notification it would not deep link. I rolled back to 4.3.5 and it's working again, so something between those versions I guess.

Very difficult to debug this cause you need the app to be killed (therefore not connected to debugger), but it seemed to be a race condition of some sort. My `OneSignal.setNotificationOpenedHandler` was being called but navigation not happening. If I wrapped the navigation action in a `setTimeout` of 2 seconds, it would work. I'd imagine I could refactor to ensure navigation was ready to occur prior to setting the handler but I'm just curious how it works without doing this in <= 4.3.5. Anyway, following for updates!

**Comment by marcshilling** [comment]
False alarm I think...the race condition was in my code. I updated to 4.3.11 and am back in business. As long as all everything in your app is ready to deep link when you call `OneSignal.setNotificationOpenedHandler`, the initial launch notification is correctly handled.

**Comment by jon-eubank** [comment]
I had a similar problem too when I was setting the `OneSignal.setNotificationOpenedHandler` in App.js but once I moved it to the first screen in my application this solved the race condition.  Previously when it was in App.js a race condition was occurring and attempting to open a screen before my React Navigation was actually ready to try to navigate.

**Comment by jennantilla** [comment]
Closing as this issue is resolved by addressing the race condition described in the comments.

**Comment by nmateo** [comment]
Can it be reopened ? OneSignal.setNotificationOpenedHandler doesn not exist in v5 afaik i've tried everything and it is undefined/ not here anymore.
Is it impossible to deepLink with notification and open the app/put it to foreground ?
With expo we use only one hook and it does the job: Notifications.useLastNotificationResponse();
If this is impossible with oneSignal this is kind of a deal breaker.
Also i contacted support they told me to use OneSignal.Notifications.addEventListener('click', (event))
Which i use already but works only when the app is in foreground... and after that support ghosted me...

**Comment by dombartenope** [comment]
Hi @nmateo, the setNotificationOpenedHandler was removed and you can now listen for a notification opened event by using `OneSignal.Notifications.addEventListener('click', (event: NotificationClickEvent) =>{}`

There's an example of usage here : 
https://github.com/OneSignal/react-native-onesignal/blob/major_release_5.0.0/MIGRATION_GUIDE.md#notification-click-listener

We have a guide on deep linking [here](https://documentation.onesignal.com/docs/links). The general idea is to either handle the link using additional data (using an event handler or a service extension) or if you just need to use the default notification open behavior to handle linking within the app you can just use the launchURL when creating the notification.
