### ISSUE TITLE
App not opens from push notification click

### ISSUE THREAD

**Issue by aneena-thomas** [OneSignal/react-native-onesignal#1402]
The app does not open from a push notification click, it always opens the browser on both iOS and Android. Any idea?

**Verisons**
 "react-native-onesignal": "^4.3.7"
 "react-native": "0.67.3"

@kesheshyan

**Comment by kesheshyan** [comment]
Thanks fore reporting. Seems like this is duplicate https://github.com/OneSignal/react-native-onesignal/issues/1397

**Comment by musthafa-pa** [comment]
I'm also facing the same issue with the Android devices. 
"react-native": "^0.67.2",
"react-native-onesignal": "^4.3.6",

**Comment by aneena-thomas** [comment]
@musthafa-pa, when I add the "OneSignal_suppress_launch_urls" key and set it to true in the info plist and manifest it's working fine for me now. Not when I click a push it redirects to the app.
