### ISSUE TITLE
ExternalId is not being set.

### ISSUE THREAD

**Issue by kamalpandey** [OneSignal/react-native-onesignal#1404]
**Description:**

I am trying to set the externalId but it is not working most of the times.

**Environment**
1. What version of the OneSignal React-Native SDK are you using?
"react-native-onesignal": "^4.3.7"

2. How did you add the SDK to your project (eg. npm)
yarn

**Steps to Reproduce Issue:**

```
useEffect(() => {
    OneSignal.setExternalUserId(id, results => {
      // Push can be expected in almost every situation with a success status, but
      // as a pre-caution its good to verify it exists
      if (results.push && results.push.success) {
        // # callBackendAPI
      }
    });
}, []);

```

**Comment by jkasten2** [comment]
@kamalpandey Could you provide details on the follow questions?
1. Is the External User Id not being updated when you view it on:
    a. The dashboard
    b. When you try to get the value from the SDK?
    c. If check the value a few minutes later does it take effect?
2. Do you get any errors in the Xcode console or Android's logcat?
3. Does the issue happen on Android or iOS or both?

**Comment by nan-li** [comment]
Closing due to no response.
