### ISSUE TITLE
How to run React Native or JavaScript code even if app is in killed state  ??

### ISSUE THREAD

**Issue by AdityaThummar** [OneSignal/react-native-onesignal#1405]
**Description:**

(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jennantilla** [comment]
Hi @ShadowClone26 - can you please provide some additional details about your question/steps to reproduce your issue?

Thank you!

**Comment by jennantilla** [comment]
Closing due to no response. Please feel free to comment if still having issues!
