### ISSUE TITLE
App Icon Badge not gets increment or decrement when notification came in IOS

### ISSUE THREAD

**Issue by FayyazAliKhan1** [OneSignal/react-native-onesignal#1408]
**App Icon Badge Issue:**

I have searched a lot about this issue, Followed all the steps mentioned in the documentation. I have reviewed the steps of adding the App groups capability many times and it always seems fine, this issue is from a very long time in IOS.

**Enviorment**
Dev & Production
**OneSignal React-Native SDK**
4.3.11
Followed all the steps mentioned in documentation, not a single step is left

I have also sent 
ios_badgeType: 'Increase',
ios_badgeCount: 1
when sending notification from backend
but it only increase 1 it's not updating to 2

I have this issue as well that setNotificationWillShowInForegroundHandler event is called twice, once a notification is received. I have used this in useEffect of app.js

Please give me a proper solution about this Thanks

**Comment by jennantilla** [comment]
Hi @FayyazAliKhan1, thanks for your patience!

Are you still having issues with badge incrementation on iOS? 

I see you mentioned that you have followed the App Groups instructions--did you also follow the [troubleshooting guide](https://documentation.onesignal.com/docs/ios-sdk-app-groups-setup#ios-app-groups-troubleshooting) to check your deployment target, entitlements, and provisioning profiles?

If you are still having issues, can you please enable [logging within the Notification Service Extension](https://documentation.onesignal.com/docs/ios-sdk-app-groups-setup#logging-within-the-nse) to verify the data is being saved correctly?

Feel free to share the results here.

**Comment by FayyazAliKhan1** [comment]
Hi @jennantilla thanks for your reply I will do the [logging with NSE](https://documentation.onesignal.com/docs/ios-sdk-app-groups-setup#logging-within-the-nse) soon

**Comment by jennantilla** [comment]
Hi @FayyazAliKhan1 just checking in--were you able to figure this out?
Closing due to no update but please comment if still having issues.
