### ISSUE TITLE
onNotificationReceived() and onNotificationOpened() never fire

### ISSUE THREAD

**Issue by GeoffreyPlitt** [OneSignal/react-native-onesignal#141]
Hello,

I'm using RN=0.39 and 3.0.0 of this lib.

On the client side, configure()  succeeds and I see a UserId and push token.

On the server side, I'm using https://github.com/SeVeNDuS/node-onesignal-api, and I'm successfully sending a notification to the client's UserId, receiving a successful response with a messageId, and recipients=1.

However, onNotificationReceived() and onNotificationOpened() are never fired.

How do I debug this, to see if the message got to my device?

**Comment by avishayil** [comment]
Hi @GeoffreyPlitt , can you please set up an example project, or let me access into your project?
As for debugging, I suggest going to the iOS / Android project and putting logs to see if the problem is on the native side or JS side.
Start with `RCTOneSignal.m`:

```objc
- (void)handleRemoteNotificationOpened:(NSString *)result {
    NSLog(result); // Add this line
    NSError *jsonError;
    NSData *objectData = [result dataUsingEncoding:NSUTF8StringEncoding];
    NSDictionary *json = [NSJSONSerialization JSONObjectWithData:objectData
                                                         options:NSJSONReadingMutableContainers
                                                           error:&jsonError];
    
    [curRCTBridge.eventDispatcher sendAppEventWithName:@"remoteNotificationOpened" body:json];
}
```

And see if the log goes well on the XCode logs.

Thanks!

**Comment by GeoffreyPlitt** [comment]
Update: My notification is "queued" in the onesignal dashboard, so that seems to be the culprit, closing. Thanks for the help anyway!
