### ISSUE TITLE
OneSignal error

### ISSUE THREAD

**Issue by ghost** [OneSignal/react-native-onesignal#1412]
**Description:**

Hello, I have this error when download OneSignal to my expo react native : "Could not load RNOneSignal native module. Make sure native dependencies are properly linked." and I did same as the documentation any help?

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@Ibtissamalwannas Thanks for your question. Can you let us know if you are ejecting your react project if this a managed workflow?
If you are are using a managed workflow make sure to also install the [`onesignal-expo-plugin](https://github.com/OneSignal/onesignal-expo-plugin)` as well as flow the instructions there.

Do you get this issue with Android or iOS or both?

Could you also include your react and expo versions you are using?

**Comment by badinenisaivardhan** [comment]
if you are using RN check : https://github.com/OneSignal/react-native-onesignal/issues/1345#issuecomment-1291587087
if EXPO: onesignal-expo-plugin (https://github.com/OneSignal/onesignal-expo-plugin

**Comment by mohammad6vakili** [comment]
same issue

**Comment by mohammad6vakili** [comment]
OneSignal Expo Plugin doesn't work...please help

**Comment by Martijncvv** [comment]
Having the same isssue. How did you fix it?

**Comment by muh-afaq** [comment]
i have same issue please porper guid about it, i see this decomentaion and this issue search other website
