### ISSUE TITLE
I do not want the permission request that you open the application.

### ISSUE THREAD

**Issue by umutkocak** [OneSignal/react-native-onesignal#1414]
**Description:**

I do not want the permission request that you open the application.
**Environment**

    "react-native": "0.68.2",
    "react-native-onesignal": "^4.3.11",

**Code:**

<img width="1238" alt="Ekran Resmi 2022-07-27 15 04 02" src="https://user-images.githubusercontent.com/25377336/181245451-fe7d8d14-30a0-4eea-9217-4af87ae9856a.png">

**Comment by nan-li** [comment]
Hi @umutkocak,

I apologize for the delayed response. This SDK will **not** automatically show the push permission prompt when the application is opened. You call the method `OneSignal.promptForPushNotificationsWithUserResponse()` to show it.

`kOSSettingsKeyAutoPrompt` existed in version `3.x.x` but is now deprecated.
