### ISSUE TITLE
How to clear setInAppMessageClickHandler listener

### ISSUE THREAD

**Issue by AuroPick** [OneSignal/react-native-onesignal#1417]
**Description:**

I created a setInAppMessageClickHandler in my bottom navigation. I want to clear this listener when user logout. How can I do that

**Environment**

"react-native-onesignal": "4.3.8"
package manager: yarn

**Steps to Reproduce Issue:**

1. Create listener in bottom navigation
2. Reset navigation when user logout
3. Listener still working

**Anything else:**

`InAppListener.js`
```js
import { useCallback, useEffect, memo } from 'react'

import lodash from 'lodash'
import { Linking } from 'react-native'
import OneSignal from 'react-native-onesignal'

const InAppListenerComponent = () => {
  // handle in app message
  const handler = useCallback((event) => {
    if (lodash.isEmpty(event)) return

    if (!event.click_name) return

    Linking.openURL(event.click_name)
  }, [])

  // create listener for OneSignal
  useEffect(() => {
    OneSignal.setInAppMessageClickHandler(handler)
  }, [handler])

  return null
}

export const InAppListener = memo(InAppListenerComponent)
```

`BottomNavigation.js`
```js
return (
    <>
      <Tab.Navigator>
        ...
      </Tab.Navigator>
      <InAppListener />
    </>
  )
```

**Comment by jennantilla** [comment]
Hi @AuroPick thanks so much for your patience.

We do not have a method for only clearing the `setInAppMessageClickHandler` but you can use [`clearHandlers`](https://github.com/OneSignal/react-native-onesignal/blob/c5c969907edaec356d23a824322aea2b85f08849/src/index.ts#L1049) to clear all handlers and observers.

Thanks!

**Comment by jennantilla** [comment]
Closing due to no response.
