### ISSUE TITLE
getTags retrieves other user's data tags 

### ISSUE THREAD

**Issue by zirgulis** [OneSignal/react-native-onesignal#1418]
**Description:**

We are using data tags to tag users with different attributes. The issue we noticed is: 

1.  User logs in into the app, if data tag is not present, set it.
2. User logs out
3. Different user account logs in the same device, data tag is present from previous user. 

Is there some limitation in place, where the data tags are set on device level and different accounts with playerIDs are ignored?

Would really appreciate any advice on this issue.

**Environment**

OneSignal version: "^4.3.11"
React native version: ""0.65.1"
Followed [docs](https://documentation.onesignal.com/docs/react-native-sdk-setup) and used yarn

**Comment by emawby** [comment]
@zirgulis By different playerIDs do you mean different `externalUserIds`?  Player IDs are device specific and do not change if the `externalUserId` is changed.

> Is there some limitation in place, where the data tags are set on device level and different accounts with playerIDs are ignored?

Yes currently tags go on the player id (device). We are aware of the limitations of handling "users" this way and are working on a change!

**Comment by jennantilla** [comment]
Just wanted to note that in our new major release (5.x.x) we have updated to a new user-centric model that addresses this feedback. Please refer to our [migration guide](https://github.com/OneSignal/react-native-onesignal/blob/major_release_5.0.0/MIGRATION_GUIDE.md) for details on upgrading. Thanks!
