### ISSUE TITLE
initWithContext is not a function

### ISSUE THREAD

**Issue by ajouve** [OneSignal/react-native-onesignal#1419]
**Description:**

I just followed this tutorial to implement OneSignal in my react native app https://documentation.onesignal.com/docs/react-native-sdk-setup, but I am not sure the code from step5 is correct.

First, there is a `});` after `OneSignal.promptForPushNotifications();` corresponding to nothing.

After that I have the exact same code, just changing the `ONESIGNAL_APP_ID` for my appid

And I have more errors:

1. `OneSignal.initWithContext(this);` `initWithContext` is not defined in the package 

```
TypeError: _reactNativeOnesignal.default.initWithContext is not a function. (In '_reactNativeOnesignal.default.initWithContext(this)', '_reactNativeOnesignal.default.initWithContext' is undefined)
```

2. Exact same issue for `OneSignal.promptForPushNotifications()`

```
TypeError: _reactNativeOnesignal.default.promptForPushNotifications is not a function. (In '_reactNativeOnesignal.default.promptForPushNotifications()', '_reactNativeOnesignal.default.promptForPushNotifications' is undefined)
```
I had a look to the code and can not find the methods

**Environment**
```
"react-native-onesignal": "^4.4.0",
"react": "18.0.0",
"react-native": "0.69.3",
testing on real iphone 12
```

**Steps to Reproduce Issue:**
Do the tutorial and run the step 5 code

Full error is

```
 ERROR  TypeError: _reactNativeOnesignal.default.initWithContext is not a function. (In '_reactNativeOnesignal.default.initWithContext(this)', '_reactNativeOnesignal.default.initWithContext' is undefined)
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

I maybe failed configuration on my side

Thanks

**Comment by pmogollons** [comment]
Having the same issue after updating to the latest version.

**Comment by nan-li** [comment]
Thanks @ajouve and @pmogollons for reporting this. The documentation for react native setup is indeed incorrect. 

1. To initialize OneSignal, call only `OneSignal.setAppId("YOUR_APP_ID")` and no call to `initWithContext`.
2. To prompt for push notifications, the method is `OneSignal.promptForPushNotificationsWithUserResponse` not `OneSignal.promptForPushNotifications`.

I apologize for the wrong documentation, we will update it.

**Comment by nan-li** [comment]
Documentation has been updated so I will close this issue.
