### ISSUE TITLE
[Question] Can I set a header and a message in OneSignal.postNotification

### ISSUE THREAD

**Issue by MEDLJosh** [OneSignal/react-native-onesignal#142]
I have the plugin working and I can send notifications to a specific user. I pass the contents object to the postNotification method, but the push notification received uses the same message as the header and the body. Is there a way to pass both a title and a message? 
```
    let data = {'test':'hello'}
    let contents =
    {
      'en': message
    }
    OneSignal.postNotification(contents,data,this.state.userPushKey)
```

**Comment by avishayil** [comment]
The current API supports `contents` only, i'll work on extending this API to send a `parameters` JSON object instead.

**Comment by MEDLJosh** [comment]
@avishayil That would be awesome! Thanks!

**Comment by hounsellal** [comment]
+1

**Comment by MEDLJosh** [comment]
Any updates on this feature?

**Comment by avishayil** [comment]
Hi @MEDLJosh , sorry but I haven't found the time to handle this yet.
Any help would be appreciated.

**Comment by daviaugustos** [comment]
Hello everyone, 

The **heading** can be passed through the othersParameters **parameter**:
![image](https://user-images.githubusercontent.com/20953743/34438513-81bc7af6-ec8e-11e7-9351-43694e39fdaf.png)

An example: 
![image](https://user-images.githubusercontent.com/20953743/34438713-dd8a1f04-ec8f-11e7-88c9-a3f88dc1c534.png)


The parameters can be found at:
https://documentation.onesignal.com/reference#create-notification

Hope this helps,
