### ISSUE TITLE
Heading notification automatically displayed

### ISSUE THREAD

**Issue by ajouve** [OneSignal/react-native-onesignal#1420]
**Description:**
On iPhone and android, just after accepting the notifications from the popup `OneSignal.promptForPushNotificationsWithUserResponse();` I have the attached notification

![IMG_9294](https://user-images.githubusercontent.com/2337492/183598659-01f30b8f-3fd0-413d-9263-6b605188a813.JPG)

**Environment**
    "react": "18.0.0",
    "react-native": "0.69.3",
    "react-native-onesignal": "^4.4.0",

Issue on iOS and android

**Steps to Reproduce Issue:**
Run the following 

```javascript
import OneSignal from 'react-native-onesignal';

// OneSignal Initialization
OneSignal.setAppId('XXX');

// promptForPushNotificationsWithUserResponse will show the native iOS or Android notification permission prompt.
// We recommend removing the following code and instead using an In-App Message to prompt for notification permission (See step 7)
OneSignal.promptForPushNotificationsWithUserResponse();

//Method for handling notifications received while app in foreground
OneSignal.setNotificationWillShowInForegroundHandler(notificationReceivedEvent => {
  console.log("OneSignal: notification will show in foreground:", notificationReceivedEvent);
  let notification = notificationReceivedEvent.getNotification();
  console.log("notification: ", notification);
  const data = notification.additionalData
  console.log("additionalData: ", data);
  // Complete with null means don't show a notification.
  notificationReceivedEvent.complete(notification);
});

//Method for handling notifications opened
OneSignal.setNotificationOpenedHandler(notification => {
  console.log("OneSignal: notification opened:", notification);
});

export function setLocale(locale) {
    OneSignal.sendTag("locale", locale);
}
```

Then accept notifications and the `Heading` will show

**Anything else:**

Not sure if this is related or an issue with the [documentation](https://documentation.onesignal.com/docs/react-native-sdk-setup) but 

```
We recommend removing the following code and instead using an In-App Message to prompt for notification permission (See step 7)
```

And the step 7 is about `Set Custom User Properties` no `using an In-App Message to prompt for notification permission`

Thanks

**Comment by nan-li** [comment]
Hi @ajouve,

Thanks for reporting the numbering issue with our documentation. As for the **Heading** popup, we don't send this to users. 

It looks like an in-app message. Can you confirm this isn't an existing OneSignal in-app message set up for your app ID? Or something else unique to your app?
