### ISSUE TITLE
Execution failed for task ':react-native-onesignal:generateDebugRFile'.

### ISSUE THREAD

**Issue by vt978** [OneSignal/react-native-onesignal#1421]
**Description:**
After several days of inactivity of my project, i wanted to build a released version of it. No other changes were made in that time other than api url changes and now i'm facing this problem. Tested other projects with almost same environment that was working before also faced this problem. This happen both in debug and release
<img width="670" alt="Screenshot 2022-08-12 at 1 52 03 PM" src="https://user-images.githubusercontent.com/49664106/184293190-5d4ac44c-15f4-4f6d-bad9-db0a4d2411b8.png">

**Environment**
1. react-native-onesignal : 4.0.6
2. react-native: 0.60.5
3. react: 16.8.6

**Steps to Reproduce Issue:**
1. Followed [docs](https://documentation.onesignal.com/docs/react-native-sdk-setup) and used npm

**Comment by nan-li** [comment]
Hi @vt978,

When you say that other projects are also facing this problem, are they also using OneSignal at all?

Did you already try a clean build in Android Studio by going to File > "Invalidate Caches / Restart ...". Then do a clean build after restarting.

**Comment by vt978** [comment]
@nan-li ,
yep, they were using onesignal also with similar environment such as onesignal, react native versions etc. Some of them were working recently up to this problem occur.

I'm tried upgrade/downgrade onesignal which didnt work. Only tried ./gradlew clean, is it the same as "Invalidate Caches / Restart ..." ? If no, is there any way to do it without android studio ?

**Comment by vt978** [comment]
Closing issue, unsure of what specified reason but the gradle dependencies below was causing the issues although it was working just fine several days ago
       classpath 'com.android.tools.build:gradle:3.4.2'
       distributionUrl=https\://services.gradle.org/distributions/gradle-6.2-all.zip

I changed it and it was working again
       classpath 'com.android.tools.build:gradle:3.6.3'
       distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip

**Comment by nan-li** [comment]
Good to hear it is resolved for you. I see the original error mentions `work-runtime:2.8.0-alpha03`. 

[That version](https://developer.android.com/jetpack/androidx/releases/work#2.8.0-alpha03) was released on August 10, 2022, and probably is what affected your build.
