### ISSUE TITLE
[Android] [Crash] RevenueCat incompatibility

### ISSUE THREAD

**Issue by yasinugrl** [OneSignal/react-native-onesignal#1422]
Latest native sdk fixed this issu but in RN still get erro.

https://github.com/OneSignal/OneSignal-Android-SDK/pull/1621

**Anything else:**

D/OneSignal(31495): App id set for first time:  [APP ID]
D/Kiwi    (31495): AppstoreSDK: Starting initialization process for application: [App Bundle ID]
D/Kiwi    (31495): ResourceManagerImpl: Registering resource: com.amazon.a.a.k.c@cdb992d
E/AndroidRuntime(31495): FATAL EXCEPTION: OS_REST_SUCCESS_CALLBACK
E/AndroidRuntime(31495): Process: [App Bundle Id], PID: 31495
E/AndroidRuntime(31495): com.amazon.a.a.o.a.b: Executing thread must be thread: 2, was: 29839
E/AndroidRuntime(31495): 	at com.amazon.a.a.o.a.a.a(Assert.java:59)
E/AndroidRuntime(31495): 	at com.amazon.a.a.o.a.a.a(Assert.java:48)
E/AndroidRuntime(31495): 	at com.amazon.a.a.o.a.a.a(Assert.java:31)
E/AndroidRuntime(31495): 	at com.amazon.a.a.k.c.a(ResourceManagerImpl.java:50)
E/AndroidRuntime(31495): 	at com.amazon.a.a.k.c.<init>(ResourceManagerImpl.java:34)
E/AndroidRuntime(31495): 	at com.amazon.a.a.b(AppstoreSDK.java:169)
E/AndroidRuntime(31495): 	at com.amazon.a.a.<init>(AppstoreSDK.java:153)
E/AndroidRuntime(31495): 	at com.amazon.a.a.a(AppstoreSDK.java:232)
E/AndroidRuntime(31495): 	at com.amazon.device.iap.PurchasingService.registerListener(PurchasingService.java:89)
E/AndroidRuntime(31495): 	at com.onesignal.TrackAmazonPurchase.setListener(TrackAmazonPurchase.java:107)
E/AndroidRuntime(31495): 	at com.onesignal.TrackAmazonPurchase.<init>(TrackAmazonPurchase.java:84)
E/AndroidRuntime(31495): 	at com.onesignal.OneSignal.handleAmazonPurchase(OneSignal.java:985)
E/AndroidRuntime(31495): 	at com.onesignal.OneSignal.init(OneSignal.java:862)
E/AndroidRuntime(31495): 	at com.onesignal.OneSignal.setAppId(OneSignal.java:735)
E/AndroidRuntime(31495): 	at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1181)
E/AndroidRuntime(31495): 	at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:889)
E/AndroidRuntime(31495): 	at com.onesignal.OneSignal$7.complete(OneSignal.java:1122)
E/AndroidRuntime(31495): 	at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:211)
E/AndroidRuntime(31495): 	at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
E/AndroidRuntime(31495): 	at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:156)
E/AndroidRuntime(31495): 	at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:279)
E/AndroidRuntime(31495): 	at java.lang.Thread.run(Thread.java:919)

**Comment by nan-li** [comment]
Hi @yasinugrl, thank you for reporting. We just released a new version of react-native-onesignal [Version 4.4.1](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.4.1) that includes the fix.
