### ISSUE TITLE
 Task :app:checkDebugAarMetadata FAILED

### ISSUE THREAD

**Issue by Zaid1habib** [OneSignal/react-native-onesignal#1424]
![new error1](https://user-images.githubusercontent.com/105972844/187150356-4fcd72da-00e6-4673-9933-156ed1860726.png)
![new error 2](https://user-images.githubusercontent.com/105972844/187150345-c174b973-da21-40af-ae99-257088051ca7.png)
![new error 3](https://user-images.githubusercontent.com/105972844/187150353-507a61a8-9a78-48df-b5a2-e88f0115e9fe.png)

this solution's is not working for me.

![not woeking 1](https://user-images.githubusercontent.com/105972844/187151061-d175e1d6-4ed9-49d2-bdd0-fb005f2b3d4a.png)
![not woeking 2](https://user-images.githubusercontent.com/105972844/187151071-c1bdee3e-020f-4f20-a2c3-f1ec432e352d.png)

**Comment by emawby** [comment]
@Zaid1habib Is this issue caused by your compileSDKVersion being 29 when a dependency requires a min of 31?
