### ISSUE TITLE
How to prompting for notifications permissions more than once

### ISSUE THREAD

**Issue by idanlevi1** [OneSignal/react-native-onesignal#1425]
**Description:**

I ask permission by `promptForPushNotificationsWithUserResponse` first,
After the user is denied, how can I show again the ask permission popup? 
I tried `promptForPushNotificationsWithUserResponse` but is not show popup again... 
(your description here)

**Environment**

 ```
react-native: 0.68.2
react-native-onesignal: 4.4.1
```

**Comment by jennantilla** [comment]
Hi @idanlevi1 

iOS allows their native push prompt to be shown one time. It cannot be re-shown if dismissed or if previously allowed. If it was shown in the past, the user must be sent to their phone settings to enable notifications.

Using OneSignal's [In-App Messages](https://documentation.onesignal.com/docs/in-app-message-examples), you can easily create and customize a "soft-prompt" to ask users to grant your app permission to send push notifications. If the user selects “Allow”, the system’s push permission prompt appears.

You can read more about implementation [here](https://documentation.onesignal.com/docs/how-to-prompt-for-push-permissions-with-an-in-app-message).

Thanks!

**Comment by jennantilla** [comment]
Closing due to no response. Feel free to comment if still having issues!
