### ISSUE TITLE
Execution failed for task ':react-native-onesignal:javaPreCompileDebug'.

### ISSUE THREAD

**Issue by Zeeshan404** [OneSignal/react-native-onesignal#1431]
**Description:**
Hey everyone, One signal was working fine before. All of a sudden this error occurred. This error is related to work manager version conflict with one signal. How to fixed it ??

```
Could not resolve all files for configuration ':react-native-onesignal:debugCompileClasspath'.
-Failed to transform work-runtime-2.8.0-alpha04.aar (androidx.work:work-runtime:2.8.0-alpha04) to match attributes {artifactType=android-classes, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
-Execution failed for JetifyTransform: /Users/.gradle/caches/modules-2/files-2.1/androidx.work/work-runtime/2.8.0-alpha04/71391acb6ab93fd556755e7699ecb22e20fa38bf/work-runtime-2.8.0-alpha04.aar.
 -Failed to transform '/Users/.gradle/caches/modules-2/files-2.1/androidx.work/work-runtime/2.8.0-alpha04/71391acb6ab93fd556755e7699ecb22e20fa38bf/work-runtime-2.8.0-alpha04.aar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)
```

**Environment**
1. "react-native": "~0.63.4",
2.  "react-native-onesignal": "^4.1.1",

**Steps to Reproduce Issue:**
Was working before. All of a sudden this happen.

**Comment by emawby** [comment]
@Zeeshan404 When you say 'all of sudden' did your OneSignal version change or anything else about your build environment?

**Comment by Zeeshan404** [comment]
I didn't change any dependencies versions nor work manager versions. 
I solved it with 
[https://stackoverflow.com/questions/69037481/android-app-wont-build-the-mincompilesdk-31-specified-in-a-dependencys-an]

**Comment by emawby** [comment]
@Zeeshan404 Thank you for posting your fix!
