### ISSUE TITLE
One signal with Firebase analytics/perf

### ISSUE THREAD

**Issue by ElSeniorMikael** [OneSignal/react-native-onesignal#1433]
**Description:**

Here's my problem, when installing firebase with analytics and perf everything perfectly fine, some Events are logging.
I tried to use the debug view for testing purpose but on my real project it wouldn't trigger for some reason, so i made a fresh project with the same version of react native and firebase as my project. Everything was working even the debug view. so at this point i knew it was a conflict in my project.

Once i installed One signal package on the fresh project my debug view stopped working and also firebase/perf stopped working. i can see some 

`2022-09-16 08:07:15.023390-0400 rabaischocstesting[13120:159478] [boringssl] boringssl_metrics_log_metric_block_invoke(153) Failed to log metrics`

**Environment**
    "@react-native-firebase/analytics": "^14.11.0",
    "@react-native-firebase/app": "^14.11.0",
    "@react-native-firebase/perf": "^14.11.0",
    "react": "17.0.2",
    "react-native": "0.67.3",
    "react-native-onesignal": "^4.4.1"

**Steps to Reproduce Issue:**

1. Install firebase 
2. Install firebase analytics
3. install firebase perf
4. testing debugView (Working fine)
5. Install one signal (Firebase stop working)
<img width="619" alt="Screen Shot 2022-09-16 at 8 48 34 AM" src="https://user-images.githubusercontent.com/73765089/190642422-41ae6d8c-0aca-48c1-89a1-9a1852c9ac51.png">

**Comment by jennantilla** [comment]
Hi @ElSeniorMikael 

Thanks for your patience. Are you still having this issue? I have not been able to reproduce this. Would you be able to share the full log?

**Comment by jennantilla** [comment]
Closing due to no response.
