### ISSUE TITLE
React Native 0.70.1 with Firebase latest, cannot run pod update

### ISSUE THREAD

**Issue by Bayramito** [OneSignal/react-native-onesignal#1434]
**Description:**
on new project with `react-native 0.70.1` i cannot run `pod update` after upgrading `Firebase 9.6.0/latest` 
<img width="1162" alt="Ekran Resmi 2022-09-19 18 26 29" src="https://user-images.githubusercontent.com/44513402/191054993-673999bb-3928-4bb0-8466-773e98aa033b.png">

**Environment**

  1. "react-native-onesignal": "^4.4.1",
  2. npm

**Steps to Reproduce Issue:**

1. Install react native via `npx react-native init testproject`
2.. install  Firebase via `npm install --save @react-native-firebase/app`
3. install onesignal via `npm install --save react-native-onesignal`

**Comment by patricpfranca** [comment]
same problem. When I use `use_frameworks!` in podfile, this error appears.

```
target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end
```

**Enviroment**
"react": "18.0.0"
"react-native": "^0.69.5"
"@react-native-firebase/analytics": "^15.6.0"
"@react-native-firebase/app": "^15.6.0"

**Comment by Bayramito** [comment]
My quick solution was downgrade to 14.11 untill firebase gets stable

**Comment by fedenelli** [comment]
Hi Guys, I step into this same error and fixed it replacing

```
target 'OneSignalNotificationServiceExtension' do
    pod 'OneSignal', '>= 3.0', '< 4.0'
end
```

with:
```
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.11.1', '< 4.0'
end
```

in my Podfile. Hope this helps.

**Comment by jennantilla** [comment]
Hi everyone, thanks for your patience!

It sounds like @patricpfranca is using version 15.6.0 of Firebase. Is that the case with everyone else?

Please share the full podfile and the exact versions of firebase you are using. That will help us look into this.

**Comment by maoryadin** [comment]
> 

**Beginning with firebase-ios-sdk v9+ (react-native-firebase v15+) you must tell CocoaPods to use frameworks.**

So we cannot work with firebase and one signal, so I am choosing firebase for now.

**Comment by alwex** [comment]
The incompatibility with firebase comes from firebase forcing this in the `Podfile`
```
use_frameworks! :linkage => :static
```

To get one signal to work along with firebase latest version, you need to also add this to the OneSignal target:
```
target 'OneSignalNotificationServiceExtension' do
  use_frameworks! :linkage => :static
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end
```
then `npx pod-install`

Note that `use_frameworks!` alone will not work.

Tested with `react-native-firebase` `17.5.0`, `react-native` `0.71.8` and `react-native-onesignal` `4.5.1`.

Should maybe be added to the documentation as a lot of app are using firebase.
