### ISSUE TITLE
[Bug]: OneSignal is undefined and ERROR TypeError: undefined is not a function (near '..._reactNativeOnesignal.default.init...')

### ISSUE THREAD

**Issue by adamchenwei** [OneSignal/react-native-onesignal#1436]
### What happened?

I followed all the steps to setup OneSignal React Native SDK according to https://documentation.onesignal.com/v7.0/docs/react-native-sdk-setup

But I can't get it running. when I load the app with the example code in the setup guide, I got this error 

<img width="692" alt="Screen Shot 2022-09-29 at 4 45 51 PM" src="https://user-images.githubusercontent.com/4201698/193139128-883be5a5-2e4f-48de-a034-e0d84058c9b7.png">

### Steps to reproduce?

```Markdown
1. follow https://documentation.onesignal.com/v7.0/docs/react-native-sdk-setup setup iOS & Android onesignal configs
2. start an app with ios emulator
3. observe error on ios emulator

node v 14.19.3
react-native-cli: 2.0.1
react-native: 0.68.2

```

### What did you expect to happen?

no error

### React Native OneSignal SDK version

4.4.1

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Relevant log output

```Shell
ERROR  TypeError: undefined is not a function (near '..._reactNativeOnesignal.default.init...')

This error is located at:
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in rnPatientPortalUi(RootComponent)
 ERROR  TypeError: undefined is not a function (near '..._reactNativeOnesignal.default.init...')

This error is located at:
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in rnPatientPortalUi(RootComponent)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @adamchenwei  I see you are on our latest react-native SDK version 4.4.1 but the setup guide you linked is from an older release.

Can you please confirm that you are following the [setup steps](https://documentation.onesignal.com/docs/react-native-sdk-setup) for our current major release?

Thanks!

**Comment by jennantilla** [comment]
Closing due to no response.
