### ISSUE TITLE
[question]: Confirm that disablePush actually worked

### ISSUE THREAD

**Issue by LazyAfternoons** [OneSignal/react-native-onesignal#1437]
### How can we help?

Hello, I'm currently implementing notification in my application via OneSignal for the first time. 
Whenever the user logs in I call disablePush(false) and when the user logs out I call disablePush(true).
I noticed that it doesn't always work for some reasons. I'm still able to receive notification even after logging out and they still show as enable in my OneSignal dashboard. 
Sometimes it does, sometimes it doesn't. 
Is there any way to ensure that the value has been updated? 
Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
@LazyAfternoons, just to clarify, you are calling `disablePush(false)` on logout?

Passing `false` to this method opts users back into notifications. If you wish to opt out users from receiving notifications through OneSignal, you should call this method with `true` on logout.

More about this method [here](https://documentation.onesignal.com/docs/sdk-reference#disablepush-method).

**Comment by LazyAfternoons** [comment]
> @LazyAfternoons, just to clarify, you are calling `disablePush(false)` on logout?
> 
> Passing `false` to this method opts users back into notifications. If you wish to opt out users from receiving notifications through OneSignal, you should call this method with `true` on logout.
> 
> More about this method [here](https://documentation.onesignal.com/docs/sdk-reference#disablepush-method).

Sorry about that, I meant exactly what you said, fixed in the op. The thing is, there's not way to wait for the update to happen or to check that, right?

**Comment by jennantilla** [comment]
You can use the [`onOSSubscriptionChanged` method](https://documentation.onesignal.com/docs/sdk-reference#handling-subscription-state-changes) will be fired on the passed-in object when a notification subscription property changes, including when `OneSignal.disablePush` is called. Let us know if that helps!

**Comment by LazyAfternoons** [comment]
> You can use the [`onOSSubscriptionChanged` method](https://documentation.onesignal.com/docs/sdk-reference#handling-subscription-state-changes) will be fired on the passed-in object when a notification subscription property changes, including when `OneSignal.disablePush` is called. Let us know if that helps!

Thank you!
