### ISSUE TITLE
[Bug]: No know class method for selector 'didReceiveNotificationExtensionRequest:withMutableNotificationContent:withContentHandler:

### ISSUE THREAD

**Issue by betocode** [OneSignal/react-native-onesignal#1438]
### What happened?

while archiving my react native project (RN 0.64.0), I got the following Error from Xcode
"No know class method for selector 'didReceiveNotificationExtensionRequest:withMutableNotificationContent:withContentHandler:'"

at RCTOneSignalExtensionService

### Steps to reproduce?

```Markdown
Build RN Project 0.64.0 with one signal 4.4.1 
deployment info iOS 10
```

### What did you expect to happen?

RN app to archive on XCODE

### React Native OneSignal SDK version

4.4.1

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @betocode

Thanks for your patience. Are you still having issues? Can you please provide some additional details about how you've [set up your Notification Service Extension](https://documentation.onesignal.com/docs/react-native-sdk-setup#step-4-install-for-ios-using-cocoapods-for-ios-apps)?

This guide on [debugging the NSE](https://documentation.onesignal.com/docs/troubleshooting-ios#debug-the-notification-service-extension) may be helpful as well.

**Comment by jennantilla** [comment]
Closing due to no response.
