### ISSUE TITLE
You uploaded an APK or Android App Bundle which has an activity, activity alias, service or broadcast receiver with intent filter, but without the 'android:exported' property set. This file can't be installed on Android 12 or higher. See: developer.android.com/about/versions/12/behavior-changes-12#exported Release details[question]: 

### ISSUE THREAD

**Issue by jayanit** [OneSignal/react-native-onesignal#1439]
### How can we help?

   <application
      android:usesCleartextTraffic="true" 
      android:animateLayoutChanges="true"
      android:requestLegacyExternalStorage="true"
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:exported="true"
      android:theme="@style/AppTheme">

 <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:exported="true"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
            <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
        </intent-filter>
         
      </activity>
  <receiver
        android:name="com.google.android.gms.gcm.GcmReceiver"
        android:exported="false"
        android:permission="com.google.android.c2dm.permission.SEND" >
        <intent-filter>
            <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            <category android:name="${applicationId}" />
        </intent-filter>
    </receiver>
    </application>

**Comment by jennantilla** [comment]
Hi @jayanit which version of our react-native SDK are you using? Can you please update to our [latest release](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.4.1)? Thanks!

**Comment by jennantilla** [comment]
Closing due to no response.
