### ISSUE TITLE
[Question] change app-id on JS side

### ISSUE THREAD

**Issue by DCKT** [OneSignal/react-native-onesignal#144]
Hello,

In my app, I have the possibility to switch between environments so I have to switch `app-id`.
Is there a way to do that ? 

Thanks for your help.

**Comment by avishayil** [comment]
I think we can implement something like this, by using build variants on iOS and Android.
Like CodePush does:
https://github.com/Microsoft/react-native-code-push#multi-deployment-testing
@jkasten2 what's your opinion on this?

**Comment by jkasten2** [comment]
@DCKT @avishayil Yes, I recommend setting these values in gradle. See the below issue for an example.
https://github.com/OneSignal/OneSignal-Android-SDK/issues/9

**Comment by DCKT** [comment]
Hello @avishayil @jkasten2 

In fact, I would like to have the ability of setting the `id` in the JavaScript (after method call).

**Comment by avishayil** [comment]
@DCKT unfortunately, you won't be able to do it on the JS side.
