### ISSUE TITLE
[question]: Any workaround to QUERY_ALL_PACKAGES

### ISSUE THREAD

**Issue by haveamission** [OneSignal/react-native-onesignal#1441]
### How can we help?

Google keeps rejecting my app from the Play Store for having QUERY_ALL_PACKAGES based on OneSignal. Is there any workaround? I thought maybe updating the library would remove this requirement, but it did not.

Alternatively, is there any documentation anywhere explaining this? Google is asking for the documentation - I've provided the note in the AndroidManifest file, but they said that they want official documentation on a web page.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @haveamission,
Thanks for reporting. Can you double check where `QUERY_ALL_PACKAGES` is coming from? We don't have this permission in our SDK.

**Comment by haveamission** [comment]
@nan-li Hrm, weird. Because this is inside my AndroidManifest:

`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" /> <!-- Create a unique permission for your app and use it so only your app can receive your OneSignal messages. -->`

Was this permission removed from the library at some point recently?

**Comment by nan-li** [comment]
It comes from [here](https://github.com/OneSignal/OneSignal-Android-SDK/blob/c50c3bed4120f7d894ccd7e59f8678301cff6bd6/OneSignalSDK/onesignal/src/release/AndroidManifest.xml#L4) but there is no `QUERY_ALL_PACKAGES`. Looking back the last 6 years, that Manifest has not had `QUERY_ALL_PACKAGES`. What version of react-native-onesignal are you using?

**Comment by haveamission** [comment]
@nan-li I am using:

"react-native-onesignal": "^4.4.1"

I do have this in my /app/build.gradle:

```
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.10, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
```

**Comment by haveamission** [comment]
Also I am not the only person getting this particular line of code in my AndroidManifest:

https://stackoverflow.com/questions/70757094/this-permision-android-permission-query-all-packages-was-automatically-added-t

> I get things like this `android/app/build/intermediates/merged_manifest/debug/AndroidManifest.xml:    <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" /> <!-- Create a unique permission for your app and use it so only your app can receive your OneSignal messages. -->` what does that mean ? – 
> Hugo
>  Aug 23 at 7:55

**Comment by haveamission** [comment]
it is specifically showing up in the intermediate folder during the build process

**Comment by nan-li** [comment]
Hi @haveamission,

It looks like some other people are seeing this too, but they likely have OneSignal in addition to the actual dependency that is injecting  `QUERY_ALL_PACKAGES`. It just happens that this permission is injected right next to a comment from the OneSignal SDK.

I see mention of `react-native-inappbrowser` as a cause. Are you using this?

**Comment by haveamission** [comment]
I am, though the newest version doesn't have the same problem (they removed QUERY_ALL_PACKAGES). I had actually updated react-native-inappbrowser, and **then** got the comment about OneSignal in my manifest. So I definitely think it's some bug with OneSignal that just requires the stars to align in all the right ways. But the comment is definitely in regards to OneSignal - it specifically says the permission is necessary for OneSignal to operate.

I ultimately fixed it, though I can't entirely tell **how** I fixed it. I basically updated a bunch of APIs and somehow that made it compile without the permission.

So my best guess is that some older API version of something is causing some old version of OneSignal that requires the permission to be pulled in.

**Comment by nan-li** [comment]
Happy to hear this has been resolved for you @haveamission,

I am still doubtful this was a permission injected by the OneSignal SDK. You shared this is in your Manifest:
`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" /> <!-- Create a unique permission for your app and use it so only your app can receive your OneSignal messages. -->`. I see this comment comes after the `QUERY_ALL_PACKAGES` permission.

This OneSignal comment here[ is actually the **first line** of one of our permissions](https://github.com/OneSignal/OneSignal-Android-SDK/blob/c50c3bed4120f7d894ccd7e59f8678301cff6bd6/OneSignalSDK/onesignal/src/release/AndroidManifest.xml#L4):
```xml    
    <!-- Create a unique permission for your app and use it so only your app can receive your OneSignal messages. -->
    <permission android:name="${applicationId}.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />
```

This leads me to think the `QUERY_ALL_PACKAGES` permission can be from another library, and the OneSignal comment is the start of a OneSignal permission.
