### ISSUE TITLE
[Bug]: react-native-onesignal 4 setNotificationWillShowInForegroundHandler() is not called on silent (data) push notification

### ISSUE THREAD

**Issue by pavlo-o-savchuk** [OneSignal/react-native-onesignal#1442]
### What happened?

**Problem**
I can't get data from the silent push notification object inside the application.

**Description**
I am setting up silent push notifications to deliver server updates to the device when the app is opened. I do not want to show push notifications to the user anywhere.  
After following the setup guides I ended up that in the device logs("adb logcat") I do receive the push notification object, however, there is no way to retrieve the data I sent on the device. In a previous version, it was onReceived() method that is not present in the current last version 4*.

Package  "react-native-onesignal": "^4.4.1"
Device    Android and Android emulator. 

**Steps:** (app_id and authorization keys are changed)
1. This is working as expected. This is a script I use to send push notifications. When the `contents` object is passed, pushes are delivered and displayed as expected. The method setNotificationWillShowInForegroundHandler() is invoked and it is possible to retrieve the data. This is how it should work. 

```
const options = {
    method: 'POST',
    headers: {
      accept: 'application/json',
      Authorization: 'Basic ZTRiZjAwNmYtNWQ1NS00ODc2LWJmNTItMTk2ZWDYwYWU0',
      'content-type': 'application/json'
    },
    body: JSON.stringify({
      app_id: "dd3eeba5-8126-43ba-9d17-7ce9c01a0758",
      "filters": [
        {"field": "tag", "key": "maguru_user_id", "relation": "=", "value": "674"},
        {"field": "country", "relation": "=", "value": "PT"}
      ],
      contents: {en: 'Unanswered call'},
      isAndroid:true,
      data: {"testParam": "testData"}
    })
  };


  fetch('https://onesignal.com/api/v1/notifications', options)
    .then(response => response.json())
    .then(response => console.log(response))
    .catch(err => console.error(err));

```
2. This is not working. This is a script I use to send SILENT push notifications. The method setNotificationWillShowInForegroundHandler() is not invoked and it is NOT possible to retrieve the data. 
```
const options = {
    method: 'POST',
    headers: {
      accept: 'application/json',
      Authorization: 'Basic ZTRiZjAwNmYtNWQ1NS00ODc2LWJmNTItMTk2ZWDYwYWU0',
      'content-type': 'application/json'
    },
    body: JSON.stringify({
      app_id: "dd3eeba5-8126-43ba-9d17-7ce9c01a0758",
      "filters": [
        {"field": "tag", "key": "maguru_user_id", "relation": "=", "value": "674"},
        {"field": "country", "relation": "=", "value": "PT"}
      ],
      content_available: true,
      isAndroid:true,
      data: {"testParam": "testData"}
    })
  };

fetch('https://onesignal.com/api/v1/notifications', options)
    .then(response => response.json())
    .then(response => console.log(response))
    .catch(err => console.error(err));
```

The main difference between the two scripts is that in #1 I pass "contents" as a param, and in the second one I do not pass the "contents", but instead, I pass "content_available: true"

Note: NotificationServiceExtension class is implemented according to the [guideline](https://documentation.onesignal.com/docs/service-extensions#android-notification-service-extension)

### Steps to reproduce?

```Markdown
1. Install "react-native-onesignal": "^4.4.1" on react-native project.
2. Setup onesignal methods for React Native.
3. Setup Silent push notification.
4. Deploy the app on the device or on the emulator.
5. Send silent push notifications.
```

### What did you expect to happen?

1. I expect the setNotificationWillShowInForegroundHandler to be called when the app is in focus.
2. I expect the notification to be hidden when the app is in the background, so I do not receive any mentions of new push notifications. 

### React Native OneSignal SDK version

4.4.1

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
10-19 10:55:15.484  6884  7205 I OneSignalExample: Received Notification Data: {"testParam":"testData"}
10-19 10:55:15.484  6884  7205 D OneSignal: Running destroyTimeout with runnable: com.onesignal.OSNotificationReceivedEvent$1@e0a4f21
10-19 10:55:15.485  6884  7205 D OneSignal: Saving Notification job: OSNotificationGenerationJob{jsonPayload={"google.delivered_priority":"normal","google.sent_time":1666173314713,"google.ttl":259200,"google.original_priority":"normal","custom":"{\"a\":{\"testParam\":\"testData\"},\"i\":\"9f6e85dc-bd91-4856-880b-d82ee1f09dd7\"}","from":"413478568955","google.message_id":"0:1666173314735031%be654685f9fd7ecd","google.c.sender.id":"413478568955"}, isRestoring=false, isNotificationToDisplay=false, shownTimeStamp=1666173315, overriddenBodyFromExtender=null, overriddenTitleFromExtender=null, overriddenSound=null, overriddenFlags=null, orgFlags=null, orgSound=null, notification=OSNotification{notificationExtender=null, groupedNotifications=null, androidNotificationId=911260800, notificationId='9f6e85dc-bd91-4856-880b-d82ee1f09dd7', templateName='', templateId='', title='null', body='null', additionalData={"testParam":"testData"}, smallIcon='null', largeIcon='null', bigPicture='null', smallIconAccentColor='null', launchURL='null', sound='null', ledColor='null', lockScreenVisibility=1, groupKey='null', groupMessage='null', actionButtons=null, fromProjectNumber='413478568955', backgroundImageLayout=null, collapseId='null', priority=0, rawPayload='{"google.delivered_priority":"normal","google.sent_time":1666173314713,"google.ttl":259200,"google.original_priority":"normal","custom":"{\"a\":{\"testParam\":\"testData\"},\"i\":\"9f6e85dc-bd91-4856-880b-d82ee1f09dd7\"}","from":"413478568955","google.message_id":"0:1666173314735031%be654685f9fd7ecd","google.c.sender.id":"413478568955"}'}}
10-19 10:55:15.489  6884  7205 D OneSignal: Notification saved values: full_data={"google.delivered_priority":"normal","google.sent_time":1666173314713,"google.ttl":259200,"google.original_priority":"normal","custom":"{\"a\":{\"testParam\":\"testData\"},\"i\":\"9f6e85dc-bd91-4856-880b-d82ee1f09dd7\"}","from":"413478568955","google.message_id":"0:1666173314735031%be654685f9fd7ecd","google.c.sender.id":"413478568955"} notification_id=9f6e85dc-bd91-4856-880b-d82ee1f09dd7 opened=1 expire_time=1666432514
10-19 10:55:15.490  6884  7205 D OneSignal: Running destroyTimeout with runnable: com.onesignal.OSNotificationOpenedResult$1@305ef46
10-19 10:55:15.490  6884  7205 D OneSignal: Running startTimeout with timeout: 5000 and runnable: com.onesignal.OSNotificationOpenedResult$1@305ef46
10-19 10:55:15.491  6884  6934 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=eaa53d53-1281-4069-8f04-44207b9f45bd, tags={ com.onesignal.OSNotificationWorkManager$NotificationWorker } ]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @pavlo-o-savchuk 

I see you mentioned that you implemented the Notification Service Extension following this [Android guide](https://documentation.onesignal.com/docs/service-extensions#android-notification-service-extension).

To set up Service Extensions to get data in React Native, you will need to use React Native Native Modules in this case. See our guide on [RN Native Module Setup](https://documentation.onesignal.com/docs/rn-android-native-module-setup-for-notification-service-extension).

Let us know if that helps!

**Comment by pavlo-o-savchuk** [comment]
ok, @jennantilla if possible add this for the future development plans, to get the method in the package by default. 
I will look into React Native Native Modules

**Comment by jennantilla** [comment]
Sure thing @pavlo-o-savchuk--I'll pass this request along to be considered for future development!
