### ISSUE TITLE
[Bug]: Android receives Duplicate Notifications when title is added

### ISSUE THREAD

**Issue by cassde** [OneSignal/react-native-onesignal#1444]
### How can we help?

When we send push notifications with Title, ios receives 1 notification, but android receives 2 notifications (one with just that title, 2nd with the message). When we send push notification without adding a title, android also receives just 1 notification, What maybe the reason for such behavior?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cassde** [comment]
@nan-li can you please advise? this started happening randomly and only when a title is included in the message, after doing some research I think it maybe because oneSignal sends titles as notification which is handled by firebase as a separate notification?

**Comment by jennantilla** [comment]
Hi @cassde 

Thanks for your patience! When did you notice this begin? Does it happen with every notification, or only sporadically?

Are you using any other notification SDKs in your app? We had a [prior report](https://github.com/OneSignal/react-native-onesignal/issues/1406) of this occurring when also using react-native-notifications.

**Comment by gpahal** [comment]
Any resolution to this bug? Still getting duplicate notifications when the app is in the background. I'm using `v4.5.0` of the react native SDK

**Comment by nympheastudio** [comment]
for information, bug still exist on version 4.5.1

**Comment by nan-li** [comment]
Hi @gpahal, @nympheastudio, 
Thanks for asking, this isn't a known bug with the `react-native-onesignal` SDK. Are you also using `react-native-notifications` or another notification library?

**Comment by Kishore0297** [comment]
i am using react-native-onesignal and  react-native-notifications. getting duplicate notifications.
