### ISSUE TITLE
[Bug]: IOS Push Certificate generated by provisionator has wrong password

### ISSUE THREAD

**Issue by notSeiti** [OneSignal/react-native-onesignal#1445]
### What happened?

I generated a push certificate for IOS using the provisionator (https://onesignal.com/provisionator) and got my p12 certificate.
Tried to upload to onesignal but got an error saying the password is wrong.

### Steps to reproduce?

```Markdown
Go to provisionator (https://onesignal.com/provisionator).
Generate a p12 certificate.
Upload to onesignal.
```

### What did you expect to happen?

The p12 certificate password should work.

### React Native OneSignal SDK version

Release 4.4.1

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @notSeiti

If you attempt to generate the certificate again using the provisionator, do you still get an invalid password?

If you need to generate more than one certificate at a time, you can open a new incognito browser window for each one, which should prevent any issues.

Let us know if that helps!

**Comment by notSeiti** [comment]
Thanks for the reply. I kept generating new certificates until one had a working password. Didn't use incognito mode nor did anything different. I guess the solution for now is to just keep trying until one works.
Since I got my problem solved somehow, I will close this issue.
