### ISSUE TITLE
[Bug]: android:exported needs to be explicitly specified for element <activity#com.onesignal.NotificationOpenedActivityHMS>

### ISSUE THREAD

**Issue by nahidmbstu** [OneSignal/react-native-onesignal#1448]
### What happened?

Error: android:exported needs to be explicitly specified for element <activity#com.onesignal.NotificationOpenedActivityHMS>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details. Conveyance_Admin.app debug manifest, line 77 Error: android:exported needs to be explicitly specified for element <receiver#com.onesignal.GcmBroadcastReceiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details. Conveyance_Admin.app debug manifest, line 56 Error: android:exported needs to be explicitly specified for element <receiver#com.onesignal.BootUpReceiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details. Conveyance_Admin.app debug manifest, line 108 Error: android:exported needs to be explicitly specified for element <receiver#com.onesignal.UpgradeReceiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details. Conveyance_Admin.app debug manifest, line 114

### Steps to reproduce?

```Markdown
npx react-native run-android
```

### What did you expect to happen?

npx react-native run-android

### React Native OneSignal SDK version

3.7.1

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SeanDunford** [comment]
@nahidmbstu I believe you need to upgrade to `4.x`

https://documentation.onesignal.com/docs/step-by-step-react-native-3x-to-400-upgrade-guide

**Comment by jkasten2** [comment]
@nahidmbstu, yes @SeanDunford is correct here, please follow the [upgrade guide to 4.x.x](https://documentation.onesignal.com/docs/step-by-step-react-native-3x-to-400-upgrade-guide). If you run into issues and can't find a solution feel free to open a new issue.

**Comment by SaadBinWaheed-empglabs** [comment]
Upgrading to 4.0.x didn't fix the issue but updating to the latest 4.5.0 fixed it.
