### ISSUE TITLE
library not found for -lPods

### ISSUE THREAD

**Issue by DCKT** [OneSignal/react-native-onesignal#145]
Hi,

I followed the iOS tutorial to setup the plugin but I have this error `ld: library not found for -lPods-test`.
Another strange things is, I have `libPods-test.a` in red in the **Frameworks** folder. I don't really know pods, I changed the `Framework Search Paths` to use `$(inherited)` for warning reason.

Also the `Header Search Path` is correctly set to : `$(SRCROOT)/../node_modules/react-native-onesignal/ios/RCTOneSignal` without recursion.

Thanks for your help.

**Comment by avishayil** [comment]
Can you please provide a repo with this issue we can take a look at?

**Comment by DCKT** [comment]
Hi @avishayil 

Thanks for your reactivity, I tried on clean project and it works properly ! 
There must be a configuration problem on the other project.

Note: I will update this issue when I found the solution.

Thanks !

**Comment by DCKT** [comment]
A little update, I'm getting this error now : 
<img width="439" alt="capture d ecran 2017-01-19 a 10 34 06" src="https://cloud.githubusercontent.com/assets/1548421/22101236/e4173d50-de32-11e6-9b40-0218a955acdd.png">

After some research, I found issue about the same things but all are correctly set in `Link Binary with Libraries` and `OneSignal.framework` is also imported in the **Frameworks** folder.

Am I missing something ?

EDIT : I have this in the `libraries` folder, I think it's not normal isn't it ?
<img width="230" alt="capture d ecran 2017-01-19 a 11 38 03" src="https://cloud.githubusercontent.com/assets/1548421/22103557/e425d154-de3b-11e6-8d2a-f388faa50657.png">

**Comment by avishayil** [comment]
@DCKT I can't really tell without looking on the repo closely. Can you provide a repo here or privately with the reproducible issue?

**Comment by DCKT** [comment]
@avishayil I'm sorry, I'm unable to share the repo. And when I create a new project, I don't have any problem so it's obvioulsy a bug in my project configuration with other plugins.

EDIT: I finally add the `libRCTOneSignal.a` who was missing . It compiles ! But my app shutdown with this error : 
```
2017-01-19 18:45:32.670 [info][tid:main][RCTBatchedBridge.m:74] Initializing <RCTBatchedBridge: 0x17e20f70> (parent: <RCTBridge: 0x17e2aac0>, executor: RCTJSCExecutor)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

EDIT 2 : this runtime error was due to bad package version (1.2.1), I upgrade to 2.0.0 and it works !

**Comment by avishayil** [comment]
Do you mind if i'll TeamViewer your computer? I would really like to help you on this.
