### ISSUE TITLE
[question][Android]: Kill app and reopen, setNotificationWillShowInForegroundHandler not called when has new notification

### ISSUE THREAD

**Issue by bakhiem** [OneSignal/react-native-onesignal#1450]
### How can we help?

On android, when I kill app, and reopen it right away, setNotificationWillShowInForegroundHandler not called when has new notification. OneSignal log show:
`Waiting for remote params. Moving onAppLostFocus() operation to a pending task queue.`
And
`App is in background, show notification`

And after 2 min, it work again:
<img width="746" alt="image" src="https://user-images.githubusercontent.com/29191068/200502725-400aa882-baa0-4af4-b24e-58c41aad1ea4.png">

How can i make it run right after opening the app, without having to wait more than 2 minutes?

It happen on Onesignal ver 4.3.4 & RN 0.65.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adilkhan2163** [comment]
same here any solution?

**Comment by adilkhan2163** [comment]
i am facing almost same issue with setNotificationWillShowInForegroundHandler some time it fired and some time not,
but initially it is not working but when I restart the app then it is fired, but in both cases I got notification on notification bar, and no listener working even setNotificationOpenedHandler is also not working.
and I got this data from getdevicestate 
{"hasNotificationPermission": true, "isEmailSubscribed": false, "isPushDisabled": false, "isSMSSubscribed": false, "isSubscribed": true, "pushToken": "my token show", "userId": "my id "}

**Comment by adilkhan2163** [comment]
i have tested it on latest and previous version above 4.+.+ and my react native version is 0.63.5

**Comment by jkasten2** [comment]
@adilkhan2163 Can you share your code, where you setup OneSignal and your call to `setNotificationWillShowInForegroundHandler`, including your callback code.

Can you also enabled OneSignal VERBOSE logging and share your full logcat so all the events can be investigated?

**Comment by harshalrandhe** [comment]
Same issue here : After the app was installed and opened for the first time setNotificationWillShowInForegroundHandler function is not working The notification is received in the notification bar instead of the handler, but when you kill the app and restart it it start working

**Comment by jennantilla** [comment]
Hello everyone, since it has been quite some time since this issue has seen any responses, I'm going to close as stale. If anyone is still experiencing issues, please @ mention me and we will be happy to give it fresh eyes. Thanks!
