### ISSUE TITLE
[question]: Handle notification click and choose to open or not the browser

### ISSUE THREAD

**Issue by MatteoGauthier** [OneSignal/react-native-onesignal#1452]
### How can we help?

Hey ! How can I handle notification click ? Perform action based on the notification payload and block the opening of `launchUrl`. Can someone help me ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@MatteoGauthier There currently isn't an option to suppress it in the SDK. We will consider it in the future.

As a work around you could define a [Custom Action ID](https://documentation.onesignal.com/docs/iam-click-actions) and use that to open your URL in your app from the [OneSignal In-App Message Click Handler](https://documentation.onesignal.com/docs/iam-sdk-methods#in-app-message-click-handler-1)

**Comment by MatteoGauthier** [comment]
> @MatteoGauthier There currently isn't an option to suppress it in the SDK. We will consider it in the future.
> 
> As a work around you could define a [Custom Action ID](https://documentation.onesignal.com/docs/iam-click-actions) and use that to open your URL in your app from the [OneSignal In-App Message Click Handler](https://documentation.onesignal.com/docs/iam-sdk-methods#in-app-message-click-handler-1)

Thanks for your reply @jkasten2, I will try with Custom Action Id, as a workaround I use _additional data_ in order to prevent native link opening
