### ISSUE TITLE
[Bug]: External id not updating

### ISSUE THREAD

**Issue by sercaneryaz** [OneSignal/react-native-onesignal#1454]
### What happened?

Hello,

in my android/ios app im using onesignal for notification.

if user lets notifications im updating external id

but when i check onesignal all users tab it says user agreed for push but theres no externalid on it.

onesignal panel:

![image](https://user-images.githubusercontent.com/40642548/202902952-2240c651-eec7-4d42-9bc8-965974fac5eb.png)

my code below:

```
async function OneSignalHandle() {
        OneSignal.setLogLevel(6, 0);
        OneSignal.setAppId("*****************");
        OneSignal.promptForPushNotificationsWithUserResponse(response => {
            if (!response) {
                Alert.alert("Warning", "You disabled notifications.")
            }
            else {
                OneSignal.setExternalUserId(dbuser.uid);

            }
        });

    }
```

### Steps to reproduce?

```Markdown
updated to 4.3.11
```

### What did you expect to happen?

i expect to update external id

### React Native OneSignal SDK version

4.3.11

### Which platform(s) are affected?

- [x] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Svarto** [comment]
I have a similar issue on Android only. Did you find a solution?

**Comment by Svarto** [comment]
@nan-li I saw you replying to a similar issue in August, could you please help here? I am happy to provide any additional information to help with the debugging.

**Comment by sercaneryaz** [comment]
i found the problem. Its about react coding fault. 

when i changed code like below it worked. you cant use this method inside on response
```
async function OneSignalHandle() {
        OneSignal.setLogLevel(6, 0);
        OneSignal.setAppId("*****************");
        OneSignal.setExternalUserId(dbuser.uid);

        OneSignal.promptForPushNotificationsWithUserResponse(response => {
            if (!response) {
                Alert.alert("Warning", "You disabled notifications.")
            }
        });

    }
```
