### ISSUE TITLE
[Bug]: Notifications are not appearing when the app is closed for more than 5 mins.

### ISSUE THREAD

**Issue by yugalkishoregoyal** [OneSignal/react-native-onesignal#1455]
### What happened?

Notifications are not visible when the app is closed for more than 5 mins on the devices mentioned below. It seems to work fine when the app is active, in the background, and closed less than 5 mins ago.

Devices I'm facing this issue on -
Vivo S1 (Android 11)
Vivo (Android 12)

When I'm checking the logs using android studio, it is logging the below error immediately after the notification was sent from the server (but not showing that notification)
Error: W/GCM: broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.app.identifier (has extras) }
Looks like the Firebase service is not responding to the received notification.

Note - The notification was sent using Urgent priority.

### Steps to reproduce?

```Markdown
1. Install the latest version of react-native-onesignal
2. Install the app on the device and make sure to close and wait for 5 mins
3. Send the push notification from onesignal dashboard.
```

### What did you expect to happen?

Notifications must work normally even after closing the app.

### React Native OneSignal SDK version

Release 4.4.1

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@yugalkishoregoyal Thanks for the details, given the following error message you uncovered in the logcat on those devices this means your app was put in to the "force stop" state. Therefore all broadcast intents (including the push) are not delivered to your app:
```
Error: W/GCM: broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.app.identifier (has extras) }
```

I high suspect this is [an issue specific to Vivo](https://dontkillmyapp.com/vivo), maybe to specific region variants. Can you test your app on other devices to see if you notice the same behavior to confirm this? The Android Studio emulator is an option test as well.

**Comment by jennantilla** [comment]
Closing issue due to no response.

Noting that we have an updated major release SDK with many new enhancements and improvementsPlease refer to our [migration guide](https://github.com/OneSignal/react-native-onesignal/blob/major_release_5.0.0/MIGRATION_GUIDE.md) to upgrade!
