### ISSUE TITLE
[question]:  React Native OneSignal 3.9.3 not receiving push notifications after updating to Android 12

### ISSUE THREAD

**Issue by gloriamaris** [OneSignal/react-native-onesignal#1458]
### How can we help?

I recently updated my React Native app to compile to Android 12.

in **build.gradle**

```
targetSdkVersion = 31
compileSdkVersion = 31
```

I have managed to create a workaround for making React Native OneSignal 3.9.3 compatible with Android 12, and in-app notifications is working as expected.

However, I **do not receive any push notifications.**

Here is the code I added in **AndroidManifest.xml**

```
<receiver
    android:exported="false"
    android:name="com.onesignal.GcmBroadcastReceiver"
    android:permission="com.google.android.c2dm.permission.SEND"
    tools:replace="android:exported">
    <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        <category android:name="com.myapp" />
    </intent-filter>
</receiver>       

<receiver
    android:name="com.onesignal.NotificationOpenedReceiver"
    android:exported="false"
    tools:replace="android:exported">
</receiver>

<receiver
    android:name="com.onesignal.BootUpReceiver"
    android:exported="true"
    tools:replace="android:exported">
</receiver>

<receiver
    android:name="com.onesignal.UpgradeReceiver"
    android:exported="true"
    tools:replace="android:exported">
</receiver>
```

Did I miss anything? I can't upgrade to OneSignal 4.x at the moment since there are breaking changes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@gloriamaris The 3.x.x branch of this SDK isn't activity being updated, no patches are planned. Please update to a 4.x.x version following this migration guide:
https://documentation.onesignal.com/docs/step-by-step-react-native-3x-to-400-upgrade-guide

If you run into issues upgrading and aren't able to find any solutions from previous issues please open a new issue and we can take a look.

**Comment by adilkhan2163** [comment]
i have added all these <recivers in android manifest file but still not working on android 12. java.util.concurrent.ExecutionException: com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_FAILED_USER_RESTRICTED: Invalid apk
Please guide me how you solve this issue

**Comment by adilkhan2163** [comment]
> @gloriamaris The 3.x.x branch of this SDK isn't activity being updated, no patches are planned. Please update to a 4.x.x version following this migration guide: https://documentation.onesignal.com/docs/step-by-step-react-native-3x-to-400-upgrade-guide
> 
> If you run into issues upgrading and aren't able to find any solutions from previous issues please open a new issue and we can take a look.

why are you guys not updating your previous version, especially 3.9.1? we have implemented lot of logic at native side and OSRemoteNotificationReceivedHandler is not working as it should be. So please update previous version at least for android 12. so that our previous apps work smoothly. thanks

**Comment by jkasten2** [comment]
> i have added all these <recivers in android manifest file but still not working on android 12. java.util.concurrent.ExecutionException: com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_FAILED_USER_RESTRICTED: Invalid apk
Please guide me how you solve this issue

This is only one of the Android 12 compatibility fixes in the 4.x.x versions of OneSignal, there are a number of others, such as notification open handling.

> why are you guys not updating your previous version, especially 3.9.1?

We only support previous major version for a limited time, [4.0.0](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.0.0) was released 2021-06-06 so we are no longer updating 3.x.x.

> we have implemented lot of logic at native side and OSRemoteNotificationReceivedHandler is not working as it should be. So please update previous version at least for android 12. so that our previous apps work smoothly. thanks

There are no known issues with [`OSRemoteNotificationReceivedHandler`](https://documentation.onesignal.com/docs/service-extensions#android-notification-service-extension). Can you open a new issue for this specifically and we can help you find a solution. Feel free to link it here as well.
