### ISSUE TITLE
[Bug]: Library not loaded: @rpath/OneSignalCore.framework/OneSignalCore

### ISSUE THREAD

**Issue by ElChawich** [OneSignal/react-native-onesignal#1459]
### What happened?

After updating to version 4.5.0 the app builds successfully. But after the app tries to open, it crashes immediately giving this error:  
<img width="998" alt="Screenshot 2022-12-01 at 6 14 30 AM" src="https://user-images.githubusercontent.com/55316641/205038814-7a65323e-50c1-48ed-a60a-68faae9e8e25.png">

Also when running npx pod-install i get this in the logs but it proceeds to install successfully:
```
[!] CocoaPods could not find compatible versions for pod "OneSignalXCFramework":
  In snapshot (Podfile.lock):
    OneSignalXCFramework (< 4.0, = 3.11.2, >= 3.0)

  In Podfile:
    OneSignalXCFramework (< 4.0, >= 3.0)

    react-native-onesignal (from `../node_modules/react-native-onesignal`) was resolved to 4.5.0, which depends on
      OneSignalXCFramework (= 3.12.3)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `OneSignalXCFramework` inside your development pod `react-native-onesignal`.
   You should run `pod update OneSignalXCFramework` to apply changes you've made.
Couldn't install: OneSignalXCFramework. Updating the Pods project and trying again...
```

### Steps to reproduce?

```Markdown
1. update to 4.5.0 version
2. build the app and try opening it.
```

### What did you expect to happen?

for the app to open and work normally

### React Native OneSignal SDK version

4.5.0

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ymc-thzi** [comment]
Having the same problem. Even when I have done a `$ pod repo update` afterwards and the pod install succeeded. 
XCode crashes with the same error.
My workaround is to set the version fixed to 4.4.1 for now... 🤷🏻‍♂️ 

`Library not loaded: @rpath/OneSignalCore.framework/OneSignalCore`

**Comment by fhboswell** [comment]
Hello, @ElChawich & @ymc-thzi 
Please try running
`pod update OneSignalXCFramework`

If you are still having issues please share the version of `OneSignalXCFramework` in your `PodFile.lock`

**Comment by ElChawich** [comment]
Hello @fhboswell,
pod update command was automatically ran from the beginning and the `OneSignalXCFramework` version in `Podfile.lock` became 3.12.3

**Comment by fhboswell** [comment]
Thank you for the information @ElChawich,
What version of CocoaPods are you using?

**Comment by maoryadin** [comment]
Same error!

**Comment by ymc-thzi** [comment]
@ElChawich thanks for answering. So I executed `pod update OneSignalXCFramework` then it updates the framework from OneSignalXCFramework (3.11.2) to OneSignalXCFramework (3.12.3) taken from the Podfile.lock.
But installing the pods again with this version it still crashes with the same error
`Library not loaded: @rpath/OneSignalCore.framework/OneSignalCore`

**Comment by emawby** [comment]
Make sure you are using Cocoapods 1.11.3 and try the below code. We have seen this issue when using versions lower than 1.11.3
```
rm Podfile.lock
pod cache clean --all
pod install --repo-update
```

**Comment by ElChawich** [comment]
hello @fhboswell  and @emawby,
Thank you for your replies.
My cocoapods version is 1.11.3, and i just tried @emawby's solution yet same error is still occuring

**Comment by nan-li** [comment]
Hi all,
Please also check your `ruby` version and update to version `2.7.5` or above, if you have a lower version than this.

**Comment by morozbogdn** [comment]
having the same problem. cannot resolve it

**Comment by BishalftSaikia** [comment]
in my case i removed "open using Rosetta" and followed the first answer on this stack https://stackoverflow.com/questions/69098207/could-not-find-ffi-1-3-0-among-85-total-gems-gemmissingspecerror-re , this solves ffi issues on my M1, try this , this may help.

**Comment by kenkeydev** [comment]
Same issue. Downgrading to 4.4.1 solved my problem.

**Comment by cenksari** [comment]
After hours of effort, I reached the following conclusion and successfully ran the application. 

If you are using XCode 14 and higher:

Go to Project --> Targets --> [Application Name] --> Frameworks, Libraries, and Embedded Content section.
Click + icon --> Type OneSignal in the search box --> Select OneSignalCore.xcframework and click Add button.
Do the same for OneSignalOutcomes.xcframework.
Check Embed and Sign on both.

Cean build folder and build.

I'm putting a screenshot below.

<img width="787" alt="Screenshot 2022-12-12 at 14 58 32" src="https://user-images.githubusercontent.com/1970703/207039547-0cd80cef-5bbf-4507-903f-03fb681ba772.png">

**Comment by Zeeshan404** [comment]
@cenksari Thanks it worked for me. I was having this issue when upgraded _react-native-onesignal_ to **4.5.0**

**Comment by yana-shkvoretz** [comment]
@cenksari This definitely fixed my issue! Thanks a lot!

**Comment by Dev-Ahmed-Adnan** [comment]
@cenksari This works perfectly with me, Many thanks.

**Comment by janandaraj** [comment]
> After hours of effort, I reached the following conclusion and successfully ran the application.
> 
> If you are using XCode 14 and higher:
> 
> Go to Project --> Targets --> [Application Name] --> Frameworks, Libraries, and Embedded Content section. Click + icon --> Type OneSignal in the search box --> Select OneSignalCore.xcframework and click Add button. Do the same for OneSignalOutcomes.xcframework. Check Embed and Sign on both.
> 
> Cean build folder and build.
> 
> I'm putting a screenshot below.
> 
> <img alt="Screenshot 2022-12-12 at 14 58 32" width="787" src="https://user-images.githubusercontent.com/1970703/207039547-0cd80cef-5bbf-4507-903f-03fb681ba772.png">

@cenksari 
I had same issue after upgrading from 3.x.x. to 4.5.0, and app crashed on start in ios, so I have added as you mentioned but build failed.

### podfile
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.11.1', '< 4.0'
end

### Podfile.lock
- OneSignalXCFramework (3.12.3):
    - OneSignalXCFramework/OneSignalCore (= 3.12.3)
    - OneSignalXCFramework/OneSignalExtension (= 3.12.3)
    - OneSignalXCFramework/OneSignalOutcomes (= 3.12.3)
  - OneSignalXCFramework/OneSignalCore (3.12.3)
  - OneSignalXCFramework/OneSignalExtension (3.12.3):
    - OneSignalXCFramework/OneSignalCore
    - OneSignalXCFramework/OneSignalOutcomes
  - OneSignalXCFramework/OneSignalOutcomes (3.12.3):
    - OneSignalXCFramework/OneSignalCore

attaching screenshot here,
<img width="1345" alt="Screenshot 2022-12-28 at 2 44 43 PM" src="https://user-images.githubusercontent.com/85667088/209788796-1923aec4-9140-43cb-999b-c603b0350157.png">

### Error says this any idea how to fix this/any one experienced this issue ?

Multiple commands produce '/Users/PC/Library/Developer/Xcode/DerivedData/Beach_Runners-byldswpvmwonzqheuuipyzwfvqba/Build/Intermediates.noindex/ArchiveIntermediates/Truckerbux/InstallationBuildProductsLocation/Applications/Beach Runners.app/Frameworks/OneSignalCore.framework':
1) Target 'Beach Runners' has copy command from '/Users/PC/Documents/Beach Runners/ios/Pods/OneSignalXCFramework/iOS_SDK/OneSignalSDK/OneSignal_Core/OneSignalCore.xcframework/ios-arm64_armv7_armv7s/OneSignalCore.framework' to '/Users/PC/Library/Developer/Xcode/DerivedData/Beach_Runners-byldswpvmwonzqheuuipyzwfvqba/Build/Intermediates.noindex/ArchiveIntermediates/Truckerbux/InstallationBuildProductsLocation/Applications/Beach Runners.app/Frameworks/OneSignalCore.framework'
2) That command depends on command in Target 'Beach Runners': script phase “[CP] Embed Pods Frameworks”

**Comment by muxbert** [comment]
Hey @janandaraj I am facing same error, have you fixed it?

**Comment by janandaraj** [comment]
@muxbert Hi i just removed OneSignalCore and OneSignalOutcomes from frameworks and did exactly in the documentation now it works but still i'm facing some missing push notification on iPhone device(on OneSignal Site it says delivered), android works fine

**Comment by jnsmith0274** [comment]
> > After hours of effort, I reached the following conclusion and successfully ran the application.
> > If you are using XCode 14 and higher:
> > Go to Project --> Targets --> [Application Name] --> Frameworks, Libraries, and Embedded Content section. Click + icon --> Type OneSignal in the search box --> Select OneSignalCore.xcframework and click Add button. Do the same for OneSignalOutcomes.xcframework. Check Embed and Sign on both.
> > Cean build folder and build.
> > I'm putting a screenshot below.

I also have the exact same issue as @janandaraj including the build error that multiple commands produce "..."  Disappointing that more recent versions of OneSignal are not playing nice with the iOS/Xcode ecosystem.

**Comment by mljlynch** [comment]
I just hit this - it would be nice if versions like this would be marked as breaking changes (major version updates) in the future.

**Comment by dhameliyawork** [comment]
I am also getting this issue with XCode 14 with ` "react-native-onesignal": "^4.5.0",`

I tried solution mentioned above https://github.com/OneSignal/react-native-onesignal/issues/1459#issuecomment-1346348669 but it doesn't work for me unfortunately. 


`Multiple commands produce Build/Products/Debug-iphoneos/spectrum.app/Frameworks/OneSignalOutcomes.framework'`

**Comment by moonvader** [comment]
When I build app using Xcode it crashes after launch - embeding `OneSignalCore.framework` and `OneSignalOutcomes.framework` as suggested above fix this problem.
But after this fix app fails to build on CI with `Multiple commands produce` error.

**Comment by yendiscart** [comment]
Solved this issue by adding extension as in the screenshot and it works 
<img width="825" alt="image" src="https://user-images.githubusercontent.com/70816248/212543677-3e9a9867-128b-4079-bb7b-3e3b194aef8b.png">

**Comment by muktadirsonyy911** [comment]
> After hours of effort, I reached the following conclusion and successfully ran the application.
> 
> If you are using XCode 14 and higher:
> 
> Go to Project --> Targets --> [Application Name] --> Frameworks, Libraries, and Embedded Content section. Click + icon --> Type OneSignal in the search box --> Select OneSignalCore.xcframework and click Add button. Do the same for OneSignalOutcomes.xcframework. Check Embed and Sign on both.
> 
> Cean build folder and build.
> 
> I'm putting a screenshot below.
> 
> <img alt="Screenshot 2022-12-12 at 14 58 32" width="787" src="https://user-images.githubusercontent.com/1970703/207039547-0cd80cef-5bbf-4507-903f-03fb681ba772.png">

Saved my day❤️

**Comment by SeanDunford** [comment]
> ruby

Just t

> Hi all, Please also check your `ruby` version and update to version `2.7.5` or above, if you have a lower version than this.

This comment might be out of date. I don't believe there is currently a `ruby@2.7.5`. Looks like `ruby@2.7.6` is valid though.

https://www.ruby-lang.org/en/downloads/releases/

**Comment by cyberIndia** [comment]
> After hours of effort, I reached the following conclusion and successfully ran the application.
> 
> If you are using XCode 14 and higher:
> 
> Go to Project --> Targets --> [Application Name] --> Frameworks, Libraries, and Embedded Content section. Click + icon --> Type OneSignal in the search box --> Select OneSignalCore.xcframework and click Add button. Do the same for OneSignalOutcomes.xcframework. Check Embed and Sign on both.
> 
> Cean build folder and build.
> 
> I'm putting a screenshot below.
> 
> <img alt="Screenshot 2022-12-12 at 14 58 32" width="787" src="https://user-images.githubusercontent.com/1970703/207039547-0cd80cef-5bbf-4507-903f-03fb681ba772.png">

in addition to this I also had to add the frameworks in Build Phases -> Embed App Extensions.. then it worked for me

**Comment by cyberIndia** [comment]
> > After hours of effort, I reached the following conclusion and successfully ran the application.
> > If you are using XCode 14 and higher:
> > Go to Project --> Targets --> [Application Name] --> Frameworks, Libraries, and Embedded Content section. Click + icon --> Type OneSignal in the search box --> Select OneSignalCore.xcframework and click Add button. Do the same for OneSignalOutcomes.xcframework. Check Embed and Sign on both.
> > Cean build folder and build.
> > I'm putting a screenshot below.
> > <img alt="Screenshot 2022-12-12 at 14 58 32" width="787" src="https://user-images.githubusercontent.com/1970703/207039547-0cd80cef-5bbf-4507-903f-03fb681ba772.png">
> 
> in addition to this I also had to add the frameworks in Build Phases -> Embed App Extensions.. then it worked for me

Nope, don't do that it caused other issues, duplicate libraries in the build. Making a new Build and then adding in the frameworks again fixed everything.

**Comment by karankharode** [comment]
> After hours of effort, I reached the following conclusion and successfully ran the application.
> 
> If you are using XCode 14 and higher:
> 
> Go to Project --> Targets --> [Application Name] --> Frameworks, Libraries, and Embedded Content section. Click + icon --> Type OneSignal in the search box --> Select OneSignalCore.xcframework and click Add button. Do the same for OneSignalOutcomes.xcframework. Check Embed and Sign on both.
> 
> Cean build folder and build.
> 
> I'm putting a screenshot below.
> 
> <img alt="Screenshot 2022-12-12 at 14 58 32" width="787" src="https://user-images.githubusercontent.com/1970703/207039547-0cd80cef-5bbf-4507-903f-03fb681ba772.png">

If anyone is still facing this issue in Flutter or React Native,
I have given the solution here
"https://stackoverflow.com/a/75446410/13561397"

It is much similar to the above solution but if you have not create the Notification service extension then you should do that first which is explained on above link 
That should help you out 
Cheers!

**Comment by geekz-reno** [comment]
> I am also getting this issue with XCode 14 with ` "react-native-onesignal": "^4.5.0",`
> 
> I tried solution mentioned above [#1459 (comment)](https://github.com/OneSignal/react-native-onesignal/issues/1459#issuecomment-1346348669) but it doesn't work for me unfortunately.
> 
> `Multiple commands produce Build/Products/Debug-iphoneos/spectrum.app/Frameworks/OneSignalOutcomes.framework'`

for anyone facing same problem, try to remove at the Build Phases -> Link Binary With Libraries and left PodsRunner only

**Comment by shkvoretz** [comment]
upgrading ruby and cocoapods as well as using `onesignal_flutter: 3.4.1` fixed the issue for my Intel Mac

**Comment by daoibrahim** [comment]
> After hours of effort, I reached the following conclusion and successfully ran the application.
> 
> If you are using XCode 14 and higher:
> 
> Go to Project --> Targets --> [Application Name] --> Frameworks, Libraries, and Embedded Content section. Click + icon --> Type OneSignal in the search box --> Select OneSignalCore.xcframework and click Add button. Do the same for OneSignalOutcomes.xcframework. Check Embed and Sign on both.
> 
> Cean build folder and build.
> 
> I'm putting a screenshot below.
> 
> <img alt="Screenshot 2022-12-12 at 14 58 32" width="787" src="https://user-images.githubusercontent.com/1970703/207039547-0cd80cef-5bbf-4507-903f-03fb681ba772.png">

Worked like a charme with Flutter as well. Thank you so much

**Comment by shkvoretz** [comment]
@daoibrahim what arch  are you on? Intel or M1?

**Comment by Sserra90** [comment]
I am on a M2 having the same error and the solutions above is not working because i get `Multiple commands produce` error

**Comment by XTalandier** [comment]
> After hours of effort, I reached the following conclusion and successfully ran the application.
> 
> If you are using XCode 14 and higher:
> 
> Go to Project --> Targets --> [Application Name] --> Frameworks, Libraries, and Embedded Content section. Click + icon --> Type OneSignal in the search box --> Select OneSignalCore.xcframework and click Add button. Do the same for OneSignalOutcomes.xcframework. Check Embed and Sign on both.
> 
> Cean build folder and build.
> 
> I'm putting a screenshot below.
> 
> <img alt="Screenshot 2022-12-12 at 14 58 32" width="787" src="https://user-images.githubusercontent.com/1970703/207039547-0cd80cef-5bbf-4507-903f-03fb681ba772.png">

It works perfectly for me. Not all heroes wear capes

**Comment by palanikumar32** [comment]
> After hours of effort, I reached the following conclusion and successfully ran the application.
> 
> If you are using XCode 14 and higher:
> 
> Go to Project --> Targets --> [Application Name] --> Frameworks, Libraries, and Embedded Content section. Click + icon --> Type OneSignal in the search box --> Select OneSignalCore.xcframework and click Add button. Do the same for OneSignalOutcomes.xcframework. Check Embed and Sign on both.
> 
> Cean build folder and build.
> 
> I'm putting a screenshot below.
> 
> <img alt="Screenshot 2022-12-12 at 14 58 32" width="787" src="https://user-images.githubusercontent.com/1970703/207039547-0cd80cef-5bbf-4507-903f-03fb681ba772.png">

It's working

**Comment by levarberry** [comment]
As of today this isn't part of the install documentation,  However, it worked for me.   Spent hours on this.

**Comment by doyeka** [comment]
Still facing this issue using `"react-native-onesignal": "4.5.1"`.

All of the suggestions in this thread didn't work for me. My environment:
Xcode 14.2
macOS Ventura 13.2.1
2.3 GHz Quad-Core Intel Core i7
node 19.2.0

Downgrading to `"react-native-onesignal": "4.4.1"` solved the issue for me. Please fix this in your future releases. Happy to send more information if needed.

**Comment by tronglv92** [comment]
> Solved this issue by adding extension as in the screenshot and it works <img alt="image" width="825" src="https://user-images.githubusercontent.com/70816248/212543677-3e9a9867-128b-4079-bb7b-3e3b194aef8b.png">

you save my day

**Comment by Remas-Safi** [comment]
> upgrading ruby and cocoapods as well as using `onesignal_flutter: 3.4.1` fixed the issue for my Intel Mac

This helped fixing my problem, where I faced two problems when I added the `OneSignalOutcomes.xcframework` to the Frameworks, Libraries, and Embedded Content section, I got the `Multiple commands produce ...etc ` error, where it worked correctly before. And if I remove them the app crashes once built and starts running .... updating cocoapods fixes this

**Comment by adefokun** [comment]
Under Targets, click your app name. Include OneSignalExtension.xcframework in Framework, Library and Embedded Content.

**Comment by wahyu-handayani** [comment]
> OneSignalXCFramework

Thank you so much, I search the solution for a day and finally find it after doing your step

**Comment by wahyu-handayani** [comment]
> Solved this issue by adding extension as in the screenshot and it works <img alt="image" width="825" src="https://user-images.githubusercontent.com/70816248/212543677-3e9a9867-128b-4079-bb7b-3e3b194aef8b.png">

Thank you so much, I search the solution for a day and finally find it after doing your step

**Comment by jennantilla** [comment]
Hello everyone! The discussion in this thread with solutions has been great--thank you to all who contributed! As it appears that these solutions have addressed the problem for many folks here, I'll go ahead and close this issue. If anyone is still facing this on at least React Native [4.5.2](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.5.2) or [5.0.5](https://github.com/OneSignal/react-native-onesignal/releases/tag/5.0.5) please @ mention me with an updated summary of what you're seeing and we'll be happy to put fresh eyes on it.

Thanks!
