### ISSUE TITLE
[Bug]: 100% Bug with new version 4.5.0 on IOS (Library not loaded: @rpath/OneSignalCore.framework/OneSignalCore)

### ISSUE THREAD

**Issue by maoryadin** [OneSignal/react-native-onesignal#1460]
### What happened?

Bug with new version 4.5.0 on IOS (Library not loaded: @rpath/OneSignalCore.framework/OneSignalCore)

### Steps to reproduce?

```Markdown
remove node_modules, package.lock, remove pods files/lock

install the new react-native-onesignal version 4.5.0
install pods -> pod install --repo-update
```

### What did you expect to happen?

run on ios device.

### React Native OneSignal SDK version

Release 4.5.0

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fhboswell** [comment]
Hello @maoryadin what version of CocoaPods are you using?

**Comment by maoryadin** [comment]
> Hello @maoryadin what version of CocoaPods are you using?

my CocoaPods version is: 1.11.3

**Comment by nan-li** [comment]
Also curious what your ruby version is @maoryadin ? `ruby --version`

**Comment by maoryadin** [comment]
> 

ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]

**Comment by maoryadin** [comment]
> ruby

ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]

**Comment by emawby** [comment]
@maoryadin If you have an example project that reproduces the issue that would be great! We have been able to reproduce the issue on Cocoapods versions lower than 1.11.3, but the issue is always resolved once updating to 1.11.3 and running the following

```
rm Podfile.lock
pod cache clean --all
pod install --repo-update
```

**Comment by fhboswell** [comment]
@maoryadin Using ruby 2.7.5 and updating ffi to the latest version and using CocoaPods 1.11.3 should solve this issue.

**Comment by maoryadin** [comment]
I will try that and will update

**Comment by ridvanaltun** [comment]
I'm dealing with the same issue. Version 4.4.1 works but something wrong with 4.5.0

**Comment by ridvanaltun** [comment]
same issue #1459

**Comment by nan-li** [comment]
Hi @ridvanaltun,

Please confirm both your `ruby` and `cocoapods` version. This arose because you are probably now using Xcode 14.1. You need `ruby` version 2.7.5 or greater and `cocoapods` 1.11.3.

Then you can clean up with:
```
rm Podfile.lock
pod cache clean --all
pod install --repo-update
```

**Comment by BishalftSaikia** [comment]
try this https://github.com/OneSignal/react-native-onesignal/issues/1459#issuecomment-1339177282

**Comment by idanlevi1** [comment]
Replace/add the target in `Podfile.lock` with:
```
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.12.3', '< 4.0'
end
```

the change is replace `3.0.0` with `3.12.3`

**Comment by LuanSdev** [comment]
This error appeared to me after update xcode to 14.2.

This [solution](https://github.com/OneSignal/react-native-onesignal/issues/1459#issuecomment-1346348669) worked for me

**Comment by jennantilla** [comment]
Hello everyone! The discussion in this thread with solutions has been great--thank you to all who contributed! As it appears that these solutions have addressed the problem for many folks here, I'll go ahead and close this issue. If anyone is still facing this on at least React Native [4.5.2](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.5.2) or [5.0.5](https://github.com/OneSignal/react-native-onesignal/releases/tag/5.0.5) please @ mention me with an updated summary of what you're seeing and we'll be happy to put fresh eyes on it.

Thanks!

**Comment by RayanAbid** [comment]
Hi @jennantilla I'm trying to run it on IOS but when the project runs it crashes with this error. 

``
dyld[82746]: Library not loaded: @rpath/OneSignalExtension.framework/OneSignalExtension
  Referenced from: <84B4B073-77E6-378E-9BE5-E712C5A2300C> /Users/umair/Library/Developer/CoreSimulator/Devices/272FB4CF-4CFF-4E56-9523-8656517E5CC1/data/Containers/Bundle/Application/131EF692-F7AE-4F09-A1C1-161657BAB45A/chatter.app/chatter
  Reason: tried: '/Users/umair/Library/Developer/Xcode/DerivedData/chatter-btenzekdimdwuxcqxauygscevwdd/Build/Products/Debug-iphonesimulator/OneSignalExtension.framework/OneSignalExtension' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (no such file), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (no such file, not in dyld cache), '/Users/umair/Library/Developer/CoreSimulator/Devices/272FB4CF-4CFF-4E56-9523-8656517E5CC1/data/Containers/Bundle/Application/131EF692-F7AE-4F09-A1C1-161657BAB45A/chatter.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (no such file), '/Users/umair/Library/Developer/CoreSimulator/Devices/272FB4CF-4CFF-4E56-9523-8656517E5CC1/data/Containers/Bundle/Application/131EF692-F7AE-4F09-A1C1-161657BAB45A/chatter.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (no such file), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (no such file, not in dyld cache), '/Users/umair/Library/Developer/CoreSimulator/Devices/272FB4CF-4CFF-4E56-9523-8656517E5CC1/data/Containers/Bundle/Application/131EF692-F7AE-4F09-A1C1-161657BAB45A/chatter.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (no such file), '/Users/umair/Library/Developer/CoreSimulator/Devices/272FB4CF-4CFF-4E56-9523-8656517E5CC1/data/Containers/Bundle/Application/131EF692-F7AE-4F09-A1C1-161657BAB45A/chatter.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/OneSignalExtension.framework/OneSignalExtension' (no such file)
Message from debugger: killed
Logging Error: Failed to initialize logging system. Log messages may be missing. If this issue persists, try setting IDEPreferLogStreaming=YES in the active scheme actions environment variables.
``

I'm using 

``
"react-native-onesignal": "^5.0.5",
``

and as for my ios version on podfile.lock 

``
 - OneSignalXCFramework (5.1.0):
    - OneSignalXCFramework/OneSignalComplete (= 5.1.0)
  - OneSignalXCFramework/OneSignal (5.1.0):
    - OneSignalXCFramework/OneSignalCore
    - OneSignalXCFramework/OneSignalExtension
    - OneSignalXCFramework/OneSignalNotifications
    - OneSignalXCFramework/OneSignalOSCore
    - OneSignalXCFramework/OneSignalOutcomes
    - OneSignalXCFramework/OneSignalUser
  - OneSignalXCFramework/OneSignalComplete (5.1.0):
    - OneSignalXCFramework/OneSignal
    - OneSignalXCFramework/OneSignalInAppMessages
    - OneSignalXCFramework/OneSignalLocation
  - OneSignalXCFramework/OneSignalCore (5.1.0)
  - OneSignalXCFramework/OneSignalExtension (5.1.0):
    - OneSignalXCFramework/OneSignalCore
    - OneSignalXCFramework/OneSignalOutcomes
  - OneSignalXCFramework/OneSignalInAppMessages (5.1.0):
    - OneSignalXCFramework/OneSignalCore
    - OneSignalXCFramework/OneSignalNotifications
    - OneSignalXCFramework/OneSignalOSCore
    - OneSignalXCFramework/OneSignalOutcomes
    - OneSignalXCFramework/OneSignalUser
  - OneSignalXCFramework/OneSignalLocation (5.1.0):
    - OneSignalXCFramework/OneSignalCore
    - OneSignalXCFramework/OneSignalNotifications
    - OneSignalXCFramework/OneSignalOSCore
    - OneSignalXCFramework/OneSignalUser
  - OneSignalXCFramework/OneSignalNotifications (5.1.0):
    - OneSignalXCFramework/OneSignalCore
    - OneSignalXCFramework/OneSignalExtension
    - OneSignalXCFramework/OneSignalOutcomes
  - OneSignalXCFramework/OneSignalOSCore (5.1.0):
    - OneSignalXCFramework/OneSignalCore
  - OneSignalXCFramework/OneSignalOutcomes (5.1.0):
    - OneSignalXCFramework/OneSignalCore
  - OneSignalXCFramework/OneSignalUser (5.1.0):
    - OneSignalXCFramework/OneSignalCore
    - OneSignalXCFramework/OneSignalNotifications
    - OneSignalXCFramework/OneSignalOSCore
    - OneSignalXCFramework/OneSignalOutcomes
   ``

I'm using macbook pro 2018 
Xcode 15.1
ruby ver:  ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin23]

Please let me know if there is any other info you need. 

Thanks
