### ISSUE TITLE
[Bug]: no visible @interface for 'RCTOneSignal' declares the selector 'initWithLaunchOptions:appId:

### ISSUE THREAD

**Issue by kenkeydev** [OneSignal/react-native-onesignal#1461]
### What happened?

I setup eveything as followed but always seem to be gettin the same error: no visible @interface for 'RCTOneSignal' declares the selector 'initWithLaunchOptions:appId:

(ios/MobileApp/AppDelegate.m:34:44)

  32 |                                             initialProperties:nil];
  33 |     NSURL *jsCodeLocation;
> 34 |     self.oneSignal = [[RCTOneSignal alloc] initWithLaunchOptions:launchOptions
     |                                            ^ no visible @interface for 'RCTOneSignal' declares the selector 'initWithLaunchOptions:appId:'

### Steps to reproduce?

```Markdown
1. yarn add react-native-onesignal
2. cd ios && pod install
3. Add a Notification Service Extension
4. pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
5. Updated code on NotificationService.swift
6. Add App Group
7. Initialize the OneSignal SDK
8. run app
```

### What did you expect to happen?

The app to run like it did before attempting to add onesignal

### React Native OneSignal SDK version

React Native Onesignal 4.5.0

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
32 |                                             initialProperties:nil];
  33 |     NSURL *jsCodeLocation;
> 34 |     self.oneSignal = [[RCTOneSignal alloc] initWithLaunchOptions:launchOptions
     |                                            ^ no visible @interface for 'RCTOneSignal' declares the selector 'initWithLaunchOptions:appId:'
  35 |                                                            appId:@"********************"];
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by musmastour** [comment]
I am facing the same issue, any news?

**Comment by jennantilla** [comment]
Hello there! Apologies that this issue was missed. Since it has been quite some time, I will be closing out this issue. Please @ mention me if you are still facing this problem on at least [Release 4.5.2](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.5.2).

Thanks!
