### ISSUE TITLE
[question]: Getting fail while archiving

### ISSUE THREAD

**Issue by HcumaliPik** [OneSignal/react-native-onesignal#1464]
### How can we help?

I have a react native app. I integrated one signal into android and ios separately. 
There is no problem in android side. 
After i am setting ios sdk, i am getting error while get archive for testfligt. 
Error text ==> 
.) Validate OneSignalNotificationExtension.appex
..) Command ValidateEmbeddedBinary failed with a nonzero exit code.
Before installing OneSignalNotificationExtension, I was able to get archive successfully. I think the problem is inside OneSignalNotificationExtension.
I put the error screenshot below. 
I am use m1 macbook air and my ios version 11.0.
I need help urgently, thank you.

<img width="917" alt="Ekran Resmi 2022-12-08 13 18 23" src="https://user-images.githubusercontent.com/113389020/206425644-ad663eb9-731d-4e95-b64e-6ad7e727005f.png">

<img width="939" alt="Ekran Resmi 2022-12-08 13 39 54" src="https://user-images.githubusercontent.com/113389020/206426449-fa4c995d-cfa0-4c67-a065-1c61107e8cff.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HcumaliPik** [comment]
Solved.

When you add a new target, the targeting version and build numbers you add must be the same as the main project.
The error here is that the OneSignalNotificationServiceExtension target's build and version numbers do not match the main project.

**Comment by phuvinhng** [comment]
How can you update the build and version number for OneSignalNotificationServiceExtension?

**Comment by HcumaliPik** [comment]
> How can you update the build and version number for OneSignalNotificationServiceExtension?

The build and version numbers of the main project and the numbers of the "OneSignalNotificationServiceExtension" target we added must be the same. You can update the build and version numbers via the general tab.
