### ISSUE TITLE
RN SDK not working İOS Error import OneSignal

### ISSUE THREAD

**Issue by canerd7u** [OneSignal/react-native-onesignal#1466]
### How can we help?

https://documentation.onesignal.com/docs/react-native-sdk-setup#step-4-install-for-ios-using-cocoapods-for-ios-apps

this step write **ignore any build errors at this point, we will resolve these later by importing the OneSignal library.**

but no answer how to importing Onesignal libray anywehere !!!!!!!!!!!!!!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by StephenTANM** [comment]
close xcode, pod install then reopen xcode

**Comment by phuocantd** [comment]
how to fix it ? @StephenTANM
