### ISSUE TITLE
[question]: Onesignal domain address change

### ISSUE THREAD

**Issue by mohammad6vakili** [OneSignal/react-native-onesignal#1469]
### How can we help?

I have a React Native application that works with OneSignal push notification system and I have used this library.
I am based in Iran and unfortunately it is not possible to connect with OneSignal or Google Firebase from Iran.
Therefore, if users want to receive notifications, they have to open the application using VPN, which is a very big problem.
I prepared a server that has a VPN and I want users to make a request to One Signal through that server and receive the token.
In this case, they don't need a VPN to receive the token because my server will do it.
Now for this I need to change the address that is called inside this library.
How can I do this?

```
After the research I did, I realized that many Iranian applications have this problem.
In my opinion, this method and changing the address can help a lot of software based on One Signal
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rgomezp** [comment]
Howdy,
Due to legal reasons, entities on the U.S embargo list will not be able to use OneSignal nor subscribe to push notifications.
We apologize for the inconvenience.
