### ISSUE TITLE
Enable sound/vibration only in certain hours

### ISSUE THREAD

**Issue by hecontreraso** [OneSignal/react-native-onesignal#147]
Hi guys! Second week building with onesignal for my app, and I think is awesome (:

Now I come to you with a question

I want my app to sound but only in certain hours, which are send from a server. Not sure how to achieve this.
Here's an idea:

Configure onesignal with sound disabled:
```
OneSignal.enableSound(false);
```
Then when a notification arrives, use _onNotificationReceived_ callback to manually trigger the notification sound

I tried this but it doesn't work:
```
onNotificationReceived: function(notification) {
	if(availableHour) {
	    OneSignal.enableSound(true);
	    OneSignal.enableVibrate(true);	
    }
}
```

Do you think that there is a better way to achieve that?

**Update:**
I advanced in this way, but now I have not been able to sound/vibrate the phone when the app is not opened

Any help will be super appreciated!

**Comment by avishayil** [comment]
I'm not sure you can achieve that without launching your app, but here's an idea: every time user gets to the app, check the hour and change the setting accordingly. It's not perfect, but if your users are accessing your app multiple times a day, you can somewhat gain more control over it.
Maybe Josh will have a better idea.
@jkasten2

**Comment by jkasten2** [comment]
@hecontreraso @avishayil 

I recommend setting the sound name to `nil` on the notification when you want to disable it. It works for both iOS and Android. There isn't a per notification vibration setting at this time.

**Comment by avishayil** [comment]
@hecontreraso You should do it on the server side:
https://documentation.onesignal.com/reference
Seach for `ios_sound`, and set the hours setting on the server side.
You can send a tag that contains the wanted hours per user and use it on your server side request.
