### ISSUE TITLE
[question]: any way to clear notification for a whole "android_group"?

### ISSUE THREAD

**Issue by pierroo** [OneSignal/react-native-onesignal#1472]
### How can we help?

We do have the removeNotification and clearOneSignalNotifications functions, but is there anything "in between" that would allow to clear all notifications under the same groupKey / android_group?

For example in a chat app, someone sent me many messages, if I tap on it I wanna clear all related notifications, but not those of other friends etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @pierroo , I believe `OneSignal.removeGroupedNotifications("yourGroupId")` found [here](https://github.com/OneSignal/react-native-onesignal/blob/main/src/index.ts#L715) is what you are looking for. Hope this helps!

**Comment by pierroo** [comment]
It certainly is, thank you @brismithers ! :)
