### ISSUE TITLE
How to show the popup when receive notification on android 

### ISSUE THREAD

**Issue by lehuydev2203** [OneSignal/react-native-onesignal#1473]
### How can we help?

I want to show a pop-up like that when receiving notifications on android When the user doesn't open the application, what to do?

![photo_2023-01-04_15-57-36](https://user-images.githubusercontent.com/41155784/210519174-bead8867-6322-40e3-8741-1f9575909da0.jpg)

I use :

 "react": "18.1.0",
 "react-native": "0.70.0",
 "react-native-onesignal": "^4.5.0",

I did enable the show pop-up in settings -> notification app

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@lehuydev2203 by default notifications don't show a as a heads up notification style (pop-up). To do this you need to create a notification category with a "Importance" of URGENT and use it on your notifications. See OneSignal's documentation for more details.
https://documentation.onesignal.com/docs/android-notification-categories
