### ISSUE TITLE
[question]: Expo dependency for iOS Notification Service Extension Module

### ISSUE THREAD

**Issue by d-podabed-belitsoft-com** [OneSignal/react-native-onesignal#1476]
### How can we help?

Hello. In "iOS Notification Service Extension Module" guide (https://documentation.onesignal.com/docs/rn-android-native-module-setup-for-notification-service-extension#ios-notification-service-extension-module) in step "Sending Events to Javascript" (https://documentation.onesignal.com/docs/rn-android-native-module-setup-for-notification-service-extension#sending-events-to-javascript-1) added this line `#import <EXUpdates/EXUpdatesAppController.h>` to `AppDelegate.h` file. And 'cause of that build corrupted. And before no Expo in previous steps. Is it possible to make it work without `EXUpdatesAppController.h`? I tried to install expo-updates manually (via Expo guide). No result. I found related issue https://github.com/OneSignal/react-native-onesignal/issues/1375, but not helped for me too (in it just excluded `AppDelegate.h` modification, build works, but without background pushes).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Thank you for the feedback @d-podabed-belitsoft-com .  I believe the documentation is in error and assumes an Expo app, when it should not.

You should be able to remove the `#import <EXUpdates/EXUpdatesAppControllerh>` line, as well as the reference to `EXUpdatesAppControllerDelegate` in your `AppDelegate` interface declaration.  So your `AppDelegate.h` file should look something like this:

```
#import <Foundation/Foundation.h>
#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>

#import <UserNotifications/UserNotifications.h>


#import <UMCore/UMAppDelegateWrapper.h>

@interface AppDelegate : UMAppDelegateWrapper <UIApplicationDelegate, RCTBridgeDelegate>


@end
```

with your `AppDelegate.m` file implementing the `didReceiveRemoteNotification` method as specified in the doc.

Please confirm this as a solution and I will make the doc update as well. Thanks!

**Comment by brismithers** [comment]
Hi @d-podabed-belitsoft-com just checking in, did the above suggestion resolve your issue? Thanks!
