### ISSUE TITLE
[Bug]: OneSignal missing files on M1 Mac

### ISSUE THREAD

**Issue by nikero41** [OneSignal/react-native-onesignal#1479]
### What happened?

In this release, when trying to build for iOS, I get an error that it misses a file. Other, non-M1 macs, do not have this issue

In Podfile:
```swift
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end
```

### Steps to reproduce?

```Markdown
1. Install react-native-onesignal@4.4.1
2. Yarn to install dependencies and pods
3. Try to build the iOS app
```

### What did you expect to happen?

I expected a normal build without errors

### React Native OneSignal SDK version

"react-native-onesignal": "4.4.1"

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
▸ Processing Info.plist
▸ Running script '[CP] Check Pods Manifest.lock'
▸ Compiling NotificationService.m

❌  /.../ios/OneSignalNotificationServiceExtension/NotificationService.m:1:9: 'OneSignal/OneSignal.h' file not found

#import <OneSignal/OneSignal.h>
        ^~~~~~~~~~~~~~~~~~~~~~~


    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'App' from project 'App')
    Run script build phase '[CP-User] [RNFB] Core Configuration' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
@snikoletopoulos can you try to update to 4.5.0?  I believe this will pick up a fix that addresses your issue.  Please let us know thanks!

**Comment by tradil** [comment]
I have exactly the same issue on MacBook with M1 Pro processor. I use react-native-onesignal version 4.5.0. I completely reset both pod and npm caches, deleted Podfile.lock file and installed new pods with repo update. OneSignalXCFFramework 3.12.3 and react-native-onesignal 4.5.0 were downloaded and reinstalled, but XCode 14.2 still reports missing OneSignal.h. I event tried to run Xcode under Rosetta. Do you have some solution for the problem?

**Comment by nikero41** [comment]
> @snikoletopoulos can you try to update to 4.5.0? I believe this will pick up a fix that addresses your issue. Please let us know thanks!

We are indeed using react-native-onesignal version 4.5.0
We also tried everything that @tradil did and can confirm it didn't work for me either

**Comment by brismithers** [comment]
If you are using CocoaPods, can you ensure you are using version `1.11.3+` and Ruby version `2.7.5+`?

**Comment by nikero41** [comment]
Here are the versions for CocoaPods and Ruby

![Screenshot 2023-02-18 at 6 38 12 PM](https://user-images.githubusercontent.com/78855607/219877478-0a3df2a2-022b-47e7-8775-737b4003f906.png)

**Comment by emawby** [comment]
Hello I am not able to reproduce this on my m1 mac, but If this is still an issue you could try updating to the latest cocoapods major release. Cocoapods had not updated since Xcode 14 was released last year, but their new version should include many fixes for that xcode version

**Comment by emawby** [comment]
Closing for now but feel free to reopen if this is still an issue

**Comment by MortadhaFadhlaoui** [comment]
Still have the same issue, i upgrade everything, any idea?

**Comment by Steffi3rd** [comment]
Same problem for me. So what's the solution?

**Comment by arnaudambro** [comment]
https://documentation.onesignal.com/docs/ios-sdk-setup#4-notification-service-extension

maybe in the objective-c file, write `OneSignalExtension` where you have `OneSignal` or `OneSignalFramework` ?

```
#import <OneSignalExtension/OneSignalExtension.h>
```

instead of 

```
#import <OneSignal/OneSignal.h>
```

not sure about it though, but at home it seems to compile

**Comment by samih-dev** [comment]
removing Pods folder + cleaning build and xcode derived data folder + then after `pod install`, 
fixed it for me 

P.S using cordova and not react-native -- but it may help
