### ISSUE TITLE
[question]: Avoiding duplicate Player IDs

### ISSUE THREAD

**Issue by dlindsey-olioapps** [OneSignal/react-native-onesignal#1481]
### How can we help?

**OneSignal APK Version**
react-native-onesignal - 4.4.1
react-native 0.70.5

**Issue**
Hello!

We are having an issue where users are getting duplicate player IDs associated with their external user ID. The external user IDs are unique and correctly associated with the users. It seems if the app has been inactive for a bit, or if the app is uninstalled and a newer version is installed, a new player ID gets subscribed while the old one remains subscribed.

To reproduce this process, I
- Install a fresh version
- Sign in and enable notifications
- Force close the app
- Uninstall the app
- Update the version number
- Install the app
- Sign in and enable notifications

I then will have two different player IDs for the same external user ID, despite using the same device on the same version of Android and calling OneSignal setExternalUserId within a ~5 min span
.
It seems to me that what is creating these duplicates for us in real time is a user
* doesn't use the application for some time
* the application gets updated in that time span
* the user gets auto signed out after X amount of days
* the user signs back in 
* A new player ID is created

Having the duplicates in there doesn't necessarily bother us (since once they've been inactive long enough, OneSignal marks them as inactive), but we did get a notice from OneSignal that we need to correct this problem and that there are some changes coming to the the way the platform works in the coming days. I am confident that we are passing the correct external user ID, but I wanted to see if anyone at OneSignal can shine some light on why this might be happening? Does the above all sound like expected behavior?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
@dlinds to my knowledge the only time a new player id *should* be generated is when the user does a proper uninstall/reinstall of the app.  The SDK persists the player id in your app's shared preferences, as long as that remains intact no new player id will be created.  Do you have any logs you could share showing this happening across one of the  non-uninstall/reinstall scenarios?  Thanks!

**Comment by ecoin-finance** [comment]
when submite app to google they use a bunch of smarphones to test, and it like span the users ids

**Comment by jennantilla** [comment]
@ecoin-finance if testers are fresh installs then creating a new player record is expected behavior.

I'd like to note that we have a new major release SDK that now tracks subscriptions (previously Player IDs) on a user level. That SDK contains many new enhancements and features. Feel free to refer to our [migration guide](https://github.com/OneSignal/react-native-onesignal/blob/major_release_5.0.0/MIGRATION_GUIDE.md) for more information on upgrading. 

Thanks!
