### ISSUE TITLE
[question]: What's wrong with registration of a plugin with expo app?

### ISSUE THREAD

**Issue by proton1k** [OneSignal/react-native-onesignal#1482]
### How can we help?

Hello! I’ve been trying to connect OneSignal by following the tutorial for Expo app, but I can't get the new subscriber.  Here is the tutorial I followed: https://documentation.onesignal.com/docs/react-native-expo-sdk-setup . I also checked github threads:

- https://github.com/OneSignal/react-native-onesignal/issues/1345
- https://github.com/OneSignal/onesignal-expo-plugin/issues/24

There's a sample code I took from this Logrocket article: https://blog.logrocket.com/implement-push-notifications-react-native-onesignal/ (signal app ID different of course)
On the OneSignal page I see a button to "check subscribed users" and the warning below shows

> You have X total subscribed users for this app, but none specifically for the Google Android (FCM) platform. You need at least one subscribed user specifically for Google Android (FCM) to continue."

I see in build logs: 

```
ERROR Could not load RNOneSignal native module. Make sure native dependencies are properly linked.
```

And it sends me back to the expo's developed plugin called "onesignal-expo-plugin" which has to do that linking for Expo version 46 or below (I have 46).
Things were checked:
- app.json is correct
- cache cleaned and regenerated the prebuild
- packages installed and present in the node_modules folder

So what may have gone wrong here?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @proton1k , closing this as it is an expo plugin issue. and response will be in https://github.com/OneSignal/onesignal-expo-plugin/issues/158
