### ISSUE TITLE
[Feedback]: README appeared outdated

### ISSUE THREAD

**Issue by obrienbcg** [OneSignal/react-native-onesignal#1486]
### What's on your mind?

The README says that the lib has been tested from iOS 7 to iOS 13. Given we're in 16 right now just wanted to flag that this is probably outdated.

```
Supports:
Tested from iOS 7 to iOS 13
Tested from Android 4.0.3 (API level 15) to Android 9 (28)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
thanks @obrienbcg , will get that updated!
