### ISSUE TITLE
[question]: Java.Lang.IllegalArgumentException: 'com.companyname.pushnotificationdemomaui: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.'

### ISSUE THREAD

**Issue by iKevinAntony** [OneSignal/react-native-onesignal#1487]
### How can we help?

I face this issue what is the issue???  Can any one help me with this... Thanks in advance

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iKevinAntony** [comment]
![Screenshot 2023-02-09 163905](https://user-images.githubusercontent.com/112926865/217796605-4c45717f-6dcd-4511-a494-3686015f2ff8.png)
 I face this issue what is the issue??? Can any one help me with this... Thanks in advance

**Comment by brismithers** [comment]
Hi @iKevinAntony thanks for reporting.  Can you please open a new issue as a "Bug Report" and provide answers to a series of questions that will give us enough context and information to help you resolve your issue?  Thanks!
