### ISSUE TITLE
[Bug]: Remote Webview debugging is enabled.

### ISSUE THREAD

**Issue by rakeshv1108** [OneSignal/react-native-onesignal#1488]
### What happened?

How can this Webview debugging mode be turned off?

I've included my release apk build in the Mobsf testing procedure to look for security flaws. Additionally, I received one serious problem from the Mobsf report for your package library. The screenshot for that report is attached. Please take action to fix the security problem.

![Screen Shot 2023-02-15 at 12 07 09 PM](https://user-images.githubusercontent.com/48330509/218951246-a9ad83ef-61ff-4154-b2a2-e4155d0d82a7.png)

Thank you.

### Steps to reproduce?

```Markdown
1. Create release android build apk.
2. Set up the Mobsf security checkup tool.
3. Analyse that same apk through that Mobsf tool.
```

### What did you expect to happen?

I want to disable or remove that debugging line from the npm package code.

### React Native OneSignal SDK version

Release 4.5.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by masaju45** [comment]
Has this issue been added to the project road map? any approximation date on when this will be addressed?

**Comment by samu-gataca** [comment]
Any new about this?

**Comment by emawby** [comment]
I apologize we do not have news yet, but we appreciate the bump! We will investigate

**Comment by maxi-alibrate** [comment]
Any new?

**Comment by Redn4s** [comment]
A pentest of our app revealed that Remote WebView debugging is activated. This was specifically found in OneSignal: `com/onesignal/WebViewManager.java`. We're use v4.5.1 of `react-native-onesignal`. 

Any news about the issue yet?

**Comment by tair-rhyme** [comment]
seems like that is false positive, because of [this](https://github.com/OneSignal/OneSignal-Android-SDK/blob/1d27d82e0d252c3a4453bb7ab048979a9321e5ea/OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java#L504), if you do not set logLevel to debug and higher it should be OK

**Comment by manish-chimera** [comment]
I am having similar issue with Onesignal Android SDK with version 5.1.7.  how can we disable Remote WEBview debugging?

**Comment by nan-li** [comment]
Hi, thanks for reaching out,
Regarding Remote WebView Debugging was Enabled
OneSignal's default logging level is warning. Make sure you don't set `OneSignal.Debug.setLogLevel(OSLogLevel.debug)` or `verbose` in your production app to avoid this from being activated.

**Comment by Monfallet** [comment]
@nan-li I have set this variable as you mentioned, but the issue persists. Another thing, during a scan I conducted on my APK, I found several paths or files containing the word "debug". Could you please help me clarify these points?

**Comment by nan-li** [comment]
Hi @Monfallet, a static analysis will pick up the existence of code, not whether the code is activated. 

The [remote webview will only be set up](https://github.com/OneSignal/OneSignal-Android-SDK/blob/04cfe9b43c2afd2f748e6ab534ed53985b5b06cd/OneSignalSDK/onesignal/in-app-messages/src/main/java/com/onesignal/inAppMessages/internal/display/impl/WebViewManager.kt#L431)  if you use levels DEBUG or higher (so `DEBUG` or `VERBOSE`).

> I found several paths or files containing the word "debug"
There is a [debug](https://github.com/OneSignal/OneSignal-Android-SDK/tree/main/OneSignalSDK/onesignal/core/src/main/java/com/onesignal/debug) package and some classes to help with logging. Again, DEBUG-level and VERBOSE-level logs will only log if you have set the log level to VERBOSE or DEBUG. See [this](https://github.com/OneSignal/OneSignal-Android-SDK/blob/04cfe9b43c2afd2f748e6ab534ed53985b5b06cd/OneSignalSDK/onesignal/core/src/main/java/com/onesignal/debug/internal/logging/Logging.kt#L89).
