### ISSUE TITLE
[question]: Voip Notifications (Ios/Android) is supported?

### ISSUE THREAD

**Issue by maoryadin** [OneSignal/react-native-onesignal#1489]
### How can we help?

I'm curious to know whether VoIP notifications are supported on both iOS and Android.
 I have two applications, one built on Expo and the other on bare React Native. 
I'm unsure if integrating VoIP into both applications would be difficult or impossible. 
Could you please help me understand this better? Thank you!

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @maoryadin apologies that this issue was missed. Our full VOIP documentation can be found [here](https://documentation.onesignal.com/docs/voip-notifications) which should address your questions. Thanks!
