### ISSUE TITLE
Unsubscribe user on iOS

### ISSUE THREAD

**Issue by haikov** [OneSignal/react-native-onesignal#15]
Is it possible to disable PushNotifications for the user through js (I'd like to add switch in the app)? I see that we have `setSubscription` method, but seems like it doesn't work on iOS.

**Comment by avishayil** [comment]
Thanks for the report, i'll test it and let you know.

**Comment by avishayil** [comment]
Hi, I won't be available on the next month to add new features. If you have any idea for a PR, i'll be happy to review it.
Hopefully after mid May i'll be back to add new features to this library.

I'm adding this request to the TODO list.

**Comment by avishayil** [comment]
I'm testing this on iOS right now, we'll let you know.
On Android it works well by my tests.

**Comment by avishayil** [comment]
Working in all my tests.
