### ISSUE TITLE
[Bug]: Android 13 not receive notifications

### ISSUE THREAD

**Issue by phucph1998** [OneSignal/react-native-onesignal#1507]
### What happened?

I using "react-native-onesignal": "^3.3.1", "react-native": "0.64.0"

Android 12 and lower devices receive notifications normally
Particularly on android 13, no notifications are received

### Steps to reproduce?

```Markdown
I using "react-native-onesignal": "^3.3.1", "react-native": "0.64.0"

Android 12 and lower devices receive notifications normally
Particularly on android 13, no notifications are received
```

### What did you expect to happen?

Solution to receive notifications on android 13 with version 3.3.1 without updating to the latest version

### React Native OneSignal SDK version

"react-native-onesignal": "^3.3.1",

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kesheshyan** [comment]
Hey @phucph1998. We would recommend to migrate to the latest stable version **[4.5.1](https://www.npmjs.com/package/react-native-onesignal/v/4.5.1)** which should work fine with Android 13.

Also we just release a beta version of our new User API that you can check out here https://github.com/OneSignal/react-native-onesignal/issues/1506

**Comment by SonamSharmac6160** [comment]
> ### What happened?
> I using "react-native-onesignal": "^3.3.1", "react-native": "0.64.0"
> 
> Android 12 and lower devices receive notifications normally Particularly on android 13, no notifications are received
> 
> ### Steps to reproduce?
> ```
> I using "react-native-onesignal": "^3.3.1", "react-native": "0.64.0"
> 
> Android 12 and lower devices receive notifications normally
> Particularly on android 13, no notifications are received
> ```
> 
> ### What did you expect to happen?
> Solution to receive notifications on android 13 with version 3.3.1 without updating to the latest version
> 
> ### React Native OneSignal SDK version
> "react-native-onesignal": "^3.3.1",
> 
> ### Which platform(s) are affected?
> * [ ]  iOS
> * [x]  Android
> 
> ### Relevant log output
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

I'm facing same issue with version 3.9.4
did you find any solution for supporting Android 13?

**Comment by SonamSharmac6160** [comment]
> Hey @phucph1998. We would recommend to migrate to the latest stable version **[4.5.1](https://www.npmjs.com/package/react-native-onesignal/v/4.5.1)** which should work fine with Android 13.
> 
> Also we just release a beta version of our new User API that you can check out here #1506

Notifications not coming after updating this version. After installation 4.5.1 or 4.0.0+ version app is getting crash. Only 3.9.4 version is working for Android 11 and 12, But not receving notification in Android 13. Is there any solution for it?
