### ISSUE TITLE
[Bug]: TypeError: undefined is not an object (evaluating '_reactNativeOnesignal.default.setAppId')

### ISSUE THREAD

**Issue by jaykeny** [OneSignal/react-native-onesignal#1508]
### What happened?

After following the setup process OneSignal.setAppId(I INSERTED MY ID HERE) is returning undefined.

**Edit**: It appears to be due to the latest react-native-onesignal beta version being automatically installed. It looks like there are some migration steps, which still resulted in the error
https://github.com/OneSignal/react-native-onesignal/blob/user_model/MIGRATION_GUIDE.md

Upon downgrading to react-native-onesignal 4.4.1 the issue is resolved once prebuilt.

### Steps to reproduce?

```Markdown
Following setup guide, it triggers the error
```

### What did you expect to happen?

It to work

### OneSignal Expo SDK version

1.3.1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Thanks for reporting @jaykeny , moving this to the react-native-onesignal repository as it seems to be related to the SDK rather than the expo plugin itself!

**Comment by brismithers** [comment]
I've updated the npm repo to revert the `latest` version back down to `4.5.1`.  Version `5.0.0-beta-01` exists for anyone that wants it explicitly, or via the `beta` tag.

@jaykeny if you are up for helping us understand what errors you got attempting to use the 5.0.0 beta version please post them here!

**Comment by mannyuiux** [comment]
Getting the same issue in iOS as well, wasn't able to find a solution anywhere. Have reached out to OneSignal support team, no response.

**Comment by nan-li** [comment]
Hi @mannyuiux, what issue are you running into? 

That you want to use react-native-onesignal `v4.x.x` but is fetching `v5.x.x` from npm?

**Comment by jennantilla** [comment]
Hello everyone! This issue will be closed out as it appears to have gone stale. If this is still a concern for anyone please respond and we will be happy to provide assistance!
