### ISSUE TITLE
OneSignalNotificationExtension build fail

### ISSUE THREAD

**Issue by gurbela** [OneSignal/react-native-onesignal#1510]
### What happened?

OneSignalNotificationExtension target build fail:

**Error:**
> Undefined symbol: _$sBOWV
 Undefined symbol: _$ss018_bridgeAnyObjectToB0yypyXlSgF
 Undefined symbol: _$ss17_assertionFailure__4file4line5flagss5NeverOs12StaticStringV_A2HSus6UInt32VtF
 Undefined symbol: _$sypN
 Undefined symbol: __swift_FORCE_LOAD_$_swiftCoreFoundation
 Undefined symbol: __swift_FORCE_LOAD_$_swiftDarwin
 Undefined symbol: __swift_FORCE_LOAD_$_swiftDispatch
 Undefined symbol: __swift_FORCE_LOAD_$_swiftObjectiveC
 Undefined symbol: _swift_allocObject
 Undefined symbol: _swift_beginAccess
 Undefined symbol: _swift_deallocObject
 Undefined symbol: _swift_dynamicCast
 Undefined symbol: _swift_endAccess
 Undefined symbol: _swift_getObjCClassMetadata
 Undefined symbol: _swift_isaMask
 Undefined symbol: _swift_release
 Undefined symbol: _swift_retain
 Undefined symbol: _swift_unknownObjectRelease

### Steps to reproduce?

```Markdown
This project worked well for a long time. But now he has a problem with build. 
The SDK is implemented according to the documentation
```

### What did you expect to happen?

iOS Development Target **11.1**

**"react-native": "0.64.4",**

I had` "react-native-onesignal": "4.3.11"` version but the new version has the same problem` "4.5.1"`.

### React Native OneSignal SDK version

4.5.1

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coderdave** [comment]
@gurbela have you by chance found a workaround for this? These same errors started happening for me after upgrading to xcode 14.3. Is that the same case with you?

**Comment by gurbela** [comment]
> @gurbela have you by chance found a workaround for this? These same errors started happening for me after upgrading to xcode 14.3. Is that the same case with you?

Yes. 14.3 has a problem

**Comment by nan-li** [comment]
Hi @gurbela and @coderdave,

Thanks for reporting,

Did anything else change before this error started appearing? 
Only your xcode version updated to 14.3? 
Was there anything else changed?
What xcode version were you on before?

**Comment by gurbela** [comment]
> Hi @gurbela and @coderdave,
> 
> Thanks for reporting,
> 
> Did anything else change before this error started appearing? Only your xcode version updated to 14.3? Was there anything else changed? What xcode version were you on before?

I haven't changed anything, I just updated the Xcode 13.4.1 => 14.3

**Comment by coderdave** [comment]
> Hi @gurbela and @coderdave,
> 
> Thanks for reporting,
> 
> Did anything else change before this error started appearing? Only your xcode version updated to 14.3? Was there anything else changed? What xcode version were you on before?

I started getting these errors after upgrading macOS to 13.3 and Xcode to 14.3.

FWIW, I still get these errors when changing the "Command Line Tools" to "Xcode 14.2"

![Screenshot 2023-04-03 at 4 44 32 PM](https://user-images.githubusercontent.com/964751/229624823-15774bed-c00d-4591-b627-4d8d05a03019.png)

**Comment by ray-holland-es** [comment]
Having same problem (did not upgrade macOS, but did update to xcode 14.3). Downgrading and changing cli tools to 14.2 did not resolve either. I removed Onesignal from Frameworks and libraries and it builds all of a sudden. Still need to test if Onesignal works - I doubt it.

**Comment by coderdave** [comment]
What is interesting, I was able to get the app to run on a physical device. However, I have noticed under "App Groups" the text is in red and when I click the "refresh button", I get "Unable to log in" with my account. Is this related?

**Comment by ray-holland-es** [comment]
It looks like libPods-OneSignalNotificationServiceExtension.a gets linked correctly for the physical device but not for the simulator. When you go to it in The Target -> General -> Frameworks and Libraries and open in finder, it will open for the device, but not for the simulator.

**Comment by ray-holland-es** [comment]
Figured it out. 

Launching Xcode 14.3 in Rosetta is no longer allowed.

In the new menu command Product → Destination → Destination Architectures → Show Rosetta Destinations or Show Both.

Then set your destination explicitly as a Rosetta simulator and it should work.

Though it would be nice to update react-native-onesignal to work without rosetta...

**Comment by jennantilla** [comment]
Thanks for the update, @ray-holland-es!  Glad to hear that explicitly setting the destination worked for you.

@coderdave and @gurbela, has this worked for you as well, or are you still having issues?

**Comment by KylixMedusa** [comment]
The rosetta solution works for now, but it would be great if onesignal could run normally on the non rosetta simulators as well.

**Comment by emawby** [comment]
@KylixMedusa I am not able to reproduce on my m1 mac. What version of cocoapods are you using?

**Comment by gurbela** [comment]
I couldn't solve this problem without updating the React Native version. Now I'm using the latest version of react-native and it's working fine

**Comment by gurbela** [comment]
This solution works for me

 ### 
      post_install do |installer|
          installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '5.0'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
      end
    end

**Comment by feriferdinan** [comment]
still got error

**Comment by feriferdinan** [comment]
still got this error

**Comment by ah584d** [comment]
any update ? the strange thing is that I'm receiving this error even working with rosetta

**Comment by ah584d** [comment]
this is what happened to me, I upgraded Xcode to 14.3.1 then downgraded  to 14.2.
The computer has been almost kill (PRO M1), I had no choice to continue using 14.3.1 with Rosetta simulator.
I discovered the solution by installing all my project on a clean fresh computer (PRO M1), and I saw that when running with Rosetta we see the symbol x86_64, and on my "polluted" mac, even with Rosetta it was logging arm64....
and then I arrived to these articles which confirm my...pain.
https://developer.apple.com/forums/thread/725563
https://armen-mkrtchian.medium.com/run-rosetta-simulator-on-xcode-14-3-381d341364ee

**Comment by ianlgnk** [comment]
> Figured it out.
> 
> Launching Xcode 14.3 in Rosetta is no longer allowed.
> 
> In the new menu command Product → Destination → Destination Architectures → Show Rosetta Destinations or Show Both.
> 
> Then set your destination explicitly as a Rosetta simulator and it should work.
> 
> Though it would be nice to update react-native-onesignal to work without rosetta...

Thanks, it fixed my problem!!
