### ISSUE TITLE
[Bug]: when build get warning: OneSignalPlugin: WARNING: OneSignalPlugin: Downgraded 'com.android.support:31.0.0' -> 28.+ to prevent compile errors! Recommend updating your project's compileSdkVersion!

### ISSUE THREAD

**Issue by hotaryuzaki** [OneSignal/react-native-onesignal#1511]
### What happened?

we use latest SDK and got warning when build the app:
```
OneSignalPlugin: WARNING: OneSignalPlugin: Downgraded 'com.android.support:31.0.0' -> 28.+ to prevent compile errors! Recommend updating your project's compileSdkVersion!
Values of variant API AnnotationProcessorOptions.arguments are queried and may return non final values, this is unsupported
```

the build was successful, but I do not know what the side effects of this

### Steps to reproduce?

```Markdown
i just upgrade my expo version to the latest 48
```

### What did you expect to happen?

no warning

### React Native OneSignal SDK version

4.5.1

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 4.18 GB / 15.55 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 20220123.190932.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @hotaryuzaki, thanks for reaching out! This warning comes from our Gradle plugin to protect against compiling errors. 

For our react-native SDK, you need to set the [compileSDKVersion to 33 or higher](https://documentation.onesignal.com/docs/react-native-sdk-setup#android-requirements).

Can you please share your current compileSDKVersion and whether upgrading resolves the warning?

Appreciate it!

**Comment by hotaryuzaki** [comment]
> Hi @hotaryuzaki, thanks for reaching out! This warning comes from our Gradle plugin to protect against compiling errors.
> 
> For our react-native SDK, you need to set the [compileSDKVersion to 33 or higher](https://documentation.onesignal.com/docs/react-native-sdk-setup#android-requirements).
> 
> Can you please share your current compileSDKVersion and whether upgrading resolves the warning?
> 
> Appreciate it!

we already have SDK version 33.
is it possible from any package in my node_modules?

**Comment by jennantilla** [comment]
Thanks for the additional information. Just to confirm, you only got this warning after upgrading to expo version 48?

**Comment by hotaryuzaki** [comment]
> Thanks for the additional information. Just to confirm, you only got this warning after upgrading to expo version 48?

I don't remember it, because this is a warning and I am still able to build the app.
And I don't know if I am just aware of it now or if it was already there before 48

**Comment by hotaryuzaki** [comment]
i'm still getting this issue, after i check everything in node_modules and get them updated.
can i get more specific debug info which package that triggered this issue?

**Comment by nan-li** [comment]
Hi, we have had no further reports of this. Please upgrade the OneSignal SDK if you or anyone is still having this issue. If this is still an issue, please open a new report with updated information.
