### ISSUE TITLE
[Bug]: setExternalUserId sets only one record when called twice in a row.

### ISSUE THREAD

**Issue by mljlynch** [OneSignal/react-native-onesignal#1515]
### What happened?

We set up SetExternalUid on the email call back. Now we are getting external uids attached to the email record, but not the push notification record. Is this expected behavior? 

My expectation would be that if I call code as follows - then both the push notification player record and email notification player record would be tagged with the same external UID. It seems however that the setting it in the email handler unsets it in the push notification record.

### Steps to reproduce?

```Markdown
OneSignal.setExternalUserId(uid);
      if (email) {
        OneSignal.setEmail(email, undefined, () => {
          // Note: we have to set the onesignal euid again in the callback so
          // the external user id is set correctly in the email record
          // see: https://documentation.onesignal.com/docs/email-sdk-methods#setemail-method
          OneSignal.setExternalUserId(uid);
        });
      }
```

### What did you expect to happen?

I would expect both the email and push notification record to have the external UID associated.

However, when using the above code, only the EMAIL record now has the external UID

### React Native OneSignal SDK version

4.4.1

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@mljlynch Thank you for reporting we will investigate

**Comment by mljlynch** [comment]
It appears this was fixed in https://github.com/OneSignal/react-native-onesignal/releases/tag/4.0.3, but I am on 4.4.1

**Comment by nan-li** [comment]
Hi, we have had no further reports of this. Please upgrade the OneSignal SDK if you or anyone is still having this issue. If this is still an issue, please open a new report with updated information.
