### ISSUE TITLE
[Bug]: Onesignal TestFlight to reject project because of Bitcode

### ISSUE THREAD

**Issue by Rommadon** [OneSignal/react-native-onesignal#1518]
### What happened?

Following XCode 14, Apple has depricated support for Bitcode. 

now causes a rejection in TestFlight/App Store with the following reason:
<img width="319" alt="Screenshot 2566-05-26 at 09 48 48" src="https://github.com/OneSignal/react-native-onesignal/assets/25241006/35a2c07d-0389-478f-93a1-566c46b344f5">

If I build my project and run otool on it, it does indeed show that it contains bitcode:
`otool -l OneSignal.framework/OneSignal | grep __LLVM -1
`
<img width="221" alt="Screenshot 2566-05-26 at 10 01 53" src="https://github.com/OneSignal/react-native-onesignal/assets/25241006/8e5ef7af-731f-46c2-bb8c-bb281d9135c1">

On xcode build setting
<img width="569" alt="Screenshot 2566-05-26 at 09 54 58" src="https://github.com/OneSignal/react-native-onesignal/assets/25241006/6da54f81-46af-4e31-9a33-da7c25649e74">
<img width="666" alt="Screenshot 2566-05-26 at 09 54 53" src="https://github.com/OneSignal/react-native-onesignal/assets/25241006/6603a1c6-3190-4335-a4f9-a4292d35f2dd">
<img width="581" alt="Screenshot 2566-05-26 at 09 54 49" src="https://github.com/OneSignal/react-native-onesignal/assets/25241006/b238fd72-a59f-4386-a6cb-5cfe652a5bae">
<img width="667" alt="Screenshot 2566-05-26 at 09 54 36" src="https://github.com/OneSignal/react-native-onesignal/assets/25241006/d2734d24-5763-4d85-91d1-166be20803da">

On Podfile setting build `ENABLE_BITCODE=NO`
`
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings["EXCLUDED_ARCHS[sdk=iphoneos*]"] = "armv7"
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
`

And xcodebuild command I add `ENABLE_BITCODE=NO` But still have contains bitcode issue 

### Steps to reproduce?

```Markdown
Xcode 14.3
"react-native-onesignal": "^4.5.1"

`
  - OneSignalXCFramework (3.12.4):
    - OneSignalXCFramework/OneSignalCore (= 3.12.4)
    - OneSignalXCFramework/OneSignalExtension (= 3.12.4)
    - OneSignalXCFramework/OneSignalOutcomes (= 3.12.4)
  - OneSignalXCFramework/OneSignalCore (3.12.4)
  - OneSignalXCFramework/OneSignalExtension (3.12.4):
    - OneSignalXCFramework/OneSignalCore
    - OneSignalXCFramework/OneSignalOutcomes
  - OneSignalXCFramework/OneSignalOutcomes (3.12.4):
    - OneSignalXCFramework/OneSignalCore
`

and upload .ipa to TestFlight
```

### What did you expect to happen?

without any issue

### React Native OneSignal SDK version

4.5.1

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @Rommadon thanks for your patience! 

Based on the info you've provided, it appears that you are already using the latest version of XCode and have set ENABLE_BITCODE to No in both the project and library settings. 

We had a [similar issue](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/659#issuecomment-635745617) a while back that was resolved by updating CocoaPods. Could you give that a go and let us know the results?

**Comment by jennantilla** [comment]
@Rommadon just following up to see if you're still having issues.

**Comment by jennantilla** [comment]
Closing due to no response. Please feel free to let us know if you are still having issues!

**Comment by wahas-mughal** [comment]
@Rommadon @jennantilla I fixed the issue by choosing ENABLE_BITCODE=NO in the build settings of OneSignalNotificationServiceExtension and Tests targets. In my case bitcode was enabled in those targets.

**Comment by iamrohitagg** [comment]
How to disable it? The bitcode settings does not show up for OneSignalNotificationServiceExtension for me

**Comment by emre-atilla** [comment]
Xcode 16 i have this issue
