### ISSUE TITLE
[Bug]: react native setExternalUserId app crashes

### ISSUE THREAD

**Issue by sekizlipenguen** [OneSignal/react-native-onesignal#1520]
### What happened?

hi,
When I compile and open the application, it closes automatically.

I realized that the source of the problem is the following function.

react native setExternalUserId 

<SKPaymentQueue: 0x600002414ec0>: No observers found that respond to "paymentQueue:shouldAddStorePayment:forProduct:", will not check for purchase intents

### Steps to reproduce?

```Markdown
react native setExternalUserId 

<SKPaymentQueue: 0x600002414ec0>: No observers found that respond to "paymentQueue:shouldAddStorePayment:forProduct:", will not check for purchase intents

-[__NSCFString characterAtIndex:].cold.1
NSRangeException - *** -[__NSArrayM objectAtIndexedSubscript:]: index 1 beyond bounds [0 .. 0]

 "react-native-onesignal": "4.5.1",

xcode 14.3 crashes
xcode 12.4 it works when compiled with this version
```

### What did you expect to happen?

urgent solution needed

### React Native OneSignal SDK version

4.5.1

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
-[__NSCFString characterAtIndex:].cold.1
NSRangeException - *** -[__NSArrayM objectAtIndexedSubscript:]: index 1 beyond bounds [0 .. 0]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @sekizlipenguen,

Thanks for reporting an issue, but there is not enough information to understand what is happening. This is **not** from react-native-onesignal:

```
<SKPaymentQueue: 0x600002414ec0>: No observers found that respond to "paymentQueue:shouldAddStorePayment:forProduct:", will not check for purchase intents
```

Please turn on verbose logging with `OneSignal.setLogLevel(6, 0)` and give the **full log** starting from when you call `OneSignal.setExternalUserId("SOME_USER_ID")`.

**Comment by jennantilla** [comment]
Closing due to no response.
