### ISSUE TITLE
[Bug]: not receiving notification ios 

### ISSUE THREAD

**Issue by AhmadAl-Ghalban** [OneSignal/react-native-onesignal#1522]
### What happened?

when send push notification in react native ios not received notification

after check Delivery status return this
Failed (Errored)

These errors are typically caused due to one of the following reasons:
Your OneSignal Application Settings are incorrect.
These tokens belong to an app that does not match your OneSignal settings.
Some other backend error occurred.

### Steps to reproduce?

```Markdown
install app and start work
working fine but not  received notification
```

### What did you expect to happen?

 received notification

### React Native OneSignal SDK version

4.5.0

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @AhmadAl-Ghalban can you please send your device a notification and share the log? More information on logging [here](https://documentation.onesignal.com/docs/sdk-reference#setloglevel-method).

Thanks!

**Comment by jennantilla** [comment]
Hi there @AhmadAl-Ghalban are you still having this issue? I'll go ahead and close this for now but please let us know if you are still having any difficulty receiving notifications.

More on not receiving notifications [here](https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown).

Thanks!
