### ISSUE TITLE
[question]: Firebase Cloud Messaging api/feature deprecation

### ISSUE THREAD

**Issue by jbrodriguez** [OneSignal/react-native-onesignal#1529]
### How can we help?

hi, we received a notifce from google, about some Firebase cloud messaging api/features being discontinued (by June 2024)

the question is, do OneSignal currently use the following apis/features:
- Legacy HTTP Protocol
issue: Sending messages via the Legacy HTTP API. 
new alternative: Send messages via the HTTP v1 API.

- Server keys
issue: Authenticating requests with server keys.
new alternative: Authenticate requests with [access tokens generated from authorized service accounts](https://notifications.google.com/g/p/ACUgQrFyWx71c96N5CDGtAj8fvNSyEU-qMf_jzKImdfd7w18avkd-WYqauxhEZC4AgkockzmdAOIHXDsEz1Y_HODTLg_X8asULOg0V0lte0YRq7WssPypKkeMcEjMjg2XyHhirD3iA6_7wrEYxfGHTquSYr4kO8MU6EqWEZpL7-QAU123by8v0JfJg3iA-4zR7YpWw9a8OvuPhW06sFePmUXFV6KF3FRQnqyXb5al9jS1FTqh108BroFd-nAEv1RhtKXk5NWXdFHVrY)

in our mobile app, we don't use fcm directly, only through OneSignal.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi there! We are aware of the deprecation of the legacy FCM and OneSignal will be updated to use FCM v1. At this moment, we do not have any information on when this is ready but we will update you as soon as we can. For the time being, no action is needed, you will be contacted when the new feature is released by OneSignal with further instructions on updating the credentials.

**Comment by jennantilla** [comment]
@jbrodriguez Update to this: Support for FCM v1 was released, and you can update your existing apps to use it on the OneSignal dashboard. Thanks!
