### ISSUE TITLE
Build without Cocoapods

### ISSUE THREAD

**Issue by GeoffreyPlitt** [OneSignal/react-native-onesignal#153]
I'm using RN=0.39 and I don't use Cocoapods. I'm able to build v1.2.3. But with v2.0.0 I get:

```
In file included from /Users/giro/stardust-app/node_modules/react-native-onesignal/ios/RCTOneSignal/RCTOneSignal.m:1:
/Users/giro/stardust-app/node_modules/react-native-onesignal/ios/RCTOneSignal/RCTOneSignal.h:4:9: fatal error: 'OneSignal/OneSignal.h' file not found
#import <OneSignal/OneSignal.h>
```

This happens even if every single header/framework search path setting is correctly set.

Probably just need to change that path or something; I'm not knowledgeable in XCode/Objective-C so I'm hoping somebody can help fix this.

**Comment by GeoffreyPlitt** [comment]
Here's a public repo that reproduces this problem: https://github.com/GeoffreyPlitt/react_native_minimal/tree/onesignal

**Comment by avishayil** [comment]
Please look at this example:
https://github.com/geektimecoil/react-native-onesignal/tree/master/examples/ios/OneSignalWithoutCocoa

**Comment by GeoffreyPlitt** [comment]
@avishayil This example does not exist in the 2.x branch

**Comment by GeoffreyPlitt** [comment]
@avishayil Please re-open, this was a false fix

**Comment by GroupXTech** [comment]
Any Idea as to when a fix will be completed? I really don't want to use pods. Thanks

**Comment by avishayil** [comment]
We're actively working on it

**Comment by GroupXTech** [comment]
Thanks man... I feel the pain... Upgrading past RN40 has big a huge pain with several libraries in our project.

**Comment by selcukitmis** [comment]
@avishayil we also waiting this to be fixed for using this in production. thanks in advance!

ping @baskan

**Comment by avishayil** [comment]
merged, tested and fixed.

**Comment by GroupXTech** [comment]
Just wanted to Say THANK YOU!!! and We appreciate your expedited hard work....

**Comment by avishayil** [comment]
@GroupXTech Our pleasure :>
