### ISSUE TITLE
[question]: iOS 30 sec delay on notification receive

### ISSUE THREAD

**Issue by mstankov** [OneSignal/react-native-onesignal#1533]
### How can we help?

Does anybody have an idea why every notification is received with a 30 second delay?

I've tested it on several different apple devices with different settings for battery, network etc and even with each setting set for best performance, the notifications from OneSignal are always received with a 30 second delay and I mean EXACTLY 30 seconds.

I can confirm that the iOS native side receives the notification after exactly 30 secs and immediately calls `setNotificationWillShowInForegroundHandler` on the JS side, which in turn calls `complete`.

react-native: 0.66.5
react-native-onesignal: latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @mstankov thanks for reaching out! Are you sending media attachments along with your notification? Adding an image to your notification could delay it up to 30 seconds as it downloads it. Can you try omitting your image temporarily to rule this factor out? Other causes for delayed notifications are mentioned [here](https://documentation.onesignal.com/docs/notifications-delayed#delays-for-notifications-on-ios-devices).

If you are still having issues, would you be able to send a [log](https://documentation.onesignal.com/docs/capturing-a-debug-log) from your device reproducing this issue?

Thanks!

**Comment by mstankov** [comment]
@jennantilla Hi Jenna, thanks for replying. I can confirm that no image is being sent yet the delay is always exactly 30 seconds. I checked the other potential causes and that doesn't seem to be the case either. I'll check the logs and send them over.

**Comment by jennantilla** [comment]
Hello @mstankov this issue has gone stale. I'm going to close it out but if you are still having issues please respond here and we'll be happy to investigate further!
