### ISSUE TITLE
How to use callback functions with ES6 generators? 

### ISSUE THREAD

**Issue by derdawid** [OneSignal/react-native-onesignal#154]
I want to use redux inside the callback. But to have access to yield function I need to pass Generator function instead of traditional. That doesn't work of course. Any idea how can do it? 

Sample code below, which doesn't work but shows the concept 

```es6
import { put, call, select } from 'redux-saga/effects'
import ConfigActions from '../Redux/ConfigRedux'
import { path } from 'ramda'
import OneSignal from 'react-native-onesignal'


// attempts to login
export function * registerPushNotification (api) {

  let onIdsAvailableCallback = function * (device) {
    console.log('available push token', device)

    yield put(ConfigActions.pushTokenAvailable(device.pushToken, device.userId ))
  }

  OneSignal.configure({
    onIdsAvailable: onIdsAvailableCallback
  })
}
```

**Comment by avishayil** [comment]
@ddereszewski Not that familiar with this syntax, but if someone can make a PR in order to make this component fully support `redux`, it would be great. Until then, i'm closing this issue.

**Comment by avishayil** [comment]
Hi @ddereszewski, check out this branch. It's WIP, but you'll find better support for redux here. 
https://github.com/geektimecoil/react-native-onesignal/tree/dev

**Comment by derdawid** [comment]
Sorry for late response. I was dealing with other issues with my app and now tried to get back on OneSignal with Generators. I see you link leads to 404 page now.
