### ISSUE TITLE
[Bug]: 5.0.0 types

### ISSUE THREAD

**Issue by rares-lupascu** [OneSignal/react-native-onesignal#1540]
### What happened?

which ones are correct?
```
OneSignal.User.login(id);
OneSignal.User.logout();
```
or
```
OneSignal.login(id);
OneSignal.logout();
```

the migration guide says the first ones are correct ... typescript says the second

### Steps to reproduce?

```Markdown
1. read the migration guide
```

### What did you expect to happen?

accurate types def

### React Native OneSignal SDK version

5.0.0

### Which platform(s) are affected?

- [x] iOS
- [x] Android

### Relevant log output

```Shell
Property 'login' does not exist on type 'typeof User'.ts(2339)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rgomezp** [comment]
Howdy @rares-lupascu ,
The second one is correct. We will make sure to update the migration guide to correct the error.

Thanks for bringing this to our attention.

Enjoy!

**Comment by manoharkharvi43** [comment]
Still the issue exits, in react-native Android it is working fine,  we are able to set external id's. But working with ios, app is getting initialized, but not able to set external id's.

for initializing app:

OneSignal.initialize(id);
OneSignal.Debug.setLogLevel(LogLevel.Verbose);

OneSignal.Notifications.requestPermission(true);

OneSignal.Notifications.addEventListener("click", (event) => {
  console.log("OneSignal: notification clicked:", event);
});


and for setting external id: 

OneSignal.login(EXTERNAL_ID);

**Comment by rares-lupascu** [comment]
> 

it is no a pb with the docs only ... typescript throws an error ... so it is possible that the types were not updated

**Comment by rares-lupascu** [comment]
in the docs
```
await OneSignal.Notifications.hasPermission()
```
returns a boolean value not a Promise ... so why should we await it?

further more hasPermission() return object on iOS (at least) when permissions have not been granted:
```
{"permission": false}
```

**Comment by Romick2005** [comment]
In migration guide:

![image](https://github.com/OneSignal/react-native-onesignal/assets/17779660/8be21b20-e7d7-47fe-9f70-f24a926f4082)
but in reality there are different names getId -> getPushSubscriptionId, getToken -> getPushSubscriptionToken

![image](https://github.com/OneSignal/react-native-onesignal/assets/17779660/5305e376-eb74-46ca-af2a-1b537a25ec13)

**Comment by Romick2005** [comment]
Methods getPushSubscriptionId and getPushSubscriptionToken are Promises only on Native side, but not for JS calls. 
![image](https://github.com/OneSignal/react-native-onesignal/assets/17779660/5bc1376b-6590-44ce-9530-7286ab8a633c)
![image](https://github.com/OneSignal/react-native-onesignal/assets/17779660/eff32403-21f8-4e25-abb4-ac1ace98d9be)
![image](https://github.com/OneSignal/react-native-onesignal/assets/17779660/80a9e2f1-a5a9-423a-96e9-7072513a60f2)

**Comment by KodyKendall** [comment]
I'm having a similar issue when reading the migration guide and the mobile SDK guide. In the mobile SDK guide, under react-native it says: ```OneSignal.User.PushSubscription.optIn();```
But when I attempt that with package.json of "react-native-onesignal": "^5.0.0". I get the following error: ```Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read properties of undefined (reading 'optIn')```.

Same with: ```const pushSubscriptionId = await OneSignal.User.PushSubscription.getPushSubscriptionId();```. I get a similar error: ```possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read properties of undefined (reading 'getPushSubscriptionId')```

**Comment by nan-li** [comment]
Hi all, thank you for pointing out these inconsistencies with the migration guide. 

We are fixing the migration guide.
There is no need to await any of these calls:
 
```typescript
OneSignal.Notifications.hasPermission()
OneSignal.User.pushSubscription.getPushSubscriptionId()
OneSignal.User.pushSubscription.getPushSubscriptionToken()
OneSignal.User.pushSubscription.getOptedIn()
```
Additionally, we will need to fix the permission boolean (it is an object and need to be fixed).

@manoharkharvi43 - Can you explain the issue you have with iOS when logging into an external_id? What is the error?

@KodyKendall - Change the casing of `pushSubscription` to `OneSignal.User.pushSubscription.optIn()`. This was one of the changes we made after the beta releases ([in 5.0.0 release](https://github.com/OneSignal/react-native-onesignal/releases/tag/5.0.0))

**Comment by manoharkharvi43** [comment]
Hi ,
I am using one signal for push notification and in app notification(in app
pop-up), it is working in both IOS and and Android. But the issue is while
setting an external-id.
In android i am able to set external-id, it is working. But when it comes
to IOS it is not setting.
I am using a one-signal version : v5 (5.0.0)
I am using the onesignal.login() function to set external-id.

**Comment by Romick2005** [comment]
![image](https://github.com/OneSignal/react-native-onesignal/assets/17779660/6a684a8a-42b1-4648-93bd-f4833ec7820f)
As it turns out from server error response "identity.external_id" need to be string, not a number.

**Comment by nan-li** [comment]
Hi @manoharkharvi43, can you turn on verbose logging by `OneSignal.Debug.setLogLevel(LogLevel.Verbose)` and share the logs when you call `OneSignal.login`? We need more information to know what is not working for you.

Hi @Romick2005 yes the identity object needs to be string values, thanks for catching this error in the type.

**Comment by arnaudambro** [comment]
> I'm having a similar issue when reading the migration guide and the mobile SDK guide. In the mobile SDK guide, under react-native it says: `OneSignal.User.PushSubscription.optIn();` But when I attempt that with package.json of "react-native-onesignal": "^5.0.0". I get the following error: `Possible Unhandled Promise Rejection (id: 0): TypeError: Cannot read properties of undefined (reading 'optIn')`.
> 
> Same with: `const pushSubscriptionId = await OneSignal.User.PushSubscription.getPushSubscriptionId();`. I get a similar error: `possible Unhandled Promise Rejection (id: 0): TypeError: Cannot read properties of undefined (reading 'getPushSubscriptionId')`

@ KodyKendall 

it's not `OneSignal.User.PushSubscription.optIn` but `OneSignal.User.pushSubscription.optIn`

with `p` and not `P`

**Comment by FazilMuhammed** [comment]
@arnaudambro @rgomezp  Anyone please help me how get player id / External ID react native oneSignal version 5+

  const state = await OneSignal.getDeviceState();
  const userID = state.userId;


this is not working

**Comment by nan-li** [comment]
All type errors, documentation, and migration guide inconsistencies reported in this issue have since been fixed.
Did not get a response after asking for logs.

@FazilMuhammed `getDeviceState` has been removed in `v5.x.x`. Here is how you can get these values:
1. `externalId` -> this is set by you, but we will soon add a getter for the `externalId` of the current user in the SDK. Look out for our next couple of releases.
2. player ID -> this has been replaced with subscription ID (representing the push subscription) and can be retrieved via `const id: string = OneSignal.User.pushSubscription.getPushSubscriptionId()`
3. onesignal ID is a new identifier that will represent a user, who can have multiple subscriptions. We will also add a getter for the `onesignalID` in a release soon.
