### ISSUE TITLE
[question]: How to remove a user, or at least remove their location data?

### ISSUE THREAD

**Issue by stilllovinnero** [OneSignal/react-native-onesignal#1542]
### How can we help?

Hey,

we are using OneSignal to track users location and to send push notifications based on their location in our react native app.

As Google Play is soon requiering users to be able to delete the collected user data (https://support.google.com/googleplay/android-developer/answer/13327111?hl=en) we are searching for a way to delete a user entry from OneSignal, but we were not able to find informations about this in the mobile SDK documentation. (https://documentation.onesignal.com/docs/mobile-sdk) 

Are we looking at the right place?
Does using OneSignal even fall under this new GooglePlay policy?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @stilllovinnero thanks for reaching out! 

You can delete users a number of ways, outlined [here](https://documentation.onesignal.com/docs/delete-users).

Location information is only collected if the user has granted permission to the App to collect this, and the app chooses to send this data to OneSignal. If you need to remove this data, you can use our [Update User API](https://documentation.onesignal.com/reference/update-user) and change the `lat` and `long` params.

Let us know if you have any additional questions or concerns!

**Comment by stilllovinnero** [comment]
Hey @jennantilla, 

thank you for your quick response! We managed to remove a subscription via the API! 
It would be nice to have this function in the react Sdk :)

Cheers!
