### ISSUE TITLE
Programmatically control  - request IOS permissions - enhancement

### ISSUE THREAD

**Issue by GroupXTech** [OneSignal/react-native-onesignal#155]
We're experiencing a large percentage of users opting out of push notifications. Ideally we would like to have the pushnotification permission request be delay by one day after the initial app download. From what I can tell all of this is controlled RCTOnesignal.m file.  Can this be reworked to have permissions controlled in the javascript to allow us to set an a flag in async storage to check against the 2nd time a person uses our app, then request permissions.

We're trying to cutdown on the bombardment of Permission requests on download and increase the percentage of authorized permissions.

Thank you in advance.

**Comment by avishayil** [comment]
@jkasten2

**Comment by GroupXTech** [comment]
I figured it out. You do have this method available. I missed it in your docs.
 - "Call when you want to prompt the user to accept push notifications. Only call once and only if you passed false to *initWithLaunchOptions autoRegister*:."
