### ISSUE TITLE
[Feedback]: Update documentation for the custom push notification sound files location

### ISSUE THREAD

**Issue by Romick2005** [OneSignal/react-native-onesignal#1556]
### What's on your mind?

The path for React Native sound should be 
`<project-root>/android/app/src/main/res/raw`
and not 
`<project-root>/android/app/res/raw`
![image](https://github.com/OneSignal/react-native-onesignal/assets/17779660/8f014106-dec3-4c01-8ad1-a6dd349d65d8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @Romick2005, thanks for pointing this out! The documentation has been [updated](https://documentation.onesignal.com/docs/customize-notification-sounds#android-and-amazon).
