### ISSUE TITLE
[question]: Get player id in version 5.0

### ISSUE THREAD

**Issue by k4t4r1n4** [OneSignal/react-native-onesignal#1557]
### How can we help?

Hi!
I'm struggling to get player id in version 5.0.
I've tried `const pushNotificationsDeviceId = (await OneSignal.getDeviceState()).userId;` but seams like OneSignal.getDeviceState() method is deprecated in v5.
Can you help me to get player id so I can sent it in a body as "include_player_ids" and post it to https://onesignal.com/api/v1/notifications on backend side?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @k4t4r1n4 thanks for reaching out! That's correct, getDeviceState is deprecated in 5.0.0. The new id to look for is [`getPushSubscriptionId`](https://documentation.onesignal.com/docs/mobile-sdk#subscription-id).

Let us know if you have any additional questions or concerns!
