### ISSUE TITLE
[Feedback]: Documentation: Invalid Android Java requestPermission parameters.

### ISSUE THREAD

**Issue by Romick2005** [OneSignal/react-native-onesignal#1559]
### What's on your mind?

Method OneSignal.getNotifications().requestPermission has only one parameter 
`requestPermission(Continuation);`
but it should look like 
`requestPermission(true, Continuation);`

![image](https://github.com/OneSignal/react-native-onesignal/assets/17779660/a9a6d9da-6339-49c0-9903-ec8200551c60)
![image](https://github.com/OneSignal/react-native-onesignal/assets/17779660/157f67f2-0638-448f-a5e3-964ad50fe95c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
@Romick2005 thanks for pointing this out! We've updated the [documentation](https://documentation.onesignal.com/docs/android-sdk-setup#2-initialization).
