### ISSUE TITLE
[Bug]: Notification.canRequestPermission always returns true

### ISSUE THREAD

**Issue by ChromeQ** [OneSignal/react-native-onesignal#1560]
### What happened?

According to the docs the `Notification.canRequestPermission()` should "Return true if the device has never been prompted for push notification permission."
https://documentation.onesignal.com/docs/mobile-sdk#checking-if-a-permissions-prompt-can-be-displayed

However I am finding that the method always returns true, despite being shown the permission request (using `Notifications.requestPermission()`) and denying it multiple times. 

I have only tested Android but may also affect iOS but not tested.

### Steps to reproduce?

```Markdown
const canAsk = await OneSignal.Notifications.canRequestPermission();
console.log('CAN ASK', canAsk); // <-- Always `true`

if (canAsk) {
  const granted = await OneSignal.Notifications.requestPermission();
  console.log('REQUESTING', granted);
} else {
  console.log('REQUESTING FAILED');
}
```

### What did you expect to happen?

Expected the `canAsk` method to return `false` when the permission has been denied

### React Native OneSignal SDK version

5.0.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShivamKJJW** [comment]
In android it has been set to behave that way.
<img width="716" alt="image" src="https://github.com/OneSignal/react-native-onesignal/assets/21214249/4608a57f-8502-4ee9-9b75-25df75dd0637">

RNOneSignal.java>Line 439

**Comment by ChromeQ** [comment]
What! That's crazy! Why would it do that? Is there no way to determine if I can/should show a custom message about turning on notifications in the settings?

Do you work at OneSignal? Can somebody at OneSignal explain this? The description (and the fact it is a Boolean) suggests it could be true or false.

**Comment by ovidb** [comment]
This is indeed "a bit" unexpected. Maybe that should be the case for android 12 and older but for everything this seems very wrong.

**Comment by nan-li** [comment]
Hi everyone, thanks for reporting this and we have fixed the Android implementation in the latest [release 5.0.1](https://github.com/OneSignal/react-native-onesignal/releases/tag/5.0.1).
