### ISSUE TITLE
[question]: how to change the text of the alert about denying notification permissions

### ISSUE THREAD

**Issue by whyamsx** [OneSignal/react-native-onesignal#1561]
### How can we help?

I searched many lines in the documentation and could not find a way to change the text in this **alert** to what I need.
Our application is not in English and we need the function of redirecting the user to settings, but in a language they can understand.

Is it possible to change this?
<img width="290" alt="image" src="https://github.com/OneSignal/react-native-onesignal/assets/62172551/fb4f03cc-d23c-485a-9cab-41370da5d313">

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
@whyamsx thank you for your patience! When are where are you seeing this alert? I could be wrong but this looks like a native alert of the device itself? Any additional steps to reproduce this is appreciated!

**Comment by jennantilla** [comment]
Closing due to no response.
