### ISSUE TITLE
[i am using in my react native app onesignal version 4.5.0 but onesignal's update their version with 5.0.0 know i did not get OneSignal.getDeviceState() function because they change their functions , this function is not recongnized in new new version how i get DeviceState]: 

### ISSUE THREAD

**Issue by MuhammadAkbar6722** [OneSignal/react-native-onesignal#1562]
### How can we help?

OneSignal.Debug.setLogLevel(LogLevel.Verbose);

// OneSignal Initialization
OneSignal.initialize("key")

 

 
 
OneSignal.Notifications.requestPermission(true);

// Method for listening for notification clicks
OneSignal.Notifications.addEventListener('click', (event) => {
    console.log(event , "LLLLLL")
  console.log('OneSignal: notification clicked:', event);
})

 
      

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VenkateshhDasari** [comment]
yes for me also i am not able to get that function any one please help

**Comment by MehmetDT** [comment]
me too

**Comment by Romick2005** [comment]
But you do not mention what data do you need? Except the fact that function is missing (removed).

**Comment by nan-li** [comment]
Hi @MuhammadAkbar6722, the general `getDeviceState()` method has been removed and the information has been split across namespaces. 

What information are you looking for?

Please see the[ migration guide](https://github.com/OneSignal/react-native-onesignal/blob/major_release_5.0.0/MIGRATION_GUIDE.md) for all the methods and information you can retreive on the 5.0.0 major release.

**Comment by FazilMuhammed** [comment]
Initially tokens, id not getting.if any changes made in code and save then only values getting.please help to get automatically value gets initially app open

**Comment by nan-li** [comment]
Hi @FazilMuhammed,
If you are looking for the current device’s push subscription, information can be retrieved via:

```javascript
const id = OneSignal.User.pushSubscription.getPushSubscriptionId();
const token = OneSignal.User.pushSubscription.getPushSubscriptionToken();
const optedIn = OneSignal.User.pushSubscription.getOptedIn();
```

**Comment by MattFixesFaults** [comment]
You find a conversion of old v4 to v5 functions in their quite hidden migration doc:
https://github.com/OneSignal/react-native-onesignal/blob/major_release_5.0.0/MIGRATION_GUIDE.md
