### ISSUE TITLE
[Bug]: Android app crashes if call OneSignal.Notifications.requestPermission()

### ISSUE THREAD

**Issue by AGavrilovOnTarget** [OneSignal/react-native-onesignal#1586]
### What happened?

After call requestPermission i get this error:

`
Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
`
<img width="237" alt="Crash error" src="https://github.com/OneSignal/react-native-onesignal/assets/66670578/9372633b-b264-4b29-94b3-5f35d442b7f5">

### Steps to reproduce?

```Markdown
1. Install `react-native-onesignal` v5.0.2
2. Add code:
import { OneSignal } from "react-native-onesignal";
OneSignal.initialize(Config.ONESIGNAL_APP_ID); // or paste you id

const initializePushNotifications = async () => {
  const [hasPermission] = await OneSignal.Notifications.requestPermission();
}
initializePushNotifications();

3. Launch Android the app
4. App crashed


buildToolsVersion = "33.0.0"
minSdkVersion = 21
compileSdkVersion = 33
targetSdkVersion = 33
ndkVersion = "23.1.7779620"
kotlinVersion = "1.8.0"
```

### What did you expect to happen?

App started successfully. 

### React Native OneSignal SDK version

5.0.2

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@AGavrilovOnTarget Hello thank you for reporting unfortunately I am not able to reproduce the issue. Does this happen on fresh installs of your app? Are you able to reproduce this on a blank app with OneSignal integrated?

**Comment by AGavrilovOnTarget** [comment]
@emawby Hello, not yet, will try to reproduce

**Comment by nysamnang** [comment]
I encountered the same issue. It happens when we don't pass the parameter to `requestPermission()` method.

To resolve this, just pass the boolean value `true` or `false` to `OneSignal.Notifications.requestPermission(false)`.

Have a nice day!

**Comment by AGavrilovOnTarget** [comment]
thanks, i passed `true` and it's working
