### ISSUE TITLE
[Bug]:  No tags appears in dashboard after i send them with Onesignal.User.addTags()

### ISSUE THREAD

**Issue by ihar-dambrouski** [OneSignal/react-native-onesignal#1589]
### What happened?

No tags appears in dashboard after i send them with Onesignal.User.addTags(); No errors in console, all is ok. 

<img width="840" alt="image" src="https://github.com/OneSignal/react-native-onesignal/assets/60747836/fc00660c-b0ca-4abb-bbdd-d8be101cf9c4">
<img width="707" alt="image" src="https://github.com/OneSignal/react-native-onesignal/assets/60747836/ca242368-89fc-4b61-973b-c071c48581b5">
<img width="573" alt="image" src="https://github.com/OneSignal/react-native-onesignal/assets/60747836/818a1361-b7d1-41a4-8430-7933e71ae440">
<img width="677" alt="image" src="https://github.com/OneSignal/react-native-onesignal/assets/60747836/a0f57257-d522-43c9-829a-240640a7c77d">

### Steps to reproduce?

```Markdown
1) Initialize sdk OneSignal.initialize('id');
2) Try to add tags with Onesignal.User.addTags()
```

### What did you expect to happen?

I want to see tags in dashboard attached to user

### React Native OneSignal SDK version

5.0.2

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iAmWillShepherd** [comment]
I think you tagged the wrong version. `addTags` is now `sendTags` in version 5.0.2. Please update to the latest version and confirm this issue still happens there.

**Comment by ihar-dambrouski** [comment]
<img width="626" alt="image" src="https://github.com/OneSignal/react-native-onesignal/assets/60747836/aa398e14-d15f-48a9-a62f-3b41b847d669">
<img width="850" alt="image" src="https://github.com/OneSignal/react-native-onesignal/assets/60747836/f3771147-2b70-4757-a483-633f999d6cec">
@iAmWillShepherd

**Comment by jennantilla** [comment]
Hi @ihar-dambrouski! Sorry for the mix up, you had it correct the first time with [`addTags`](https://documentation.onesignal.com/docs/data-tag-implementation#adding-multiple-tags-at-once).

I can't quite tell from the code you provided, are you adding the tags as an object? I see you passing in `newTags` as a parameter but am unsure of its type.

Here is an example:
`OneSignal.User.addTags({my_tag1: 'my_value', my_tag2: 'my_value2'});`

If you are still having issues, can you please send the [full log](https://documentation.onesignal.com/docs/capturing-a-debug-log) so we can help diagnose?

Thanks!

**Comment by jennantilla** [comment]
Closing this issue due to no response. @ihar-dambrouski if you are still having issues please let us know, we'd be happy to help!
