### ISSUE TITLE
[Bug]: Notifications.addPermissionListener('click', e...) doesn't seem to be firing

### ISSUE THREAD

**Issue by peetaloo** [OneSignal/react-native-onesignal#1596]
### What happened?

We're migrating to OneSignal v5 and encountered an issue with the notification permission observer in our React Native/Expo app. 

Previously in v4, we had an `addPermissionObserver(e)` tracking the result of the native push permission prompt (allow or deny) and would run a function depending on which result was returned. 

In v5 however, when trying to do the same thing with:
```
Notifications.addEventListener('click', e => {
    console.log('Notif click event', e)
  })
```
the click event never fires. (The `console.log` never runs).

With `addEventListener('permissionChange', e...)`, it only triggers when we press "Allow" (returns true) on the native permission prompt. Pressing "Deny" or dismissing the prompt doesn't trigger the event listener at all. (No console.log, no event.) Not sure if thats intended? 

I thought it might've been an issue with the listener being removed before it could fire but that doesn't seem to be the case as the `permissionChange` event is triggered on "allow" and logging the `removeEventListener()` appears only when closing the app.

Tested on an Android device running Android 13.

### Steps to reproduce?

```Markdown
Package versions:
"react-native-onesignal": "5.0.2"
"onesignal-expo-plugin": "2.0.2"
"expo": "49.0.8"

On Android 13. We're pretty sure its happening on iOS as well.
```

### What did you expect to happen?

Expected the Notifications `click` event to return something.

### React Native OneSignal SDK version

5.0.2

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @peetaloo, thanks for reaching out. I see you are reporting two issues.

**Notification click listener**
- The click listener should fire anytime a notification is opened whether it is from the background or from a killed state.
- Is this consistent behavior or does the click listener sometimes fire and sometimes not? 
- Is this notification opened while the app is killed or while the app is in the background?

**Permission change listener**
- It should fire when there is a **change**. So, on a new app install with Android 13, it will start out with no push permission yet (hasPermission is `false`). Then, prompting for push and choosing deny will **not** fire the permission listener as it has not changed. You can check the permission status by `OneSignal.Notifications.hasPermission()`

**Comment by peetaloo** [comment]
Hi @nan-li thanks for getting back to me. 

**Notification click listener**
- I think I misunderstood what the click listener was for. I assumed it was for listening to the clicked action of a native prompt like the native push prompt. Just to confirm, the "click" is for when a user presses on a push notification?

**Permission change listener**
- Yea that makes sense. Thanks for clearing that up.

**Comment by nan-li** [comment]
Hi @peetaloo 

> 
> **Notification click listener**
> 
> I think I misunderstood what the click listener was for. I assumed it was for listening to the clicked action of a native prompt like the native push prompt. Just to confirm, the "click" is for when a user presses on a push notification?

Yes,  the "click" is for when a user presses on a push notification, and you can get information about their interaction with the notification.
