### ISSUE TITLE
Show permissions prompt later

### ISSUE THREAD

**Issue by skizzo** [OneSignal/react-native-onesignal#16]
Hi and thanks for this amazing toolset.
I'd like to know, is there a way to "delay" the prompt that shows when the app starts and asks the user for permissions to send notifications?
Thanks!

**Comment by ghost** [comment]
See my PR #13

**Comment by micksabox** [comment]
Whoops. Wrong account used for the last comment.

**Comment by skizzo** [comment]
Looks good @micksabox, let's hope that the pull request makes it into the repo soon :+1:
