### ISSUE TITLE
Apple Mach-O Linker Error in example app

### ISSUE THREAD

**Issue by bitsal** [OneSignal/react-native-onesignal#160]
I can't run example app in XCode tool.
<img width="1191" alt="screen shot 2017-01-24 at 3 25 10 pm" src="https://cloud.githubusercontent.com/assets/5635839/22247163/65560cf6-e249-11e6-848f-633aeaedc1f5.png">

Steps:

1. clone the repo
2. switch to tag `v3.0.0`
3. Go to `examples/OneSignalRNExample`
4. `npm i`
5. `cd ios && pod install`
6. go to XCode and press Run 

Could you help me to find where I did a mistake?

P.S.:
I've encountered the issue like these:
https://github.com/geektimecoil/react-native-onesignal/issues/19
https://github.com/geektimecoil/react-native-onesignal/issues/133
and decided to compare your example app with mine to be sure I don't miss anything.
Everything was OK until I updated to React 0.40.0 and all related modules.

**Comment by avishayil** [comment]
Did you Run from the XCode project or workspace?
Make sure you entered the workspace.

**Comment by avishayil** [comment]
By the way, the full example is updated to RN 0.32, which is compatible with version `v1.2.3`. I definitely need to update it to RN 0.40.

**Comment by logileifs** [comment]
I'm also encountering the same bug in a project with react-native version 0.37. Installed using Cocoapods and followed all the installation instructions. The weird thing is that when I did the same in a clean project with same version it worked.

**Comment by bitsal** [comment]
@avishayil When I run it from workspace it starts working. My fault.
BTW,
I would like to see an example with 0.40.0 react native.

**Comment by logileifs** [comment]
Can this issue be re-opened? I'm still encountering this bug. I can provide more details if needed

**Comment by logileifs** [comment]
For me it worked to add "${PODS_ROOT}/OneSignal/iOS_SDK/Framework" to `any architecture` in Framework search paths.

![screen shot 2017-01-26 at 14 34 36](https://cloud.githubusercontent.com/assets/2317815/22335040/f38bd640-e3d4-11e6-8d36-4b50f74f52e9.png)

**Comment by bitsal** [comment]
I'm using pod this line was added automatically I guess. At least there is nothing in *.xcodeproj file.

**Comment by pravinagrawal145** [comment]
I got the same issue while I'm trying to run on iOS 7s Plus 10.3.1.
I tried to reopen Xcode and restart the React packager. It works for me.
