### ISSUE TITLE
[Bug]: Unable to determine the Notification Permission status on android via getDeviceState()

### ISSUE THREAD

**Issue by theo-wall** [OneSignal/react-native-onesignal#1600]
### What happened?

We are trying to monitor if the user has either not decided on notification permission, granted, or denied push notifications. This is possible on iOS through the `notificationPermissionStatus` field. But on android this field is not present and we are enable to check their permission status outside of `hasNotifcationPermision`: `false`(default)/`true`. 

### Steps to reproduce?

```Markdown
1. Install 4.5.1 react-native-onesignal
2. Fetch device state using `OneSignal.getDeviceState()` 
3. Check on iOS `notificationPermissionStatus` field is returned
4. Check on android `notificationPermissionStatus` field is missing
```

### What did you expect to happen?

I am expecting `notificationPermissionStatus` field to be returned on iOS and Android

### React Native OneSignal SDK version

Release 4.5.1

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
iOS output:
{"hasNotificationPermission": false, "isEmailSubscribed": false, "isPushDisabled": false, "isSMSSubscribed": false, "isSubscribed": false, "notificationPermissionStatus": 0, "pushToken": "<token>", "userId": "<user-id>"}

android output:
{"hasNotificationPermission": false, "isEmailSubscribed": false, "isPushDisabled": false, "isSMSSubscribed": false, "isSubscribed": false, "pushToken": "<token>", "userId": "<user-id>"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @theo-wall thank you for your patience!

I will bring this up to the team regarding adding `notificationPermissionStatus` to Android. We will be moving away from the player version of our SDKs (<=4.x.x) in favor of our new major release (5.x.x). 

This new version does not have `getDeviceState`, it does offer a [new method](https://documentation.onesignal.com/docs/mobile-sdk#checking-push-notification-permissions) for getting notification permission status. I'd encourage you to look at the [migration guide](https://github.com/OneSignal/react-native-onesignal/blob/major_release_5.0.0/MIGRATION_GUIDE.md) and consider upgrading to our latest major release.

Thanks!

**Comment by theo-wall** [comment]
@jennantilla I was worried that was going to be the answer. It looks like we will have to look into updating to 5.x.x. Thanks for the response!
