### ISSUE TITLE
[Bug]: React native - Push notifications are not received in iOS when app is running ( Foreground )

### ISSUE THREAD

**Issue by vaibhav-toddleapp** [OneSignal/react-native-onesignal#1604]
### What happened?

Push notifications are not showing up when app is running, there is no alert / no banner in notification center of iOS. works fine when app is in background or not in the memory ( killed ).

Observed this issue suddenly. please verify for iOS 15 or 15+ devices.

Libraries: 
```
"react-native-onesignal": "4.4.1"
```

PodFile:
```
target 'OneSignalNotificationServiceExtension' do
    pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
  end
```

### Steps to reproduce?

```Markdown
1. Setup onesignal react native SDK
2. Run app in iOS physical device
3. trigger notification when app is running ( in foreground )
```

### What did you expect to happen?

Should show alert / banner in notification center even when app is running.

### React Native OneSignal SDK version

4.4.1

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @vaibhav-toddleapp! Would you be able to share the [log](https://documentation.onesignal.com/docs/capturing-a-debug-log) from your device reproducing this behavior? Also, we have a new major release that offers many improvements and enhancements that you're encouraged to check out! See the migration guide [here](https://github.com/OneSignal/react-native-onesignal/blob/major_release_5.0.0/MIGRATION_GUIDE.md).

**Comment by jennantilla** [comment]
Closing due to no response. @vaibhav-toddleapp if you are still having issues please let us know!
