### ISSUE TITLE
(OneSignalNotificationServiceExtension )I got error on build with recat native sdk. How to fix it and what did i do wrong ?

### ISSUE THREAD

**Issue by tuugi0113** [OneSignal/react-native-onesignal#1606]
### How can we help?

Error I got : 
OneSignalNotificationServiceExtension
Sandbox: bash(18062) deny(1) file-read-data /Users/xades/Desktop/workspace/xot/xs-main-native/ios/Pods/Target Support Files/Pods-xs_core_native-OneSignalNotificationServiceExtension/expo-configure-project.sh
things i changed : 
iOS Podfile :
  target 'exadsasd' do
    inherit! :complete
    # Pods for testing
![Screenshot 2023-11-27 at 10 06 47](https://github.com/OneSignal/react-native-onesignal/assets/108115660/83c894fc-ce89-46ae-b424-04a9b09bef29)

  end

  target 'OneSignalNotificationServiceExtension' do
    pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'
    pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'
  end
   Xcode version : 15.0.1
   react native version : 0.72.4
   react version 18.2.0 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by serolgames** [comment]
Have you tried to reinstall completely step by step with oneSignal documentation ?

**Comment by jennantilla** [comment]
Hello @tuugi0113 apologies that this issue has gone stale Did going back through the documentation as  @serolgames suggested help? 

If this still a concern for you please respond here and we can discuss further.

Thanks!

**Comment by opeyemiagbeja** [comment]
@tuugi0113 did you resolve this ?

**Comment by sarowerj** [comment]
I was facing same issue with react-native 0.80.1. Here is my issue details: 

`Sandbox: bash(32861) deny(1) file-write-create /Users/**/**/**/**/ios/Pods/resources-to-copy-OneSignalNotificationServiceExtension.txt`

Solution: I just disabled` User Script Sandboxing `by selecting `No`. And the issue has been solved. 

<img width="1250" height="234" alt="Image" src="https://github.com/user-attachments/assets/8e00290c-009b-4593-a528-1257956f76d2" />
