### ISSUE TITLE
[Bug]: Build fails with Framework not found OneSignalUser after adding onesignal.

### ISSUE THREAD

**Issue by harrisrobin** [OneSignal/react-native-onesignal#1607]
### What happened?

Hello, 

I am trying to setup OneSignal on our iOS app. Our app has two flavours (targets), Staging & Prod. 
As a result, I created two extensions targeting each respective target (please advise if this is a bad idea):

![CleanShot 2023-11-30 at 12 41 16@2x](https://github.com/OneSignal/react-native-onesignal/assets/3880008/26d77694-23ed-4c16-a1c0-b765f768bd6c)

I've had quite a few issues getting it to work, latest one solved by making sure that the deployment targets match. However, now I get: Framework not found OneSignalUser and there does not seem to be any issues about this particular error here. 

![CleanShot 2023-11-30 at 12 43 07@2x](https://github.com/OneSignal/react-native-onesignal/assets/3880008/3d9ee4bf-2281-4995-88a2-f13abc0ee119)

In my podfile, i have:
```
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'
end

target 'OneSignalNotificationServiceExtensionStaging' do
  pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'
end

```

Any ideas what could be causing this?

### Steps to reproduce?

```Markdown
1. Install react-native-one-signal `^5.0.3`
2. Use xcode `15.0.1`
3. use react-native `0.72.6`
```

### What did you expect to happen?

I expect my app to build, right now the build fails ever since i added onesignal due to the error above.

### React Native OneSignal SDK version

5.0.3

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harrisrobin** [comment]
When I delete the extension target and re-add it, i now get: `No such module 'OneSignalExtension'`

![CleanShot 2023-11-30 at 12 55 39@2x](https://github.com/OneSignal/react-native-onesignal/assets/3880008/99333dab-ff5d-41b1-8033-d0fac7bcd9ea)

**Comment by harrisrobin** [comment]
Doing the [following](https://github.com/OneSignal/react-native-onesignal/issues/1451#issuecomment-1650008635) eventually fixed the issue for me. Seems odd that I have to do this, i am working on a standard project so this seems like it should be included in the docs?

Will close this, thanks

**Comment by fedeolto** [comment]
For the ones landed here because getting "No such module 'OneSignalExtension'" error: 
https://documentation.onesignal.com/docs/troubleshooting-ios#no-such-module-onesignal

Also looks like having 2 notifications services, one per target is the right way:
https://documentation.onesignal.com/docs/troubleshooting-ios#can-we-setup-multiple-notification-service-extensions-for-multiple-targets-in-single-xcode-project
