### ISSUE TITLE
[Bug]: Empty subscription id

### ISSUE THREAD

**Issue by nachos5** [OneSignal/react-native-onesignal#1608]
### What happened?

For a decent chunk of our users (about 4%), a push notification subscription is not being created.

The response from `OneSignal.initialize` is the following for these users:

```json
{
  "notificationPermission": true,
  "pushSubscriptionState": {
    "id": "",
    "optedIn": true,
    "token": "ftjo7cue........."
  },
  "result": "success"
}
```

As you can see, the subscription id is empty.

### Steps to reproduce?

```Markdown
I can't reproduce this myself, but from Sentry I can see that this is the response for these users.
```

### What did you expect to happen?

I expect the SDK to create a valid subscription.

### React Native OneSignal SDK version

5.0.3

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by serolgames** [comment]
Then it's probably an issue on your side, 

Are you really sure 100% that you set your id properly and that there is no risk that you login an empty id to one signal ?

**Comment by nan-li** [comment]
Hi @nachos5, there is no response from `OneSignal.initialize("appId")`. What is your code that is returning this?
``` 
{
  "notificationPermission": true,
  "pushSubscriptionState": {
    "id": "",
    "optedIn": true,
    "token": "ftjo7cue........."
  },
  "result": "success"
}
```

Additionally, it may take varying length of time to receive the subscription_id if you are getting it too soon after calling `OneSignal.initialize()`.
