### ISSUE TITLE
[question]: OneSignal + Multi Stage/Flavour Environment

### ISSUE THREAD

**Issue by LucasReinaldo** [OneSignal/react-native-onesignal#1612]
### How can we help?

Hey folks, I am trying to set my react native app to support a multi-stage environment so I can have a dev, staging and prod app.

The issue is when trying to build the dev and staging (iOS) I get an error:

`Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier.`

I guess I need to add a dynamic suffix to handle the different envs? Has anyone done that? Some screenshots, guides, code, repo are welcome!

Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LucasReinaldo** [comment]
well, for those wondering: https://documentation.onesignal.com/docs/troubleshooting-ios#can-we-setup-multiple-notification-service-extensions-for-multiple-targets-in-single-xcode-project

you need to create another NSE (suffix Dev or your env) and redo all the steps. Don't forget to include the new NSE in Podfile.

**Comment by kosbog** [comment]
@LucasReinaldo did you implement it? I tried, but no luck. Stuck on group issue for stage env.

**Comment by LucasReinaldo** [comment]
> @LucasReinaldo did you implement it? I tried, but no luck. Stuck on group issue for stage env.

yep! It is quite annoying to get it right, those are the resources I used to get it done:

- <https://blog.logicwind.com/adding-multiple-target/>
- <https://www.bigbinary.com/blog/handling-environment-specific-configurations-in-react-native>
- <https://sarunw.com/posts/how-to-set-up-ios-environments/>

**Comment by FilipGryczewskiInv** [comment]
@LucasReinaldo  Hi, I tired to implement two separate NSE for two different apps, but the duplicated one keeps throwing
`Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier.` despite having their own NSE. Do you know what can cause it? The main NSE is somehow still related to the second app? Thanks in advance!
