### ISSUE TITLE
[question]: Can we use the same bundle ID for development and production with different OneSignal app IDs?

### ISSUE THREAD

**Issue by sandipshiwakoti** [OneSignal/react-native-onesignal#1615]
### How can we help?

Hey there! I'm seeking clear guidance on the configuration of OneSignal in both development (dev) and production (prod) environments. 

Our current setup includes:
- OneSignal SDK Version: 5.0.4
- Utilizing the same bundle ID (com.example) for both dev and prod environments
- Two separate OneSignal apps with distinct app IDs for dev and prod
- The same Firebase Server Key JSON and .p8 file are used for both environments

## Questions:

- Is it recommended to use the same bundle ID (com.example) with same firebase server key json(android) and .p8 file(iOS) for both dev and prod environments?
- Should we consider using distinct bundle IDs (e.g., com.example.dev for development)?
- What are the potential issues or best practices we should be aware of in this configuration?

Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haider-Ali-7** [comment]
Hi, I'm in same situation. So what solution worked for you?

**Comment by sandipshiwakoti** [comment]
This solution worked for me: https://github.com/OneSignal/react-native-onesignal/issues/1612#issuecomment-1849923213
