### ISSUE TITLE
[question]: How to get `getPushSubscriptionId` in the next line of code

### ISSUE THREAD

**Issue by nusendra** [OneSignal/react-native-onesignal#1616]
### How can we help?

I tried to get sub id with this code

```
const id = OneSignal.User.pushSubscription.getPushSubscriptionId();
console.log(id) // print nothing
```

But it will show the id after i made some changes on code and save. So it will re-render the screen and get that id.
How can i get that id in the first load? Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TomasPaoletti** [comment]
Hello, try this:

const id = **await** OneSignal.User.pushSubscription.getPushSubscriptionId();

Use await because it is a promise

**Comment by nusendra** [comment]
> Hello, try this:
> 
> const id = **await** OneSignal.User.pushSubscription.getPushSubscriptionId();
> 
> Use await because it is a promise

first of all, we can't use await on that.
<img width="519" alt="image" src="https://github.com/OneSignal/react-native-onesignal/assets/8466308/b3a6b169-10dd-4b9e-89b2-a527fcd3af29">


I did that before, and it doesn't work.

**Comment by TomasPaoletti** [comment]
Yes, I know, but I meant something like this:

```
const getSubscriptionId= async () => {
      try {
        const id = await OneSignal.User.pushSubscription.getPushSubscriptionId();
        console.log(id);
      } catch (err) {
       console.log(err);
      }
    };
```

**Comment by nusendra** [comment]
> Yes, I know, but I meant something like this:
> 
> ```
> const getSubscriptionId= async () => {
>       try {
>         const id = await OneSignal.User.pushSubscription.getPushSubscriptionId();
>         console.log(id);
>       } catch (err) {
>        console.log(err);
>       }
>     };
> ```

I did this too before, didn't work
<img width="550" alt="image" src="https://github.com/OneSignal/react-native-onesignal/assets/8466308/494c66bb-0f59-4f7e-a2aa-10513cdfc447">

**Comment by nusendra** [comment]
Found the solution by myself using this code

<img width="552" alt="image" src="https://github.com/OneSignal/react-native-onesignal/assets/8466308/86517319-1be7-49e4-8bd3-f23ded360346">

It will trying to get sub id with setInterval. If sub id exist, then break the loop.
