### ISSUE TITLE
[Bug]: Onesignal push notification with status Failed on iOS 

### ISSUE THREAD

**Issue by tuandm96** [OneSignal/react-native-onesignal#1617]
### What happened?

Onesignal push message for devices subscribed, android devices can receive notification as normal (status Delivered), iOS devices can't receive notification (status Failed)
![ios-failed](https://github.com/OneSignal/react-native-onesignal/assets/39674309/e170e6c1-7912-4034-a8c9-f18240d7a38b)

### Steps to reproduce?

```Markdown
1. Go to Onesignal Dashboard
2. Click the tab Message after that click New Push Notification, input the title and message. In the section platform settings, we choose Send to Apple iOS and Send to Google Android
3. Click the button Review and Send
4. Click the tab Deliver, and observe the table we see messages sent to Google Android devices have the status Delivered, Apple iOS devices have the status Failed
```

### What did you expect to happen?

 Apple iOS devices can receive notifications like Google Android devices (status Delivered).

### React Native OneSignal SDK version

4.5.0

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @tuandm96 thanks for reaching out. Failed delivery for an iOS device may indicate that the Bundle ID has changed from what these devices originally subscribed under. Can you please verify your Bundle ID and ensure it hasn't changed? You will need to put the original version to what the users subscribed under to fix this.

**Comment by tuandm96** [comment]
Hi @jennantilla, I'm making sure Bundle ID is not changed. Before 12/06/2023 (mm/dd/yyyy) it works okay. After this time happened issues although don't have any update

**Comment by tuandm96** [comment]
I have solved it. Root cause is KeyID not exist on Keys section of apple developer, may be someone remove this key.

**Comment by huyln97** [comment]
I same the issue,  I check bundle ID and it's work for me
