### ISSUE TITLE
[question]: How to customize notification prompts based on user language preference?

### ISSUE THREAD

**Issue by sandipshiwakoti** [OneSignal/react-native-onesignal#1619]
### How can we help?

I am experiencing issues with customizing notification prompts based on user language preference in the React Native OneSignal library (Version 5.0.4). 

### Issues

Below are the details of the problem:

- I am looking for guidance on how to customize the notification prompt. I have explored the official documentation, but I couldn't find specific details for React Native.
- I want to set the prompt languages based on the user's preference. It seems that the functionality I require is available for the web (referencing: [OneSignal Prompt Localization](https://documentation.onesignal.com/docs/prompt-localization)).

### Screenshots:

- The language based on the user's device is not being set for iOS and Android notification prompts.
1. iOS
<img width="301" alt="Screenshot 2024-01-03 at 13 08 56" src="https://github.com/OneSignal/react-native-onesignal/assets/62270918/707b4547-0dad-44eb-bef3-a59f4b3026b7">

2. Android
<img width="397" alt="Screenshot 2024-01-03 at 13 09 42" src="https://github.com/OneSignal/react-native-onesignal/assets/62270918/bc732357-db04-411c-909a-935be189c0d4">

### How to solve it?

- I understand that in-app messaging is recommended for customization. However, I would like to know if it's possible to use this approach without disabling the auto prompts.

- I attempted to use React Native permissions for requesting customized localized permission prompts. While this approach works well, I am unable to disable the auto prompt of OneSignal.

- Is there an alternative method for customization?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @sandipshiwakoti thank you for your patience! The prompts from your screenshots are the device's native prompt, which will display in whatever language is set for the device natively. OneSignal can only customize the [in-app soft prompt](https://documentation.onesignal.com/docs/how-to-prompt-for-push-permissions-with-an-in-app-message).

Please let us know if you have any additional questions or concerns!

**Comment by AstrOOnauta** [comment]
Same here! My device is in a different language than English, but the prompt is showing in english.

@sandipshiwakoti any results for that?

**Comment by sandipshiwakoti** [comment]
@AstrOOnauta I didn’t find a solution either. OneSignal mentioned the native prompt can’t be customized and should display in the device’s language, but it didn’t work for me. They recommended In-App Messaging for more customization options, but it wasn’t needed for my app.
