### ISSUE TITLE
onNotificationOpened not triggered on componentDidMount

### ISSUE THREAD

**Issue by adrianha** [OneSignal/react-native-onesignal#162]
Hi,
onNotificationOpened wont be triggered when i configure OneSignal inside componentDidMount. Any idea how to solve this? because i need to access navigator inside the class to do a navigation

**Comment by avishayil** [comment]
I'm not familiar with all navigator types, but you could solve it in a couple of ways, as this issue appeared in previous versions of this library:
1. Using RNRF - I never experienced any problem with it and `OneSignal`.
2. Initialize your navigator class and check if it exists before making an action based on the payload. If it is, do the action. If not, try again in 1 second (Maybe use `setInterval` for this?)

**Comment by avishayil** [comment]
Also, I might be thinking to make this a React `Component`, rather than regular `import`. I'm not sure if it'll be the right direction, because it can cause some troubles. For example, if you configure only after the component was mounted, you can miss the payload.

@jkasten2 What do you think? can we do something about it?

**Comment by adrianha** [comment]
i think using setInterval is not reliable for checking the payload from push notification. Could you please give example using react-native-onesignal and RNRF @avishayil ?

**Comment by adrianha** [comment]
hi @avishayil , apparently it was not being called because i did some synchronous checking to API when app started/resumed. everything is good now. Thank you

**Comment by avishayil** [comment]
@adrianha please check https://github.com/geektimecoil/react-native-onesignal/tree/dev branch, it now tests new module structure to allow using the listeners on React `Component` lifecycle events.

```javascript
componentWillMount() {
    OneSignal.addEventListener('received', this.onReceived);
    OneSignal.addEventListener('opened', this.onOpened);
    OneSignal.addEventListener('registered', this.onRegistered);
    OneSignal.addEventListener('ids', this.onIds);
}
```
And removing listeners is necessary of course, on `ComponentWillUnmount`.
Check the example here:
https://github.com/geektimecoil/react-native-onesignal/blob/e8359ddc1e34ccf90aac4a049d50a607757371c6/examples/RNOneSignal/index.android.js

**Comment by adrianha** [comment]
Hi @avishayil ,
I've already tried from dev branch, but its still not working when there is some async checking when app start.
Here's the snippet of my App.js file: [App.js](http://pastebin.com/898t5i95)
where PushNotificationController is based on Usage section on readme.
Any suggestion?
