### ISSUE TITLE
[Bug]: reactNativeOnesignal.OneSignal.clearHandlers  is unedfined

### ISSUE THREAD

**Issue by newme616** [OneSignal/react-native-onesignal#1620]
### What happened?

Updated to     "react-native-onesignal": "^5.0.4", now this code seems not to work anymore:

`
    return () => OneSignal.clearHandlers();`

### Steps to reproduce?

```Markdown
Update pkg to latest version.
Using with expo
```

### What did you expect to happen?

Expected to work

### React Native OneSignal SDK version

5.0.4

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
TypeError: _reactNativeOnesignal.OneSignal.clearHandlers is not a function (it is undefined)
    in HomeStack (created by RootNavigator)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @newme616,

Version 5 of the `react-native-onesignal` SDK is a major release and contains breaking changes from version 4.
The `clearHandlers()` method no longer exists. 
You can start by visiting our [v5 migration guide and API reference](https://github.com/OneSignal/react-native-onesignal/blob/major_release_5.0.0/MIGRATION_GUIDE.md) for all available methods and properties.
