### ISSUE TITLE
[question]: Multiple commands produce '/Users/hamzabakaran/Library/Developer/Xcode/DerivedData/mobile..../Build/Products/Debug-iphonesimulator/.../Frameworks/OneSignalExtension.framework'

### ISSUE THREAD

**Issue by HamzaBakaran** [OneSignal/react-native-onesignal#1621]
### How can we help?

I'm encountering a 'Multiple commands produce' error related to OneSignalExtension.framework in my React Native iOS app (Xcode 15.1, OneSignal 4.5.1).

Here is full error message:

```
Multiple commands produce '/Users/hamzabakaran/Library/Developer/Xcode/DerivedData  
/mobile-ctpnuulbuipfykbyqdihvziwoxdf/Build/Products/Debug-iphonesimulator   
 /AppName.app/Frameworks/OneSignalExtension.framework'


Target 'mobile' (project 'mobile') has copy command from '/Users/hamzabakaran/Documents/Projects/app/app-mobile 
 /ios/Pods/OneSignalXCFramework/iOS_SDK/OneSignalSDK/OneSignal_Extension/OneSignalExtension.xcframework   
 /ios-arm64_i386_x86_64-simulator/OneSignalExtension.framework' to  
'/Users/hamzabakaran/Library/Developer/Xcode/DerivedData/mobile-ctpnuulbuipfykbyqdihvziwoxdf/Build  
/Products/Debug-iphonesimulator/AppName.app/Frameworks/OneSignalExtension.framework'



```
I've tried switching to OneSignal 4.5.0, removing OneSignalExtension.xcframework form Embed Frameworks (got 
```
/Users/hamzabakaran/Documents/Projects/app/app- 
 mobile/ios/Pods/boost/boost/container_hash/hash.hpp:131:33  
 No template named 'unary_function' in namespace 'std';
 did you mean '__unary_function'?

```
)
 but the issue persists. Can anyone offer guidance on resolving this?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @HamzaBakaran, apologies for the delay in getting back to you. Is this still an issue you are facing?

**Comment by lucianolopezz** [comment]
Same error after upgrade Expo 50

**Comment by lucianolopezz** [comment]
I solved adding **use_frameworks! :linkage => :static**

`target 'OneSignalNotificationServiceExtension' do
  use_frameworks! :linkage => :static // add here
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end`
