### ISSUE TITLE
[Bug]:  `OneSignal.Notifications.canRequestPermission` not working [Android 11, Android 12]

### ISSUE THREAD

**Issue by johannessachse** [OneSignal/react-native-onesignal#1622]
### What happened?

I tried to ask for notification permission but `OneSignal.Notifications.canRequestPermission` does not return anything.

### Steps to reproduce?

```Markdown
1. Disable push notifications in system settings
2. Request permission
3. Receiving no result or permission dialog

            const canRequest = await OneSignal.Notifications.canRequestPermission();
            console.log(canRequest); // log: true

            console.log('request start'); // log: request start
            const result = await OneSignal.Notifications.requestPermission(false);
            console.log('request end'); // no log received


For your information:
On iOS and Android 13+ everything works fine
```

### What did you expect to happen?

I expect that the permission dialog opens and a boolean is returned.

### React Native OneSignal SDK version

Release 5.0.4

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @johannessachse thank you for your patience! 

On Android 12 and lower notifications were accepted silently/automatically. This changed in Android 13 where granting permission become required. Therefore, prompting only happens for Android 13 or newer devices. `canRequestPermission` currently returns `true` for Android 12 and lower although prompting will actually occur. We can look into adding some additional documentation of this behavior to clarify. 

Let me know if you have any additional questions or concerns!
