### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by oun** [OneSignal/react-native-onesignal#163]
Hi I got this error when building iOS with cocoa pods:

> Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTOneSignal", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64

I use RN 0.40, one-singal pod v2.3.5 and react-native-onesignal v3.0.0 and follow the installation guide.

**Comment by avishayil** [comment]
Could you please share your repo so we can test it closely and figure out what the issue is?
Similar issue:
https://github.com/geektimecoil/react-native-onesignal/issues/18

**Comment by oun** [comment]
Finally It's working now. I look into the example projects with cocoa pod and found that it has react native onesignal xcode project under libraries and add libRCTOneSignal.a under Link binary with Libraries.

This is my config. Hope this help others!.
![onesignal](https://cloud.githubusercontent.com/assets/286253/22318994/8017b954-e3b1-11e6-81b6-89bd6f3dcfc9.jpg)

Thanks

**Comment by avishayil** [comment]
Great! Just for you to know, react-native link should do the trick for you.

**Comment by sharathkoppolu** [comment]
![screen shot 2018-09-27 at 10 22 26 am](https://user-images.githubusercontent.com/34389914/46124055-68190b00-c23f-11e8-9401-1382ea817eda.png)

similar issue after adding pod install for some other plugin and opening project with project.xcworkspace, Please help me in solving this issue. Trying to resolve this error from couple of days

**Comment by msnajib** [comment]
> ![screen shot 2018-09-27 at 10 22 26 am](https://user-images.githubusercontent.com/34389914/46124055-68190b00-c23f-11e8-9401-1382ea817eda.png)
> 
> similar issue after adding pod install for some other plugin and opening project with project.xcworkspace, Please help me in solving this issue. Trying to resolve this error from couple of days

+1

**Comment by j-schuster** [comment]
@MuhammadSNajib did you happen so find a solution?

**Comment by denorro** [comment]
@j-schuster @msnajib Did either one of you resolve this issue? If so, it would be greatly appreciated if you could tell me. I have the same exact errors.

**Comment by 77TecShaeer** [comment]
+@3
