### ISSUE TITLE
[question]: React native oneSignal

### ISSUE THREAD

**Issue by cnlkkrb** [OneSignal/react-native-onesignal#1633]
### How can we help?

I added oneSignal to my react native project. It asks for notification permission when I enter the application directly. Can I connect this to a button? I want it to ask when I press the button. If the user does not give permission, I want to create a modal. How do I do this?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by opmat** [comment]
You can take a look at the example provided with this repository available on https://github.com/OneSignal/react-native-onesignal/tree/main/examples/RNOneSignalTS/src

The [OSButtons.tsx](https://github.com/OneSignal/react-native-onesignal/blob/main/examples/RNOneSignalTS/src/OSButtons.tsx) and [OSConsole.tsx](https://github.com/OneSignal/react-native-onesignal/blob/main/examples/RNOneSignalTS/src/OSConsole.tsx) files contain code for using button to trigger various events including requesting notification permission.
I hope that helps

**Comment by jennantilla** [comment]
@opmat thank you for your response and linking to our example project.

@cnlkkrb you can read more about permission prompting [here](https://documentation.onesignal.com/docs/permission-requests).

Let us know if you have any additional questions or concerns!
