### ISSUE TITLE
[question]: OneSignal.User.pushSubscription.getPushSubscriptionId() does not work

### ISSUE THREAD

**Issue by netomarchiori** [OneSignal/react-native-onesignal#1634]
### How can we help?

Need some help on getting the userId or getPushSubscriptionId from a giver user.

On the same code, I do the following:

```
OneSignal.Debug.setLogLevel(LogLevel.Verbose);
OneSignal.initialize(Constants.expoConfig.extra.oneSignalAppId);

OneSignal.Notifications.requestPermission(true);

const oneSignalUserPushId = OneSignal.User.pushSubscription.getPushSubscriptionId();

```

the first time the app runs, oneSignalUserPushId is always empty.

Previously, the userId was assigned regardless of the user accepted the push or not, is there a way to get the userId currently?

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Martinocom** [comment]
If your code is more or less exactly the same as you posted, there is a [limitation in the doc](https://github.com/OneSignal/react-native-onesignal/blob/major_release_5.0.0/MIGRATION_GUIDE.md#limitations) saying: 

> Any User namespace calls must be invoked after initialization. Example: OneSignal.User.addTag("tag", "2")

Maybe you should initialize the SDK, then inside a provider subscribe into permissionChange event and wait for confirmation and ONLY THEN ask for the ID. This _justified_ delay may help in your case, but if you don't want to "justify", you can try if a `setTimeout` works.

**Comment by johannessachse** [comment]
We also have a similar issue while using version 5.0.5. I can not reproduce this by myself, but I get corresponding Sentry-Exceptions.

1. Initialize OneSignal during app start
```typescript
        OneSignal.Debug.setLogLevel(LogLevel.Verbose);
        OneSignal.initialize(appId);
        OneSignalHelper.requestPermission();
        OneSignalHelper.addEventListener(...)
```
2. Get the subscription ID. To make sure that OneSignal is correctly initialized, we do a 5-times retry with 2 seconds timeout each. Additionally, the user needs to fill in a login form before this function is executed. That means our last attempt to retrieve the subscription ID is typically 12-20 seconds after app start.   
```typescript
OneSignal.User.pushSubscription.getPushSubscriptionId()
```

Nevertheless, for some users we don't get a subscription ID. This happens on Android (13, 14) as well as on iOS (15.8 up to 17.4)

**Comment by jennantilla** [comment]
Hello there! In [5.1.0](https://github.com/OneSignal/react-native-onesignal/releases/tag/5.1.0) we updated the Push Subscription property getters to be async so that the value is always correct. Please upgrade to this version and let us know if you are still having any issues.

Thanks!
