### ISSUE TITLE
[question]: Handling the Dismiss event

### ISSUE THREAD

**Issue by opmat** [OneSignal/react-native-onesignal#1636]
### How can we help?

How can I handle the Notification _Dismiss event_ in the mobile SDK just the same way the Web SDK has the Dismiss event?
Is this a feature that is been considered?
The challenge is that I want to make a notification available to App locally, but the only option is the Click and foregroundWillDisplay events. If the user clears notification received when the app is closed without clicking on it, I am unable to save that Notification.

I will appreciate any suggestion on how to save notifications received when the app is closed other than when it is clicked incase notifications are cleared.

Thank you

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @opmat thanks for reaching out! While our mobile SDKs do not have a dismiss event for notifications, we do have a [notification click listener](https://documentation.onesignal.com/docs/mobile-sdk#set-notification-click-listeners) which is fired when a notification is tapped. Please let us know if you have any additional questions or concerns!

**Comment by jennantilla** [comment]
Closing due to no response.
