### ISSUE TITLE
Unable to make android notifications appear as banner

### ISSUE THREAD

**Issue by junshengpierre** [OneSignal/react-native-onesignal#164]
Hi,

I am trying to get android notifications to appear as a banner. I have tried inFocusDisplaying(2) but it only showed up in the notification drawer whether the app was in focus or not.

I was able to get iOS notifications to appear as a banner and show up in the notification drawer with `kOSSettingsKeyInFocusDisplayOption: OSNotificationDisplayTypeNotification` regardless of app focus.

Is there a config to allow banner notifications on android with RN?

react-native: 0.39.2
react-native-onesignal: 2.0.0
device: Samsung Galaxy S6 Android 6.0.1

```javascript
OneSignal.inFocusDisplaying(2)
OneSignal.configure({...})
```

**Comment by avishayil** [comment]
Hi @junshengpierre ,
By saying "as a banner", what exactly you mean?
What you are describing here is the normal behavior, I think.
Can you elaborate more on this / upload a screenshot with the expected behavior?
Thanks!

**Comment by junshengpierre** [comment]
Hi @avishayil,

With `inFocusDisplaying(2)` on android, when a notification is received on android, it shows up as an icon on the extreme left corner of the status bar and in the notification shade.

<img width="200" alt="screen shot 2017-01-26 at 10 50 33 am" src="https://cloud.githubusercontent.com/assets/14052341/22319327/a54aa294-e3bc-11e6-9c13-f522b8b1deed.png">

I was trying to make the notifications appear as a banner as well when the app is not in focus like this:

<img width="200" alt="screen shot 2017-01-26 at 11 09 06 am" src="https://cloud.githubusercontent.com/assets/14052341/22318716/ef8e0d64-e3b7-11e6-9856-9af438fb6802.png">

Is this possible with react-native-onesignal? Thank you.

**Comment by jkasten2** [comment]
@junshengpierre ~To get a head-up notification like this you need to set the `priority` of the notification to `10`. This can be done with the OneSignal create notification REST API call noted below.
https://documentation.onesignal.com/reference#section-delivery~
**Update**
You must create a notification category / channel to change the display priority of the notification to show the notification as a pop up banner.
See the following page on setting one up and using it.
https://documentation.onesignal.com/docs/android-notification-categories

**Comment by junshengpierre** [comment]
@jkasten2 Alright, I'll go ahead and do that. Thank you!

**Comment by kelset** [comment]
Hey @jkasten2 I tried going for your hint by posting to the OneSignal REST API (via RoR) with this params:

```
        params = {"app_id" => ENV["ONE_SIGNAL_APP_ID"],
                  "headings" => {"en" => title},
                  "contents" => {"en" => text},
                  "priority" => 10,
                  "filters" => [ {"field": "tag", "key": "server_uid", "relation": "=", "value": send_to} ]
                }

```

but it doesn't create a head-up notification, in my tests.
I've been using an Android 6.0 real device, RN 0.38 and `react-native-onesignal 1.2.3`.

Is it somewhat related to the config param `enableInAppAlertNotification`? Does it have to be set to `false`?

**Comment by jkasten2** [comment]
@kelset You will need to use the latest 3.0.1 react-native-onesignal SDK. This is required since the feature was added in a recent Android Native SDK update.
https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.4.0

**Comment by kelset** [comment]
So it won't work even in version 2.0?

**Comment by Noitidart** [comment]
I'm having same issue, i set priority to high as well. How did you guys fix this?

**Comment by cgilboy** [comment]
@jkasten2 Per your comment here https://github.com/OneSignal/OneSignal-Android-SDK/issues/10, it looks like no client-side intervention is needed to raise the notification priority to 10 when the rest API sets it to 10. Is this true for the react-native library as well? 

I can't get this to work at the moment with v3.3.2 of the RN libraary. When I examine the notification that is delivered, I see `priority: 6` in my react-native client, despite sending `priority: 10` via the rest api.

**Comment by jorbs** [comment]
Hi. Same issue here. @cgilboy did you have any luck on this?

**Comment by cgilboy** [comment]
@jorbs Unfortunately not. I had to move on to other priorities. Please do ping back if you find a solution!

**Comment by rgomezp** [comment]
@cgilboy ,
Please update to the latest version of the SDK as you're on a very old version. What is the response from the OneSignal REST API?

**Comment by jorbs** [comment]
I was able to get it using a channel.

**Comment by iacocesar** [comment]
same issue

**Comment by jkasten2** [comment]
@IacoCesar You must create a notification category / channel to change the display priority of the notification to show the notification as a pop up banner.
See the following page on setting one up and using it.
https://documentation.onesignal.com/docs/android-notification-categories

**Comment by NikitaNeganov** [comment]
@jkasten2 Hi, I have the same issue. 
I did create a channel, and even used it from the Dashboard, but still the same result (though I chose the highest priority).

When using rn-firebase it was required to explicitly state (in-app) the channel I was using, i.e. `firebase.init(); firebase.setAndroidChannel()`

Is there a similar method here or how do I use that channel?

**Comment by YinhaoHe** [comment]
Hi there, do you guys find a way to make it happen?
