### ISSUE TITLE
[question]: Changing the Language of Android System Modal Text in the requestPermission Callback Function

### ISSUE THREAD

**Issue by WooMinGy** [OneSignal/react-native-onesignal#1645]
### How can we help?

![image](https://github.com/OneSignal/react-native-onesignal/assets/86763219/4904d3e1-d6c1-4f53-8602-28bccfc8bff2)

How can I change the language of the Android system modal that appears when navigating to device settings from the callback function of the requestPermission method? The language is currently mixed with Korean and English, as shown in the picture.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @WooMinGy thanks for reaching out! The language of the modal in your screenshot should be based on the device's system settings; it is a native prompt outside of OneSignal's customizable options. Is your phone currently set to Korean or English?

**Comment by WooMinGy** [comment]
@jennantilla 
Thank you for your response.
It is currently set to Korean.

**Comment by jennantilla** [comment]
@WooMinGy apologies for the delay in response. Do you also have English as a language on your phone (in Settings?)? Can you try removing it and see if the modal language updates?

**Comment by jennantilla** [comment]
Closing due to no response.

**Comment by itlockit2** [comment]
I am also experiencing the same issue where the system prompt only appears in English, even though my phone's language is set to Korean. Additionally, when I use [LocaleConfig](https://developer.android.com/reference/android/app/LocaleConfig) and set it up in `res/xml/locale_config.xml` like this:

```xml
<locale-config xmlns:android="http://schemas.android.com/apk/res/android">
  <locale android:name="ko"/>
</locale-config>
```

and configure `AndroidManifest.xml` as follows:

```xml
<application
  android:localeConfig="@xml/locale_config"
</application>
```

the system prompt no longer appears at all.

**Comment by Jeyoung-Park** [comment]
same here
has anyone solved this issue?

**Comment by patricpfranca** [comment]
I’m experiencing the same issue. My device is set to Portuguese, but the prompts are showing up in English. Is there a solution for this?
