### ISSUE TITLE
[question]: Handle notification click when app is not in foreground/open ?

### ISSUE THREAD

**Issue by nmateo** [OneSignal/react-native-onesignal#1651]
### How can we help?

OneSignal.setNotificationOpenedHandler does not exist in v5 afaik i've tried everything and it is undefined/ not here anymore.
Is it impossible to deepLink with notification and open the app/put it to foreground ?
With expo we use only one hook and it does the job: Notifications.useLastNotificationResponse();
If this is impossible with oneSignal this is kind of a deal breaker.
Also i contacted support they told me to use OneSignal.Notifications.addEventListener('click', (event))
Which i use already but works only when the app is in foreground... and after that support ghosted me...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manuhook** [comment]
Hi ! same problem here, did you find a solution ?

**Comment by nmateo** [comment]
> Hi ! same problem here, did you find a solution ?
Yes, in our case, it was a permission on  MIUI  "display pop-up" that was not activated.
Wth this permission activated and the launchURL / url property with "app://" link, it works.
