### ISSUE TITLE
[question]: airplane mode ON/OFF: what to expect?

### ISSUE THREAD

**Issue by pierroo** [OneSignal/react-native-onesignal#1653]
### How can we help?

Some of my users complain that once they turn back off the airplane mode (they left ON during the night) they don't get all the notifications that were sent to them during the night.

Apparently only for my app, other apps it's working fine.

What should we do with onesignal for those pending notifications to not be lost entirely when airplane mode is on?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@pierroo Thanks for reaching out, could you report this as a possible bug by creating an issue from this instead?
https://github.com/OneSignal/react-native-onesignal/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=bug-report.yml

There are details like which SDK version, Android and iOS versions, can you reproduce, etc we need to help investigate.
