### ISSUE TITLE
devices iOS and android are not received any push notif

### ISSUE THREAD

**Issue by hotaryuzaki** [OneSignal/react-native-onesignal#1659]
### How can we help?

we have an issue in our app, our backend sends push notif to API/v1/NOTIFICATIONS and we get 200 response with id in data object. Then we can see in the dashboard the message we have sent with "delivery" status.
But the issue is the device doesn't receive any push notif (iOS and android).
We experienced this issue last week, including our installed app. So, we believe this issue from onesignal side.
any suggestion??

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @hotaryuzaki thank you for your patience! Is this still a concern for you? There are [several reasons](https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown) why notifications may not be shown on a device.

If you are still having issues, follow [this guide](https://documentation.onesignal.com/docs/capturing-a-debug-log) and send yourself a push notification while the device is plugged into your dev tools.

You can share the log here we can take a look.
