### ISSUE TITLE
Can you post a p2p notification with a later date/time ?

### ISSUE THREAD

**Issue by logileifs** [OneSignal/react-native-onesignal#166]
I want to be able to register a remote notification to the current device from my app that will be fired at a later date. I can't see anything about it in the documentation, is that possible somehow? If not, is it something that could be implemented?

**Comment by avishayil** [comment]
Hi @logileifs , I don't think you can do it using the library, but you could always send it to another micro application that would be activated by a cron job, that will call the api on the right time.

**Comment by logileifs** [comment]
thanks for your suggestion @avishayil. I actually found another simpler/better solution, I use your SDK to configure the client app but then I schedule my notifications by making HTTP calls to the opensignal web API since it has a parameter where you can specify the time/date of the notification

**Comment by avishayil** [comment]
Great!

**Comment by hounsellal** [comment]
@logileifs , would you have a moment to describe how you were able to access the REST API through HTTP calls after the react-native-onesignal SDK configures the client app?

I have react-native-onesignal configuring just fine and I can use that SDK. But when I use a REST client in the app, it want my authentication key. Did you include that in your app? The one signal documentation says not to: "The REST API key is for our REST API. Treat this like a password and do NOT use this KEY in your app"

Any help would be appreciated.

**Comment by hounsellal** [comment]
For those having the same problem, it was because I was filtering users in a  way that required the api key. If you use playerIds directly, it works fine without the api key.
