### ISSUE TITLE
[Bug]: OneSignal: This method has been deprecated. Use getIdAsync instead for getting push subscription id.

### ISSUE THREAD

**Issue by Romick2005** [OneSignal/react-native-onesignal#1663]
### What happened?

Would be good to know the method name that is deprecated and is in use.

### Steps to reproduce?

```Markdown
Previous version 5.0.6 works fine.
```

### What did you expect to happen?

![image](https://github.com/OneSignal/react-native-onesignal/assets/17779660/afc90318-c75e-4943-9851-070a1dd9c6c6)

### React Native OneSignal SDK version

Release 5.0.10

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Relevant log output

```Shell
OneSignal: This method has been deprecated. Use getIdAsync instead for getting push subscription id.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @Romick2005 good call, we will update the log to include the method name.

In [Release 5.1.0](https://github.com/OneSignal/react-native-onesignal/releases/tag/5.1.0), the SDK added the method `await OneSignal.User.pushSubscription.getIdAsync()` as a more accurate getter for the push subscription ID.

The previous getter was `OneSignal.User.pushSubscription.getPushSubscriptionId()`, which is still fully supported and behaves same as before. 

The new async getter will return more accurate data during early app startup, compare to `getPushSubscriptionId()` which may return `undefined`.

**Comment by hexllhexll** [comment]
The same problem

**Comment by Romick2005** [comment]
Replacements:
getPushSubscriptionId -> getIdAsync
getPushSubscriptionToken -> getTokenAsync
getOptedIn -> getOptedInAsync
hasPermission -> getPermissionAsync

**Comment by hexllhexll** [comment]
Thank you, problem has been resolved

**Comment by jennantilla** [comment]
Thank you flagging! The warnings have been [updated](https://github.com/OneSignal/react-native-onesignal/tree/fix/documentation_updates) and will be included in our next React Native release.
