### ISSUE TITLE
How to solve this Error in XCode Multiple commands produce React-Core-60309c9c-RCTI18nStrings | React-Core-RCTI18nStrings?

### ISSUE THREAD

**Issue by lchentanaone** [OneSignal/react-native-onesignal#1665]
Error

Showing Recent Messages
Multiple commands produce '/Users/********/Library/Developer/Xcode/DerivedData/ryorimobilev2-bimmpniobmadxrfontyocvohycrj/Build/Intermediates.noindex/
ArchiveIntermediates/ryorimobilev2/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/RCTI18nStrings.bundle'

Showing Recent Messages
Target 'React-Core-60309c9c-RCTI18nStrings' (project 'Pods') has create directory command with output 
'/Users/********/Library/Developer/Xcode/DerivedData/ryorimobilev2-bimmpniobmadxrfontyocvohycrj/Build/Intermediates.noindex/
ArchiveIntermediates/ryorimobilev2/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/RCTI18nStrings.bundle'

Showing Recent Messages
Target 'React-Core-RCTI18nStrings' (project 'Pods') has create directory command with output 
'/Users/********/Library/Developer/Xcode/DerivedData/ryorimobilev2-bimmpniobmadxrfontyocvohycrj/Build/Intermediates.noindex/
ArchiveIntermediates/ryorimobilev2/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/RCTI18nStrings.bundle'

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @lchentanaone thanks for reaching out! Can you share more about the steps to reproduce this issue? 

Do you get the same errors when you remove OneSignal from your project? I don't see mention of OneSignal in the errors above; it looks like this could be a pod issue?

You can try:
```
$ pod deintegrate
$ pod install
```

Let us know if you are still having this problem only when you try to add the OneSignal SDK to your project.

Thanks!

**Comment by vuongtran99dn** [comment]
first, you need remove pod folder 
then add this to Podfile

`post_install do |installer|

     ################### ADD THE FOLLOWING #########################
     installer.pods_project.targets.each do |target|
      if target.name == "React-Core-RCTI18nStrings"
        target.remove_from_project
      end
    end
    ###############################################################

    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end`

pod install again and Target React-Core-RCTI18nStrings will be remove from your project.

check result in xcode > pod > target 

![Screenshot 2024-05-07 at 12 52 28](https://github.com/OneSignal/react-native-onesignal/assets/70287791/9b5ac7ea-3a1e-4f7d-956b-b7f20a557d0c)

My english is so bad... hope u understand

**Comment by NgocLe1001** [comment]
![CleanShot 2024-05-08 at 21 34 50@2x](https://github.com/OneSignal/react-native-onesignal/assets/57764602/7557d49b-ac3d-4acf-9a9b-5e0d79e46a03)
Xcode => Pods => Target => Find it and remove works for me

**Comment by Danishqureshi8817** [comment]
open this issue

**Comment by nguyendinhdoan** [comment]
I have the same issue
