### ISSUE TITLE
"library not found for -lPods"

### ISSUE THREAD

**Issue by ghost** [OneSignal/react-native-onesignal#167]
Hello friends, when I try to run the project I get the following error: "clang: error: linker command failed with exit code 1 (use -v to see invocation) "library not found for -lPods"
react native v: 0.39
react-native-onesignal ":" ^ 2.0.0 ".
pod v: 1.2.0,
OneSignal: (2.3.5)

**Comment by avishayil** [comment]
Hi @kamish770 are you running the Xcode workspace? since from your error it seems that your'e running the project form the Xcode project file, which is wrong after using `CocoaPods`.
