### ISSUE TITLE
[Feedback]: Bump to OneSignal-iOS-SDK 3.12.8 / privacy manifest requirement

### ISSUE THREAD

**Issue by manuhook** [OneSignal/react-native-onesignal#1673]
### What's on your mind?

Hi, can you please plan very soon a new release that includes OneSignal-iOS-SDK 3.12.8 that address the privacy manifest requirement for the App Store ?
https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.12.8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marcvictorpassarelli** [comment]
@manuhook I'm not sure if you're using v4 or v5, but for v4 they did yesterday [here](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.5.3), but it seems they still have to do that for v5

**Comment by manuhook** [comment]
Yes thank you, it looks like it's OK on the V4 now. It was already fine on V5 a few weeks ago.
