### ISSUE TITLE
[question]: How to prevent web notifications from showing when tab is being viewed?

### ISSUE THREAD

**Issue by thatop007** [OneSignal/react-native-onesignal#1676]
### How can we help?

We currently able to receive web desktop notifications successfully and would like to know if it is possible and how to prevent web notifications from showing when the tab being viewed by the user is our site.

here is our current implementation in our react web app, in particular our attempt to not show the notification if the user is currently looking at our site.

```
  useEffect(() => {
    function foregroundWillDisplayListener (event) {
      console.log(event);
      //dont show notification if tab is currently being viewed
      if (document.visibilityState === 'visible') {
        return event.preventDefault();
        
      }
    }
        OneSignalDeferred.push(function () {
      OneSignal.Notifications.addEventListener("foregroundWillDisplay", foregroundWillDisplayListener);

    });

  }, []);
```

looking at  foregroundWillDisplayListener event param I saw there are 2 params:

- notification
- preventDefault - when call the prevent default function we are getting this error:

```
Error: Browser does not support preventing display.
    at Object.preventDefault (ServiceWorkerManager.js:168:27)
```

<img width="416" alt="image" src="https://github.com/OneSignal/react-native-onesignal/assets/91869074/adcee3d1-89ff-40da-b926-6657275147c6">

your time and assistance is highly appreciated.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@thatop007 this repo only supports Android and iOS, and but I see you are using this on a web site, and using the OneSignal-Website-SDK.

I see you created an issue on the OneSignal-Website-SDK repo so I followed up with you there.
