### ISSUE TITLE
[Bug]: OneSignal.login() doesn't set the externalId in react native

### ISSUE THREAD

**Issue by Raduc4** [OneSignal/react-native-onesignal#1682]
### What happened?

Hi, I have this bug. I'm trying to setup the external_id of a user, where the external_id is my users database uuid, however, the external Id is not set up in any way and I can't debug this.
I'm using pure react native for this and the flow is very simple, I initialize OneSignal, request the permission and then login the user, nothing special in my opinion.
![image](https://github.com/OneSignal/react-native-onesignal/assets/55291600/73a3a644-eba4-4693-a022-42664e3d2ed6)
Also I can get my externalId with OneSignal.User.getExternalId()
but, when trying to send the notification to the external id using the rest API I get this
{"id":"","errors":["All included players are not subscribed"]}⏎
but I have a subscription created for the current app running

### Steps to reproduce?

```Markdown
1. A bare react native project
2. Install one signal library
3. Initialize
4. OneSignal.login(a random id)
5. Check if you can get the external id with OneSignal.getExternalId(): Promise<string>
6. Check if you can get the onesignal subscription ID OneSignal.getSubscriptionId(): Promise<string>
```

### What did you expect to happen?

The UUID of the user from my database to be assigned to the current subscription

### React Native OneSignal SDK version

Latest

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BishalftSaikia** [comment]
await for `OneSignal.Notifications.requestPermission(true)` to resolve , then login, use `async` `await` or put it inside `.then `, maybe thats the issue

**Comment by Raduc4** [comment]
> await for `OneSignal.Notifications.requestPermission(true)` to resolve , then login, use `async` `await` or put it inside `.then `, maybe thats the issue

Somehow it started to work by itself.
Maybe because I disabled the verification

**Comment by sirusbaladi** [comment]
> > await for `OneSignal.Notifications.requestPermission(true)` to resolve , then login, use `async` `await` or put it inside `.then `, maybe thats the issue
> 
> Somehow it started to work by itself. Maybe because I disabled the verification

what do you mean by disabled the verification? I'm having the same issue.

**Comment by Snouzy** [comment]
I guess he means to disable this verification. For a more detailled explanation you can follow this: https://documentation.onesignal.com/docs/identity-verification

![screenshot-2024-07-14_10h25m22s@2x](https://github.com/user-attachments/assets/1c21b548-50c6-441b-9fc0-cf009995de33)
