### ISSUE TITLE
[Bug]: Push Notification with status FAILED on iOS

### ISSUE THREAD

**Issue by Felipelpk** [OneSignal/react-native-onesignal#1683]
### What happened?

The push message is not being sent to iOS devices, after sending it automatically returns the FAILED status.

In-app message is working correctly, my Bundle ID is correct.

### Steps to reproduce?

```Markdown
1. Go to Onesignal Dashboard
2. Click the tab Message after that click New Push Notification, input the title and message. In the section platform settings, we choose Send to Apple iOS and Send to Google Android
3. Click the button Review and Send
4. Click the tab Deliver, Apple iOS devices have the status Failed
```

### What did you expect to happen?

Apple iOS devices can receive notifications.

### React Native OneSignal SDK version

Release 5.1.0

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @Felipelpk thank you for your patience! Are you still having this issue? If so can you please provide a screenshot of the failed status shown?

More information on failed notifications here: https://documentation.onesignal.com/docs/push-notification-message-reports#what-are-failed-notifications

Appreciate it!

**Comment by jennantilla** [comment]
Closing due to no response.
