### ISSUE TITLE
[Bug]: canRequestPermission is not working as expected

### ISSUE THREAD

**Issue by Balaram-RJS** [OneSignal/react-native-onesignal#1698]
### What happened?

react-native-onesignal version 5.1.2 OneSignal.Notifications.canRequestPermission is not working as expected. Should it return true even if the user denied the native system prompt for android version 13. I am yet to check it for iOS.

### Steps to reproduce?

```Markdown
doRegisterForRemoteNotifications = () => {
    OneSignal.Notifications.getPermissionAsync().then(granted => {
        OneSignal.Notifications.canRequestPermission().then(canrequest => {
            console.log('granted :: ' + granted);
            console.log('canrequest :: ' + canrequest);
            let doInit = Platform.select({
                android: () => {
                    OneSignal.Notifications.requestPermission(false);
                },
                ios: () => {
                    OneSignal.Notifications.requestPermission(false);
                },
                default: () => {},
            });
            if (granted === false && canrequest === true) {
                doInit();
            }
        });
    });
};
```

### What did you expect to happen?

in the above code i would expect granted to be false and canrequest to be false if the user has denied the native system prompt.

### React Native OneSignal SDK version

5.1.2

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Balaram-RJS** [comment]
hi,
Could any one confirm whether this is the intended behaviour

**Comment by jennantilla** [comment]
Hi @Balaram-RJS thank you for you patience! 

`canRequestPermission` only returns true if the device has _never_ been prompted for push notification permission. So if a user denies the prompt then it will return false.

Please let us know if you have any additional questions or concerns!

**Comment by Balaram-RJS** [comment]
Hi @jennantilla ,

Thank you for taking out the time to reply,
but **canRequestPermission** is not working like that and if a user denies the system prompt it still returns true.
I have attached the device logs herewith.
[device_log.txt](https://github.com/OneSignal/react-native-onesignal/files/15184567/device_log.txt)
