### ISSUE TITLE
[Bug]: Missing API declaration

### ISSUE THREAD

**Issue by sbongiz** [OneSignal/react-native-onesignal#1699]
### What happened?

I am having trouble submitting the application to the store.
Apple tells me I need to add some Missing API declaration.

I followed the step-by-step guide for the Ios integration.
https://documentation.onesignal.com/docs/react-native-sdk-setup

ITMS-91053: Missing API declaration - Your app’s code in the “PlugIns/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

ITMS-91053: Missing API declaration - Your app’s code in the “PlugIns/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

### Steps to reproduce?

```Markdown
Follow the guide to setup OneSignal in Ios.
Submit the app on the store
```

### What did you expect to happen?

I expected that the submission to have no problem

### React Native OneSignal SDK version

Release 5.1.0

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yosukapro** [comment]
Hello
Did you find a solution to this problem?

**Comment by ekediala** [comment]
+1

**Comment by nan-li** [comment]
Hi everyone, thank you for reporting. 

This same issue is reported on our native ios SDK, please check the information in that post: https://github.com/OneSignal/OneSignal-iOS-SDK/issues/1397. You can follow up there.
