### ISSUE TITLE
Receiving Notifications when locked screen?

### ISSUE THREAD

**Issue by almadsen** [OneSignal/react-native-onesignal#170]
Is it posible to somehow receive, and/or display notification in any way when the device's screen is locked (and inactive)?

I get notifications when app is opened, in background and even when closed on my iOS device but it doesn't seem to register anything when closed and screen is locked (and inactive).

Anyone any thoughts on this, couldn't really find anything in OneSignals docs on this.

**Comment by almadsen** [comment]
Nevermind, found a way to do it. Just haven't played around with the settings enough I guess.

**Comment by oscarnevarezleal** [comment]
@almadsen how did u solve ethis?
