### ISSUE TITLE
iOS: Badge not showing

### ISSUE THREAD

**Issue by aneena-thomas** [OneSignal/react-native-onesignal#1705]
### How can we help?

Added app groups  but still badge not showing in iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @aneena-thomas thanks for reaching out! Can you please provide some additional information about how you added App Groups? We have some iOS App Groups Troubleshooting [documentation](https://documentation.onesignal.com/v9.0/docs/ios-sdk-app-groups-setup#ios-app-groups-troubleshooting) that may be helpful. If you are still having issues, please provide the [logs](https://documentation.onesignal.com/v9.0/docs/ios-sdk-app-groups-setup#logging-within-the-nse) from the NSE and we can take a closer look.

Thanks!

**Comment by jennantilla** [comment]
Closing due to no response. @aneena-thomas if you are still having issues please mention me and we can continue investigating. Thanks!
