### ISSUE TITLE
[question]: Even though I followed all the instructions, the icon does not change

### ISSUE THREAD

**Issue by qaniqani** [OneSignal/react-native-onesignal#1712]
### How can we help?

Hi everybody.

I integrated Onesignal into my react-native application and it works without any problems. I changed the app icon, created my icons from the github project recommended by onesignal and added them to my project. The icons appear in place in the emulator. But on my real device (Xiaomi mi 11T Pro), the character a appears somewhere in the notification window and this character does not exist in my project. I tried everything, I couldn't understand where it was coming from and how.

Is there anyone who can help with this?

Note: When I send the icon name parametrically from the Onesignal panel, the large icon appears on the right, but the small icon does not appear at all.

![WhatsApp Image 2024-06-04 at 16 27 23](https://github.com/OneSignal/react-native-onesignal/assets/19714568/fdea7153-4c5e-4634-a5b6-b0fb3dfd3510)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @qaniqani apologies for the delay in response. Is this still an issue for you?

**Comment by qaniqani** [comment]
Hello,

It fixed itself, I couldn't understand... There is no problem now.

Thnx :)
