### ISSUE TITLE
[Bug]: NotificationClickEvent returning `launchUrl` instead of `launchURL` (on Android)

### ISSUE THREAD

**Issue by Aya-Sato** [OneSignal/react-native-onesignal#1713]
### What happened?

When calling `OneSignal.Notifications.addEventListener("click", (event) => {};)`, `event.notification.launchUrl` is being returned on Android instead of `event.notification.launchURL`. 

### Steps to reproduce?

```Markdown
OneSignal.Notifications.addEventListener("click", (event) => {
     console.log(event.notification.launchURL)
  }
)
```

On iOS, `event.notification.launchURL` is correctly returned as specified by the `OSNotification` type. On Android, `event.notification.launchURL` is undefined and instead `event.notification.launchUrl` is returned.

### What did you expect to happen?

Expect to have the `event.notification.launchURL` returned on Android as well.

### React Native OneSignal SDK version

5.2.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pilotpirxie** [comment]
I have the same issue and I had to do the ugly hack to quiet warnings and the error to support both platforms. On iOS it works fine, the object returned to the android device is invalid.
```
      if (
        oneSignalEvent.notification?.launchURL ||
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-expect-error
        oneSignalEvent.notification?.launchUrl
      ) {}
```

**Comment by Martinocom-Switcho** [comment]
I created an issue here some months ago: https://github.com/OneSignal/react-native-onesignal/issues/1635
It was marked as resolved 8h ago so I hope new update will rollout soon!

**Comment by Aya-Sato** [comment]
@Martinocom-Switcho Thank you for letting us know! I will close the issue

**Comment by pilotpirxie** [comment]
@Aya-Sato Shouldn't you first release the fix and then close? When can we expect change to be released?

**Comment by pilotpirxie** [comment]
@Aya-Sato Hey, you closed the issue but we still haven't got the new version with the fix. And it's about a month. Can you please reopen the issue?

**Comment by Martinocom-Switcho** [comment]
@pilotpirxie I think it was closed because #1635 was still open and this was a duplicate.

But I agree that if merged ≠ released, the original #1635 should't be closed. Or at least it should be stated somewhere if this is the policy of this repo.

**Comment by Aya-Sato** [comment]
@pilotpirxie @Martinocom-Switcho 
Yes, I closed the issue because it was a duplicate. I do agree with @Martinocom-Switcho though that the original shouldn't have been closed if it was not released yet..

**Comment by Martinocom-Switcho** [comment]
@Aya-Sato @pilotpirxie released
https://github.com/OneSignal/react-native-onesignal/releases/tag/5.2.1
