### ISSUE TITLE
Not getting iOS push token

### ISSUE THREAD

**Issue by gorgekara** [OneSignal/react-native-onesignal#172]
I've followed your installation instructions and hit a wall with the CocoaPod installation. 

After finding the solution here: https://github.com/geektimecoil/react-native-onesignal/issues/72 - i've reverted the OneSignal pod version to 1.13.2 and the build passed. However i can't get the push token generated when i request it in the app - and is not sent to OneSignal - i can't see it in the users section, it just says "No Push Token" for the user.

I'm testing this out on an actual iPhone 6s.

Am i missing some steps, or maybe i should enable some options in xcode?

Thanks!

**Comment by avishayil** [comment]
Hi @gorgekara , did you allow push notifications when running the app when you get the alert?

**Comment by avishayil** [comment]
@gorgekara Did you manage to work this issue out? I recommend following the latest instructions.

**Comment by gorgekara** [comment]
Hi, i followed the latest instructions and it worked. Thanks!

**Comment by avishayil** [comment]
Great!
