### ISSUE TITLE
How to add jwtToken to login

### ISSUE THREAD

**Issue by lednhatkhanh** [OneSignal/react-native-onesignal#1723]
On OneSignal web, we can add jwtToken to login function by:

`OneSignal.login(externalId, jwtToken)`

Wonder how can I do the same thing with this sdk. Thank you.

**Comment by jennantilla** [comment]
Hi @lednhatkhanh thanks for reaching out!

We are currently working on adding JWT validation to our 5.x.x SDKs. It is not yet currently available but should be by the end of this quarter. 

Be sure to keep an eye on our [releases](https://github.com/OneSignal/react-native-onesignal/releases) for when it is added and ready to use!
