### ISSUE TITLE
[Bug]: Setting `OneSignal.Notifications.requestPermission` parameter `fallbackToSettings` to `false` has no effect

### ISSUE THREAD

**Issue by hrastnik** [OneSignal/react-native-onesignal#1727]
### What happened?

When calling `OneSignal.Notifications.requestPermission` it's possible to pass a parameter `fallbackToSettings` which should control whether the in-app `Open Settings` prompt will display when the native prompt has been rejected. However, this parameter has no effect and the Open Settings prompt shows always

### Steps to reproduce?

```Markdown
1. Call `await OneSignal.Notifications.requestPermission(false);`
2. The "Open Settings" prompt will show
```

### What did you expect to happen?

The prompt should not show up.

### React Native OneSignal SDK version

5.2.2

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by martin-key** [comment]
Same here. This issue should be marked as Major as we have received multiple reports by uses.

**Comment by aharonphytech** [comment]
I opened PR addressing this issue:
https://github.com/OneSignal/react-native-onesignal/pull/1729

**Comment by aharonphytech** [comment]
@jennantilla, thank you for merging the PR. I believe the issue should be resolved now

**Comment by jennantilla** [comment]
Thanks for your patience, everyone! [Release 5.2.3](https://github.com/OneSignal/react-native-onesignal/releases/tag/5.2.3) is ready. I'll go ahead and close this out but please let us know if there are any additional questions or concerns.
