### ISSUE TITLE
disable alerts 

### ISSUE THREAD

**Issue by ghost** [OneSignal/react-native-onesignal#173]
I want to cancel the alert when the application is open. Have only external alarms.

My code:

`OneSignal.configure({
  onIdsAvailable: function (device) {
    getUserId(device.userId);
  },
  onNotificationReceived: function (notification) {
    permissions = {
        alert: false,
        badge: true,
        sound: true
    };
    OneSignal.requestPermissions(permissions);
  },
  onNotificationOpened: function(message, data, isActive) {
    console.log("MS TYPE", message.notification.payload.additionalData.type);
    switch(message.notification.payload.additionalData.type) {
    case '1':
          Actions.messenger();
        break;
    case '2':
          Actions.overview();
        break;
      }
    }
});`

**Comment by avishayil** [comment]
Hey @kamish770 , is this on iOS or Android?

**Comment by ghost** [comment]
ios

**Comment by avishayil** [comment]
Please see https://github.com/geektimecoil/react-native-onesignal/issues/157#issuecomment-274646754
