### ISSUE TITLE
[Bug]: Tags not appearing in OneSignal dashboard after being added.

### ISSUE THREAD

**Issue by hamzaali98** [OneSignal/react-native-onesignal#1754]
### What happened?

After adding tags to a user via `OneSignal.User.addTags()`, I can fetch the tags successfully using `OneSignal.User.getTags()` and see them logged in my application. However, these tags do not appear on the OneSignal dashboard.

- React Native version: 0.74.3

**Additional Information**:
I have confirmed that the tags are being added successfully, and there are no visible network errors in the logs. This issue occurs even after refreshing the dashboard multiple times.

### Steps to reproduce?

```Markdown
1. Use `OneSignal.User.addTags()` to add tags to the user.
2. Use `OneSignal.User.getTags()` to confirm that the tags are added and fetched correctly.
3. Check the OneSignal dashboard, and the tags do not appear there.
```

### Code
```
useEffect(() => {
  if (patientProfile) {
    OneSignal.User.getTags()
      .then(tags => {
        console.log('Current tags for the user:', tags);
      })
      .catch(error => {
        console.error('Error fetching tags:', error);
      });

    OneSignal.User.pushSubscription.getIdAsync().then(id => {
      console.log('Push subscription ID:', id);
    });

    OneSignal.User.pushSubscription.getTokenAsync().then(token => {
      console.log('Push subscription token:', token);
    });

    console.log('Adding tags to OneSignal User');

    OneSignal.User.addTags({
      role: 'patient',
      email: String(patientProfile.user.email || ''),
      phone: String(patientProfile.user.phoneNumber || ''),
      donor: String(patientProfile.bloodDonor ? 'yes' : 'no'),
    });
  }
}, [patientProfile]);
```

### What did you expect to happen?

The tags should appear on the OneSignal dashboard after being added.

### React Native OneSignal SDK version

5.2.2

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Relevant log output

```Shell
- Current tags for the user: `{"donor": "yes", "email": "speetar.patient2@gmail.com", "phone": "+218123123123", "role": "patient"}`
- Push subscription ID: `ed124ccb-a2b0-4b9c-a4ba-a8c81ed89796`
- Push subscription token: `94f7ca889631e9fc124477e4f2929cdcf0d74dcbeff8aa41711d8270d6c69189`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hamzaali98** [comment]
As can be seen in the following screenshot the user is being registered but the user tags are not there.

![Screenshot 2024-10-16 at 21 26 02](https://github.com/user-attachments/assets/d7d7153c-8ffc-4fa3-9327-f6b2fba4f3cd)

![Screenshot 2024-10-16 at 21 27 07](https://github.com/user-attachments/assets/3dc7a9b8-3837-4c59-957f-0cf91039eb66)

**Comment by jennantilla** [comment]
Hello @hamzaali98 thanks for your patience. This may have just been a momentary lag in our dashboard logging. If you are still seeing this problem please let us know and we can investigate further!

**Comment by batuhanbag** [comment]
any updates here ? I've exact same issue

**Comment by vicnguyenqt** [comment]
Same issue. Very poor documentation.

**Comment by hariappointy** [comment]
same issue still

**Comment by rainerllera** [comment]
This is happening to me on `"react-native-onesignal": "^5.3.1"` with `"onesignal-expo-plugin": "^2.1.0"`.  @hariappointy did you figure it out?

**Comment by hariappointy** [comment]
@rainerllera I was using more than 2 tags on free plan. If we use more than 2 tags the logs show success and get tags also works but tags will not be registered. Try with only 2 tags. I migrated to FCM completely.
