### ISSUE TITLE
[Bug]: Open Settings alert keep prompt out

### ISSUE THREAD

**Issue by cre8tech-developer** [OneSignal/react-native-onesignal#1755]
### What happened?

I've encountered an issue with the iOS notification permission flow using OneSignal. When we call OneSignal.Notifications.requestPermission(true), the expected prompt appears, allowing the user to either click "Allow" or "Don't Allow." However, regardless of the user's choice, an alert to open the Settings may unexpectedly appear.

### Steps to reproduce?

```Markdown
1.Set OneSignal.Notifications.requestPermission(true) 
2.Click "Allow" or "Don't Allow"
3."Open Settings" alert will prompt out
```

### What did you expect to happen?

Should not show "Open Settings" alert

### React Native OneSignal SDK version

5.2.3, 5.2.5

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by parulgarg004** [comment]
@cre8tech-developer have you solved this issue?
