### ISSUE TITLE
[question]: Identity verification

### ISSUE THREAD

**Issue by tiagotwistag** [OneSignal/react-native-onesignal#1759]
### How can we help?

Hi,
Is there any timeline for identity verification to be added to the new SDK(v5)? Sadly, this blocks us from moving forward with the update

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @tiagotwistag thanks for your patience! We are working on a beta release for wrappers that should be ready in the next several weeks. Please keep an eye on our [releases](https://github.com/OneSignal/react-native-onesignal/releases) to see when it is ready to try out!

**Comment by liamjones** [comment]
Hi @jennantilla - I'm checking on module upgrades in our project - Identity Verification (JWT) still isn't available in the v5 SDKs yet, correct?

**Comment by nan-li** [comment]
Hi @liamjones that is correct. They are only available as beta releases in the native OneSignal Android and iOS SDKs.
