### ISSUE TITLE
Unable to get the example working

### ISSUE THREAD

**Issue by ranjithnori** [OneSignal/react-native-onesignal#176]
I cloned the repo and tried to run the examples like its mentioned in the docs but I couldn't. It seems like I'm missing something here. Can someone help me out ?

Here's the error message:

The build fails on xcode with the following error. 

OneSignal pod version : 1.13.3

![screen shot 2017-02-02 at 4 14 34 pm](https://cloud.githubusercontent.com/assets/4106656/22546352/bccd015e-e962-11e6-90d1-d8d73cf4a6c3.png)

**Comment by avishayil** [comment]
Hi @ranjithnori , your pod version is too Old.
`cd ios && pod update` should solve the problem.

**Comment by ranjithnori** [comment]
Thanks for the quick response, that fixed it! :)
