### ISSUE TITLE
[question]: An update in APNs certificate, do i need to do anything on my end?

### ISSUE THREAD

**Issue by sleekLancelot** [OneSignal/react-native-onesignal#1769]
### How can we help?

Hi there, so i got this mail from apple some days ago concerning an update in APNs certification authority.

> 
> Hello,
> 
> As we announced in October, the Certification Authority (CA) for Apple Push Notification service (APNs) is changing. APNs will update the server certificates in sandbox on January 20, 2025, and in production on February 24, 2025. To continue using APNs without interruption, you’ll need to update your application’s Trust Store to include the new server certificate: SHA-2 Root : USERTrust RSA Certification Authority certificate.
> 

Do i need to do anything on my end or is this something to be handled by onesignal?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Thank you for sharing this. We are aware of this changes from Apple and there is nothing you need to do on your end. Our service will continue to work as usual.

Thanks!

**Comment by teoilucas** [comment]
Hello! My app uses onesignal to send push notifications but it seems like iOS devices stopped receiving push notifications.
Do you guys know what we can do to fix it?
Thanks!
