### ISSUE TITLE
Since upgrading to 0.30 (RN 0.40) cannot find header file OneSignal/OneSignal.h

### ISSUE THREAD

**Issue by yogiben** [OneSignal/react-native-onesignal#177]
Since an upgrade to 0.30, getting missing header errors on both run and build.

![image](https://cloud.githubusercontent.com/assets/1703155/22544231/3262cbee-e934-11e6-8af5-45e26aecdd00.png)

**Comment by avishayil** [comment]
Can you share a repository with the reproduced error?

**Comment by avishayil** [comment]
Hi @yogiben did you manage to sort this out?

**Comment by avishayil** [comment]
Closing this for now, let me know if you have any issues. Thanks!
