### ISSUE TITLE
libRCTOneSignal.a not found

### ISSUE THREAD

**Issue by abhitheawesomecoder** [OneSignal/react-native-onesignal#178]
![screen shot 2017-02-02 at 10 51 39 pm](https://cloud.githubusercontent.com/assets/3944526/22560387/6609745a-e99a-11e6-864c-a31b0380f2f3.png)

**Comment by avishayil** [comment]
I think it's the same problem as #176

**Comment by avishayil** [comment]
Hi @abhitheawesomecoder did you manage to get around this issue? Would you like to share a repo with the issue reproduced?

**Comment by abhitheawesomecoder** [comment]
Yes, you we're right about the issue

**Comment by avishayil** [comment]
Great!
