### ISSUE TITLE
Update the documentation for initWithLaunchOptions autoRegister

### ISSUE THREAD

**Issue by Ouadie** [OneSignal/react-native-onesignal#179]
The `autoRegister` is not present in the last version of OneSignal it's replaced with `
settings:@{kOSSettingsKeyAutoPrompt: @false}`

>  self.oneSignal = [[RCTOneSignal alloc] initWithLaunchOptions:launchOptions
>                                                        appId:@"myAppId"
>                                                       settings:@{kOSSettingsKeyAutoPrompt: @false}];

**Comment by avishayil** [comment]
Could you set a PR? If not I'll do it tomorrow.

**Comment by avishayil** [comment]
https://github.com/geektimecoil/react-native-onesignal/commit/cf883d889b83392215cc4d8fe6220c6b9e10b0c5 fixes this.
