### ISSUE TITLE
Is there a way to get the previously received notifications?

### ISSUE THREAD

**Issue by sriraman** [OneSignal/react-native-onesignal#180]
I want to get all the list of notifications which are cleared by the user without clicking on it. I can view those notifications in the Onesignal.db. But, I couldn't find the way to get the notifications through `OneSignal` API.

**Comment by avishayil** [comment]
https://documentation.onesignal.com/reference#view-notifications
I think that's all you can do, but they are not user-specfic.
I think the best you can do is to track them by yourself with `onNotificationReceived` and `onNotificationOpened`

**Comment by sriraman** [comment]
`onNotiicationOpened` will be called only if the user clicks on the notification.

`onNotificationReceived` will be called only if the React Native is running in the background. But, React native will be killed after few minutes if the user goes to background.

So, If the user dismisses the notification and the react native layer is not alive on that particular time, then the Javascript layer will not receive the data.

**Comment by sriraman** [comment]
All those information are stored in the `OneSignal.db`. If there is a way to access that info through OneSignal RN module, It will be nice.

**Comment by avishayil** [comment]
That would be something that the OneSignal team might consider. I'm closing the issue and tagging @jkasten2 , since it's not an existing functionality that they provide.
Thanks @sriraman .
