### ISSUE TITLE
react-native-onesignal + react-native-maps crashes app

### ISSUE THREAD

**Issue by andypavia** [OneSignal/react-native-onesignal#181]
If you have both [react native maps](https://github.com/airbnb/react-native-maps) and react-native-onesignal make sure you compile react-native-maps in the following way (android/app/build.gradle).

```
compile(project(':react-native-maps')){
    exclude group: 'com.google.android.gms', module: 'play-services-base'
    exclude group: 'com.google.android.gms', module: 'play-services-maps'
  }
  compile 'com.google.android.gms:play-services-base:+'
  compile 'com.google.android.gms:play-services-maps:+'
```

**Comment by avishayil** [comment]
Hey @andypavia I didn't quite get the issue. Did you manage to solve it and just want the solution to be documented? Or you still have an issue? If you managed to solve it, I'll be happy to accept PRs to the FAQ section with the problem and solution.

**Comment by avishayil** [comment]
I'll add this to the FAQ section.

**Comment by roziki-dev** [comment]
thanks, working,,,, 
but problem in react-native-google-places

**Comment by dinukasal** [comment]
This works! :smile:

**Comment by red62labs** [comment]
not working still crashed on OneSignal.init("661874516")
