### ISSUE TITLE
addEventListerner is not a function

### ISSUE THREAD

**Issue by martwetzels** [OneSignal/react-native-onesignal#183]
When implementing the addEventListeners on iOS (haven't checked Android yet) I get the following error: ```_reactNativeOneSignal2.default.addEventListener is not a function```

Followed the instructions from the README and cannot find any other issue concerning this issue. 

The project is on RN 0.41.2, RN-OneSignal 3.0.1.

```
import OneSignal from 'react-native-onesignal'

  componentWillMount(){
    OneSignal.addEventListener('received', this.onReceived);
    OneSignal.addEventListener('opened', this.onOpened);
    OneSignal.addEventListener('registered', this.onRegistered);
    OneSignal.addEventListener('ids', this.onIds);
  }

  componentWillUnmount() {
    AppState.removeEventListener('change', this._handleAppStateChange.bind(this))
    OneSignal.removeEventListener('received', this.onReceived);
    OneSignal.removeEventListener('opened', this.onOpened);
    OneSignal.removeEventListener('registered', this.onRegistered);
    OneSignal.removeEventListener('ids', this.onIds);
  }

onOpened(openResult) {
    console.log('Message: ', openResult.notification.payload.body);
    console.log('Data: ', openResult.notification.payload.additionalData);
    console.log('isActive: ', openResult.notification.isAppInFocus);
    console.log('openResult: ', openResult);
  }

  onRegistered(notifData) {
      console.log("Device had been registered for push notifications!", notifData);
  }

  onIds(device) {
      console.log('Device info: ', device);
  }

```

These are the parts of the code in my main.js that I directly copied from the README so don't think there is anything wrong there.. Any other code you need?

**Comment by avishayil** [comment]
@martwetzels Please update the `react-native-onesignal` library to 3.0.2, this is where we introduced the change.

**Comment by martwetzels** [comment]
That did the trick, didn't know this got introduced in 3.0.2. Thanks for the quick reply.

**Comment by yaseralimardany** [comment]
same problems.

version of one signal is: "react-native-onesignal": "^3.2.1",

**Comment by bruno9520** [comment]
@yaseralimardany i have the same issue :S any idea how to fix it, i tried using OneSignal.configure(); but it did not work

**Comment by yaseralimardany** [comment]
I got this error in logcat:
E/OneSignal: Unknown error getting FCM Token
java.lang.NoSuchMethodError: No static method isDeviceProtectedStorage(Landroid/content/Context;)Z in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in /data/app/com.motoshubapp-2/base.apk)
at com.google.firebase.FirebaseApp.zza(Unknown Source)
at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
at com.onesignal.PushRegistratorFCM.initFirebaseApp(PushRegistratorFCM.java:64)
at com.onesignal.PushRegistratorFCM.getToken(PushRegistratorFCM.java:50)
at com.onesignal.PushRegistratorAbstractGoogle.attemptRegistration(PushRegistratorAbstractGoogle.java:97)
at com.onesignal.PushRegistratorAbstractGoogle.access$100(PushRegistratorAbstractGoogle.java:37)
at com.onesignal.PushRegistratorAbstractGoogle$1.run(PushRegistratorAbstractGoogle.java:84)
at java.lang.Thread.run(Thread.java:818)
