### ISSUE TITLE
idsAvailable not Fetching Player ID

### ISSUE THREAD

**Issue by santhoshvkumar** [OneSignal/react-native-onesignal#188]
I tried using idsAvailable 
`OneSignal.idsAvailable((aa) => { console.log(aa); });`
I am getting not a function error.
When I tried using  `OneSignal.addEventListener('ids', this.onIds);` it's working for the first time when app is get registered, but what I want to achieve is when user clicks a button during that time I need to get the Player ID. How to achieve this ?

**Comment by avishayil** [comment]
@santhoshvkumar `idsAvailable` is an event listener, means that when the event is emitting you'll get your data.
The only way to achieve what you're describing here is to use the listener, store the data inside your application state and use it later.

**Comment by santhoshvkumar** [comment]
@avishayil thanks for the quick reply. Now the complexity increases, when I do `OneSignal.addEventListener('ids', this.onIds);` it call once when the Permission setting changed for once. Where as my doubt is I am doing the dev testing and I deleted the app and re-installed it multiple times but not every time device asked for permission, so most of the time ids handler not called.
 If this is going to be case. Let's say two user switch the devices and work if I am Purely depend on **PlayerID** now the notification is will not goto the user I wanted to send. Can you give me some insight on this.

**Comment by avishayil** [comment]
@santhoshvkumar I'm not sure I fully understood your problem.
The `idsAvailable` is called once every time the app is run, according to every test I made so far.
Honestly, I never tried to play with the permissions and see.
Could you please try to re-phrase your issue? or maybe simplify it to actions? What are you doing, what is your expected result, what is happening... etc.

**Comment by santhoshvkumar** [comment]
@avishayil Let me try Re-Phrasing My Query. I have **_index.io.js_** in which I have

```javascript
componentWillMount() {
        OneSignal.addEventListener('received', this.onReceived);
        OneSignal.addEventListener('opened', this.onOpened);
        OneSignal.addEventListener('registered', this.onRegistered);
        OneSignal.addEventListener('ids', this.onIds);
    }
onIds(device) {
        console.log('Device info: ', device);
    }
```
So every time I open the app my expectation is  **onIds**  should be called to fetch the **PlayerID** but it's not Calling every time.

Since this is failing I tried to do the following method
```javascript
componentWillMount() {
   OneSignal.idsAvailable((checkValue) => {
            console.log(checkValue);
    });
}
```
![whatsapp image 2017-02-11 at 10 42 28 am](https://cloud.githubusercontent.com/assets/5351539/22851414/dfbaef6a-f046-11e6-9964-e0aebb49a793.jpeg)


What's the best method to get **PlayerID** when ever I open the App.

**Comment by avishayil** [comment]
@santhoshvkumar there is not such method `OneSignal.idsAvailable`, so you'll encounter the red screen every time you call it.

According to your setup, `onIds` function should be called every time the app is running. If it is not the situation, i'd love to check why. Do you have any repo to reproduce this error?

**Comment by avishayil** [comment]
@santhoshvkumar did you manage to sort this out?

**Comment by santhoshvkumar** [comment]
@avishayil Yes sorted it out. It my bad I gave the call in inner router when I moved it to root file it got fixed. Weird though but it's working. Thanks for the response.
