### ISSUE TITLE
Android JS Crash

### ISSUE THREAD

**Issue by sarriaroman** [OneSignal/react-native-onesignal#189]
When react-native-onesignal is imported on RN 0.42 I'm getting a red screen with the error in the line 26 of index.js:

```
}).catch((...args) => console.error("Error: ", args));
```

The app starts again after remove the import.

**Comment by avishayil** [comment]
@sarriaroman This is related to the internet connection, I think i'd better change it to `console.warn` rather than `console.error`. Thanks!

**Comment by sarriaroman** [comment]
Yes... it's related to the internet connection. Sorry I forgot that on the issue. By changing the console as you mention will solve the error ;). Thanks

**Comment by avishayil** [comment]
@sarriaroman could you please make a PR for this? i'm AFK for some time.

**Comment by sarriaroman** [comment]
Yes of course. I will create the PR

**Comment by sarriaroman** [comment]
PR created. #190

**Comment by avishayil** [comment]
Solved with #190
