### ISSUE TITLE
How to handle notification when app opened from a cold start (iOS)

### ISSUE THREAD

**Issue by 151dd** [OneSignal/react-native-onesignal#191]
When the app is opened from a notification when it is in the foreground or background, everything works great. However if the app is opened from a notification and the app isn't already running, it has no knowledge of the notification data when opened. How do I solve this?

**Comment by avishayil** [comment]
@danrice01 If I get this right, you're saying that:
- The app is killed (not appearing in the recent apps drawer).
- User clicks on a notification (drawer or lock screen)
- `opened` event doesn't work.

Personally, I tested the `opened` event from a cold start and it works well.

Can you try debugging it further? go to https://github.com/geektimecoil/react-native-onesignal/blob/master/ios/RCTOneSignal/RCTOneSignal.m#L42 and put a breakpoint on Xcode, try to see if the app stops there while expected. You can test it with this configuration:

![Image](http://i.imgur.com/SaDr1B1.png "Image")

**Comment by avishayil** [comment]
Hi @danrice01 any additional insights? did you manage to work this issue out?

**Comment by 151dd** [comment]
Hi @avishayil thanks for the speedy reply. I've now discovered this was an issue with a callback in my code. Not sure why it's only an issue on cold start, but looks like it's a problem with my implementation and nothing to do with this module. Thanks again.

**Comment by avishayil** [comment]
@danrice01 Glad you sorted this out.

**Comment by jonolock91** [comment]
@danrice01 - Hi, how did you resolve your issue with the notification not notifying onOpened on a cold start? I'm having the same issue and cannot for the life of me figure it out.

**Comment by binchik** [comment]
@jonolock91 I'm having the same problem, did you figure it out? `opened` not called on a cold start. It works only if I have remote debugging enabled.

**Comment by 151dd** [comment]
Hi @jonolock91, from memory I originally had OneSignal event listeners inside a callback which had a delay in firing after boot. Once I moved them outside of that it worked fine. Worth checking if you have a similar setup.

**Comment by jordanmkoncz** [comment]
Just a heads up that I've posted a pretty lengthy comment at https://github.com/geektimecoil/react-native-onesignal/issues/332#issuecomment-341326624 discussing this problem.
