### ISSUE TITLE
Receiving messages without displaying notification

### ISSUE THREAD

**Issue by afshinm** [OneSignal/react-native-onesignal#192]
I'm not sure how feasible my request is but, what I want to do is receiving the message but avoid displaying that notification (alert style) immediately. For instance, I want to get the message on clientside, then process it and display the notification to the user. 

Is this possible to use this library and OneSignal this way?

**Comment by avishayil** [comment]
I think you can do it in a couple of ways:
1. Silent notifications - read about it, I'm not sure we're supporting this in the module here, but I think it's on the todo list.

2. Send a notification, save the payload and then cancel it using `cancelNotification` - never tried to use it though.

Let me know how it works for you.

**Comment by avishayil** [comment]
Hey @afshinm did you manage to sort this issue?

**Comment by note89** [comment]
```
OneSignal.inFocusDisplaying(0);
```
should do the trick but its a bit buggy and sometimes shows the alert anyway.

**Comment by anjar10** [comment]
Hello @afshinm just create notification with content_available=true.

**Comment by tmjordan** [comment]
@afshinm hi man, please have you find how to receive message without showing an alert?

**Comment by tmjordan** [comment]
@anjar10 , hi man, it's not working for me

**Comment by tmjordan** [comment]
@note89, hi it's not working for me
