### ISSUE TITLE
Update the documentation for onNotificationOpened: function(message, data, isActive)

### ISSUE THREAD

**Issue by Ouadie** [OneSignal/react-native-onesignal#194]
I've just tested with the last version of oneSignal and the version **v3.0.0** of **react-native-onesignal** You should change `onNotificationOpened: function(message, data, isActive)`  by `onNotificationOpened: function(notificationData, isActive)` and you can get the message and data from
 `message=notificationData.notification.payload.title` and `data=notificationData.notification.payload.additionalData`

**Comment by avishayil** [comment]
Hi @Ouadie , the latest version is 3.0.3 and the documentation has been changed. Please keep updated with it.
Thanks for noticing!
