### ISSUE TITLE
opened event not firing when running release version of app

### ISSUE THREAD

**Issue by jonolock91** [OneSignal/react-native-onesignal#195]
I've got my push notification coming through and the 'opened' event gets fired on my debug version of the app from both a cold start and while the app is running. However when I test my release version the event fires when the app is running, but doesn't when the app is completely closed. The app opens but then nothing happens, it should trigger my alert. I'm testing this by running an alert for my callback, this fires on my debug app but not on my release app. Tested only on iOS.

It also seems to lock/break my navigation when the app loads.

I'm using the version 0.40 of RN and the latest version of this library.

Any ideas? I'd be grateful!

**Comment by jonolock91** [comment]
I've tried the breakpoint recommendation on here https://github.com/geektimecoil/react-native-onesignal/issues/191 on line 42, and my code does break at the desired point. But I'm not sure why my callback doesn't get fired still

**Comment by twohotko** [comment]
i am also facing this problem now , i follow the instruction and all are fine. However when the app is killed then onOpened will not be fired.

please help on this issue

**Comment by twohotko** [comment]
btw i am using RN 0.30
it is fully support backward compatible?

**Comment by jeroenbourgois** [comment]
I am having similar issues, still trying to pinpoint the problem, but on Android it seems the event is not always reached.

**Comment by binchik** [comment]
I'm facing the same problem, haven't tried on Android yet. On iOS everything works fine if I have remote debugger enabled (both in debug and release schemes). However if I turn it off, `opened` event is not fired in case the app is launched via a notification (it works as expected if the app is in background or foreground mode).

I put breakpoints in Xcode project, the notification is delivered in `launchOptions` but it never reaches the `opened` event, though native code's `eventDispatcher` sends `remoteNotificationOpened` on cold start successfully.

@jonolock91 @jeroenbourgois @twohotko  did you figure your issue out?

UPDATE:

I got it working by subscribing to `opened` event in global scope. Seems like the `opened` was emitted before I subscribed to it in `comonentWillMount`. Cannot say that I'm satisfied with the global scope approach, so if anyone has another solution, please share it.

**Comment by jonolock91** [comment]
@binchik - I hadn't figured it out yet, I was hoping there would be a patch at some point. How have you managed to subscribe to the event in the global scope, what is your event bound to?

**Comment by binchik** [comment]
@jonolock91 here's what I did: https://gist.github.com/binchik/3cc63fbc615dcb20619ef8e44983e7e8

**Comment by jeroenbourgois** [comment]
@binchik no, no success so far

**Comment by jonolock91** [comment]
@binchik Have just tried your approach which I thought worked at first, but its hit and miss, sometimes the 'opened' event triggers and sometimes it doesn't, the same with my approach. I'm really not sure if it's because I'm running and unpublished version of my app from Xcode in release mode, I may have to push it to Test Flight and see how it performs there.

**Comment by avishayil** [comment]
Please let me know if you have any more issues with this.

**Comment by jonolock91** [comment]
Sorry should have closed, in the end I managed to get it working by moving the event listeners outside of the Redux class - https://github.com/geektimecoil/react-native-onesignal/issues/206#issuecomment-295627262

**Comment by jordanmkoncz** [comment]
Just a heads up that I've posted a pretty lengthy comment at https://github.com/geektimecoil/react-native-onesignal/issues/332#issuecomment-341326624 discussing this problem.
