### ISSUE TITLE
App automatically requesting permissions 

### ISSUE THREAD

**Issue by edo1493** [OneSignal/react-native-onesignal#197]
Hello,
I am on the latest RN and OneSignal (thanks for the fix). I am seeing this behaviour where the app automatically asks for Push permissions when the app is loaded. I am not calling anything inside the JS side, so I guess this is something that comes with the library. 

I was wondering if this is an expected behaviour or not, cause I'd like to ask the user for permissions when I want, not at the start. 

Thanks

**Comment by Ouadie** [comment]
You should use **kOSSettingsKeyAutoPrompt**
```
self.oneSignal = [[RCTOneSignal alloc] initWithLaunchOptions:launchOptions
appId:@"myAppId"
settings:@{kOSSettingsKeyAutoPrompt: @false}];
```

**Comment by shafy** [comment]
And then we can just do
```
// Setting requestPermissions
permissions = {
    alert: true,
    badge: true,
    sound: true
};
OneSignal.requestPermissions(permissions);
```

And if the user agrees, he is subscribed? Or am I missing something?
