### ISSUE TITLE
android app crash with react-native-maps

### ISSUE THREAD

**Issue by sonnylazuardi** [OneSignal/react-native-onesignal#2]
I used react-native-onesignal with react-native-maps, but when opening my page containing maps, it crashes. any idea how to solve it? thanks

**Comment by avishayil** [comment]
Hi, do you have a crash report?

**Comment by sonnylazuardi** [comment]
how do we get crash report?

**Comment by avishayil** [comment]
Can you run your app using Android Studio and capture error output from
your app in debug mode?

**Comment by danpe** [comment]
A stack trace? try debugging so you will get a red screen with the error
and stack trace

**Comment by sonnylazuardi** [comment]
@danpe @avishayil fixed this by deleting https://github.com/geektimecoil/react-native-onesignal/blob/master/android/build.gradle#L24

**Comment by avishayil** [comment]
Awesome!

**Comment by note89** [comment]
so the solution is to remove 
`onesignal_app_id` ? Isn't that required to actually use the lib ?
