### ISSUE TITLE
Notification time updated if turn off the screen and then turn on with app open in the foreground

### ISSUE THREAD

**Issue by chunghe** [OneSignal/react-native-onesignal#203]
I've ran into a weird bug and couldn't find any related ticket. It would be really helpful if someone could shed light one it. Thanks in advance!

**react-native-onesignal version**: 1.2.3

**reproducible steps**:

originally time of the notification is 9:29
![media-20170223](https://cloud.githubusercontent.com/assets/78242/23241109/4fac0aa2-f9ac-11e6-97e1-31962917986d.png)

Open the app, keep it in the foreground, turn off the screen, then turn on the screen. It looks like those notifications being 'reprocessed' and time of it updated to 9:34.
(This bug only happens if app is open in the foreground)
![media-20170223 1](https://cloud.githubusercontent.com/assets/78242/23241110/4fb22310-f9ac-11e6-92d6-be41921b75b0.png)

**Comment by jkasten2** [comment]
@chunghe Thanks for the details. I was not able to reproduce the issue on Android 7.0 but was on Android 5.0.1. You are correct the SDK will represent the notification, this done to make sure the notification wasn't missed. However it does unintentionally update the received time as well.

I have opened issue https://github.com/OneSignal/OneSignal-Android-SDK/issues/179 on our Android Native SDK repo to track the progress there.

**Comment by chunghe** [comment]
@jkasten2 Glad it is reproducible. Appreciate!
