### ISSUE TITLE
onOpened is not firing when the app is start from a notification (Android)

### ISSUE THREAD

**Issue by tchamio** [OneSignal/react-native-onesignal#206]
When the app is in the foreground or background, everything works great. However if the app is opened from a notification and the app isn't already running, the onOpened function is not firing.

**Comment by MikePodgorniy** [comment]
iOS to have the same problem. 
But when running debug mode everything works as expected
How to fix it?

**Comment by jonolock91** [comment]
+1 Having issue with this on iOS realease app opening from a fresh start.

**Comment by derdawid** [comment]
+1 #209

**Comment by dcolin** [comment]
Same problem on Android RN 0.42 but works with iOS.

**Comment by jeroenbourgois** [comment]
Same problem on Android RN 0.42, works on iOS

**Comment by dcolin** [comment]
I found the problem on Android, seems `$ react-native link` does not edit correctly the `MainApplication.java` file, you need to import :

```
...
import com.geektime.rnonesignalandroid.ReactNativeOneSignalPackage;
```

And add :
```
protected List<ReactPackage> getPackages() {
  return Arrays.<ReactPackage>asList(
    new MainReactPackage(),
    new ReactNativeOneSignalPackage() // Add this line
  );
}
```

Check [the example](https://github.com/geektimecoil/react-native-onesignal/tree/master/examples/RNOneSignal), it works fine.

**Comment by jeroenbourgois** [comment]
@dcolin sadly that was not the case :( The event fires sometimes, just not _every_ time.

**Comment by cihancil** [comment]
@jeroenbourgois Does it happen when you exit the app pressing back button?

That's the case onOpened does not get called for me.

**Comment by chunghe** [comment]
Same for both iOS/Android. i'm using latest version of react-native-onesignal (3.0.3) and react-native(0.43.3). If the app is in the background or foreground, `opened` handler receives correct payload and click on the push notification will navigate to the page accordingly. But if the app not exist in the background, click on the navigation will only bring the app to the foreground, the `opened` handler not called at all.

Is there a workaround for this issue? It's a huge setback for us :(

**Comment by vladimir-fsh** [comment]
Event listeners don't work in the redux wrapped component. If defined listeners before then that works

**Comment by madmaw** [comment]
Adding `android:launchMode="singleTop"` to the manifest fixed this for me, but did introduce a problem where the user can hit back and end up in the same app!

**Comment by jonolock91** [comment]
@vladimir-fsh This actually seems to work for me now (hoping it doesn't suddenly stop working), moving the event listener outside of my Redux Class in my index file. I was having an issue for some time - https://github.com/geektimecoil/react-native-onesignal/issues/195

**Comment by LEEY19** [comment]
@jonolock91 Hi Johnathan, may I ask how did you move the event listener outside of the redux class? do you mean that this class is not inside the Provider component?

**Comment by jonolock91** [comment]
@LEEY19  This is a snippet of my code with bits cut out for simplicity. So the OneSignal event listener is outside of my class. This is my index.js by the way.

```
'use strict';

// React/Redux
import React, { Component } from 'react';
import {
    Router,
    Scene,
    Actions as Route
} from 'react-native-router-flux';
import { createStore, applyMiddleware, combineReducers, compose } from 'redux';
import { connect, Provider } from 'react-redux';
import logger from 'redux-logger'

import reducers from './src/reducers';

import {
    Alert,
    ...
} from 'react-native';


// Redux setup
const RouterWithRedux = connect()(Router);
const middleware = [/*logger*/];
const store = compose(
  applyMiddleware(...middleware)
)(createStore)(reducers);

OneSignal.addEventListener('opened', (openResult) => {
    // **
    // Handle OneSignal push notification
    // **
    Route.handlePushNotification();
});


class App extends Component {
    render() {
        return (
            <Provider store={store}>
                <RouterWithRedux>
                        <Scene
                        ...
                        </Scene>
                </RouterWithRedux>
            </Provider>
        );
    }
}

AppRegistry.registerComponent('my_app', () => App);
```

**Comment by jordanmkoncz** [comment]
Just a heads up that I've posted a pretty lengthy comment at https://github.com/geektimecoil/react-native-onesignal/issues/332#issuecomment-341326624 discussing this problem.

**Comment by udarts** [comment]
Hi Guys I know this is an old issue but I am running into a similar issue:

https://github.com/geektimecoil/react-native-onesignal/issues/676#issuecomment-441230605
