### ISSUE TITLE
This Doesnt Work

### ISSUE THREAD

**Issue by haabnaseem** [OneSignal/react-native-onesignal#21]
i have followed your documentation, and it does not work. i think you should test before posting here.

**Comment by avishayil** [comment]
Hi, what doesn't work? can you post the error / some details?
Thanks!

**Comment by dansjensen** [comment]
It is working for me on iOS. I recommend looking at the example AwesomeProject to verify that you have the same settings.

**Comment by avishayil** [comment]
Please re-open this thread when you have more details.
Thanks!

**Comment by haabnaseem** [comment]
Hi, i followed your instructions to install this package, i got Onesignal.h not found error in Xcode.

**Comment by avishayil** [comment]
You need to install the OneSignal pod as the documentation says.
Also make sure that you link all the libraries like in the documentation.
