### ISSUE TITLE
Do not show notification when in a certain screen of App

### ISSUE THREAD

**Issue by nickrobinson352** [OneSignal/react-native-onesignal#210]
I have my app showing a notification when the application is in the foreground, however I would like to suppress this when its on a given screen of the app. How do I go ahead and achieve it ?

```
OneSignal.addEventListener('received', this.onReceived.bind(this))

onReceived (notification) {
    console.log('Notification received: ', notification)
    if (this.isActiveWindow()) {
                 // suppress notification
    }
}

```

**Comment by jeroenbourgois** [comment]
I am not sure, but the docs describe this I guess:
https://github.com/geektimecoil/react-native-onesignal#set-in-app-focus-behavior

```
// 0 None - Will not display a notification,
// instead only onNotificationReceived will fire 
// where you can display your own in app messages.
OneSignal.inFocusDisplaying(0);
```

**Comment by hhravn** [comment]
@nickrobinson352 did you figure out how to do this? inFocusDisplaying only handles Android;

```   //Android only: Set Display option of the notifications. displayOption is of type OSInFocusDisplayOption
    // 0 -> None, 1 -> InAppAlert, 2 -> Notification
    static inFocusDisplaying(displayOption) {
        if (Platform.OS == 'android') {
            RNOneSignal.inFocusDisplaying(displayOption);
        }
    }

**Comment by nickrobinson352** [comment]
I need it in iOS :(

**Comment by avishayil** [comment]
Hi, the only way I can think of is unsubscribing when on the `componentDidMount` method of the necessary screen than re-subscribing on the `componentWillUnmount`.
https://github.com/geektimecoil/react-native-onesignal#change-user-subscription-status
It's not the best out there, but there is no other choice in my opinion.
