### ISSUE TITLE
Open notification in app

### ISSUE THREAD

**Issue by berdof** [OneSignal/react-native-onesignal#215]
I'm sending push notifications via rest api. For web browsers I need to set open url with a link, but using this I have a trouble on ios. When I click on notification it opens web browser but not the app. Am I missing something?

**Comment by jkasten2** [comment]
@berdof This is expected behavior. If you don't want the URL to open on iOS you will need to send 2 notifications. One just to your web users with a launch URL set. And another to just your iOS users without a URL set.
