### ISSUE TITLE
[ios] Not subscribed

### ISSUE THREAD

**Issue by DCKT** [OneSignal/react-native-onesignal#216]
Hello,

I recently update my app to the latest react-native versions, and after some tests my device still `Not subscribed` when I check the BO. (I receive the playerId correctly and I'm able to send tags)

So I went to the [Troubleshooting page](https://documentation.onesignal.com/docs/all-users-are-shown-as-not-subscribed) and I checked all issues but all seems good.

In Xcode, I have the steps checked correctly, so what could be wrong ? 
Also, I guess, I have no conflicting package : 
```
"base-64": "0.1.0",
"keymirror": "0.1.1",
"lodash": "4.17.4",
"moment": "2.17.1",
"react": "15.4.2",
"react-native": "0.42.0",
"react-native-background-geolocation-android": "git+ssh://git@github.com/transistorsoft/react-native-background-geolocation-android.git#2.5.0",
"react-native-image-picker": "0.26.1",
"react-native-localization": "0.1.28",
"react-native-modal-picker-fix": "0.0.20",
"react-native-onesignal": "3.0.3",
"react-native-scrollable-tab-view": "0.7.2",
"react-native-signature-capture": "0.4.5",
"react-native-vector-icons": "4.0.0",
"react-redux": "5.0.3",
"redux": "3.6.0",
"redux-thunk": "2.2.0"
```

Thanks for your help

**EDIT:**  I tried on the project example and I got the same result, does it mean it's a certificat problem ?

**Comment by jkasten2** [comment]
@DCKT The `Not subscribed` status normally means that Apple reported to use the app is no longer installed on your device. If you uninstall the app and reinstalled it you will most likely get a new OneSignal player / user ID and the old one will be reported like this.

Can you contact OneSignal support while logged into your account linking them to this issue. We can check a few things on our end.

**Comment by DCKT** [comment]
Hi @jkasten2 

Yesterday, I've removed the iPhone from the test user and create a new one and it worked perfectly after that. Quite strange

Thanks for your answser

**Comment by jkasten2** [comment]
@DCKT Good to hear you're up and running now.

@DCKT @avishayil Looks like we can close this issue.
