### ISSUE TITLE
How to subscribe and unsubscribe device

### ISSUE THREAD

**Issue by devgenerate** [OneSignal/react-native-onesignal#217]
Hello, in my app I need subscribe my device when login and unsubscribe after logout, just I could use the app with different users (on different moments obviously) and notifications will arrive to the correct user, so if device is subscribed permanently when I install the app the same device will receive notifications of all users who used the app on the same device.

Thanks.

**Comment by theslyone** [comment]
Hi @davidgit75 , I'm also trying to accomplish this, I use react-redux so i had previously created a middleware in which i listen for the relevant events (e.g LOGIN_SUCCESS, LOGOUT_SUCCESS) before binding and unbinding the event listeners, but for some reasons the listener handlers don't get called if not registered on a react component lifecycle event (componentDidMount, componentWillMount etc). I then decided to create a component and watch for a redux store state change before binding, this also does not work for reasons i'm not quite sure of but here is the weirdest of all.

Even setting a timeout before binding does not work
~~~~
...
componentWillMount () {
   setTimeout(() => {
        OneSignal.addEventListener('ids', (ids) =>< {
            console.log('Device info:' + ids)
       })
   }, 5000)
}
...
~~~~

Still debugging to better understand why. Please do share and observations you might also have experienced.

**Comment by theslyone** [comment]
Hi @davidgit75 , I'm also trying to accomplish this, I use react-redux so i had previously created a middleware in which i listen for the relevant events (e.g LOGIN_SUCCESS, LOGOUT_SUCCESS) before binding and unbinding the event listeners, but for some reasons the listener handlers don't get called if not registered on a react component lifecycle event (componentDidMount, componentWillMount etc). I then decided to create a component and watch for a redux store state change before binding, this also does not work for reasons i'm not quite sure of but here is the weirdest of all.

Even setting a timeout before binding does not work

...
componentWillMount () {
   setTimeout(() => {
        OneSignal.addEventListener('ids', (ids) =>< {
            console.log('Device info:' + ids)
       })
   }, 5000)
}
...
Still debugging to better understand why. Please do share any observations you might also have experienced.

**Comment by theslyone** [comment]
Hi @davidgit75 , I'm also trying to accomplish this, I use react-redux so i had previously created a middleware in which i listen for the relevant events (e.g LOGIN_SUCCESS, LOGOUT_SUCCESS) before binding and unbinding the event listeners, but for some reasons the listener handlers don't get called if not registered on a react component lifecycle event (componentDidMount, componentWillMount etc). I then decided to create a component and watch for a redux store state change before binding, this also does not work for reasons i'm not quite sure of but here is the weirdest of all.

Even setting a timeout before binding does not work
```
...
componentWillMount () {
   setTimeout(() => {
        OneSignal.addEventListener('ids', (ids) =>< {
            console.log('Device info:' + ids)
       })
   }, 5000)
}
...
```
Still debugging to better understand why. Please do share and observations you might also have experienced.

**Comment by theslyone** [comment]
Hi @davidgit75 , I'm also trying to accomplish this, I use react-redux so i had previously created a middleware in which i listen for the relevant events (e.g LOGIN_SUCCESS, LOGOUT_SUCCESS) before binding and unbinding the event listeners, but for some reasons the listener handlers don't get called if not registered on a react component lifecycle event (componentDidMount, componentWillMount etc). I then decided to create a component and watch for a redux store state change before binding, this also does not work for reasons i'm not quite sure of but here is the weirdest of all.

Even setting a timeout before binding does not work
```
...
componentWillMount () {
   setTimeout(() => {
        OneSignal.addEventListener('ids', (ids) =>< {
            console.log('Device info:' + ids)
       })
   }, 5000)
}
...
```
Still debugging to better understand why. Please do share any observations you might also have experienced.

**Comment by devgenerate** [comment]
@theslyone I used addEventListener on the app index, just the events are binded on all app, just:

```
  componentWillMount() {
    OneSignal.addEventListener('received', notification => this.onReceived(notification));
    OneSignal.addEventListener('opened', openResult => this.onOpened(openResult));
    OneSignal.addEventListener('registered', notifData => this.onRegistered(notifData));
    OneSignal.addEventListener('ids', device => this.onIds(device))
  }


componentWillUnmount() {
    OneSignal.removeEventListener('received', notification => this.onReceived(notification));
    OneSignal.removeEventListener('opened', openResult => this.onOpened(openResult));
    OneSignal.removeEventListener('registered', notifData => this.onRegistered(notifData));
    OneSignal.removeEventListener('ids', device => this.onIds(device));
  }

componentDidMount() {
    OneSignal.getTags((receivedTags) => {console.log('**++ TAGS RECEIVED ++**', receivedTags); this.props.setDeviceTags(receivedTags)});
  }
```

I dont know if I understood your question, so I am using redux too. If this doesn't help you and I can help you I 'll be careful  to do it.


Really I hadn't understood how can I do it, so add or remove a device according to the login. According to documentation and an answer of the OneSignal people maybe this should made using sessions of onesignal. I don't know still how to do it but if I discovered it I add it to this thread.

```
Hi there, please see the docs for the 3rd party library for how to change subscription status: https://github.com/geektimecoil/react-native-onesignal#change-user-subscription-status
```

**Comment by avishayil** [comment]
For the original question, I would try to use `setSubscription` method.
https://github.com/geektimecoil/react-native-onesignal#change-user-subscription-status
We're still not too familiar how this library works with redux and we see some issues regarding it. I hope we'll find some time to adjust the library to make it work right with redux.

**Comment by amit13091992** [comment]
> For the original question, I would try to use `setSubscription` method.
> https://github.com/geektimecoil/react-native-onesignal#change-user-subscription-status
> We're still not too familiar how this library works with redux and we see some issues regarding it. I hope we'll find some time to adjust the library to make it work right with redux.

Hi @avishayil Why the link which you have mentioned, opens the official Github repository of oneSignal only? and please do suggest that how can I achieve this unsubscribe feature for onesignal. Thanks
