### ISSUE TITLE
How to show android banner background and foreground?

### ISSUE THREAD

**Issue by yoonjaepark** [OneSignal/react-native-onesignal#218]
```
      OneSignal.postNotification(contents,
          {   group: 10,
              priority: 100,
              shown: true, // BOOLEAN: If the notification was displayed to the user or not
              payload: {group: 10,displayType: 2, notificationID : "", contentAvailable : true, badge : 1, sound : "default", title : "Hello!", body : "World", launchURL : "", }, // OBJECT; the push data
              displayType: 2, //The display method of a received notification
              silentNotification: false // BOOLEAN : Wether the received notification was a silent one
          }
          , this.state.device_info.userId)
```

this code is Example work just push
![kakaotalk_photo_2017-03-18-02-27-22_77](https://cloud.githubusercontent.com/assets/6939460/24055185/72501b9c-0b82-11e7-8b3a-4fa8cb108535.jpeg)

![image](https://cloud.githubusercontent.com/assets/6939460/24055671/419eecb0-0b84-11e7-8744-c822fb89a0b8.png)

how to show android banner???

**Comment by jkasten2** [comment]
@YoonJaePark I see you have priority set 100 which anything above 9 will make it a heads up notification shown in Google's docs below.
https://developer.android.com/guide/topics/ui/notifiers/notifications.html#Heads-up

Make sure you are using the latest version of this SDK and you are testing on a Android 5.0 or newer device.

Thanks.

**Comment by yoonjaepark** [comment]
@jkasten2 HaHa. Thank you sir. but don't work priority and group and not showing heads-up.. i don't know.
And i want use OneSignal.configure not work
my Code
not work console log help plz
 ```
 componentDidMount() {
    OneSignal.configure({
      onNotificationOpened: this.handleNotification.bind(this),
      onNotificationReceived: function(notification) {
       console.log("notification received: ", notification);
      }
    });
  }
```

**Comment by jkasten2** [comment]
@YoonJaePark Sorry I overlooked this before, `OneSignal.postNotification` parameters are `(messageBody, additionalData, player_id)`. It doesn't allow any of the options in your first post.

To do this you will need to make a REST API call directly instead of use the `postNotification` function.
https://documentation.onesignal.com/v3.0/reference#create-notification

**Comment by newbiepub** [comment]
You should make a REST API then push notification with `{priority: 10}`
I got an example that use `simple-onesignal`. This works for me 
```var onesignal = require('simple-onesignal');
    onesignal.configure('ONESIGNAL_API_KEY', 'ONESIGNAL_REST_API');
    onesignal.sendMessage({
        large_icon: "ic_launcher",
        contents: {en:'Hello world!'},
        included_segments:['All'],
        data: {id: "123123123"},
        priority: 10
      }, function(err, resp) {
        if(err) {
          console.log(err);
        } else {
          console.log(resp);
        }
      });
```

**Comment by jkasten2** [comment]
@newbiepub You should not include your OneSignal REST API key in your app. Someone could extract it from your app. The OneSignal app id is fine.

You can target users with `include_player_ids` without the API key.

**Comment by newbiepub** [comment]
@jkasten2 I did not include any key in my app. I included it into my server API.
