### ISSUE TITLE
pushToken null on Android

### ISSUE THREAD

**Issue by ddeanto** [OneSignal/react-native-onesignal#220]
When I run the app on an Android device in debug mode I get a null pushToken:
<img width="1111" alt="screen shot 2017-03-19 at 1 47 43 pm" src="https://cloud.githubusercontent.com/assets/8404695/24083307/e16b91c2-0caa-11e7-881a-719b9a692c51.png">
Here is my app/build.gradle and manifest.xml
<img width="914" alt="screen shot 2017-03-19 at 1 42 49 pm" src="https://cloud.githubusercontent.com/assets/8404695/24083259/24363756-0caa-11e7-964e-4275ffaab455.png">
<img width="949" alt="screen shot 2017-03-19 at 1 37 54 pm" src="https://cloud.githubusercontent.com/assets/8404695/24083260/2437da0c-0caa-11e7-91b0-61dd849d57ae.png">

**Comment by ddeanto** [comment]
turns out `{ exclude group: 'com.google.android.gms' }` was stopping google messaging service (gcm) from working (duh). But without it, I run into multiple dex files problem during build, opening a new issue https://github.com/geektimecoil/react-native-onesignal/issues/222

**Comment by adirzoari** [comment]
@ddeanto  I have same issue,did you find solution?

**Comment by werlleydev** [comment]
Same error in version 3.2.7
