### ISSUE TITLE
How to request permissions from the user if he manually disabled notifications?

### ISSUE THREAD

**Issue by segalr3** [OneSignal/react-native-onesignal#221]
I'm calling requestPermissions, but nothing happens.

**Comment by ddeanto** [comment]
That only works for iOS https://github.com/geektimecoil/react-native-onesignal#register-for-push-notifications-ios-only

**Comment by segalr3** [comment]
thanks @ddeanto, I read that one can request the user to allow notifications once, closing the issue.

**Comment by ngnclht1102** [comment]
My question is how to determine whether we can ask for notification from the app or not? 
If not than we will navigate user to the setting page.
