### ISSUE TITLE
multiple dex files

### ISSUE THREAD

**Issue by ddeanto** [OneSignal/react-native-onesignal#222]
I am getting this error during build:

` Multiple dex files define Lcom/google/android/gms/location/places/zzl;`

Here is my app/build.gradle:

<img width="716" alt="screen shot 2017-03-20 at 12 41 08 am" src="https://cloud.githubusercontent.com/assets/8404695/24088849/f7a6eecc-0d05-11e7-9227-49f68ed2ea72.png">

I have gone through the solutions of https://github.com/geektimecoil/react-native-onesignal/issues/20, https://github.com/geektimecoil/react-native-onesignal/issues/48, and https://github.com/geektimecoil/react-native-onesignal/issues/51, https://github.com/geektimecoil/react-native-onesignal#issue-1---multiple-dex-files-define, https://github.com/geektimecoil/react-native-onesignal#issue-2---multiple-dex-files-define-again, and https://github.com/geektimecoil/react-native-onesignal#issue-4---make-react-native-onesignal-work-with-react-native-maps but no luck

thanks!

**Comment by ddeanto** [comment]
I also tried this https://github.com/geektimecoil/react-native-onesignal/issues/220, but this was no good for other reasons

**Comment by ddeanto** [comment]
This fixed it:
```
dependencies {
    compile project(':react-native-onesignal')
    compile project(':react-native-google-places')
    compile project(':react-native-maps')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-svg')
    compile project(':react-native-vector-icons')
    compile project(':react-native-image-crop-picker')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile project(path: ':react-native-testfairy')
    compile 'com.google.android.gms:play-services:10.2.0' // THIS FIXED IT
}
```

**Comment by brascene** [comment]
@ddeanto Thank you for your comments, this issue is annoying, and I'm still getting it, even with your last advice.. don't know what to do
