### ISSUE TITLE
Package com.geektime.reactnativeonesignal does not exist

### ISSUE THREAD

**Issue by ricsirigu** [OneSignal/react-native-onesignal#224]
` package com.geektime.reactnativeonesignal does not exist
import com.geektime.reactnativeonesignal.ReactNativeOneSignalPackage;
 `

I'm on Android with react native 0.42,

I followed the instructions here 

https://github.com/geektimecoil/react-native-onesignal#android-installation

Any ideas? @avishayil

**Comment by jakeatwork** [comment]
I'm having the same issue currently with RN 0.42

**Comment by jakeatwork** [comment]
<img width="1303" alt="ccreact onesignal issue" src="https://cloud.githubusercontent.com/assets/1273830/24275971/afcd2ace-0ff0-11e7-85ad-a270a0035280.png">

**Comment by ricsirigu** [comment]
@jakeatwork the correct import is `import com.geektime.rnonesignalandroid.ReactNativeOneSignalPackage;
`

I managed to solve the issue, there was a conflict with the maps library

**Comment by jakeatwork** [comment]
@ricsirigu worked for me! thanks.

**Comment by snjjain11** [comment]
I'm getting an error stating "Native module RNonesignal tried to override RNonesignal for module name OneSignal. if this was your intention, set can overrideexistingmodule=true

**Comment by nguyengiang160692** [comment]
I just add this line (app/build.grade)
 compile project(':react-native-onesignal')

And it work...

**Comment by lenichols** [comment]
Having the same issue...

**Comment by ignindra** [comment]
@lenichols Have you tried [this](https://github.com/geektimecoil/react-native-onesignal/issues/224#issuecomment-298848869) solution? Apparently after typing `react-native link react-native-onesignal` into the console, it doesn't add that missing line into gradle build file.
I'm currently using RN 0.45.1

**Comment by lingster** [comment]
I had this issue and the problem was caused by running ```react-native link react-native-onesignal``` more than once, which resulted in duplicated imports of onesignal in ```MainApplication.java``` and also in the ```settings.gradle``` file. Might be worth checking for this.

**Comment by mmathea1** [comment]
I had the same exact issue until I realized I had added `new ReactNativeOneSignalPackage()` manually even after `react-native link` had done it for me. So check your _MainApplication.java_ and make sure you only have one entry.

After that, run `react-native run-android` to re-compile
