### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by sinchan** [OneSignal/react-native-onesignal#230]
Shouldn't the `registerForPushNotifications` part of the readme specify that it should only be used when `kOSSettingsKeyAutoPrompt` is `@NO` :

> *Call when you want to prompt the user to accept push notifications. Only call once and only if you passed **@NO** to kOSSettingsKeyAutoPrompt on init.

Instead of: 

> *Call when you want to prompt the user to accept push notifications. Only call once and only if you passed @YES to kOSSettingsKeyAutoPrompt on init.

Because if kOSSettingsKeyAutoPrompt is true then the notification registration is automatically prompted according to the OneSignal iOS native docs.

**Comment by avishayil** [comment]
Solved with https://github.com/geektimecoil/react-native-onesignal/commit/d39fefea91511e5a81f8a3d9408e094d74baf4c5
