### ISSUE TITLE
Question: How can i show badge number in app?

### ISSUE THREAD

**Issue by minhnguyenwp** [OneSignal/react-native-onesignal#231]
I want get badge count and show in app like notification of facebook. 
Can u help me that. using react code to do that. get badge count and **show in header of the app.** 

I dont know how to do that ?  
iOS has this PushNotificationIOS but android has no. 

is there any way to do that?

**Comment by avishayil** [comment]
That's not something related to this library, you should calculate the number of notifications that hadn't been handled by the user than use a UI component to display them.

**Comment by ghost** [comment]
For future references: [PushNotificationIOS.setApplicationIconBadgeNumber](https://facebook.github.io/react-native/docs/pushnotificationios.html#setapplicationiconbadgenumber).
