### ISSUE TITLE
promptForPushNotificationWithUserResponse not available through this API

### ISSUE THREAD

**Issue by joerick** [OneSignal/react-native-onesignal#234]
Hi! Thanks for this module, it's been really useful for us.

In the OneSignal iOS library they've [added](https://github.com/OneSignal/OneSignal-iOS-SDK/commit/d272d35d0739afd212ca45096967e2e442cc5a73) a promptForPushNotificationWithUserResponse, which supplies a callback so the app can do something once the user has made a decision with the dialog.

It would be great to have this ability in this module too!

**Comment by avishayil** [comment]
Thanks, we'll review this for the next versions of this library.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
