### ISSUE TITLE
missing context for property implementation declaration

### ISSUE THREAD

**Issue by vdlindenmark** [OneSignal/react-native-onesignal#236]
Xcode show this message inside AppDelegate.m on the row where this is:
`@synthesize oneSignal = _oneSignal;`

Xcode 8.3, React-native 42.3, react-native-onesignal 3.0.3

**Comment by avishayil** [comment]
Hi @vdlindenmark , could you share a repo with the issue reproduced?
Thanks!

**Comment by vdlindenmark** [comment]
Actually i don't know how to reproduce that warning. I'm not working on that project anymore, but i know at the moment the app runs without any issue.

I close this issue
