### ISSUE TITLE
Feature: Move out all keys from native code to JS side

### ISSUE THREAD

**Issue by dwilt** [OneSignal/react-native-onesignal#239]
In both the [Android](https://github.com/geektimecoil/react-native-onesignal#android-installation) and [iOS](https://github.com/geektimecoil/react-native-onesignal#ios-installation) setup steps, it's required that we put in the OneSignal App ID in multiple places (in `AppDelegate.m` on iOS and in `android/app/build.gradle` for Android). 

Something like:

```js
import OneSignal from 'react-native-onesignal'; // Import package from node modules

const oneSignal = new OneSignal('[OneSignal App ID GOES HERE]');
```
This has several advantages:

1. A lot of projects, since React Native is JS based, have the environment variables accessible in the JS. Whether you are using [12 Factor](https://12factor.net/config) or just have your keys hardcoded in your project, they are most likely living in your JS. This allows the developer to have a key in a single spot and then it gets mapped to the corresponding native code elsewhere. They don't have to go put keys in multiple files.

2. Being that most React Native developers are JS developers and not Objective-C/Swift or Java developers, this is a much more comfortable pattern and would simplify installation and reduce bugs. Installation wouldn't need anything manual as a `react-native link` could then take care of it all because they wouldn't need to customize any files with their app ID.

**Comment by avishayil** [comment]
I think that's generally a good idea, but i'm not sure how capable are we in terms of prioritization of what we want this library to do.
We'd focus on adding more features and trying to fix bugs, than simplify the already-simplified installation instructions & onboarding to this library.

**Comment by Nightsd01** [comment]
I would also agree that this is a good idea @dwilt . Thank you for the excellent proposal.

In our next major release (4.0) we will likely move to this model.

**Comment by rgomezp** [comment]
We have already removed the requirement so you don't have to add the App-Id to the gradle script
