### ISSUE TITLE
Android has conflicts with react-native-push-notification

### ISSUE THREAD

**Issue by raymondctc** [OneSignal/react-native-onesignal#240]
I'm using `react-native-onesignal` with this library, https://github.com/zo0r/react-native-push-notification

However, I found that the event `remoteNotificationReceived` is causing a crash when the app is active and when OneSignal push event is received. As both libraries are sharing the same event name and it seems that it's due to the event being sent out is already a parsed JSON while `react-native-push-notification` will parse the JSON in JS level

```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at index.android.js:71
    at RCTDeviceEventEmitter.emit (EventEmitter.js:181)
    at MessageQueue.__callFunction (MessageQueue.js:236)
    at MessageQueue.js:108
    at guard (MessageQueue.js:46)
    at MessageQueue.callFunctionReturnFlushedQueue (MessageQueue.js:107)
    at debuggerWorker.js:71
```

**Comment by avishayil** [comment]
I think we should handle this, by changing the event names.

**Comment by delvedor** [comment]
Hi! Same issue here :)
