### ISSUE TITLE
linker command failed with exit code 1 / no type or protocol named 'RCTBridgeModule'

### ISSUE THREAD

**Issue by nonameolsson** [OneSignal/react-native-onesignal#243]
Hi!

This works great on Android! It's just me who don't understand how Xcode works. However, I've been struggling almost two days to get the app to build on iOS. 

I really appreciate some help here since I'm stuck.

This is the error message: 
```
Apple Mach-O Linker (ld) Error Group
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
<img width="1680" alt="screen shot 2017-04-13 at 17 53 27" src="https://cloud.githubusercontent.com/assets/1493018/25012915/30f95992-2072-11e7-9269-ff0dcbdebd35.png">

When running `xcodebuild -verbose` this is the output:
<img width="1680" alt="screen shot 2017-04-13 at 17 59 07" src="https://cloud.githubusercontent.com/assets/1493018/25013170/e9af028e-2072-11e7-8c1e-d8887a3ad3ff.png">

Here is my code:
`AppDelegate.m`
```
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "AppDelegate.h"

#import <RNCrashes/RNCrashes.h>
#import <RNAnalytics/RNAnalytics.h>

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import "RCTOneSignal.h"


@implementation AppDelegate
@synthesize oneSignal = _oneSignal;

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  self.oneSignal = [[RCTOneSignal alloc] initWithLaunchOptions:launchOptions
                                                         appId:@"XXXXXXXXXX"];
  
  
  [RNCrashes registerWithCrashDelegate: [[RNCrashesDelegateAlwaysSend alloc] init]];  // Initialize Mobile Center crashes

  [RNAnalytics registerWithInitiallyEnabled:true];  // Initialize Mobile Center analytics

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"OpusApp"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

// Required for the notification event.
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification {
  [RCTOneSignal didReceiveRemoteNotification:notification];
}

@end
```
`AppDelegate.h`
```
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import <UIKit/UIKit.h>
#import <RCTOneSignal.h>

@interface AppDelegate : UIResponder <UIApplicationDelegate>

@property (nonatomic, strong) UIWindow *window;
@property (strong, nonatomic) RCTOneSignal* oneSignal;

@end
```

Config in Xcode
<img width="1680" alt="screen shot 2017-04-13 at 17 56 06" src="https://cloud.githubusercontent.com/assets/1493018/25013026/80e08e08-2072-11e7-939f-21a019738c8d.png">
<img width="1680" alt="screen shot 2017-04-13 at 17 57 05" src="https://cloud.githubusercontent.com/assets/1493018/25013066/a1583988-2072-11e7-8efb-b3f44f829460.png">

I really need some help here guys. Thanks for taking your time to read this issue.

**Comment by qruzz** [comment]
I am having the exact same problem, and haven't been able to solve it!
Anyone found a fix to this ?

**Comment by dcolin** [comment]
Same problem, any idea?

I got this error when running: `xcodebuild -verbose`

```
In file included from ../node_modules/react-native-onesignal/ios/RCTOneSignal/RCTOneSignal.h:4:
../node_modules/react-native/React/Base/RCTBridgeModule.h:12:9: fatal error: 'React/RCTDefines.h' file not found
#import <React/RCTDefines.h>
```

And this one with Xcode:

```
Apple Mach-O Linker Error Group : Linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by faizmokh** [comment]
Currently had the same problem as well. Anyone have the solution? I'm trying to create multiple xcode schemes but stuck at this part.

**Comment by the-mold** [comment]
guys, did anyone solve it? i am having the same issue

**Comment by loehnertz** [comment]
I had the same issue and fixed it!
I did it by including the `react-native-onesignal` module into the 'Linked Frameworks and Libraries' within the Xcode project under 'General'.
Also I dragged the `RCTOneSignal.xcodeproj` file into the `Libraries` directory within my Xcode project.
Now it successfully compiles and everything works flawlessly! :blush:

**Comment by SuhairZain** [comment]
@loehnertz For me, both of them are already there.

Was anyone able to fix this issue?

**Comment by mateoKaradza** [comment]
I have just one issue present, and that's the `no type or protocol named 'RCTBridgeModule'`

@loehnertz  What version of React Native are you using? I'm on newest (0.45.1)

**Comment by IvRRimum** [comment]
@mateoKaradza Having the same issue, updaing the react-native helped and adding React as a first target

**Comment by askarhu** [comment]
Hope you all tried "react-native run-ios" after you installed (and linked especially) new libraries. Most of the time the issue is that we forget to restart the run-ios loop after linking new libraries and that typically causes these issues.
