### ISSUE TITLE
Too low SDK Build Tools Revision

### ISSUE THREAD

**Issue by nonameolsson** [OneSignal/react-native-onesignal#244]
I have upgraded to `react-native: 0.43.3`, and now I can't install the application on my Android anymore.

A problem occurred configuring project: 'react-native-onesignal'. The SDK Build Tools revision (23.0.1) is too low for project ':react-native-onesignal'. Minimum required is 25.0.0`.

I don't really understand. Is the SDK specified in `react-native-onesignal` too low?

<img width="718" alt="screen shot 2017-04-14 at 15 11 44" src="https://cloud.githubusercontent.com/assets/1493018/25044072/bcc1d5dc-2124-11e7-883e-e922d41e634e.png">

**Comment by brascene** [comment]
Same issue here..

**Comment by jkasten2** [comment]
@nonameolsson @brascene You need to update your Android build tools by running `android` from the terminal to bring up the Android SDK Manager.
![image](https://cloud.githubusercontent.com/assets/645861/25195968/06752f26-24f4-11e7-9864-3d7f6a0cc999.png)

It is found in under `<android-sdk-root>/tools/android/`` if it isn't in your `PATH`. It can also be updated in Android Studio from `Tools` > `Android` > `SDK Manager`.

**Comment by brascene** [comment]
I have already installed Build tools 25.0.2. but now I think this issue is not related only with onesignal. In my case, I had to replace every buildToolsVersion for dependencies from build.gradle from 23.0.1 to 25.0.0, but I don't understand why. I was able to build my project normally, until today..
However, I also had to add this to build.gradle: dexOptions { javaMaxHeapSize "4g" }
What could be the cause of this behavior?

**Comment by avishayil** [comment]
@brascene would you mind sharing a repo with your code?

**Comment by mikeduminy** [comment]
This happens when you update the Android plugin for Gradle to 2.3 or higher.

https://developer.android.com/studio/releases/gradle-plugin.html#revisions

**Comment by brascene** [comment]
@avishayil sorry for delayed answer, and as @michaelduminy wrote, the issue is related with gradle version. In my project it was 2.3.1, and after I changed it to lower version 2.2.3 it's working normally without any error.

**Comment by avishayil** [comment]
Great! glad you managed to sort it out!

**Comment by nonameolsson** [comment]
@brascene That solved my problem also!

**Comment by MBach** [comment]
And why should we downgrade gradle to <2.3 and stick to 2.2.3? 2.3 release was published last February

**Comment by nonameolsson** [comment]
@MBach Good question! But that solved my problem. Does this work for you with build tools 2.3?

**Comment by MBach** [comment]
@nonameolsson of course it doesn't work! I found this issue after reading some messages in the console, and I have landed here.

**Comment by nonameolsson** [comment]
@MBach Ok! If you downgrade and clean your project before building, it should work again.

**Comment by MBach** [comment]
@nonameolsson I know, to be honest, I was in 2.2.3 and minSdk 23. When I wanted to upgrade to latest releases in my project, all my dependencies were OK except this one. So I had to revert back
