### ISSUE TITLE
TypeError: OneSignal.configure is not a function Upgrading from RN from v0.34.1 to v0.42.3 and onesignal from v.1.2.3 to v3.0.3

### ISSUE THREAD

**Issue by bgoyal2222** [OneSignal/react-native-onesignal#248]
var OneSignal  =require('react-native-onesignal');

OneSignal.configure({
        onIdsAvailable: function(device) {
          console.log('UserId', device.userId);
          console.log('PushToken', device.pushToken);
        }
};

This code is working properly in RN 0.34.1

i tried
import OneSignal from 'react-native-onesignal';
then it doesn't show any error but doesn't work on mobile.

**Comment by Temereru** [comment]
they changed the way the plugin works between versions, you now need to register callbacks
