### ISSUE TITLE
Remove example AwesomeProject from npm package

### ISSUE THREAD

**Issue by dansjensen** [OneSignal/react-native-onesignal#25]
Thank you for providing a really easy way to use OneSignal notifications with React Native.

Please would it be possible to exclude the example AwesomeProject from the npm package.

When I use cloud services for continuous integration, I have observed that pod file in the example messes up the build. Also, it would be better, if the npm package only includes whatever is required to integrate and run with own project.

**Comment by avishayil** [comment]
That's a good idea, I'll add it to the TODO list.
Thanks.
