### ISSUE TITLE
Clic Action on a received notification 

### ISSUE THREAD

**Issue by guilabonte** [OneSignal/react-native-onesignal#250]
Hi!

We want to run a windev mobile function from a handler declared as ObjectiveC in the xCode at the click of a notification received from OneSignal. Note that the NotificationOpenedIOS function call a Windev Mobile procedure. The problem is that when user a user click on a notification, the application crash at this point on that function IExternalCall* call = AllocExternalCall(0x18ee67c624224f33ll,1);

What i'm doing wrong? Thank you very much!

**in WDAppDelegate.mm**

#include "WDObjectiveC.h"
#import "WDAppDelegate.h"
#import <OneSignal/OneSignal.h>

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions 
{
	bBackground = NO;
	[self RunApplication :launchOptions];
    
    [OneSignal initWithLaunchOptions:launchOptions appId:@"xxxx" handleNotificationReceived:nil handleNotificationAction:^(OSNotificationOpenedResult *result) {
        
        // This block gets called when the user reacts to a notification received
        OSNotificationPayload* payload = result.notification.payload;
        if (payload.additionalData) {
            NotificationOpenedIOS(payload.additionalData[@"WX_PROP_CONTENU"]);
        }
        
    } settings:@{kOSSettingsKeyInFocusDisplayOption:@(OSNotificationDisplayTypeNotification),kOSSettingsKeyInAppAlerts:@false,kOSSettingsKeyAutoPrompt:@false}];

return YES;
}

**in WDObjectiveC.mm**

class INativeCall
{
public :
	virtual void** Params()      = 0;
	virtual void   Return(void*) = 0;
};
class IExternalCall
{
public :
	virtual void	Push	(int,void*,uint32_t) = 0;
	virtual void*	Call	() = 0;
	virtual void	Release	() = 0;
};
IExternalCall* AllocExternalCall(uint64_t,int);
int NotificationOpenedIOS(NSString* p0)
{
    _//The application crashed here_
    _IExternalCall* call = AllocExternalCall(0x18ee67c624224f33ll,1);_
    call->Push(0,&p0,16);
    int r = *(int*)call->Call();
    call->Release();
    return r;
}

**In WDObjectiveC.h**
#ifndef WDObjectiveC_h
#define WDObjectiveC_h

#include <stdint.h>
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <OneSignal/OneSignal.h>

int NotificationOpenedIOS(NSString*);

#endif /* WDObjectiveC_h */

**Comment by avishayil** [comment]
Hi @guilabonte , Could you share a repo with your code?

**Comment by guilabonte** [comment]
I'm sorry, I can't, making my source code publicly available goes against my company's Privacy Policy. There is some code source I can post here to help my cause.

**Comment by avishayil** [comment]
If you could share it with me privately with my email on my profile, i'd might be able to help. Otherwise, it would be very hard to do so without reproducing your issue.
