### ISSUE TITLE
AndroidManifest.xml requires a placeholder substitution but no value for <onesignal_google_project_number> is provided.

### ISSUE THREAD

**Issue by justfede** [OneSignal/react-native-onesignal#251]
Hi guys! I'm having some issues implementing OneSignal SDK for my React Native application.

The error I got:

**AndroidManifest.xml requires a placeholder substitution but no value for <onesignal_google_project_number> is provided.**

But in my app/build.gradle:

`android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.pamela"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        manifestPlaceholders = [onesignal_app_id: "xxxx",
                                onesignal_google_project_number: "xxxx"]
    }
    signingConfigs {
   blablabla
` 

What i'm doing wrong?

**Comment by lu79931748** [comment]
how did you deal with this issue？

**Comment by nimamoradi** [comment]
@justfede how did you fix this
 adding 
```
<meta-data
            tools:replace="android:value"
            android:name="onesignal_google_project_number"
            android:value="REMOTE" />
```
won't help

**Comment by juliancorrea** [comment]
+1

**Comment by nimamoradi** [comment]
when delete build of onesignal in node_modules/react-native-onesignal/android/build folder , error will go

**Comment by pistonsky** [comment]
Just try `yarn`, worked for me

**Comment by kapilSoni101** [comment]
@nimamoradi:  Sir i am also getting above error but in the ionic3 app in my case i am not using any onesignal plugin so tell me what i do i have tried each and everything but nothing worked for me.tell me 1 thing sir its related to the goolge-map plugin issue or any another plugin?

**Comment by ldco2016** [comment]
delete the build in node modules? wow, that is not a good working solution. I am getting this issue and its already 2019.

**Comment by export-mike** [comment]
and in 2020!

**Comment by kolesnikov-pasha** [comment]
2021)

**Comment by waqarsaeed45** [comment]
2022

**Comment by shreedhar1** [comment]
2023

**Comment by nan-li** [comment]
Hi all, we don't necessarily keep an eye on closed issues since this issue was closed by the original poster within an hour of opening.

Please give updated details about this issue for you? 
- The exact error message
- The version of react-native-onesignal you are using
- Any other relevant information

**Comment by jkasten2** [comment]
`onesignal_google_project_number` was removed in [react-native-onesignal 4.0.0](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.0.0) so this is no longer an issue. Please follow the migration guide in the release notes lto get updated to this version.

If you run into any issues upgrading to the 4.0.0 SDK please open a new isssue.
