### ISSUE TITLE
No push token

### ISSUE THREAD

**Issue by reynaldi-lorenzo** [OneSignal/react-native-onesignal#255]
I have following the documentation and trying to implement to my project, but keep getting "no push token" in my onesignal user dashboard. So i decided to clone the example by creating new project, but no luck, always "no push token". I see in event listener log, device.pushToken always null. Did anyone also have similar issue with me? Thank

**Comment by avishayil** [comment]
Are you using real device? Simulators won't get push token.

**Comment by reynaldi-lorenzo** [comment]
This is wat i get in my verbose log : https://github.com/OneSignal/OneSignal-Android-SDK/issues/229 . I really confussed about this issue, i think this is the main issue why i get "no push token", so i open a issue here and in official android SDK

**Comment by yasheshkt** [comment]
Hi @avishayil . So is it safe to assume that the pushToken would always be returned in a real device? I also don't get a pushToken in simulator which according to me is justified. I am just worried how sure we can be, about getting a pushToken in real device!
