### ISSUE TITLE
iOS didReceiveRemoteNotification

### ISSUE THREAD

**Issue by apaul314** [OneSignal/react-native-onesignal#258]
Hi there!

Open event is not fired. After debugging a little while i figured out that
```c
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification
```
- not fired, while getting remote notification but

```c
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
``` 
- fired, but i cannot call `[RCTOneSignal didReceiveRemoteNotification:notification]` in this method to pass notification object further to js thread. 

iOS 10. React Native 0.44.

**Comment by zakster12** [comment]
@hose314 any progress on this?

**Comment by apaul314** [comment]
@zakster12 yeap but with hacks and patchs

In order to handle push notifications i'm using [this one](https://github.com/zo0r/react-native-push-notification) but it causes an issue with android and i've made a [patch on it](https://github.com/hose314/react-native-push-notification/commit/3fe51425cbb2f1e0bf131f56978ffb85f3ca0b3d)

yeap, i know, not a best practice so waiting for some suggestion

**Comment by avishayil** [comment]
This is not relevant with the latest SDK.
