### ISSUE TITLE
[iOS] Crash on iOS 9.3.2 because of missing didReceiveRemoteNotification method

### ISSUE THREAD

**Issue by negativetwelve** [OneSignal/react-native-onesignal#259]
In the [installation instructions](https://github.com/geektimecoil/react-native-onesignal#adding-the-code-1), it says to add:

```
// Required for the notification event.
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification {
    [RCTOneSignal didReceiveRemoteNotification:notification];
}
```

to the AppDelegate. This line is causing a crash anytime we receive a push notification, but only on devices that aren't iOS 10. This is using the latest (3.0.4) react-native-onesignal library.

Removing this method still allows the device (and OneSignal) to receive push notifications, but the crash now does not occur.

It looks like this method was removed in this commit: https://github.com/geektimecoil/react-native-onesignal/commit/4b2c55da780cff9bc82c227c052b416681dfdb27#diff-53b840050097cad618dd73cd2ebd59f2L81 and the previous comment makes it seem like it's no longer required.

Unfortunately, it's still in the header file (https://github.com/geektimecoil/react-native-onesignal/blob/master/ios/RCTOneSignal/RCTOneSignal.h#L17) so our app compiled and then caused a runtime error when it could not find the selector :(

Couple of questions:

1. Is it okay to remove this method? Are we missing functionality by removing it?
2. If it is okay to remove, should the method definition in the header be removed and the readme updated? If so, I would love to submit a PR for that.

**Comment by zakster12** [comment]
I have the exact same problem. 
![screen shot 2017-05-23 at 12 39 16 pm](https://cloud.githubusercontent.com/assets/25477229/26348265/eb5b8e16-3fb4-11e7-80e4-72f091f43409.png)

![screen shot 2017-05-23 at 12 40 34 pm](https://cloud.githubusercontent.com/assets/25477229/26348327/103c5b70-3fb5-11e7-9bfa-d03ecd554482.png)

**Comment by zakster12** [comment]
@negativetwelve I removed the 
```
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification {
    [RCTOneSignal didReceiveRemoteNotification:notification];
}
```
and everything works just fine. It wasn't necessary to do anything else but I am also interested in this question:

> Are we missing functionality by removing it?

**Comment by negativetwelve** [comment]
@zakster12 sorry for the late reply. I haven't worked on purely native in a while so I was unsure if that hook was necessary for anything. I think I remember seeing that the native OneSignal SDK is now hooking into this method on its own which means that the need to add it manual is no longer required (hence why they removed it)

**Comment by negativetwelve** [comment]
it's been working fine for us on iOS 9 with that method removed and we're indeed still receiving push notifications with the proper OneSignal JS hooks!

**Comment by zakster12** [comment]
@negativetwelve did you receive notifications when the app is killed/closed? Because I do not receive them: I have content available set to true and
```
onReceived = (receivedNotif) => {
}
```
but I receive them only the app is not closed. Can you help here?

**Comment by negativetwelve** [comment]
hi @zakster12, we currently do not take advantage of the `content-available` for notifications but our devices are all receiving push notifications when the app has been force closed (not in memory)

**Comment by jemmyphan** [comment]
@negativetwelve does it work when the app is active, mine didn't work when it is active ( it works while the app is in background)

**Comment by negativetwelve** [comment]
@jemmyphan sorry, this all happened a while ago and we've since updated versions of the OneSignal SDK

**Comment by jemmyphan** [comment]
@negativetwelve nvm, thanks anyway.

**Comment by ghost** [comment]
Thanks very much @negativetwelve 

That solved my problem - I followed the guide over on Medium https://medium.com/differential/react-native-push-notifications-with-onesignal-9db6a7d75e1e which was incredibly helpful, it saved me a tonne of time - I'll add a comment on there to report of this, looking at the guide it seems that Pod isn't required either now.

Thanks for your help!
