### ISSUE TITLE
post notification detail

### ISSUE THREAD

**Issue by neo125874** [OneSignal/react-native-onesignal#261]
hello, i know there's example,

But i want to ask about could i just just pass 'data' as {} ?
And is the playerId string type?

could i just execute like this?

``let contents = {
                'zh-Hant': message.text
            }
 OneSignal.postNotification(contents, {}, playerId);``

any default template could ref?   thanks in advance!

**Comment by neo125874** [comment]
@avishayil excuse me, is the p2p require the key setting or something? use the rest? or just call the function `OneSignal.postNotification` in the app?

**Comment by neo125874** [comment]
@avishayil ok, i found that if i set the language code like 'zh-Hant', not working...
but if set 'en' then it works both english and chinese, thanks

**Comment by leoskyrocker** [comment]
'zh-Hant' is working for me when I also have a 'en' message (I haven't tried whether it works without 'en')

Try the following:
```
let contents = { 'en': 'English Message', 'zh-Hant': message.text } OneSignal.postNotification(contents, {}, playerId);
```
