### ISSUE TITLE
Is it possible to add action buttons to notifications?

### ISSUE THREAD

**Issue by mostafiz93** [OneSignal/react-native-onesignal#262]
Is it possible to add  action buttons (say, Accept and Deny)  to the notification that will perform specific operations when pressed.  I'm talking about this [Action Buttons](https://documentation.onesignal.com/v3.0/docs/action-buttons). Are those possible in React Native?

I'm attaching some sample what I'm actually looking for. 

![](http://www.androidpolice.com/wp-content/uploads/2014/12/nexus2cee_notification1.png)

![](https://i.stack.imgur.com/9B1gi.png)

![](https://developer.android.com/images/ui/notifications/notification_drawer.png)

**Comment by bbrcan** [comment]
Yep, definitely need this functionality! Any advice would be greatly appreciated

**Comment by jkasten2** [comment]
@mostafiz93 @bbrcan Yes, these are supported by this SDK. For Android you must swipe down with 2 fingers to see the buttons. For iOS 10 you must 3d touch on the notification to see them.

Then [normal notification opened event](https://github.com/geektimecoil/react-native-onesignal#handling-notifications) will fired when a button is pressed. The id of the button will be sent to the event as well.

**Comment by bbrcan** [comment]
What about when posting a notification though?

I noticed `postNotification()` only supports `contents`, `data`, and `player_ids`, whereas there's a lot more options supported by the OneSignal API, `buttons` being one of them.

I know this isn't an official SDK and you guys are kind enough to maintain & share this so a big thank you for that! :)

**Comment by jkasten2** [comment]
@bbrcan Correct, the `postNotification()` function included with this SDK is limited to those 3 parameters so adding action buttons isn't possible with it. However you can use the [OneSignal Create notification](https://documentation.onesignal.com/reference#create-notification) REST API endpoint directly to send the notification from either your app's code or through your own server. However if you do so through your app make sure to omit the `Authorization` header as this isn't secure in your app. `include_player_ids` does not require this key.

**Comment by leoskyrocker** [comment]
@jkasten2 are you aware of anyone working on adding options to this? It seems like a missing piece to reach full-parity.

**Comment by leoskyrocker** [comment]
seems like an overlook. someone added this feature here: https://github.com/geektimecoil/react-native-onesignal/pull/266.
Currently I cannot get it working yet though but it looks like what I was expecting.

**Comment by leoskyrocker** [comment]
Confirmed that this is working for me! (My use case was to set small_icon & large_icon)
The way I passed the params is as follow:
```OneSignal.postNotification(contents, {}, onesignalPlayerId, {small_icon: 'ic_stat_name', large_icon: 'ic_launcher'})```

I'll try to see if I have time to update the docs in the next few days. yay!

**Comment by jumaediahsan** [comment]
so how to make button on pushnotification ,, any tutorials ?

**Comment by leoskyrocker** [comment]
By no means a complete example nor tested.. but something along the line:

Define Handler on action taken:
```
onOpened (openResult) {
  if (openResult.action.actionID === 'userSaidYes') {
    // do your logic
  }
}
```

Setup to listen to open event (which is also triggered when action taken) wherever you start your app:
```
OneSignal.addEventListener('opened', this.onOpened)
```

Then if you're sending a P2P notification with postNotification, you would do:
```
OneSignal.postNotification(contents, {}, onesignalPlayerId, {buttons: [{"id": "userSaidYes", "text": "Yes", "icon": "ic_xxxx_android_only"}, {"id": "userSaidNo", "text": "No", "icon": "ic_xxxx_android_only"}]})
```

**Comment by neo125874** [comment]
@leoskyrocker hello, did the action button support icon next to the button in ios/android?

**Comment by wahyu-handayani** [comment]
> @mostafiz93 @bbrcan Yes, these are supported by this SDK. For Android you must swipe down with 2 fingers to see the buttons. For iOS 10 you must 3d touch on the notification to see them.
> 
> Then [normal notification opened event](https://github.com/geektimecoil/react-native-onesignal#handling-notifications) will fired when a button is pressed. The id of the button will be sent to the event as well.

Hi I am currently using onesignal and flutter to build notification, as for android the action button shows up like what you said (by swiping down the notification). but in ios simulator, I cant do that, even with swipe left or right or double click. can you give a detail info about what 3d touch mean, I think I need to try it
