### ISSUE TITLE
Unrecognized selector with Swift AppDelegate 

### ISSUE THREAD

**Issue by 0x6e6562** [OneSignal/react-native-onesignal#265]
I'm getting an `unrecognized selector` error when integrating OneSignal into a React project where the AppDelegate is implemented in Swift.

The integration appears to work fine (i.e. APNs arrive triggered by the OneSignal API).

The notification payload arrives correctly into the Swift `didReceiveRemoteNotification` callback:

```swift
import UIKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
  
  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
    
    // Leave non-OneSignal init code out for brevity

    OneSignal.initWithLaunchOptions(launchOptions,
                                    appId: "xxxxx-xxx-xx-xxx-xxxxx")

    return true
  }
  
  func application(_ application: UIApplication,
                   didReceiveRemoteNotification userInfo: [AnyHashable : Any],
                   fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
    RCTOneSignal.didReceiveRemoteNotification(userInfo)
    completionHandler(.newData)
  }
  
}
```

However, when 

`RCTOneSignal.didReceiveRemoteNotification(userInfo)`

is invoked, the following error occurs:

```
2017-05-30 18:08:08.276997+0100 EventSpike[1273:709714] +[RCTOneSignal didReceiveRemoteNotification:]: unrecognized selector sent to class 0x10033ab18
2017-05-30 18:08:08.277591+0100 EventSpike[1273:709714] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[RCTOneSignal didReceiveRemoteNotification:]: unrecognized selector sent to class 0x10033ab18'
```

On face value it seems like the Swift variant of the Objective-C callback is bogus:

```objective-c
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification {
    [RCTOneSignal didReceiveRemoteNotification:notification];
}
```

So I'm wondering if the Swift has been mis-ported or whether there is something that hasn't been linked correctly.

Or is the case that you can't do this in Swift?

Moving forwards I could send events from Swift directly into JavaScript (i.e. just use the Swift OneSignal library), but it seems a shame seeing that this is whole point of the React library.

Am I missing the point somewhere?

**Comment by hhravn** [comment]
@0x6e6562 Getting the exact same error in an AppDelegate implemented in Objective-C

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[RCTOneSignal didReceiveRemoteNotification:]: unrecognized selector sent to class 0x3d86e8'`

Edit: Fixed by; https://github.com/maxx555/react-native-onesignal/commit/9f61f835c01ba927eb167ee2ae2a779b8c54ba24

**Comment by 0x6e6562** [comment]
Many thanks for the heads up @hhravn :-) 

The patch by @maxx555 fixes the symptom of the unrecognized selector, but the function is a NOOP, so the event effectively gets black holed. Somehow the event needs to get send over the RCTBridge into JavaScript - I get the feeling I've misunderstood the API.

**Comment by 0x6e6562** [comment]
To workaround this issue, I just wired the JS bridge into `didReceiveRemoteNotification` callback:

```objective-c
+ (void)didReceiveRemoteNotification:(NSDictionary *)dictionary {
   [curRCTBridge.eventDispatcher sendAppEventWithName:@"OneSignal-remoteNotificationReceived" body:dictionary];
}
```

Seems to work, but I don't follow why the Swift and Objective-C variants work differently.
