### ISSUE TITLE
App crash on Android at launch if no Internet connection is available

### ISSUE THREAD

**Issue by duyluandethuong** [OneSignal/react-native-onesignal#27]
Hi,

For all Android devices I have tested, my application crash right at the moment the app start if no Internet connection is available. If we turn on 3G/4G and / or Wi-Fi then everything is working. The situation does not happen on iOS device. 

Any suggestion? I have put NetInfo to prevent is `idsAvailable()` function from running but it still fails. Seem like we need to do something in the native code.

**Comment by jkasten2** [comment]
@duyluandethuong Can you get the full stack trace from the logcat of the device?

**Comment by duyluandethuong** [comment]
Here it is

04-29 12:02:21.099 21401-21491/com.trgapp W/EGL_emulation: eglSurfaceAttrib not implemented
04-29 12:02:21.099 21401-21491/com.trgapp W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa1da6d20, error=EGL_SUCCESS

```
                                                        --------- beginning of system
```

04-29 12:02:21.652 21401-28811/com.trgapp I/ReactNativeJS: 'networkStatus when load TRG Internal', ''
04-29 12:02:21.654 21401-28811/com.trgapp I/ReactNativeJS: Running application "TRGApp" with appParams: {"initialProps":{},"rootTag":1}. **DEV** === true, development-level warning are ON, performance optimizations are OFF
04-29 12:02:21.870 21401-28811/com.trgapp I/ReactNativeJS: 'networkStatus when running utils', 'NONE'
04-29 12:02:21.873 21401-28812/com.trgapp D/debug: User:2ff8d03f-233d-4ecf-a981-8929ba123131
04-29 12:02:21.873 21401-28812/com.trgapp D/debug: registrationId:APA91bFQd0y7UlQZxTMFpQYG1mmHndZiwIPdJyqTVTyMq7f0ZFsnhk-ON_pAT746MBYq_fr4gEKmDEbc-QmqSJ_acGIWbqBSqGyWcHDDoj9_xngtxMcNhgE
04-29 12:02:21.875 21401-28811/com.trgapp I/ReactNativeJS: 'id Available', { pushToken: 'APA91bFQd0y7UlQZxTMFpQYG1mmHndZiwIPdJyqTVTyMq7f0ZFsnhk-ON_pAT746MBYq_fr4gEKmDEbc-QmqSJ_acGIWbqBSqGyWcHDDoj9_xngtxMcNhgE',
                                                             userId: '2ff8d03f-233d-4ecf-a981-8929ba123131' }
04-29 12:02:21.885 21401-28811/com.trgapp E/ReactNativeJS: Network request failed
04-29 12:02:21.923 21401-21491/com.trgapp W/EGL_emulation: eglSurfaceAttrib not implemented
04-29 12:02:21.923 21401-21491/com.trgapp W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa1ec5900, error=EGL_SUCCESS

**Comment by duyluandethuong** [comment]
Hi, 

The problem seems to be fixed by modifying the index.js file in `node_modules/react-native-onesignal`. Change the idsAvailable methods to the following. Remeber to add **NetInfo** to your react dependencies:

```
Notifications.idsAvailable = function(idsAvailable) {
    NetInfo.isConnected.fetch().then(isConnected => {
        if (isConnected == true) {
            RNOneSignal.idsAvailable(idsAvailable);
        }
        else {
            return;
        }
    });
}
```

**Comment by avishayil** [comment]
Hi, Thanks for the report and the solution.
I'll add this to the next release.
