### ISSUE TITLE
cant see documentation for onIdsAvailable

### ISSUE THREAD

**Issue by PrimeLens** [OneSignal/react-native-onesignal#271]
Where do I find documentation on `onIdsAvailable`?
(I've inherited an older codebase)

**Comment by BuffMcBigHuge** [comment]
The documentation shows onIdsAvailible as an event, but I'm not seeing it fire. 

```
OneSignal.addEventListener('ids', function(ids) {
    console.log(ids);
});
```

Can we retrieve the user's player id by a simple function call like `OneSignal.getTags()`?

**Comment by leoleung0102** [comment]
similar question here. 
Is it possible to obtain the player id when the app is starting cuz I want to obtain the player id and pass it to server using graphql mutation

**Comment by PrimeLens** [comment]
The preceding two posts seem to refer to the newer code patterns.  In the original post I was referring to the older way which was

    OneSignal.configure({
      onIdsAvailable: (device) => {
        console.log(device);
      },
      onNotificationOpened: (message, data, isActive) => {
        console.log(message, data, isActive);
      }
    });

I'm moving my code base to the newer way so needing the docs is no longer relevant to me but I will leave this issue here in case someone else is also looking.

**Comment by maxcodes** [comment]
@PrimeLens `OneSignal.configure` doesn't work on newer versions (You should be using 
`OneSignal.addEventListener` as mentioned in the Readme). What version are you on?

**Comment by PrimeLens** [comment]
@maxcodes   as mentioned in original post, this was for an inherited older code base. It was 0.39.  At the time there was no option to upgrade but we ran into roadblock after roadblock and made an executive decision to rebuild. 
I still feel that docs for the older way should be available so my original request is still valid even though it will no longer be relevant to my work right now.

**Comment by maxcodes** [comment]
@PrimeLens You can check the docs for any version by switching to that tag on Github and reading the Readme 👍 

![screen shot 2017-07-06 at 12 01 42 pm](https://user-images.githubusercontent.com/6092334/27923153-0a18d2a4-6243-11e7-809d-2d7788f7678e.png)

**Comment by PrimeLens** [comment]
Thanks, very useful!
