### ISSUE TITLE
errors when adding docs readme code to AppDelegate.h

### ISSUE THREAD

**Issue by PrimeLens** [OneSignal/react-native-onesignal#272]
I'm pasting in the following code from the docs

    #import <RCTOneSignal.h>

    @property (strong, nonatomic) RCTOneSignal* oneSignal;

When I paste it at the start I get this error

<img width="702" alt="appdelegate h error 1" src="https://user-images.githubusercontent.com/636249/27691640-a15478bc-5cb2-11e7-9945-19d706322b23.png">

When I paste it just before the end I get this error

<img width="704" alt="appdelegate h error 2" src="https://user-images.githubusercontent.com/636249/27691651-a9f635be-5cb2-11e7-9f6f-311cd2e2a88e.png">

**Comment by jkasten2** [comment]
@PrimeLens Imports need to be before the interface definition and property definitions need to be inside the interface definition. See this example below for the order.
https://github.com/geektimecoil/react-native-onesignal/blob/master/examples/RNOneSignal/ios/RNOneSignal/AppDelegate.h

**Comment by PrimeLens** [comment]
Thanks @jkasten2  fantastic help
