### ISSUE TITLE
Message Notifications must have English language content

### ISSUE THREAD

**Issue by leoleung0102** [OneSignal/react-native-onesignal#273]
During the testing of sending push notification to other user by using Postman, I try to use "zh-Haut" to add Chinese content. However, the bad request has shown when I submit the request. 

Is it possible to use Chinese or other language to add to the content or heading, or it currently only supports English?

Thanks
![issue](https://user-images.githubusercontent.com/15317452/27695630-0f0f43ae-5d22-11e7-9c4d-b8cf95c026ed.png)

**Comment by jkasten2** [comment]
@leoleung0102 OneSignal uses English as the default language so the field must be filled. However if you only want to send your message in one language you can place it under `"en"` even though it is Chinese for example.

**Comment by leoleung0102** [comment]
@jkasten2 it's work. Thank for the help.
