### ISSUE TITLE
Issues, availability and maintainance

### ISSUE THREAD

**Issue by avishayil** [OneSignal/react-native-onesignal#276]
Hi all,

I feel like you guys should get some answers about why this library hadn't been updated for a while, so I'd like to give a quick heads up about what happened, since the library grew up impressively to 11k downloads / month since we started this project.

My wife got pregnant and gave and early birth (beginning of the 7th month).
We've been now in the neonatology for almost 3 months and just got home with the new baby.
Didn't have much time to do anything and just got back full time to work.

I hope things will be better from now on, and I'll try to go over the issues in the nexts days. Anyway folks that would like to help maintain this library alongside @jkasten2  will be welcome.

Thanks!
Avishay

**Comment by maxcodes** [comment]
Thanks for the update, and congratulations!
