### ISSUE TITLE
App crash when receiving notification 

### ISSUE THREAD

**Issue by BlackStef** [OneSignal/react-native-onesignal#278]
I have an Issue with my OneSignal installation, my App Crash when I send the test notification from OneSignal dashboard. 

But after when I relunch my App, I can see the notifications appear at the top bar ! 
Here my OneSignal CrashLog ; 

[onesignal_crash_logcat.txt](https://github.com/geektimecoil/react-native-onesignal/files/1125155/onesignal_crash_logcat.txt)

I also have a react-native-background-Job, maybe there Are some conflicts ?

**Comment by mehrdadmms** [comment]
@BlackStef i have the same issue 
what should i do ? 
i'm on react native 55.3 version and onesignal 3.2.4
