### ISSUE TITLE
addEventListener('ids', this.onIds) does not work (or I misunderstand something )

### ISSUE THREAD

**Issue by Kacoze** [OneSignal/react-native-onesignal#280]
Ok, so I configured onesignal with rn as is in readme, and it works. Notifications are coming. However I also need to get device (player) id, so it can be handled by my api. As I understood, I should use:
```
componentWillMount() {
    OneSignal.addEventListener('ids', this.onIds);
}

onIds(device) {
    console.log('Device info: ', device);
}
```
However, it never triggers. Am I doing sth wrong? How can I get device ids of current user?

**Comment by ghost** [comment]
@Kacoze Feedbacks are appreciated if you managed to resolve your issue.

**Comment by atasmohammadi** [comment]
any solutions for this issue? facing the same.

**Comment by arma7x** [comment]
i'm also facing this issues, device can received push notification but can't get ids.
Edited: fixed by add OneSignal.configure() after addEventListener

**Comment by deepakverma4** [comment]
+1

**Comment by tranvannhat** [comment]
Thanks @arma7x <3

**Comment by yaseralimardany** [comment]
come on. Its work. why documentation of one signal was weak!!

**Comment by duytq94** [comment]
In previous version, we don't need add that line, but don't know why they don't update the docs!!!

**Comment by kovalyovkirill** [comment]
Thanks for solution. Just found in docs:
`Please note that calling OneSignal.configure() causes the ids event to fire.`

**Comment by mohanasundaramn** [comment]
@arma7x  Fixed my issue, Thank you.

**Comment by VictorPulzz** [comment]
Not fix for me

**Comment by Luckygirlllll** [comment]
I'm getting an error  RNOneSignal.configure is not a function after updating OneSignal to the latest version, was it deprecated/ removed in the latest version? 
  https://github.com/geektimecoil/react-native-onesignal/issues/844
