### ISSUE TITLE
Navigation doesn't work in onOpened callback when app in background

### ISSUE THREAD

**Issue by bbrcan** [OneSignal/react-native-onesignal#281]
Hi all!

I'm creating a simple video chat app. When the "accept" button on the notification is clicked, the video screen should open up.

I'm using the standard `react-navigation` package.

Here's an abridged copy of my code:

```javascript
export default class HomeScreen extends Component { 

  constructor(props) {                                   
    super(props); 
    this.onOneSignalIds = this.onOneSignalIds.bind(this);
    this.onOpened = this.onOpened.bind(this);
  }

  componentDidMount() {
    OneSignal.configure({});
    OneSignal.removeEventListener('ids', this.onOneSignalIds);
    OneSignal.removeEventListener('opened', this.onOpened);
    OneSignal.addEventListener('ids', this.onOneSignalIds); 
    OneSignal.addEventListener('opened', this.onOpened);
  }

  ...

  onOpened(openResult) {

    if (openResult.action.actionID == "accept") {
      let roomId = openResult.notification.payload.additionalData.roomId;

      const { navigate } = this.props.navigation;
      navigate('VideoScreen', { 'roomId' : roomId });
    }
  }

  ...

}
```

When the app is in the *foreground*, this works great. However, when the app is in the *background*, `HomeScreen` opens up, not `VideoScreen`.

Any ideas how I can fix this?

Thanks everyone!!! :)

PS - Why do I have `OneSignal.removeEventListener()` in `componentDidMount()` instead of `componentWillUnmount()`? I found that for whatever reason, the event listeners weren't always getting removed and the handlers were getting called multiple times.

**Comment by bbrcan** [comment]
I think this might be related to this issue here:

https://github.com/react-community/react-navigation/issues/476

HomeScreen is actually getting loaded multiple times! Check this out (I put some logs in):

```
HomeScreen::constructor()         
HomeScreen::componentDidMount()   
HomeScreen::onOpened()            
HomeScreen::constructor()         
HomeScreen::componentDidMount()   
HomeScreen::componentWillUnmount()
HomeScreen::constructor()         
HomeScreen::componentDidMount()   
```

What I noticed is that `VideoScreen` *is* getting loaded (`constructor()` + `componentDidMount()` are called), however it's not *visible*. It seems like `HomeScreen` is getting loaded right back on top of it!

As a temporary workaround, I've had to declare a variable (`roomToLoad`) outside the scope of `HomeScreen`. I then check this in `componentDidMount()`, and navigate from there, **which works**.

```javascript
// roomToLoad is a variable at file scope
if (roomToLoad) {                                          
  const { navigate } = this.props.navigation;                          
  navigate('VideoScreen', { 'roomId' : roomToLoad });
  roomToLoad = null;                                       
}                                                                      
```

**Comment by phamhuyhoang95** [comment]
Someone tell me what the difference if I register event on parent App component or child component. Because I using react-navigation thanks.
