### ISSUE TITLE
Implement checkPermissions for Android

### ISSUE THREAD

**Issue by ahndrew** [OneSignal/react-native-onesignal#288]

**Comment by apaul314** [comment]
You can check push notification permissions with something like 
```java
NotificationManagerCompat notificationManagerCompat = NotificationManagerCompat.from(this.reactContext);
boolean enabled = notificationManagerCompat.areNotificationsEnabled‌();
```
API Level should be greater then 24. Read the android docs for more details

**Comment by jkasten2** [comment]
@ahndrew @hose314 This already part of the SDK. You can call [`OneSignal.getPermissionSubscriptionState`](https://github.com/geektimecoil/react-native-onesignal#check-push-notification-and-user-subscription-status) to get the status. This is noted under the [Check Push Notification and User Subscription Status](https://github.com/geektimecoil/react-native-onesignal#check-push-notification-and-user-subscription-status) section of the readme.
