### ISSUE TITLE
Nothing happens when calling OneSignal.idsAvailable()

### ISSUE THREAD

**Issue by whollacsek** [OneSignal/react-native-onesignal#29]
After `OneSignal.configure(...)` I tried to call `OneSignal.idsAvailable(callback)` but the callback is never triggered. Everything is setup correctly, on the Onesignal dashboard I can see the new device.

**Comment by DanDance** [comment]
Same issue. Any updates?

**Comment by avishayil** [comment]
Hi, I just got back from a vacation, i'll try to have a look on all the
issues this week.
Thanks!

**Comment by avishayil** [comment]
Hi, everything works in my testing.
Please try again and report?

**Comment by whollacsek** [comment]
Hi @avishayil, I'll try it next week, will let you know asap

**Comment by avishayil** [comment]
I'm closing the issue for now. If the problem persist, please re-open it.

**Comment by whollacsek** [comment]
sorry for the late response, it seems to work now

**Comment by avishayil** [comment]
Great! Please let me know if something else breaks.
