### ISSUE TITLE
Documentation for custom notification sounds

### ISSUE THREAD

**Issue by lslima91** [OneSignal/react-native-onesignal#291]
The current docs are not explicit in which folder to put the custom sound file.

https://documentation.onesignal.com/v3.0/docs/customize-notification-sounds

**Comment by edencakir** [comment]
+1, can you provide this?

**Comment by avishayil** [comment]
https://documentation.onesignal.com/docs/customize-notification-sounds

**Comment by mik-rom** [comment]
@avishayil 
Can't find any information about react native on that page.
Tried adding to _android/app/src/main/res/raw_ but it didn't work

**Comment by mik-rom** [comment]
Still have not been able to make custom sounds work on android. What is the proper way to do it? Anyone knows?
