### ISSUE TITLE
getPermissionSubscriptionState is not a function

### ISSUE THREAD

**Issue by almirfilho** [OneSignal/react-native-onesignal#296]
I can use everything else but the method `getPermissionSubscriptionState()`.

```javascript
import OneSignal from 'react-native-onesignal';
console.log(OneSignal.getPermissionSubscriptionState); // => undefined
```
I've also noticed the PR #289 that introduce this method is merged in master (hence its mention in the docs) but is not bundled within the latest version (3.0.4).

So, I guess it wasn't released yet, right?
Could you guys bump a new version with this feature, please?
Thanks a lot!

**Comment by pqthang97** [comment]
+1 this
i have same issue

**Comment by JoshStaff** [comment]
+1

Same situation here.

**Comment by jkasten2** [comment]
3.0.5 was released a few days ago. Can you update and give it a try?

Thanks.

**Comment by almirfilho** [comment]
Thanks!

**Comment by victorbadila** [comment]
I'm using version 3.1.1 and I have this issue. 
`console.log(OneSignal.getPermissionSubscriptionState);` yields `undefined`.

**Comment by JoshStaff** [comment]
Victor, if you need this I have a fork where I correctly expose the subscription state. You could try that?

**Comment by victorbadila** [comment]
Thanks, I will try it :)

However I think the issue should be reopened.

**Comment by adambeck7** [comment]
Experiencing the same issue on 3.6.5.
