### ISSUE TITLE
Swift - Code missing from didReceiveRemoteNotification

### ISSUE THREAD

**Issue by yaronlevi** [OneSignal/react-native-onesignal#298]
Hi, 
My project has an AppDelegate.swift instead of AppDelegate.m
I carefully followed the installation instruction. When finished I didn't see any mention of code need to be added to didReceiveRemoteNotification (in appDelegate).

But looking at your example app I can see that in fact there is a code there:
```
// Required for the notification event.
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification {
  [RCTOneSignal didReceiveRemoteNotification:notification];
}
  
```

Did I miss any step?
Should the link command have added some code (but malfunctioned because I am using swift)?

**Comment by jkasten2** [comment]
@yaronlevi This project is intended to work with Objective-C as there would be additional steps to bridge to Swift. Can you switch your project to Objective-C?

**Comment by yaronlevi** [comment]
Unfortunately, no as there is a considerable amount of code and functionality written in Swift. Is it possible you can provide me the missing steps, or better add them to the docs?

If it is a non-trivial amount of work, it could be a deal breaker for us, and I'll need to implement the Onesignal iOS SDK manually.

*No complaints from the Android side though, works great (-:
