### ISSUE TITLE
Can't test OneSignal push notification

### ISSUE THREAD

**Issue by qdd1** [OneSignal/react-native-onesignal#299]
Hope this is not a dump question I am asking.

I made an sample/default Android app and integrate OneSignal push notification in it.
I followed: https://documentation.onesignal.com/docs/react-native-sdk-setup

Everything is good and ready except in "MyApp" on OneSignal I cant see, nor select any `subscribe User` to push a testing push to the device.
I've install the sample App on my Android and a simulator using `react-native run-android` command.  The App shows on both devices but on simulator it also shows a warning `Error: [{"FrameToTop":1, "code": "E_MISSING_PERMISSION"}]` when I added this line `import OneSignal from 'react-native-onesignal';`

Here is sample App code:

` import React, { Component } from 'react';
import {
	StyleSheet,
	Text,
	View
} from 'react-native';
import OneSignal from 'react-native-onesignal';

class App extends Component {
	componentWillMount() {
		OneSignal.addEventListener('received', this.onReceived);
		OneSignal.addEventListener('opened', this.onOpened);
		OneSignal.addEventListener('registered', this.onRegistered);
		OneSignal.addEventListener('ids', this.onIds);
    }

    componentWillUnmount() {
        OneSignal.removeEventListener('received', this.onReceived);
        OneSignal.removeEventListener('opened', this.onOpened);
        OneSignal.removeEventListener('registered', this.onRegistered);
        OneSignal.removeEventListener('ids', this.onIds);
    }

    onReceived(notification) {
        console.log("Notification received: ", notification);
    }

    onOpened(openResult) {
		console.log('Message: ', openResult.notification.payload.body);
		console.log('Data: ', openResult.notification.payload.additionalData);
		console.log('isActive: ', openResult.notification.isAppInFocus);
		console.log('openResult: ', openResult);
    }

    onRegistered(notifData) {
        console.log("Device had been registered for push notifications!", notifData);
    }

    onIds(device) {
		console.log('Device info: ', device);
    }
	render() {
		return (
			<View style={styles.container}>
				<Text style={styles.welcome}>
					Welcome to React Native!
				</Text>
				<Text style={styles.instructions}>
					To get started, edit index.android.js
				</Text>
				<Text style={styles.instructions}>
					Double tap R on your keyboard to reload,{'\n'}
					Shake or press menu button for dev menu
				</Text>
			</View>
		);
	}
}

const styles = StyleSheet.create({
	container: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: '#F5FCFF',
	},
	welcome: {
		fontSize: 20,
		textAlign: 'center',
		margin: 10,
	},
	instructions: {
		textAlign: 'center',
		color: '#333333',
		marginBottom: 5,
	},
});

export default App;`

Can anyone point out where I did wrong?

**Comment by almirfilho** [comment]
@qdd1 how did you fix this?

**Comment by qdd1** [comment]
I went through the setup document ( re-setup) once again and add this line on "ComponentWillMount()": OneSignal.setSubscription(true);

**Comment by burakadam** [comment]
I fix it with "react-native link".
