### ISSUE TITLE
Sample project or better documentation

### ISSUE THREAD

**Issue by kennym** [OneSignal/react-native-onesignal#3]
Could you please post a sample project displaying the usage of the `onNotificationOpened` callback? I am having a hard time making my React project setting it up for that callback. OneSignal is properly set-up only that last part is failing.

**Comment by kennym** [comment]
Can it be that this code in `AppDelegate.m` is the culprit:

```
  self.oneSignal = [[OneSignal alloc] initWithLaunchOptions:launchOptions
                                      appId:@"ID-REPLACED"
                                      handleNotification:nil];
```

Should I set `handleNotification:nil` to something else? In the README it's omitted, but XCode says it requires that parameter.

Any ideas?

**Comment by avishayil** [comment]
Hi, I'll set up a sample project as soon as I can, that's a good idea.

**Comment by avishayil** [comment]
As i'm setting the projects I see I forgot some things in the documentation.
I'll upload it soon and update the documentation as well :>

**Comment by avishayil** [comment]
Repo updated. Please try the examples.
According to your question - I can't see any need for this handleNotification, since it's already being used on the module itself, so you don't need to include it in your AppDelegate.

**Comment by kennym** [comment]
@avishayil thanks a lot! That's really helpful

XCode keeps asking me to provide a `handleNotification` parameter, even if I am passing it `nil`... any ideas of how to get rid of that message, as you seemingly don't get that one?

Let me know of this is out of the scope of this issue.

**Comment by avishayil** [comment]
What version of react native are you using?

**Comment by avishayil** [comment]
@kennym What version of react native are you using?
Did you try running the supplied example project?
