### ISSUE TITLE
QUESTION: Android setup build tools

### ISSUE THREAD

**Issue by ghost** [OneSignal/react-native-onesignal#300]
Our current app is using a newer gradle (3.3). Can we skip the steps for setting these in this section: https://github.com/geektimecoil/react-native-onesignal#adding-the-code

```
distributionUrl=https://services.gradle.org/distributions/gradle-2.14.1-all.zip
```

And

```
    classpath 'com.android.tools.build:gradle:2.2.2' // Upgrade gradle
```

And

```
    buildToolsVersion "23.0.2" // NOT REQUIRED BUT RECOMMENDED - This is good for in-process dex (faster)
```

**Comment by jkasten2** [comment]
@ccuilla Yes, the SDK will work with newer versions of gradle and it's build tools than the instructions list.

**Comment by ghost** [comment]
Awesome. Thanks.
