### ISSUE TITLE
Trigger/Schedule LocalNotifications?

### ISSUE THREAD

**Issue by aaronbuchanan** [OneSignal/react-native-onesignal#302]
We're using OneSignal for our app's remote notifications but we also need to trigger some local notifications incase the user's internet connection dies based on our requirements, I see `application:didReceiveLocalNotification` mentioned in this repo but nothing that covers how to trigger one. Are local notifs in scope for this SDK or should I be looking elsewhere for this? 

Thanks, appreciate the work to bring one signal to react-native!

**Comment by paulief** [comment]
+1
We're currently using https://github.com/zo0r/react-native-push-notification for our local notifications but it would be awesome to be able to do it within this library! The other library is a bit heavy for only local notifications.

**Comment by aaronbuchanan** [comment]
@paulief yep was figuring that's where I'd end up, are you using this library's `didReceiveLocalNotification` method at all or are they totally independent?

**Comment by paulief** [comment]
@aaronbuchanan I'm not using that, but I'd guess they'd work together? Sorry, can't say for sure

**Comment by jjdp** [comment]
you could technically send a notif to yourself using https://github.com/geektimecoil/react-native-onesignal#post-notification-peer-to-peer-notifications.

they dont support local notifs at the moment, and I'd rather avoid another notif lib

**Comment by awesomejerry** [comment]
AFAIK, localNotifications can be triggered when offline. Does p2p notification rely on the internet?

**Comment by jjdp** [comment]
yes it does
