### ISSUE TITLE
Undefined is not an object (evaluating 'RNOneSignal.configure')

### ISSUE THREAD

**Issue by dzpt** [OneSignal/react-native-onesignal#304]
I get this error, even after relink the lib as #208 

It points to the line 131, index.js

```
static configure() {
        RNOneSignal.configure();
    }
```

react-native-cli: 2.0.1
react-native: 0.44.0

**Comment by rafaelviny** [comment]
your solved?

**Comment by dzpt** [comment]
Yes, i found out that i duplicate installing OneSignal.
One by pod, one by npm. After removed one of them and i got it work.
Have you tried to relink the lib?

**Comment by rafaelviny** [comment]
Possibly yes, I will try again using only the pod in a new project

**Comment by masudhossain** [comment]
Which one did you remove and how?

**Comment by dzpt** [comment]
@masudhossain I removed the pod install and use npm + link library, its easier to manage dependencies.

**Comment by masudhossain** [comment]
@Tom29  Thank you, that fixed everything 👍
