### ISSUE TITLE
"oids" event is only giving userId and pushToken not player ID

### ISSUE THREAD

**Issue by atasmohammadi** [OneSignal/react-native-onesignal#307]
```
OneSignal.addEventListener('ids', this.onIds)
```
is returning only userId and pushToken. how to get player id?

**Comment by smartdevdom** [comment]
Hi, userId is player Id

**Comment by slorber** [comment]
this is confusing, they support confirmed me that playerId == userId and that they are going to use the same term everywhere un the future
