### ISSUE TITLE
force launch app when receiving notification

### ISSUE THREAD

**Issue by hungdev** [OneSignal/react-native-onesignal#312]
hi, i want to force open app when receiving a notification like messenger call of facebook or skype app.
Could you tell me how do i resolve it?

**Comment by ghost** [comment]
nobody decided?

**Comment by jkasten2** [comment]
@hungdev You will write some native code to do this on either iOS or Android.

### iOS
You will need to use VoIP notifications and Apple's PushKit library to do this. See [their guide](https://developer.apple.com/library/content/documentation/Performance/Conceptual/EnergyGuide-iOS/OptimizeVoIP.html) on setting this up and getting a VoIP type push token. The OneSignal SDK does not support PushKit so all the eventing in your app with need to be handed with your own code. The OneSignal backend does support sending to VoIP however you should create a 2nd OneSignal app to register these kinds of tokens. You will need to use the OneSignal [Add a device](https://documentation.onesignal.com/v3.0/reference#add-a-device) to register the device with OneSignal.

## Android
Follow OneSignal's [Background Data and Notification Overriding](https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding) to setup the required Java code to receive background data. However you will still need to write code to start your own custom Android Activity for the call.

**Comment by gorohovgame** [comment]
YEs thank, in ios all work, for me need only android. You can create this
module?
