### ISSUE TITLE
NetInfo's "change" event is deprecated

### ISSUE THREAD

**Issue by ghost** [OneSignal/react-native-onesignal#313]
After upgrading to latest React Native (0.48.0) I keep getting this warning:

`NetInfo's "change" event is deprecated. Listen to the "connectionChange" event instead.`

I guess this is due to: https://github.com/geektimecoil/react-native-onesignal/blob/88f00a6f30bbf2986a570f908cff877b8ef71883/index.js#L20

**Comment by kelvinblade** [comment]
+1

**Comment by raubas** [comment]
Me too, added a PR: #321

**Comment by ghost** [comment]
@raubas I already opened one here https://github.com/geektimecoil/react-native-onesignal/pull/317

**Comment by raubas** [comment]
Yeah I saw that just after adding mine…!

**Comment by ujwal-setlur** [comment]
Any ETA on merging this?

**Comment by askarhu** [comment]
Please let us know on this. I was getting the same and this is going to possibly delay the rollout until resolved.

**Comment by deavial** [comment]
Right! We are all in a race to get our iOS 11 updates out the door and stuff like this has us in a holding pattern.

**Comment by almostintuitive** [comment]
Same here!

**Comment by smartdevdom** [comment]
Hi, when go to push with it

**Comment by ghost** [comment]
@jkasten2 we're still in need of a npm publish here.
