### ISSUE TITLE
Android setup

### ISSUE THREAD

**Issue by kelvinblade** [OneSignal/react-native-onesignal#316]
I followed the instructions to set up onsignal for react native. It is working on iOS. However on Android, it does not seem to be running or returning the player id. I've been fiddling with it all day looking at examples and other tutorials.

When I run react-native link react-native-onesignal, it does not add `ReactNativeOneSignalPackage()`
. Do I need to add it manually? I tried adding it in manually but neither import `com.geektime.rnonesignalandroid.ReactNativeOneSignalPackage;` nor `com.geektime.reactnativeonesignal.ReactNativeOneSignalPackage` worked, boh gave me an error.

I also noticed that it didn't add the following to 
```
include ':react-native-onesignal'
project(':react-native-onesignal').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-onesignal/android')
```
Is this required?

Also for the 

```
manifestPlaceholders = [onesignal_app_id: "YOUR_ONESIGNAL_ID",
                                onesignal_google_project_number: "REMOTE"]
```

Do I leave "REMOTE" or do I change it to my google project number as I saw in some tutorials? Thanks

**Comment by el-lsan** [comment]
@kelvinblade Did you manage to solve this issue ?
I'm facing the same.

**Comment by varqasim** [comment]
+1
