### ISSUE TITLE
Duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by matheusrocha89** [OneSignal/react-native-onesignal#318]
Hi guys, I already read all other issues of this topic, tried their solutions but didn't work with me. I am not using `cocoapods` and I am using version 3.0.3 of `react-native-onesignal`.
Configured everything like it is on the docs of iOS but when I try `react-native run-ios` or try to build the project from XCode I always get the same error:

`102 duplicate symbols for architecture x86_64`

Part of the log message:

```
 /Users/matheusrocha/Developer/correio-news/ios/Correio/Frameworks/OneSignal.framework/OneSignal(UNUserNotificationCenter+OneSignal.o)
    /Users/matheusrocha/Developer/correio-news/ios/build/Build/Products/Debug-iphonesimulator/libRCTOneSignal.a(UNUserNotificationCenter+OneSignal.o)
duplicate symbol _OBJC_METACLASS_$_swizzleUNUserNotif in:
    /Users/matheusrocha/Developer/correio-news/ios/Correio/Frameworks/OneSignal.framework/OneSignal(UNUserNotificationCenter+OneSignal.o)
    /Users/matheusrocha/Developer/correio-news/ios/build/Build/Products/Debug-iphonesimulator/libRCTOneSignal.a(UNUserNotificationCenter+OneSignal.o)
ld: 102 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Tried other solution sometimes the duplicate symbols become lower (98, 96) but I can't build the project.

Can somebody help me with that?

**Comment by matheusrocha89** [comment]
Found the solution. The problem was the references on the frameworks of xcode project.

**Comment by esaminu** [comment]
Please elaborate..

**Comment by MoOx** [comment]
See https://stackoverflow.com/a/46678210/988941

**Comment by nemanjas1** [comment]
What helped me, in RN 0.58.6 and One Signal 3.2.14, is modifying Podfile by removing pod, and manually linking. This is my Podfile
```
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
end


target 'pdt' do
  # pod 'OneSignal', '>= 2.6.2', '< 3.0'
end
```
