### ISSUE TITLE
NotificationNotDisplayingExtender usage

### ISSUE THREAD

**Issue by Univac1107** [OneSignal/react-native-onesignal#319]
Hello, in the code the NotificationNotDisplayingExtender is implemented, but not declared on any manifest. Is it actually being used?

How can I use It?

Thanks!

**Comment by ntnamag** [comment]
Same problem? SyncService process use large memory

**Comment by Nightsd01** [comment]
@Univac1107 This is a good point, it looks like the `NotificationNotDisplayingExtender` is not being used in the SDK and will be removed in a future release. Thanks for pointing this out!
