### ISSUE TITLE
Google play service library Error 

### ISSUE THREAD

**Issue by WilliamAnputra** [OneSignal/react-native-onesignal#322]
<img width="1128" alt="screen shot 2017-09-09 at 1 51 41 am" src="https://user-images.githubusercontent.com/14292510/30226810-985a039e-9501-11e7-94bc-d76a2ccb4b0f.png">

I'm creating a new react native project and followed the step from [https://github.com/geektimecoil/react-native-onesignal](url). So far it works, i got the list of device on onesignal's dashboard but the problem is my device is not subscribed? and it's telling me google play service error? i could not receive any notifications

this is build.gradle
https://gist.github.com/WilliamAnputra/38c35dd08b201504bae5e42eae59b09a

any particular reason why ?

**Comment by yaseralimardany** [comment]
how solved this issue?

**Comment by yaseralimardany** [comment]
@WilliamAnputra
