### ISSUE TITLE
[UIApplication registerForRemoteNotifications] must be used from main thread only

### ISSUE THREAD

**Issue by robhogan** [OneSignal/react-native-onesignal#326]
This is an Xcode 9 warning because it has a new mechanism which makes these obvious but the problem applies to all versions in principle. 

~~I've never actually experienced a problem with it~~, but afaik it's a potential cause of crashes since `UIKit` access isn't thread safe. These types of calls should be dispatched to the UI queue.

Update: This does actually cause some buggy behaviour with the initial permissions request dialog, which should be a blocking operation on the UI thread. The behaviour now is that the permissions dialog will be dismissed by any subsequent UI dialog before the user has had a chance to answer, and vice-versa if permissions are requested while another modal is on screen.

**Comment by Nightsd01** [comment]
Hi @rh389 , I am unable to reproduce this issue but I've seen similar behavior in older versions of React. Are you still having this issue? I will close this issue due to inactivity however if you are still encountering this problem, please feel free to respond and I'll reopen the issue.

**Comment by robhogan** [comment]
I’ll double check when I get chance, but I don’t think this has been addressed yet. I’ll ask for a reopen later if so.

**Comment by noway** [comment]
happens for me

**Comment by noway** [comment]
Still happens to me with

"react-native-onesignal": "^3.5.0",
"react-native": "^0.61.4",

can we reopen the issue?
