### ISSUE TITLE
Cannot resole the EventEmitter Error

### ISSUE THREAD

**Issue by mukeshkamboj** [OneSignal/react-native-onesignal#328]
I am getting the below error. I have tried out the steps mentioned in the error console. But no luck.

		"react": "16.0.0-alpha.12",
		"react-native": "0.48.3",

![error](https://user-images.githubusercontent.com/7412848/30947717-e840f65c-a428-11e7-9d66-bc6f489518bd.png)

The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false

Body:
{"from":"/Users/abc/development/react_native/node_modules/react-native-root-siblings/lib/AppRegistryInjection.js","to":"react-native/Libraries/EventEmitter/EventEmitter","message":"Unable to resolve module `react-native/Libraries/EventEmitter/EventEmitter` from `/Users/abc/development/react_native/node_modules/react-native-root-siblings/lib/AppRegistryInjection.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.","name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]}
processBundleResult
    BundleDownloader.java:170
access$100
    BundleDownloader.java:39
onResponse
    BundleDownloader.java:139
execute
    RealCall.java:135
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1113
run
    ThreadPoolExecutor.java:588
run
    Thread.java:818

**Comment by gallavie** [comment]
I get also this error 
my version is react-native: 0.49.1

**Comment by mukeshkamboj** [comment]
@gallavie 

Below links can be helpful. Read them carefully. As this problem cause varies as per the situation. This is not happening because of the react-native-onesignal.

https://github.com/facebook/react-native/issues/14209
https://github.com/facebook/react-native/issues/11498
