### ISSUE TITLE
Cannot find protocol declaration for 'OSSubscriptionObserver'

### ISSUE THREAD

**Issue by therahuls1ngh** [OneSignal/react-native-onesignal#329]
Cannot find protocol declaration for 'OSSubscriptionObserver'

**Comment by AviramCohen** [comment]
+1

**Comment by therahuls1ngh** [comment]
i dont know how its working but its working now

**Comment by karamat** [comment]
Getting this error, any idea how it was solved?

**Comment by JakeRawr** [comment]
I'm just got this error when upgrading to 3.0.9

**Comment by gasipari** [comment]
I have the same error on 3.0.9. Any idea how to fix? Thanks
