### ISSUE TITLE
[iOS] sending a boolean false tag doesn't work

### ISSUE THREAD

**Issue by mtt87** [OneSignal/react-native-onesignal#331]
`react-native@0.46.4` `react-native-onesignal@3.0.5` testing on iOS11 simulator, it seems like if you send a false tag it doesn't appear in OneSignal dashboard as if it wasn't sent at all.
```js
OneSignal.sendTags({
    name: profile.name,
    isFalse: true,
});
```
This will be shown in the dashboard as `{ name: 'Mattia', isFalse: true }`
```js
OneSignal.sendTags({
    name: profile.name,
    isFalse: false,
});
```
This will be shown in the dashboard as `{ name: 'Mattia' }`.

On Android, the same code will produce correctly `{ name: 'Mattia', isFalse: false }`

**Comment by mtt87** [comment]
I'm not a swift/obj-c developer but having a look here:
https://github.com/geektimecoil/react-native-onesignal/blob/master/ios/RCTOneSignal/RCTOneSignal.m#L221-L223
```obj-c
RCT_EXPORT_METHOD(sendTag:(NSString *)key value:(NSString*)value) {
    [OneSignal sendTag:key value:value];
}
```
it seems like it's expecting a string.

**Comment by mtt87** [comment]
@avishayil are you closing this because it's fixed or another reason? Thank you

**Comment by avishayil** [comment]
@mtt87 you found the solution yourself. It does expecting a string, so sending `false` as a boolean will not be accepted.

**Comment by mtt87** [comment]
Yes but this behaviour is not correct because it should be either a `boolean` or a `string`.
On Android it works fine and it sends a boolean.

If you think it should only allow strings, then the Android implementation is wrong.

Do you see my point here?

**Comment by avishayil** [comment]
I see. Let's hear what @Nightsd01 has to say on this, leaving this open.

**Comment by mtt87** [comment]
Given that the Android implementation works fine and can handle `boolean` values, and also OneSignal itself can handle `boolean` values, I would say that it's the iOS implementation that is wrong.

Unfortunately I don't know obj-c to be able to help myself but looks like a simple check "if it's a string or boolean" could work.

Thank you 😄

**Comment by Nightsd01** [comment]
Hello @mtt87 , thank you for reporting this issue.

I just tested this out. It looks like the `sendTag:value:` method will indeed expect only string values. However, the `sendTags:` method expects a dictionary. As long as you send the booleans with the `sendTags:` method, it works just fine. 

For example, in react-native, sending the following values with the SDK works just fine. If you have problems with it, you might try making sure you are updated to the most recent version of the React-Native-OneSignal SDK

```javascript
OneSignal.sendTags({"test1" : "hello", "test2" : true});
```

**Comment by nebtrx** [comment]
Hey, 

Kudos to the author and collaborators of the library. You've done a great job guys. However, I did run into this issue when trying to update a device using the rest API.

In order to reproduce it, someone just needs to execute the following in his terminal:

```bash
curl --include \                                                                                                     
     --request PUT \
     --header "Content-Type: application/json" \
     --data-binary "{\"tags\":{\"boolean-test\":false}}" \
     https://onesignal.com/api/v1/players/<PlayerID>

```

You'll realize the `boolean-test` tag doesn't get added if it doesn't exist and,  otherwise, it gets deleted.

Thanks
