### ISSUE TITLE
postNotification crashing app

### ISSUE THREAD

**Issue by stirman** [OneSignal/react-native-onesignal#335]
```
var JSONObj = new Object()
var JSONObj = {
    "app_id": "[MY APP ID HERE]",
    "include_player_ids": ["[PLAYERID HERE"],
    "data": {"foo": "bar"},
    "contents": {"en": "English Message"}
}
OneSignal.postNotification(JSONObj)
```

App crashes, console in XCode shows:

```
2017-10-10 18:12:51.338 [fatal][tid:com.facebook.react.OneSignalQueue] Exception '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]' was thrown while invoking postNotification on target OneSignal with params (
        {
        "app_id" = "REDACTED";
        contents =         {
            en = "English Message";
        };
        data =         {
            foo = bar;
        };
        "include_player_ids" =         (
            "REDACTED"
        );
    },
    "<null>",
    "<null>",
    "<null>"
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Any idea what could be going on here?!

Many thanks. Been pulling my hair out all day with one :)

**Comment by stirman** [comment]
I also tried passing three separate arguments to postNotification as described in the README... 
```
let data = arr // some array as payload
let contents = {
	'en': 'You got notification from user'
}
OneSignal.postNotification(contents, data, playerId);
```

ERROR:

[tid:com.facebook.react.OneSignalQueue] Exception '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]' was thrown while invoking postNotification on target OneSignal with params (
        {
        en = "You got notification from user";
    },
    "<null>",
    "[REDACTED PLAYER ID]",
    "<null>"
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by StuartMorris0** [comment]
I have the same problem 👎 

It looks to me like its the syntax used as the error we see suggests null entries at the end too...
```
{
        "app_id" = "REDACTED";
        contents =         {
            en = "English Message";
        };
        data =         {
            foo = bar;
        };
        "include_player_ids" =         (
            "REDACTED"
        );
    },
    "<null>",
    "<null>",
    "<null>"
```

Now I have tried multiple different ways of passing the data into the postNotification function but I cannot seem to get it correct. I can make the nulls removed from the error, tried with and without the labels such as "contents" and still no joy. 

Here is the same error but without the headings (with the headings produces the same)...
```
 Exception '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]' was thrown while invoking postNotification on target OneSignal with params (
    "REDACTED-AppID",
        {
        en = "Test Message";
    },
        {
        foo = bar;
    },
        (
        "REDACTED-PlayerId"
    )
)
```

If you do figure it out, please update the thread.

**Comment by stirman** [comment]
I'm on React Native 0.47 and XCode 9.1 beta.

What version of RN and XCode are you on? Still having the same issue here, can't figure this one out!

**Comment by StuartMorris0** [comment]
Xcode 9.0 and latest RN 0.49.3

**Comment by stirman** [comment]
@geektimecoil Any thoughts here? Much appreciated!

**Comment by jkasten2** [comment]
@stirman @StuartMorris0 Thanks for the details, we will look into this issue.

Just to confirm is this only a iOS issue, no issues with Android?

So this issue isn't holding you up you can use the REST API directly to send a notification.
https://documentation.onesignal.com/reference#create-notification

Make sure you do NOT include the `Authorization: Basic` HTTP header in your app however.

**Comment by StuartMorris0** [comment]
@jkasten2 Correct only iOS for me, have not touched Android yet.

**Comment by stirman** [comment]
@jkasten2 Yes, sorry... I'm only working on iOS currently.

**Comment by nikitph** [comment]
happens for me too. same steps tried as @stirman

**Comment by wkoutre** [comment]
Same here. In the meantime, I'm using their REST API. Something like...

```
import axios from 'axios'

export const oneSignalSendNotification = async ({ playerIdsArr, contents }) => {
  const ONESIGNAL_URI = "https://onesignal.com/api/v1/notifications";
  const headers = {
    "Content-Type": "application/json",
    Authorization: `Basic ${ONESIGNAL_API_KEY}`
  };
  const config = {
    headers
  };

  const body = JSON.stringify({
    app_id: ONESIGNAL_APP_ID,
    include_player_ids: playerIdsArr,
    contents
  });

  try {
    const res = await axios.post(ONESIGNAL_URI, body, config);

    console.log(`*** RESPONSE FROM ONESIGNAL ***`, res);
  } catch (err) {
    console.log(`ONESIGNAL ERR`, err);
  }
};
```

**Comment by Nightsd01** [comment]
Here is the problem, the `postNotification()` function takes four parameters, you can't just provide the JSON body of the entire notification.

Here is the definition of the `postNotification()` function:

```    static postNotification(contents, data, player_id, otherParameters)```

Sending in all four parameters will resolve this particular issue.
