### ISSUE TITLE
Can't make a notification silent

### ISSUE THREAD

**Issue by aauffray** [OneSignal/react-native-onesignal#338]
Hi,

I want to make one of my notifications totally silent (i.e. not be displayed in any way, notification center nor in-app popup).

I tried to programmatically insert 'hidden' to true in my additional data (server side), 'shown' to false and I also tried to set both of these in the notification template on the website. Neither worked.

How can I do this ? Thanks

**Comment by avishayil** [comment]
https://documentation.onesignal.com/docs/silent-notifications

**Comment by isaaclem** [comment]
@avishayil :According to the link that you've shared, it seems like background-notifications by enabling `Mutable Content` only works with iOS?
