### ISSUE TITLE
Outdated Android Support Library

### ISSUE THREAD

**Issue by ivan133** [OneSignal/react-native-onesignal#340]
Hi!
I'm using react-native-onesignal@3.0.5
If I build an android app with targetSDKVersion set to 22 everything works fine.
But if I built an android app with targetSDKVersion set to 26,  It builds ok but when I install it to android 8.0.0 device I see a message "Outdated Android Support Library" in one signal users list.
And the push notifications don't work.
Looks like it applies only for android 8.0.0 (works on older version)

I have had similar issue with https://github.com/OneSignal/OneSignal-Cordova-SDK on other project and was able to solve it by decreasing the version from 2.2.2 to 2.2.0 Release

**Comment by pmogollons** [comment]
Hi, 

Im also getting this issue when opening an app on android 8, I get the following stack trace.

I already updated the build.gradle file to use

```
compileSdkVersion 26
buildToolsVersion "26.0.2"

dependencies {
    ...
    compile "com.android.support:appcompat-v7:26.0.0-alpha1"
    ...
}
```


```
08:21:40 E OneSignal : The included Android Support Library is to old or incomplete. Please update to the 26.0.0 revision or newer.
08:21:40 E OneSignal : java.lang.ClassNotFoundException: android.support.v4.app.JobIntentService
08:21:40 E OneSignal : at java.lang.Class.classForName(Native Method)
08:21:40 E OneSignal : at java.lang.Class.forName(Class.java:453)
08:21:40 E OneSignal : at java.lang.Class.forName(Class.java:378)
08:21:40 E OneSignal : at com.onesignal.OSUtils.initializationChecker(OSUtils.java:99)
08:21:40 E OneSignal : at com.onesignal.OneSignal.init(OneSignal.java:492)
08:21:40 E OneSignal : at com.onesignal.OneSignal.init(OneSignal.java:468)
08:21:40 E OneSignal : at com.onesignal.OneSignal.access$000(OneSignal.java:79)
08:21:40 E OneSignal : at com.onesignal.OneSignal$Builder.init(OneSignal.java:283)
08:21:40 E OneSignal : at com.geektime.rnonesignalandroid.RNOneSignal.initOneSignal(RNOneSignal.java:72)
08:21:40 E OneSignal : at com.geektime.rnonesignalandroid.RNOneSignal.onHostResume(RNOneSignal.java:286)
08:21:40 E OneSignal : at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:187)
08:21:40 E OneSignal : at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:616)
08:21:40 E OneSignal : at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:649)
08:21:40 E OneSignal : at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:850)
08:21:40 E OneSignal : at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:109)
08:21:40 E OneSignal : at com.facebook.react.ReactInstanceManager$4$2.run(ReactInstanceManager.java:821)
08:21:40 E OneSignal : at android.os.Handler.handleCallback(Handler.java:789)
08:21:40 E OneSignal : at android.os.Handler.dispatchMessage(Handler.java:98)
08:21:40 E OneSignal : at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
08:21:40 E OneSignal : at android.os.Looper.loop(Looper.java:164)
08:21:40 E OneSignal : at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
08:21:40 E OneSignal : at java.lang.Thread.run(Thread.java:764)
08:21:40 E OneSignal : Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.JobIntentService" on path: DexPathList[[zip file "/data/app/com.nativicate.growapp786-FRYcg9-GgV2I6RW1DiakBw==/base.apk"],nativeLibraryDirectories=[/data/app/com.nativicate.growapp786-FRYcg9-GgV2I6RW1DiakBw==/lib/arm, /data/app/com.nativicate.growapp786-FRYcg9-GgV2I6RW1DiakBw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
08:21:40 E OneSignal : at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
08:21:40 E OneSignal : at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08:21:40 E OneSignal : at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by harshrajk** [comment]
Hi @pmogollons, were you able to resolve this issue ?

**Comment by cihadturhan** [comment]
I can confirm it happens android 8.0 or above.
I followed exactly what's written in in readme.

I'm using v3.1.2 and I'll update to v3.1.4 if it matters.

**Comment by bss-trongluong** [comment]
I get whole day to resolve this bug

Update 
 minSdkVersion        : 16,
                compileSdkVersion    : 27,
                buildToolsVersion    : '27.0.3',
                targetSdkVersion     : 27
 and update com.android.support to 27.1.1 It will run

**Comment by rodrigograca31** [comment]
I just had this issued and solved it by upgrading to `<engine name="android" spec="~7.1.0" />` on my config file to support SDK 27 as well as remove one older plugin and had problems with dex (`Multiple dex files define Lorg/apache/cordova/BuildHelper`) and used this to solve it: https://stackoverflow.com/questions/46562289/multiple-dex-files-define-lorg-apache-cordova-buildhelper

**Comment by xstable** [comment]
@bss-trongluong `and update com.android.support to 27.1.1 It will run`
How did you do this?

**Comment by rgomezp** [comment]
There shouldn't be any current issues with the library being out of date. Please open a new issue if you encounter a similar issue

**Comment by ghost** [comment]
I found this [link](https://stackoverflow.com/a/16581310/5374771) as solution hope wil help you
