### ISSUE TITLE
disable alert box when app in foreground

### ISSUE THREAD

**Issue by kelvinblade** [OneSignal/react-native-onesignal#343]
how can i disable the alert box when the app is in opened and just show them as push notifications like when the app is closed? Thanks.

**Comment by hcyildirim** [comment]
Hi, you can look at the readme file [here.](https://github.com/geektimecoil/react-native-onesignal#set-in-app-focus-behavior)

## Android:
`OneSignal.inFocusDisplaying(2);`

## IOS:
```
self.oneSignal = [[RCTOneSignal alloc] initWithLaunchOptions:launchOptions
                     appId:@"YOUR APP ID"
                     settings:@{kOSSettingsKeyInFocusDisplayOption : @(OSNotificationDisplayTypeNotification), kOSSettingsKeyAutoPrompt : @YES}];
```

**Comment by Noitidart** [comment]
@ccoeder may you please share updated link. The docs don't seem to be there anymore.

**Comment by hcyildirim** [comment]
@Noitidart oh, they changed the readme file. I found the old version [here](https://github.com/geektimecoil/react-native-onesignal/tree/improved_demo#set-in-app-focus-behavior).

**Comment by Noitidart** [comment]
Thanks very much for such a fast reply @ccoeder !! I'll check that out. I'll also look out for updated docs, in case stuff changed.

**Comment by hemanowell** [comment]
Please can i use the code for android?

**Comment by hcyildirim** [comment]
@hemanowell Have you tried this one? `OneSignal.inFocusDisplaying(2);`
