### ISSUE TITLE
Release tags are missing from github

### ISSUE THREAD

**Issue by deavial** [OneSignal/react-native-onesignal#344]
Unable to do a diff to see what has changed as there hasn't been a release tag since 3.0.5 Without release notes being published, the only way to know if a release is safe to pull down is by reading the diffs.

**Comment by avishayil** [comment]
You're right, we'll try to do it from now on.

**Comment by robhogan** [comment]
There's no reason the tags couldn't be added retrospectively. IMO, it's most useful for seeing which release first contained a particular commit, eg: 

![image](https://user-images.githubusercontent.com/2590098/35363477-149b32c6-0162-11e8-8be7-fe14c98be303.png)

That comes in handy when you need to know which version to fall back to, or whether something you're watching has landed in a release yet.

They also provide a reliable changelog: https://github.com/geektimecoil/react-native-onesignal/compare/v3.0.4...v3.0.5

**Comment by avishayil** [comment]
These tags now been added.
