### ISSUE TITLE
Open specific component of  if a push notification is received when the application is in background

### ISSUE THREAD

**Issue by mostafiz93** [OneSignal/react-native-onesignal#347]
How can I navigate to a specific component if a notification is received when the application is in background?

I could easily do this when the notification is opened manually, i.e. notification is received and user has tapped on the notification to open it. 

I can even do this when the app is in foreground. I just add `onReceived` event listener described.

But my question is how can I automatically open the application and navigate to a particular component when a notification is received?

**Comment by jkasten2** [comment]
@mostafiz93 It sounds like you want to launch your app as soon as a notification is received, not when it is tapped on. It is only recommend that this is own if you are making a calling app. This is explained in the following issue.
https://github.com/geektimecoil/react-native-onesignal/issues/312
