### ISSUE TITLE
support promptLocation?

### ISSUE THREAD

**Issue by gbaladi** [OneSignal/react-native-onesignal#35]
Hi,

there is any way to use promptLocation from react native? 

thanks

**Comment by avishayil** [comment]
Hi @gbaladi,
I'm not sure what promptLocation means?

**Comment by gbaladi** [comment]
Hi @avishayil, 

from OneSignal IOS (and Android) API documentation site:

promptLocation
Prompts the user for location permissions to allow geotagging from the OneSignal dashboard. This lets you send notifications based on the device's location.

Example

Objective-C
[self.oneSignal promptLocation];
Note: Requires the follow entries in your .plist file.

NSLocationUsageDescription
NSLocationWhenInUseUsageDescription

**Comment by avishayil** [comment]
OK, I'll add this to the todo list

**Comment by avishayil** [comment]
Seems there is some problem, since for some reason the OneSignal framework is not including OneSignalLocation files, and therefore it's impossible to include promptLocation on iOS.

On Android it works great.

@jkasten2 - can you help with iOS here?

**Comment by jkasten2** [comment]
@avishayil If you include CoreLocation and the plist entries it should work. I am not sure I know what you mean by "OneSignalLocation files".

**Comment by avishayil** [comment]
Great. I'll try to do it and update. My mistake about the OneSignalLocation stuff.

**Comment by avishayil** [comment]
@jkasten2 what plist entries are you talking about?

**Comment by jkasten2** [comment]
@avishayil 

```
NSLocationUsageDescription
NSLocationWhenInUseUsageDescription
```

http://matthewfecher.com/app-developement/getting-gps-location-using-core-location-in-ios-8-vs-ios-7/

**Comment by avishayil** [comment]
@jkasten2 Tried doing that, says "No visible interface for promptLocation". My Objective-C is weak.

**Comment by jkasten2** [comment]
@avishayil Can you confirm it is being called with an instance of OneSignal? I see it is included in the [OneSignal.h](https://github.com/geektimecoil/react-native-onesignal/blob/979a0f873c9c6a2cadd3e768e47b63b439fe0633/examples/AwesomeProject/ios/Pods/OneSignal/iOS_SDK/Framework/OneSignal.framework/Versions/A/Headers/OneSignal.h#L109) in the example project you have.

**Comment by avishayil** [comment]
@jkasten2 it is included there, but doesn't work.

``` objc
RCT_EXPORT_METHOD(promptLocation) {
    [oneSignal promptLocation];
}
```

![Error](http://i.imgur.com/magPXeG.png)

**Comment by avishayil** [comment]
We're currently testing the new version, which apparently solves this issue.
