### ISSUE TITLE
INSTALL_FAILED_DUPLICATE_PERMISSION C2D_MESSAGE - install -r error

### ISSUE THREAD

**Issue by kingarawana** [OneSignal/react-native-onesignal#352]
I recently upgraded to onesingal@3.0.7 and everything seemed to be working correctly until I tried to reinstall the app on my development phone.

The error I get is: `Failed to finalize session : INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.example attempting to redeclare permission com.example..permission.C2D_MESSAGE already owned by com.example`

I reinstall by running:
`adb install -r myapp.apk`

I do this because I don't want to lose the data I have locally. This used to work fine in the past, but now it's no longer working.

The first time I reinstalled it after the upgrade it was fine. But after installed it, made some updates, then tried to reinstall it again, it failed with the error mentioned above.

I checked my app to see if that permission was declared anywhere else, it wasn't. The only place it was defined were in the one-signal build folders.

Please let me know if there's a way I can reinstall my app without losing all my existing data.

Thanks!

Phone: 6.0.1
react-native 0.49.5
minSdkVersion: 16
targetSdkVersion: 22
react-native-onesignal: 3.0.7

**Comment by avishayil** [comment]
Please make sure that you don't have multiple permission declarations in your Manifest.

**Comment by backlajan** [comment]
C:\platform-tools>adb install -r app.apk
Performing Streamed Install
adb: failed to install app.apk: Failure [INSTALL_FAILED_DEPRECATED_SDK_VERSION: App package must target at least SDK version 23, but found 21] What this
