### ISSUE TITLE
Not receiving push notification from FCM

### ISSUE THREAD

**Issue by shukerullah** [OneSignal/react-native-onesignal#359]
We have successfully implemented `react-native-onesignal` in our app and receiving push notifications on both platforms. But when I send notification from firebase panel or [pushtry.com](pushtry.com) to the android devices, it says successfully sent but not receiving notification on device. Is there any step that I have missed?

**Comment by jkasten2** [comment]
@shukerullah Android does not display the notification directly like iOS does. The app or the SDK in this case needs to parse the payload received from GCM / FCM and generate a notification. The payload format sent from the Firebase panel or from other services won't be in the format the OneSignal SDK is expecting.

**Comment by shukerullah** [comment]
Thanks for the response.
