### ISSUE TITLE
Push notifications disappear

### ISSUE THREAD

**Issue by FrenchBully** [OneSignal/react-native-onesignal#363]
I have everything wired and working AFAIK.  The issue I'm running into is when a push notification comes through and I ignore it by not clicking on it. The notification will eventually disappear from my notification history after several minutes. Testing on iOS, and not for android.

**Comment by jkasten2** [comment]
@FrenchBully Are you setting badges? If so badges will be cleared by the OneSignal SDK when the app is opened / resumed. When the app's badges are cleared iOS will automatically remove all notifications for your app from the notification center.

To disable the badge clearing done by the OneSignal SDK follow the guide below.
https://documentation.onesignal.com/docs/appearance#section-setting-and-clearing-badge-numbers

**Comment by arindam89** [comment]
I am also having the same issue and I am not setting the badge count.  Sometimes even the app also does not open up.

**Comment by FrenchBully** [comment]
I actually found the issue, thanks. A colleague was clearing the notification else where in the code, which I was eventually able to track down.
