### ISSUE TITLE
Exception on file abc_ic_ab_back_material.xml 

### ISSUE THREAD

**Issue by flobiwankenobi** [OneSignal/react-native-onesignal#37]
I got the error:

`File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013
`
**Emulator Info**
Android API Level: 19
CPU/ABI: Google APIs Intel Atom (x86)

**Comment by flobiwankenobi** [comment]
Found a solution by changing following lines in build.gradle:

**from**
    `compile 'com.android.support:appcompat-v7:+'`
    `compile 'com.android.support:support-v4:+'`
**to**
    `compile 'com.android.support:appcompat-v7:23.4.0'`
   `compile 'com.android.support:support-v4:23.4.0'`

**Comment by avishayil** [comment]
Thanks for the solution, i'll test it and include in the next releases.
