### ISSUE TITLE
Multiple OneSignal apps

### ISSUE THREAD

**Issue by rcorrie** [OneSignal/react-native-onesignal#375]
Is it possible to register to more than one OneSignal apps (particularly, on android)?

Thank you for such a great library!

**Comment by Nightsd01** [comment]
Yes, you can have multiple OneSignal apps with their own unique App ID's. Please feel free to ask if you have any other questions

**Comment by rcorrie** [comment]
@Nightsd01 Thanks, is there any documentation on how to set that up?

**Comment by lilian131** [comment]
I'd like to get the doc too ??

**Comment by rcorrie** [comment]
@lilian131 I got this working by obtaining a token with `react-native-onesignal` and then registering the device via the `POST https://onesignal.com/api/v1/players` api. 

This way you can register the device with multiple OneSignal Apps.

Something like this:

```Javascript
import OneSignal from 'react-native-onesignal'

OneSignal.getPermissionSubscriptionState(({pushToken}) => {
    fetch('https://onesignal.com/api/v1/players', {
        method: 'post',
        body: JSON.stringify({
             app_id: ONESIGNAL_APP_ID, // <== replace this with your app id
             identifier: pushToken,
             device_type: 0, // 0 = iOS, 1 = Android
             // Check the docs to see other accepted params
             // https://documentation.onesignal.com/reference#add-a-device
        })
    })
})
```

**Comment by wikramhwt** [comment]
Hello guys,
We are working on the On-demand restaurant management app. So basically we have. 3 android and iOS apps (user, admin and rider)
android push configured with firebase and firebase allows us to configure 3 apps against one firebase key.
How we can make this possible?
