### ISSUE TITLE
Amazon ADM support?

### ISSUE THREAD

**Issue by booker-laputa** [OneSignal/react-native-onesignal#376]
I would like to ask if Amazon FDM supported?

**Comment by avishayil** [comment]
I think it's a platform that competes with OneSignal, doesn't it?

**Comment by jkasten2** [comment]
@booker-laputa Do you mean Amazon ADM to support Kindle Fire devices? You can follow the additional steps below to add support.
https://documentation.onesignal.com/docs/amazon-sdk-setup
