### ISSUE TITLE
Notification Service Extension Issue

### ISSUE THREAD

**Issue by colinramsay** [OneSignal/react-native-onesignal#377]
With v3.0.9, having followed the instructions in the readme:

```
Undefined symbols for architecture x86_64:
  "_RCTRunningInAppExtension", referenced from:
      -[RCTOneSignal checkPermissions:] in libRCTOneSignal.a(RCTOneSignal.o)
      -[RCTOneSignal requestPermissions:] in libRCTOneSignal.a(RCTOneSignal.o)
      -[RCTOneSignal getPermissionSubscriptionState:] in libRCTOneSignal.a(RCTOneSignal.o)
  "_RCTSharedApplication", referenced from:
      -[RCTOneSignal checkPermissions:] in libRCTOneSignal.a(RCTOneSignal.o)
      -[RCTOneSignal requestPermissions:] in libRCTOneSignal.a(RCTOneSignal.o)
  "_OBJC_CLASS_$_RCTConvert", referenced from:
      objc-class-ref in libRCTOneSignal.a(RCTOneSignal.o)
  "_RCTRegisterModule", referenced from:
      +[RCTOneSignal load] in libRCTOneSignal.a(RCTOneSignal.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by Nightsd01** [comment]
@colinramsay When do you get this error, you are attempting to compile the primary App target for simulator I assume? 

How did you include RCTOneSignal as a dependency in your project?

**Comment by colinramsay** [comment]
This happens for simulator and device. We included as per the reader with the caveat that RN link didn’t work properly so we had to drag the xcproj into Xcode. That might be the source of the problem in that there’s another step we need to manually perform.

**Comment by Nightsd01** [comment]
@colinramsay when you say the RN link didn't work properly, what was the problem?

Are you saying you dragged RCTOneSignal.xcodeproj as a subproject of your Xcode project?

**Comment by Nightsd01** [comment]
When you look in your Xcode project settings (both for the app and the extension targets), do you see ***libRCTOneSignal.a*** as a framework in the ***Linked Frameworks and Libraries*** section?

<img width="1554" alt="ss_xcode" src="https://user-images.githubusercontent.com/8186991/35644795-d5843e62-067e-11e8-999a-3c27424cd9f3.png">

**Comment by colinramsay** [comment]
We added that in build phases as per the readme so I think so; I’m not at a computer now to check. 

The odd thing is that the errors we see refer to things in RN itself that it seems cannot be found.

**Comment by Nightsd01** [comment]
@colinramsay  This specifically started happening after you added the extension service? You were successfully able to run the app for both simulator & real iOS device before adding the extension?

**Comment by colinramsay** [comment]
I’ll have to check on that but it does look like the source of the errors is the extension.

**Comment by colinramsay** [comment]
Confirming that we do have libRCTOneSignal.a as a framework in the Linked Frameworks and Libraries section.

If I remove extension service target then the build succeeds.

**Comment by Nightsd01** [comment]
Just to confirm, you have ***libRCTOneSignal.a*** in the Linked Frameworks and Libraries in _both_ the Extension _and_ the primary App's target, right?

**Comment by colinramsay** [comment]
That's correct.

**Comment by Nightsd01** [comment]
Is your notification extension service in Swift or Objective-C?

**Comment by colinramsay** [comment]
Swift, and I've added the bridging header as per the readme.

**Comment by Nightsd01** [comment]
This is probably the issue.

When you select the Extension target, go to ***Build Settings***, and look for the ***Objective-C Bridging Header*** setting, what is the value?

**Comment by colinramsay** [comment]
I think you're probably right, but we've managed to get this working on our CI build so I think it was also related to something local to my computer. I guess expanding the docs to include exact instructions for the Obj-C Bridging Header might help for future issues. Thanks very much for spending time on this, it is appreciated.

**Comment by vinceprofeta** [comment]
@colinramsay @Nightsd01  can you post your Obj-C Bridging Header and a screenshot of the files I need to make.

**Comment by franzwarning** [comment]
Hi -- getting this same error. Using Obj-C for the Notification Service Extension. Not using Cocoapods -- used react-native link to setup. It works without the extension. Header search paths are right, and library is linked with both binaries. Any idea how to proceed?

**Comment by yongloon** [comment]
i have same issue, problem fixed?
