### ISSUE TITLE
Rich Notifications in iOS 10/11 

### ISSUE THREAD

**Issue by Nightsd01** [OneSignal/react-native-onesignal#379]
It appears that a recent update has broken rich push notifications in iOS 10 & 11.

The push notifications are delivered however the image is not shown correctly. It appears that the push notification extension service is not launching correctly.

This is resolved by compiling the universal ***libOneSignal.a*** framework using an older version of Xcode (8.3.3) which appears to resolve the problem.

**Comment by fatihkahveci** [comment]
@Nightsd01 we are getting same issue. When we try send "ios_attachments" notification delivered but image is not. We try https or not http as well but we are getting same error any idea?

**Comment by Nightsd01** [comment]
Hi @fatihkahveci 

Have you added the `OneSignalNotificationServiceExtension` to your iOS application? [Here are the steps](https://github.com/geektimecoil/react-native-onesignal#add-notification-service-extension) to add the extension service to your iOS app.

Also, what kind of attachments are you sending, just plain images? JPEG's or PNG's? Can you look at an example of one of the images that is not being shown in iOS and tell me what the file size is for this image?

**Comment by Nightsd01** [comment]
Also, if you did correctly add the extension service and your images aren't broken/too large, then you are likely experiencing the issue I described above. This will be fixed relatively soon with a new `react-native-onesignal` update. I apologize it's been 12 days, we've been working on a relatively large feature and the fix for this issue will be shipped along with it.

**Comment by fatihkahveci** [comment]
@Nightsd01 

Yes we add OneSignalNotificationServiceExtension correctly. Also we test jpg and png images and this images very small less then 100 kb. Thanks for quick response i think we need to weed new update :punch:

**Comment by Nightsd01** [comment]
@fatihkahveci  this issue has been resolved in 3.1.0.

Please feel free to respond if you are still encountering any issues.

**Comment by fatihkahveci** [comment]
Unfortunately issue is continue our case.

Firstly we added 3.1.0 version our package.json.

![package](https://cdn.pbrd.co/images/H9QWfIj.png)

And after that we add OneSignalNotificationServiceExtension and NotificationService.m file.

![service](https://cdn.pbrd.co/images/H9QXprj.png)

![service2](https://cdn.pbrd.co/images/H9QXOXu.png)

And this is NotificationService.m file

![servicefile](https://cdn.pbrd.co/images/H9QYu6Y.png)

Also this is one signal notification (Also we set Allow Arbitrary Loads to true so not ssl link is fine and we tested this with ssl link and still not working.)

![notification](https://cdn.pbrd.co/images/H9QYRQO.png)

ping @Nightsd01

**Comment by haabnaseem** [comment]
hi @fatihkahveci were you able to find a solution ?

**Comment by Nightsd01** [comment]
@fatihkahveci @haabnaseem Are you saying you are still unable to see rich push notifications?

This will not fix your problem, but it will help me understand what the problem is. Try this and let me know if the button shows up or not on the push notification.

Try sending a push notification through the OneSignal dashboard. Do ***NOT*** add images to this push notification. Instead, add two buttons. When you send this push notification to iOS, do the buttons show up?

The buttons won't show up automatically. If you have a 6S or newer, on the lock screen you have to force press for the buttons to show up. Otherwise, if you are on the home screen (device unlocked), you have to pull downwards when the notification shows up.

It looks something like this to show the buttons:

![alt text](https://cdn-images-1.medium.com/max/1600/1*pCEEzvhrWN7UGDubiHdtyQ.gif)

**Comment by fatihkahveci** [comment]
@haabnaseem @Nightsd01 

Hello, our problem has been solved. You need do three things for that.

1- Get lastest version.
2- You need to send rich media notification with https protocol.
3- Rich media notification only work on iOS 10+ (We don't test button notification on iOS 10 device.)
