### ISSUE TITLE
App freezes/hangs when pressing push notification if the app is closed

### ISSUE THREAD

**Issue by colinramsay** [OneSignal/react-native-onesignal#380]
We stripped our app back to bare bones and upgraded to the latest version of `react-native-onesignal` and were still seeing this. The app was unresponsive to use input, but there was nothing in any log that pointed at the problem.

This was fixed in a flash of genius by one of our developers who added:

```
OneSignal.configure({})
```

Before our app is started with `AppRegistry.registerComponent`. This isn't specifically mentioned in the readme but I can see that it's called here:

https://github.com/geektimecoil/react-native-onesignal/blob/9690b71eac5a89263a949898ae1867020e12a7a5/examples/RNOneSignal/redux-index.js#L42

It's not exactly clear why this was needed so it might be worth documenting.

**Comment by el-lsan** [comment]
I was facing the same issue and adding `OneSignal.configure({})` solved the issue.
Thanks! 

P.S: As you mentioned, probably this should be on readme ( if not a bug ).

**Comment by Nightsd01** [comment]
We believe this issue has been resolved since `3.1.0`. Please feel free to post if you are still encountering this issue and we'll be happy to reopen and investigate.

**Comment by adirzoari** [comment]
@colinramsay did you succeed to get notification when app is closed?
can you show example please?

**Comment by colinramsay** [comment]
Our solution is documented in my initial comment on this issue.

**Comment by adirzoari** [comment]
@colinramsay did you succeed to do it without Android Notification Extender Service?

**Comment by colinramsay** [comment]
This was on iOS.

**Comment by adirzoari** [comment]
ah.. it works for you in android?

**Comment by colinramsay** [comment]
We weren't implementing on Android at that time, so I can't say.
