### ISSUE TITLE
App crashes when notification arrives in opened application

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [OneSignal/react-native-onesignal#381]
when application is opened then notification is displayed on application and then app crash.
is there any option to not displayed notification in alert when app opened ?

**Comment by Nightsd01** [comment]
Can you post a stack trace of the crash? Are you talking about Android or iOS...?

If you don't want an in-app alert to be displayed, you can call OneSignal.inFocusDisplaying(0) to set it to not display an alert (the OS will handle it)
