### ISSUE TITLE
Notification Recieved but app stopped

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [OneSignal/react-native-onesignal#383]
When received notification it displayed in the notification bar but after that app stopped working.

react-native : 0.52.0
react-native-onesignal: 3.0.8

![](https://im.ezgif.com/tmp/ezgif-1-4dec264ef6.gif)

**Comment by Nightsd01** [comment]
I am closing this issue due to both inactivity & a complete lack of detail. I have literally no idea what "app stopped working" means.

Please feel free to respond and _add more details_ if you are still encountering this issue and I will be happy to reopen it.

**Comment by nilaybrahmbhatt** [comment]
See this image.
when app receive notification on notification panel suddently app stoped working.

![2018-02-07-12-26-45](https://user-images.githubusercontent.com/6310631/36770035-fea496fc-1c6d-11e8-9a7a-b18479d7001d.gif)
