### ISSUE TITLE
Google Play Services Library Error 

### ISSUE THREAD

**Issue by LuckyLuky** [OneSignal/react-native-onesignal#387]
Hi, 

I can't seem to connect my app to OneSignal. App compiled successfully, but it doesn't receive notifications. 

When I go `Users/All Users` in administration, I see a connection, but with an error stating `Google Play services library initialization error. Check for conflicting plugins and make sure "com.google.android.gms.version" is in your AndroidManifest.xml. Check the logcat for more details.`. 
I've checked the `AndroidManifest.xml` located in `android/app/build/intermediates/manifests/full/debug` and I can see the `com.google.android.gms.version` metadata there. 

Any suggestions on how to fix this?

**Comment by WilliamAnputra** [comment]
Is your device shown on OneSignal's dashboard?

**Comment by LuckyLuky** [comment]
Yes, it is. I'm providing screenshots. 


![image](https://user-images.githubusercontent.com/13261271/36018993-017c0bac-0d7e-11e8-8a05-c26c937afa49.png)

![image](https://user-images.githubusercontent.com/13261271/36019001-09b98268-0d7e-11e8-9210-4109d81959f1.png)

**Comment by LuckyLuky** [comment]
Problem solved. I wasn't aware that the app has to be built for release. Is there any way to test this in debug release?

**Comment by LuckyLuky** [comment]
Update - I've found out that the real reason was that I didn't have permission to receive notifications. So for anyone experiencing the same issue, make sure you have this line in your `AndroidManifest.xml`: 

`<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>`

**Comment by nirweb** [comment]
I have the same problem and i do added this code but not work :-( please help.

**Comment by yaseralimardany** [comment]
same problem

**Comment by neo125874** [comment]
@LuckyLuky @wpyar @yaseralimardany any solution? thanks..

**Comment by LuckyLuky** [comment]
Well the solution I've provided worked for me. 

I suggest checking the debug version of `AndroidManifest.xml` generated during build, if it contains the required permission. Otherwise, I don't know.

**Comment by yaseralimardany** [comment]
same problem

**Comment by neo125874** [comment]
@LuckyLuky @yaseralimardany I got this, in my situation, that's the build version issue...
After updating gradle, gms, it finally works.
Thank you both.

**Comment by yaseralimardany** [comment]
I got this error in logcat:
E/OneSignal: Unknown error getting FCM Token
                                                          java.lang.NoSuchMethodError: No static method isDeviceProtectedStorage(Landroid/content/Context;)Z in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in /data/app/com.motoshubapp-2/base.apk)
                                                              at com.google.firebase.FirebaseApp.zza(Unknown Source)
                                                              at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                              at com.onesignal.PushRegistratorFCM.initFirebaseApp(PushRegistratorFCM.java:64)
                                                              at com.onesignal.PushRegistratorFCM.getToken(PushRegistratorFCM.java:50)
                                                              at com.onesignal.PushRegistratorAbstractGoogle.attemptRegistration(PushRegistratorAbstractGoogle.java:97)
                                                              at com.onesignal.PushRegistratorAbstractGoogle.access$100(PushRegistratorAbstractGoogle.java:37)
                                                              at com.onesignal.PushRegistratorAbstractGoogle$1.run(PushRegistratorAbstractGoogle.java:84)
                                                              at java.lang.Thread.run(Thread.java:818)

**Comment by yaseralimardany** [comment]
and pushToken is null in the real device. In the onesignl project i have error:

Google Play Services Library Error
--

**Comment by GibranPolonsky** [comment]
same problem.

**Comment by yaseralimardany** [comment]
any ideas?

**Comment by vedpawar** [comment]
I am also facing the same issue.

**Comment by vahid263** [comment]
I have the same problem

**Comment by yaseralimardany** [comment]
Its onesignal problem in newer version. Older version that you put app id in the androidmanifest.

**Comment by adirzoari** [comment]
@yaseralimardany  I'm facing same error and also push token is null. any new??

**Comment by adirzoari** [comment]
@LuckyLuky  I had the permission and still get this issue.

**Comment by LuckyLuky** [comment]
@adirzoari Check if this permission is present in the debug/release version of `AndroidManifest.xml` generated during build. Otherwise, I don't know unfortunately.

**Comment by adirzoari** [comment]
maybe it's because I have react-native-firebase and it not working together?

**Comment by lahed** [comment]
same problem

**Comment by jkasten2** [comment]
Make sure you have the latest 3.2.4 OneSignal SDK that was released on May 21th and follow these new additional setup [Adding the Gradle Plugin](https://documentation.onesignal.com/docs/react-native-sdk-setup#section-adding-the-gradle-plugin) step.

**Comment by lahed** [comment]
Yes, i try on a fresh project, and dont work :(

**Comment by MaurilioMatsuyama** [comment]
Same problem here...i'm using onesignal with xamarin

**Comment by MaurilioMatsuyama** [comment]
I solved here....
I uninstalled the google play services packages and onesignal in sequence.
After this i installed onesignal and everything works now.
Ps: Look in archives created after build and verify if the google play services dll is there.
P2s: I'm using onesignal with xamarin applications.

**Comment by Demuzx** [comment]
@lahed, just the versions of your compileSdkVersion 26, buildToolsVersion "26.0.0" must match your compile "com.android.support:appcompat-v7:26.0.0". See your app/build.gradle.

**Comment by kllm** [comment]
+1

**Comment by lahed** [comment]
check #525

**Comment by nahidmbstu** [comment]
@lahed  , i am getting notification but the app is crashing after receiving it . how to solve it ????????????????????

my build.gradle
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        maven { 
            url 'https://maven.google.com/' 
            name 'Google'
        } 
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven { 
          
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { 
            url 'https://maven.google.com/' 
            name 'Google' 
        }
    }
}
```
app/build.gradle

```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal 
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.0, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.2"

    defaultConfig {
        applicationId "com.driverapp"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
         manifestPlaceholders = [onesignal_app_id: "7cb17176-6d1d-48cb-89aa-2df617123eba",
                                onesignal_google_project_number: "REMOTE"]
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-mauron85-background-geolocation')
    compile project(':react-native-image-picker')
    compile project(':react-native-onesignal')
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:26.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-base:+'
    compile 'com.google.android.gms:play-services-maps:+'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}


```


one signal code 


```
 OneSignal.init("7cb17176-6d1d-48cb-89aa-2df617123eba")
      OneSignal.setSubscription(true);
     // OneSignal.inFocusDisplaying(2);


      OneSignal.addEventListener('received', this.onReceived);
      OneSignal.addEventListener('opened', this.onOpened);
      OneSignal.addEventListener('ids', this.onIds);

      OneSignal.configure();  // if device info not working 


    }


    onReceived = (notification) => {
      console.log("Notification received: ", notification);
    }

    onOpened = (openResult) => {
      console.log('Message: ', openResult.notification.payload.body);
      console.log('Data: ', openResult.notification.payload.additionalData);
      console.log('isActive: ', openResult.notification.isAppInFocus);
      console.log('openResult: ', openResult);
    }

    onIds = (device)=> {
      console.log('Device info: ', device);
    }

  


    componentWillUnmount() {
      OneSignal.removeEventListener('received', this.onReceived);
      OneSignal.removeEventListener('opened', this.onOpened);
      OneSignal.removeEventListener('ids', this.onIds);
    
    }

```

androidmanifesto.xml


```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.driverapp">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:launchMode="singleTop">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
       <meta-data
      android:name="com.google.android.geo.API_KEY"
      android:value="key"/>
    </application>

</manifest>
```

**Comment by coz119** [comment]
<activity 
...
>
<service android:name="com.google.firebase.components.ComponentDiscoveryService" >
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
 </service>
...
</activity>

It works for me.

**Comment by coz119** [comment]
`
<activity ...>
<service android:name="com.google.firebase.components.ComponentDiscoveryService" >
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
 </service>
...
</activity>
`

It works for me

**Comment by carnivash** [comment]
None of the solutions proposed here worked for me, i'm using onesignal package version 2.6.0, is there anything else worth trying? thanks

**Comment by ThallyssonKlein** [comment]
same problem here, I posted my configuration files on this other issue:

https://github.com/OneSignal/react-native-onesignal/issues/525#issuecomment-668732429

**Comment by ThallyssonKlein** [comment]
I changed the app_id of the onesignal in the app to a new one and it worked.

**Comment by parthanjaria** [comment]
i am also facing the same issue.
