### ISSUE TITLE
'silent notifications' without user consent for notifications should be possible ?

### ISSUE THREAD

**Issue by Gys** [OneSignal/react-native-onesignal#388]
I want to update my app in the background using silent notifications. The way I understand it, iOS does not require the notifications permission for receiving silent notifications. At least not according to this link:
https://www.urbanairship.com/blog/watch-list-ios-8-opt-in-changes

I tried to test this, but found that `onRegistered(notifData) {}` is not fired if I disallow notifications. So my app only *registers* with the OneSignal server if the users *allows* notifications.

So I wonder, is this an artificial limitation of react-native-onesignal ? Or an artificial limitation of the OneSignal service ? Or is UrbanAirship simply wrong and is this a real limitation of iOS ?

**Comment by Nightsd01** [comment]
OneSignal does not support silent notifications if the user is not subscribed to push notifications. We may considering allowing this in the future but at the present time it is not allowed.

It is allowed by iOS, however, so if you want to use silent notifications without registering the user for push notifications you certainly can. You just can't do it with onesignal, sorry.

**Comment by franzwarning** [comment]
Consider reopening?
