### ISSUE TITLE
Is thie library working with react native EXPO ?

### ISSUE THREAD

**Issue by OdaiTu** [OneSignal/react-native-onesignal#391]
im using EXPO for my application and i want to know if this library supported for expo ?
if yes can you explain if there are some differs 
thanks

**Comment by Nightsd01** [comment]
Hi @OdaiTu , since Expo seems to just be a package on top of the standard react-native environment, I don't think you should have a problem using our SDK. Please let us know if you encounter any issues with it and we'll be happy to reopen.
