### ISSUE TITLE
Android: tapping notification re-opens app

### ISSUE THREAD

**Issue by WilliamAnputra** [OneSignal/react-native-onesignal#393]
my app reopens the app only when the notification is tapped when the app is in background. i've followed solutions from #81, it didn't work

**Comment by Nightsd01** [comment]
@WilliamAnputra Please add a bit more detail to your bug report.

 Could you show me a JSON example of the push notification you are sending? 

What version of the OneSignal RN SDK are you using, how did you add it to your project, and what environment are you using (standard React Native, expo, etc). 

I am closing this issue until more information is provided. I would be happy to reopen the issue once this happens so we can investigate further.

**Comment by calanti** [comment]
I am experiencing the same thing, launchMode="singleTop" too. My project is a detached Expo (ExpoKit) app. 


    "react-native-onesignal": "^3.1.1",
    "react": "16.0.0",
    "expo": "^24.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz",

**Comment by pjcaro** [comment]
@calanti Could you solve it?

**Comment by Gutyn** [comment]
@WilliamAnputra Any luck fixing this? Any solution/workaround? Have a beautiful day.
