### ISSUE TITLE
Both IOS and Android work perfectly in development environment, but not work in production environment

### ISSUE THREAD

**Issue by MelissaWeng** [OneSignal/react-native-onesignal#394]
Both IOS and Android work perfectly in development environment (push notification can be received wonderfully), but not work in production environment. 

IOS in production environment shows the following screen when loading the app:
![image](https://user-images.githubusercontent.com/34234560/36259304-7c596d5a-1266-11e8-822b-8daf1bd0a7bd.png)
But when I comment the usage codes and comment `import OneSignal from 'react-native-onesignal';`, the app can be loaded normally.

Android in production environment can open the app, but push notification doesn't work and OneSignal doesn't get the player ID.

My project is using ExpoKit (ejected from expo). 
dependences from package.json:
```
"dependencies": {
    "expo": "^22.0.0",
    "moment": "^2.20.1",
    "react": "16.0.0-beta.5",
    "react-native": "https://github.com/expo/react-native/archive/sdk-22.0.0.tar.gz",
    "react-native-background-geolocation": "^2.10.1",
    "react-native-elements": "^0.18.5",
    "react-native-firebase": "^3.2.0",
    "react-native-onesignal": "^3.0.9",
    "react-native-vector-icons": "^4.4.2",
    "react-native-view-more-text": "^1.4.2",
    "react-navigation": "^1.0.0-beta.15"
  }
```

Anyone has any ideas? Thank you so much!

**Comment by Nightsd01** [comment]
Hi @MelissaWeng this indicates that the OneSignal library isn’t being loaded correctly. Can you run using Xcode with a release profile and see if you get any errors printed to the console?

**Comment by MelissaWeng** [comment]
@Nightsd01 Oh yes, actually it's the profile problem. The app was in the store before I installed the oneSignal Library and there was no appropriate certificates for push notification. I generated new signed APK and uploaded to Play Store for Android, and made a new build for App Review for IOS, and did updates in the real phones (so certificates installed). Now it works!

I'm closing this issue.
