### ISSUE TITLE
Android version doesn't work with react-native-device-info

### ISSUE THREAD

**Issue by yevhenjl** [OneSignal/react-native-onesignal#396]
On Android 'react-native-onesignal' doesn't work together with react-native-device-info.
Does not even register users.

`
"react-native-onesignal": "^3.0.9",
"react-native-device-info": "^0.14.0",
`

**Comment by Nightsd01** [comment]
I’m not sure what you mean when you say it “does not work”...?

**Comment by yevhenjl** [comment]
I mean, after installing "react-native-device-info" Android version doesn't register device, even no any messages in console (I took code from example). On iOS all fine.
Without "react-native-device-info" in both OS all work.

**Comment by yevhenjl** [comment]
In addition, if AndroidManifest.xml has the option `tools:node="replace"`, OneSignal in Android does not work either. I just deleted this line and "react-native-device-info" and it all worked.

**Comment by christianversloot** [comment]
Thanks a lot @yevhenjl this solved my problem!
