### ISSUE TITLE
Get the current playerid/userid

### ISSUE THREAD

**Issue by williamrijksen** [OneSignal/react-native-onesignal#4]
Is it currently possible to get the current OneSignal userid/playerid like this on iOS? https://documentation.onesignal.com/docs/ios-sdk-api#section-idsavailable.

I need it to send a specific notification to a specific user.

**Comment by avishayil** [comment]
Good idea.
You now have:

``` javascript
OneSignal.idsAvailable((idsAvailable) => { 
    console.log(idsAvailable.playerId);
    console.log(idsAvailable.pushToken);
});
```

on the latest package.

**Comment by jvandijk** [comment]
That's an awesome fast response! Thank you!

**Comment by avishayil** [comment]
Let me know if it works or you have any issues.
If not, i'll close this issue...
Thanks!

**Comment by williamrijksen** [comment]
@avishayil I looks like it's working on iOS. Thank you!

**Comment by avishayil** [comment]
Your'e welcome!
Closing issue.

**Comment by alejandrorbradford** [comment]
how does that work for iOS/Swift?

**Comment by BeauNouvelle** [comment]
@alejandrorbradford and anyone else getting here after a google search here it is for Swift:

```
OneSignal.idsAvailable { (pushID, pushToken) in
    print(pushID)
    print(pushToken)
}
```

**Comment by nodeEnthu** [comment]
for people coming here in 2017:
```
Deprecations and Major Changes
March 21, 2017: Removed getRegistrationId() from documentation. getUserId() should always be used instead.
March 15, 2016: Deprecated getIdsAvailable() in favor of getUserId() and getRegistrationId(). Deprecated idsAvailableCallback in favor of subscriptionChange event.
```

**Comment by jpmazza** [comment]
I cannot get the playerId.
I tried with `OneSignal.idsAvailable` but is not a function. Also tried with `OneSignal.getUserId` and it display the error "is not a function".

How can I get the player id? I have installed the version 3.0.7.

Thanks in advance!

**Comment by SamiChab** [comment]
Apparently it has now changed. According to the docs you have to add an event listener:
````
componentWillMount() {
    OneSignal.addEventListener('ids', this.onIds);
}

componentWillUnmount() {
    OneSignal.removeEventListener('ids', this.onIds);
}

onIds(device) {
    console.log('Device info: ', device);
}
````

**Comment by bhgames** [comment]
Yeah but that new onIds function never gets fired.

**Comment by antton** [comment]
What about Web push? Is it possible to "send notifications to an specific user"?

**Comment by sinapcs** [comment]
@bhgames @jpmazza  could you find a way to get current playerID?

**Comment by bhgames** [comment]
So, using the latest version (3.2.2)

  componentWillMount() {
    OneSignal.init(Config().pushId, {kOSSettingsKeyAutoPrompt: true});

    OneSignal.addEventListener('ids', this.updatePushId.bind(this));
    OneSignal.configure()
  }

  async updatePushId(device) {
    postJSON(UPDATE_PUSHID_URL, 
      {
        user_id: this.props.user.id,
        push_id: device.userId
      },
      { 'Authorization': this.props.authentication_token }
    );
  };


This worked for me.

**Comment by sinapcs** [comment]
@bhgames it worked. thanks.
OneSignal.configure() did the trick. why there is nothing about it in documents :|

**Comment by bhgames** [comment]
Because you needed to know it. That's why. :P React Native development is the worst development.

**Comment by jorge-mr** [comment]
https://documentation.onesignal.com/docs/ios-native-sdk#section--getpermissionsubscriptionstate-
```swift
let userId = OneSignal.getPermissionSubscriptionState().subscriptionStatus.userId
print("your userID:",userId!)
```

**Comment by immortal-88** [comment]
The goal was to recieve PlayerID from Onesignal on application launch. 
So in App.js for me worked the following code:
```javascript
let userID;
componentWillMount() {
    OneSignal.init(ONESIGNAL_APP_ID, {
      kOSSettingsKeyAutoPrompt: true,
    });
    OneSignal.getPermissionSubscriptionState( (status) => {
      userID = status.userId;
      alert(userID);
    });
  }
```

**Comment by kenef** [comment]
Has anyone figured this out? How can I get the Player ID of a specific device? I need this to be able to send push notifications to my users. Groups and filters are worthless in my application. The only thing I need is the Player ID and I can't find anything about how to get this in any of the documentation. Can someone please help? My app is built in Ionic V3.

**Comment by davekedar** [comment]
I have the same problem, documentatoin is not clear 

```
import React from "react";
import { AsyncStorage } from "react-native";
import { createRootNavigator } from "./router";
import { isSignedIn } from "./auth";
import { YellowBox } from "react-native";
import OneSignal from "react-native-onesignal"; // Import package from node modules
//import { Provider } from 'react-redux';
//import { store } from '../app/redux/app-reducer';
YellowBox.ignoreWarnings([
  "Warning: isMounted(...) is deprecated",
  "Module RCTImageLoader"
]);
export default class App extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      signedIn: false,
      checkedSignIn: false
    };
  }
  componentWillMount() {
    OneSignal.init("my app id");
    
    OneSignal.addEventListener("received", this.onReceived);
    OneSignal.addEventListener("opened", this.onOpened);
    OneSignal.addEventListener("ids", this.onIds);
  }

  componentWillUnmount() {
    OneSignal.removeEventListener("received", this.onReceived);
    OneSignal.removeEventListener("opened", this.onOpened);
    OneSignal.removeEventListener("ids", this.onIds);
  }

  onReceived(notification) {
    console.log("Notification received: ", notification);
  }

  onOpened(openResult) {
    console.log("Message: ", openResult.notification.payload.body);
    console.log("Data: ", openResult.notification.payload.additionalData);
    console.log("isActive: ", openResult.notification.isAppInFocus);
    console.log("openResult: ", openResult);
  }

  onIds(device) {
    console.log("Device info: ", device);
  }

  componentDidMount() {
    // status = AsyncStorage.getItem('loggedIn');
    // if(status === 'success'){
    //   this.setState({checkedSignIn: true});
    // }
    isSignedIn()
      .then(res => this.setState({ signedIn: res, checkedSignIn: true }))
      .catch(err => alert("An error occurred"));
  }

  render() {
    const { checkedSignIn, signedIn } = this.state;

    // If we haven't checked AsyncStorage yet, don't render anything (better ways to do this)
    if (!checkedSignIn) {
      return null;
    }

    const Layout = createRootNavigator(signedIn);
    return (
      //<Provider store={store}>
      <Layout />
      //  </Provider>
    );
  }
}
```
this is my code and it was told to me in other thread that i should use OneSignal.getPermissionSubscriptionState(callback) but where ? and how ? and how will I pass playerID? please someone help

**Comment by kenef** [comment]
@davekedar I was able to get this to work by calling it in my ionViewDidLoad()

```
window["plugins"].OneSignal.getIds(function(ids) {
    //alert(JSON.stringify(ids['userId']));
    let playerID = ids['userId'];
    //alert(playerID);
});
```

This is working for me; give it a shot.

**Comment by davekedar** [comment]
Thanks @kenef

**Comment by pztrick** [comment]
Just invoking `OneSignal.configure()` was enough to have an event emitted on the listener `'ids'`.

E.g.:

```
  componentWillMount() {
      OneSignal.init("APP ID GOES HERE", {kOSSettingsKeyAutoPrompt : true});
      OneSignal.addEventListener('received', this.onReceived);
      OneSignal.addEventListener('opened', this.onOpened);
      OneSignal.addEventListener('ids', this.onIds);

      OneSignal.configure();  // <-- add this line
  }

  componentWillUnmount() {
      OneSignal.removeEventListener('received', this.onReceived);
      OneSignal.removeEventListener('opened', this.onOpened);
      OneSignal.removeEventListener('ids', this.onIds);
  }

  onReceived(notification) {
      console.log("Notification received: ", notification);
  }

  onOpened(openResult) {
    console.log('Message: ', openResult.notification.payload.body);
    console.log('Data: ', openResult.notification.payload.additionalData);
    console.log('isActive: ', openResult.notification.isAppInFocus);
    console.log('openResult: ', openResult);
  }

  onIds(device) {
    console.log('Device info: ', device);
  }
```

**Comment by SirPhemmiey** [comment]
To help those still having issues getting the `player_id`.

```
onIds(device) {
    console.log('Device info: ', device);
  }
```
The `device` returns an object. So to really get the `player_id ` you're looking for, you should do something like `device.userId`

**Comment by luizmagao** [comment]
How do I get this to work in Cordova?

**Comment by kenef** [comment]
@luizmagao what is your environment?

**Comment by Mayurk007** [comment]
hello i have quickblox dialogid how i fetch quickblox userid by using this dialogid

**Comment by cyb3rsalih** [comment]
> Just invoking `OneSignal.configure()` was enough to have an event emitted on the listener `'ids'`.
> 
> E.g.:
> 
> ```
>   componentWillMount() {
>       OneSignal.init("APP ID GOES HERE", {kOSSettingsKeyAutoPrompt : true});
>       OneSignal.addEventListener('received', this.onReceived);
>       OneSignal.addEventListener('opened', this.onOpened);
>       OneSignal.addEventListener('ids', this.onIds);
> 
>       OneSignal.configure();  // <-- add this line
>   }
> 
>   componentWillUnmount() {
>       OneSignal.removeEventListener('received', this.onReceived);
>       OneSignal.removeEventListener('opened', this.onOpened);
>       OneSignal.removeEventListener('ids', this.onIds);
>   }
> 
>   onReceived(notification) {
>       console.log("Notification received: ", notification);
>   }
> 
>   onOpened(openResult) {
>     console.log('Message: ', openResult.notification.payload.body);
>     console.log('Data: ', openResult.notification.payload.additionalData);
>     console.log('isActive: ', openResult.notification.isAppInFocus);
>     console.log('openResult: ', openResult);
>   }
> 
>   onIds(device) {
>     console.log('Device info: ', device);
>   }
> ```

So, How can you extract the ID ? Could you explain it more?

**Comment by sourabhCofoundry** [comment]
Get the all playerid/userid using jquery and other .Please let me know it's possible or not

**Comment by pawanchhapola** [comment]
This worked for me in functional component:

```
  const data = await OneSignal.getDeviceState();
  const player_id=data.userId;
```

**Comment by beyzatsc** [comment]
> This worked for me in functional component:
> 
> ```
>   const data = await OneSignal.getDeviceState();
>   const player_id=data.userId;
> ```

thank you.. you are my hero

**Comment by AliAbdullah1122** [comment]
> OneSignal

can you send me the code you use here

**Comment by AliAbdullah1122** [comment]
i cannot get playerid in latest version v9 of onesignal in react native

**Comment by harinderratton** [comment]
OneSignal.getDeviceState().then((idsAvailable) => {console.log('idsAvailable', idsAvailable?.userId)});

**Comment by yepes** [comment]
OneSignal.getDeviceState().then(idsAvailable => {
              console.log('idsAvailable', idsAvailable?.userId);
            });

Throws an "undefined is not a function"


"react-native-onesignal": "^5.0.1",

**Comment by nan-li** [comment]
Hi @yepes, 

`OneSignal.getDeviceState()` is no longer available in the latest major release.

Please see [this guide](https://github.com/OneSignal/react-native-onesignal/blob/major_release_5.0.0/MIGRATION_GUIDE.md) for all the methods and properties available in version 5.x.x of the react-native-onesignal library.
