### ISSUE TITLE
Duplicate notification registration

### ISSUE THREAD

**Issue by tonyxiao** [OneSignal/react-native-onesignal#40]
Set bridge can be called multiple times due to reloading bundle during debugging or code push.

```
- (void)setBridge:(RCTBridge *)receivedBridge {
    _bridge = receivedBridge;

    if (launchDict) {
        NSLog(@"launchDict:%@", launchDict);
        [_bridge.eventDispatcher sendDeviceEventWithName:@"remoteNotificationOpened" body:launchDict];
    }
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(handleRemoteNotificationReceived:)
                                                 name:OSRemoteNotificationReceived
                                               object:nil];
}
```

We will end up calling `handleRemoteNotificationReceived` and thus js multiple times for each notification.

**Comment by avishayil** [comment]
Can you set up a PR for this?
@jkasten2 can you help?

**Comment by jkasten2** [comment]
@avishayil or @tonyxiao Can you try out the following commit to see if it fixes the issue?
https://github.com/jkasten2/react-native-onesignal/commit/e3137a8fa2d33a10b1e11dfd5f0826e392052cd2

**Comment by avishayil** [comment]
It seems to work well, thanks @jkasten2 .
@tonyxiao can you test on your end and report back using the latest package?

Thanks!

**Comment by tonyxiao** [comment]
👍 looks good

**Comment by avishayil** [comment]
Closing issue for now.
Thanks!
