### ISSUE TITLE
No Sound On iOS Notification (Only Vibration)

### ISSUE THREAD

**Issue by dancherb** [OneSignal/react-native-onesignal#403]
I'm trying to use a custom sound for push notifications with OneSignal on my React Native app. It works wonderfully for Android, but I'm only getting a vibration for iOS.

I'm using this line on my server:

`ios_sound: "synthring.aiff"`

And have added the file to my root folder as shown in the image (all black blocks are my app name): https://i.stack.imgur.com/GUBAk.png

I'm following this doc: https://documentation.onesignal.com/docs/customize-notification-sounds

Any ideas why I'm not hearing anything? The sound is less than 10 seconds long, and I've also tried wav sounds exported specifically as U-Law and A-Law.

I've found I'm also getting no default sound of any kind when I remove the ios_sound line, just a vibration, so maybe the problem is here. Has anyone else come across this?

Thanks!

**Comment by Nightsd01** [comment]
It sounds like you either have the mute switch on the device set to mute, or you have the alert ringer volume set too low. 

Just tested the latest version of the react native onesignal SDK in iOS and the sound seems to work fine. I would suggest looking at the mute switch or alert volume.

**Comment by Nightsd01** [comment]
@dancherb  It sounds like you either have the mute switch on the device set to mute, or you have the alert ringer volume set too low. 

Just tested the latest version of the react native onesignal SDK in iOS and the sound seems to work fine. I would suggest looking at the mute switch or alert volume.

**Comment by dancherb** [comment]
Jesus yeah that was it, bought an iPhone for work and no-one told me there was a hardware mute switch, cheers for that heads up! 

Custom sounds all working well, but I noticed that on iOS the notification "fades out" after a few seconds and the sound stops. Is there any way to make it stick? (I'm trying to set up a phone call kind-of notification). I'll close the issue for now!

**Comment by Nightsd01** [comment]
This is an iOS limitation. If you’re trying to make a phone call type of notification, you might look into using PushKit VOIP notifications. The OneSignal SDK doesnt currently support it at the current time however.

**Comment by dancherb** [comment]
I've found that the notification does stick around and ring properly if on the lock screen, which I'm happy with... last q: if the notification pops up while in the app on iOS, pressing "close" doesn't stop the custom sound - it still goes on for 30 seconds (on Android it stops right away, as if we tapped the notification from anywhere else). Do you know of any workarounds for this - maybe a way to silence the sound from within the app, or to disable the sound/handle the notification myself if the app is already open? thanks for the help!
