### ISSUE TITLE
OneSignal.h file not found

### ISSUE THREAD

**Issue by faustoct1** [OneSignal/react-native-onesignal#405]
Getting this error on xcode `OneSignal.h file not found`. I have expo detached and everything was working fine suddenly it stopped maybe an unexpected update or smth.

Sometimes I get an error `OSEmailSubscription`.

Any ideia what's going on? how to fix it?

**Comment by Nightsd01** [comment]
@faustoct this was fixed in a recent PR (#404) which has now been included in update 3.1.1

**Comment by faustoct1** [comment]
@Nightsd01 tks will test let u know.. tks for replying me as soon as possible..

**Comment by faustoct1** [comment]
@Nightsd01  worked ! thanks
