### ISSUE TITLE
How to send notification a precise date?

### ISSUE THREAD

**Issue by DarkXelus** [OneSignal/react-native-onesignal#409]
Hello,
I would like send a notification on a certain dates i try with this code but he doesn't work can you help me.

`let contents = {
      'en': Notification send'
}
OneSignal.postNotification(contents, {}, token, {send_after: date})`
a variable date matches a date want to send

**Comment by Nightsd01** [comment]
@DarkXelus This would not be an issue with the SDK.

You need to send the date as an ISO formatted date string. For example: `Thu Sep 24 2015 14:00:00 GMT-0700 (PDT)` or `September 24th 2015, 2:00:00 pm UTC-07:00` are examples that would both work.

Please let me know if you have any further issues and I'd be happy to help.

**Comment by DarkXelus** [comment]
@Nightsd01 I tried with the following code but it returns me an error: 
`OneSignal.postNotification(contents, {}, token, 'Mon Mar 5 2018, 9:49:00 GMT-0100')`

He send a notification now instead of the specified date.

error: JSON value  'Mon Mar 5 2018, 9:49:00 GMT-0100' of NSString cannot be converted to NSDictionary
How to appear the badge?
Do you have an example to help me?

Thank
