### ISSUE TITLE
Unable to merge AndroidManifest

### ISSUE THREAD

**Issue by tonyxiao** [OneSignal/react-native-onesignal#41]
Keeps on getting the following error

```
[com.onesignal:OneSignal:2.4.1] /Users/Tony/Code/app/node_modules/react-native-onesignal/android/build/intermediates/exploded-aar/com.onesignal/OneSignal/2.4.1/AndroidManifest.xml:54:17-69 Error:
    Missing 'name' key attribute on element category at [com.onesignal:OneSignal:2.4.1] AndroidManifest.xml:54:17-69
[com.onesignal:OneSignal:2.4.1] /Users/Tony/Code/app/node_modules/react-native-onesignal/android/build/intermediates/exploded-aar/com.onesignal/OneSignal/2.4.1/AndroidManifest.xml Error:
    Validation failed, exiting


See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

:react-native-onesignal:processDebugAndroidTestManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-onesignal:processDebugAndroidTestManifest'.
> java.lang.RuntimeException: Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Basically the `manifestPlaceholders` from my `app/build.gradle` is not able to override the settings `build.gradle` inside `react-native-one-signal`. Therefore `manifestApplicationId` as well as all the other fields are empty string.

**Comment by avishayil** [comment]
@jkasten2 any ideas?

**Comment by avishayil** [comment]
I bypassed it by moving some random values to the manifest placeholders, your settings on app build.gradle should overwrite them.

Please tell me if the issue persists.

**Comment by avishayil** [comment]
Closing issue for now. Please report back if issue persists. 
Thanks!

**Comment by ricardomalagon** [comment]
Hi, i have the same error any another idea how to solve it? @avishayil

**Comment by jkasten2** [comment]
@ricardomalagon The following error from above means that only parts of the `AndroidManifest.xml` are being added to your apk.
```
Missing 'name' key attribute on element category at [com.onesignal:OneSignal:2.4.1] AndroidManifest.xml
```
Please post you full error if it differers in anyway.

I am not sure what would omit only part of the setting from the OneSignal SDK like this. If you can provide a project or a step-by-step guide on reproducing the issue we can reopen and take a look.
