### ISSUE TITLE
Ios Media Attachment Issue

### ISSUE THREAD

**Issue by fatihkahveci** [OneSignal/react-native-onesignal#410]
Hello,

When we try to send notification with ios_attachment notification appears but image is not. Our settings here;

Firstly we added 3.1.0 version our package.json.

![package](https://cdn.pbrd.co/images/H9QWfIj.png)

And after that we add OneSignalNotificationServiceExtension and NotificationService.m file.

![service](https://cdn.pbrd.co/images/H9QXprj.png)

![service2](https://cdn.pbrd.co/images/H9QXOXu.png)

And this is NotificationService.m file

![servicefile](https://cdn.pbrd.co/images/H9QYu6Y.png)

Also this is one signal notification (Also we set Allow Arbitrary Loads to true so not ssl link is fine and we tested this with ssl link and still not working.)

![notification](https://cdn.pbrd.co/images/H9QYRQO.png)

ping @Nightsd01

**Comment by Nightsd01** [comment]
@fatihkahveci Can you send me your `info.plist`? 

In my own testing with the react-native SDK, HTTP image url's will not load unless you make an App Transport Security exception in your info.plist.

**Comment by fatihkahveci** [comment]
@Nightsd01 

![service](https://cdn.pbrd.co/images/Ha5vaVP.jpg)

This settings true since we begin to develop app. Also we test image with https. I can send you info.plist file with email if you want?

**Comment by Nightsd01** [comment]
@fatihkahveci Can you tell me what happens when, instead of trying to attach images to the push notification, you attach buttons instead? Do the buttons show up correctly or is the notification still blank?

**Comment by fatihkahveci** [comment]
@Nightsd01 Still same. When we try to send button, notification appears but button not.

**Comment by Nightsd01** [comment]
@fatihkahveci if buttons also aren't being attached, that indicates that the OneSignalNotificationServiceExtension is never being launched, or is crashing. 

Do you have some crash reporter, such as Crashlytics, installed in your application? Are you seeing any crash reports involving the OneSignalNotificationServiceExtension?

**Comment by Nightsd01** [comment]
By the way, how exactly are you running your app? You're just using the generated xcodeproj to launch it right?

**Comment by fatihkahveci** [comment]
@Nightsd01 

Yes we are using Crashlytics. But not any error in OneSignalNotificationServiceExtension. And yes we lunch xcodeproj but also we try to send testflight for testing other devices but still same. Notification appears but image or button not :(  . This is so wierd

**Comment by Nightsd01** [comment]
@fatihkahveci Would it be possible for you to PM me a link to a zip of your project to make this investigation a bit easier? 

If not, can you answer some questions:

1. Is your project using any Swift?

2. When you attempted the test to use buttons, did you also attach an image with that same notification? If so, can you please test with ONLY a button and no image and tell me if the button still does not appear?

3. How are you handling provisioning/codesigning with the OneSignalNotificationServiceExtension? Did you select 'automatically manage signing' on the General settings page for the extension?

**Comment by fatihkahveci** [comment]
@Nightsd01 

Good news its work when we try  iPhone9,3 (11.2.2) with ssl image. But when we try this not ssl image its not show.

**Comment by Nightsd01** [comment]
@fatihkahveci I am not sure what you mean...? Are you talking about an HTTPS image working but HTTP images do not work?

**Comment by fatihkahveci** [comment]
@Nightsd01 
Yes https image working but http image not.

**Comment by Nightsd01** [comment]
@fatihkahveci Can you give me an example of one of the HTTP image url's that does not work?

**Comment by Nightsd01** [comment]
This would definitely be an issue with app transport security settings, not the OneSignal SDK

**Comment by fatihkahveci** [comment]
@Nightsd01 I think so too but its weird we give App Transport Security permission for this. I think we need to get ssl for our cdn.


HTTP : http://cdn.fatchapp.com/images/users/135055/photo_QRV0KIWteU.jpeg
HTTPS : https://pbs.twimg.com/profile_images/873942556526211075/6w0LNT9D_400x400.jpg

**Comment by Nightsd01** [comment]
Yeah. Unfortunately we have no control over what App Transport Security blocks.

I would suggest setting your domain as an exception so that ATS doesn't block it. You can do this by modifying your `info.plist` file like this:

```xml
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSExceptionDomains</key>
  <dict>
    <key>fatchapp.com</key>
    <dict>
      <!--Include to allow subdomains-->
      <key>NSIncludesSubdomains</key>
      <true/>
      <!--Include to allow HTTP requests-->
      <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
      <true/>
      <!--Include to specify minimum TLS version-->
      <key>NSTemporaryExceptionMinimumTLSVersion</key>
      <string>TLSv1.1</string>
    </dict>
  </dict>
</dict>
```
