### ISSUE TITLE
Notification not received on Android when application is dead

### ISSUE THREAD

**Issue by lucasharada** [OneSignal/react-native-onesignal#411]
I made a custom notification when a specific kind of data arrives from server, but it only works when the application is alive (be it foreground or background). For this, I tested setting `OneSignal.inFocusDisplaying(0);` and `OneSignal.inFocusDisplaying(2);`.

When in foreground, everything runs smooth: the notification is received, the data is processed and a modal is shown to the user.

When in background, I still have a little problem: the notification is received, the data is processed and the modal is created and shown on the screen; the problem is that **no notification appears** on the tray in a way that the user has no idea of what happened. This occured with both `inFocusDisplaying` 0 and 2.

The real problem is when the application is dead, because no notification is shown. I checked #341, but I still need this custom notification to be built and shown on screen. Is there a way to do so?

**Versions:**

- "react": "16.0.0",
- "react-native": "0.51.0",
- "react-native-onesignal": "3.1.1",

**Comment by Nightsd01** [comment]
@lucasharada this is quite unusual. 

Silly question, but are you sure you don't have Do-Not-Disturb enabled on the device?

Here are the different types of notification display modes:
0: ** None** It is up to your application to show the notification when the application is open. Whenever your application is closed or in the background, however, the system should still show the notification.
1: **In-App Alert** The SDK will show an in-app alert whenever a notification is received if the app is running in the foreground. However if the app is closed or in the background, the system will show the notification.
2: ** System** Lets the system handle whether or not the notification is shown.

**Comment by lucasharada** [comment]
@Nightsd01 Do-Not-Disturb is disabled. I already tested this on 2 devices, but the output is the same. The notification is only received when the application is alive. 

Based on your explanation, the display mode I need is the **None** (0), so I can threat it when the application is open, but let the system handle it when application is dead.

Here is the piece of code related to the OneSignal feature:

```
import React, { Component } from 'react';
import { View } from 'react-native';
import OneSignal from 'react-native-onesignal';

import RootNavigator from './RootNavigator';
import GiftModal from './modals/GiftModal';

// Mocked data to be received with Notification additionalData
const test = require('./TestGift.json');

OneSignal.configure({});

class RootComponent extends Component<{}> {

  state = {
    modalVisible: false,
    activeModalImage: null,
    activeModalEstablishmentName: null,
    activeModalTitle: null,
    activeModalDescription: null
  };

  componentWillMount() {
    OneSignal.inFocusDisplaying(0);
  }

  componentDidMount() {
    this.onReceived = this.onReceived.bind(this);
    this.onOpened = this.onOpened.bind(this);

    OneSignal.addEventListener('received', this.onReceived);
    OneSignal.addEventListener('opened', this.onOpened);
  }

  componentWillUnmount() {
    OneSignal.removeEventListener('received', this.onReceived);
    OneSignal.removeEventListener('opened', this.onOpened);
  }

  onReceived(notification) {
    console.log('Notification received: ', notification);
    // console.log('Test file: ', test);

    // const data = notification.payload.additionalData;
    const data = test;
    if (data.type === 'gift') {
      this.setState({
        activeModalImage: data.Gift.Image,
        activeModalEstablishmentName: data.Gift.Name,
        activeModalTitle: data.Gift.Title,
        activeModalDescription: data.Gift.Description,
        modalVisible: true
      });
    }
  }

  onOpened(openResult) {
    console.log('Message: ', openResult.notification.payload.body);
    console.log('Data: ', openResult.notification.payload.additionalData);
    console.log('isActive: ', openResult.notification.isAppInFocus);
    console.log('openResult: ', openResult);
  }

  hideModal() {
    this.setState({ modalVisible: false });
  }

  formatDate(date) {
		const day = date.getDate()
			.toLocaleString('en-US', { minimumIntegerDigits: 2, useGrouping: false });
		const month = (date.getMonth() + 1)
			.toLocaleString('en-US', { minimumIntegerDigits: 2, useGrouping: false });
		const year = date.getFullYear().toString().substr(-2);

		return `${day}/${month}/${year}`;
	}

  render() {
    return (
      <View style={{ flex: 1 }}>
        <RootNavigator />
        <GiftModal
          isVisible={this.state.modalVisible}
          hideModal={this.hideModal.bind(this)}
          giftImage={this.state.activeModalImage}
          giftEstablishmentName={this.state.activeModalEstablishmentName}
          giftTitle={this.state.activeModalTitle}
          giftDescription={this.state.activeModalDescription}
          date={this.formatDate(new Date())}
        />
      </View>
    );
  }
}

export default RootComponent;
```

**Comment by lucasharada** [comment]
@Nightsd01 Got to work! Seems like I had some trouble with cache. The steps I took to fix were:

1. npm cache clean --force
2. cd android && ./gradlew clean
3. cd .. && react-native run-android

**Comment by adirzoari** [comment]
@lucasharada I'm facing same issue. I'm looking a way to get notification when app is closed. I just did exactly as tutorial and it works just when app is open.did you succeed to get notification in android when app is closed?

**Comment by shahchaitanya** [comment]
I'm getting same issue in One Plus 5 which has Oreo 8.0.0. Other android version except 8, get notification even app is killed. I'm using react-native-one-signal 3.0.5 version.
