### ISSUE TITLE
Dependency "react-native-onesignal" has no shared framework schemes

### ISSUE THREAD

**Issue by MayeuldP** [OneSignal/react-native-onesignal#416]
I got this message 
`Dependency "react-native-onesignal" has no shared framework schemes
`
when I run in my project `carthage update --platform iOS`.... 
Any ideas ?

Concerning my config :

```
Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.10.0
  Yarn:  1.5.1
  npm:  5.6.0
  Watchman:  Not Found
  Xcode:  Xcode 9.2 Build version 9C40b
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3
```

**Comment by Nightsd01** [comment]
@MayeuldP Why are you using Carthage? The OneSignal RN SDK is distributed through npm. Are you using Carthage for some other dependency?

**Comment by MayeuldP** [comment]
Yeap ! That's it ! 
So currently I got a redScreen with this one : ` this._nativeModule.addListener is not a function ... this._nativeModule.addListener is undefined`...it's indeed because of RNOneSignal, because it's the corresponding file of the error, that's why I think it could come from the carthage update because it's the only place where I have troubles with OpenSignal setup...

**Comment by Nightsd01** [comment]
@MayeuldP  I still don't quite understand what you are doing with Carthage. Can you send me your Cartfile?

**Comment by MayeuldP** [comment]
Here it is (in my Cartfile) : 
```
github "intercom/intercom-ios"
github "bugsnag/bugsnag-cocoa"
github "mixpanel/mixpanel-iphone"
github "geektimecoil/react-native-onesignal"
```
I can't right now try it, but so should I try to remove it from the cartfile, and try to setting up correctly with npm and react-native link ?  

Thank a lot for trying to help me by the way 👍

**Comment by Nightsd01** [comment]
@MayeuldP  Yes, you will want to remove it from Carthage and install it via npm. Please make sure to read the readme, this will resolve your problem, please feel free to ask if you encounter any further issues.
