### ISSUE TITLE
Time to Live

### ISSUE THREAD

**Issue by kasperbe** [OneSignal/react-native-onesignal#418]
Hey!

I noticed in the Interface of OneSignal's administration interface there's a TTL property.
I tried settings this to for examples 10 seconds, however it has no effect. 

Is this something we have to manually handle?

**Comment by Nightsd01** [comment]
@kasperbe The TTL property determines how long the notification will be valid (shown to the user) when the device is offline. So if you set the TTL to be 10 minutes and the device is offline (undeliverable) for 11 minutes, they will not see the notification. By default this property is set to 3 days with OneSignal. 

Most developers/companies never need to mess with the TTL property but it's there in case you need it. 

Feel free to reply if you're having problems with this and I'll be happy to reopen the issue.

**Comment by kasperbe** [comment]
So by offline, it doesn't actually mean unread? I expected this to mean if the message has not been read within TTL it will get removed. Did I misunderstand?
