### ISSUE TITLE
calling getPermissionSubscriptionState does not register the device with Onesignal

### ISSUE THREAD

**Issue by hmenzagh** [OneSignal/react-native-onesignal#419]
Hi, 

as said in the title calling getPermissionSubscriptionState does not register the device with Onesignal, i need to restart the app and that it gets properly registered ..

here is my code :

```js
const manageIosPermissions = (account, dispatch) => {
	if (isIphone()) {
		OneSignal.getPermissionSubscriptionState((status) => {
			if (status.hasPrompted === false) {
				OneSignal.registerForPushNotifications();
			}
		});
	};
};
```

Thanks

**Comment by Nightsd01** [comment]
Are you saying that in your app devices never get registered? What is the root issue?

`getPermissionSubscription()` state is simply a getter method, it doesn't register the device with OneSignal. Device registration happens automatically, usually after around 5-15 seconds.

**Comment by hmenzagh** [comment]
Thanks for your answer,
Then the issue is that the device does not get registered automatically i need to restart the app, and then it instantly gets registered ! I have waited around 2-3mn with no results ..

**Comment by Nightsd01** [comment]
@hmenzagh please provide some more details. Is this only occurring in iOS or Android? When you say the app "does not register", what precisely do you mean? How do you know the app is not getting registered?

I am closing this issue until more detail is provided, as of right now I am not sure what to make of this issue, but I will be happy to reopen and investigate once you provide more information.

**Comment by hmenzagh** [comment]
Details: based on the device tracking on OneSignal, we cannot send any notifications or see the device unless the app has been restarted (only on iOS).

Update: since we integrated deep-links (the only one signal related edit) this is no longer an issue, I don't know if this is related or not ... so the issue may stay closed ! Thanks
