### ISSUE TITLE
No known class method for selector 'didReceiveRemoteNotification:'

### ISSUE THREAD

**Issue by suupham2506** [OneSignal/react-native-onesignal#421]
![screen shot 2018-03-16 at 10 46 40 am](https://user-images.githubusercontent.com/28852565/37502771-56761306-2907-11e8-906c-efb1c56faca5.png)

**Comment by jonkarlbiere** [comment]
same here
is there any other solution?

**Comment by jkasten2** [comment]
@suupham2506 @zootopia106 This was removed from the setup instructions a while ago as it is now handled automatic in the SDK. You can safely remove the 4 lines (42 to 45) in this case.
```objective-c
// Required for the notification event.
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification {
  [RCTOneSignal didReceiveRemoteNotification:notification];
}
```

**Comment by Nightsd01** [comment]
@suupham2506 @zootopia106  This has also been updated in the demo project as well.
