### ISSUE TITLE
error: package com.geektime.rnonesignalandroid does not exist

### ISSUE THREAD

**Issue by Kisepro** [OneSignal/react-native-onesignal#422]
Hello,

I already saw this issue referenced and I tried the solutions proposed but it's still not working for me.
It's working on a empty project when install it but not working on my main project, so I'm wondering what could be the problem ? 

However I can find the correct com.geektime.rnonesignalandroid package in node_modules\react-native-onesignal\android\src\main\java\com\geektime\rnonesignalandroid so I can't understand why it's not found.

react 16.0.0
react-native 0.54.2

My MainApplication.java
```
package com.XXX;

import com.geektime.rnonesignalandroid.ReactNativeOneSignalPackage;
import android.app.Application;

import com.facebook.react.ReactApplication;
import com.AlexanderZaytsev.RNI18n.RNI18nPackage;
import com.facebook.reactnative.androidsdk.FBSDKPackage;
import com.inprogress.reactnativeyoutube.ReactNativeYouTube;
import com.oblador.vectoricons.VectorIconsPackage;
import com.imagepicker.ImagePickerPackage;
import com.RNFetchBlob.RNFetchBlobPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import com.facebook.CallbackManager;
import com.facebook.FacebookSdk;
import com.facebook.appevents.AppEventsLogger;
import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private static CallbackManager mCallbackManager = CallbackManager.Factory.create();

  protected static CallbackManager getCallbackManager() {
    return mCallbackManager;
  }

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(new MainReactPackage(),
          new ReactNativeOneSignalPackage(),

          new RNI18nPackage(), new FBSDKPackage(mCallbackManager), new ReactNativeYouTube(), new VectorIconsPackage(),
          new ImagePickerPackage(), new RNFetchBlobPackage());
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();

    FacebookSdk.sdkInitialize(getApplicationContext());
    // If you want to use AppEventsLogger to log events.

    SoLoader.init(this, /* native exopackage */ false);

    AppEventsLogger.activateApp(this);
  }
}

```

The ReactNativeOneSignalPackage.java in my nodes_modules

```
package com.geektime.rnonesignalandroid;

import com.facebook.react.ReactPackage;
import com.facebook.react.bridge.JavaScriptModule;
import com.facebook.react.bridge.NativeModule;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.uimanager.ViewManager;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Created by Avishay on 1/31/16.
 */
public class ReactNativeOneSignalPackage implements ReactPackage {
...
}
```

**Comment by Kisepro** [comment]
I don't know why but the "react-native link" was not adding the line "compile project(':react-native-onesignal')"  I did it manually and it's now working

Another minor problem is that the link action add each times the following lines
```
import com.geektime.rnonesignalandroid.ReactNativeOneSignalPackage;
new ReactNativeOneSignalPackage(),

```

The issue can be closed

**Comment by Nightsd01** [comment]
@Kisepro I'm unable to reproduce this issue. In my attempt, I created a completely new react-native project and manually added the react-native-onesignal SDK following the instructions in the readme.

Did you follow the guidance in the readme precisely to the letter? If not, how did you do it?

**Comment by Kisepro** [comment]
@Nightsd01 Yes I followed it precisely, and doing it on a completly new react-native project it works also for me.

It's really specific to my project I think and I managed to make it works when I understood why so I guess you shouldn't lose your time on that issue.

I suspect this could be because of "react-native-push-notification" linking, I had another conflict with i this package like this compile instruction

```
dependencies {
    compile ('com.google.android.gms:play-services-gcm:8.1.0') {
        force = true;
    }
...
}
```

I don't need this package anymore so it was not a big deal to remove it

**Comment by Nightsd01** [comment]
I am glad to hear that resolved your issue.

We have a onesignal grade plugin that can resolve issues similar to this. It needs to be placed at the ***top*** of the App gradle file:

```
plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.8.1'
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin
```

**Comment by krunalray** [comment]
I migrate 4.3.6 to 5.0.0 and follow the Android SDK Setup instruction.

i used
"react-native": "0.64.0",

buildToolsVersion = "34"
        minSdkVersion = 21
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "23.1.7779620"
        kotlin_version = '1.9.0'

when i build the release apk and start the app then suddenly it's crash and give me error

`FATAL EXCEPTION: mqt_native_modules

com.facebook.react.bridge.NativeArgumentsParseException: OneSignal.setLogLevel got 2 arguments, expected 1

FATAL EXCEPTION: mqt_native_modules
Process: com.student.project, PID: 9884
com.facebook.react.bridge.NativeArgumentsParseException: OneSignal.setLogLevel got 2 arguments, expected 1
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:332)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
	at java.lang.Thread.run(Thread.java:1012)` 
	
in debug mode i'm not getting any kind of error and working fine.
