### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by ScreamZ** [OneSignal/react-native-onesignal#424]
Hello,

I'm getting this error when I try to compile on android

com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: -26: Package com.biogen new target SDK 22 doesn't support runtime permissions but the old target SDK 26 does.

```

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="23" />
```

Why ?

Best regards

**Comment by Nightsd01** [comment]
@ScreamZ I am not sure what makes you think this is related to the OneSignal SDK....?

I am closing this issue due to a total lack of details. Please add more information (ie. a list of your project's dependencies, what triggered this issue, and so on) and I will be happy to reopen it.
