### ISSUE TITLE
Android cold start notification not triggering opened event listener

### ISSUE THREAD

**Issue by pmogollons** [OneSignal/react-native-onesignal#425]
Im having an issue with the opened event listener that is not getting triggered all times on cold start. Almost 30% of the times we open a notification the listener event is not getting called.

We have already checked that there are related issues and that this was fixed, previous to this fix we were not able to get android to trigger the listener at all, but the issue still persist.

We are using:

"react-native": "0.48.4",
"react-native-onesignal": "3.1.1",

## Realated issues
https://github.com/geektimecoil/react-native-onesignal/issues/195
https://github.com/geektimecoil/react-native-onesignal/issues/279
https://github.com/geektimecoil/react-native-onesignal/issues/332

Thanks in advance.

**Comment by Nightsd01** [comment]
@pmogollons I am not able to reproduce your problem. Can you tell me if this issue still occurs in version `3.1.2` of the react-native-onesignal SDK?

Also, how do you know that the `opened` event is not being called? Can you remove everything from the function, and only add a single `console.log` statement to make sure that none of your code could be causing the issue?

Lastly, if that doesn't work, can you reproduce this issue in the Demo project located in the `/examples/RNOneSignal` folder?

**Comment by Nightsd01** [comment]
Closing due to no response....

If you are still encountering this issue @pmogollons please feel free to respond with the questions I asked above and I'll be happy to reopen & investigate.

**Comment by anniewey** [comment]
I'm facing the same probleme. App is launched but onOpened isn't triggered. Tried upgrade the version from 3.2.5 to 3.2.6 but issue still persist.
FYI, I've implemented according to the documentation https://documentation.onesignal.com/v5.0/docs/react-native-sdk-setup#section-usage
