### ISSUE TITLE
IOS: Cannot find protocol declaration for 'OSSubscriptionObserver'

### ISSUE THREAD

**Issue by ogeeThilook** [OneSignal/react-native-onesignal#428]
It's not possible to build IOS version.
There is closed case:
https://github.com/geektimecoil/react-native-onesignal/issues/329

**Packages Version**
"react": "^16.3.0-alpha.1"
"react-native": "0.54.0"
"react-native-onesignal": "^3.1.1"

The error is triggered in **RCTOneSignal.h**

```
#if __has_include(<OneSignal/OneSignal.h>)
#import <OneSignal/OneSignal.h>
#else
#import "OneSignal.h"
#endif

@interface RCTOneSignal : NSObject <OSSubscriptionObserver, OSEmailSubscriptionObserver>

- (id)initWithLaunchOptions:(NSDictionary *)launchOptions appId:(NSString *)appId;
- (id)initWithLaunchOptions:(NSDictionary *)launchOptions appId:(NSString *)appId settings:(NSDictionary*)settings;

@end
```

**Comment by Nightsd01** [comment]
@ogeeThilook Can you verify if this issue still occurs in the latest version `3.1.2`...? 

Are you sure you followed the readme instructions carefully and added the `Header Search Paths` to your Xcode project's build settings?

Lastly, can you explain how you added the OneSignal SDK to your project? You are not using Cocoapods, correct?

**Comment by aliy321** [comment]
im also having this issue, using Cocoapods.

**Comment by Nightsd01** [comment]
@aliy321 what do you mean you’re using cocoa pods? 

All you need is npm to install react-native-onesignal

**Comment by ogeeThilook** [comment]
Hello @Nightsd01 thank you for your quick reply. For some reason, the one-signal was appearing inside PodFile automatically and was trying to be installed via cocoa pods. After removing the node modules folder and install one-signal as the first dependency (After react-native and react) I was able to resolve the issue.
