### ISSUE TITLE
setLocationShared is not a function

### ISSUE THREAD

**Issue by hjJunior** [OneSignal/react-native-onesignal#434]
I have cloned example repository to get started, when I build I'm getting this error

```
_reactNativeOnesignal2.default.setLocationShared is not a function
```

I've see #370 pull request merge, but even with this, I got this error, what should I do do solve the problem

### Details
Running on iOS simulator

**Comment by Nightsd01** [comment]
@hjJunior Why are you using `_reactNativeOnesignal.default`...? What is the 'default' property? 

The example project does not include this line anywhere.

Are you sure you are downloading the most recent example project, and that npm is installing the most recent version of the `react-native-onesignal` dependency?

**Comment by hjJunior** [comment]
Sorry, I've cloned the repository, so I'll close now, because when I install by npm its everything okay 👍
