### ISSUE TITLE
Switching back from setSubscription(false) to setSubscription(true)

### ISSUE THREAD

**Issue by martinosmartinos** [OneSignal/react-native-onesignal#436]
It looks like once you unsubscribe user with setSubscription(false) and later on subscribe back with setSubscription(true) -- it  stays on false at least onesignal dashboard shows user as opted out.
Any trick here to overcome named issue?

**Comment by Nightsd01** [comment]
@martinosmartinos I am not able to replicate your behavior. When I use `setSubscription(false)` and then go back to `setSubscription(true)`, the dashboard correctly shows the user as being subscribed again.

Are you seeing any errors printed to the log when you do `setSubscription(true)`? Are you sure the user was subscribed before your app ever calls `setSubscription(false)`...?

**Comment by martinosmartinos** [comment]
Actually I was wrong and everything works fine while switching setSubscription. Problem was my code itself so I am closing this issue. Thanks for reply and putting me on a right path, appreciate!
