### ISSUE TITLE
IOS setup step missed in Docs

### ISSUE THREAD

**Issue by VBarzionov** [OneSignal/react-native-onesignal#438]
Hi,
It seems that setup steps for IOS verision missed part about inserting ONE_SIGNAL_APP_ID.
I try this package first time, and not very confident is this step is nessesary.
However untill I did modification in AppDelegate.m - pushes did not work.
I found info here https://github.com/OneSignal/react-native-onesignal
![image](https://user-images.githubusercontent.com/33849682/38006818-37c4df2c-324f-11e8-9716-14f9165d77ff.png)

**Comment by Nightsd01** [comment]
@VBarzionov I’m not sure what you mean? The readme is very clear about where to put the OneSignal App ID, both for iOS and Android...?

**Comment by VBarzionov** [comment]
There is no information about set APP_ID for IOS on this page https://github.com/geektimecoil/react-native-onesignal

**Comment by Nightsd01** [comment]
@VBarzionov yes, there is. The readme says where to put the code and also says to replace with your own App ID. 

```
On the application didFinishLaunchingWithOptions method, insert the following code (replace YOUR_ONESIGNAL_APP_ID with your OneSignal app ID):
```

**Comment by VBarzionov** [comment]
You are right. 
After you point I could finally find the code inside collapsed block.
