### ISSUE TITLE
Android notifications register without prompt?

### ISSUE THREAD

**Issue by ilyakar** [OneSignal/react-native-onesignal#447]
Sorry if it’s a silly question, I’m not too familiar with Android workings. So Android users don’t get a prompt for getting notifications, they are just automatically subscribed?

**Comment by djalmaaraujo** [comment]
@ilyakar I might be wrong, but after buildTools 25, the user accepts to receive notifications before installing the app. :)

**Comment by jkasten2** [comment]
@ilyakar @djalmaaraujo Android does not have a system prompt for notification permissions like iOS does, they are enabled by default. Android 6.0 (API Level 23) did add runtime permission prompts however notifications were not one of them.

If you wish to not auto subscribe your users you may call `OneSignal.setSubscription(false);` after init on the first app start. Then when you prompt and they accept call `OneSignal.setSubscription(true);`.

**Comment by ilyakar** [comment]
Thank you for explaining, Josh. That’s what I was hoping for.

Kind regards,
Ilya
