### ISSUE TITLE
Network failure on OneSignal.logoutEmail()

### ISSUE THREAD

**Issue by vgeorge** [OneSignal/react-native-onesignal#448]
I've successfully registered an user e-mail after login using `OneSignal.setEmail(email, callback)`, but when I call OneSignal.logoutEmail(callback) the following error is returned: `Failed due to network failure. Will retry on next sync.`. It doesn't seem to exist a network problem, otherwise `.setEmail()` wouldn't work. I'm using the following versions:

```
"react-native": "0.51.1"
"react-native-onesignal": "3.1.4"
```

**Comment by jkasten2** [comment]
@vgeorge Is this an issue with iOS or Android or both? Are using the latest 3.1.4 OneSignal React Native SDK?

**Comment by vgeorge** [comment]
@jkasten2 I've tested only on Android. If you mean "3.1.4 OneSignal React Native SDK" as this module  3.1.4 version, yes, this is the version. Also I've only tested in the emulator, with Android 8.1.

**Comment by Nightsd01** [comment]
@vgeorge calls to `setEmail()` don't get executed immediately, it can take up to 30 seconds. 

Is your app waiting until the callback for `setEmail()` returns successfully before trying to call `logoutEmail()`? 

If so, would it be possible for you to reproduce this issue in our example demo project?

**Comment by vgeorge** [comment]
@Nightsd01 I was trying to use this feature to notify a specific user, but I found out how to do it using `setTags()` and `getTags()`. I won't have time to try with the example right now, but I recall I wasn't waiting for `setEmail()` response, so probably my mistake.

**Comment by Nightsd01** [comment]
@vgeorge if you see this issue again please let me know, otherwise I've been unable to reproduce it.
