### ISSUE TITLE
Execution failed for task ':app:packageAllDebugClassesForMultiDex'

### ISSUE THREAD

**Issue by flobiwankenobi** [OneSignal/react-native-onesignal#45]
Upgrading react-native-onesignal from 1.1.5 to 1.1.6 causes following exception:

`java.util.zip.ZipException: duplicate entry: android/support/v7/appcompat/R$anim.class`

I am running React Native 0.27.2

**Comment by wrousseau** [comment]
This is probably because of this commit : https://github.com/geektimecoil/react-native-onesignal/commit/b7acc4170306d24ca9358c1e213cf764b837750b

I believe the two lines 

```
compile 'com.android.support:appcompat-v7:+'
compile 'com.android.support:support-v4:+'
```

play more or less the same role ?

**Comment by avishayil** [comment]
You are compiling the appcompat twice, I believe. 
Can you please check if you're compiling them in your app build.gradle? or anywhere else in your project? 
Please report back.

**Comment by avishayil** [comment]
Closing this issue for now, please report back when possible and reopen this issue if applicable.

**Comment by zsajjad** [comment]
Facing same issue.
I have appcompat-v7:23.0.1 for facebook signin & google signin. Solution from @wrousseau doesn't solve the problem.

**Comment by avishayil** [comment]
Dupe if #48
