### ISSUE TITLE
Xcode deployment Error "minimum OS too low"

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [OneSignal/react-native-onesignal#450]
Xcode version 8.2.1
one signal version : latest
react-native version  : 0.50.3

![](https://lh3.googleusercontent.com/-NlEfraGCPds/WsKFg57vouI/AAAAAAAACXI/1HaV-mCt2D01Vex9azcgncfAbPYkdeKSwCL0BGAYYCw/h408/2018-04-02.png)

**Comment by Nightsd01** [comment]
@nilaybrahmbhatt This is not an issue with the OneSignal SDK...this is an issue with your deployment target. 

https://stackoverflow.com/questions/27169179/minimum-os-version-mismatch

**Comment by nilaybrahmbhatt** [comment]
@Nightsd01  i know that but what's the minimum OS required for OneSignal SDK ?
