### ISSUE TITLE
Device is not visible (android)

### ISSUE THREAD

**Issue by dmitryshelomanov** [OneSignal/react-native-onesignal#454]
react-native - 0.53
react-native-navigation - 3.1.4

actions
1. run react-native link
2. modify AndroidManifest
3. add keys

Notifications do not come. There are no errors.

**Comment by dmitryshelomanov** [comment]
ps. All keys valid

**Comment by dmitryshelomanov** [comment]
adb logcat error
`OneSignal AppId format is invalid.`
`Example: 'b2f7f966-d8cc-11e4-bed1-df8f05be55ba'`

**Comment by Nightsd01** [comment]
@userbq201 Did you change your app ID in your app's `build.gradle` file?

Better yet, can you just post your `app/build.gradle` file?

**Comment by jkasten2** [comment]
@userbq201 Can you check your `<application>` tag in your `AndroidManifest.xml` for `tools:node="replace"`? If so please remove it, this is the most common issue for this error if you have already confirmed the id is correct.

If you run into other issues after removing this I recommend adding the following to the very top of your `app/build.gradle`:
```gradle
buildscript {
  repositories {
    maven { url 'https://plugins.gradle.org/m2/' }
  }

  dependencies {
    classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.8.2, 0.99.99]'
  }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
```

For more details on this in this thread
https://github.com/geektimecoil/react-native-onesignal/issues/373#issuecomment-378048968
