### ISSUE TITLE
No type or protocol named 'OSSubscriptionObserver'

### ISSUE THREAD

**Issue by danchokobo** [OneSignal/react-native-onesignal#457]
![2018-04-06 17 29 42](https://user-images.githubusercontent.com/16972272/38418931-26ba0bee-39c0-11e8-996f-e202b484f4ec.png)

**Comment by Nightsd01** [comment]
@danchokobo How did you install the RN SDK? What version of the SDK are you using?

If you expand `RCTOneSignal.xcodeproj` subproject in the Libraries section of your project, can you see `libOneSignal.a` and `OneSignal.h`?

**Comment by jmknoll** [comment]
@Nightsd01 I'm running into the same problem after adding the RN Onesignal library. I see both of those files when I expand RCTOneSignal.xcodeproj

I was following the setup instructions [here](https://medium.com/differential/react-native-push-notifications-with-onesignal-9db6a7d75e1e) (might be a bit outdated)

Edit: If I update to the latest OneSignal pod (2.8.2), I get a linker error similar to the one referenced in issue [#243](https://github.com/geektimecoil/react-native-onesignal/issues/243) , with the following output:
)

```
duplicate symbol _OBJC_METACLASS_$_OSRequestSubmitNotificationOpened in:
 ReactNativeApp/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(Requests.o)
User/Library/Developer/Xcode/DerivedData/ReactNativeApp-brdrerntnzqyjacqihvypuvwogtz/Build/Products/Debug-iphonesimulator/libRCTOneSignal.a(Requests.o)
ld: 225 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Nightsd01** [comment]
@jmknoll cocoapods is no longer needed to install the OneSignal SDK. All you need is the npm package.

I would recommend running `pod deintegrate` in your iOS project, and then open the `projectname.xcodeproj`.

**Comment by Nightsd01** [comment]
@danchokobo I am assuming you managed to fix your issue. Closing issue due to no response. If you are still encountering this problem please feel free to respond and I'll be happy to reopen and investigate.

**Comment by loweehahn** [comment]
@Nightsd01 I'm having this issue too. My OneSignal plugin version is 3.1.4. I have `libOneSignal.a` and `OneSignal.h` inside `RCTOneSignal.xcodeproj` and finally, I didn't attempt to update OneSignal with pod.
