### ISSUE TITLE
Events of Google Analytics for Firebase are not integrated when app is closed

### ISSUE THREAD

**Issue by edipoReboucas** [OneSignal/react-native-onesignal#461]
I'm trying integrate Google Analytics for Firebase based on [One Signal Documentation](https://documentation.onesignal.com/docs/google-analytics-for-firebase).

Maybe I have find a bug, when my app is closed, none of events documented on One Signal Documentation are integrated with Firebase.

When I was trying isolate the bug, I create a sample app base on the examples of this repository, and the problem still happen, you can reproduce the error cloning  [my fork](https://github.com/edipoReboucas/react-native-onesignal/tree/firebase_integrate_error), branch `firebase_integrate_error`.

Thinking that the problem maybe can be in Android SDK, I created a sample project, based on examples of android sdk, and at this time, wall works fine, yout can check cloning my [fork of android sdk](https://github.com/edipoReboucas/OneSignal-Android-SDK/tree/firebase_integrate_error), branch `firebase_integrate_error`. 

When debugging react-native sample java sources, I have noted that objects aparently are not initilialized, the `trackFirebaseAnalytics`and `appContext` are `null` when notification is open when app is closed.

```java
  // Users/myuser/.gradle/caches/modules-2/files-2.1/com.onesignal/OneSignal/3.8.3/bc193aa92f805c1e17c56fad02ed94ab5a2890ac/OneSignal-3.8.3-sources.jar!/com/onesignal/OneSignal.java
   // Called when receiving GCM/ADM message after it has been displayed.
   // Or right when it is received if it is a silent one
   //   If a NotificationExtenderService is present in the developers app this will not fire for silent notifications.
   static void handleNotificationReceived(JSONArray data, boolean displayed, boolean fromAlert) {
      OSNotificationOpenResult openResult = generateOsNotificationOpenResult(data, displayed, fromAlert);
      if(trackFirebaseAnalytics != null && getFirebaseAnalyticsEnabled(appContext))
         trackFirebaseAnalytics.trackReceivedEvent(openResult);

      if (mInitBuilder == null || mInitBuilder.mNotificationReceivedHandler == null)
         return;

      mInitBuilder.mNotificationReceivedHandler.notificationReceived(openResult.notification);
   }
```

**Comment by Nightsd01** [comment]
@edipoReboucas Sorry for the delay in getting back to you, I was sick all last week. I'm investigating your issue now and I'll get back to you shortly if you're still experiencing it, at least within 24 hours.

**Comment by edipoReboucas** [comment]
Thanks @Nightsd01 , this bug is a "block" in my task. Reviewing my sample project, I noticed that I did not submit the changes to github in the React Native sample project. I did it now.

**Comment by edipoReboucas** [comment]
Hi @Nightsd01, any luck reproducing this bug?

**Comment by rgomezp** [comment]
Hi @edipoReboucas ,
@Nightsd01 is no longer at OneSignal. Were you able to resolve? Can I close this issue?

**Comment by rgomezp** [comment]
Closing due to no response
