### ISSUE TITLE
Invariant Violation: OneSignal only supports received, opened, and ids events I am getting this error on building app on android 

### ISSUE THREAD

**Issue by hassanshuja** [OneSignal/react-native-onesignal#463]
Invariant Violation: OneSignal only supports `received`, `opened`, and `ids` events

This error is located at:
    in beonews (at renderApplication.js:35)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)

**Comment by lfaz** [comment]
@hassanshuja what version of react native onesignal are u using? I am using ^3.1.4 and for some reason the build does not success on android studio using 2.3.3 gradle and 25.0.0 , I know this is nothing related to your issue!

react native onesignal gradle file:

```
apply plugin: 'com.android.library'

def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android {
    compileSdkVersion safeExtGet('compileSdkVersion', 23)
    buildToolsVersion safeExtGet('buildToolsVersion', '25.0.0')

    defaultConfig {
        // Do NOT change these values here, set them in your android/app/build.gradle instead
        manifestPlaceholders = [onesignal_app_id: '', onesignal_google_project_number: 'REMOTE']
        minSdkVersion safeExtGet('minSdkVersion', 16)
    }
    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile "com.facebook.react:react-native:${safeExtGet('reactNativeVersion', '+')}"

    compile('com.onesignal:OneSignal:3.8.3') {
        // Exclude com.android.support(Android Support library) as the version range starts at 26.0.0
        //    This is due to compileSdkVersion defaulting to 23 which cant' be lower than the support library version
        //    And the fact that the default root project is missing the Google Maven repo required to pull down 26.0.0+
        exclude group: 'com.android.support'
        // Keeping com.google.android.gms(Google Play services library) as this version range starts at 10.2.1
    }

    testCompile 'junit:junit:4.12'
}

// Add the following to the top (Line 1) of your app/build.gradle if you run into any issues with duplicate classes.
// Such as the following error
//   Error: more than one library with package name 'com.google.android.gms.license'

/*
plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.8.1'
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
*/
```

**Comment by lfaz** [comment]
can u post ur gradle files if u using android studio?

**Comment by lfaz** [comment]
error i am getting: 
Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.1) from [com.android.support:cardview-v7:26.0.1] AndroidManifest.xml:25:13-35
	is also present at [com.android.support:support-v4:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:23:9-25:38 to override.

**Comment by Nightsd01** [comment]
@hassanshuja the error says what it means, somewhere in your project you must be subscribing to an unsupported event type. Can you search your codebase for `OneSignal.addEventListener` and tell me what types of events you are subscribing to?

**Comment by Nightsd01** [comment]
Closing this issue due to no response @hassanshuja. If you are still encountering this issue please feel free to reply...

**Comment by hassanshuja** [comment]
sorry for late response but i have resolved the issue by deleting an old supportive event so after that it works fine.
