### ISSUE TITLE
Bring cocoapods support back

### ISSUE THREAD

**Issue by danieljvdm** [OneSignal/react-native-onesignal#465]
Going through old commits I can see that there used to be a podspec but it has since been removed. If you are using React installed via cocoapods in a Swift project (with !use_frameworks) there is no other way - that I know of - to link this library other than through cocoapods.

Here is a working podspec that I'd be happen to open a PR for:

```
require 'json'
package_json = JSON.parse(File.read('package.json'))

Pod::Spec.new do |s|

  s.name           = "react-native-onesignal"
  s.version        = package_json["version"]
  s.summary        = package_json["description"]
  s.homepage       = "https://github.com/geektimecoil/react-native-onesignal"
  s.license        = package_json["license"]
  s.author         = { package_json["author"] => package_json["author"] }
  s.platform       = :ios, "7.0"
  s.source         = { :git => "#{package_json["repository"]["url"]}.git", :tag => "v#{s.version}" }
  s.source_files   = 'ios/RCTOneSignal/*.{h,m}'
  s.dependency 'React'
  s.dependency 'OneSignal', '2.8.2'

end
```

**Comment by Nightsd01** [comment]
@danieljvdm the iOS SDK includes a static iOS OneSignal library. If you try to include the native iOS SDK as a dependency wont you see a duplicate symbols issue?

In any case, I didn’t realize there was a way to use this SDK via cocoapods, that’s my mistake. I’ll be happy to add it back tomorrow.

**Comment by danieljvdm** [comment]
@Nightsd01  thanks for the response, sorry for taking a while to get back to you. You're right about the duplicate symbols issue, I'm not really sure if there's a way to get around that. I think it's safe though, judging by the code I saw. What are you thoughts on that?

I suppose ideally this library wouldn't package the iOS onesignal SDK in it but I'm guessing there's no way to do that with `react-native link`.

If it's safe (but just throws warnings) to use the cocoapods method, should we just add it back in with a note in readme?

**Comment by danieljvdm** [comment]
I just opened a PR for this

**Comment by Nightsd01** [comment]
Thanks for the pr @danieljvdm , merged!

**Comment by ProteanDev** [comment]
@danieljvdm Do this still work with react-native-onesignal version ^3.2.5 and Xcode 9.x.x?
