### ISSUE TITLE
Onesignal run to localhost ?

### ISSUE THREAD

**Issue by eceliknet** [OneSignal/react-native-onesignal#466]
Hi, onesignal localhost runing ???

**Comment by Nightsd01** [comment]
@ankaramedya ...? Do you mean a local instance of the OneSignal backend server? It’s closed source, sorry. 

Closing this issue due to lack of detail. It is generally in bad taste to open an issue with 4 words.

**Comment by eceliknet** [comment]
I want to work through the local server. but I did not do it. Could you help
