### ISSUE TITLE
Checking if app notification is enabled on Android

### ISSUE THREAD

**Issue by James2516** [OneSignal/react-native-onesignal#468]
Why [.checkPermissions](https://www.npmjs.com/package/react-native-onesignal#check-push-notification-permissions-ios-only) is only available for iOS?

Notification permission checking is added to Android in 2016: https://developer.android.com/reference/android/support/v4/app/NotificationManagerCompat.html#areNotificationsEnabled()

**Comment by Nightsd01** [comment]
You can use `getPermissionSubscriptionState()` just like with iOS.
