### ISSUE TITLE
iOS cold start onOpened not triggered (Again!)

### ISSUE THREAD

**Issue by haiyamicode** [OneSignal/react-native-onesignal#472]
Pretty much the same issue as #332 , but for me now the suggested solutions do not work anymore. No matter how early I call `addEventListener` (right at the start of App.js), my onOpened callback does not get called. I tried adding `OneSignal.configure` before it and tried many ways, still the same.
This only happens on **iOS** by the way.

**Comment by Nightsd01** [comment]
@wilonth I am not able to reproduce your issue, whenever I try it with our demo/example project, it works just fine. You are using onesignal-react-native version 3.1.4 correct?

How do you know for sure that the `opened` event function is never firing? 

Can you send some of the code you are using...?

**Comment by haiyamicode** [comment]
Nvm I made a mistake. I put OneSignal's call at the very end of didFinishLaunchingWithOptions and that was wrong.
