### ISSUE TITLE
Callback when user is coming to app from notification

### ISSUE THREAD

**Issue by sunnymopada** [OneSignal/react-native-onesignal#473]
react-native-fcm provides a method named FCM.getInitialNotification() by which we can know whether the user opened the app from notification or opened normally. Based on it we are taking decision for deeplinking. I'm not sure how to achieve similar thing using onesignal, As one signal onOpened firing when the user is coming from notification, not firing when the user came normally.

```
   FCM.getInitialNotification().then((notif) => {
      // User came to app from the notification when app is killed
      if (notif !== undefined && notif !== null && notif.notification_type) {
        //Take user to deeplinking screen based on notification_type
      } else {
        //Take user to home screen
      }
    })
```

**Comment by Nightsd01** [comment]
You might consider adding a Boolean variable `didOpenFromNotification`. It would normally be `false` but in the `opened` event listener you could set to `true`. You can then check the value of the flag in the `componentDidMount()` method, or use a timer to delay it.

In any case, there's many ways you could approach this, it is _not_ an issue with the SDK.
