### ISSUE TITLE
I cannot install react-native-onesignal using pod install

### ISSUE THREAD

**Issue by lfaz** [OneSignal/react-native-onesignal#476]
Pod file I included:

pod 'react-native-onesignal', 
    :podspec => "../node_modules/react-native-onesignal/react-native-onesignal.podspec",
    :path => '../node_modules/react-native-onesignal'

Error installing react-native-onesignal
[!] /usr/local/bin/git clone git+https://github.com/geektimecoil/react-native-onesignal.git.git /var/folders/hp/96xj1gkj76s_x7hbh3rd2vs80000gn/T/d20180426-27872-elbnyw --template= --single-branch --depth 1 --branch v3.1.4

Cloning into '/var/folders/hp/96xj1gkj76s_x7hbh3rd2vs80000gn/T/d20180426-27872-elbnyw'...
fatal: Unable to find remote helper for 'git+https'

Any idea?

**Comment by Nightsd01** [comment]
Should be fixed in #469

**Comment by lfaz** [comment]
@Nightsd01 how it shuould be fixed? I didn't see or understand how!
