### ISSUE TITLE
ERROR: _reactNative.NetInfo.getConnectionInfo is not a function

### ISSUE THREAD

**Issue by facuescobar** [OneSignal/react-native-onesignal#477]
**Description:**
https://github.com/geektimecoil/react-native-onesignal/blob/master/index.js#L59

This line is causing this error because NetInfo is not available in the current RN version.

Can you add conditions to this extra functionality? 
If I comment this code the issue is fixed: https://github.com/geektimecoil/react-native-onesignal/blob/master/index.js#L47-L67

**Environment**
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
    "react-native-onesignal": "github:geektimecoil/react-native-onesignal#master",

**Steps to Reproduce Issue:**
Instal RN 0.45.1 version and "react-native-onesignal": "github:geektimecoil/react-native-onesignal#master" and the app will display that error.

<img width="200" alt="screen shot 2018-04-26 at 12 48 07 pm" src="https://user-images.githubusercontent.com/6618677/39317280-9176c2c4-4951-11e8-994c-633a84535f1c.png">

**Comment by Nightsd01** [comment]
@facuescobar  React-Native 0.45.1 was released over a year ago. Does this issue occur if you update to a more recent version of react-native?

**Comment by Nightsd01** [comment]
@facuescobar I have done some more investigating, and it appears like usage of the NetInfo API is no longer needed in our SDK, so I went ahead and removed it. Please let me know if you encounter any other issues.

**Comment by facuescobar** [comment]
@Nightsd01 a RN upgrade wasn't an option for us because it required a lot of things, and we didn't have the time. 

Thanks for this update!
