### ISSUE TITLE
react native ios 8.2 action buttons not showing after adding notification service extension

### ISSUE THREAD

**Issue by Assiance** [OneSignal/react-native-onesignal#478]
**Description:**
Before adding the notification service extension action buttons would work but rich media would not.
After adding the notification service extension neither action buttons nor rich media work.

**Environment**
ios: 8.2
react-native: 47.1
react native onesignal: 3.1.4

1. How did you add the SDK to your project (eg. npm)
I added onesignal using npm

**Steps to Reproduce Issue:**
  1. Install the OneSignal SDK using npm into your project
  2. Initialize the SDK in the iOS AppDelegate
  3. Added Notification Service Extension
  4. Attempt to receive a push notification

When going through the docs the only thing I was unsure about is a possible typo when adding the notification service extension. The docs say "Open NotificationServiceExtension.m or NotificationService.swift and replace the whole file contents with the code below:" I am thinking it means NotificationService.m  and not NotificationServiceExtension.m because I can't find a NotificationServiceExtension.m file anywhwere.

**Comment by Nightsd01** [comment]
Apple added rich media support (push notification extension service) in iOS 10. 

iOS 8.2 would not support rich media attachments.

**Comment by Assiance** [comment]
@Nightsd01 The issue is mainly about action buttons are you saying that action buttons will not work before iOS10?
