### ISSUE TITLE
errors in generating signed APK.

### ISSUE THREAD

**Issue by seokgyo** [OneSignal/react-native-onesignal#48]
Hi,

starting from v1.1.6, generating signed APK for android emits the following error:

:app:dexRelease
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Landroid/support/v7/appcompat/R$anim;
Unknown source file :   at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file :   at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file :   at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file :   at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file :   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file :   at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file :   at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file :   at com.android.dx.command.Main.main(Main.java:106)

:app:dexRelease FAILED

Any Idea?

Thanks.

**Comment by jkasten2** [comment]
`Multiple dex files define ... android/support/v7/appcompat` means there is 2 copies of the Android Support Library v7 in your project. You can try changing the 2 lines in [build.gradle](https://github.com/geektimecoil/react-native-onesignal/blob/master/android/build.gradle#L36-L37) 
From:

```
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:support-v4:23.4.0'
```

TO:

```
    compile 'com.android.support:appcompat-v7:+'
    compile 'com.android.support:support-v4:+'
```

**Comment by andreibarabas** [comment]
I tried the suggested fix, but no luck. I get the same error (even in Debug)

```
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Landroid/support/v7/appcompat/R$anim;
Unknown source file :   at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file :   at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file :   at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file :   at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file :   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file :   at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file :   at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file :   at com.android.dx.command.Main.main(Main.java:106)

```

here is the build.gradle from onesignal

```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:+'
    compile 'com.android.support:support-v4:+'
    compile 'com.facebook.react:react-native:+'
    compile 'com.onesignal:OneSignal:2.+@aar'
    compile 'com.google.android.gms:play-services-gcm:+'
    compile 'com.google.android.gms:play-services-analytics:+'
    compile 'com.google.android.gms:play-services-location:+'
}
```

**Comment by jkasten2** [comment]
@andreibarabas You can try removing the following line.

```
compile 'com.android.support:appcompat-v7:+'
```

If that doesn't work list all the other plugins you have in your project, one of them must be conflicting.

**Comment by andreibarabas** [comment]
@jkasten2 , i removed the line. the same issue. I removed one signal completely, and it compiles.

here is the **package.json** file

```
  "dependencies": {
    "merge": "^1.2.0",
    "merge-recursive": "0.0.3",
    "path": "^0.12.7",
    "qs": "^6.2.0",
    "react": "15.0.2",
    "react-native": "^0.26.1",
    "react-native-fs": "^1.4.0",
    "react-native-gifted-spinner": "0.0.4",
    "react-native-onesignal": "^1.1.4",
    "react-native-pdf-view": "^0.3.2",
    "react-native-router-flux": "^3.26.16",
    "react-native-vector-icons": "^2.0.2",
    "tcomb-form-native": "^0.5.0",
    "url": "^0.11.0",
    "util": "^0.10.3"
  },
```

in the meantime, i'm removing each plugin to determine with whom it is conflicting

**Comment by andreibarabas** [comment]
Very strange... in the /node_modules/react-native-onesignal/android/build/intermediates/exploded-aar/com.android.support folder I found two folders appcompat-v7 and appcompat and in appcompat-v7 there where 3 subfolders with different versions.

I removed all such folders, and the build moved on but crashed at **recyclerview** with

`com.android.dex.DexException: Multiple dex files define Landroid/support/v7/recyclerview/R$attr;`

Then I removed the recyclerview folders from a similar path as above, and build advanced to crash at 

`com.android.dex.DexException: Multiple dex files define Lcom/facebook/drawee/R$attr;`

then at

`com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/R$anim;`

then, I removed the entire module from node_modules, and run npm install again and installed a fresh copy of 

react-native-onesignal@1.1.7 

and looking at what installed in /node_modules/react-native-onesignal/ I saw that there is a build folder in android/build populated with multiple appcompat folders and versions.

I removed the /node_modules/react-native-onesignal/android/build folder, **and it worked**. So, no need to  #49 , but rather make sure you exclude the build folder from the package when you ship it.

**Comment by avishayil** [comment]
This solution to remove the build folder when shipping seems little hacky to me, since building again or sending the app through a CI would might cause this issue again.

Do you have a repo that can re-produce this issue?

**Comment by avishayil** [comment]
Actually now I tried to run my app without those two lines, it runs well.
Should be ok now.
@andreibarabas @seokgyo @jkasten2 please confirm?

**Comment by baptistejamin** [comment]
It's because your Android app is running with a 23 SDK, but if you upgrade your app with a new react native version, it's should run with SDK version 25, and that's producing an error.

**Comment by avishayil** [comment]
@mywaystar I'm with RN 0.28, or you haven't meant to me?

**Comment by baptistejamin** [comment]
Did you upgraded your android folder too ?
Le 26 juin 2016 6:53 PM, "Avishay Bassa" notifications@github.com a
écrit :

**Comment by avishayil** [comment]
I found what the problem is. You need to upgrade your gradle version to 2.10.
Create in your /android/ the folder /gradle/wrapper and in this folder create gradle-wrapper.properties file with the following content:

``` javascript
#Wed Jun 01 12:37:05 IDT 2016
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https://services.gradle.org/distributions/gradle-2.10-all.zip
```

Then, in your /android/build.gradle file , upgrade the classpath:

``` javascript
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
```

then it runs smoothly.

I'll add this documentation to the readme.

**Comment by avishayil** [comment]
Readme updated.

**Comment by avishayil** [comment]
@seokgyo @andreibarabas @mywaystar

Please confirm it's working after the latest documentation change.
Thanks!

**Comment by seokgyo** [comment]
@avishayil 
Now everything works well for me. Thanks very much. 😄

**Comment by andreibarabas** [comment]
1.1.8 did the trick. Thanks

**Comment by avishayil** [comment]
Happy to hear that :), closing issue.

**Comment by bendellarocco** [comment]
I installed 1.1.8 and am still seeing this issue.  I tried the solution @avishayil suggestion and received new errors.  Is there a step I am missing in the process?  Thank you for any help you can provide.
