### ISSUE TITLE
symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by kennym** [OneSignal/react-native-onesignal#5]
I am getting the following error when trying to build the sample project and any project with the library:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_OneSignal", referenced from:
      objc-class-ref in libRCTOneSignal.a(RCTOneSignal.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any ideas on how to fix this?

**Comment by kennym** [comment]
So, I just submitted a pull request which fixes that.

**Comment by durul** [comment]
I was able to fix it by appending $(inherited) to Other Linker Flags in my target.

**Comment by johanleroch** [comment]
Hi, I have the same problem and your solution @durul didn't work for me :/

Here the versions I use in my project:
react-native-cli: 2.0.1
react-native: 0.53.3
react-native-onesignal: 3.1.4


<img width="800" alt="capture d ecran 2018-04-27 a 19 45 52" src="https://user-images.githubusercontent.com/7213352/39376931-abb1d342-4a53-11e8-80fa-e63d3e7bcf3a.png">
<img width="496" alt="capture d ecran 2018-04-27 a 19 45 30" src="https://user-images.githubusercontent.com/7213352/39376932-abcac0b4-4a53-11e8-87cc-23e1e0047e26.png">

**Comment by nicubarbaros** [comment]
I can't Archive my project in XCode. 
Stuck here

```

Showing All Errors Only
  "_OBJC_CLASS_$_RCTOneSignalExtensionService", referenced from:
  objc-class-ref in NotificationService.o
  Id: symbol(s) not found for architecture arm64
```

**Comment by clementinoux** [comment]
> Hi, I have the same problem and your solution @durul didn't work for me :/
> 
> Here the versions I use in my project:
> react-native-cli: 2.0.1
> react-native: 0.53.3
> react-native-onesignal: 3.1.4
> 
> <img alt="capture d ecran 2018-04-27 a 19 45 52" width="800" src="https://user-images.githubusercontent.com/7213352/39376931-abb1d342-4a53-11e8-80fa-e63d3e7bcf3a.png">
> 
> <img alt="capture d ecran 2018-04-27 a 19 45 30" width="496" src="https://user-images.githubusercontent.com/7213352/39376932-abcac0b4-4a53-11e8-87cc-23e1e0047e26.png">

@johanleroch Hi, finally any solution for this issue ?

**Comment by denorro** [comment]
@clementinoux Did you find a solution for this? If so, could you share?

**Comment by JJMoon** [comment]
I am upgrading RN from 0.59.10 to 0.61.5, and having same problem. 
react-native-onesignal version is 3.6.2.
``` 
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RCTOneSignalExtensionService", referenced from:
      objc-class-ref in NotificationService.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation
```
This part of the document mentions about it, but doesn't help.
https://documentation.onesignal.com/docs/troubleshooting-react-native#ios-installation

**Comment by jkasten2** [comment]
@JJMoon Did you use Objective-C or Swift when you created your `OneSignalNotificationServiceExtension` target? I recommend using `Objective-C` unless you are more familiar with Swift and need to customize the logic.

Also recommend switching to using Cocoapods if you haven't already, this simplifies a lot of the linking steps that could go wrong.

If you continue to see issues please open a new issue with more details on your project setup.
