### ISSUE TITLE
(v3.2.1) (iOS) No users on dashboard & Not receiving notifications  

### ISSUE THREAD

**Issue by nicastelo** [OneSignal/react-native-onesignal#502]
**Description:**
I can't get v3.2.1 working. I set up the app, followed the documentation and checked the app id several times. The weird thing is that I don't even see the Users in the OneSignal dashboard.
I tried to initialize the module in the both ways (JS and AppDelegate).
Finally I tried to downgrade to v3.1.4, I just replaced the version in the package.json, ran `yarn` and it worked.

**Environment**
Version v3.2.1
SDK installed using yarn, and linked with `react-native link` (Not pods)
RN v0.55.3
OS: iOS

**Steps to Reproduce Issue:**
1. Install the OneSignal SDK using yarn into your project `yarn add react-native-onesignal`
2. Run `react-native link react-native-onesignal`
3. Set up OneSignal app
2. Initialize the SDK in the iOS AppDelegate or with `OneSignal.init()` in the JS code
3. Attempt to receive a push notification

**Anything else:**

The app didn't crash nor throw any errors.
I debugged the ids listener and I noticed that it doesn't gets executed every time I open the app, just sometimes (don't know if that's the correct behavior).
I didn't try it on Android.

**Comment by rafaelribeiros** [comment]
Same here.

**Comment by Nightsd01** [comment]
Hi @nicastelo 

Can you verify that if you go to the Xcode project settings, `libRCTOneSignal.a` shows up as a dependency in the Linked Libraries section?

**Comment by Nightsd01** [comment]
Also, I suspect this is an issue with Xcode subproject dependencies vs. cocoa pod dependencies.

Can you tell me if your project looks like this?

![alt text](http://www.hesse.io/testapp.jpg)

**Comment by tpedersen123** [comment]
@Nightsd01 I have the same issue and can verify that my setup is as you described.

![image](https://user-images.githubusercontent.com/11134247/40020974-dec90336-57c3-11e8-8016-83149e2398b4.png)

**Comment by Nightsd01** [comment]
@tpedersen123 Can you call `OneSignal.setLogLevel(6, 0)` before you call `OneSignal.init("your_app_id")` and tell me if you see any errors printed to the console?

Also, let's check a few things:

0. You're not using Expo right?
1. You are running on a real iOS device, correct? Please note that Apple does not support push notifications in the iOS simulator
2. You went to Xcode Project Settings > Capabilities, and enabled Push Notifications?
3. Where in your react app are you calling `OneSignal.init()` from? 
4. Can you see if this issue occurs in the previous version (3.1.4)? If you downgrade to 3.1.4, note that this older version doesn't support JS initialization so you'll have to add code to the native Objective-C AppDelegate as [described here](https://github.com/geektimecoil/react-native-onesignal/blob/732491fece1fa92946ca6dacf173af28a2b2e618/README.md)

**Comment by tpedersen123** [comment]
0. You're not using Expo right?
Nope
1. You are running on a real iOS device, correct? Please note that Apple does not support push notifications in the iOS simulator
Yes
2. You went to Xcode Project Settings > Capabilities, and enabled Push Notifications?
Yes
3. Where in your react app are you calling OneSignal.init() from?
In our "root" component in ComponentWillMount
4. Can you see if this issue occurs in the previous version (3.1.4)? If you downgrade to 3.1.4, note that this older version doesn't support JS initialization so you'll have to add code to the native Objective-C AppDelegate as described here
It worked fine before the updrage to 3.2.*, we have had this app running for months now on 3.1.2 working just fine.
Only a recent addition of AWS modules forced us to upgrade because of the collision with Google Play Services (GMS module)

The code works fine on Android with the exception of "onIds()" event listener not being called.

I tried your example project on Android, that doesn't trigger "onIds()" to be called either as far as I can see.

**Comment by tpedersen123** [comment]
Here are the init lines of OneSignal - the `kOSSettingsKeyAutoPrompt` works to suppress permission prompt, so `init()` IS called.
We prompt for permissions later on.

``` OneSignal.setLogLevel(6, 0);
    OneSignal.init('top secret', {
      kOSSettingsKeyAutoPrompt: false,
    });
    OneSignal.inFocusDisplaying(0);
    OneSignal.addEventListener('opened', this.onOpened)
    OneSignal.addEventListener('ids', this.onIds)
```

**Comment by Nightsd01** [comment]
@tpedersen123 When you do eventually prompt for push notifications permission from the user, does the prompt actually show up? Try uninstalling the app and reinstalling it, and make sure the push notification permission prompt actually shows up.

Try a clean install of your app, accept push notification permission, and then can you send me the entire logs from Xcode console?

PS: Sorry you're seeing this issue, thanks for working with me to troubleshoot!

**Comment by tpedersen123** [comment]
@Nightsd01 Yes, the prompt shows up every time.

I don't get any OneSignal logs in the console? I did add `OneSignal.setLogLevel(6, 0);`

**Comment by tpedersen123** [comment]
Sorry, was looking in the wrong place. Logs coming up shortly

**Comment by tpedersen123** [comment]
![image](https://user-images.githubusercontent.com/11134247/40024950-4a0065e8-57d0-11e8-81e7-3c3a8b769dd4.png)

I only get these after a call to
`[27 <private> stream, pid: 683, url: https://onesignal.com/api/v1/apps/top-secret-key/ios_params.js, tls] cancelled
`

**Comment by Nightsd01** [comment]
@tpedersen123  There really should be more logs than that - you are calling `setLogLevel(6, 0)` **before** calling `init()` right?

**Comment by tpedersen123** [comment]
Yes, but I am having trouble getting the console logs. Will try again tomorrow.
Feel free to email me on tpedersen ( at) gmail.com to avoid messing up this issue discussion :-)

**Comment by tpedersen123** [comment]
@Nightsd01 
I tried removing `kOSSettingsKeyAutoPrompt` to trigger permission prompt right away. 
That gave me this output
`WARNING: Attempted to send an event (OneSignal-idsAvailable) when no listeners were set.`
and `onIds(device)` was called but `device` was null

**Comment by rafaelribeiros** [comment]
Using `OneSignal.configure()` after `OneSignal.init()` works for me.

**Comment by hhunaid** [comment]
Related #503

**Comment by Nightsd01** [comment]
@tpedersen123 Can you please send your logs? Just for the first ~10 seconds after launching your app.

Also, can you tell me where in your project you are calling `OneSignal.init()` from, where you are adding OneSignal event listeners, etc?

**Comment by neo125874** [comment]
@nicastelo hi, did you solve this issue?

**Comment by Nightsd01** [comment]
Hi everyone - this issue has been resolved in a new PR (#512). We expect to have this merged and a new update released within the next hour or two. Thanks for your patience!

**Comment by Nightsd01** [comment]
@nicastelo @tpedersen123 The new update (3.2.3) has been released and should fix this issue. Please feel free to let me know if you see this issue (or other issues) again and I'll be happy to investigate.

**Comment by tpedersen123** [comment]
@Nightsd01 Everything works now - I love you, man :-)
Thx!
