### ISSUE TITLE
(v3.1.4) (iOS) In debug mode app crashes

### ISSUE THREAD

**Issue by tavriaforever** [OneSignal/react-native-onesignal#504]
**Description:**
The last version didn`t work for me as I mention in https://github.com/geektimecoil/react-native-onesignal/issues/503 so I use 3.1.4 and it works, but not in all versions of ios. 

If I launch app in simulator with ios 11 – everything `ok`, but if I run app in simulator with ios 8.1 app crashed.

It reproduced only in debug mode, in release mode – app works like usual without any errors.

![monosnap 2018-05-14 14-10-59](https://user-images.githubusercontent.com/975906/39994056-c24f00f4-5780-11e8-8cb7-2bcf47bb06c7.png)

![main m 2018-05-14 14-03-57](https://user-images.githubusercontent.com/975906/39993777-b56d9824-577f-11e8-90d9-eb3767af26bf.png)

**Environment**
1. OneSignal React-Native SDK 3.1.4
2. How did you add the SDK to your project (eg. npm): npm i --save react-native-onesignal@3.1.4
3. react-native 0.55.3
4. nodejs 8.4.0
5. xcode 9.3.0

**Steps to Reproduce Issue:**
1.  run `react-native run-ios` by default open iPhone 6 with ios 8.1 in simulator

**ios code**
appDelegate.h
```
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import <UIKit/UIKit.h>
#import <RCTOneSignal.h>

@interface AppDelegate : UIResponder <UIApplicationDelegate>

@property (nonatomic, strong) UIWindow *window;
@property (strong, nonatomic) RCTOneSignal* oneSignal;

@end
```

appDelegate.m
```
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@implementation AppDelegate

@synthesize oneSignal = _oneSignal;

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.oneSignal = [[RCTOneSignal alloc] initWithLaunchOptions:launchOptions appId:@"ff5ba423-ea78-4b29-8b91-9282b9f143eb"];
  
  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"rbtse"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  return YES;
}

@end
```

So with onesignal push I couldn\`t use default way to start develop react-native app with `react-native run-ios`.

Maybe I missed something?

**Comment by Nightsd01** [comment]
@tavriaforever I am not able to reproduce this issue running a debug scheme with the iOS 8.1 iPhone 6 simulator, the SDK launches and the app runs just fine...? There really should be no difference between the Debug and Release schemes except some additional compiler optimizations.

Why are you running in debug vs. release schemes, do you have environment/compiler flags or something?

I understand you are having a null user ID issue in version 3.2.1 of the SDK, but does 3.2.1 have this same issue crashing in the simulator as well?

**Comment by tavriaforever** [comment]
@Nightsd01 I could send my project to you where all issues from 3.2.1 and 3.1.4 exist. I have just started it. Please write me on my email.

**Comment by Nightsd01** [comment]
The [new update (3.2.3)](https://github.com/geektimecoil/react-native-onesignal/releases/tag/3.2.3) has been released and should fix this issue. @tavriaforever Please feel free to let me know if you see this issue (or other issues) again and I'll be happy to investigate. 

By the way, thank you so much for sending me your project - it was instrumental in being able to reproduce this problem!
