### ISSUE TITLE
Opened event calling twice on notification open

### ISSUE THREAD

**Issue by hiteshagja** [OneSignal/react-native-onesignal#505]
In the recent version, the `opened` event calling twice on notification open. It was working fine in the previous releases/versions. 

`
OneSignal.addEventListener('opened', this.onOpened);
`

I am checking on Android device.

**Comment by Nightsd01** [comment]
@hiteshagja Are you saying this issue only occurs in Android...?

Also, how do you know that the event is getting called twice? I have attempted to reproduce your issue but it only gets fired once.

Can you please provide a bit more detail on how you are reproducing this issue? What steps should we follow...?

**Comment by Nightsd01** [comment]
Please provide more information. For example, does this only occur when the app is open (in the foreground), background, closed completely, etc.?

Also, please add a `console.log` statement in your code where you are calling `OneSignal.addEventListener` to make sure you are not adding the event listener twice...?

**Comment by Nightsd01** [comment]
Hi @hiteshagja ,

Thanks for reporting this issue, after digging a bit deeper, this issue was caused when we introduced JS initialization in 3.2.0.

I've created a pull request (#506)  to fix this problem and it should be included in an update either later today or tomorrow!

**Comment by Nightsd01** [comment]
#506 has been merged - thanks for reporting this issue @hiteshagja

**Comment by hiteshagja** [comment]
Thanks @Nightsd01

**Comment by jigaryadav** [comment]
@Nightsd01  thankx
