### ISSUE TITLE
Problem if exist Two notification Not OPEN notification ??

### ISSUE THREAD

**Issue by abdelhakimkotti** [OneSignal/react-native-onesignal#507]
if exist one notification => Open notification 
if exist two notification => First open , second not open ??
if exist three notification => First open , second not open , three not open ??

**Comment by Nightsd01** [comment]
@abdelhakimkotti please explain what you mean in a bit more detail, perhaps post screenshots...?

**Comment by abdelhakimkotti** [comment]
if exist multiple notifications.
first notification open,  and other notification no open, if click ??

**Comment by Nightsd01** [comment]
@abdelhakimkotti I am having a hard time understanding what you're saying. 

You didn't follow the issue template either, posted no details....

I am closing this issue due to a lack of information - please either post more info and I'll be happy to reopen and investigate

**Comment by abdelhakimkotti** [comment]
![a](https://user-images.githubusercontent.com/24668048/40228667-ce286954-5a89-11e8-8265-1119ced936da.png)
Any solution ??
