### ISSUE TITLE
Is onesignal using same token as in fcm?

### ISSUE THREAD

**Issue by hyochan** [OneSignal/react-native-onesignal#508]
I had react-native-fcm project previously and want to use react-native-onesignal. My server is integrating fcm services fetching user's token. My question is, is `onesignal` using the same token as is in `firebase` or they use different one?

**Comment by Nightsd01** [comment]
@dooboolab if your project is using FCM then OneSignal will use the FCM token, correct

**Comment by hyochan** [comment]
@Nightsd01 reopening this issue because I have another question. My ios app was integrated with fcm module too previously. Will ios use fcm token too? Because I am testing it right now, but push is not received from my backend. I want to make myself clear, if ios is using the fcm token too.
