### ISSUE TITLE
Multiple dex files define

### ISSUE THREAD

**Issue by zsajjad** [OneSignal/react-native-onesignal#51]
RN v0.24.1

```
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/auth/api/signin/internal/zzk;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/auth/api/signin/internal/zzk;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

```

android/app/build.gradle

```
dependencies {
    compile project(':react-native-facebook-account-kit')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.google.android.gms:play-services-location:8.3.0"
    compile "com.facebook.react:react-native:+"
    compile("com.google.android.gms:play-services-analytics:8.3.0"){
      force = true
    }
    compile project(':react-native-onesignal')
    compile project(':react-native-google-analytics-bridge')
    compile project(":react-native-share")
    compile project(":react-native-vector-icons")
    compile project(':react-native-android-statusbar')
    compile project(":react-native-facebook-login")
    compile project(":react-native-google-signin")
    compile project(":react-native-image-picker")
}
```

**Comment by bendellarocco** [comment]
Some people seemed to solve this issue using the solution here: https://github.com/geektimecoil/react-native-onesignal/issues/48

**Comment by avishayil** [comment]
@zsajjad try to include the following in your app `build.gradle` file:

``` gradle
android {
   ...
   defaultConfig {
      ...
      multiDexEnabled true
   }
}
```

**Comment by bendellarocco** [comment]
@avishayil I tried that when I first got this issue and that did not solve it.

**Comment by bendellarocco** [comment]
I noticed other users said they only started getting this error after a specific version of this repository.  Is there a change list or release notes so I can see if my app will be strongly effected if I downgrade?

**Comment by avishayil** [comment]
Nothing I can think of, but you can see the commits and the version bumps
on NPM accordingly. I'll debug older RN versions when I'll get the chance.

**Comment by bendellarocco** [comment]
@avishayil I am on 25.1 I believe.  If you need any assistance from me please let me know.  I am actively working on this as well.  Also I was speaking about release notes for this repository.  Not react.  Sorry if I caused confusion.

**Comment by avishayil** [comment]
@bendellarocco Can you send me a link to your repository project?

**Comment by bendellarocco** [comment]
@avishayil It is a private repository.  I will make a branch and invite you.  Is that fine?

List of Solutions I have Tried:
Pulled 1.1.8
Added multiDexEnabled true
Added the updates to android/gradle/wrapper/gradle-wrapper.properties and the updates to android/build.gradle which gave me a new error unrelated to this one

**Comment by avishayil** [comment]
Sure.

On Tue, Jun 28, 2016 at 12:02 AM, Ben Dellarocco notifications@github.com
wrote:

> @avishayil https://github.com/avishayil It is a private repository. I
> will make a branch and invite you. Is that fine?
> 
> List of Solutions I have Tried:
> Pulled 1.1.8
> Added multiDexEnabled true
> Added the updates to android/gradle/wrapper/gradle-wrapper.properties and
> the updates to android/build.gradle which gave me a new error unrelated to
> this one
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/geektimecoil/react-native-onesignal/issues/51#issuecomment-228874552,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAyekGDCqtdzjbn2XIM7niLYZO-tSBvoks5qQDp2gaJpZM4I-8Tr
> .

## 

בברכה,
אבישי בסה.
All The Best,
Avishay Bassa,
Israel Mobile: +972 (54) 928-0802
US Mobile: +1 (501) 232-1231
E-Mail/G-Talk: avishay.il@gmail.com
Skype: avishayil

**Comment by bendellarocco** [comment]
@avishayil invited you.  also set up a "oneSignalTesting" branch so our development wont impact you

**Comment by avishayil** [comment]
@bendellarocco I was able to compile your repository, please see my comments.
I will update the documentation according to the things I saw there and that needed to pay attention to.

**Comment by avishayil** [comment]
@zsajjad Please take a look on the FAQ section and see if this can solve the problem for you. If not, i'd be happy to take a look at your app repository and try to help.

**Comment by avishayil** [comment]
If anyone would like to add on this or issue is recurring, please re-open this. Thanks!
