### ISSUE TITLE
Is ios using fcm token too?

### ISSUE THREAD

**Issue by hyochan** [OneSignal/react-native-onesignal#513]
@Nightsd01 reopening this issue because I have another question. My ios app was integrated with fcm module too previously. Will ios use fcm token too? Because I am testing it right now, but push is not received from my backend. I want to make myself clear, if ios is using the fcm token too.

Couldn't reopen the [issue](https://github.com/geektimecoil/react-native-onesignal/issues/508) so I am posting for new issue. Receiving well in android device but not in ios. Maybe ios is not using fcm token. Therefore, it feels like I need to change my server code to onesignal's. Am I right?

**Comment by Nightsd01** [comment]
Hi @dooboolab 

OneSignal does not support using FCM to send push notifications to iOS. There's really no point in it if you're using OneSignal to do what is essentially the same thing.
