### ISSUE TITLE
usage documentation is missing

### ISSUE THREAD

**Issue by sinapcs** [OneSignal/react-native-onesignal#514]
**Description:**

Hi. I don't want to report an issue of sdk. I can not find usage documentation like sending p2p notifications or setting tags.yesterday it was here:
https://documentation.onesignal.com/v5.0/docs/react-native-sdk-setup

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by Nightsd01** [comment]
Hi @sinapcs 

We moved the usage docs to the SDK reference section, sorry if that caused any confusion

https://documentation.onesignal.com/docs/react-native-sdk

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sinapcs** [comment]
Thanks @Nightsd01. it's better to add this link to end of previous page. maybe some other people looking for it too.
