### ISSUE TITLE
react native onesignal android push token is null

### ISSUE THREAD

**Issue by adirzoari** [OneSignal/react-native-onesignal#517]
I'm using ` react-native-onesignal": "^3.2.3` and I'm getting push token null in 
`
    onIds = (device) => {
        console.log('Device info: ', device)
    }`

androidManifest.xml
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.moonsite.sqlivetrivia">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.CAMERA"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
        <intent-filter>
          <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
      </service>
      <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
        <intent-filter>
          <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
        </intent-filter>
      </service>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />

        <receiver android:name="io.invertase.firebase.notifications.RNFirebaseNotificationReceiver"/>
          <receiver android:enabled="true" android:exported="true"  android:name="io.invertase.firebase.notifications.RNFirebaseNotificationsRebootReceiver">
          <intent-filter>
              <action android:name="android.intent.action.BOOT_COMPLETED"/>
              <action android:name="android.intent.action.QUICKBOOT_POWERON"/>
              <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
              <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
              </receiver>
          
        
          <activity
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:windowSoftInputMode="adjustResize"
            android:launchMode="singleTop" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
          </activity>
          <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
        </application>

</manifest>
`

build.gradle
```
`dependencies {
    compile project(':react-native-onesignal')
    compile project(':react-native-image-crop-picker')
    compile project(':react-native-vector-icons')
    compile project(':react-native-linear-gradient')
    
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile project(':react-native-device-info')
    compile project(':react-native-config')
    implementation(project(':react-native-firebase')) {
        transitive = false
    }
    // Firebase dependencies
    implementation "com.google.android.gms:play-services-base:15.0.0"
    implementation "com.google.firebase:firebase-core:15.0.2"
    implementation project(':react-native-device-info')
    implementation project(':react-native-config')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:23.0.1"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation "com.google.firebase:firebase-auth:15.1.0"
    implementation "com.google.firebase:firebase-database:15.0.0"
    implementation "com.google.firebase:firebase-analytics:15.0.2"


}`
```

**Comment by Nightsd01** [comment]
@adirzoari Please use `OneSignal.setLogLevel(6, 0)` (verbose) and post your logcat? Are you seeing any errors...?

This doesn't appear to be a common issue in `3.2.3` so some investigation & more details from you would be helpful.

**Comment by adirzoari** [comment]
@Nightsd01 where to add it? where that I configure the onesignal?

**Comment by adirzoari** [comment]
I add here and I don't see nothng in debug console 
```
`  componentDidMount() {
        OneSignal.init(ONESIGNAL_APP_ID)
        OneSignal.configure({})
        OneSignal.setLogLevel(6, 0)
        OneSignal.addEventListener('received', this.onReceived)
        OneSignal.addEventListener('opened', this.onOpened)
        OneSignal.addEventListener('ids', this.onIds)`
```

**Comment by Nightsd01** [comment]
@adirzoari It would actually be better if you go into the react-native-onesignal Android src, edit `OneSignal.java`, and add this line just above where it calls `OneSignal.init()...`, around line 120:

```java
import com.onesignal.OneSignal.LOG_LEVEL;

//<- Inside RNOneSignal.java's init() method ->

OneSignal.sdkType = "react";
      
//ADD THIS LINE
OneSignal.setLogLevel(LOG_LEVEL.VERBOSE, LOG_LEVEL.NONE);

OneSignal.init(activity,
   null,
   appId,
   new NotificationOpenedHandler(mReactContext),
      new NotificationReceivedHandler(mReactContext)
);

```

**Comment by adirzoari** [comment]
here to write appId or my real appId 'Y2FmNTxxxxEtZjhkNC00Nxxxxxxxxxxxxxxxxxxxxxxxxxxx?
`OneSignal.init(activity,
   null,
   appId,
   new NotificationOpenedHandler(mReactContext),
      new NotificationReceivedHandler(mReactContext)
);`

**Comment by Nightsd01** [comment]
Please write your real app ID.

**Comment by Nightsd01** [comment]
Oh, in RNOneSignal.java? Don't edit/touch anything except adding logging.

**Comment by adirzoari** [comment]
okay I add this line. where can i see the logs?

**Comment by adirzoari** [comment]
I got the error 

>  error: cannot find symbol      OneSignal.setLogLevel(LOG_LEVEL.VERBOSE, LOG_LEVEL.NONE);

**Comment by Nightsd01** [comment]
Please add the `import` line

**Comment by adirzoari** [comment]
which import? can you write it?

**Comment by Nightsd01** [comment]
You can import at the top of the file, where you will see all of the other `import` statements..

**Comment by adirzoari** [comment]
okay I write manually 0 and 6
`      OneSignal.setLogLevel(0, 6);
`
is that okay?

**Comment by Nightsd01** [comment]
It would be better to do what I posted above

**Comment by adirzoari** [comment]
yes but I'm not sure what to import. can you write the full import and I add in my code please?
I stuck a week with this issue.

**Comment by Nightsd01** [comment]
Ok.. search for this line:

`import com.onesignal.OneSignal.EmailUpdateError;`

And replace it with this:
```
import com.onesignal.OneSignal.EmailUpdateError;
import com.onesignal.OneSignal.LOG_LEVEL;
```

**Comment by adirzoari** [comment]
okay I add. what should I do now?
when i added the 0 and 6 manually I get two errors and I got screens shots
![screenshot_2018-05-22-00-02-23-917_com moonsite sqlivetrivia](https://user-images.githubusercontent.com/20258998/40329956-0fcab138-5d54-11e8-958f-e73ad1b6a7e8.png)
![screenshot_2018-05-22-00-02-17-158_com moonsite sqlivetrivia](https://user-images.githubusercontent.com/20258998/40329957-0ff429d2-5d54-11e8-8aa6-e0983a9e245b.png)
but now with the import you said I don't see any errors

**Comment by Nightsd01** [comment]
@adirzoari That works! That is an issue with our Android native SDK, which we've fixed a few days ago. 

We will be creating a new `react-native-onesignal` update to fix this issue today

**Comment by adirzoari** [comment]
thanks you very very much! can you notify me when you release new update please?

**Comment by Nightsd01** [comment]
@adirzoari The new update is now available (3.2.4) - please feel free to ask if you have any other problems

**Comment by nahidmbstu** [comment]
i am also facing this issue

**Comment by nahidmbstu** [comment]
how to solve this ?
