### ISSUE TITLE
Prevent displaying some notifications

### ISSUE THREAD

**Issue by yaseralimardany** [OneSignal/react-native-onesignal#518]
I know there is a parameter named OneSignal.inFocusDisplaying(2); for display/hide notification.
But I want to prevent displaying some notifications not all of theme.
For example, Received 10 notifications and I want to check additionalData of those, then for example two of those notification display for user.

Anybody help?
Can i add some code to Received function to manage displaying of received notifications?

**Comment by Nightsd01** [comment]
@yaseralimardany Our react-native SDK does not support this, so you would have to build it out yourself. But I would suggest you research the Android Notification Extender service in Android, and the iOS notification service extension.

https://documentation.onesignal.com/docs/android-customizations

I don't know of any guide or tutorial that will walk you through this step by step, so you'll need to do some research.

I hope this helps. If you need further assistance I would recommend Apple developer forums (for the iOS notification extension service) and Android developer community.
