### ISSUE TITLE
postNotification from android to ios

### ISSUE THREAD

**Issue by neo125874** [OneSignal/react-native-onesignal#519]
**Description:**
post notification not received by ios from android

**Environment**
latest one-signal

**Steps to Reproduce Issue:**
same code in the js file
`let contents = {
              en: "Calling..."
            };`
 `OneSignal.postNotification(contents, {}, item._value.uID, {});`

1. ios post to android (works)
2. android post to ios(not working)

**Anything else:**
action buttons support icon with url?
if yes? only android or only ios?
Because I couldn't get the icon from the postNotification or from the web(https://onesignal.com/)

**Comment by Nightsd01** [comment]
@neo125874 We were able to fix this issue in the new update (3.2.4), thank you for the bug report!

**Comment by neo125874** [comment]
@Nightsd01 thanks, i will try it later.
But how about the action buttons? I set the icon url but not showing.

**Comment by camin-mccluskey** [comment]
@Nightsd01 I'm now getting what appears to be the same issue. The player_id array is not being correctly parsed on Android. When i call `JSON.stringify(player_id)` the crash is resolved but the notifcation still isn't sent.
