### ISSUE TITLE
Notification does not appear on lock screen

### ISSUE THREAD

**Issue by andreibarabas** [OneSignal/react-native-onesignal#52]
Guys, The payload

```
{
    "app_id": "XXXXXXXXXXXXXXXX",
    "contents": {"en": "English Message","es": "Spanish Message"},
    "buttons": [{"id": "id1", "text": "button1", "icon": "ic_menu_share"}, {"id": "id2", "text": "button2", "icon": "ic_menu_send"}],
    "included_segments": ["All"],
    "android_visibility": 1
}
```

According to API docs, the notification should appear on lock screen. But this does not happen. I have enabled on the phone notifications on lock screen, and other apps like Facebook, Whatsapp, Gmail appear on the lock screen.

**Comment by avishayil** [comment]
Works fine on my end...
@jkasten2 do you have any suggestions?

**Comment by andreibarabas** [comment]
I'm testing on  an Android 4.4. Might it be that the case?

**Comment by jkasten2** [comment]
@andreibarabas Lock screen notifications were added in Android 5.0 Lollipop.
https://developer.android.com/about/versions/android-5.0.html#LockscreenNotifications

**Comment by andreibarabas** [comment]
I see! thanks for clearing that out for me. I've been bumping my head against this for a while now. Thanks
