### ISSUE TITLE
Options in JavaScript init method

### ISSUE THREAD

**Issue by sachinB94** [OneSignal/react-native-onesignal#520]
Update docs to reflect all the options accepted by `init` method in JavaScript. For example, `kOSSettingsKeyInFocusDisplayOption`

**Comment by Nightsd01** [comment]
@sachinB94 Thanks for bringing this up, we've added this information to our documentation: https://documentation.onesignal.com/v5.0/docs/react-native-sdk#section-ios-initialization-parameters

**Comment by sachinB94** [comment]
Hey, is `kOSSettingsKeyInFocusDisplayOption` not supported? I've tried it with values `0`, `1` and `2`, and it works fine.

I know there's an `OneSignal.inFocusDisplaying()` method, but if we can set `kOSSettingsKeyInFocusDisplayOption` in `init` also, don't you think it should be documented too?
