### ISSUE TITLE
iOS Native SDK intialization doesn't work any longer

### ISSUE THREAD

**Issue by sachinB94** [OneSignal/react-native-onesignal#521]
**Description:**

Notification `opened` event is not triggered when SDK is initialized in AppDelegate.m
```
self.oneSignal = [[RCTOneSignal alloc] initWithLaunchOptions:launchOptions
                                                           appId:@"APP_ID"
                                                        settings:@{kOSSettingsKeyInFocusDisplayOption: @(OSNotificationDisplayTypeNotification), kOSSettingsKeyAutoPrompt: @NO}];
  } 
```

**Environment**

React Native: v0.42.0
React Native OneSignal: v3.2.3

**Steps to Reproduce Issue:**

1. Install the OneSignal SDK
2. Initialize the SDK in the iOS AppDelegate
3. Attach `opened` event listener in `index.ios.js`
4. Receive a push notification
5. Click on the notification when app is in background/closed state
6. `opened` event not fired

**Comment by Nightsd01** [comment]
@sachinB94 Thank you for reporting this, I was able to reproduce and fix the issue thanks to all of the helpful information you've provided. Great job troubleshooting! This should now be fixed in the new update (3.2.4)
