### ISSUE TITLE
Documentation update re: ids event usage

### ISSUE THREAD

**Issue by demoran23** [OneSignal/react-native-onesignal#523]
**Description:**
To properly register for the `ids` event, you have to first invoke `configure`.  This is not documented at https://documentation.onesignal.com/v5.0/docs/react-native-sdk.

eg:

``` javascript
    OneSignal.configure();
    OneSignal.addEventListener('ids', this.onIds);
```

**Environment**
RNOneSignal version: 3.2.1

**Comment by Nightsd01** [comment]
We've updated the docs @demoran23 , thanks for pointing that out. 

`ids` will fire whenever the subscription state actually changes. If you want it to fire at a specific time though, you can call `OneSignal.configure()`
