### ISSUE TITLE
Icon of notification OK but not when open the control center

### ISSUE THREAD

**Issue by LcsLpr** [OneSignal/react-native-onesignal#527]
Hello,

I'am using the last version of react-native-onesignal and RN.

I followed this guide to put my icons for the notifications : [Documentation link](https://documentation.onesignal.com/docs/customize-notification-icons)
It is working when I receive the notif but not when I open the control center ... (screenshots below)

[Notif received OK](https://image.ibb.co/hOY0Fo/Screenshot_20180522_105537_2.jpg)
[In control center NOOK](https://image.ibb.co/dBd31T/Screenshot_20180522_105543_2.jpg)

Any idea please ???

**Comment by Nightsd01** [comment]
@LucasLpr I will be closing this issue until you post more details. For example, please list your dependencies. We have an issue template for exactly this reason...

Please describe what steps you took, what did you use to generate the icons? 

I'll be happy to reopen + investigate whenever you provide some more details

**Comment by LcsLpr** [comment]
Hello,

This is my dependencies : 

```
dependencies {
    implementation project(':react-native-geolocation-service')
    implementation project(':react-native-splash-screen')
    implementation project(':react-native-pdf')
    implementation project(':react-native-fetch-blob')
    implementation (project(':react-native-intercom')) {
        exclude group: "com.google.android.gms", module:"play-services-basement"
    }
    implementation "io.intercom.android:intercom-sdk:3.+"
    implementation project(':react-native-android-open-settings')
    implementation project(':react-native-system-setting')
    implementation project(':react-native-onesignal')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-i18n')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"
    implementation project(':tipsi-stripe')
    implementation project(':react-native-maps')
    implementation (project(':react-native-camera')) {
        exclude group: "com.google.android.gms"
    }
    implementation "com.android.support:appcompat-v7:23.0.1"
}
```

I have created folders drawable-mdpi, drawable-hdpi etc (because I had mipmad-mdpi ... folders).
And then I have put colored icons with these dimensions : 
res/drawable-mdpi/ (24x24)
res/drawable-hdpi/ (36x36)
res/drawable-xhdpi/ (48x48)
res/drawable-xxhdpi/ (72x72)
res/drawable-xxxhdpi/ (96x96)
res/drawable-xxxhdpi/ (256x256) (Large Icon)
And with the names : 
/drawable-[SIZE_NAMES]/ic_stat_onesignal_default.png
/drawable-xxxhdpi/ic_onesignal_large_icon_default.png (Large Icon)

I didn't use any tools to generate it ... Thank you :)

**Comment by eQuinox-l** [comment]
@Nightsd01 can you re-open it ? 
By the way, I tried on another Android and this one did work to get all colors on the notification

**Comment by LucasLpr** [comment]
Up
