### ISSUE TITLE
Send Push Notification with NotificationID

### ISSUE THREAD

**Issue by Kaniz92** [OneSignal/react-native-onesignal#529]
**Description:**
Is there a way to send the onesignal notification with defined notificationID from the [Server Rest API](https://documentation.onesignal.com/reference#view-notification)?

**Environment**

react-native-onesignal: 3.2.3
react-native: 0.54

**Comment by Nightsd01** [comment]
No. You can use the additional data field for custom information though. Your question doesn't make much sense, could you explain a bit more...?
