### ISSUE TITLE
react-native-onesignal build failed 

### ISSUE THREAD

**Issue by erez-guesty** [OneSignal/react-native-onesignal#534]
???

![image](https://user-images.githubusercontent.com/33092944/40604504-ecaa3eda-6267-11e8-8559-3f0ca4d62d6a.png)

**Comment by Richi2293** [comment]
I think it's a problem with jcenter.
We find a similar problem here too:

https://github.com/rebeccahughes/react-native-device-info/issues/413

**Comment by sanazmortazavi** [comment]
yes, i have the same problem with building project in android.
@avishayil,
@Nightsd01
@jkasten2

**Comment by erez-guesty** [comment]
@Richi2293
ver 12.0.0 is empty in jcenter, maybe aim to path with content, i.e. 12.0.1


```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-onesignal'.
      > Could not find firebase-messaging.jar (com.google.firebase:firebase-messaging:12.0.0).
        Searched in the following locations:
            https://jcenter.bintray.com/com/google/firebase/firebase-messaging/12.0.0/firebase-messaging-12.0.0.jar

```

**Comment by Richi2293** [comment]
I believe that there is no jar file of the other version of firebase.
I tried in various ways, the build works and the app works but onesignal does not work, the device does not receive notifications.
I think we need to be patient until the jcenter site works well

**Comment by Nightsd01** [comment]
The build is failing because this SDK has no tests, it's a wrapper around our iOS and Android SDK's (both have tests).

This seems to be a duplicate of the other issue so I'll be closing this one
