### ISSUE TITLE
idsAvailable is not called

### ISSUE THREAD

**Issue by whollacsek** [OneSignal/react-native-onesignal#54]
Today I upgraded from 1.1.5 to 1.1.8 and `idsAvailable` stopped working event though on OneSignal dashboard the new user is added correctly.

I'm using RN 0.28.

**Comment by whollacsek** [comment]
found the origin: https://github.com/facebook/react-native/issues/8469

**Comment by avishayil** [comment]
Thanks, we'll adapt to the new situation.

**Comment by avishayil** [comment]
Are you sure? displays fine on my end, RN 0.28, Android.

``` javascript
// Getting idsAvailable
OneSignal.idsAvailable((idsAvailable) => {
    console.log(idsAvailable.pushToken);
    console.log(idsAvailable.userId);
});
```

**Comment by whollacsek** [comment]
I didn't check on Android but it didn't work on iPhone device.

`idsAvailable` is not called because `NetInfo` is always returning false: https://github.com/geektimecoil/react-native-onesignal/blob/e279e9e7457446b7a6a21a730734703544831638/index.js#L154-L161

I downgraded to RN 0.27.2 and it worked. I guess we'll have to wait for more clarification from RN developers on the new behaviour of `NetInfo`.

**Comment by skycocker** [comment]
Fixed in https://github.com/geektimecoil/react-native-onesignal/pull/56, in the meantime you can use the changes from that PR to fix your local version.
