### ISSUE TITLE
Android onIds not working! (onesignal version 3.2.4)

### ISSUE THREAD

**Issue by furkancelik** [OneSignal/react-native-onesignal#540]
hi all,

I compiled one signal's own sample code for anroid.
(https://github.com/geektimecoil/react-native-onesignal/tree/master/examples/RNOneSignal)

the compilation is successful, but I can't get deviceId.
I wrote my own app ID with one signal init.

I'm running emilator. I didn't test it on the actual device.
deviceID is not working in the emilator? IOS also works.

**Comment by lahed** [comment]
check #525

**Comment by Nightsd01** [comment]
I am closing because this is a duplicate issue (#525).

Please go into the OneSignal dashboard and check to see if you see any errors there - as well as checking the logcat. 

If you don't see the same issue seen in #525, please provide more information and I'll be happy to reopen + investigate.

**Comment by om-fountain** [comment]
In my case, I never got any errors on the OneSignal dashboard; the device was getting registered with OneSignal fine. The onIds were just not firing. So, not exactly the same as #525 

Adding this right after OneSignal.init() fixed my issue:

```
    OneSignal.configure();
```
Hope this helps others who land here from google.

**Comment by QuijoteShin** [comment]
> In my case, I never got any errors on the OneSignal dashboard; the device was getting registered with OneSignal fine. The onIds were just not firing. So, not exactly the same as #525
> 
> Adding this right after OneSignal.init() fixed my issue:
> 
> ```
>     OneSignal.configure();
> ```
> Hope this helps others who land here from google.
** OneSignal.addEventListener("ids", this.onIds); not firing

Thank you @om-fountain , worked for me!
