### ISSUE TITLE
App is force closing when app is open after receiving the notification.

### ISSUE THREAD

**Issue by ahmermunaf** [OneSignal/react-native-onesignal#543]
App is force closing when app is open after receiving the notification. But when App is in background it is working fine

**Comment by chocolatemusic** [comment]
i same.

i solve

At the very top of your Android project's app/build.gradle

`buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal 
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.0, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

apply plugin: "com.android.application"

import com.android.build.OutputFile

/**`

**Comment by ahmermunaf** [comment]
I have already done this work but the error is not resolving.

**Comment by Nightsd01** [comment]
@ahmermunaf You have not given _any_ details/info to help solve your problem so I will be closing your issue. We have an issue template that asks for several details.

Please at least provide a stack trace.

Once you provide some more info, I'd be happy to reopen the issue and help investigate.

**Comment by ahmermunaf** [comment]
@Nightsd01 I am new to react native. please tell me what you want ? Source Code ?
