### ISSUE TITLE
OneSignal gradle sync bug when added into project

### ISSUE THREAD

**Issue by vincentvella** [OneSignal/react-native-onesignal#544]
**Description:**
Android gradle sync is failing for task: 

* What went wrong:
Execution failed for task ':react-native-onesignal:processDebugAndroidTestManifest'.
> Manifest merger failed with multiple errors, see logs

**Environment**
1. What version of the OneSignal React-Native SDK are you using?
3.2.4
2. How did you add the SDK to your project (eg. npm)
npm

**Steps to Reproduce Issue:**
1. Added the OneSignal SDK using npm
2. Added react-native-onesignal to the dependencies in the app build.gradle
3. Added ReactNativeOneSignalPackage() to the MainApplication.java
4. Ran Gradle Sync
(project still works and I receive notifications but the gradle sync continues to say that it's broken)

I think this may have something to do with this error: 
Attribute meta-data#onesignal_app_id@value at manifestMerger7179252738002097895.xml requires a placeholder substitution but no value for <onesignal_app_id> is provided.

There should not be an error there though because I'm initializing it with the new Javascript SDK and just compiling the assets into the project to my knowledge.

**Comment by Nightsd01** [comment]
Hi, this is related to the OneSignal Android native SDK (not specific to our react-native SDK), however it shouldn't actually cause any build errors/problems. 

In short, you'll see the error but there shouldn't be any actual issues.

Please feel free to ask if you have any other questions/problems and we'd be happy to help!

**Comment by rgoldiez** [comment]
Confirming what @Nightsd01 is saying..... I was trying and trying to debug this issue (after upgrading from `3.1.2` to `3.2.4` and apparently it's not an issue at all.  I was able to build the app and run it in the simulator just fine.

**Comment by fadlykayo** [comment]
Having the same problem at **3.2.12**. What was the solution for this?

**Comment by AfanasievN** [comment]
Having the same problem with 3.3.1 ...
