### ISSUE TITLE
push Token is always null on 3.1.4

### ISSUE THREAD

**Issue by nahidmbstu** [OneSignal/react-native-onesignal#549]
**Description:**
  push Token is always null . i dont want to update module version then i have to change my code.my version is 3.1.4

Environment:
  OS: Linux 4.13
  Node: 8.11.2
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: N/A
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
  "react-native-onesignal": "3.1.4",
```

  onIds = (device) => {

    const { params } = this.props.navigation.state;

    console.log('Device info: ', device);

```

**Comment by Nightsd01** [comment]
Multiple issues have been fixed since 3.1.4 that would cause this. Please don’t create tickets for outdated versions. 

I don’t know why you would have to chance your code if you’re using 3.1.4? I don’t believe we’ve made any breaking chances.
