### ISSUE TITLE
ExampleUnitTest.java Causes Rebuild To Fail On Android

### ISSUE THREAD

**Issue by bendellarocco** [OneSignal/react-native-onesignal#55]
Once removing this file my build passed

/Users/bdellarocco/apps/masstuning/node_modules/react-native-onesignal/android/src/test/java/com/geektime/rnonesignalandroid/ExampleUnitTest.java
Error:(3, 17) error: package org.junit does not exist
Error:(5, 24) error: package org.junit does not exist
Error:(11, 6) error: cannot find symbol class Test
Error:(13, 9) error: cannot find symbol method assertEquals(int,int)
:react-native-onesignal:compileDebugUnitTestJavaWithJavac FAILED
Error:Execution failed for task ':react-native-onesignal:compileDebugUnitTestJavaWithJavac'.

> Compilation failed; see the compiler error output for details.

**Comment by avishayil** [comment]
Any way to reproduce this issue?

**Comment by avishayil** [comment]
Not clear why is this happening,
Can you please post your `android/build.gradle` file here?

**Comment by bendellarocco** [comment]
Sure, @avishayil 
// Top-level build file where you can add configuration options common to all sub-projects/modules.

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$projectDir/../../node_modules/react-native/android"
        }
    }
}

```

**Comment by avishayil** [comment]
Couldn't replicate, but the only solution I can think of is to compile junit in your project.

**Comment by bendellarocco** [comment]
I just removed the file and the issue resolved

**Comment by avishayil** [comment]
More stable solution would be to compile junit, but I'm happy you figured it out yourself.

**Comment by vidyuthd** [comment]
I am getting this issue now with version 3.0.3. Please add compile junit in build.gradle.

**Comment by waqasjuttt** [comment]
i have same issue. plzzzz anybody help me i have attached pic for those errors occur in my project
 
![1](https://user-images.githubusercontent.com/24193724/29107608-6735bd5a-7cf4-11e7-9176-085262275db3.jpg)
