### ISSUE TITLE
FAILURE: Build failed with an exception.  * What went wrong: Could not resolve all files for configuration ':app:debugCompileClasspath'. > Could not find common.jar (android.arch.core:common:1.1.0).   Searched in the following locations: https://jcenter.bintray.com/android/arch/core/common/1.1.0/common-1.1.0.jar

### ISSUE THREAD

**Issue by nahidmbstu** [OneSignal/react-native-onesignal#551]
Environment:
  OS: Linux 4.13
  Node: 8.11.2
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: N/A
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

Running Example project

git clone https://github.com/geektimecoil/react-native-onesignal
cd react-native-onesignal && cd examples && cd RNOneSignal
npm install --save 
 react-native run-android

gives me the error ................

**Comment by Nightsd01** [comment]
@rodrigofbm In your `android/build.gradle` in your `repositories` section, try moving `google()` ABOVE `jcenter()`. 

It's bizarre, but we've seen this fix this particular issue.

**Comment by davekedar** [comment]
Have you updated the android Studio?

**Comment by Nightsd01** [comment]
I'm assuming due to no response that moving google() fixed your issue. If not please feel free to reply and I'll be happy to reopen & investigate the issue
