### ISSUE TITLE
WakefulBroadcastReceiver behavior with react-native-onesignal?

### ISSUE THREAD

**Issue by dhamaniasad** [OneSignal/react-native-onesignal#554]
**Description:**

It seems like the react native SDK does not use a WakefulBroadcastReceiver, so if your user closes your app, they will not receive any notifications. The native Android SDK seems to have support for this. Is there any way to get the app to receive notifications even when it is closed when using the react native sdk?

**Environment**
react-native-onesignal @ 3.2.4, added via npm

**Steps to Reproduce Issue:**
  1. Install the OneSignal SDK using npm into your project
  2. Initialize the SDK following the setup instructions for Android
  3. Send yourself push notification while app is running (foreground or background), and you receive it
  4. Swipe the app away from recents screen, and now send yourself push notification again, notification is not received

**Comment by Nightsd01** [comment]
@dhamaniasad The react-native SDK is simply a wrapper on top of our native Android SDK. It will use the WakefulBroadcastReceiver if it has to.

Most android devices will _not_ actually force-close an app when you swipe away from the recents screen. However some Chinese devices will. 

Please read our troubleshooting article for this.

https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown
