### ISSUE TITLE
How to stop OneSignal to set values for the Icon Badge on android device

### ISSUE THREAD

**Issue by fabiobh** [OneSignal/react-native-onesignal#555]
**Description:**
When I receive a push, or click in the push message from OneSignal, the badge in the icon is changed, I don't want that OneSignal changes the badge in my icon.

I follow the documentation and try to add the following line to my AndroidManifest file:
<meta-data android:name="com.onesignal.BadgeCount" android:value="DISABLE" />

It was supposed that OneSignal don't show badges in my app icon, but adding the line above didn't change anything.

This is my complete android manifest file:

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.virtus">

    <meta-data android:name="com.onesignal.BadgeCount" android:value="DISABLE" />
    
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:launchMode="singleTop" 
        android:screenOrientation="portrait"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      
    </application>

</manifest>

**Environment**
react-native-onesignal @ 3.2.4, added via npm

**Steps to Reproduce Issue:**
1. Write the line \<meta-data android:name="com.onesignal.BadgeCount" android:value="DISABLE" /> inside your AndroidManifest.xml file
2. Send a push to your device using OneSignal dashboard (it will change the badge icon)
3. Click on the push OR remove the push message (the badge icon will change again)

**Comment by Nightsd01** [comment]
Your `DISABLE` meta-data is in the wrong location in your manifest. Please make sure to read our [docs](https://documentation.onesignal.com/docs/android-customizations#section-app-icon-badge-counts) on badges in Android.

It should be inside of the `<application> ... </application>` tags like this:

```xml
<application ...>
   <meta-data android:name="com.onesignal.BadgeCount" android:value="DISABLE" />
</application>
```

So in your particular manifest, remove the DISABLE statement and change your application section to this:

```xml
<application
  android:name=".MainApplication"
  android:label="@string/app_name"
  android:icon="@mipmap/ic_launcher"
  android:allowBackup="false"
  android:theme="@style/AppTheme">
  <meta-data android:name="com.onesignal.BadgeCount" android:value="DISABLE" />
  <activity
    android:name=".MainActivity"
    android:label="@string/app_name"
    android:launchMode="singleTop" 
    android:screenOrientation="portrait"
    android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
    android:windowSoftInputMode="adjustResize">
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>
  </activity>
  <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
  
</application>
```

**Comment by TuNguyenThanh** [comment]
I have a problem:
Click on the push or remove the push message (the badge icon will change again)
How to fix ???

**Comment by fabiobh** [comment]
@TuNguyenThanh Just add the <meta-data android:name="com.onesignal.BadgeCount" android:value="DISABLE" /> tag inside the application tag just like @Nightsd01 showed. Your app will not update the badge again even if you click on the push message.
