### ISSUE TITLE
Setting collapse_id prevents vibration on ios

### ISSUE THREAD

**Issue by scottmas** [OneSignal/react-native-onesignal#562]
**Description:**
Triggering notifications with the `collapse_id` parameter set prevents new vibrations. The expected behavior is to have the phone vibrate for every new message in the `collapse_id` but to only show the most recent message. Currently we only get vibrations on the very first notification. 

**Environment**
Using version 3.2.4 of the SDK. The library was added using `react-native link`, which manually added the library (e.g. I did not use pods)

**Steps to Reproduce Issue:**
1. Install the OneSignal SDK using npm into your project
2. Initialize the SDK in the iOS AppDelegate
3. Send multiple notifications to yourself via the server API with a `collapse_id` equal to `123`
4. Note that you only receive a vibration the very first time.

**Comment by Nightsd01** [comment]
@scottmas This is system (iOS) behavior, not specific to OneSignal.

In fact this is the entire purpose of the `collapse_id`, it will only alert users on the first notification if they're on the lock screen.
