### ISSUE TITLE
Setting android_group makes small_icon be ignored

### ISSUE THREAD

**Issue by scottmas** [OneSignal/react-native-onesignal#563]
**Description:**
If `android_group` is set, then the `small_icon` parameter is ignored and only the default bell icon appears as the icon image. 

**Environment**
SDK version 3.2.4, using manual linking. 

**Steps to Reproduce Issue:**
1. Install the OneSignal SDK using npm into your project
2. Initialize the SDK
3. Send multiple messages to an Android device with the `android_group` set to `123` and a valid `small_icon`, where the asset exists in `./android/app/src/main/res/drawable-*`. 
4. Note that after the second message, the icon becomes the default bell icon.

**Comment by Nightsd01** [comment]
@scottmas With grouped notifications, you could potentially have several different notification icons. 

Instead, OneSignal's SDK will simply use the _default_ notification icon for your app.

If you want to use something other than the default bell icon, you can. Please see our [documentation on this topic](https://documentation.onesignal.com/docs/customize-notification-icons) for more info.

In short, this is not a bug with the SDK.

**Comment by scottmas** [comment]
Ahh, that makes sense.
