### ISSUE TITLE
OneSignal listeners do not work

### ISSUE THREAD

**Issue by teloconf** [OneSignal/react-native-onesignal#564]
**Description:**

I'm trying to decipher because both iOS and Android OneSignal does not work. The app works perfectly but OneSignal stays in silent mode and never receives any parameters.
All events return undefined.
Can you help me, please?

Thanks in advance

**Environment**

I am using:
 - "react": "16.3.1",
 - "react-native": "0.55.4",
 - "react-native-onesignal": "^3.2.4",

**Steps to Reproduce Issue:**

1. Install OneSignal
2. run-android

**Anything else:**

<img width="804" alt="captura de pantalla 2018-06-14 a las 2 33 33" src="https://user-images.githubusercontent.com/7244055/41385380-7b7be756-6f7b-11e8-88b0-3a85cdfdb055.png">
<img width="797" alt="captura de pantalla 2018-06-14 a las 2 35 14" src="https://user-images.githubusercontent.com/7244055/41385392-9a564f9a-6f7b-11e8-9457-233943610ab0.png">

**Comment by Nightsd01** [comment]
When you say "all events return undefined", what do you mean...?

Also, just to make sure, Apple does not allow push notifications in the iOS simulator, you will not get a push token / ID. You would need to run on a real iOS device.

Please just post some more info. Does it ask you for push permission in iOS? 

Also, try posting the logs of the first ~30 seconds of running your app. Make sure to put `OneSignal.setLogLevel(6, 0)` **above** init.

**Comment by Nightsd01** [comment]
Closing this issue due to no response - I am assuming you were able to fix this issue in your project. Please feel free to reply if that is not the case and I'll be happy to reopen the issue and investigate.

**Comment by Mohammad-Khalid23** [comment]
OnReceived Listener is not working , but I am getting notification

    OneSignal.addEventListener('received', this.onReceived);

  onReceived(notification) {
    console.log("Notification received: ", notification);
  }

**Comment by Nightsd01** [comment]
@Mohammad-Khalid23 Please do provide more details, ie. what version of our SDK are you using, your project react-native version and dependencies, whether this issue happens in iOS vs. android, etc....

**Comment by Mohammad-Khalid23** [comment]
I'm getting same issue my  **"react-native-onesignal": "^3.1.2",** 

```
Environment:
  OS: Linux 4.13
  Node: 8.9.0
  Yarn: Not Found
  npm: 5.5.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: ^0.55.3 => 0.55.4
```
Sometimes, onReceived working and sometime not
