### ISSUE TITLE
Callbacks opened, received not working

### ISSUE THREAD

**Issue by GibranPolonsky** [OneSignal/react-native-onesignal#567]
Description:
The callbacks has not been dispatched when a notifications arrive or open.

Environment
ANDROID
"react": "16.3.1",
"react-native": "0.55.3",
"react-native-onesignal": "^3.2.4",

Steps to Reproduce Issue:
  1. Install the OneSignal SDK using npm into your project
  2. Initialize the SDK in the Android Project
  3. Attempt to receive a push notification

Possible Solution: 
I just rolled back to "react-native-onesignal": "3.0.7", and installed the SDK as the old docs says.

**Comment by Nightsd01** [comment]
@CusProjects Please provide more details. For example, post the code you are using to add the event listeners, where you initialize the SDK, and so on.

Also, are you sure that the notification actually _arriving_ on the device?  Is this on the simulator or a real android device? Does it work in iOS?

**Comment by GibranPolonsky** [comment]
@Nightsd01 
componentWillMount() {
    OneSignal.init("YOUR_ONESIGNAL_APPID");
    OneSignal.configure();
    OneSignal.addEventListener('received', this.onReceived);
    OneSignal.addEventListener('opened', this.onOpened);
}

componentWillUnmount() {
    OneSignal.removeEventListener('received', this.onReceived);
    OneSignal.removeEventListener('opened', this.onOpened);
}

onReceived(notification) {
    console.log("Notification received: ", notification);
}

onOpened(openResult) {
    console.log('Message: ', openResult.notification.payload.body);
    console.log('Data: ', openResult.notification.payload.additionalData);
    console.log('isActive: ', openResult.notification.isAppInFocus);
    console.log('openResult: ', openResult);
}
The notifications actually arrived but the callback did not.
I used a Genymotion Simulator Google Nexus 5 with Android 5.1.0

**Comment by Nightsd01** [comment]
@CusProjects Does this issue only occur when the app is terminated and then you tap a notification? Does it occur in the background, or when the app is open? Or does it occur for _all_ of those situations?

Do other events (like the `ids` event) fire?

Lastly, how do you know for sure that the event is not being called, you're just not seeing the console.log statements? 

Try setting `OneSignal.setLogLevel(6, 0)` right above `OneSignal.init(...)` and tell me if you see any errors printed to logcat.

**Comment by GibranPolonsky** [comment]
It occurs for all of the situations. (background, active)
The ids event works.
I tried just  with console.log statement

**Comment by Nightsd01** [comment]
@CusProjects could you try what I suggested and set the OneSignal log level and tell me if you see any errors?

Also, does this issue occur for you on several types/brands/versions of Android devices, or just one?

I’ve not seen this particular issue reported by other devs where the events work except for `opened` and `received`, so the more information you can provide the better.

**Comment by roycclu** [comment]
@Nightsd01 
similar problem here. device iPhoneX receives notifications. but the onIds callback doesn't work

xcode log shows
```
2018-06-18 15:35:45.326179+0800 timepop[9767:3704776] INFO: Device Registered with OneSignal: <device-id>
```

code looks like
```
  componentDidMount() {
    OneSignal.setLogLevel(6, 0);
    OneSignal.init(<app_id>, {
      kOSSettingsKeyAutoPrompt: true,
    });
    OneSignal.addEventListener('received', this.onReceived);
    OneSignal.addEventListener('opened', this.onOpened);
    OneSignal.addEventListener('ids', this.onIds);
    OneSignal.getTags(tags => {
      console.log('Did get tags: ', tags);
    });
  }

  componentWillUnmount() {
    OneSignal.removeEventListener('received', this.onReceived);
    OneSignal.removeEventListener('opened', this.onOpened);
    OneSignal.removeEventListener('ids', this.onIds);
  }

  onReceived = notification => {
    console.log('Notification received: ', notification);
  };

  onOpened = openResult => {
    console.log('Message: ', openResult.notification.payload.body);
    console.log('Data: ', openResult.notification.payload.additionalData);
    console.log('isActive: ', openResult.notification.isAppInFocus);
    console.log('openResult: ', openResult);
  };

  onIds = device => {
    console.log('Device info: ', device);
  };
```

The onOpened and onReceived callbacks fire, but onIds does not fire. 
This is an issue. We need the deviceId to register with our server for targeted push. 

Any idea why?

rn: 0.54.0-rc3
rn-onesignal: 3.2.4

**Comment by Nightsd01** [comment]
@roycclu The `ids` event will only fire when there is a change (ie. the user subscribes and gets a onesignal user ID)

Otherwise, if you want it to fire at a certain time, you can always call `OneSignal.configure()` which will cause `ids` to fire. It's pretty confusing for legacy reasons, I'll be refactoring this logic in the next major release, but in the mean time that will solve your problem.

**Comment by Nightsd01** [comment]
@CusProjects Closing the issue due to no response, I assume you managed to get it working. Please post your solution if you did. If the issue still occurs for you (or anyone else) please post here and I'll be happy to reopen + investigate.

**Comment by roycclu** [comment]
@Nightsd01 hey man, thanks for the tip. Got involved with other parts of the project and finally now checked.  

The solution works, calling configure triggers the onIds callback. Although this is anti-intuitive. One would assume that by calling OneSignal.init() is enough to trigger callback.
