### ISSUE TITLE
Could not read path

### ISSUE THREAD

**Issue by SirPhemmiey** [OneSignal/react-native-onesignal#568]
It keeps giving this error when i try to build
`Could not read path 'C:\xampp\htdocs\customer_stylefit\node_modules\react-native-onesignal\android\build\generated\source\r\debug\android\support\v4'.
?[33m> ?[39mC:\xampp\htdocs\customer_stylefit\node_modules\react-native-onesignal\android\build\generated\source\r\debug\android\support\v4`

**Comment by SirPhemmiey** [comment]
Okay..so i had to delete the build folder of the package

**Comment by buiminhduc1995** [comment]
show me how to fix it

**Comment by SirPhemmiey** [comment]
Hey @buiminhduc1995, i located the android build folder of react-native-onesignal module inside node_modules and deleted it. It will be created automatically once you run `react-native run-android` again.
