### ISSUE TITLE
Notice & Help Request Regarding RN 0.29 Support

### ISSUE THREAD

**Issue by avishayil** [OneSignal/react-native-onesignal#57]
In RN 0.29 fb changed the way RN libraries should be included in Android, and listen to application life cycle. I'm working right now on a solution for the migration, but I'd be happy to get some help from Android experts around here.

Version 1.1.9 would include all features and will support RN version < 0.29, while version 1.2.0 and up will support RN 0.29 and up. New features will be supported only on RN 0.29 and up once we'll figure a solution to migrate the library according to the new changes.

**Comment by jkasten2** [comment]
@avishayil Can you link their doc?

The OneSignal native code is designed to handle either an Activity or Application Context already.

**Comment by avishayil** [comment]
https://github.com/facebook/react-native/issues/8509

**Comment by jkasten2** [comment]
@avishayil
You can use `getApplicationContext()` instead.

**Comment by avishayil** [comment]
Yeah, I'm trying that but I have problem using the notificationOpenedHandler, can't get it to work using the new life cycle.

**Comment by avishayil** [comment]
Migration process:
https://github.com/geektimecoil/react-native-onesignal/tree/RN-0.29

Couldn't seem to listen to Application lifecycle properly...

**Comment by avishayil** [comment]
Nailed it.

**Comment by satya164** [comment]
Note that listening to lifecycle events and `getCurrentActivity` has been supported in RN for quite a few versions. So it's not a breaking change for you.

**Comment by avishayil** [comment]
Thanks @satya164 !, i'll definitely take a look on this.
