### ISSUE TITLE
kOSSettingsKeyInFocusDisplayOption with JS init method?

### ISSUE THREAD

**Issue by slorber** [OneSignal/react-native-onesignal#574]
Hi,

There is already an issue on the subject: https://github.com/geektimecoil/react-native-onesignal/issues/520

Previous versions allowed me do disable the default alert displayed when a new push message is received while the app is in foreground:

```
    self.oneSignal = [[RCTOneSignal alloc] initWithLaunchOptions:launchOptions
                                            appId:@"dgdfgdfg"
                                            settings:@{kOSSettingsKeyInFocusDisplayOption : @(OSNotificationDisplayTypeNone)}];
```

But with the JS init method, I don't see any equivalent feature, is there anything available or should I still use native code for that?

**Comment by Nightsd01** [comment]
Yes, you can pass in iOS settings with the new JS init method:

```javascript
OneSignal.init("your_app_id_here", {kOSSettingsKeyInFocusDisplayOption:  2})
```

Of course, these settings will only be used in iOS. If you have shared source between Android and iOS, you can still pass in these settings, they will just get ignored in Android

OSNotificationDisplayTypeNone = 0
OSNotificationDisplayTypeInAppAlert = 1
OSNotificationDisplayTypeNotification = 2

Please feel free to ask if you have any other questions

We've updated our [documentation](https://documentation.onesignal.com/v5.0/docs/react-native-sdk#section-ios-initialization-parameters) to explain this as well, thanks for bringing that up.

**Comment by slorber** [comment]
thanks, nothing to add, this was just missing from the doc

**Comment by ADjenkov** [comment]
Sorry for asking in already closed issue , but is there any way (other than custom notification UI inside the app) to achieve kOSSettingsKeyInFocusDisplayOption:  2 for Android?
