### ISSUE TITLE
How can we upgrade to the latest version?

### ISSUE THREAD

**Issue by yaronlevi** [OneSignal/react-native-onesignal#582]
Hi (-:

We have an app in production that uses react-native-onesignal in version 3.0.5.
Now it's time to get the latest version which is 3.2.5.
Is updating package.json from 3.0.5 to 3.2.5 and npm install will do the trick?

Do we need to perform any others steps/commands run link command again?

(what about those native onesignal sdks and other native changes)

**Comment by Nightsd01** [comment]
Hi, you can follow the getting started instructions. Yes, updating `package.json` to `3.2.5` and running `npm i` will update to the latest version. Depending on how you want to initialize the SDK, you can either remove the old initialization code from `build.gradle` (for Android) and `AppDelegate.h` & `AppDelegate.m` (for iOS) and add the new initialization code in JS.

https://documentation.onesignal.com/docs/react-native-sdk-setup

**Comment by yaronlevi** [comment]
Great!
Good to hear it's a simple process.
Thanks.
