### ISSUE TITLE
iOS silent notifications only work if app is build with Xcode GUI

### ISSUE THREAD

**Issue by Gys** [OneSignal/react-native-onesignal#584]
**Description**

The app receives normal notifications plus silent notifications. Its build for Android and iOS. All notifications are send using the OneSignal service. A few days ago we noticed the iOS silent notifications sometimes did not not work during tests. Not sure why we did not notice before; maybe we used Xcode more while testing the silent notifications - for the simulator we have use a workaround anyway. After some frustrating trial and error we found that using Xcode GUI made all the difference. That might explain why the live versions always worked as expected.

The problem: normal notifications always work on Android and iOS. Silent notifications also always work on Android. But for iOS the silent notifications *only* work if the project is run on the device from *Xcode GUI*. If we use `react-native run-ios --device` then the silent notifications are not working, meaning: the 'received' event listener is not fired at all (but still fires for normal notifications!).

Switching between Xcode and react-native cli is the only difference. Using Xcode GUI means having a working app. Using react-native cli immediately after that results in an app not receiving silent notifications. With exactly the same code, no other click or command executed, no build cleaning. Immediately doing Xcode GUI means having a working app again.

We tested this on two MacBooks.

Could this be a OneSignal problem ? Is it really possible that Xcode GUI builds / compiles things differently from react-native commandline ? Doesn't the commandline just call Xcode commandline ?

**Environment**

react-native-onesignal 3.2.5 (also tried 3.2.4 and 3.1.2; same problem)
Xcode 9.4.1 Build version 9F2000
xcode-select --print-path gives '/Applications/Xcode.app/Contents/Developer'
react-native-cli 2.0.0
Node 8.4.0
npm 5.6.0
react 16.3.1
react-native 0.55.4
macOS High Sierra 10.13.6

**Comment by Nightsd01** [comment]
@Gys thank you for reporting this, this is _quite_ strange. It seems to have more to do with whether or not Xcode is debugging the process. Even if you launch the app from Xcode, if you unplug the device (without closing the app), silent notifications will immediately stop working. 

Thank you for bringing this to our attention, this doesn't occur in any of our other SDK's (I just tested). We will investigate to see if there's anything we can do.

**Comment by Nightsd01** [comment]
I investigated this issue and it's not an issue with our SDK, it seems to be a problem with React-Native specifically. The issue doesn't occur in release mode.

Unfortunately my best recommendation at this point: if you need to test a feature related to silent notifications, run it with Xcode.

I will be creating an issue with react-native and will update this ticket once I've gathered more information, but I have been able to verify that the issue occurs with silent notifications _even without_ our SDK installed at all.
