### ISSUE TITLE
I keep receiving notifications from another user even after closing session

### ISSUE THREAD

**Issue by jerolan** [OneSignal/react-native-onesignal#596]
**Description:**
I am using email targeting to send notifications to my users to multiple devices that have the same email using the function `setEmail`, but when the user closes session he still receives notifications even after running the function` logoutEmail` and `setSubscription (false)`

**Environment**
react-native-onesignal: "3.2.5"
react-native: "0.55.3"

**Steps to Reproduce Issue:**
```javascript
componentDidUpdate (prevProps) {
    /**
     * Synchronize email when user login
     */
    if (!prevProps.email && this.props.email) {
      OneSignal.setSubscription(true)
      OneSignal.setEmail(this.props.email, (err) => console.log('NOTI_EMAIL_CB', err))
    }

    /**
     * Stop user synchronization
     */
    if (prevProps.email && !this.props.email) {
      OneSignal.setSubscription(false)
      OneSignal.logoutEmail(err => console.log('NOTI_EMAIL_CB', err))
    }
 }
```

**Comment by jerolan** [comment]
Closed, i moved my targeting strategy to `tags`

**Comment by vladkosinov** [comment]
I have same issue: `logoutEmail` is not unsubscribing from notifications
//cc @Nightsd01
