### ISSUE TITLE
Error: Could not find com.android.tools.build:gradle:3.1.2

### ISSUE THREAD

**Issue by salimakhtar92** [OneSignal/react-native-onesignal#599]
I am facing following issue:
```
 Could not resolve all dependencies for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:3.1.2.
```

How to fix this?

**Comment by Nightsd01** [comment]
@salimakhtar92 We have an issue template that asks you to provide a lot of details. For example, what version of our SDK are you using, what version of React-Native, what other dependencies you're using, etc.

Please post those details along with your `build.gradle` and `gradle-wrapper.properties` and I'll be happy to reopen and help you solve the problem.
