### ISSUE TITLE
ios badge does not reset

### ISSUE THREAD

**Issue by scottmas** [OneSignal/react-native-onesignal#600]
This is just re-opening https://github.com/geektimecoil/react-native-onesignal/issues/309, which has been closed due to a misunderstanding. The issue is still outstanding. 

I have correctly set up the extension, and can receive rich images just fine. However, the badge count does not reset. Please look on the original issue for further details.

**Comment by Nightsd01** [comment]
@scottmas 

Did you set up the App Group correctly?

If so, can you try this:

1. In **both** `Info.plist` files (your app target will have one, the OneSignalNotificationServiceExtension target will _also_ have one), add the following key/value pair:

`OneSignal_app_groups_key` = `group.{your_app_bundle_id}.onesignal`

Let me know if that works

**Comment by scottmas** [comment]
That did the trick! Is this in the documentation? I thought I followed it pretty closely

**Comment by Nightsd01** [comment]
@scottmas Actually, we just released 3.2.6 and it includes some improvements for the app group name logic. Can you try _removing_ the `Info.plist` fields I asked you to add, and see if 3.2.6 fixes the issue?

If not, just add back the keys to Info.plist and it should work, I'm just curious!

**Comment by scottmas** [comment]
Sorry, I haven't got the chance to look yet! We're getting a release out today and I don't want to jeopardize it. I will try to let you know once we upgrade.

**Comment by paolo2796** [comment]
I have the same problem.. Anyone resolved it? Thank you.

**Comment by scottmas** [comment]
Setting the app group name in Info.plist fixes it. I haven't tested if the latest version fixes it automatically though.

**Comment by tudiantuan** [comment]
I have issue version 3.9.2... Anyone resolved it?
