### ISSUE TITLE
Huaweii ​and MIUI's custom notification sound from template doesn't play

### ISSUE THREAD

**Issue by pacozaa** [OneSignal/react-native-onesignal#602]
**Description:**
Hi! I have been successfully used this package with my apps for a while but the problem that happen is that Huaweii and MIUI's custom notification sound from template doesn't play. Even though, others phone work just fine and notification ring the right custom sound. Is there any problem with Huawei and MIUI phone?

**Environment**
1. `"react-native": "0.50.3",`
2. `"react-native-onesignal": "3.2.5"`

**Steps to Reproduce Issue:**
1. Set your custom template in Onesignal console with custom sound
2. Run android app with the right sound and template and compare result between Huawei and maybe Samsung.
3. Huawei and MIUIalways use their default sound

Thank for awesome package!

 Best,
Sarin

**Comment by jkasten2** [comment]
@pacozaa Is the Huaweii device you are testing on running Android Oreo (8.0) or newer? If so you will need to setup and use a Android Notification Channel / Category. See the details on below on setting up and using one.
https://documentation.onesignal.com/docs/android-notification-categories

**Comment by pacozaa** [comment]
@jkasten2 Thank you. Yes it is!

**Comment by Nightsd01** [comment]
If you still have any other problems please feel free to reply, otherwise it looks like Josh's reply should fix the issue

**Comment by pacozaa** [comment]
@Nightsd01 @jkasten2 Is it *require* to use Android Notification Channel / Category? Why? Why can't I use the same code ? What is a cause of problem?

I don't want to code the whole project again. It's not make sense.
