### ISSUE TITLE
Question: handling notifications received when the app is closed (swiped out), once the app is activated

### ISSUE THREAD

**Issue by rahamin1** [OneSignal/react-native-onesignal#608]
Hi Guys. 
### First of all, thank you!
Since this is my first post here, after few questions without replies :( in existing threads, I would like first to thank the creators of this package which seem to be my neighbors :)

### Description of the situation
- I start the app, then close it (swipe out or click on the 'X' at the top right)
- Notifications are received while the app is closed. Let's assume that 2 notifications are received
- When I click on the 1st notification's icon, the `onOpened` handler is triggered with the notification's data and I can process it and display it to the user
- What I would like to do is, once the user is done viewing the data of the 1st notification, is to access the 2nd notification and present it, without the need to click on its icon

### My questions
- How can I access notifications before the user clicked on their icons?
- If this can be done, can I dismiss the icon of the notification that I handle?

**Comment by Nightsd01** [comment]
Hi @rahamin1,

In iOS and Android, notifications can open apps in the background in different ways. 

In iOS, setting `content-available` to `true` will usually launch the app in the background, but not always. A more reliable strategy is to create a Notification Service Extension. However, this is basically like a mini separate process from your main app, a separate executable. The extension service will not launch the React native runtime and you’d have to implement it in swift or ObjC. 

When a notification is received with `mutable-content` set to `true`, it will launch the extension. Your extension should save the notification data to a shared app group suite with NSUserDefaults, which is the only way I am aware of that you can transfer data between an app and an extension service. 

I would recommend you simply do this on a backend server.

**Comment by rahamin1** [comment]
@Nightsd01 You answered another question... Read again :)
