### ISSUE TITLE
how do i get / set the badge count?

### ISSUE THREAD

**Issue by masterkrang** [OneSignal/react-native-onesignal#61]

**Comment by avishayil** [comment]
From OneSignal documentation:

`The OneSignal SDK automatically sets the badge count on your app to the number of notifications that are currently in the notification shade.`

https://documentation.onesignal.com/docs/android-notification-customizations

I think it's not possible atm.
Tagging @jkasten2 if he has any other toughts.

**Comment by masterkrang** [comment]
@avishayil thanks for the response. I found a way to do this without using OneSignal, which is to use a combination of `PushNotificationIOS`, and these methods from here: https://github.com/zo0r/react-native-push-notification#ios-only-methods

**Comment by avishayil** [comment]
@masterkrang that's great! I'm wondering if it would be interesting enough to borrow this functionality from these libraries and create a manageable badgeanager manager using this library. Thoughts? 

Anyway, it's not a library issue, so I'm closing this here.

**Comment by owsis** [comment]
hi @masterkrang, can I see your code how to implement badge count in IOS device.
