### ISSUE TITLE
display notification type in foreground on iOs wrong ?

### ISSUE THREAD

**Issue by dungnguyen10989** [OneSignal/react-native-onesignal#612]
I've initialize OneSignal as docs: 
```
OneSignal.init(ONESIGNAL_APP_ID, {
      kOSSettingsKeyAutoPrompt: true,
      kOSSettingsKeyInFocusDisplayOption: 2
    });

OneSignal.inFocusDisplaying(2);
```
On Android, it's run ok, but when the iOs device in foreground (isActive), the notification still appeares as AlertIOS, not be banner on the notification center.

and in AppDelegate.m: 
```
[OneSignal initWithLaunchOptions:launchOptions
                             appId:@"my-app-id"
          handleNotificationAction:nil
                          settings:@{kOSSettingsKeyAutoPrompt: @true}];
  OneSignal.inFocusDisplayType = OSNotificationDisplayTypeNotification;
```
but notification still appeares as AlertIOS, how can I fix it to appearing on the notification center ?

**Comment by dungnguyen10989** [comment]
@Nightsd01 help me pls !

**Comment by Nightsd01** [comment]
Hi @dungnguyen10989, apologies for the delay, are you sure you’re using the latest version of the SDK?

You should not initialize using _both_ the AppDelegate and JavaScript. Try removing all OneSignal code from `AppDelegate.m` and let me know if the problem still occurs.

**Comment by Nightsd01** [comment]
Closing due to no response - please feel free to reply if you're still having this problem and I'll be happy to reopen and investigate.
