### ISSUE TITLE
[iOS] When app is in background "opened" callback does not fire

### ISSUE THREAD

**Issue by steverob** [OneSignal/react-native-onesignal#613]
**Description:**
When the app is in background mode, and the user taps on an incoming notification, the `opened` callback is not firing.

When the app is in focus, and we have `OneSignal.inFocusDisplaying(2)` set, the notification shows and if the user taps it, nothing happens. `received` callback is fired though.

On Android, in both cases when I tap the notification, the `opened` callback is firing without any issues.

Is this the expected behaviour? What I want to happen is - when the notification is displayed (app is in background) and the user taps it, the app should be opened and the `opened` callback should be fired so that I can navigate the user to a screen (using a deeplink sent with `additionalData`).

**Environment**

OneSignal RN SDK - `3.2.6`
RN - `0.55.4`
iOS - `11.2.6`

**AppDelegate.m** - https://gist.github.com/steverob/25c969ded98dce44ca168309d67a103f

I followed the setup instructions detailed in the [documentation](https://documentation.onesignal.com/docs/react-native-sdk-setup#section-ios-installation) and also added the `Notification Service Extension`.

**Comment by motogod** [comment]
I have the same issue, but it happens on Android.

When the app is in background mode, the user taps on an incoming notification, the opened callback is not firing and  there is no additionalData in received callback.

I test it in Android simulator 8.0.0 and physical device 8.1.0.

Any one has the same issue even in Android or IOS ?

Environment
 "react": "16.3.1",
 "react-native": "~0.55.2",
 "react-native-onesignal": "^3.2.6"

**Comment by steverob** [comment]
Yeah I can confirm I can see this occasionally on android as well. 

--
Regards
Steve Robinson

**Comment by Nightsd01** [comment]
@steverob Apologies for the delayed response, can you reproduce this issue in our example project? If so - can you please upload it to dropbox and post a link?

The example project is in the `examples` folder of this repository. Clone the repo, run `npm i` (or yarn), run `react-native link react-native-onesignal` and try running the iOS project, replace with your own App ID, iOS bundle identifier, etc.

**Comment by Nightsd01** [comment]
Closing due to no response - if you're still running into this problem please feel free to respond and I'll be happy to reopen and help investigate

**Comment by steverob** [comment]
Yes this still happens. 

--
Regards
Steve Robinson

**Comment by Nightsd01** [comment]
@steverob since I cannot reproduce this issue, can you attempt to reproduce it in our demo project?

90% of the time when a user reports this problem it usually turns out to be user error, so it would be good to make sure you can reproduce it in our demo project. If you can, it would be very helpful to share a Dropbox link

**Comment by triasrahman** [comment]
It still happens, especially on iOS background service.
