### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by vahid263** [OneSignal/react-native-onesignal#615]
I am using Onesignal SDK in my android mobile app and myapp is behind a proxy server, how can I change the http://onesignal.com URL in my SDK?

**Comment by vahid263** [comment]
Actually I need to change the BASE_URL at below line(OneSignalRestClient.java)

private static final String BASE_URL = "https://onesignal.com/api/v1/";

but this file is read only and I can not make change!!

**Comment by Nightsd01** [comment]
You would need to remove OneSignal from your `build.gradle` and you would need to manually download the Android and iOS native SDK’s (links below) and modify them to change the URL. 

Once you change the URL, you’ll need to recompile both of them, compile Android SDK into a jar, and you can compile the iOS SDK into a framework or a static library, or even host it as a private cocoapod. 

We will consider making this easier in the future but unfortunately that’s the only way to do it today. 

https://github.com/OneSignal/OneSignal-Android-SDK
https://github.com/OneSignal/OneSignal-iOS-SDK

**Comment by vahid263** [comment]
Special Thank, and how can I recompile? 
is this ture command? " ./gradlew build "
this command didn't export Jar file?

**Comment by vahid263** [comment]
I changed this line and build a Jar file and use in my project but I have the following error:
`09-14 17:24:00.866 12761-13010/com.onesigtest E/dalvikvm: Could not find class 'android.app.job.JobInfo$Builder', referenced from method com.onesignal.NotificationRestorer.startDelayedRestoreTaskFromReceiver
09-14 17:24:02.081 12761-13114/com.onesigtest E/dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method com.onesignal.NotificationChannelManager.createChannel
09-14 17:24:02.081 12761-13114/com.onesigtest E/dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method com.onesignal.NotificationChannelManager.createDefaultChannel
09-14 17:24:02.081 12761-13114/com.onesigtest E/dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method com.onesignal.NotificationChannelManager.createRestoreChannel
09-14 17:24:30.896 12761-13072/com.onesigtest E/dalvikvm: Could not find class 'android.app.job.JobScheduler', referenced from method com.onesignal.OneSignalSyncServiceUtils.cancelSyncTask
09-14 17:24:30.901 12761-13072/com.onesigtest E/dalvikvm: Could not find class 'android.app.job.JobInfo$Builder', referenced from method com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob
`
