### ISSUE TITLE
libOneSignal.a has not been properly updated

### ISSUE THREAD

**Issue by cojo** [OneSignal/react-native-onesignal#616]
**Description:**

libOneSignal.a has not been properly updated to the latest native iOS SDK since 3.2.4 (native SDK 2.8.5).  This means that even though the Podfile points to a newer SDK version, the corresponding fixes will not be picked up by users who run manual installations (as we do).  This used to work fine.

**Environment**

Latest version available.  As mentioned above we simply npm install the project, then import the corresponding library from npm modules into XCode.

**Steps to Reproduce Issue:**

1. Simply install the project, or go in Github and browse the iOS directory.  Note that the libOneSignal.a file has not been updated alongside the podfile / version updates since 3.2.4 and you will not receive the corresponding fixes as a result.

**Comment by Nightsd01** [comment]
I’ve been maintaining this repo for nearly a year and I never knew it even _had_ a static binary 😂

Thanks for bringing this up, great catch. We’ll update it shortly.

**Comment by Nightsd01** [comment]
Thanks for bringing this up, we’ll fix it shortly. 

We have created release checklists for every SDK except this one, since the RN SDK was originally created by a different contributor, I’ll do that so we don’t forget things like this going forward.

**Comment by cojo** [comment]
Awesome, thanks so much for the quick response!  I figured there was a decent chance this might not be part of the standard release process since I know our workflow of manually importing / installing dependencies is atypical.  
Looking forward to what I think will hopefully fix some badge incrementing / app service extension issues we've been fighting with (I see the latest version has some fixes for it!) - thanks again!

**Comment by Nightsd01** [comment]
Sorry for the delay here, I've been working on a native iOS SDK update (2.8.8) and I just released that today, so I went ahead and released a new RN SDK update as well (3.2.7)!

We've also updated our release instructions so that we'll not forget to update the static library again. Thanks for pointing that out!
