### ISSUE TITLE
onReceived is not being fired when the app is killed

### ISSUE THREAD

**Issue by kaanduraa** [OneSignal/react-native-onesignal#617]
**Description:**

When the app is in foreground, onreceived works fine. However, when the app is killed, onReceived is not being fired. I check this by simple fetch operation in onReceived
(your description here)

**Environment**

1. 3.2.6
2. npm instal, react-native link

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by Nightsd01** [comment]
You need to set `content-available` to `true` to get iOS to launch the app in the background. But if the app is force-closed, the system will not launch the app, and there's not much we can do about this.

If you absolutely need some process to occur when notifications are received, check out the Notification Service Extension. It's a bit complex and it can't load the react-native runtime so you'd have to write it in Swift/ObjC.
