### ISSUE TITLE
Reporting message click event manually.

### ISSUE THREAD

**Issue by chitswe** [OneSignal/react-native-onesignal#618]
If notification is received while app is in focus, I want to show custom in app message. I use `OneSignal.inFocusDisplaying(0);` . But how can I report back message clicked status programatically.

**Comment by Nightsd01** [comment]
@chitswe You can use our REST API to do this, unfortunately our SDK does not currently provide a way to report custom notification opened events but it's relatively simple to use our API.

https://documentation.onesignal.com/reference#track-open
