### ISSUE TITLE
OneSignal.getPermissionSubscriptionState is not called on Android

### ISSUE THREAD

**Issue by faustoct1** [OneSignal/react-native-onesignal#619]
`````
OneSignal.getPermissionSubscriptionState((status) => {
  alert('ping')
});
`````

Can't get user token. Any issue related? It was working .. still working on ios but stopped on android.

**Comment by jfishman1** [comment]
I responded to your question through our support channel. Will close this here. Please direct further inquiries to our support channel.

**Comment by faustoct1** [comment]
Waiting on chat..
