### ISSUE TITLE
how do I stop OneSignal from resetting the badge count automatically?

### ISSUE THREAD

**Issue by masterkrang** [OneSignal/react-native-onesignal#62]
I am trying to maintain the badge count on the app icon until the user visits a specific section in my app. This section is in the TabBar and I want to bind the badge in the TabBar to the badge count. This is impossible if OneSignal clears the badge count automatically each time we receive notifications.

**Comment by avishayil** [comment]
From the docs:
https://documentation.onesignal.com/docs/android-notification-customizations
Try this, on your Android Manifest file:
`<meta-data android:name="com.onesignal.BadgeCount" android:value="DISABLE" />`
Not sure on iOS, though.

**Comment by masterkrang** [comment]
sorry this question was for iOS and I found the answer https://github.com/OneSignal/OneSignal-iOS-SDK/issues/11

**Comment by danhhgl** [comment]
Thanks @masterkrang
