### ISSUE TITLE
[Android Pie] Crashed when onReceive fired

### ISSUE THREAD

**Issue by abdullahizzuddiin** [OneSignal/react-native-onesignal#620]
**Description:**

My App crashed when received background notification. It resulted this error message:
```
java.lang.NoSuchMethodError: No static method zzc(Landroid/content/Context;)Lcom/google/firebase/iid/zzaa; in class Lcom/google/firebase/iid/zzaa; or its super classes (declaration of 'com.google.firebase.iid.zzaa' appears in base.apk)
	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:29)
	at com.google.firebase.iid.zzg.run(Unknown Source:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)
```

You can look my app/build.gradle in this link https://pastebin.com/kq7D6amV

I realized, this error only showed on Android Pie (Google Pixel 1). When I tried on other phone using prior version, it work normally.

**Environment**
1. What version of the OneSignal React-Native SDK are you using?
*react-native-onesignal": "^3.2.6*

2. How did you add the SDK to your project (eg. npm)
*npm install react-native-onesignal@latest*

3. Android Version:
*Android Pie 9.0*

**Steps to Reproduce Issue:**

1. run `npm install -- save react-native-onesignal@latest`
2. implement
`OneSignal.addEventListener('received', (notification)=>{console.log(notification)}`
3. Send messages without title, but insert some background data
4. Crashed

On my app logcat, it still be able to print the log (notification), shortly after that, my app crashed. Sometimes, the crash error messages printed before the log, but sometimes, it printed after the log.

**Comment by werlleydev** [comment]
@abdullahizzuddiin What version of the RN?

**Comment by Nightsd01** [comment]
@abdullahizzuddiin I cannot reproduce this issue on our own Android 9 devices. Also, I can no longer see your `app/build.gradle`, have you added our gradle plugin?

If not, please try adding this to the very top of your `app/build.gradle` and let me know if the issue still occurs:

```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.11.0, 0.99.99]'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

repositories {
    jcenter()
    maven { url 'https://maven.google.com' }
}
```

**Comment by Nightsd01** [comment]
@abdullahizzuddiin Would you also please post your `package.json`?

**Comment by anjar10** [comment]
I also experienced the same issue. I solved it by upgrading `com.google.gms:google-services` from 4.0.1 to  4.1.0.

**Comment by Nightsd01** [comment]
@abdullahizzuddiin can you post your `app/build.gradle` and give @anjar10’s suggestion a shot?

(Assuming you hadn’t already fixed this issue in the past 8 days, apologies for the delay we’ve been swamped/busy lately)

**Comment by Nightsd01** [comment]
Closing due to no response, if you're still having this problem please post and I'll be happy to reopen and help investigate

**Comment by abdullahizzuddiin** [comment]
Thank to @anjar10 my problem solved after I implement his suggestion. 

Thanks to you all :)

**Comment by pradeepconnecpath** [comment]
> I also experienced the same issue. I solved it by upgrading `com.google.gms:google-services` from 4.0.1 to 4.1.0.

@anjar10 : Can you  please elaborate the fix? Did you change in the build.gradle file? Would you mind pasting your file here?

**Comment by anjar10** [comment]
I just upgrade google service in `build.gradle` file which located in `<PROJECT_ROOT>\build.gradle`. Here is my `build.gradle` file:
```
...
buildscript {
    repositories {
        jcenter()
        google()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath 'com.google.gms:google-services:4.1.0'
    }
}
...
```
