### ISSUE TITLE
Question: is there a way to read notification data received while app was closed, without clicking the notification icon?

### ISSUE THREAD

**Issue by rahamin1** [OneSignal/react-native-onesignal#621]
#### I am talking about the following scenario (at the moment, I am developing only for android):

1. App is closed
2. Notification is received
3. User double clicks on the app to activate it

Is there a way to read the notification data without clicking on the notification icon?

**Comment by TuNguyenThanh** [comment]
+1

**Comment by chitswe** [comment]
https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding

**Comment by rahamin1** [comment]
Thanks @chitswe 
#### When the app is in the background I get onReceived events, with the data.
#### When the app is closed, however, I don't get any events, since it is closed... 

- If the user clicks on a notification icon, then I get the data in an onOpened event
- However, I don't know how to access notifications data if the user does not click on the notification icon. That's what I am looking for: the method to access these notifications without clicking them...

**Comment by chitswe** [comment]
You need to implement background service to receive notification as described in doc. You have to access notifications data in background service, not in your main app. But some android phone such as Xiaomi, Huawei block background service when the app is closed. One benefit of using background service is that when app is opened again user can get older notifications that should be received while the app is not running.

**Comment by giacomomasseron** [comment]
Where can I find doc about background service to receive notification?

**Comment by rahamin1** [comment]
3 messages above...
