### ISSUE TITLE
No such service ComponentInfo{com.bybes.app/com.onesignal.SyncJobService}

### ISSUE THREAD

**Issue by thedevdavid** [OneSignal/react-native-onesignal#624]
**Description:**
Integrated OneSignal with the official docs. iOS is working fine but Android immediately crashes when app in the background.

**Environment**
Latest React Native (0.56)
Latest OneSignal (3.2.6)
NPM (6.2.0)
MacOS

**Steps to Reproduce Issue:**
Install the OneSignal SDK using npm into your project
Link and implement using official docs
react-native run-android

**Comment by Nightsd01** [comment]
Please share a stack trace from the crash and I'll be happy to reopen the issue and help investigate

**Comment by thedevdavid** [comment]
@Nightsd01 ```No such service ComponentInfo{com.bybes.app/com.onesignal.SyncJobService}```

**Comment by Nightsd01** [comment]
@DLevai94 I am so sorry I didn't notice your response until now. Are you still encountering this problem with the latest version of our react-native SDK?

If so, can you please post the full stacktrace (not just that one line)?

**Comment by jkasten2** [comment]
@Nightsd01 There was another thread that @DLevai94 was able fix this issue
https://github.com/geektimecoil/react-native-onesignal/issues/623#issuecomment-423805687
