### ISSUE TITLE
how to send notifcations to all users and on custom tag

### ISSUE THREAD

**Issue by skokon** [OneSignal/react-native-onesignal#625]
Hello, im trying to send notification to all users and on custom filter tag like this

        let messageSettings = {
            headings: { en: 'onTag'},
            filters: [
                {field: 'tag', key: 'email', relation: 'exists'}
            ]
        }
        OneSignal.postNotification({
            'en': 'You got notification from user'
        }, {}, '17e3c78c-6c0b-4f31-9755-0b5f9a2e4662', messageSettings)

im entering my device player ID but im not receiving any notification any i want to post notify to all users

**Comment by mlop113** [comment]
let data = arr // some array as payload
let contents = {
	'en': 'You got notification from user'
}
OneSignal.postNotification(contents, data, '17e3c78c-6c0b-4f31-9755-0b5f9a2e4662');

**Comment by skokon** [comment]
@mlop113  what would this do.....

**Comment by Nightsd01** [comment]
@skokon This is not possible - you would need to use the OneSignal REST API key which you would NOT want to do on the client.

This functionality would definitely be something you would want to implement on your backend. After all, if someone ever knew your app ID and could send notifications to custom filters.....they could spam all your users.

https://documentation.onesignal.com/reference#section-send-to-users-based-on-filters

**Comment by skokon** [comment]
@Nightsd01 then can i send notifcation to all users depending on segemnt which its "ON_TAG" ?
