### ISSUE TITLE
Notification not received / no sound

### ISSUE THREAD

**Issue by nicovak** [OneSignal/react-native-onesignal#628]
**Description:**

There is an issue with the REST API, the notification is not received or the sound isn't triggered
It seems to be caused by multiple locale in `heading` and global locale in `contents`
Tested on **ANDROID 5.1** and **8.0**

**Environment**

- version `3.2.6 `
- yarn / react-native-link
- Last documentation followed

**Steps to Reproduce Issue:**

1. Initialize react-native-one-signal
3. Follwing the example, set your device to french locale (or the one missing in `contents` but present in `heading`)
2. Call the REST API with the following JSON content

**Not working**
```json
   "headings":{
      "en": "HELLO",
      "fr":"BONJOUR"
   },
   "contents":{
      "en":"Hi"
   },
```

**Working**
```json
   "headings":{
      "en": "HELLO",
      "fr":"BONJOUR"
   },
   "contents":{
      "en":"Hi",
      "fr":"Salut"
   },
```

**Comment by Nightsd01** [comment]
@nicovak That is strange, I am not able to reproduce this issue. Using your contents/headings from the example that doesn't work for you seems to work fine for me.

Are you using a custom sound?

**Comment by nicovak** [comment]
@Nightsd01  Thank you for your support.
Yes I am using a custom sound. Here is the full request without the data key:
As I said before, the phone must be on the `fr` locale because It's present in `headings` but not in `contents`

```json
{
   "app_id":"**********************",
   "headings":{
      "en":"⚠️ **********************",
      "fr":"⚠️ **********************"
   },
   "contents":{
      "en":"**********************",
   },
   "include_player_ids":[
      "**********************"
   ],
   "small_icon":"**********************",
   "large_icon":"**********************",
   "priority":10,
   "android_sound":"tone_01",
   "android_led_color":"FF331855",
   "ios_sound":"tone_01.wav",
   }
}
```

I may try with a logcat and see what happens

**Comment by Nightsd01** [comment]
@nicovak Sorry for the (very) delayed response. Are you still having this issue?

**Comment by nicovak** [comment]
@Nightsd01 Don't worry, the solution was to set `fr` and `en` in both `headings` and `contents` as I replied before. The issue is still present but the workaround is fine.
