### ISSUE TITLE
Custom notification for each screen

### ISSUE THREAD

**Issue by dungnguyen10989** [OneSignal/react-native-onesignal#632]
I'm building a realtime chat application, I want to receive the notification with sound when I'm being in ListConversationScreen, and receive the notification without sound when I'm being in DetailOfConversationScreen, how can I handle this feature ?

**Comment by Nightsd01** [comment]
There is no easy way to do this with our SDK - you would need to implement a NotificationExtenderService (Android) & Notification Extension Service (iOS) to do this natively for each platform.
