### ISSUE TITLE
package com.onesignal does not exist

### ISSUE THREAD

**Issue by devv-aman** [OneSignal/react-native-onesignal#633]
**Description:**

After linking react-native-onesignal to my project I'm getting following errors from react-native-onesignal project

![CMD screenshot](https://i.imgur.com/Xzx5AJd.png)

I have even searched for the error from previous issues and even on internet, but unable to find any solutions

My updated app/build.gradle file according to doc
```

buildscript {
    repositories {
        google()
        maven { url 'https://plugins.gradle.org/m2/' }
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
        classpath 'com.google.gms:google-services:4.0.2'
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.11.2, 0.99.99]'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.8.1'
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
```

**Environment**
**OneSignal React-Native Version:** 3.7.2

<br />

**Steps to add the SDK in my project**

1. npm i --save react-native-onesignal
2. react-native link react-native-onesignal
3. also added following line in app/build.gradle file, which was not added by react-native link

```
implementation project(':react-native-onesignal')
```

But Still I'm getting the error.
Thanks in advance

**Comment by jkasten2** [comment]
@entrepaman From the error it looks like the OneSignal native Java classes and even the react native classes are not being found. 

You can try to regenerate the android folder with the following?
```
sudo rm -rf android/
react-native eject
react-native upgrade //rebuilds android/ios folders
react-native link
react-native run-android
```

If that doesn't help it might be easiest to create a new react native project and setup things up again with the new project.

**Comment by Nightsd01** [comment]
Closing due to no response
