### ISSUE TITLE
Never getting push token or user id after initializing.

### ISSUE THREAD

**Issue by vinceprofeta** [OneSignal/react-native-onesignal#634]
**Description:**

We recently switched to react native and one signal. When users upgrade to the new app, One signal IDS never get fired. When asking for getPermissionSubscriptionState() we get the response below.

No user id, no push token, and its weird that userSubscriptionEnabled is true but subscriptionEnabled is false.

emailAddress: null
emailSubscribed: false
emailUserId: null
hasPrompted: true
notificationsEnabled: true
pushToken: null
subscriptionEnabled: false
userId: null
userSubscriptionEnabled: true

When install fresh version without upgrading, this is not an issue. 

I have tried to call every function in the API docs but nothing ever comes back for push token

**Environment**

**Steps to Reproduce Issue:**

1. Install old version of app
  2. Initialize the SDK on iOS
  3. Ids is never called

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by Nightsd01** [comment]
@vinceprofeta Are you sure that your App ID exactly matches the right bundle ID (ie `my.flappybird.clone`)? 

Please also note that iOS simulator does not allow push notifications, so if you're testing on simulator that is definitely the issue.

Lastly, if neither of those things is the case (your bundle ID matches and you are testing on real device), can you post your list of dependencies (package.json)?

**Comment by udarts** [comment]
I have the same thing, but then on android simulator and same real device:

userSubscriptionEnabled: 'true',
subscriptionEnabled: 'false',
notificationsEnabled: 'true'

The weird part is that it doesn't occur on all android devices, I have tested it on my Galaxy S9 (real device) and works. The simulator and real device are nexus 5 with nougat (7.1.1 and API 25). So far this simulator and device are the only ones having the issue.

**Comment by udarts** [comment]
According to the code (for android), it mentions the following:

// Notifications enabled for app? (Android Settings)
boolean notificationsEnabled = permissionState.getEnabled();

// User subscribed to OneSignal? (automatically toggles with notificationsEnabled)
boolean subscriptionEnabled = subscriptionState.getSubscribed();

So subscriptionEnabled should be the same as that notificationsEnabled is, but it is not for the version on android I mentioned above: 7.1 (API 25). Other versions seem to be fine.

**Comment by Nightsd01** [comment]
Closing due to no response - udarts has a separate issue open.

**Comment by eabuslaiman30** [comment]
Hey guys. I don't know if that problem is the same I had.
I was getting the userId (onIds callback) but the push token was null.

I fixed it by adding the following into the app/build.gradle file:

> compile 'com.google.android.gms:play-services-gcm:7.0.0'

I hope it works for someone.

**Comment by jkasten2** [comment]
@eabuslaiman30 That is odd, the SDK should already be pulling in FCM instead of GCM.

Adding that may have fixed your issue due to some dependency conflicts of other `com.google.android.gms` used in your project. At runtime you may have seen a `com/google/android/gms` class missing in your logcat.

[Adding the OneSignal Gradle Plugin](https://documentation.onesignal.com/docs/react-native-sdk-setup#section-adding-the-gradle-plugin) will solve this issue if this was the case.
