### ISSUE TITLE
EventListener events not firing at all

### ISSUE THREAD

**Issue by learnlapp** [OneSignal/react-native-onesignal#635]
I am having trouble with getting the event listeners to fire.

OneSignal.addEventListener('ids', this.onIds);

I tested this on iphone and android simulator.

init is working because I can see the player ids registering.

i am also able to send push notifications from the dashboard to the ios device and android simulator.

However, I am not able too get the userId from the "ids" event.

Tried 3.2.4 - 3.2.7

**Comment by Nightsd01** [comment]
Hi @manhldgs ,

The `ids` event only fires when the ID's actually change. So if you close the app and reopen it won't fire.

If you need a surefire way to get the ID's every time the app launches and not just deltas/changes, you can call `OneSignal.getPermissionSubscriptionState()`

Just to make sure there is not an issue here, can you try _completely_ uninstalling the app from your phone, reinstall it, and check to make sure the `ids` event fires?

**Comment by Nightsd01** [comment]
Closing due to no response

**Comment by rcidt** [comment]
@Nightsd01 I am seeing this issue. `getPermissionSubscriptionState` is also not firing for me. 

I upgraded from version `3.1.4` and this was working then.

**Comment by shahchaitanya** [comment]
@rcidt Call OneSignal.configure() to trigger onIds event every time.
