### ISSUE TITLE
Support iOS 12 in-app notification settings deep link

### ISSUE THREAD

**Issue by Dexwell** [OneSignal/react-native-onesignal#637]
**Description:**
iOS 12 allows us to provide the system a deep link to in-app notification settings, so that this shows a 'Configure In [app name]...' button to the user:

![Preview](https://b8f8d16bddc8b97ba822-09756f7ed83cedb9c95a6e172984ef2f.ssl.cf1.rackcdn.com/2018-9-11-0-34-48.jpeg)

I believe this is done through: [userNotificationCenter(_:openSettingsFor:)](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/2981869-usernotificationcenter).

It would be pretty sweet if we could set this up through react-native-onesignal.

**Environment**
npm react-native-onesignal version 3.2.1, iOS 12

**Comment by Nightsd01** [comment]
@Dexwell Great point! We are planning to do this. We actually currently support this functionality with our [iOS 12 Beta SDK](https://github.com/OneSignal/OneSignal-iOS-SDK/tree/beta), it is in its third (and probably final) release. We expect to release it publicly this week.

Once it is released, we will be bringing this functionality to react-native as well. Thanks!

**Comment by Dexwell** [comment]
@Nightsd01 Sweet! Does the new SDK aso support customizing the summary per thread (see section [Customizing group summary](https://mackuba.eu/2018/06/11/notifications-in-ios-12/))? Look forward to the release!

**Comment by Dexwell** [comment]
@Nightsd01 Is it possible yet to implement this?
