### ISSUE TITLE
Android: subscriptionEnabled not true even when approving permissions

### ISSUE THREAD

**Issue by udarts** [OneSignal/react-native-onesignal#638]
**Description:**

I am having an issue where when a user approves the permission (set using a manual popup). And I check the getPermissionSubscriptionState, it returns the following:

```` javascript
userSubscriptionEnabled: 'true',
subscriptionEnabled: 'false',
notificationsEnabled: 'true'
````

According to the code, it mentions the following:
```` javascript
// Notifications enabled for app? (Android Settings)
boolean notificationsEnabled = permissionState.getEnabled();

// User subscribed to OneSignal? (automatically toggles with notificationsEnabled)
boolean subscriptionEnabled = subscriptionState.getSubscribed();
````
So subscriptionEnabled should be the same as that notificationsEnabled is, but it is not for the version on android I mentioned below. Other versions seem to be fine.

**Environment**

So far only happening on Android Nougat 7.1 (API 25).
I followed the documentation as described on OneSignal (React-native documentation as I also use iOS).

**Steps to Reproduce Issue:**

I did all the steps as I should, but on SDK other than the 7.1, I receive the push notification (if approved by user).

This must be a bug in the SDK for android somehow.

Btw, this is the code I use to register on android:

```` javascript
if (Platform.OS === 'android') {
    OneSignal.init("id");
    // console.log(this.state.firstTime);
    Alert.alert(
        I18n.t('notifications title'),
        I18n.t('notifications subtitle'), 
       [
            {text: I18n.t('notifications no'), onPress: () => {
                OneSignal.setSubscription(false);
            }, style: 'cancel'},
            {text: I18n.t('notifications ok'), onPress: () => {
                OneSignal.setSubscription(true);
            }}
        ],
        { cancelable: false }
    )
}
````

**Comment by Nightsd01** [comment]
@udarts `subscriptionEnabled` and `notificationsEnabled` mean different things.

`subscriptionEnabled` is just the user's subscription status with _OneSignal_. Calling `setSubscription(true/false)` should only change `subscriptionEnabled` and nothing else.

`notificationsEnabled` indicates if the user has enabled/disabled notifications for your app. So if they go into Settings and disable notifications for your app, this setting will change.

I am not entirely sure what your issue is, actually. Are you saying that users are still able to receive notifications even after you call `OneSignal.setSubscription(false)`?

**Comment by udarts** [comment]
@Nightsd01 subscriptionEnabled toggles automatically with notificationsEnabled, as is what the comment in the code says, if this is not true, then it should be removed from the code. 

The issue seems only occurs on a simulator and real device with Android 7.1.

Android users get a custom modal asking them if they want to subscribe yes or no. If they click yes, setSubscription(true) is being called, after reloading the app, I check the getPermissionSubscriptionState and it says:

```` javascript 
userSubscriptionEnabled: 'true',
subscriptionEnabled: 'false',
notificationsEnabled: 'true'
````

So subscriptionEnabled is still false even if users say yes. 

And like I say, it only happens on the specific android version 7.1, any other versions, seem to be working as it should.

**Comment by jkasten2** [comment]
@udarts There is most likely an issue with the Android 7.1 device you are using. Either with the Google Play services app on the device or a connection issue with Google or OneSignal.
Make sure the Android emulator you have selected has Google Play services installed on it.

I recommend checking the logcat for any OneSignal, GCM, or FCM errors as this would tell you more details on why it isn't subscribing.

**Comment by udarts** [comment]
Thanks for the reply, on the real device I know the google play service app is installed, as far as I know on the simulator as well, but I will have a closer to logcat and see if I missed anything.

Will report back with the findings.

Cheers.

**Comment by udarts** [comment]
@jkasten2 I have looked at the logcat, but no errors (at least not related to OneSignal, GCM or FCM), so I start to think there is something really wrong with that version of android, as it seems to work with other versions.

**Comment by jkasten2** [comment]
@udarts I recommend checking your All users page to see if the device show up and if there is any errors there.
https://documentation.onesignal.com/docs/player-id#section-finding-player-ids

You can also message OneSignal support with the OneSignal player id from the device. They can check if they have any more details on their end.

**Comment by Nightsd01** [comment]
Closing due to no response
