### ISSUE TITLE
'OneSignal/OneSignal.h' file not found on Xcode 10

### ISSUE THREAD

**Issue by exclusiveTanim** [OneSignal/react-native-onesignal#640]
**Description:**

I am trying to configure the OneSignal on my end but got 'OneSignal/OneSignal.h' file not found error on my NotificationService.m file. I have followed everything from the documentation.

**Environment**

1. Xcode 10 with iOS 12

**Steps to Reproduce Issue:**
follow the steps from https://documentation.onesignal.com/docs/ios-sdk-setup

**Comment by exclusiveTanim** [comment]
I have got the solution. After re-installing the POD file its working fine on my end. Thanks

**Comment by DenisDov** [comment]
https://youtu.be/sLMCmXT4i9A

**Comment by rochapablo** [comment]
None of the comments above worked.

**Comment by thierryskoda** [comment]
I have the same error. @raymondctc, have you found a solution?

**Comment by OguzEkinci** [comment]
> I have got the solution. After re-installing the POD file its working fine on my end. Thanks

if u are working on vscode, you should delete pod folder in xcode and vscode. after you pod install, that might be
