### ISSUE TITLE
Push notifications are not shown when the app is being opened (in foreground)

### ISSUE THREAD

**Issue by duongkhoilinh** [OneSignal/react-native-onesignal#641]
**Description:**

Hi, I'm using react-native-onesignal in my app and push notifications are showing 100% of the time when the app isn't being used (in foreground). However, when the app is being opened, notifications are not shown and the listeners are not being triggered either

**Environment**

* I'm using OneSignal React-Native SDK v3.2.7, added via `yarn`
* macOS version: Mojave
* XCode version: 9.4.1
* Device: Apple iPhone 6, running iOS 11

My code is based on the code of [RNOneSignal example](https://github.com/geektimecoil/react-native-onesignal/tree/master/examples/RNOneSignal):

```
class Root extends Component {
  constructor(props) {
    super(props)
    this.onReceived = this.onReceived.bind(this)
    this.onOpened = this.onOpened.bind(this)
    this.onIds = this.onIds.bind(this)
  }
  componentWillMount() {
    console.warn(new Date())
    console.warn('componentWillMount')
    OneSignal.setLogLevel(7, 0);
    OneSignal.inFocusDisplaying(2);
    OneSignal.init(MY_APP_ID);
    OneSignal.configure({});
    OneSignal.addEventListener('received', this.onReceived);
    OneSignal.addEventListener('opened', this.onOpened);
    OneSignal.addEventListener('ids', this.onIds);
  }

  componentWillUnmount() {
    console.warn('componentWillUnmount')
    OneSignal.removeEventListener('received', this.onReceived);
    OneSignal.removeEventListener('opened', this.onOpened);
    OneSignal.removeEventListener('ids', this.onIds);
  }

  onReceived(notification) {
    console.warn("Notification received: ", notification);
  }

  onOpened(openResult) {
    console.warn('Message: ', openResult.notification.payload.body);
    console.warn('Data: ', openResult.notification.payload.additionalData);
    console.warn('isActive: ', openResult.notification.isAppInFocus);
    console.warn('openResult: ', openResult);
  }

  onIds(device) {
    console.warn('Device info: ', device);
  }
	render(){
		return(
			<Provider store={store}>
				<App />
			</Provider>
		);
	}
}
```
**PS:** When I use the same app ID on the [RNOneSignal example app](https://github.com/geektimecoil/react-native-onesignal/tree/master/examples/RNOneSignal), everything works fine (notifications are shown while the app is in background as well as foreground)

**Comment by Nightsd01** [comment]
Hi @duongkhoilinh, thank you for the detailed issue!

Have you implemented the OneSignalNotificationServiceExtension?

Can you post your `package.json` so I can see your dependencies?

**Comment by duongkhoilinh** [comment]
Hi @Nightsd01, thanks for the quick reply.
Yes, I implemented the `OneSignalNotificationServiceExtension` as shown [here](https://documentation.onesignal.com/v5.0/docs/react-native-sdk-setup#section-add-notification-service-extension)
This is my `package.json` file:
```
{
  "name": "berrys",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "clean": "watchman watch-del-all && rm -rf node_modules && rm -rf $TMPDIR/react-* && npm cache clean --force && yarn",
    "test": "jest"
  },
  "dependencies": {
    "lodash": "^4.17.11",
    "react": "16.3.1",
    "react-native": "^0.55.4",
    "react-native-collection": "^2.0.8",
    "react-native-dropdownalert": "^3.5.0",
    "react-native-elements": "^1.0.0-beta5",
    "react-native-fbsdk": "^0.7.0",
    "react-native-firebase": "^4.3.8",
    "react-native-flash-message": "^0.1.9",
    "react-native-google-signin": "^1.0.0-rc6",
    "react-native-grid-component": "^1.1.0",
    "react-native-image-picker": "^0.26.10",
    "react-native-instagram-login": "^1.0.7",
    "react-native-linear-gradient": "^2.4.0",
    "react-native-linkedin-sdk": "^0.0.9",
    "react-native-local-storage": "^1.5.2",
    "react-native-onesignal": "^3.2.7",
    "react-native-square-grid": "^1.0.5",
    "react-native-swiper": "^1.5.13",
    "react-native-vector-icons": "^5.0.0",
    "react-native-xml2js": "^1.0.3",
    "react-navigation": "^2.1.0",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.10.12"
  },
  "devDependencies": {
    "babel-jest": "23.0.1",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.1.0",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./src/app/fonts/"
    ]
  }
}
```

**Comment by Nightsd01** [comment]
@duongkhoilinh can you try searching your codebase for **any** usage of `OneSignal.inFocusDisplaying` to make sure you are not setting it to 0 anywhere?

Furthermore, can you try removing ALL usage of `OneSignal.inFocusDisplaying` to see if that's potentially causing the issue?

**Comment by Nightsd01** [comment]
Closing due to no response - please answer the above comment if you are still having this issue and I'll be happy to reopen + help investigate

**Comment by duongkhoilinh** [comment]
Hi @Nightsd01, sorry for the late reply, in my app I set `OneSignal.inFocusDisplaying` to `2`. More code:
```
OneSignal.setLogLevel(7, 0);
OneSignal.inFocusDisplaying(2);
OneSignal.init('my-app-id', { kOSSettingsKeyInFocusDisplayOption: 2 });
OneSignal.configure({});
```

**Comment by sonlexqt** [comment]
I'm having the same problem 😞

**Comment by hyochan** [comment]
@duongkhoilinh I think you should use `OneSignal.inFocusDisplaying(2)` after `Onesignal.init`.
Also, bear in mind that you are trying to do the same thing `{ kOSSettingsKeyInFocusDisplayOption: 2 }` and `OneSignal.inFocusDisplaying(2)`.

**Comment by rukmanary** [comment]
I still have this problem. Any other solution? I call Onesignal in ComponentDidMount. it works on Android, but not in iOS
