### ISSUE TITLE
Push notifications with delay or onOpeningApp() [Error]

### ISSUE THREAD

**Issue by MayeuldP** [OneSignal/react-native-onesignal#644]
**Description:**

* Does anyone got the same issue ? Most of the push notifications for my users works well. However I have some of them who're receiving the push notification only when they open the application.
 But since it's not the case for everyone of them, it's weird. It's not because of some OS, I have users with Samsung's devices having this problem too.

* Another trouble, is peoples who're receiving the notifications only hours after. I checked that : [OneSignal Notifications delayed](https://documentation.onesignal.com/docs/notifications-delayed) but didn t help me.

If anyone had similar problems and succeed to resolve them, I'd be grateful to have some clues for any fix.
**Environment**
```
react-native-onesignal : ^3.1.0
react-native-cli: 2.0.1
react-native: 0.55.3
```

**Comment by Nightsd01** [comment]
@MayeuldP Please post some more info: what version/s of `react-native-onesignal` are were you using in the version/s of your app that had this issue for these devices? Are they all Android? Are you setting the `priority` parameter on the notifications?

Also, why specifically did that article not help you?

**Comment by Nightsd01** [comment]
Closing issue due to no response - please add more information if you are still facing this problem and I'll be happy to reopen the issue
