### ISSUE TITLE
actionSelected missing on Android, raw payload not parsed

### ISSUE THREAD

**Issue by XenorPLxx** [OneSignal/react-native-onesignal#645]
**Description:**
Hello!

I've noticed that payload when clicking notification button (system notification, app in background or closed) is different on Android than iOS.

Example iOS payload:
```
{
  "isAppInFocus": false,
  "shown": true,
  "payload": {
    "rawPayload": {
      "custom": {
        "ti": "f2ae2db1-e0e2-412d-85bf-79b260f7aefe",
        "a": {
          "actionSelected": "testaction",
          "type": "some-test-type"
        },
        "i": "8c67ea65-eb65-4d1b-97e4-0c5dd258bec3",
        "tn": "TEST BUTTONS TEST"
      },
      "buttons": [
        {
          "i": "cancel",
          "n": "cancel"
        },
        {
          "i": "testaction",
          "n": "testaction"
        }
      ],
      "aps": {
        "alert": {
          "body": "TEST",
          "title": "TEST",
          "subtitle": "TEST"
        },
        "sound": "default",
        "mutable-content": 1
      }
    },
    "additionalData": {
      "actionSelected": "testaction",
      "type": "some-test-type"
    },
    "subtitle": "TEST",
    "title": "TEST",
    "actionButtons": [
      {
        "text": "cancel",
        "id": "cancel"
      },
      {
        "text": "testaction",
        "id": "testaction"
      }
    ],
    "sound": "default",
    "body": "TEST",
    "notificationID": "8c67ea65-eb65-4d1b-97e4-0c5dd258bec3"
  }
}
```

Example Android payload:
```
{
  "payload": {
    "fromProjectNumber": "379304984365",
    "groupMessage": "",
    "lockScreenVisibility": 1,
    "rawPayload": "{\"google.delivered_priority\":\"normal\",\"google.sent_time\":1538641721460,\"google.ttl\":259200,\"google.original_priority\":\"normal\",\"custom\":\"{\\\"a\\\":{\\\"type\\\":\\\"some-test-type\\\",\\\"actionButtons\\\":[{\\\"id\\\":\\\"cancel\\\",\\\"text\\\":\\\"cancel\\\",\\\"icon\\\":\\\"cancel\\\"},{\\\"id\\\":\\\"testaction\\\",\\\"text\\\":\\\"testaction\\\",\\\"icon\\\":\\\"testaction\\\"}],\\\"actionSelected\\\":\\\"__DEFAULT__\\\"},\\\"ti\\\":\\\"f2ae2db1-e0e2-412d-85bf-79b260f7aefe\\\",\\\"i\\\":\\\"cf39a3e1-3b4f-4a9a-940d-7ed31cf20dd7\\\",\\\"tn\\\":\\\"TEST BUTTONS TEST\\\"}\",\"oth_chnl\":\"\",\"pri\":\"5\",\"vis\":\"1\",\"from\":\"379304984365\",\"alert\":\"TEST\",\"title\":\"TEST\",\"grp_msg\":\"\",\"google.message_id\":\"0:1538641721465276%55c8ede1f9fd7ecd\",\"actionSelected\":\"testaction\",\"notificationId\":1995481635}",
    "additionalData": {
      "type": "some-test-type"
    },
    "body": "TEST",
    "actionButtons": [
      {
        "icon": "cancel",
        "text": "cancel",
        "id": "cancel"
      },
      {
        "icon": "testaction",
        "text": "testaction",
        "id": "testaction"
      }
    ],
    "title": "TEST",
    "priority": 5,
    "notificationID": "cf39a3e1-3b4f-4a9a-940d-7ed31cf20dd7"
  },
  "displayType": 0,
  "androidNotificationId": 1995481635,
  "shown": true,
  "isAppInFocus": false
}
```

As you can see actionSelected is available on Android only, when raw payload is parsed manually. On iOS both raw payload is parsed and actionSelected is available as separate field.

**Environment**

1. What version of the OneSignal React-Native SDK are you using?
3.2.7
2. How did you add the SDK to your project (eg. npm)
yarn
3. OS
Android 8, iOS 12.1 Beta 2

**Steps to Reproduce Issue:**

1. Install and setup push notifications (with extension for buttons on iOS)
2. Add `opened` `eventListener` with `console.log`
3. Send notification with buttons, while app in background or closed.
4. Click action button.
5. Compare result on Android and iOS

**Comment by Nightsd01** [comment]
You are checking the `notification` object, but you need to check the result of the `opened` event/callback. At the root of that object there is an `action` property that looks like this (on both Android and iOS):

```
{
   "notification" : {
      //notification with payload JSON here 
   },
   "action" : {
      "actionID" : "action_id_here",
      "type" : 1 
   }
}
```

Due to legacy codebase decisions, the actual notification JSON is structured differently on both platforms unfortunately, so for diving deeper you would need to use `Platform.OS` checks and have separate android/ios implementations.

But fortunately the actual `action` property will be the same on Android/iOS so your currently question should be solved. 

In the future we plan to initiate a major refactor of our react-native SDK so that it is a bit cleaner. I'll make it a lot more like our Flutter SDK where the schema/structure of objects like Notifications is _exactly_ the same whether it's in Android or iOS.

**Comment by XenorPLxx** [comment]
OH! That is indeed correct, thank you for your help :D.
