### ISSUE TITLE
Bridging header? How to make one?

### ISSUE THREAD

**Issue by ilyakar** [OneSignal/react-native-onesignal#647]
**Description:**
I followed the readme for setting up Onesignal and came to the part of setting up a bridging header.
![image](https://user-images.githubusercontent.com/1760709/46488496-1d7d2d00-c803-11e8-8ce3-e7d1d79eb55d.png)
All the details up until this point were very clear and now I have no idea what you want me to do.
Please advise.

**Environment**
Irrelevant

**Comment by Nightsd01** [comment]
@ilyakar If you are a beginner to Xcode/Swift, I would not suggest using Swift unless you absolutely have to. The bridging header adds complexity and for the time being, adding even a single line of swift increases the size of your app by several MB.

But if you must use Swift, here is how to set the bridging header: create a new header file in your Xcode project. Inside of the header file, call:

```
#import "RCTOneSignalExtensionService.h"
```

Then you need to tell your Xcode project settings what your bridging header is named, [like this](https://stackoverflow.com/questions/31716413/xcode-not-automatically-creating-bridging-header)

**Comment by ilyakar** [comment]
Aah. So I only need to add the bridging header if I used some swift? In that case as I understand I can disregard that step. Thanks for clarifying!
