### ISSUE TITLE
Only Receive Notification When the app is active or minimised, no notification when it is closed

### ISSUE THREAD

**Issue by Mixpeal** [OneSignal/react-native-onesignal#648]
I went through other issues, nothing has worked for me.

I have also add this: https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding

Still not working, is there anything special with this, 

Note: notifications are either sent from wordpress plugin or Onesignal Site

**Comment by Nightsd01** [comment]
@Mixpeal Please add more details. You did not follow our issue template. Please add basic information such as what version of the SDK you are using, whether this is occurring only on android/ios/both, whether this occurs on multiple devices, just simulator, etc.

I will reopen the issue once you add some more information

**Comment by giacomomasseron** [comment]
I have the same problem.

I installed the package, followed the guide, added this code to my App.js file:

    componentWillMount() {
        OneSignal.init("...");

        OneSignal.addEventListener('received', this.onReceived);
        OneSignal.addEventListener('opened', this.onOpened);
        OneSignal.addEventListener('ids', this.onIds);
    }

    componentWillUnmount() {
        OneSignal.removeEventListener('received', this.onReceived);
        OneSignal.removeEventListener('opened', this.onOpened);
        OneSignal.removeEventListener('ids', this.onIds);
    }

    onReceived(notification) {
        log("Notification received: ", notification);
    }

    onOpened(openResult) {
        log('Message: ', openResult.notification.payload.body);
        log('Data: ', openResult.notification.payload.additionalData);
        log('isActive: ', openResult.notification.isAppInFocus);
        log('openResult: ', openResult);
    }

    onIds(device) {
        log('Device info: ', device);
    }

But I get the message only when app is opened or in background.  
If the app is closed I do not get any message.

**Comment by 1129530686** [comment]
I get the message only when app is opened or in background.
If the app is closed I do not get any message
