### ISSUE TITLE
I want alarm

### ISSUE THREAD

**Issue by 532815096** [OneSignal/react-native-onesignal#650]
this notification meet my needs？and how ？

**Comment by jkasten2** [comment]
@532815096 Please see the following guide on what OneSignal push notifications can do.
https://documentation.onesignal.com/docs

Then follow the setup guide here.
https://documentation.onesignal.com/docs/react-native-sdk-setup

If you run into any issue or have any additional questions I recommend contacting OneSignal support.
If you find an issue with this SDK please open a new issue and we can look into it. Thanks!
https://documentation.onesignal.com/docs/react-native-sdk-setup
