### ISSUE TITLE
Duplicate Classes Issue: Program type already present: com.google.android.gms.common.api.internal.zzb

### ISSUE THREAD

**Issue by zakayothuku** [OneSignal/react-native-onesignal#655]
![image](https://user-images.githubusercontent.com/3469965/47074079-55707100-d202-11e8-941d-5978b63c65b6.png)

Here's the setup
![capture](https://user-images.githubusercontent.com/3469965/47074137-75a03000-d202-11e8-8e23-4980d3a4202a.PNG)

![Uploading Capture.PNG…]()

I keep getting a duplicate_classes error even after doing the fix.
What could be the issue?

**Comment by jkasten2** [comment]
@schatzdesigns This error normally means that their is a conflict with another plugin in your project including an incompatible version of the Google Play services library.

Can you double check you have added this Gradle plugin correctly?
https://documentation.onesignal.com/docs/react-native-sdk-setup#section-adding-the-gradle-plugin

If you are still seeing an issue please provide a step-by-step guide on reproducing the issue with a new react native project.

**Comment by Nightsd01** [comment]
Closing issue due to no response. Please feel free to reply if you are still having this problem and we'll be happy to reopen the issue and help investigate.
