### ISSUE TITLE
Badge increment is not working, 

### ISSUE THREAD

**Issue by ashish-czone** [OneSignal/react-native-onesignal#656]
**Description:**

Hey guys,

I am unable to get badge count increment working on iOS. Followed all the steps mentioned in the documentation but can't get the badge notification or even image attachment in the notifications. Its almost like the NotificationServiceExtension didn't exist at all.

**Environment**

xcode 10, 
react native 0.57.2, 
onesignal 3.2.7

Added the SDK using npm install

**Steps to Reproduce Issue:**

1. npm install react-native-onesignal
2. Follow react native  set up instructions https://documentation.onesignal.com/docs/react-native-sdk-setup
3. Compile and upload on testflight

**Anything else:**

1. Main App Target-> App groups-
<img width="1397" alt="screen shot 2018-10-18 at 11 28 14 am" src="https://user-images.githubusercontent.com/1729518/47134248-ab5c1c00-d2c9-11e8-9de5-c3d73cf0de69.png">

2. OneSignalExtension target-
a) Added libraries
<img width="1363" alt="screen shot 2018-10-18 at 11 30 13 am" src="https://user-images.githubusercontent.com/1729518/47134252-abf4b280-d2c9-11e8-84e5-7f9d841d8bab.png">
b) Modified NotificationService.m
<img width="1307" alt="screen shot 2018-10-18 at 11 31 21 am" src="https://user-images.githubusercontent.com/1729518/47134253-abf4b280-d2c9-11e8-983b-bee32d69f570.png">
c) App groups (You can cross-check from the screenshot that its the same as in the main target)-
<img width="1387" alt="screen shot 2018-10-18 at 11 32 26 am" src="https://user-images.githubusercontent.com/1729518/47134256-ac8d4900-d2c9-11e8-9728-6ff5888115f1.png">
d) Added Header search path-
<img width="1405" alt="screen shot 2018-10-18 at 11 32 44 am" src="https://user-images.githubusercontent.com/1729518/47134257-ac8d4900-d2c9-11e8-8119-0252d543106d.png">

**Comment by Nightsd01** [comment]
@ashish-czone Do you have the same app group set up for _both_ your app target & notification service extension?

Our RN SDK setup docs specifically say to follow this guide:

https://documentation.onesignal.com/docs/ios-sdk-app-groups-setup#section-2-enable-app-groups-capability

**Comment by ashish-czone** [comment]
@Nightsd01 Thanks for the reply.

I have added screenshots of my system in the original issue, Please refer. The app groups are exactly the same and follow the pattern as specified in the docs.

However, please note that when I try to send an image (uploaded a jpg from my computer), I do not see it in the notification received in the phone. So, it seems that the extension (created by following the docs, that is supposed to enable images and sound in the notifications) itself isn't doing anything.

I suspect that the issue could be due to the fact that I am using the latest version of react native (0.57.2) and of xcode (10). Please confirm if this library is tested to work with these versions.

**Comment by ashish-czone** [comment]
It seems that the issue was related to 'deployment target'. The deployment target was set to ios version 12.0 in the Extension that I had created while I was testing on ios version 11.4.1,  I retried today morning and now the image as well as the badge count increment is working fine!!

I am closing this issue as of now, hopefully, this will now keep working :-)

**Comment by FayyazAliKhan1** [comment]
@ashish-czone I have tried alot but still my batch is not showing in ios I changed the deployment versions but still not 
could anyone please let me know what's the issue I am using latest onesignal verison, although I m receiving notifications but the badge count is not showing, in my iphone the badge switch is also on
