### ISSUE TITLE
Is the location updated when the app is in background? 

### ISSUE THREAD

**Issue by iesteban** [OneSignal/react-native-onesignal#657]
I want to trigger a notification when the user enters in a specific zone. Geofencing. 

It should be independent of whether the user opens the app or not. 

I haven't found any information related. 

Thank you so much!

**Comment by Nightsd01** [comment]
Yes - in iOS specifically you will want to enable the Background Location Updates capability and add a `NSLocationAlwaysUsageDescription` description to your app's `Info.plist`.
