### ISSUE TITLE
IOS Notifications permission failed

### ISSUE THREAD

**Issue by sohutek** [OneSignal/react-native-onesignal#658]
Thanks for being here, wish you guys the best. I've set up successfully. But the only problem i've gotten is when i opened my app the first time. It didn't ask me for Notifications Permission. And there was no Notifications permission in my app's settings. I really don't know why. What did i miss?

**Comment by CesarDenis** [comment]
@sohutek I'm in trouble, how did you solve it?

**Comment by harzkr** [comment]
Did you solve this @CesarDenis @sohutek
