### ISSUE TITLE
sendTags Docs

### ISSUE THREAD

**Issue by c-h-** [OneSignal/react-native-onesignal#66]
I believe the sendTags docs need to be updated.

the following code on Android resulted in an error for me that the OneSignal native module expected a map but instead got 2 strings (e.g. native module only accepts the object format not two string arguments).

``` javascript
// Sending single tag
OneSignal.sendTags("key", "value");

// Sending multiple tags
OneSignal.sendTags({key: "value", key2: "value2"});
```

**Comment by avishayil** [comment]
Hi, Thanks for reporting this.
I'll have a look.

**Comment by Izitable** [comment]
Hi, i believe the issue is an extra 's'.

Just tried on Android with success the following:
`OneSignal.sendTag("key", "value");`

**Comment by bitcoinvsalts** [comment]
+1 still there: OneSignal.sendTags("key", "value");
