### ISSUE TITLE
It just stopped working, didn't chane anything

### ISSUE THREAD

**Issue by fragilehm** [OneSignal/react-native-onesignal#670]
```
OneSignalPlugin: WARNING: OneSignalPlugin: Downgraded 'com.android.support:28.0.0' -> 27.+ to prevent compile errors! Recommend updating your project's compileSdkVersion!
```

```
compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        applicationId "bundleId"
        minSdkVersion 22
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
```

**Comment by peterkuiper** [comment]
I'm having the same problem

**Comment by jkasten2** [comment]
I recommend checking that you don't have `com.android.support` with a plus `+` version anywhere in your `build.gradle` files as this would have tried to automatically upgrade to version `28`.

The OneSignal-Gradle-Plugin in this case prevented a build issue with your project. This is just a warning so everything just be still working fine.

The other option is you can upgrade to `compileSdkVersion` to `28` to remove the warning.

**Comment by Nightsd01** [comment]
@fragilehm Please let me know if @jkasten2's advice has fixed the issue for you or not.

**Comment by dvsingh9** [comment]
did everything, same issue here with ionic
