### ISSUE TITLE
OneSignal inFocusDisplaying(2) Notification Shade not working in Android

### ISSUE THREAD

**Issue by damiththamara** [OneSignal/react-native-onesignal#671]
**Description:**
I'm using OneSignal React Native SDK and successfully integrated OneSignal with both Android and IOS and push notifications are working perfect as well. 

But there is an issue with displaying the notifications.  I wanted to use the notification Shade, which is [2] option for the `inFocusDisplaying` method. IOS started to working after adding the optional parameter 
 `kOSSettingsKeyInFocusDisplayOption` to the init function but couldn't get shade notifications to work on Android. Options [0] and [1] are working by the way. 

Already gone through the previously posted issues but only found inFocusDisplaying issues related to IOS.
**Notifications are working only need  notification Shade to work on Android**. `inFocusDisplaying(2)`

**Environment**
1. OneSignal React-Native SDK Version - 3.2.8
2. How did you add the SDK to your project (eg. npm) - npm
3. React Native Version - 0.56.0

**Steps to Reproduce Issue:**

  1. Install the OneSignal SDK using npm
  2. Initialize the SDK in Android index.js (Used a separate function to trigger init when a user logged in)
  3. Attempt to receive a push notification

**Anything else:**

This is the function where I'm initializing the SDK.
    
> subscribe = () => {
>         this.mode = "subscribe";
>         os.init(contants.ONESIGNAL_APP_ID, {kOSSettingsKeyInFocusDisplayOption:  2});
>         os.setSubscription(true);
>         os.inFocusDisplaying(2);
>         this.addEventListeners();
>         os.configure();
>     }
>

**Comment by taminhtien** [comment]
Same problem for me. iOS works but android not work.

**Comment by noway** [comment]
Happens for me on iOS too. This is pretty important imo.

**Comment by noway** [comment]
Any update on this?

**Comment by Nightsd01** [comment]
I've tested this and I am not able to reproduce. Looking at the OP's code, it seems like the issue would likely be that his `subscribe()` function isn't getting called?

Please make sure to call `OneSignal.init()` immediately when the app launches, don't wait until some later point. If you don't want the user to receive push notifications and don't want them to get prompted for permission, that's fine, but don't delay initialization of the SDK. 

Also, please call `OneSignal.inFocusDisplaying()` before you call `OneSignal.init()`.

**Comment by noway** [comment]
@Nightsd01 

Sorry, didn't see my github notification. Still doesn't work for me, no luck receiving notifications when the app is open, although out of app notifications are received fine.

> it seems like the issue would likely be that his subscribe() function isn't getting called?

I tried calling `OneSignal.subscribe()`, but it's not a function.

> Please make sure to call OneSignal.init() immediately when the app launches, don't wait until some later point

I'm calling it in componentDidMount

> please call OneSignal.inFocusDisplaying() before you call OneSignal.init().

tried that, still no luck.

I'm initialising OneSignal like this (in `src/Main.js` component):

```javascript
  componentDidMount() {
    console.disableYellowBox = true

    OneSignal.inFocusDisplaying(2)
    OneSignal.setSubscription(true)
    // OneSignal.subscribe(true)
    OneSignal.init(oneSignalAppId, {
      kOSSettingsKeyAutoPrompt: false,
      kOSSettingsKeyInFocusDisplayOption: 2,
    })
    OneSignal.configure()
    OneSignal.enableSound(true);
    OneSignal.enableVibrate(true);
    OneSignal.addEventListener('received', this.onReceived);
    OneSignal.addEventListener('opened', this.onOpened);
    OneSignal.addEventListener('ids', this.onIds);

    this.authenticate()
  }
```

That's my index.js
```javascript
import React, { PureComponent } from 'react'
import { AppRegistry } from 'react-native'
import { Provider as StoreProvider } from 'react-redux'
import App from 'src/Main'

import configureStore from 'src/store/configureStore'

const store = configureStore()

class app extends PureComponent {
  render() {
    return (
      <StoreProvider store={store}>
        <App />
      </StoreProvider>
    )
  }
}

AppRegistry.registerComponent('app', () => app)
```

Anything wrong you can pick out?

**Comment by noway** [comment]
Any update on this?

**Comment by rgomezp** [comment]
Hi @noway,
Sorry for the delay. Make sure to initialize OneSignal before you do anything else. Check out the [usage](https://documentation.onesignal.com/docs/react-native-sdk-setup#section-usage) in our documentation.

**Comment by rgomezp** [comment]
Closing for now. Feel free to reply here and tag us and we can re-opoen the issue

**Comment by noway** [comment]
I'll try to test it next week.

**Comment by NewBieBR** [comment]
Same problem for me on iOS and Android.
```javascript
    OneSignal.init(ONESIGNAL_APP_ID, {
      kOSSettingsKeyAutoPrompt: false,
      kOSSettingsKeyInFocusDisplayOption: 2,
    });
    OneSignal.inFocusDisplaying(2);
    OneSignal.addEventListener('received', this.onReceived);
    if (__DEV__) {
      OneSignal.addEventListener('opened', this.onOpened);
      OneSignal.addEventListener('ids', this.onIds);
    }
    if (this.props.player.id) {
      OneSignal.setExternalUserId(this.props.player.id);
    }
    OneSignal.configure();
```

**Comment by noway** [comment]
I haven't tested rejigging initialization code, i still experience this too.

**Comment by BrunoPes** [comment]
I'm with the same problem on Android. When I try out `inFocusDisplaying()` with the values `0` and `1`, it works fine. The `0` does nothing with incoming notification, and the `1` value shows inapp Alert with the notification title and body correctly, just like is documented.
But the `2` value does nothing, and it's working exactly like the `0`.

In fact, doing debugs, I could realize that the incoming notification has the key `displayType` with value `0`, even when I'm using `inFocusDisplaying(2)`. Just don't get it what is happening here...

**Note: The Notification Shade never appears, on back or foreground, and even with the app in dead state. It only triggers the notification sound and it shows the app icon on Android StatusBar.** 

Here's my code:
```js
export function initOneSignal() {
  OneSignal.init(APP_ID);
  OneSignal.inFocusDisplaying(2);
  OneSignal.setSubscription(true);
  OneSignal.configure();
  return;
}
```

**My enviroment**:

1. react: 16.4.0
2. react-native: 0.55.0
3. react-native-onesignal: 3.2.14

**Android**:
1. buildToolsVersion: 27.0.3
2. minSdkVersion: 16
3. compileSdkVersion: 27
4. targetSdkVersion: 26
5. supportLibVersion: 26.1.0

**Comment by rgomezp** [comment]
Thanks for your patience while we investigate

**Comment by dktlabs** [comment]
@BrunoPes can you try this: https://github.com/geektimecoil/react-native-onesignal/issues/164#issuecomment-275311345  ?

**Comment by dktlabs** [comment]
I can confirm that this is still not working in my production app. @rgomezp any news on that ?
I'm using a Galaxy s7

**Comment by rgomezp** [comment]
Howdy @EnanlyPay ,
I just tested on a Galaxy S8 and the setting still works as expected. Have you taken a look at the logcat for the device when you reproduce the issue?

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by noway** [comment]
the issue doesn't happen for me anymore on 
    "react-native-onesignal": "^3.3.2",
    "react-native": "^0.60.5",

for ios. not sure about android

**Comment by rgomezp** [comment]
@noway , in either case that's an old version of the package. consider upgrading

**Comment by noway** [comment]
will do

**Comment by nikitawolfik** [comment]
@Nightsd01 why is it bad to init OneSignal sometime later in the app and not immediately?
