### ISSUE TITLE
iOS: listener 'received' is not called when app is killed

### ISSUE THREAD

**Issue by davorbuha** [OneSignal/react-native-onesignal#672]
Hello, this is my first time posting here so I would like to thank you for creating this library.

**Description:**

I have set up everything like in tutorial for react-native and also set up Notification Service Extension in Xcode. But my in-app listener 'received' is not being called when app is killed, it is working when app is in background and foreground but not when it is killed. I tried to debug native code for Notification service extension and uncommented those 2 lines which should modify notification and it worked. Is it possible to get that kind of a event in react-native and run part of a code if App is killed by user

**Environment**

1. What version of the OneSignal React-Native SDK are you using?
 - "react-native": "0.55.3",
 - "react-native-onesignal": "^3.2.8"

2. How did you add the SDK to your project (eg. npm)
     yarn add react-native-onesignal
     react-native link react-native-onesignal
     - manually set up Notification Service Extension

**Steps to Reproduce Issue:**

  1. Install the OneSignal SDK using npm into your project
  2. Link Library with project
  3. Set up Notification Service Extension
  4. Add listener 'received' and kill app
 

**Anything else:**
---

**Comment by Nightsd01** [comment]
@davorbuha Unfortunately if the app is not running in the foreground/background, the react-native context will not be running when the app is received which means the event will not be triggered.

If you want to execute code in the background when notifications are received, you would need to implement it in native code using the Notification Service Extension (in iOS) and the notification service extender (in Android)
