### ISSUE TITLE
Ios Player id issue

### ISSUE THREAD

**Issue by davekedar** [OneSignal/react-native-onesignal#673]
**Description:**
I am trying to get playerid for Onesignal, while doing that it is working strangely. 
`onIds = async (device) => {
  console.log("Device info: ", device.userId);
  let playerid = device.userId;
  AsyncStorage.setItem('playerid', playerid);
  //this.setState({device_id: playerid})
  alert(playerid);
}`

the above code gives me this error, but in alert i am getting the player id. check the picture attached.
![image](https://user-images.githubusercontent.com/11268363/48552752-9a6ded00-e8ff-11e8-9dbc-e50defacaf0b.png)

** Purpose: **
I want to save the playerid in a state or Asyncstorage so that I can send that in Signin api response. but it is not happening. 

**Environment**
` "react-native-onesignal": "^3.2.8",
"react": "16.6.0-alpha.8af6728",
    "react-native": "^0.57.5",`

**Comment by Nightsd01** [comment]
@davekedar I don't believe this is an issue with our SDK as I don't see OneSignal mentioned in that stack trace, and it looks like the event is firing correctly.

**Comment by davekedar** [comment]
@Nightsd01 I understand your comment but it is only when I am enabling one signal, closing this will not be a solution there may be someone else who has faced this and solved it, they can help. 

I just need to know how we can get playerid from ios to store in server that's it. 

Please help
