### ISSUE TITLE
onOpened not fired on production

### ISSUE THREAD

**Issue by udarts** [OneSignal/react-native-onesignal#676]
**Description:**
I noticed that the onOpened is not fired on production. I tried it on debug and it works like a charm.

**Environment**
I use react-native-onesignal: 3.2.8

Installed it via: npm install --save react-native-onesignal

**Steps to Reproduce Issue:**
1. Installing onesignal for react-native (as described above)
2. Setting up the SDK as mentioned in the docs of OneSignal.
3. Sending a push notification.
4. Clicking on the push notification opens up the app and after 100 ms, it opens another screen to show the push notification text.

This works well on debug, but on production, it doesn't open the other screen.

Here is part of the code of what I use:

In the App.js
````
onOpened(openResult) {
        console.log('Message: ', openResult.notification.payload.body);
        console.log('Data: ', openResult.notification.payload.additionalData);
        console.log('isActive: ', openResult.notification.isAppInFocus);
        console.log('openResult: ', openResult);
        if (openResult.notification.payload.body !== '') {
            const pushTitle = openResult.notification.payload.title;
            const pushBody = openResult.notification.payload.body;
            AsyncStorage.multiSet([['pushtitle', pushTitle], ['pushbody', pushBody]]);
        }
    };
````

In my home.component.js
````
AsyncStorage.multiGet(["pushtitle", "pushbody"]).then(responses => {
            responses.map((result, i, response) => {
                if (response[1][1] !== '' && response[1][1] !== null) {
                    setTimeout(() => {
                        navigation.navigate('PushDetails', {
                            title: response[0][1],
                            body: response[1][1]
                        });
                    }, 100)
                }
            })
        })
````

Edit:
Small addition, the app is closed when receiving the push notification.

**Comment by udarts** [comment]
Ok, another update:

I have moved the addEventListener for opened, outside the class

````
OneSignal.addEventListener('opened', (openResult) => {
    if (openResult.notification.payload.body !== '') {
        const pushTitle = openResult.notification.payload.title;
        const pushBody = openResult.notification.payload.body;
        AsyncStorage.multiSet([['pushtitle', pushTitle], ['pushbody', pushBody]]);
    }
});
````

Now the following thing happens:

When I receive a push notification, the app is closed, I click the notification and the app opens, but nothing (apart from the normal app shown) happens. When I close the app and reopen it, suddenly the other screen is shown with the push notification.

So the first time the app opens from the notification, not happens (apart from the normal app shown), but when I reopen the app, the screen is shown with notification text.

Any idea, or is this a bug?

**Comment by Nightsd01** [comment]
@udarts Can you ensure that your code that calls `OneSignal.addEventListener()` is definitely getting called when your app launches?

I've seen some devs add the event listeners in really weird places, such as in the `componentWillUnmount()` function of some component that doesn't even get displayed under most circumstances. Please make sure your code that adds the event listener _does_ get called every time. 

It's also strange that you have an `onOpened` function, but you _also_ are passing the `addEventListener('opened'...` function a callback? This means the callback will get called and not your `onOpened()` function

**Comment by udarts** [comment]
The code is added in the componentWillMount, and the `addEventListener('opened'...` this is the same as the documentation on oneSignal: [https://documentation.onesignal.com/docs/react-native-sdk-setup#section-usage](url)

**Comment by udarts** [comment]
@Nightsd01 In dev mode when I click the notification, it opens the app and goes straight to the specific screen. But not when released (for both iOS and Android).

**Comment by Nightsd01** [comment]
@udarts Test out 3.2.11 and let me know if the issue still occurs for you. Also, try adding the event listener and initializing OneSignal in `componentDidMount`

**Comment by udarts** [comment]
@Nightsd01 will check as soon as I can.

**Comment by Nightsd01** [comment]
Closing due to no update/response, I assume that fixed the issue. If not please reply and I'll be happy to reopen.
