### ISSUE TITLE
[Question] Clear queued notifications created with postNotification

### ISSUE THREAD

**Issue by FabianMeul** [OneSignal/react-native-onesignal#677]
**Description:**
I've figured out how to queue multiple notifications using `OneSignal.postNotifications()`.
I am however not seeing a way to clear one or more of those queued notifications. 
e.g. I queue 5 notifications, each triggering on a different day. 
What do I have to do if I want to cancel the second one?

**Environment**
1. React-Native OneSignal: `3.2.8`
2. Added using `yarn`.

**Comment by Nightsd01** [comment]
@FabianMeul this is not something we allow client devices to do for security reasons, but we do have an API for it. This is definitely something you should only do from a backend server for authenticated clients. 

https://documentation.onesignal.com/reference#create-notification

**Comment by FabianMeul** [comment]
Thx for your response @Nightsd01 .

Our use case is that the clients' device queues up multiple local notifications, based on remote data that is received from the server.

The notifications represent days on which an action needs to be taken.
If for some reason, an action is not required, I'd like to cancel that local queued notification.

While I see that is a security issue for remote notifications, I fail to see how this is relevant for local notifications.
Also; when I queue a local notification, the server won't know anything about it and won't be able to cancel it, correct?

**Comment by FabianMeul** [comment]
To follow up for anyone who might also have this question;

We ended up switching over to `react-native-firebase`, which has a much more extensive API for handling local notifications.
