### ISSUE TITLE
How to remove modal view which appears in the Android app, when app is opened and user is receiving PN in that moment? 

### ISSUE THREAD

**Issue by Luckygirlllll** [OneSignal/react-native-onesignal#679]
**Description:**

How to remove modal view which appear in the Android app, when app is opened and user is receiving PN in that moment? 

(your description here)

**Environment**

 1."react-native-onesignal": "^3.2.7"
2. yarn 

**Steps to Reproduce Issue:**

  1. Install the OneSignal SDK using yarn into your project
  2. Initialize the SDK in react native
  3. Receive push notification when app is opened

**Anything else:**

<img width="321" alt="pn" src="https://user-images.githubusercontent.com/10096433/49521006-20e96f00-f8ad-11e8-9f89-082a07d427fe.png">

**Comment by Nightsd01** [comment]
Please add some more details, I am not sure I understand your issue at all...?

**Comment by Luckygirlllll** [comment]
@Nightsd01 If you don't understand the issue, it doesn't mean that issue is not exist, and it's not a reason to close it.

The problem is that not everyone want to see Push Notification in form of ugly Alert when app is in foreground which is build-in inside oneSignal library. 

Due to the fact that there is no normal documentation for `react-native-onesignal` it was not clear how to get rid of that alert. 

I found out that it's possible to use `OneSignal.inFocusDisplaying(2)  ` in order to remove that Alert.

**Comment by kekkeme** [comment]
Same here iOS 11 device versions. i am using inFocusDisplaying(0) and it works fine. However, if application is closed(even not in background) and user clicks notification and that time if get another notification it shows as alert.

**Comment by vzaffalon** [comment]
Why is this closed, and why is this even a feature?, when you install a library for push notifications why would you want a modal opening in screen showing the content of the push???
