### ISSUE TITLE
Set OneSignal app id programmatically.

### ISSUE THREAD

**Issue by irvadt** [OneSignal/react-native-onesignal#68]
Can I set OneSignal app id programmatically from my JS code? In my case I have to differentiate my app id between staging and production environment, and the environment is set in the JS portion of my app.

**Comment by avishayil** [comment]
Hi,
Unfortunately, you can't do that :\ I'd recommend using two different OneSignal apps - one for staging and one for production. Then, use some build script to differentiate

**Comment by jdestremps** [comment]
The new gradle does not seem to allow programmatic setting of manifestPlaceholders in the build loop, and if you have two dimensions, and need to differentiate between apps and environments, then this is quite a limitation.  Let's say you have two dimensions, app and env, and you have app A and B, and env PreProd and Prod.  Then you have four variants.  We want a separate app ID for each one.  Not possible right now programmatically, and we'll have to change values and build manually.
