### ISSUE TITLE
Add example with extension + cocoapods

### ISSUE THREAD

**Issue by slorber** [OneSignal/react-native-onesignal#685]
Hi,

The example folder with cocoapods does not include the notification extension.

https://github.com/geektimecoil/react-native-onesignal/blob/master/examples/CocoapodsDemo/ios/Podfile

That would be helpful to make an example with both cocoapods and the extension, to ensure this setup works fine and there's a runnable example that we can use as a foundation for our own apps.

Related issues:
- https://github.com/geektimecoil/react-native-onesignal/issues/667
- https://github.com/geektimecoil/react-native-onesignal/issues/569

**Comment by rgomezp** [comment]
Hi @slorber. Thank you for the request. We will consider adding this in the future so that more people can use it as a foundation.
