### ISSUE TITLE
Sending a notification from onesignal dashboard and get blank payload infos

### ISSUE THREAD

**Issue by giacomomasseron** [OneSignal/react-native-onesignal#686]
**Description:**
I send a notification from onesignal dashboard. I receive it but payload infos are blank.

**Environment**
1. Version ^3.2.7
2. Added the package with command `npm install --save react-native-onesignal`

**Steps to Reproduce Issue:**
  1. Install the OneSignal SDK using npm into your project
  2. Initialize the SDK in android
  3. Send notification from onesignal dashboard

This is the code I added in my App file:

    onReceived(notification) {
        console.log("Notification received: ", notification);
    }

    onOpened(openResult) {
        console.log('Message: ', openResult.notification.payload.body);
        console.log('Data: ', openResult.notification.payload.additionalData);
        console.log('isActive: ', openResult.notification.isAppInFocus);
        console.log('openResult: ', openResult);
    }

What I get in the log are only blank values.

**Comment by giacomomasseron** [comment]
Nobody can help me?

**Comment by Nightsd01** [comment]
@GiacomoK when you say you only get blank values, I’m not entirely sure what you mean? Can you post your logs?

**Comment by Nightsd01** [comment]
Closing due to no response.
