### ISSUE TITLE
RNOneSignal.setExternalUserId is not a function

### ISSUE THREAD

**Issue by Sanglepp** [OneSignal/react-native-onesignal#687]
**Description:**

 Tried to implement the new setExternalUserId method to my project, but it seems that the added functionality is lost with the merge of the pull request [#680](https://github.com/geektimecoil/react-native-onesignal/commit/44b665056aa862cbbdb20a5f9e87c59fee3daaba). 

**Environment**
1. What version of the OneSignal React-Native SDK are you using? 

3.2.11

2. How did you add the SDK to your project

yarn add react-native-onesignal
 

**Steps to Reproduce Issue:**

1. Install OneSignal
2. Initialize the SDK with OneSignal.init(ONESIGNAL_APP_ID);
3. Try to set external user id with OneSignal.setExternalUserId(userId);
4. Catch error "RNOneSignal.setExternalUserId is not a function"

**Anything else:**

**Comment by Stefan-vs** [comment]
Was able to reproduce this error on Android, on iOS it works fine

**Comment by dorom** [comment]
https://github.com/geektimecoil/react-native-onesignal/pull/688 - @Nightsd01 maybe could take a look at this?

**Comment by Nightsd01** [comment]
Apologies for the delay in noticing this - thanks for posting this issue. I've created a new release to resolve the problem (3.2.12)

@dorom thanks for creating the PR, I didn't notice it until after I'd merged my own (identical) PR to resolve the problem, sorry about that! But thanks for the help
