### ISSUE TITLE
Badge increment not working with silent notifications (always 1)

### ISSUE THREAD

**Issue by JulienUsson** [OneSignal/react-native-onesignal#694]
**Description:**

Silent Notification with `ios_badgeType = 'Increase'`, `ios_badgeCount = 1` and `content_available = true` always set the badge to 1.
The badges is **increased correctly** when i send a **normal Notification**.
The badges is **set correctly** when i send a silent Notification with **`ios_badgeType = 'SetTo'`**.

**Environment**

```
 React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
      Memory: 40.18 MB / 8.00 GB
      Shell: 5.6.2 - /usr/local/bin/zsh
    Binaries:
      Node: 11.0.0 - ~/.nvm/versions/node/v11.0.0/bin/node
      Yarn: 1.12.1 - ~/.nvm/versions/node/v11.0.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v11.0.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27
        Build Tools: 23.0.1, 24.0.3, 25.0.2, 26.0.1, 26.0.2, 27.0.3
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
      react-native-onesignal: 3.2.12
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Steps to Reproduce Issue:**

Send many silent Notifications with `ios_badgeType = 'Increase'`, `ios_badgeCount = 1` and `content_available = true`

**Comment by jkasten2** [comment]
@JulienUsson Sorry for the delay and thanks for all the details.

iOS only natively supports setting a badge value, it does not have an increase operation built in. OneSignal's badge increase operation on iOS relies on the app's Notification Service Extension which can only fire if there is a visible notification to display. This is a limitation of iOS itself.

If you need to update the badge value silently, without showing a notification, you will need to keep track of the value on your server and always use "SetTo". We will update our documentation to make note of this limitation. Thanks.
