### ISSUE TITLE
Custom notification sound broken on android?

### ISSUE THREAD

**Issue by mik-rom** [OneSignal/react-native-onesignal#699]
**Description:**
I'm having trouble using a custom sound for react-native-onesignal push notifications. I have used the exact same sound file for an old ionic app without problems but I can't get it working in react-native.

https://documentation.onesignal.com/docs/customize-notification-sounds

Paths I've added the file to:

_project/android/app/src/main/res/raw/bells.mp3_
_project/android/res/raw/bells.mp3_
_project/res/raw/bells.mp3_

I have also tried adding a file named _onesignal_default_sound.mp3_ to all the paths above to try to replace the default sound like the docs say but it has no effect.

**Environment**
"react-native-onesignal": "^3.2.11", added by npm install --save react-native-onesignal
"react": "16.6.1",
    "react-native": "0.57.7",

**Steps to Reproduce Issue:**

1. Install react-native-onesignal
2. Add sound file to directories above (whichever one is correct, it's not in the documentation for react-native specifically)
3. Send a notification through onesignal console or p2p notification in app with custom sound (android_sound)

**Anything else:**

```
let otherParams = {
  "android_sound": "bells", // I have tried bells.mp3 also
  "priority": 10,
  ...customOtherParams
}    
OneSignal.postNotification(content, data, playerId, otherParams)
```

**Comment by Nightsd01** [comment]
@rom1k What version of Android are you testing with?

Android Oreo (8.0) introduced Notification Categories / Channels. They must be used if you want to customize priority, sound, LED Color, Badges, Lockscreen visibility or vibration. More details on the requirements, how to setup, and using them below.
https://documentation.onesignal.com/docs/android-notification-categories

**Comment by Nightsd01** [comment]
Closing due to no response

**Comment by nahidmbstu** [comment]
i am having the same issue

**Comment by nahidmbstu** [comment]
@Nightsd01

**Comment by nahidmbstu** [comment]
did you find any solution ? @rom1k

**Comment by jeffreyabarrios** [comment]
Hello! I have the same issue im using React Native. 

I have added the mp3 (and ogg) file to android/app/src/main/res/raw, also tried on /android/app/res/raw, and setting the name on the notification template like "notificationsound" without the extension, also tried setting it from the REST API and still when the notification arrives, tried creating categories / channels, and still it plays the default sound (also led color not working).

Please help.

**Comment by felipebutcher** [comment]
Hey guys. I was having the same problem. Not sure which one solved but I did these two things:
- Open project from android studio, clean, build, run.
- Removed the app and installed again.
It actually worked after I reinstalled the app.

**Comment by anastely** [comment]
Can you share your tried code when setting sounds? @jeffreyabarrios

**Comment by santhoshkumarguna** [comment]
Hi! I have the same issue i am using React Native64.2.

I have added the mp3 file to android/app/res/raw.notification only arriving custom sound not play.i read the full documentation and implemented properly but still its not working.

Please help.
