### ISSUE TITLE
Support to upload/add apn authentication key in the console instead of push certificate

### ISSUE THREAD

**Issue by sunnymopada** [OneSignal/react-native-onesignal#700]
**Description:**

According to apple documentation, They suggests to use APN Auth key instead of push certificates.
https://firebase.google.com/docs/cloud-messaging/ios/certs

**Environment**
React native onesignal- 3.2.12

**Comment by Nightsd01** [comment]
Since this is not related to our actual SDK itself and would not require any updates/changes to our SDK's, I will be closing this issue. But I will be bringing it up with some of our engineers to discuss how easy this would be to do, and we've discussed it before. Thanks for bringing this up!
