### ISSUE TITLE
App rerender after click on push notification

### ISSUE THREAD

**Issue by janaka120** [OneSignal/react-native-onesignal#701]
**Description:**
When I clicked on push notification, my **Android** app is getting render again. I didn't check it on **IOS**.

**Environment**
react-native-onesignal: 3.2.11,
react: 16.6.0-alpha.8af6728,
react-native: 0.57.4,

I used `npm install --save react-native-onesignal` command to install oneSignal.

I configured the oneSignal package according to this documentation. https://documentation.onesignal.com/v5.0/docs/react-native-sdk-setup

**Steps to Reproduce Issue:**

  1. Install the OneSignal SDK using npm into your project
  2. Initialize the SDK in the Android
  3. Send a push notification throught OneSignal webSite(for testing purpose).
  4. App is running in foreground.
  5. Clicked on the push notification received.
  6. App is render again.

I'm using `react-navigation: 2.16`. 
This is my code.

```
componentDidMount() {
        // One signal notification settings
        OneSignal.configure();
        OneSignal.setLogLevel(5, 0); // adb logcat debug (5) logs
        OneSignal.init('xxxxxxxxxxxx');
        OneSignal.inFocusDisplaying(2);
        OneSignal.addEventListener('ids', this.onIds);
        OneSignal.getPermissionSubscriptionState((status) => {
            if(status.userId)
                // update userID using props
	});
    }
```
```
    onIds = (device) => {
        const userId = device.userId;
        if(userId)
           // update userID using props

        OneSignal.removeEventListener('ids', this.onIds);
    }
```

I removed all the event listeners(**received**, **opened**), I used. But when I clicked on the push notification. My Android app rerender.

```
        OneSignal.addEventListener('received', this.onReceived);
        OneSignal.addEventListener('opened', this.onOpened); 
```

I try to find out a solution, But I couldn't. If some has any idea about this Please tell me.

**Comment by janaka120** [comment]
I find out, why app gets rerender. Because when I clicked on notification, app goes to background and then it comes to foreground. 
why does app status change? when I clicked on notification.
How to stop this.

**Comment by martinosmartinos** [comment]
Did you add android:launchMode="singleTop" to your AndroidManifest.xml?

**Comment by janaka120** [comment]
@martinosmartinos yes, I added it.

**Comment by martinosmartinos** [comment]
Try to move your logic into componentWillMount lifecycle instead and see if it helps.

**Comment by janaka120** [comment]
Thanks  for your support @martinosmartinos. But it didn't work.

**Comment by rgomezp** [comment]
Hello @janaka120 
It sounds like you're trying to deep-link into your app. You can find more information on this topic [here](https://documentation.onesignal.com/docs/links). You may also be encountering an issue due to react-navigation.

I'm wondering if the entire app is re-rendering or if you mean that the current screen gets re-rendered (react-lifecycle)?

**Comment by janaka120** [comment]
Hi @rgomezp 

My entire app is rendering when I tap on push-notification.

**Comment by rgomezp** [comment]
@janaka120 I see. Is the metro-bundler rebuilding everything or do you simply get taken back to the splash-screen and/or homepage?

**Comment by janaka120** [comment]
@rgomezp I don't get back to the splash-screen. I get back to the homepage. When I console my main app.js after tap on push notification, it rendered So my app route to home screen.

**Comment by rgomezp** [comment]
@janaka120 ok so just to confirm, the app is not being re-bundled correct?

**Comment by janaka120** [comment]
@rgomezp yes. It's not rebundling.

**Comment by rgomezp** [comment]
This sounds like a deep-linking issue. Please read our documentation on setting deep-links correctly and verify that you did everything correctly. https://documentation.onesignal.com/docs/links

**Comment by janaka120** [comment]
@rgomezp I didn't use any deep-link with push-notification.

**Comment by rgomezp** [comment]
Can you please test on iOS to see if you are getting the same result? I'm not sure why this is happening. React will re-render when state changes

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by karvulf** [comment]
That could solve your problem:
Instead of using  android:launchMode="singleTop"use android:launchMode="singleTask"

**Comment by hotaryuzaki** [comment]
> That could solve your problem:
> Instead of using android:launchMode="singleTop"use android:launchMode="singleTask"

i have same issue.
another problem is when i open deep link from Email, apps open new app task. If i open task manager my apps have multiple tabs running.
And it solved if i change to SINGLETASK.

But my question, is there any problem that i must concern if change to SINGLETASK??

**Comment by lafiosca** [comment]
@rgomezp I believe I'm experiencing the same problem as the original poster on Android. My application is running, and I minimize it. A push notification arrives, and I tap it to open the application. At this point, the entire application reinitializes. It does not behave this way on iOS. I am currently using `singleTop` as recommended by the SDK docs, but I'm curious if another mode might fix this problem.

**Comment by hotaryuzaki** [comment]
Use singleTask instead.
I don't understand why they're not fix this issue, because this is very important

**Comment by lafiosca** [comment]
Thanks @hotaryuzaki, after posting my comment yesterday I tried out `singleTask` which seems to be working so far without any noticeable problems. I am concerned though because the SDK authors have said multiple times that this could cause issues.

**Comment by hotaryuzaki** [comment]
Yes I got confirmed by them about that, but they weren't mentioned the detail which problem they mean.
If it was an issue, I don't know why they're didn't fix that.

**Comment by rgomezp** [comment]
Howdy,
We are planning to fix this in a future release. Thanks for your patience

**Comment by jariwalabhavesh** [comment]
@rgomezp : Can you provide possible issue detail that may occure on changing launchMode from 'singleTop' to 'singleTask'.
So we can understand risk of switching to  'singleTask'
I am also facing an issue with auth0 and onesignal.

Right now I had swithed to 'singleTask'

**Comment by rgomezp** [comment]
Setting it to singleTask may result in multiple copies of your activity being created

@jariwalabhavesh

**Comment by jariwalabhavesh** [comment]
@rgomezp : 
Thanks for the response.
I think as you mention in previous comment that you guys are planning for a fix. Till that we will wait.

**Comment by xeroxoid** [comment]
@rgomezp As per React Native documentation (https://facebook.github.io/react-native/docs/linking) Linking requires  the MainActivity to be `singleTask`. Is there away around this for OneSignal?

**Comment by samitha9125** [comment]
> Howdy,
> We are planning to fix this in a future release. Thanks for your patience

@rgomezp  Thank you for working on this and is this issue fixed yet?

**Comment by rgomezp** [comment]
This feature request has not been implemented yet

**Comment by bernhardt1** [comment]
@rgomezp is there an ETA for when the fix will come through? IMO: This is the biggest problem with onesignal for react native in its current state.

I have also switched to `singleTask`.

I am not seeing multiple copies of the activity being created when using `singleTask`. Plus it is the only way to stop the app from re-launching on notification press. It is also necessary to have deep links work properly...

**Comment by KestasVenslauskas** [comment]
Having same problems with push notifications on android. But I do use deep links.
The problem is that if app is killed and opened from notification it open from loading everything from start. If user pressed Home button and comes back again app always reloads and always re-launches same launchUrl from depp-linking.

**Comment by FayyazAliKhan1** [comment]
@KestasVenslauskas did you managed to solve this cause I also implement the deep link and the same problem is coming to me
