### ISSUE TITLE
After eject Expo project unable to run app

### ISSUE THREAD

**Issue by rb162215** [OneSignal/react-native-onesignal#703]
After ejecting expo project when i run app getting error 

> Failed to resolve: host.exp.exponent:expoview:29.0.0

in my gradle file i am using `implementation('host.exp.exponent:expoview:29.0.0')`

any suggestion is really appreciated.

Thanks in advance

**Comment by Nightsd01** [comment]
@ravi-vinfotech What makes you think this is related to OneSignal? This issues section is for the OneSignal SDK.
