### ISSUE TITLE
Event listeners not triggered when the app is closed

### ISSUE THREAD

**Issue by EgidioCaprino** [OneSignal/react-native-onesignal#704]
Hi all 👋

I'm working on a React Native application and I'm observing this behaviour.

1. The application is closed.
2. I receive a push notification.
3. I open the application from the launcher, not by tapping on the push notification.
4. Neither `received` nor `opened` event listeners are triggered.

Is that correct? I would expect at least `received` event to be triggered.

If that's a correct behaviour, is there any way to retrieve the un-tapped push notifications?

Thank you,

Egidio

**Comment by Nightsd01** [comment]
@EgidioCaprino This is correct behavior unless your app is actually running in the background. If your app is terminated, then the `received` event will not be fired. You would need to implement the Notification Service Extension (iOS) or the Notification Extender Service (Android) but both would need to be done separately in native code.

And if you are opening the app _without_ tapping the notification, then of course the `opened` event will not fire.

**Comment by EgidioCaprino** [comment]
Would [this](https://documentation.onesignal.com/docs/react-native-sdk-setup#section-add-notification-service-extension) solve the problem?
