### ISSUE TITLE
Still Receiving In App Alert after setting OneSignal.inFocusDisplaying(0)

### ISSUE THREAD

**Issue by lightninglu10** [OneSignal/react-native-onesignal#705]
**Description:**

After setting OneSignal.inFocusDisplaying(0);

We still receive in app alerts on iOS

Here is the code for our OneSignal component:

```
componentWillReceiveProps(nextProps, nextState) {
    if (nextProps.auth.isLoggedIn && !this.props.auth.isLoggedIn) {
      OneSignal.init(ONE_SIGNAL_APP_ID);
      OneSignal.inFocusDisplaying(0);
      OneSignal.addEventListener('ids', this.onIds);
      OneSignal.addEventListener('opened', this.onOpened);
    }
  }
```

**Environment**

    "react-native-onesignal": "^3.2.8",
yarn add

**Comment by Nightsd01** [comment]
@lightninglu10 Can you please add some more details....?

Are you talking about when the app is running in the **foreground**? Could you send a screenshot perhaps?

**Comment by lightninglu10** [comment]
Yep, when the app is running in the foreground and open. 

![unadjustednonraw_mini_9](https://user-images.githubusercontent.com/2453737/51055765-befbe380-1595-11e9-85da-f9c695b89728.jpg)

So this is the notification we're sending, and it pops everytime when the app is foregrounded. If it helps we're using detached Expo (ExpoKit). 

Not sure what other detail you guys need, just seems like something with the API isn't working properly.

**Comment by lightninglu10** [comment]
Setting option 2 works though, as we can get both the notification and the alert, but never not the alert.

![unadjustednonraw_mini_17](https://user-images.githubusercontent.com/2453737/51055884-18fca900-1596-11e9-922a-fed6743a5b1e.jpg)

**Comment by lightninglu10** [comment]
Any updates on this @Nightsd01 ? This is a pretty big blocker to using One Signal for notifications.

**Comment by Nightsd01** [comment]
@lightninglu10 `componentWillReceiveProps` has been deprecated. Can you please move all of the SDK related setup code to `componentDidMount` instead? Can you also please try adding the line where you call `inFocusDisplaying(0)` to be above the line where you call `init`?

If none of that works, can you post your full `package.json`?

**Comment by lightninglu10** [comment]
Nope none of that works. Are you guys sure the API is working properly? Is there something I can put in AppDelegate.m to mitigate this issue?

Anyways my package.json is here:

```
{
  "name": "playground-mobile",
  "main": "./app.expo.js",
  "private": true,
  "scripts": {
    "start": "expo start",
    "debug": "REACT_DEBUGGER=\"rndebugger-open --open --expo\" expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "@ptomasroos/react-native-multi-slider": "^1.0.0",
    "@redux-offline/redux-offline": "^2.5.1",
    "create-react-class": "^15.6.3",
    "detect-libc": "^1.0.3",
    "expo": "^31.0.2",
    "expokit": "31.0.1",
    "javascript-time-ago": "^1.0.34",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "object-diff": "0.0.4",
    "prop-types": "^15.6.2",
    "rc": "^1.2.8",
    "react": "16.5.0",
    "react-addons-update": "^15.6.2",
    "react-devtools": "^3.4.2",
    "react-devtools-core": "^3.4.2",
    "react-mixin": "^5.0.0",
    "react-moment": "^0.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
    "react-native-animatable": "^1.3.0",
    "react-native-animated-linear-gradient": "^1.1.2",
    "react-native-applinks": "^0.0.2",
    "react-native-autogrow-textinput": "^5.2.0",
    "react-native-background-geolocation": "^2.14.1",
    "react-native-cached-image": "^1.4.3",
    "react-native-deck-swiper": "^1.5.26",
    "react-native-device-info": "^0.24.3",
    "react-native-dialogs": "^1.0.2",
    "react-native-expanding-circle-transition": "^1.2.3",
    "react-native-expo-image-cache": "^3.2.0",
    "react-native-fast-image": "^5.1.1",
    "react-native-image-picker": "^0.27.1",
    "react-native-image-resizer": "^1.0.0",
    "react-native-img-cache": "^1.5.3",
    "react-native-interactable": "^0.1.10",
    "react-native-keychain": "^3.0.0",
    "react-native-linear-gradient": "^2.4.3",
    "react-native-map-link": "^2.1.3",
    "react-native-material-ripple": "^0.8.0",
    "react-native-onesignal": "^3.2.8",
    "react-native-orientation": "^3.1.3",
    "react-native-photo-upload": "^1.3.0",
    "react-native-rest-client": "^0.1.1",
    "react-native-sideswipe": "^1.4.2",
    "react-native-sortable-grid": "^2.0.0",
    "react-native-splash-screen": "^3.1.1",
    "react-native-super-grid": "^2.4.3",
    "react-native-swipe-cards": "^0.1.1",
    "react-native-swipe-list-view": "^1.3.1",
    "react-native-swiper": "^1.5.14",
    "react-native-vector-icons": "^6.0.2",
    "react-native-wheel": "^1.1.4",
    "react-native-wheel-picker": "^1.2.0",
    "react-navigation": "1.5.11",
    "react-redux": "^5.1.1",
    "realm": "2.17.0",
    "redux": "^4.0.1",
    "redux-offline": "^2.0.0",
    "redux-thunk": "^2.3.0",
    "remote-redux-devtools": "^0.5.13",
    "rgb2hex": "^0.1.9",
    "rn-fetch-blob": "^0.10.13",
    "rn-viewpager": "^1.2.9",
    "rn-viewpager-q5": "^1.3.0",
    "seamless-immutable": "^7.1.4",
    "tcomb-form-native": "^0.6.20"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "react-native-debugger-open": "^0.3.17"
  }
}
```

**Comment by Nightsd01** [comment]
@lightninglu10 It looks like you are probably calling `OneSignal.inFocusDisplaying(1)` somewhere in your app. Could you please run a search of your entire codebase to verify that you are **not** doing this?

If not, can you please download our example/demo project (it's in the examples folder in this repo) and see if you can reproduce the issue with that project? And if you can, please zip it up and send me a link via dropbox or something so I can reproduce it as well.

**Comment by lightninglu10** [comment]
Good shout @Nightsd01. We inherited this codebase and didn't realize the previous maintainers were calling OneSignal in random places. 

Found the culprit and fixed it.
