### ISSUE TITLE
infocusDisplaying(2) not working in iOS

### ISSUE THREAD

**Issue by aleixrodriala** [OneSignal/react-native-onesignal#708]
**Description:**
When you send a notification with this code, it doesn't display any notification in the notification center when it should, as it's working perfectly on Android. This is my code:
```
componentWillMount(){
    OneSignal.init(settings.ONESIGNAL_API_KEY, {kOSSettingsKeyInFocusDisplayOption: 2});
    OneSignal.inFocusDisplaying(2);
  }
```

Notifications work fine when app is not in focus, but when app is in focus no notification gets displayed.

Also, when setting inFocusDisplaying to 0, I receive that notification in the "received" event listener always.

**Environment**
Onesignal 2.9.4 iOS SDK (installed with CocoaPods)
react-native-onesignal 3.2.11 (npm install and react-native link)
    "react": "16.6.3",
    "react-native": "0.57.8",

**Steps to Reproduce Issue:**
  1. Install the OneSignal SDK using npm into your project
  2. react-native link react-native-onesignal && cd ios && pod install
  3. Attempt to receive a push notification with the app open

**Anything else:**
When the app is in focus and a notification is recieved, in the logs appear the following:
```
2019-01-17 22:22:45.740666+0100 tipsecapp[1205:250244] VERBOSE: onesignalUserNotificationCenter:willPresentNotification:withCompletionHandler: Fired!
2019-01-17 22:22:45.740892+0100 tipsecapp[1205:250244] VERBOSE: notificationOpened:isActive called!
```

And when I open the app the following logs appear:
```
2019-01-17 22:23:03.626620+0100 tipsecapp[1205:250244] VERBOSE: oneSignalApplicationDidBecomeActive
2019-01-17 22:23:03.626920+0100 tipsecapp[1205:250244] VERBOSE: getNotificationTypes:mSubscriptionStatus: -1
2019-01-17 22:23:03.629887+0100 tipsecapp[1205:250244] VERBOSE: getNotificationTypes:mSubscriptionStatus: -1
```

This issue is driving me crazy, I've tried everything I could think of and searched a lot but didn't find anything that works for me, and my whole business depends on this, please any help would be really appreciated.

Thanks for your time,
Aleix.

**Comment by Nightsd01** [comment]
@aleixrodri98, I am not entirely sure I understand your issue. Are you saying that _no_ notification gets displayed even though you're calling `OneSignal.inFocusDisplaying(2)`?

In every case I've ever seen, this issue is usually caused when developers are calling `inFocusDisplaying(0)` somewhere else in their codebase and they don't realize it....can you do a full text search of your entire codebase to make sure you aren't doing this?

**Comment by aleixrodriala** [comment]
Hi @Nightsd01, thanks for the fast reply, yes you are right, no notification gets displayed even though I'm calling OneSignal.inFocusDisplaying(2)

Me too, all the issues I saw were the opposite problem that's why I created this one.

Checked a million times, there is no inFocusDisplaying(0) in the code.

**Comment by Nightsd01** [comment]
@aleixrodri98 Please try our sample/demo project `RNOneSignal` in the `/examples` folder of this repository, set it up with your iOS bundle identifier and your onesignal App ID, and let me know if the same issue occurs there. Our example project is already using `inFocusDisplaying(2)` so you won't need to add this.

**Comment by aleixrodriala** [comment]
Trying that will tell you in few mins, forgot to say that I'm not using Expo, maybe that could be some reason or whatever, thanks.

**Comment by aleixrodriala** [comment]
Sorry @Nightsd01, can't seem to be able to figure out how to run the expo app (CocoaPods) example, in a device, so it asks for notifications permissions, because when used with Expo Client does not prompt for notification permissions.

Could you please tell me how to run the expo app in my device? Or what should I do to set up the example repo and run it on a device?

Thanks

**Comment by Nightsd01** [comment]
@aleixrodri98 Please try running the other example, `RNOneSignal`

**Comment by aleixrodriala** [comment]
Finally got it working, and it works just fine in the example.

```
2019-01-18 01:48:21.878966+0100 RNOneSignal[1363:283200] VERBOSE: onesignalUserNotificationCenter:willPresentNotification:withCompletionHandler: Fired!
2019-01-18 01:48:21.879171+0100 RNOneSignal[1363:283200] VERBOSE: notificationOpened:isActive called!
2019-01-18 01:48:21.879870+0100 RNOneSignal[1363:283200] VERBOSE: callLegacyAppDeletegateSelector:withCompletionHandler: Fired!
2019-01-18 01:48:21.880027+0100 RNOneSignal[1363:283200] VERBOSE: oneSignalRemoteSilentNotification:UserInfo:fetchCompletionHandler:
2019-01-18 01:48:21.880167+0100 RNOneSignal[1363:283200] VERBOSE: notificationOpened:isActive called!
```

Removed the cocoapods library in my project, and added only the same library, put the exact same code into my project and again not working.

Don't know what else to do, do you know what I could try?

**Comment by Nightsd01** [comment]
@aleixrodri98 I would make sure that when you ran a full codebase search for any usage of `inFocusDisplaying` that you were definitely searching the _entire_ project and not just one file or directory. That is by FAR the most common cause of this issue.

The fact that it works in the example but not in your project is an even bigger indication that this is what is going on.

If possible, could you zip up and send your project to our support team? You can easily chat with support by going to the dashboard at www.onesignal.com 

If not, it is extremely difficult to debug an issue like this without being able to reproduce it ourselves.

**Comment by aleixrodriala** [comment]
100% sure that inFocusDisplaying is not used elsewhere in the entire project

Will zip up the project and send it to the support team, do you think they will be able to help me with this? Or can I just send a private link to you? 

Thanks

**Comment by aleixrodriala** [comment]
Fixed it, was a conflict with Firebase Messaging library (removing the library fixed it), thanks for all the help, hope it will be useful for someone.

**Comment by Nightsd01** [comment]
@aleixrodri98 Glad to hear you were able to get to the bottom of it! Feel free to ask if you have any other issues and I hope you enjoy using the SDK

**Comment by nttung291** [comment]
I'm facing the same problem in my app. Is there any solution to use both of Firebase Messaging and OneSignal in app focus ? As I guess that using Firebase Messaging to verify phone number it will push a silent message to my app could make this issue.
