### ISSUE TITLE
received fires twice if message is opened (Android)

### ISSUE THREAD

**Issue by phsumi** [OneSignal/react-native-onesignal#709]
**Description:**

Android: Is this intended behavior? My received handler fires twice with the same message (once as a pure notification, once wrapped into another result) if either a popup is tapped or a notification in the notifcation area.

In order to prevent this, I had to add a little hack here:

    //NOTE: this seems to be called before AND after opening a message.
    onReceived(notification) {
        //i get once the notification itself, once i have to unwrap it
        if(notification.notification) {
            notification = notification.notification;
        }

        //if we tap a notification, received fires twice with the
        //same data. Just ignore the duplicate
        var id = notification.payload.notificationID;
        if(id && this.lastNotificationId === id) return;
        this.lastNotificationId = id;

        console.warn("Notification received: ", notification);
    }

**Environment**
3.2.12 through Yarn

**Steps to Reproduce Issue:**
Just followed the tutorial and sent a message.

**Comment by Nightsd01** [comment]
@phsumi I would suspect you are setting your 
`onReceived` function as the event listener for _both_ the `opened` and `received` callbacks. Can you please post the code where you are adding event listeners and initializing the SDK so we can verify that this is not the case?

If not, can you please download this repo and try reproducing this problem in one of our example projects located in the `/examples` directory of this repo?

**Comment by phsumi** [comment]
No, I just copy/pasted the sample code:

    public init() {
        OneSignal.init(Env.oneSignalAppId);

        OneSignal.addEventListener("received", this.onReceived);
        OneSignal.addEventListener("opened", this.onOpened);
        OneSignal.addEventListener("ids", this.onIds);
    }

**Comment by Nightsd01** [comment]
@phsumi are you running our example project with no additional changes?

If not, please check to make sure you are NOT using `OneSignal.addEventListener`, because somehow you are setting your `onReceived` function as an `opened` event listener.

**Comment by phsumi** [comment]
@Nightsd01  Did a clean checkout on another machine and the issue is gone. Dunno whether there was a caching issue with some experimental code, but the problem seems to have been on my side - sorry for wasting your time guys!

**Comment by anniewey** [comment]
@Nightsd01 How to disable `onOpened` being called when tap inAppAlert Ok button?
