### ISSUE TITLE
Compatibility with OneSignal SDK 2.0 (autoregister bug)

### ISSUE THREAD

**Issue by weixiyen** [OneSignal/react-native-onesignal#71]
autoregister is handled differently in SDK 2.0, via a settings dictionary I believe, so the app crashes.

For those having issues, update your podspec to this:
pod 'OneSignal', '1.13.3'

**Comment by ghost** [comment]
Same here. 

Hope for fast fix :)

**Comment by JKalash** [comment]
Working on creating a pull request for the fix. Stay tuned!

**Comment by JKalash** [comment]
@weixiyen @alexanderniebuhr Temporary fix:
Replace **pod 'OneSignal'** with **pod 'OneSignal', '~> 1.13.2'** and run a **pod update**. Should restrict CocoaPods from fetching the latest OneSignal SDK version and rather get the 1.13.3 version which is compatible with the ios react-native wrapper.

**Comment by ghost** [comment]
Yeah. I know, but I think make it works with the newest version of the onesignal SDk is the goal :)

Thanks for your workaround and time

**Comment by JKalash** [comment]
Here's the PR! https://github.com/geektimecoil/react-native-onesignal/pull/73

**Comment by avishayil** [comment]
We're currently testing the new version, which apparently solves this issue.
