### ISSUE TITLE
 Push notification is freezing up the app on iOS (White Screen)

### ISSUE THREAD

**Issue by FrazeColder** [OneSignal/react-native-onesignal#711]
**Description:**
sadly I am facing problem with One Signal and my react native application. I don't know why but somehow my push notifications aren't working anymore.. But only on iOS.. I have had the same problem with Android too but Android is working again. So, that means that the problem cannot really be the react native code cause it is working on Android.

However, when I receive a notification on my iOS device the screen remains white and the application doesn't crash. This is actually not good cause that means I don't get any crash log.. And you cannot debug iOS devices on a MacBook cause Apple has deactivated to receive push notifications on the iPhone emulator..

So, I don't really know what to do.. All I did was replacing the icons and the splash screen. On both, Android and iOS. Also confusing is, the application gets compiled and build without any problems on XCode..

I have read some issues on GitHub already but none of them are working.. What I am really wondering about is, why it is working on my Android device but not on my iOS device.. 

I already tried to solve the problem by deleting the `node_modules` folder and create it again by `npm install`. However, this didn't fix the problem. I also runned `pod install` again and checked the OneSignal documentation to double check if everything is correctly installed.. And yes, everything is correctly installed.. 

You guys have any idea on what to do and how to solve the problem?
After I tap on the notification the app launches and then remains on a white screen.. 

If the app is running in background and I tap on the push notification everything works fine!

But when I am inside the app and I receive a push notification, the app "crashes" and keeps remaining on the white screen. As well when the app is completely closed and I tap on the push notification.. The app "crashes" and keeps remaining on the white screen also...

Here is my Code:
import OneSignal from "react-native-onesignal";

constructor(props) {
    super(props);
    this.state = {
      pushNotification: null,
      visible: false
    };

    OneSignal.init("00000000000000000000", {
      kOSSettingsKeyAutoPrompt: true
    });

    OneSignal.inFocusDisplaying(0);
    OneSignal.enableVibrate(true);
    OneSignal.enableSound(true);

    OneSignal.addEventListener("received", this.onReceived);
    OneSignal.addEventListener("opened", this.onOpened);
    OneSignal.addEventListener("ids", this.onIds);
  }

componentWillUnmount() {
    OneSignal.removeEventListener("received", this.onReceived);
    OneSignal.removeEventListener("opened", this.onOpened);
    OneSignal.removeEventListener("ids", this.onIds);
  }

  onReceived = notification => {
    console.log("Notification received: ", notification);

    this.setState({
      pushNotification: notification,
      visible: true
    });
  };

  onOpened = openResult => {
    console.log("Message: ", openResult.notification.payload.body);
    console.log("Data: ", openResult.notification.payload.additionalData);
    console.log("isActive: ", openResult.notification.isAppInFocus);
    console.log("openResult: ", openResult);

    this.setState({
      pushNotification: openResult.notification,
      visible: true
    });
  };

  onIds = device => {
    console.log("Device info: ", device);
  };

You guys can help me?
Kind regards and Thank You!

**Environment**
```
React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 121.66 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 27
        Build Tools: 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.5 => 0.57.5
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-rename: 2.4.0

```

**Steps to Reproduce Issue:**
Would answer that question if I would know how to reproduce this issue...

**Anything else:**

Cannot provide any crash stack cause I cannot debug my iOS app on an emulator... Apple doesn't allow push notifications on iOS emulators...

**Comment by Nightsd01** [comment]
@FrazeColder you can debug your app without Xcode. I would recommend calling `OneSignal.setLogLevel(6, 0)` BEFORE the line where you initialize the SDK. Then please open the iOS project in Xcode and run it from there. This way you should be able to see the logs. 

Also, I am not sure what “the white screen” means. That is not a crash.

**Comment by Nightsd01** [comment]
@FrazeColder you can debug your app on a real iOS device using Xcode. I would recommend calling `OneSignal.setLogLevel(6, 0)` BEFORE the line where you initialize the SDK. Then please open the iOS project in Xcode and run it from there. This way you should be able to see the logs. 

Also, I am not sure what “the white screen” means. That is not a crash.

**Comment by FrazeColder** [comment]
Where is the log going to be saved? And really? I can do this? I have to look this up!

Give me a few minutes and I will paste the log here!

**Comment by Nightsd01** [comment]
@FrazeColder I edited my comment because originally the first sentence had a typo. 

If you run your app in a real iOS device from Xcode, the log will be displayed in the Xcode console. 

This will be a relatively important thing to know for any iOS dev so I would recommend becoming somewhat familiar with Xcode

**Comment by FrazeColder** [comment]
Alright mate. First of all thank you for helping me. Through the debugging via XCode I already could fix the problem with the method `onReceived(...)`. I was trying to get a attribute of a state variable which was null. However, this wasn't a problem on Android.. very strange.

However, I am still facing one problem. When I close the app manuell (swiping it off the screen) and then receive a push notification I get this error:

![img_3f90b15df75e-1](https://user-images.githubusercontent.com/18104426/51490307-31956c00-1dab-11e9-849d-41de6755f3ce.jpeg)

Another problem is also cause I have closed the app completely, XCode has stopped logging the app.. So I don't really know whats going on behind..  However, here again: There is no problem at all opening the app on Android when receiving a push notification and the app is completely closed and killed!

This is the log I get with the filter set to `one` and as mentioned already.. this log is only till I closed the app...

```
2019-01-21 18:29:34.156 [warn][tid:com.facebook.react.JavaScript] Require cycle: node_modules/react-native-popup-dialog/dist/type.js -> node_modules/react-native-popup-dialog/dist/components/DialogButton.js -> node_modules/react-native-popup-dialog/dist/tynode_modules/react-native-popup-dialog/dist/components/DialogButton.js -> node_modules/react-native-popup-dialog/dist/type.js
2019-01-21 18:29:34.453437+0100 DealBee[20334:6582269] VERBOSE: oneSignalDidRegisterForRemoteNotifications:deviceToken:
2019-01-21 18:29:34.478660+0100 DealBee[20334:6582269] VERBOSE: oneSignalApplicationWillResignActive
2019-01-21 18:29:37.867376+0100 DealBee[20334:6582269] VERBOSE: oneSignalDidRegisterForRemoteNotifications:deviceToken:
    ProvisionedDevices =     (
2019-01-21 18:29:37.883466+0100 DealBee[20334:6582486] VERBOSE: Calling OneSignal create/on_session
ealBee[20334:6582489] VERBOSE: HTTP Request (OSRequestRegisterUser) with URL: https://onesignal.com/api/v1/players, with parameters: {
  "timezone" : 3600,
  "device_model" : "iPhone10,4",
  "carrier" : "Vodafone.de"
2019-01-21 18:29:38.140082+0100 DealBee[20334:6582269] INFO: Device Registered with OneSignal: b1437353-c335-498b-b021-02835f52aa8c
2019-01-21 18:29:38.251662+0100 DealBee[20334:6582269] VERBOSE: oneSignalApplicationDidBecomeActive
2019-01-21 18:30:06.061637+0100 DealBee[20334:6582269] VERBOSE: oneSignalApplicationWillResignActive
2019-01-21 18:30:06.663758+0100 DealBee[20334:6582269] VERBOSE: oneSignalApplicationDidEnterBackground
```

**Comment by Nightsd01** [comment]
@FrazeColder you can also view iOS logs in the macOS “Console” app. But in this case the problem seems fairly obvious. Somewhere in your code - probably in your `opened` event handler or in your render function, you are attempting to access a property that does not exist (`this.state.pushNotification.payload`). 

I would carefully look at the red stacktrace screenshot you sent because it’s telling you exactly what is wrong.
