### ISSUE TITLE
Installing OneSignal on React Native - linker command failed with exit code 1

### ISSUE THREAD

**Issue by FrazeColder** [OneSignal/react-native-onesignal#714]
Hey Guys,
I am about to install OneSignal to my React Native application. I have installed OneSignal successfully with [the documentation](https://documentation.onesignal.com/docs/react-native-sdk-setup#section-ios-installation) (at list without "Notification Service Extension").

Then I started to follow the documentation to install the "Notification Service Extension" as well. However, after I installed the "Notification Service Extension" correctly (followed the OneSignal documentation instructions) including the Bridging Header I get an error.

My error is located in the target of `OneSignalNotificationServiceExtension`. This is my error:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RCTSRWebSocket", referenced from:
      objc-class-ref in libReact.a(RCTInspectorPackagerConnection.o)
  "_OBJC_CLASS_$_RCTReconnectingWebSocket", referenced from:
      objc-class-ref in libReact.a(RCTPackagerConnection.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Clearly caused by the `OneSignalNotificationServiceExtension`:
<img width="377" alt="bildschirmfoto 2019-01-22 um 18 37 46" src="https://user-images.githubusercontent.com/18104426/51554217-037c5e80-1e75-11e9-991f-625bfd29b8fa.png">

But I don't know why and how to solve this problem.. Google isn't really helping me.. 
My `Header Search Paths` are set correctly like in the documentation:
<img width="753" alt="bildschirmfoto 2019-01-22 um 18 40 28" src="https://user-images.githubusercontent.com/18104426/51554320-4d654480-1e75-11e9-8acb-e067734e54a3.png">

The `Link Binary with Libraries` part is also done correct!
![image](https://user-images.githubusercontent.com/18104426/51554383-74bc1180-1e75-11e9-92f7-d94ab2cd9006.png)

As well the part with `Cocoapods` but I do think my problem has something to do with the `Link Binary with Libraries` part... However, I don't know how to solve this problem..

Would appreciate any kind of help!

**Comment by Nightsd01** [comment]
Hi, first, the Swift Bridging Header is only necessary if you want to use Swift. For you, I would recommend using Objective-C instead. 

Second, you should not be linking your Extension Service target to ‘libRCTOneSignal.a‘ since Cocoapods will already be doing this for you. If you added the extension service to your Podfile and ran a ‘pod install‘, cocoapods will handle it for you. All you need to do then is replace ‘NotificationService.m‘ with the file shown on the documentation and you should be set.

**Comment by FrazeColder** [comment]
So I don't even have to Link the Binaries with the Libraries? - Well.. this is how I read it in the OneSignal documentation.. Its quite unstructured cause there are some sections which are using Cocoapods and some without.. Would be better to have one section on how to install this with Cocoapods and one on how to install it without.. 

Could you tell me which one a relevant for me to install it with Cocoapods?

**Comment by Nightsd01** [comment]
@FrazeColder we could perhaps simplify the docs a bit, but at the end of the day, react native is inherently complicated and you’ll learn a lot of this stuff as you go along. 

My previous comment pretty much laid out everything you should know, if you have any specific questions feel free to ask!
