### ISSUE TITLE
Some devices mysteriously don't get their tags set

### ISSUE THREAD

**Issue by scottmas** [OneSignal/react-native-onesignal#716]
**Description:**
On some devices some of the times (notice all the caveats?), `sendTags` does not appear to work or something. I'm not sure what's happening really, since it happens so intermittently and I've never been able to reproduce it in a development environment. I know for a fact that the notification with the appropriate tag is getting sent out via the API, and most of the devices receive the notification. But there's just one or two devices running the exact same code that appear to be cursed and never receive the notification. 

**Environment**
I've only seen this occur on ios devices, specifically two iphone SE's . On one of the SE's, it began working again randomly, but the other one is still not registering. I'm not sure if it's only happened on ios devices because it's an ios specific issue or because I just haven't tested on enough devices. 

**Steps to Reproduce Issue:**
No reliable way to reproduce it :(

**Comment by Nightsd01** [comment]
@scottmas do you have these devices in your possession? Please do send the logs if you can. 

There are thousands of reasons a device might not receive a given notification, so without more information it’s really hard to say. 

Are you sure the devices are registered with OneSignal and they tapped “Allow” push permission?

**Comment by scottmas** [comment]
Welp, it turns out my wife had turned _off_ notifications on her device for the app. Which explains it... Thanks for the quick reply and sorry for the false alarm.
