### ISSUE TITLE
Expokit 32 - pendingNotification experienceId is null. 

### ISSUE THREAD

**Issue by owenhope** [OneSignal/react-native-onesignal#717]
Hi,

I know this is not an issue with react-native-onesignal but I was wondering if you could offer some advice.

When opening push notifications on iOS, Expo (detached) throws an error on 

`- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler
{
  EXPendingNotification *pendingNotification = [[EXPendingNotification alloc] initWithNotificationResponse:response identifiersManager:self];
  if (![[EXKernel sharedInstance] sendNotification:pendingNotification] && [EXEnvironment sharedEnvironment].isDetached) {
    _pendingNotifications[pendingNotification.experienceId] = pendingNotification;
  }
  completionHandler();
}`

The issue is 

`_pendingNotifications[pendingNotification.experienceId] = pendingNotification;`

pendingNotification.experienceId is null.

I have tried to pass in the data in the push notification as 

`curl --include \
     --request POST \
     --header "Content-Type: application/json; charset=utf-8" \
     --header "Authorization: Basic REST_ID" \
     --data-binary "{\"app_id\": \"APP_ID\",
\"contents\": {\"en\": \"There are 10 games today\"},
\"headings\": {\"en\": \"Matchups are ready\"},
\"data\": {\"experienceId\": \"@login/expo-slug\"},
\"included_segments\": [\"Subscribed Users\"]}" \
     https://onesignal.com/api/v1/notifications`

Any idea how I can pass this data to fix this issue?

**Comment by rgomezp** [comment]
Hello,
Are you running this in a simulator or a real device?

**Comment by Nightsd01** [comment]
@owenhope expo push notifications and OneSignal notifications are different things and have different structures. This is more of an issue with Expo being incompatible with non-Expo push notifications.
