### ISSUE TITLE
How to use OneSignal.setSubscription(true); ?

### ISSUE THREAD

**Issue by HoYeongSong** [OneSignal/react-native-onesignal#718]
Hello. I want to make react-native switch for OneSignal.setSubscription(true) to  OneSignal.setSubscription(false). 

But I'm not good at javascript and react-native. So can u help me, please?

I'm so sorry. I'm not good at English. Thank you for read.

**Comment by rgomezp** [comment]
Simply call the function as you have it. Just make sure you have already initialized OneSignal. More info [here](https://github.com/geektimecoil/react-native-onesignal/issues/717)
