### ISSUE TITLE
status.subscriptionEnabled in android is string

### ISSUE THREAD

**Issue by manoelneto** [OneSignal/react-native-onesignal#720]
**Description:**

Why when I call `OneSignal.getPermissionSubscriptionState` do I got a status object with `subscriptionEnabled` key as string in android, but as boolean in IOS?

**Environment**

1. What version of the OneSignal React-Native SDK are you using? 3.2.12
2. How did you add the SDK to your project? yarn add

Like this comment here https://github.com/geektimecoil/react-native-onesignal/issues/634#issuecomment-423062635

**Comment by Nightsd01** [comment]
@manoelneto great point! This has been fixed in #725, thanks for pointing this out. It will be included in our next release.
