### ISSUE TITLE
Weird Setup Fix for "Crash on start" (Android)

### ISSUE THREAD

**Issue by faizsameerahmed96** [OneSignal/react-native-onesignal#721]
I was trying to setup onesignal sdk with my application currently using both react-native-google-signin and react-native-maps. 

Initially I setup the Signing and Maps components without a hassle and everything worked fine. When I tried to setup onesignal however I was getting a gradle build error. After excluding packages from Signin and Maps the build proceeded but whenever my app started it automatically crashed. To find out the reason for this I opened up Android Studio and started going through the logs. I found that the crash was due to some missing classes. After googling what happened and lots of trial and error I added 
`implementation 'com.google.firebase:firebase-messaging:17.3.4'` to my gradle file and everything now works perfectly. 

Is there something I missed in the documentation?

**Comment by rgomezp** [comment]
Did you follow the Android SDK Setup guide? https://documentation.onesignal.com/docs/android-sdk-setup ? You shouldn't need to add that line

**Comment by Nightsd01** [comment]
Closing due to no response - if you are still having this issue please reply and we'll be happy to reopen and help investigate
