### ISSUE TITLE
Can't run app because errors from onesignal

### ISSUE THREAD

**Issue by matan335** [OneSignal/react-native-onesignal#722]
My app worked fine yesterday but all of a sudden today android wont run without me doing anything

the error :
<img width="989" alt="2019-02-03 -15 30 06" src="https://user-images.githubusercontent.com/40234607/52177401-f6dafd00-27c8-11e9-95d6-a275f96d5550.png">

what should I do about it?

**Comment by Nightsd01** [comment]
@matan335 Have you tried updating your project's `compileSdkVersion`...?
