### ISSUE TITLE
Expokit, onesignal, error when running react-native run-android

### ISSUE THREAD

**Issue by foxdreamstudio** [OneSignal/react-native-onesignal#723]
hi @ALL, i need your help. i have create apps using expokit, and i have add library onesignal. the problem is when im execute react-native run-android, theres error like this
![screen shot 2019-02-08 at 5 54 47 pm](https://user-images.githubusercontent.com/37882679/52474928-75baa600-2bcc-11e9-8499-1a7b9e14970f.png)
i have been looking the solution in internet but there's no any solution can solve it.
please anyone help me. thanks.

this the gradle file
[Android_build.gradle.txt](https://github.com/geektimecoil/react-native-onesignal/files/2844817/Android_build.gradle.txt)
[App_build.gradle.txt](https://github.com/geektimecoil/react-native-onesignal/files/2844818/App_build.gradle.txt)

**Comment by Nightsd01** [comment]
@foxdreamstudio Please try adding our OneSignal Gradle Plugin to the *very top* of your `app/build.gradle` and try re-running your project:

```groovy
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.0, 0.99.99]'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
```

Also, can you try cloning our example project from our `/examples/RNOneSignal` folder and see if that works for you?

**Comment by rgomezp** [comment]
Closing due to no response
