### ISSUE TITLE
setSubscription throws getNotificationTypes:mSubscriptionStatus: -15 error

### ISSUE THREAD

**Issue by Werbelow** [OneSignal/react-native-onesignal#727]
**Description:**
Our app has settings to toggle notifications, (not related to the OS settings). I would like to use the setSubscription() method when they toggle on or off, but it keeps throwing the error: "getNotificationTypes:mSubscriptionStatus: -15" and resets my app to the router screen. 

It does indeed update the subscription status, however, it does so while throwing that error. 

The notifications work so far, just hitting this bug on this one function. 

**Environment**
iOS, iPhone XS
OneSignal version: ^3.2.12
I installed it using the instructions, including the cocoa pods method.

**Steps to Reproduce Issue:**
just using this method:
OneSignal.setSubscription(this.state.overallNotifications);

**Anything else:**
shows this in the console, or in the alert if I turned that on in the debugging: 
getNotificationTypes:mSubscriptionStatus: -15

**Comment by Nightsd01** [comment]
@Werbelow this would be an issue with whatever @types provider you are using. Please post your `package.json`. It looks like whoever is providing your types for our SDK hasnt updated to include those new functions.

**Comment by Nightsd01** [comment]
Closing since this is not an issue with our SDK. But I would be happy to chat with the types provider

**Comment by Werbelow** [comment]
thanks @Nightsd01 

As far as I know I am not using any typing. 

But here is my package.json 

```{
  "name": "",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "build-android": "cd android && ./gradlew assembleRelease",
    "bundle": "react-native run-ios --configuration Release",
    "reset-cache": "watchman watch-del-all && npm start -- --reset-cache"
  },
  "dependencies": {
    "@feathersjs/authentication-client": "^1.0.6",
    "@feathersjs/feathers": "^3.2.3",
    "@feathersjs/rest-client": "^1.4.5",
    "axios": "^0.18.0",
    "core-js": "^2.5.7",
    "crypto-js": "^3.1.9-1",
    "date-fns": "^1.29.0",
    "instabug-reactnative": "^8.0.20",
    "lodash": "^4.17.11",
    "prop-types": "^15.6.2",
    "react": "16.5.0",
    "react-native": "0.57.2",
    "react-native-action-button": "^2.8.5",
    "react-native-autogrow-textinput": "^5.2.0",
    "react-native-check-box": "^2.1.6",
    "react-native-ci-tools": "^1.1.0",
    "react-native-dropdownalert": "^3.9.1",
    "react-native-fast-image": "^5.1.1",
    "react-native-firebase": "^5.2.0",
    "react-native-image-picker": "^0.27.1",
    "react-native-image-view": "^2.0.12",
    "react-native-modal": "^7.0.0",
    "react-native-onesignal": "^3.2.12",
    "react-native-picker-select": "^5.1.0",
    "react-native-router-flux": "^4.0.5",
    "react-native-vector-icons": "^6.0.1",
    "react-native-video": "^4.3.1",
    "react-redux": "^5.0.7",
    "react-timeago": "^4.1.9",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.5",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "eslint": "^5.13.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-node": "^8.0.1",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-standard": "^4.0.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.0",
    "react-test-renderer": "16.5.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
