### ISSUE TITLE
application closing after receiving notification

### ISSUE THREAD

**Issue by joaodematejr** [OneSignal/react-native-onesignal#728]
R: application closing after receiving notification , 
notifications are sent directly from the site

  classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.0, 0.99.99]'

R: installation using npm

   "react": "16.8.2",
   "react-native": "0.58.5",
  "react-native-onesignal": "^3.2.12",

demonstration
https://ibb.co/r29d4ZH

**/**/code

export default class HelloWorldApp extends Component {

    constructor(props) {
        super(props);
        OneSignal.setLogLevel(6, 0);
        OneSignal.init("key");
        OneSignal.inFocusDisplaying(1);
        OneSignal.enableVibrate(true);
        OneSignal.enableSound(true);
        OneSignal.addEventListener('received', this.onReceived);
        OneSignal.addEventListener('opened', this.onOpened);
        OneSignal.addEventListener('ids', this.onIds);
        OneSignal.configure();
    }

    componentWillUnmount() {
        OneSignal.removeEventListener('received', this.onReceived);
        OneSignal.removeEventListener('opened', this.onOpened);
        OneSignal.removeEventListener('ids', this.onIds);
    }

    onReceived = notification => {
        console.log("Notification received: ", notification);

    };

**Comment by rgomezp** [comment]
Please follow our issue template guide when submitting issues. Also, please include the full code. It looks like you only included some of the callbacks

**Comment by joaodematejr** [comment]
import React, { Component } from 'react';
import { Text, View } from 'react-native';
import OneSignal from 'react-native-onesignal';

export default class HelloWorldApp extends Component {


    constructor(props) {
        super(props);
        OneSignal.setLogLevel(6, 0);
        OneSignal.init("key");
        OneSignal.inFocusDisplaying(1);
        OneSignal.enableVibrate(true);
        OneSignal.enableSound(true);
        OneSignal.addEventListener('received', this.onReceived);
        OneSignal.addEventListener('opened', this.onOpened);
        OneSignal.addEventListener('ids', this.onIds);
        OneSignal.configure();
    }

    componentWillUnmount() {
        OneSignal.removeEventListener('received', this.onReceived);
        OneSignal.removeEventListener('opened', this.onOpened);
        OneSignal.removeEventListener('ids', this.onIds);
    }

    onReceived = notification => {
        console.log("Notification received: ", notification);

    };

    onOpened(openResult) {
        console.log('Message: ', openResult.notification.payload.body);
        console.log('Data: ', openResult.notification.payload.additionalData);
        console.log('isActive: ', openResult.notification.isAppInFocus);
        console.log('openResult: ', openResult);
    }

    onIds(device) {
        console.log('Device info: ', device);
    }

    render() {
        return (
            <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
                <Text>Hello world!</Text>
            </View>
        );
    }
}

**Comment by joaodematejr** [comment]
Is it usual to close application after receiving a notification?

**Comment by Nightsd01** [comment]
@joaodematejr it sounds like it’s crashing, not just closing. Can you please run `adb logcat` and post the stacktrace for the crash you’re getting?

**Comment by joaodematejr** [comment]
BUILD SUCCESSFUL in 9s
134 actionable tasks: 1 executed, 133 up-to-date
MacBook-Pro-de-Joao:android joao$ adb logcat *:S ReactNative:V ReactNativeJS:V
--------- beginning of system
--------- beginning of crash
--------- beginning of main
02-21 18:49:06.336 30248 30248 D ReactNative: ReactInstanceManager.onReloadWithJSDebugger()
02-21 18:49:06.347 30248 30248 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
02-21 18:49:06.347 30248 30248 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
02-21 18:49:06.348 30248 30248 D ReactNative: ReactInstanceManager.tearDownReactContext()
02-21 18:49:06.357 30248 30248 D ReactNative: CatalystInstanceImpl.destroy() start
02-21 18:49:06.367 30248 30272 D ReactNative: CatalystInstanceImpl.destroy() end
02-21 18:49:06.395 30248 30378 D ReactNative: ReactInstanceManager.createReactContext()
02-21 18:49:06.539 30248 30378 D ReactNative: Initializing React Xplat Bridge.
02-21 18:49:06.540 30248 30378 D ReactNative: Initializing React Xplat Bridge before initializeBridge
02-21 18:49:06.541 30248 30378 D ReactNative: Initializing React Xplat Bridge after initializeBridge
02-21 18:49:06.541 30248 30378 D ReactNative: CatalystInstanceImpl.runJSBundle()
02-21 18:49:06.550 30248 30383 D ReactNative: ReactInstanceManager.setupReactContext()
02-21 18:49:06.550 30248 30383 D ReactNative: CatalystInstanceImpl.initialize()
02-21 18:49:06.552 30248 30383 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
02-21 19:02:31.888 31078 31078 D ReactNative: ReactInstanceManager.detachViewFromInstance()
02-21 19:06:39.791 31927 31927 D ReactNative: ReactInstanceManager.ctor()
02-21 19:06:39.917 31927 31927 D ReactNative: ReactInstanceManager.createReactContextInBackground()
02-21 19:06:39.917 31927 31927 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
02-21 19:06:40.231 31927 31927 D ReactNative: ReactInstanceManager.onReloadWithJSDebugger()
02-21 19:06:40.237 31927 31927 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
02-21 19:06:40.238 31927 31927 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
02-21 19:06:40.564 31927 31986 D ReactNative: ReactInstanceManager.createReactContext()
02-21 19:06:41.085 31927 31986 D ReactNative: Initializing React Xplat Bridge.
02-21 19:06:41.095 31927 31986 D ReactNative: Initializing React Xplat Bridge before initializeBridge
02-21 19:06:41.099 31927 31986 D ReactNative: Initializing React Xplat Bridge after initializeBridge
02-21 19:06:41.100 31927 31986 D ReactNative: CatalystInstanceImpl.runJSBundle()
02-21 19:06:41.108 31927 31993 D ReactNative: ReactInstanceManager.setupReactContext()
02-21 19:06:41.109 31927 31993 D ReactNative: CatalystInstanceImpl.initialize()
02-21 19:06:41.123 31927 31993 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
02-21 19:07:00.779 32117 32117 D ReactNative: ReactInstanceManager.ctor()
02-21 19:07:00.835 32117 32117 D ReactNative: ReactInstanceManager.createReactContextInBackground()
02-21 19:07:00.835 32117 32117 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
02-21 19:07:02.124 32117 32117 D ReactNative: ReactInstanceManager.onReloadWithJSDebugger()
02-21 19:07:02.129 32117 32117 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
02-21 19:07:02.130 32117 32117 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
02-21 19:07:02.386 32117 32153 D ReactNative: ReactInstanceManager.createReactContext()
02-21 19:07:02.959 32117 32153 D ReactNative: Initializing React Xplat Bridge.
02-21 19:07:02.967 32117 32153 D ReactNative: Initializing React Xplat Bridge before initializeBridge
02-21 19:07:02.975 32117 32153 D ReactNative: Initializing React Xplat Bridge after initializeBridge
02-21 19:07:02.976 32117 32153 D ReactNative: CatalystInstanceImpl.runJSBundle()
02-21 19:07:02.977 32117 32161 D ReactNative: ReactInstanceManager.setupReactContext()
02-21 19:07:02.978 32117 32161 D ReactNative: CatalystInstanceImpl.initialize()
02-21 19:07:02.986 32117 32161 D ReactNative: ReactInstanceManager.attachRootViewToInstance()

**Comment by joaodematejr** [comment]
I do not know if you need to set anything in OneSignal.setLogLevel (6, 0); to display, I have never used this command in the event of any further information, just let me know.

**Comment by rgomezp** [comment]
I am not seeing anything regarding OneSignal in the log you posted. setLogLevel is a function we provide to facilitate debugging. You can learn more about it [here](https://documentation.onesignal.com/docs/react-native-sdk#section-debugging).

**Comment by Nightsd01** [comment]
@jjoaodematejr this would mean your app is crashing. I would recommend checking logs so that you can get a stacktrace to see what is causing the crash. 

You can use `adb logcat` to get runtime logs from your app. Please post the actual stacktrace of the crash, otherwise it’s not really possible for us to help you in a meaningful way.

**Comment by Nightsd01** [comment]
Closing due to no response.
