### ISSUE TITLE
Crash on iOS after receiving push notification

### ISSUE THREAD

**Issue by humqn** [OneSignal/react-native-onesignal#729]
**Description:**
After clicking on notification on ios the app crash.

**Environment**
    ios 11.4.1
- "expo": "^32.0.0",
-  "expokit": "^32.0.7",
-  "react": "16.5.0",
-  "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
-   "react-native-onesignal": "^3.2.12",
-    react-native-cli: 2.0.1
-    react-native: 0.57.1

**Steps to Reproduce Issue:**

1. Start a fresh RN project : expo init testOneSignal (choose JS project, and tabs)
2. install OneSignal via npm : npm i --save react-native-onesignal
3. expo eject (choose ExpoKit )
4. react-native link
5. Install pods : cd ios && pod install
6. Open Xcode Project : Configure signature & add capabilities push notifications and background modes (tick remote notifications)
7. react-native run-ios (to build pods)
8. In Xcode Project : Build and run on a device, open the app, put the app in background mode (close it)
9. Add in screens/HomeScreen.js OneSignal methods (init, and EventListeners).
10. Fire a notification and click on it. The app crash :(

**More info :**
crash traces on main.m : 
[RNGestureHandlerManager.m:135] [GESTURE HANDLER] Initialize gesture handler for root view <RCTRootContentView: 0x119f3d080; reactTag: 1; frame = (0 0; 768 1024); gestureRecognizers = <NSArray: 0x1c4445100>; layer = <CALayer: 0x1c4239500>>
libc++abi.dylib: terminating with uncaught exception of type NSException

Thanks for your help.

**Comment by Nightsd01** [comment]
@humqn this would definitely be an issue with the code in your `onOpened` handler, since our SDK isn’t touching any react views when a notification is received. Can you please post your callback code? I’d also suggest commenting it out to verify.

**Comment by humqn** [comment]
```
import React from 'react';
import {
  Image,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { WebBrowser } from 'expo';

import { MonoText } from '../components/StyledText';
import OneSignal from 'react-native-onesignal';

export default class HomeScreen extends React.Component {
  static navigationOptions = {
    header: null,
  };

  constructor(properties) {
    super(properties);
    OneSignal.init("KEY");

    OneSignal.addEventListener('received', this.onReceived);
    OneSignal.addEventListener('opened', this.onOpened);
    OneSignal.addEventListener('ids', this.onIds);
  }

  componentWillUnmount() {
    OneSignal.removeEventListener('received', this.onReceived);
    OneSignal.removeEventListener('opened', this.onOpened);
    OneSignal.removeEventListener('ids', this.onIds);
  }

  onReceived(notification) {
    console.log("Notification received: ", notification);
  }

  onOpened(openResult) {
    console.log('Message: ', openResult.notification.payload.body);
    console.log('Data: ', openResult.notification.payload.additionalData);
    console.log('isActive: ', openResult.notification.isAppInFocus);
    console.log('openResult: ', openResult);
  }

  onIds(device) {
    console.log('Device info: ', device);
  }

  render() { ...
```

**Comment by humqn** [comment]
I commented out all listeners and the app is still crashing when users click on notification.

**Comment by Nightsd01** [comment]
@humqn please share the full stacktrace

**Comment by humqn** [comment]
it seems to be linked to an expokit issue : https://github.com/expo/expo/pull/3431

**Comment by Nightsd01** [comment]
@humqn yeah unfortunately there’s not much we can do about this. Please feel free to respond with the full stack trace if you’d like us to investigate further but I’d agree it’s an issue with Expokit.
