### ISSUE TITLE
missing information about extra data in documentation?

### ISSUE THREAD

**Issue by isaaclem** [OneSignal/react-native-onesignal#731]
As stated in this documentation: [https://documentation.onesignal.com/v5.0/docs/react-native-sdk-setup](url)

```js
onReceived(notification) {
  console.log("Notification received: ", notification);
}
```

But I've always getting undefined, which later found out that extra data is actually on second parameters instead

```js
onReceived(notification, data) {
  console.log("Extra Data: ", data.payload );
}
```

**Comment by rgomezp** [comment]
Hello, I am actually not sure why you are getting data this way. You should be receiving your notification object as so:
```
{payload: {…}, displayType: 1, androidNotificationId: -1351902930, shown: true, isAppInFocus: true}
```
I'd recommend double checking the version that you're using and make sure it is the latest.

**Comment by isaaclem** [comment]
@rgomezp : It stated `"react-native-onesignal": "^3.2.11",`. Since just a `0.0.01` version behind I don't think it make a difference? But of course I will try it out asap. Thanks

**Comment by rgomezp** [comment]
No problem. Please let us know if you were able to resolve

**Comment by Nightsd01** [comment]
@isaaclem the current version of the SDK sends only one parameter in the `onReceived` callback. I’m not sure why you’re adding a second parameter?
