### ISSUE TITLE
Is react-native-onesignal avaiable for Google Analytics for Firebase

### ISSUE THREAD

**Issue by Donhv** [OneSignal/react-native-onesignal#734]
I want setup Google Analytics for Firebase for my react-native project like:
https://documentation.onesignal.com/docs/google-analytics-for-firebase
But seem react-native-onesignal not integrated. it is only avaiable in native:
- IOS: https://github.com/OneSignal/OneSignal-iOS-SDK/blob/master/iOS_SDK/OneSignalSDK/Source/OneSignalTrackFirebaseAnalytics.m
- android : https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/TrackFirebaseAnalytics.java

Anyone can help me or confirm this?

**Comment by Nightsd01** [comment]
@Donhv `react-native-onesignal` in iOS is simply a wrapper on top of our native iOS SDK, so you can definitely make use of the Firebase integration.

**Comment by sandeep14** [comment]
@Nightsd01 for android , os_notification_received event not showing in firebase  react-native-onesignal.

it is not availabe for react-native-onesignal android version?
