### ISSUE TITLE
How to get badge icon count?

### ISSUE THREAD

**Issue by JsonAveza** [OneSignal/react-native-onesignal#735]
**Description:**
 
I am using one signal in react native application for push notification android and ios. I want to get the badge count to open other page based on badge count in app . is it possible to get the badge count in react native  using one signal?.

(your description here)

**Environment**

I used one signal version is  : "react-native-onesignal": "^3.2.12",

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by Nightsd01** [comment]
@JsonAveza there isn’t a way to do this directly with our SDK. However in iOS you can access it natively using `UIApplication.shared.applicationIconBadgeNumber`

You might also find a package out there that lets you access this from JS.
