### ISSUE TITLE
Crash on purchase of IAP Android

### ISSUE THREAD

**Issue by macfanatic** [OneSignal/react-native-onesignal#737]
**Description:**

When I make a successful purchase of the `android.test.purchased` SKU on a physical Android phone, my callback succeeds with the purchase receipt but OneSignal crashes in another thread.

Error: `Expected receiver of type com.android.vending.billing.IInAppBillingService, but got android.os.BinderProxy`

**Environment**
1. react-native-onesignal 3.2.12
2. added using npm to an ejected expo SDK 32 app

**Steps to Reproduce Issue:**
Assumes you have a working OneSignal SDK installation.

1. Run app on a device
2. Purchase the consumable test product `android.test.purchased`
3. Observe the OneSignal billing observer crashes with illegal argument exception

**Stack Trace**

```
W/System.err: java.lang.IllegalArgumentException: Expected receiver of type com.android.vending.billing.IInAppBillingService, but got android.os.BinderProxy
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.onesignal.TrackGooglePurchase$2.run(TrackGooglePurchase.java:146)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
```

**Comment by rgomezp** [comment]
Hello,
Thanks for your patience. Could you please provide the full logcat of the device?

**Comment by macfanatic** [comment]
We resolved this issue recently by calling our `OneSignal.init()` in a different setup method.

We're now calling in our `App#componentWillMount()` method, whereas before we were calling in a callback method for `Expo.AppLoading#onFinish()` component callback.

Setup earlier vs after Expo has finished loading (even with our ejected Expo app) seems to have resolved the issue.
