### ISSUE TITLE
Jest test failing on TypeError: _reactNativeOnesignal.default.init is not a function (OneSignal + Jest)

### ISSUE THREAD

**Issue by AfanasievN** [OneSignal/react-native-onesignal#738]
**Description:**
## Jest test failing on TypeError: _reactNativeOnesignal.default.init is not a function

I am using jest tests and I've implemented oneSignal in my App.js
and when I try to run yarn test it then not passing tests.
Here is Error
<img width="1646" alt="Снимок экрана 2019-03-21 в 11 49 42" src="https://user-images.githubusercontent.com/25581141/54744401-99abd700-4bcf-11e9-9e44-09cd881b46da.png">

My App.js file:
<img width="655" alt="Снимок экрана 2019-03-21 в 11 50 03" src="https://user-images.githubusercontent.com/25581141/54744435-a7615c80-4bcf-11e9-816a-f1ccf6a034be.png">

My App.test.js:
<img width="572" alt="Снимок экрана 2019-03-21 в 11 49 53" src="https://user-images.githubusercontent.com/25581141/54744443-b0522e00-4bcf-11e9-9263-a6939e2978e1.png">

My jest-setup.js:
<img width="642" alt="Снимок экрана 2019-03-21 в 11 53 14" src="https://user-images.githubusercontent.com/25581141/54744561-f60ef680-4bcf-11e9-90b4-798e41b10646.png">

**Environment**
"react": "16.8.4",
"react-native": "0.59.1",
"babel-jest": "24.5.0",
"jest": "24.5.0",
 "react-test-renderer": "16.8.4"
"jest": {
    "preset": "react-native",
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    },
    "transformIgnorePatterns": [
      "./node_modules/(?!(react-native|styled-components|react-navigation|react-test-renderer|react-native-onesignal|react-native-localization|react-native-gesture-handler|react-native-vector-icons|@react-native-community/async-storage|@react-native-community/netinfo|@react-navigation/.*))"
    ],
    "setupFiles": [
      "./jest-setup.js"
    ],
    "moduleNameMapper": {
      "^styled-components$": "<rootDir>/node_modules/styled-components/native/dist/styled-components.native.cjs.js"
    }
  }

**Comment by rgomezp** [comment]
Hello,
Thank you for your patience. Were you able to resolve? I'd be interested in what notificationsService does. It would be helpful if you shared a sample project so I could build it and take a closer look.

**Comment by AfanasievN** [comment]
@rgomezp this is my NotificationService
<img width="935" alt="Снимок экрана 2019-04-02 в 12 15 32" src="https://user-images.githubusercontent.com/25581141/55391188-87238d00-5541-11e9-93a6-d6f4bcb24a1c.png">

And this one is NotificationsHandlers
<img width="676" alt="Снимок экрана 2019-04-02 в 12 15 53" src="https://user-images.githubusercontent.com/25581141/55391219-973b6c80-5541-11e9-8e02-d607c68c6ed9.png">

**Comment by rgomezp** [comment]
Hello,
Could you please share a repro project with us through our support channel at onesignal.com so we can build it?

**Comment by Nightsd01** [comment]
@AfanasievN OneSignal’s react native SDK is just a wrapper on top of a native SDK framework. Are your tests pure JS or do they emulate iOS/Android and load our native framework?

I would suggest using mocking so that your tests don’t use OneSignal react native code at all.

**Comment by AfanasievN** [comment]
Hello, @Nightsd01 @rgomezp I found a solution today. 
I still don't know why but jest could not figure out functions after dot like on screen shot
<img width="617" alt="Снимок экрана 2019-05-02 в 16 49 12" src="https://user-images.githubusercontent.com/25581141/57080114-8c1f5c00-6cfa-11e9-9c8a-eb669e9f08bc.png">

My workaround is to add to my jest-setup file this code --->
` 
jest.mock('react-native-onesignal', () => {
  return {
    OneSignal: jest.fn(() => 'undefined'),
    init: jest.fn(() => 'undefined'),
    inFocusDisplaying: jest.fn(() => 'undefined'),
    addEventListener: jest.fn(() => 'undefined'),
  };
});
`
<img width="636" alt="Снимок экрана 2019-05-02 в 16 50 16" src="https://user-images.githubusercontent.com/25581141/57080219-bbce6400-6cfa-11e9-9e37-f0b99b83ff8f.png">

Thanks for your time and awareness, we can close this issue

<img width="662" alt="Снимок экрана 2019-05-02 в 16 53 14" src="https://user-images.githubusercontent.com/25581141/57080273-ddc7e680-6cfa-11e9-818d-32439c29ef1c.png">

**Comment by 0sudiptoroy** [comment]
I have TypeError: user.generateAuthToken is not a function problem and my problem is not solve

**Comment by 0sudiptoroy** [comment]
![code](https://user-images.githubusercontent.com/68549946/96678428-4c857d80-138f-11eb-827a-0985269cd076.png)
![terminal error in jest](https://user-images.githubusercontent.com/68549946/96678445-527b5e80-138f-11eb-8e7e-0f394d9f2ba8.png)

**Comment by 0sudiptoroy** [comment]
I am using "jest": "^26.5.3", "supertest": "^5.0.0",

**Comment by rodrigogaraujo** [comment]
This error has fix?

    I put the mock but this error continue
Test suite failed to run

    Invariant Violation: Native module cannot be null.
    import OneSignal from 'react-native-onesignal'
    `jest.mock('react-native-onesignal', () => { ....`

**Comment by blwinters** [comment]
Here is a full set of mock functions based on the OneSignal type definition. Because it is so large, I put it in a separate mock file, rather than use `jest.mock` in the jest setup file.

``` javascript
// __mocks__/react-native-onesignal.js

export default {
  setAppId: jest.fn(),
  addPermissionObserver: jest.fn(),
  clearPermissionObservers: jest.fn(),
  addSubscriptionObserver: jest.fn(),
  clearSubscriptionObservers: jest.fn(),
  addEmailSubscriptionObserver: jest.fn(),
  clearEmailSubscriptionObservers: jest.fn(),
  addSMSSubscriptionObserver: jest.fn(),
  clearSMSSubscriptionObservers: jest.fn(),
  setNotificationWillShowInForegroundHandler: jest.fn(),
  setNotificationOpenedHandler: jest.fn(),
  promptForPushNotificationsWithUserResponse: jest.fn(),
  registerForProvisionalAuthorization: jest.fn(),
  disablePush: jest.fn(),
  unsubscribeWhenNotificationsAreDisabled: jest.fn(),
  enterLiveActivity: jest.fn(),
  exitLiveActivity: jest.fn(),
  isLocationShared: jest.fn(),
  setLocationShared: jest.fn(),
  promptLocation: jest.fn(),
  getDeviceState: jest.fn(),
  setLanguage: jest.fn(),
  sendTag: jest.fn(),
  sendTags: jest.fn(),
  getTags: jest.fn(),
  deleteTag: jest.fn(),
  deleteTags: jest.fn(),
  setEmail: jest.fn(),
  logoutEmail: jest.fn(),
  setSMSNumber: jest.fn(),
  logoutSMSNumber: jest.fn(),
  postNotification: jest.fn(),
  clearOneSignalNotifications: jest.fn(),
  removeNotification: jest.fn(),
  removeGroupedNotifications: jest.fn(),
  setLaunchURLsInApp: jest.fn(),
  setExternalUserId: jest.fn(),
  removeExternalUserId: jest.fn(),
  setInAppMessageClickHandler: jest.fn(),
  setInAppMessageLifecycleHandler: jest.fn(),
  addTrigger: jest.fn(),
  addTriggers: jest.fn(),
  removeTriggerForKey: jest.fn(),
  removeTriggersForKeys: jest.fn(),
  getTriggerValueForKey: jest.fn(),
  pauseInAppMessages: jest.fn(),
  sendOutcome: jest.fn(),
  sendUniqueOutcome: jest.fn(),
  sendOutcomeWithValue: jest.fn(),
  userProvidedPrivacyConsent: jest.fn(),
  requiresUserPrivacyConsent: jest.fn(),
  setRequiresUserPrivacyConsent: jest.fn(),
  provideUserConsent: jest.fn(),
  setLogLevel: jest.fn(),
  clearHandlers: jest.fn(),
}
```

**Comment by blwinters** [comment]
Here's a new mock for v5.x

``` js
module.exports = {
  OneSignal: {
    initialize: jest.fn(),
    login: jest.fn(),
    logout: jest.fn(),
    setConsentRequired: jest.fn(),
    setConsentGiven: jest.fn(),
    Debug: {
      setLogLevel: jest.fn(),
      setAlertLevel: jest.fn(),
    },
    LiveActivities: {
      enter: jest.fn(),
      exit: jest.fn(),
      setPushToStartToken: jest.fn(),
      removePushToStartToken: jest.fn(),
      setupDefault: jest.fn(),
      startDefault: jest.fn(),
    },
    User: {
      pushSubscription: {
        addEventListener: jest.fn(),
        removeEventListener: jest.fn(),
        getPushSubscriptionId: jest.fn(),
        getIdAsync: jest.fn().mockResolvedValue(null),
        getPushSubscriptionToken: jest.fn(),
        getTokenAsync: jest.fn().mockResolvedValue(null),
        getOptedIn: jest.fn(),
        getOptedInAsync: jest.fn().mockResolvedValue(false),
        optOut: jest.fn(),
        optIn: jest.fn(),
      },
      addEventListener: jest.fn(),
      removeEventListener: jest.fn(),
      getOnesignalId: jest.fn().mockResolvedValue(null),
      getExternalId: jest.fn().mockResolvedValue(null),
      setLanguage: jest.fn(),
      addAlias: jest.fn(),
      addAliases: jest.fn(),
      removeAlias: jest.fn(),
      removeAliases: jest.fn(),
      addEmail: jest.fn(),
      removeEmail: jest.fn(),
      addSms: jest.fn(),
      removeSms: jest.fn(),
      addTag: jest.fn(),
      addTags: jest.fn(),
      removeTag: jest.fn(),
      removeTags: jest.fn(),
      getTags: jest.fn().mockResolvedValue({}),
    },
    Notifications: {
      hasPermission: jest.fn(),
      getPermissionAsync: jest.fn().mockResolvedValue(false),
      requestPermission: jest.fn().mockResolvedValue(false),
      canRequestPermission: jest.fn().mockResolvedValue(false),
      registerForProvisionalAuthorization: jest.fn(),
      permissionNative: jest.fn().mockResolvedValue(null),
      addEventListener: jest.fn(),
      removeEventListener: jest.fn(),
      clearAll: jest.fn(),
      removeNotification: jest.fn(),
      removeGroupedNotifications: jest.fn(),
    },
    InAppMessages: {
      addEventListener: jest.fn(),
      removeEventListener: jest.fn(),
      addTrigger: jest.fn(),
      addTriggers: jest.fn(),
      removeTrigger: jest.fn(),
      removeTriggers: jest.fn(),
      clearTriggers: jest.fn(),
      setPaused: jest.fn(),
      getPaused: jest.fn().mockResolvedValue(false),
    },
    Location: {
      requestPermission: jest.fn(),
      setShared: jest.fn(),
      isShared: jest.fn().mockResolvedValue(false),
    },
    Session: {
      addOutcome: jest.fn(),
      addUniqueOutcome: jest.fn(),
      addOutcomeWithValue: jest.fn(),
    },
  },
}
```
