### ISSUE TITLE
error 3000 returned from apns

### ISSUE THREAD

**Issue by yusuf987** [OneSignal/react-native-onesignal#739]
I am implementing push notification with one signal
I follow all the old documentation for implementation below is the link

https://github.com/geektimecoil/react-native-onesignal/blob/732491fece1fa92946ca6dacf173af28a2b2e618/README.md

on one signal dashboard it show some 3000 apps issue with my real device 

![Screen Shot 2019-03-24 at 5 43 58 PM](https://user-images.githubusercontent.com/24749530/54879313-6bdbc200-4e5d-11e9-8ce2-b12478f1c21d.png)

and also not able to receive any notification showing below error
![Screen Shot 2019-03-24 at 5 45 44 PM](https://user-images.githubusercontent.com/24749530/54879330-9168cb80-4e5d-11e9-8278-a294f2892760.png)

does anyone know what is issue 

I have tried to re generate provisioning profiles but issue still remain

**Comment by Nightsd01** [comment]
@yusuf987 are you sure you actually enabled the Push Notifications capability for your app in Xcode?

**Comment by yusuf987** [comment]
> @yusuf987 are you sure you actually enabled the Push Notifications capability for your app in Xcode?

yes I enabled the capability I also got the pop-up which asks permission for push notification

**Comment by rgomezp** [comment]
Could you please include the full log from the device? Thanks

**Comment by rgomezp** [comment]
Closing due to no response
