### ISSUE TITLE
iOS version of Onesignal.getPermissionSubscriptionState does not work with RN 0.59.4 

### ISSUE THREAD

**Issue by cyb3rsalih** [OneSignal/react-native-onesignal#743]
**Description:**

Onesignal.getPermissionSubscriptionState method does not work with React Native v0.59.4  but works with v0.58.3 

**Environment**
I am using same version of Onesignal SDK which 3.2.12 
And install the package with yarn

**Steps to Reproduce Issue:**

  1. Install the OneSignal SDK using yarn into your project
  2. Initialize the SDK in the App.js which like in documentation
  3. Run iOS app in your device or simulator
  3. Try to get userID with this code :

```ES6
componentWillMount() {
        OneSignal.init("MY_ONESIGNAL_ID");
        OneSignal.configure();
        OneSignal.getPermissionSubscriptionState( (status) => { 
            userID = status.userId; 
        this.setState({ myOnesignalID:userID })
        });
    }
```

With 0.58.3 version this code works well 

but with 0.59.4  OneSignal.getPermissionSubscriptionState does not work. So I can't get the userID 

I don't try the code with Android.

**Comment by Nightsd01** [comment]
@cyb3rsalih what does “it does not work” mean? Are you seeing a crash or something?

**Comment by cyb3rsalih** [comment]
ahh.. sorry. I mean, Just function not work. Does not give me the userID. No crash in the app.

**Comment by cyb3rsalih** [comment]
It is so strange that, It works now. Probably subscription process take long.
