### ISSUE TITLE
onesignal.com used Cloudflare to restrict access

### ISSUE THREAD

**Issue by MahmoudYaser0** [OneSignal/react-native-onesignal#746]
i am using onesignal with react-native as always but now i have new error

![Clipboarder 2019 04 23](https://user-images.githubusercontent.com/47948254/56563458-6389ba80-65b4-11e9-9729-8fc11422bfd7.png)

When i start a vpn or proxy server it works

**Environment**
"react-native": "0.57.4",
"react-native-onesignal": "^3.2.12",

**Comment by rgomezp** [comment]
Hello,
What country are you located in?

**Comment by MahmoudYaser0** [comment]
syria

**Comment by rgomezp** [comment]
I'm sorry we currently don't provide our service to folks in your country. I'm really sorry for the inconvenience

**Comment by xeroxoid** [comment]
Hi @rgomezp we are having the same issue here in Greece. Notifications worked fine until we updated to 3.9.1 (from 3.8.1).

**Comment by lsuhail** [comment]
Same issue from Yemen mobile apps not getting notifications. firebase is better an valid option.
thanks to Google.
