### ISSUE TITLE
Is it possible to use same one signal app for multiple react native app  ?

### ISSUE THREAD

**Issue by degodfather** [OneSignal/react-native-onesignal#747]
I have two different RN App on android, I want to use same OS app id in both applications. Is it possible ?

**Comment by rgomezp** [comment]
Hello,
Each app will need its own app id. Why do you want to do this?

**Comment by degodfather** [comment]
I was planning to share same codebase with multiple application. So thought of using the same OS app . Thank you !

**Comment by rgomezp** [comment]
No problem!
