### ISSUE TITLE
popup notification not showing android

### ISSUE THREAD

**Issue by omarDtp** [OneSignal/react-native-onesignal#748]
**Description:**

I installed react-native-onesignal as the guide said and linked it correctly, I am able to recieve notifications but they're not sliding down from status bar even though all my files are correctly installed.

**Environment**

installed through yarn since npm gave me permission error
react-native: 0.59.4
react:16.8.6
react-native-onesignal:3.2.12

screenshots:
https://ibb.co/BKP0STQ
https://ibb.co/fpQ6Hsy
https://ibb.co/gMFMyy2
https://ibb.co/pZL6pxf
https://ibb.co/X2Nm3Qj

**Comment by arnekolja** [comment]
@omarDtp How have you been able to solve this?
