### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by davidianbonner** [OneSignal/react-native-onesignal#75]
Hi,

I recently came across an issue with archiving an iOS app due to the `Argument list too long: recursive header expansion failed`error. It was failing within the `react-native-onesignal/android/build/intermediate`directory. 

Obviously not entirely related to this library, it was the additional paths under the `android` directory that triggered the issue for us. As the paths are expanded and attached to the command for all search paths stated in the "Build Settings". 

I resolved this on my end by changing the search path to `$(SRCROOT)/../node_modules/react-native-onesignal/ios`. 

My thoughts/question is wether the above path should be highlighted in the documentation? I see no reason why the `android` directory should be included.

Thanks

**Comment by avishayil** [comment]
Thanks @dbonner1987 , you did the right thing.
We'll clarify that in the documentation.

**Comment by josquiroz6** [comment]
Hello, I tried to change the search path, but it didn't work out. Could you please let me know the reason?

**Comment by nerdvibe** [comment]
@avishayil I'm having the same issue:

`/Users/user/projects/project/app/vers/ios/../node_modules/react-native-onesignal/android/build/intermediates/res/merged/debug/values-ja.` and I can't find a solution. 

Does anybody have any clue? The `$(SRCROOT)/../node_modules/react-native-onesignal/ios` solution seems to not be working with me..
