### ISSUE TITLE
Example  Android ReactNative build fails due to build error

### ISSUE THREAD

**Issue by quarryman** [OneSignal/react-native-onesignal#750]
**Description:**
I am following [setup guide](https://documentation.onesignal.com/docs/react-native-sdk-setup) to run example React Native app from this repo on Android.

Setup without any changes fails due to next error:

`error: package com.geektime.rnonesignalandroid does not exist`

Most issues like this are resolved by adding `compile project(':react-native-onesignal')` to build.gradle

In my case it's already there.

I see that actual example code is outdated as it uses deprecated 'compile' directive so I followed ['setup guide Android Specific Instructions'](https://documentation.onesignal.com/docs/react-native-sdk-setup#section-android-specific-instructions) and changed deprecated 'compile' to `implementation 'com.onesignal:OneSignal:[3.10.8, 3.99.99]'`, however error is still there

In Android Studio I am able to SYNC after using  `implementation 'com.onesignal:OneSignal:[3.10.8, 3.99.99]'` however build still fails with the same error.

Tried running with cli `react-native run-android` with the same result.

I see error package is required in MainApplication.java and  its present in 'node_modules' under right path/name.

What else should I check and how do I know it was successfully compiled?

**Environment**
 react-native: "0.55.4",
 react-native-onesignal: "^3.2.12",
 compileSdkVersion 27
 buildToolsVersion 27.0.3

**Steps to Reproduce Issue:**
First way
1. Clone repo git clone https://github.com/geektimecoil/react-native-onesignal
2.  cd examples && cd RNOneSignal
3. yarn
4. react-native run-android
Results in `error: package com.geektime.rnonesignalandroid does not exist`
Another way - follow guide instructions with  - with the same result.

**Anything else:**
I fould closed issues with the same error and they are resolved by compiling react-native-onesignal module in build.gradle, which is done in my case for both deprecated 'compile' and new 'implementation' syntax

**Comment by rgomezp** [comment]
Hello @quarryman ,
I wasn't able to reproduce the issue, unfortunately. In either case, thanks for bringing up the fact we have to update `compile` to `implementation`. The changes will be reflected in the next release. In the meantime, if you want to [link to the files locally](https://stackoverflow.com/questions/14381898/local-dependency-in-package-json) from your `package.json`, you can clone them [here](https://github.com/geektimecoil/react-native-onesignal/tree/update-testapp).

**Comment by quarryman** [comment]
Hello @rgomezp 
Thanx for reviewing my issue.
I would ask to sync current repo and documentation.
I think I would create another issue for this. This one can be closed.
