### ISSUE TITLE
Sync example in this repo with official documentation

### ISSUE THREAD

**Issue by quarryman** [OneSignal/react-native-onesignal#752]
**Description:**
The problem is that RN example in this repo is not in sync with official documentation for React Native which leads to misunderstanding if example code is outdated and if it must be updated according to official docs.

Here is what I mean:

This is  _MainApplication.java_ code from [documentation](https://documentation.onesignal.com/docs/react-native-sdk-setup):

```
import com.geektime.rnonesignalandroid.ReactNativeOneSignalPackage;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new ReactNativeOneSignalPackage() // You must return the ReactNativeOneSignalPackage here
      );
    }
  };
  
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return getPackages();
  }
}
```

Which is different from what you have by default in this repo RN example. So it's not clear if this repo code is outdated and must be updated from documentation.

Another issue is that documentation code has this override

```
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return getPackages();
  }
```

for _Application_ class, however Application doesnt have corresponding method, unless you extend _NavigationApplication_.

Documentation code simply won't compile.

So documentation should either not have this override, or declare class this way

`public class MainApplication extends NavigationApplication `

given you have previously installed _reactnativenavigation_
This will allow for override as NavigationApplication implements _createAdditionalReactPackages()_

**Environment**

**Steps to Reproduce Issue:**

1. Take MainApplication.java code from [documentation](https://documentation.onesignal.com/docs/react-native-sdk-setup)

2. Insert to MainApplication.java
3. Try to compile.
4. Compilation fails due to overriding method that is not present in Application class.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Hello,
Thanks for bringing this up. You shouldn't copy and paste that code from the documentation, though I admit it can lead to confusion. Everybody will have slightly different setups depending on the libraries they're using etc...

Would love to get your thoughts on whether [this](https://documentation.onesignal.com/docs/react-native-sdk-setup#section-android-specific-instructions) is clearer and cleaner.

Cheers

**Comment by rgomezp** [comment]
Thank you for bringing this up. We have moved that section to Troubleshooting. Hopefully it won't confuse folks moving forward. Thanks for bringing up this issue. 

Cheers
