### ISSUE TITLE
Custom Sound Notification Folder Directory for React Native Platform OneSignal Sound not working

### ISSUE THREAD

**Issue by nahidmbstu** [OneSignal/react-native-onesignal#753]
I have gone over the documentation over here. 
https://documentation.onesignal.com/docs/customize-notification-sounds

the doc does not says anything specifically for react native , in which folder i should add the sound files. it would be helpful for everybody .

**Comment by rgomezp** [comment]
Hello,
Thank you for your question. You have to follow the respective instructions for the native version of each platform. If you are using Expo, you will need to eject first.

**Comment by nahidmbstu** [comment]
i have made my app using react-native-cli  for android  platform . can you please tell me where to i should put the sound file . thanks ? @rgomezp

**Comment by rgomezp** [comment]
Hello,
You must put it in the `res/raw` folder

**Comment by nahidmbstu** [comment]
is  res/raw from the /root    or from    /root/android/   . i have tried both . didnt work...

**Comment by nahidmbstu** [comment]
@rgomezp

**Comment by rgomezp** [comment]
did you include the file extension when you put the name of the file in the dashboard? @nahidmbstu

**Comment by nahidmbstu** [comment]
i have added the file in .mp3 format in both folder.  i did not added the file extension in dashboard. it gives me the default sound. not the custom one. @rgomezp

**Comment by rgomezp** [comment]
Please make sure you have done all of the following:

1. You have made sure that the file is in the \<root\>/android/app/res/raw folder (if res/raw don't exist, create them)
2. The file has the file extension .mp3 in the folder but not in the dashboard
3. You have checked that the file is not being removed in the build step by extracting the APK and ensuring it's still there

Sometimes, the build step will remove files it believes are unnecessary depending on the setup you have. Please make sure the build is not removing the file.

Cheers

**Comment by rgomezp** [comment]
Feel free to ask I reopen this issue if you are still having issues. I will also make sure to update the documentation to make sure it reflects the correct path

Edit: https://documentation.onesignal.com/docs/customize-notification-sounds#section-android-and-derivatives-like-amazon- **ADDED**

**Comment by jeffreyabarrios** [comment]
Hello! I have the same issue im using React Native. 

I have added the mp3 (and ogg) file to android/app/src/main/res/raw, also tried on /android/app/res/raw, and setting the name on the notification template like "notificationsound" without the extension, also tried setting it from the REST API and still when the notification arrives, it plays the default sound.

Please help.

**Comment by rgomezp** [comment]
Howdy,
Please unpack the apk file and see if the sound file is being added to the correct location.

**Comment by felipebutcher** [comment]
Hey guys. I was having the same problem. Not sure which one solved but I did these two things:
- Open project from android studio, clean, build, run.
- Removed the app and installed again.
It actually worked after I reinstalled the app.

**Comment by 4sagar** [comment]
Make sure you have 'sound' permission enabled in the app permissions.

**Comment by rohitkum28** [comment]
> Hey guys. I was having the same problem. Not sure which one solved but I did these two things:
> 
> * Open project from android studio, clean, build, run.
> * Removed the app and installed again.
>   It actually worked after I reinstalled the app.

After struggling for hours, surprisingly this is what fixed my issue.
Also, the path to store the sound file given in the documentation is wrong. The file should be stored at `<project-root>\android\app\src\main\res\raw` instead of `<project-root>/android/app/res/raw`. I suggest onesignal team to kindly update that as it will difficult for someone with non-android development  background to figure the mistake.

**Comment by anastely** [comment]
I have Xiaomi and to allow sounds should I do it manually `app info => Notification => allow sound ✅` :D after enabling it I can get the sound as expected So
@yosagar can you share this permission?
i couldn't found it :\

**Comment by RizqiSyahrendra** [comment]
> > Hey guys. I was having the same problem. Not sure which one solved but I did these two things:
> > 
> > * Open project from android studio, clean, build, run.
> > * Removed the app and installed again.
> >   It actually worked after I reinstalled the app.
> 
> After struggling for hours, surprisingly this is what fixed my issue. Also, the path to store the sound file given in the documentation is wrong. The file should be stored at `<project-root>\android\app\src\main\res\raw` instead of `<project-root>/android/app/res/raw`. I suggest onesignal team to kindly update that as it will difficult for someone with non-android development background to figure the mistake.

Thank you, it works

**Comment by ptucky** [comment]
> > Hey guys. I was having the same problem. Not sure which one solved but I did these two things:
> > 
> > * Open project from android studio, clean, build, run.
> > * Removed the app and installed again.
> >   It actually worked after I reinstalled the app.
> 
> After struggling for hours, surprisingly this is what fixed my issue. Also, the path to store the sound file given in the documentation is wrong. The file should be stored at `<project-root>\android\app\src\main\res\raw` instead of `<project-root>/android/app/res/raw`. I suggest onesignal team to kindly update that as it will difficult for someone with non-android development background to figure the mistake.

This safe me, it works

**Comment by mohammad6vakili** [comment]
Hi @rgomezp.
I went through these steps:
1- Put relax.mp3 sound file in `<project-root>/android/app/src/main/res/raw`
2- Create a group and a channel in `Android Notification Channels` section in Onesignal dashboard in setting/messaging
![channel](https://user-images.githubusercontent.com/59134745/206909635-3fb1bbf4-1e44-4d20-9991-46642e51ff05.png)
![new](https://user-images.githubusercontent.com/59134745/206909488-9a65a3c9-4831-4086-8767-a54983641c41.png)
As you can see the file name is `relax` and in the channel setting I just entered `relax` in sound name field.
but still my notification sound is the default device sound.
did I miss something?
please help @rgomezp
