### ISSUE TITLE
Writing app_id outside js code

### ISSUE THREAD

**Issue by Djazouli** [OneSignal/react-native-onesignal#755]
**Description:**

I am trying to use onesignal for my android app. Currently, this is working, but I have this line in my file app.js: 

    OneSignal.init('xxxxxx-xxxx-xxxx-xxxxx-xxxxxxxxxxx');

where all the xxxx represents my onesignal_app_id. This is what is recommended in [OneSignal doc](https://documentation.onesignal.com/docs/react-native-sdk), but I am not familiar with app creation, and my question is: Does this mean that if someone unzip the apk, he can get my onesignal_app_id?

I was using an older buildTool (23.0.2) before, allowing me to write the onesignal_app_id in the gradle (as can be seen [here](https://github.com/geektimecoil/react-native-onesignal/blob/732491fece1fa92946ca6dacf173af28a2b2e618/README.md)), and it felt safer. But I had to update some dependencies, and I need to use buildTools 28, and the previous method does not work anymore.

So my question is: can I write the app_id safely in my code? If not, how to put it in a safe place?

**Environment**

For my android:     
```
compileSdkVersion 28
buildToolsVersion '28.0.3'

dependencies:    {api "com.onesignal:OneSignal:3.10.7"}
```
 I used npm to add the SDK to my project.
 In the js code, simply:
 `import OneSignal from 'react-native-onesignal';`

**Steps to Reproduce Issue:**

Well this isn't really a bug, more help wanted.

**Anything else:**

(crash stacktraces, as well as any other information here)

Thanks a lot!
Djazouli

**Comment by rgomezp** [comment]
Hello,
Thank you so much for your question. You can read our response [here](https://documentation.onesignal.com/docs/security#section-what-happens-if-a-bad-actor-gains-access-to-my-app_id-).
