### ISSUE TITLE
example app project iOS extension service not eneabled

### ISSUE THREAD

**Issue by harutyundr** [OneSignal/react-native-onesignal#761]
**Description:**
As per documentation, OneSignal.inFocusDisplaying(2) should show the incoming notification using OS notification center. It shows an alert instead.

**Environment**
The issue is confirmed with the example project at examples/RNOneSignal without any changes.
Testing via XCode on iPad Mini running iOS 9.3.5

**Steps to Reproduce Issue:**
The instructions to run the project don't mention it, but I had to enable Push Notifications and Background Modes -> Remote notifications. Notifications when the app is in background work as expected.

Thank you!

**Comment by rgomezp** [comment]
@harutyundr ,
Thanks for bringing this up. This is fixed in [this PR](https://github.com/geektimecoil/react-native-onesignal/pull/759) and should not require those steps moving forward. 

Feel free to follow up and I can reopen the issue if needed! :)
