### ISSUE TITLE
Seems like you included .git/ folder inside the npm package

### ISSUE THREAD

**Issue by mtt87** [OneSignal/react-native-onesignal#762]
**Description:**
Seems like you included the `.git` folder with the package release.
This is problematic because it can throw errors like these when trying to install other packages
```
npm ERR! path /node_modules/react-native-onesignal
npm ERR! code EISGIT
npm ERR! git /node_modules/react-native-onesignal: Appears to be a git repo or submodule.
npm ERR! git     /react-native-onesignal
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

**Environment**
Using `"react-native-onesignal": "^3.2.13"`

**Steps to Reproduce Issue:**
Install the package then try to install any other package, i.e.
`npm i --save react-native-onesignal`
`npm i --save react-native-schemes-manager`

**Anything else:**

It can be temporarily fixed by removing `/node_modules/react-native-onesignal/.git` but the git folder should not be inculded in the npm released package.

**Comment by thinklinux** [comment]
Yeap and npm install fails every time because of that. It's kind of annoying :)

**Comment by rgomezp** [comment]
Hello,
Thanks for bringing this up! We're so sorry and will try to get this fixed asap.

**Comment by rgomezp** [comment]
Hello everyone, this has been fixed.
