### ISSUE TITLE
Notifications are not received when app is killed and increase by option is selected on IOS

### ISSUE THREAD

**Issue by oroundo-tech** [OneSignal/react-native-onesignal#766]
I am having issues with React Native One Signal.

**Description:**

I have followed instructions for React Native and installed package successfully.
I am getting delivered applications with PushNotificationIOS from React Native.

When the app is killed and I send notification, I can get them when opening app next time.

In case when I send notification from dashboard that increases badge number, this is not working.

**Environment**

  "react-native": "0.57.8",
 "react-native-onesignal": "3.2.13"

**Steps to Reproduce Issue:**

1. Install the OneSignal SDK
2. Kill the app
3. Go to OneSignal dashboard and send IOS notification that increases badge number
4. Open the app 
5. PushNotificationIOS.getDeliveredNotifications() returns []

**Comment by rgomezp** [comment]
Hello,
Could you please provide more details regarding your issue?
From what I understand so far, the notifications are coming in all at once for iOS instead of when they are actually sent. Also, the badge count is not working correctly? Could you please describe the badge behavior you are seeing?

**Comment by oroundo-tech** [comment]
Hi,
 here is the workflow I want to achieve:
1. I send notification from OneSignal dashboard to IOS device and set increase badge by 1.
2. Notification is received on the phone.
3. App is killed.
4. I open the app and get notifications from Notifications Center using PushNotificationIOS from react-native.

What is wrong ? 
When I set increase badge by 1 this is not working.
When I dont set the badge increase this workflow is working.

**Comment by rgomezp** [comment]
Because you're using local notifications in combination with our SDK, you may need to set the badge count manually and keep track of it off the device. I don't know how the local notification library for React Native works but if it is also manipulating badge counts, there may be a conflict with our SDK.

**Comment by rgomezp** [comment]
Closing due to no response
