### ISSUE TITLE
Google Play Services Library Error

### ISSUE THREAD

**Issue by sagarv1997** [OneSignal/react-native-onesignal#768]
**Description:**

Almost half of the registered devices are showing Google Play services library error in OneSignal Dashboard. I Referred to all the previous issues #322 and #525 and tried each and every step but still, the newly registered devices are showing Google Play Services library error and are not able to receive a notification.

I even tried to create a fresh new project and integrate OneSignal but still, I am facing the same error

![image](https://user-images.githubusercontent.com/13160994/58395022-d5499e00-8063-11e9-80ac-f08aa96aaf4e.png)

**Environment**

OneSignal React-Native SDK: 3.2.12
React-native: 0.57.8

**Steps Tried to solve**

1. Upgraded React-native OneSignal SDK
2. #387 Add <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/> to the AndroidManifest.xml
3. https://github.com/geektimecoil/react-native-onesignal/issues/525#issuecomment-392224930 Tried this method.
4. Created a fresh new project using the latest React-native but still the same issue.
5. Reinstalled Google Play services from Android Studio

**Project Build.gradle**

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 27
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
        maven {  // <-- THIS
            url 'https://maven.google.com/' // <-- THIS
            name 'Google' // <-- THIS
        } // <-- THIS
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {  // <-- THIS
            url 'https://maven.google.com/' // <-- THIS
            name 'Google' // <-- THIS
        } // <-- THIS
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}
`

**App Build.gradle**

`apply plugin: "com.android.application"

import com.android.build.OutputFile

buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal 
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.1, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"

def enableSeparateBuildPerCPUArchitecture = true

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "com.pokewreck.poketimer"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 14
        versionName "3.2.0"

    }
        signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
 
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release

        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-add-calendar-event')
    compile project(':react-native-splash-screen')
    compile project(':react-native-billing')
    compile project(':react-native-admob')
    compile project(':react-native-onesignal')
    compile project(':react-native-vector-icons')
    compile project(':react-native-gesture-handler')
    compile project(':react-native-code-push')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules

}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
`

**Comment by rgomezp** [comment]
The Google Play Services Library error means that one of the libraries required for OneSignal was not correctly added during the setup process. 

Please double check that you have correctly completed all the setups on our mobile SDK setup docs for the SDK you are using: https://documentation.onesignal.com/docs/mobile-sdk-setup

Also, make sure you are using the latest version of the Android Support Library in your app. It looks like you're using an older version.

You can turn on the setLogLevel method and send us a full log from the device getting this error if you need further assistance.

**Comment by sagarv1997** [comment]
> The Google Play Services Library error means that one of the libraries required for OneSignal was not correctly added during the setup process.
> 
> Please double check that you have correctly completed all the setups on our mobile SDK setup docs for the SDK you are using: https://documentation.onesignal.com/docs/mobile-sdk-setup
> 
> Also, make sure you are using the latest version of the Android Support Library in your app. It looks like you're using an older version.
> 
> You can turn on the setLogLevel method and send us a full log from the device getting this error if you need further assistance.

Thanks for the Help and Support, I found that the issue was with the firebase cloud settings!
Issue solved.

**Comment by arfa123** [comment]
> The Google Play Services Library error means that one of the libraries required for OneSignal was not correctly added during the setup process.
> 
> Please double check that you have correctly completed all the setups on our mobile SDK setup docs for the SDK you are using: https://documentation.onesignal.com/docs/mobile-sdk-setup
> 
> Also, make sure you are using the latest version of the Android Support Library in your app. It looks like you're using an older version.
> 
> You can turn on the setLogLevel method and send us a full log from the device getting this error if you need further assistance.

I am also facing same error on react native: 0.60.5 and react native onesignal: 3.3.2. I have followed all the steps mention in documentation. can you explain which google play services library required by the onesignal?

**Comment by adhinugraha** [comment]
> > The Google Play Services Library error means that one of the libraries required for OneSignal was not correctly added during the setup process.
> > Please double check that you have correctly completed all the setups on our mobile SDK setup docs for the SDK you are using: https://documentation.onesignal.com/docs/mobile-sdk-setup
> > Also, make sure you are using the latest version of the Android Support Library in your app. It looks like you're using an older version.
> > You can turn on the setLogLevel method and send us a full log from the device getting this error if you need further assistance.
> 
> I am also facing same error on react native: 0.60.5 and react native onesignal: 3.3.2. I have followed all the steps mention in documentation. can you explain which google play services library required by the onesignal?

i have same error  on react native: 0.60.5 and react native onesignal: 3.3.2. here are the error on logcat:

> 2019-08-26 17:40:15.164 29951-30079/com.kora.agen E/OneSignal: Error Getting FCM Token
    java.io.IOException: INVALID_SENDER
        at com.google.firebase.iid.zzk.zza(com.google.firebase:firebase-iid@@19.0.1:66)
        at com.google.firebase.iid.zzk.zza(com.google.firebase:firebase-iid@@19.0.1:79)
        at com.google.firebase.iid.zzo.then(com.google.firebase:firebase-iid@@19.0.1:4)
        at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by rgomezp** [comment]
If you're still using 27, try upgrading to 28 @arfa123

**Comment by faridsaud** [comment]
@sagarv1997 what issue did you have on your firebase project? I'm facing the same issue and so far I haven't found a solution.

**Comment by renanmav** [comment]
I’d like to know too @sagarv1997

**Comment by parthanjaria** [comment]
> > The Google Play Services Library error means that one of the libraries required for OneSignal was not correctly added during the setup process.
> > Please double check that you have correctly completed all the setups on our mobile SDK setup docs for the SDK you are using: https://documentation.onesignal.com/docs/mobile-sdk-setup
> > Also, make sure you are using the latest version of the Android Support Library in your app. It looks like you're using an older version.
> > You can turn on the setLogLevel method and send us a full log from the device getting this error if you need further assistance.
> 
> Thanks for the Help and Support, I found that the issue was with the firebase cloud settings!
> Issue solved.

Can you please let us know what change cleared the issue? @sagarv1997

**Comment by 0xhex** [comment]
bro,can you share solution please @sagarv1997 
also did you find a solutions guys? @renanmav @faridsaud @parthanjaria
