### ISSUE TITLE
iOS 13 getPermissionSubscriptionState invalid token

### ISSUE THREAD

**Issue by amitassaraf** [OneSignal/react-native-onesignal#771]
**Description:**

Seems like on iOS 13 the push token that is returned is badly formatted.

Note that the only thing I changed in the output of the console.log is the "*" which replaces the value of the real push token.

```
OneSignal.getPermissionSubscriptionState((data) => {
        const pushToken = data.pushToken;
        const userId = data.userId;
        console.log(pushToken); //"{length=32,bytes=0x6d0ede****************8e7e42...399**********60}"
});
```

**Environment**
Yarn with React Native 0.59.9 & react-native-onesignal 3.2.12 on iOS 13

**Steps to Reproduce Issue:**
1. Install react-native-onesignal on iOS 13 & React Native 0.59.9
2. Call getPermissionSubscriptionState to request a token

**Comment by rgomezp** [comment]
Hello @amitassaraf ,
Thank you for bringing this up. Because iOS 13 is still in Beta, this issue may be resolved before the release this fall. However, we will keep a close eye on this leading up to the release. Thanks again

**Comment by rgomezp** [comment]
Will close in this repo as this is a general iOS issue. Please follow the same issue on the iOS SDK repository: https://github.com/OneSignal/OneSignal-iOS-SDK/issues/504
