### ISSUE TITLE
[android] Numbers stripped from additionalData

### ISSUE THREAD

**Issue by EskelCz** [OneSignal/react-native-onesignal#772]
**Description:**

I'm sending p2p notification similar to this:
```
{"p2p_notification":{"senderId":"MkCRZlyCLSd9kf3oByM5mcOSxrh1","timestamp":1559940935689}}
```
what the android client receives is this:
```
"senderId":"MkCRZlyCLSd9kf3oByM5mcOSxrh1"
```
Strings are working fine, but the number attribute is omitted. I can see that the data is sent correctly from onesignal website 'message report', it's something on the receiving end on Android.
iOS is working properly.

**Environment**

Latest version, 3.2.14 from npm

**Steps to Reproduce Issue:**

1. From one client call this:
```
const data = { 'senderId': sender, timestamp: unixTime, action: action }
OneSignal.postNotification('test', { string: 'abc', number: 123 }, second_client_id)
```
2. in second client listen for the notification
3. check values in notification.payload.additionalData.p2p_notification
4. I see only the string value, not the numerical

**Comment by rgomezp** [comment]
Hello,
Thank you for reporting this. Sounds like a bug. Thank you for your patience while we reproduce and look further into this issue

**Comment by rgomezp** [comment]
Hello,
Taking a closer look at your code snippet, it looks like you aren't following the correct format. It should look something like:
```
OneSignal.postNotification({"en": "This is the message"}, {key1:"this", key2:"that"}, "81145769-e762-4ad1-89df-02aa4ef466a1"); 
```

Please see our [docs](https://documentation.onesignal.com/docs/react-native-sdk#section-post-notification-peer-to-peer-notifications-) for more info

**Comment by EskelCz** [comment]
@rgomezp That was just a simplification of the snippet, I have the correct format (just as you shown) in my application. It's definitely a bug.

**Comment by rgomezp** [comment]
@EskelCz ,
Try putting quotation marks around the number

**Comment by EskelCz** [comment]
@rgomezp Sure, I can make it a string and then parse int on the other side. That is what I use now as a workaround. The whole purpose of this issue was to avoid this operation.

**Comment by rgomezp** [comment]
Right, thanks for bringing up the bug. We will look into getting it fixed

**Comment by rgomezp** [comment]
Just curious, what device are you testing with and what's its CPU

**Comment by EskelCz** [comment]
One of the cheapest recent Androids, Xiaomi Redmi 6A. CPU is ARM Cortex-A53

**Comment by rgomezp** [comment]
After doing some testing, it looks like this happens with P2P notifications on Android devices. Numbers only get excluded if they are 64 bit numbers in `additionalData`

e.g: If the number is less than 2147483647 (largest possible 32 bit number) but greater than 9223372036854775807 (largest possible 64 bit number) then it will display correctly, with numbers > 64 bits shown in scientific notation

**Comment by EskelCz** [comment]
@rgomezp thanks for doing the testing. in my case it was indeed a 64bit number, to carry a unix timestamp from javascript's Date.valueOf(), which is precise to milliseconds.

I can probably reduce the precision to stay within 32 bits, but still, can this be changed, for the sake of consistency?

**Comment by rgomezp** [comment]
Yes. We have already made a note to change this for a future release. Thanks for finding this bug!
