### ISSUE TITLE
react-native-onesignal:packageDebugResources issue when running application

### ISSUE THREAD

**Issue by saikmadana** [OneSignal/react-native-onesignal#773]
I am using react-native in my application. I am trying to build and run my application. When I run I am getting the issue as

```
> Task :react-native-onesignal:packageDebugResources FAILED

FAILURE: Build failed with an exception
```

and

```
BUILD FAILED in 3m 8s
122 actionable tasks: 3 executed, 119 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
```

I have been trying so many solutions online. But, can't solve this. Please let me know what I am doing wrong and where it went wrong.

If you need any other info, please let me know.

Thanks...

**Comment by rgomezp** [comment]
Hello,
Could you please follow our issue template? 

Thanks

**Comment by rgomezp** [comment]
Closing due to no response
