### ISSUE TITLE
Doesn't subscribe the user with Honor brand (Android 8)

### ISSUE THREAD

**Issue by LcsLpr** [OneSignal/react-native-onesignal#779]
**Description:**

I am using this SDK for a year and half and I have just noticed an issue with Honor smartphones:

Listener on 'ids' isn't triggered and the smartphone is not subscribed on the OneSignal list...
It is working with every other kind of smartphones except this one ... (I used to test :  Honor 7A Pro, on Android 8.0.0).

With getPermissionSubscriptionState I have :

notificationsEnabled: true
subscriptionEnabled: false
userSubscriptionEnabled: true

I did all issues, none of them are similar with this one (even the one who are about subscriptionEnable: false)

**Environment**

I used the SDK 3.2.4 and now the 3.2.14.

**Comment by rgomezp** [comment]
Hello,
Are you only seeing this on Honor? Or have you been able to reproduce on other devices?

**Comment by LcsLpr** [comment]
> Hello,
> Are you only seeing this on Honor? Or have you been able to reproduce on other devices?

Hello, I used onesignal for a large audience in a react native application. We never noticed issues with compatibility with other devices.
I found this bug when implementing onesignal for a new project, and on the many devices tested all worked except this one. I tried on another Honor(Honor 7x) and it did work as well, very confusing.

**Comment by rgomezp** [comment]
Could you please use the [logging](https://documentation.onesignal.com/docs/react-native-sdk#section-debugging) method with verbose to generate a log that may give us some further insights?
