### ISSUE TITLE
Users not receiving notifications if they turn off their phone

### ISSUE THREAD

**Issue by scottmas** [OneSignal/react-native-onesignal#782]
**Description:**
When users turn off their phone, they stop receiving notifications from the app _until_ they open up the app again. In the words of one of our users:

"Notifications will work as long as I launch the app at least once during the day.  I am a user that turns off their phone at night and back on in the morning.  If I don’t launch the app in the morning when I wake up, I won’t get any app notifications throughout the day.  Once I launch the app, I will start getting the notifications.  If I reboot the phone at any point during the day, the same thing happens.  I am hopeful that this information will help you to solve the issue."

**Environment**
OneSignal SDK 3.2.12
It appears to happen only on Android devices although we are not positive
Happens on Android 9+

**Steps to Reproduce Issue:**
1. In react native app run ` OneSignal.sendTag("accountId", "some-user-id");`
2. Open the app and then close it to ensure the tag is registered with the device 
3. On the server run:
```javascript
axios.post("https://onesignal.com/api/v1/notifications", {  
  filters: [
    {
      field: "tag",
      key: "accountId",
      relation: "=",
      value: "some-user-id"
    },         
   ],
   //Message payload here...
}, { 
  //Auth headers here...
  headers:  {}
})
```
4. See that notifications come through on the phone
5. Restart your phone
6. Send the notification again on the server. See that notifications do NOT pop up on the device
7. Open the app again and close it
8. See that notifications come through

**Comment by rgomezp** [comment]
**EDIT:** had to edit my reply because it was wrong. Here is a [summary](https://documentation.onesignal.com/docs/how-notifications-work#section-notifications-when-app-is-closed) of notification behavior. The person should be getting the notifications if the app wasn't force-killed, or the couple other scenarios outlined in the documentation. However, it will take a couple minutes to go back in the shade after the phone reboots. It will also be non-interruptive meaning it won't vibrate, make noise, etc...

**Comment by scottmas** [comment]
Let me investigate a little more and get back to you Rodrigo. There's a chance it may just be certain devices.

**Comment by rgomezp** [comment]
Hi Scott,
Would like to close out this issue. Any updates?

**Comment by scottmas** [comment]
Haven't had time to investigate this behavior. Closing for now.
