### ISSUE TITLE
Feature request: flow typing

### ISSUE THREAD

**Issue by otusweb** [OneSignal/react-native-onesignal#783]
**Description:**
It would be great if the react native SDK could have typing included. i'm using flow for my project and I miss having flow help me when I use OneSignal.

**Environment**
    "react-native-onesignal": "3.2.14"

I found this issue back from last year: https://github.com/geektimecoil/react-native-onesignal/issues/453
but it seems to be closed with no fix

**Comment by rgomezp** [comment]
Thanks for your suggestion. We keep track of all feature requests internally so I will be closing this issue after making a note of your request. Just a general reminder that the SDK _is_ open source for anyone wanting to contribute with these types of feature implementations :)

**Comment by otusweb** [comment]
Thanks @rgomezp. As a note, I found out that flow-typed has a flow definition for one-signal (https://github.com/flow-typed/flow-typed/tree/master/definitions/npm/react-native-onesignal_v3.x.x/flow_v0.69.0-). Maybe just adding this in the instruction page would be enough for now.
