### ISSUE TITLE
onReceived not getting called and app crashed

### ISSUE THREAD

**Issue by harryharihar** [OneSignal/react-native-onesignal#786]
Description:
App getting crashed on background notification.

Environment

What version of the OneSignal React-Native SDK are you using?
react-native-onesignal": "^3.2.12

How did you add the SDK to your project (eg. npm)
npm install react-native-onesignal

Android Version:
Android 7.1.2

Steps to Reproduce Issue:
implement
OneSignal.addEventListener('received', (notification)=>{console.log(notification)}
Send messages from one signal when app is opened and app crashed .
On my app logcat, it still be able to print the log (notification), shortly after that, my app crashed. 

Firebase dependencies :
implementation 'com.google.firebase:firebase-core:16.0.9'
implementation 'com.google.firebase:firebase-config:17.0.0'

React Native Version
"react-native": "0.59.9"

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience while we investigate the issue

@harryharihar could you please include the logs from the crash? Make sure you have turned on OneSignal [logging](https://documentation.onesignal.com/docs/react-native-sdk#section--setloglevel-)

**Comment by rgomezp** [comment]
Closing due to no response
