### ISSUE TITLE
Sound disabled by default.

### ISSUE THREAD

**Issue by degodfather** [OneSignal/react-native-onesignal#793]
I created notification channel and group in OneSignal panel and when I try to send a notification the messages are received by no notification sound. When I checked the settings page the sound is disabled by default. How to enable sound? I gave high priority in One signal panel for the channel. 
![photo_2019-07-06_12-03-37](https://user-images.githubusercontent.com/4501062/60752674-25623b80-9fe6-11e9-8bd0-4b928b065b09.jpg)

**Comment by rgomezp** [comment]
Howdy, 
Could you please provide some more details regarding the specific environment as well as repro steps? For example, what device did you test this on?

**Comment by degodfather** [comment]
The device I tested was MIUI 10.3.5 on Poco F1.

**Comment by jkasten2** [comment]
@arunharidas Did you originally create the Notification Channel / Category without sound enable or with a priority lower than "High"? If so I recommend creating a new channel to test this or fully uninstall then reinstall your app on the deice. Android does not allow programmatically updating channel settings once they have been created on the device.

Also noticed in your MIUI screenshot is there not a priority option anywhere? This should be set to "High" or "Urgent" so the notification sound can be enabled.

**Comment by rgomezp** [comment]
I suspect this is an operating-system specific issue

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by eskiesirius** [comment]
im having this kind of problem too.. sound disabled by default.. mine is MIUI GLobal 11.0.3.. it doesn't have Urgent, the highest priority is High

**Comment by degodfather** [comment]
@eskiesirius The problem is with the MIUI. They disable sound notification by default for not so famous apps. Only few apps are getting notification sound by default like Whatsapp, Viber etc, even the slack doesn't have notification by default.
