### ISSUE TITLE
SendTags with callback? 

### ISSUE THREAD

**Issue by brasrox** [OneSignal/react-native-onesignal#796]
**Description:**

thankyou for this nice lib, im using android and **i need SendTags with callback (onSuccess,failure)**
searching the archives i see that it put in consideration. any updates?

**Environment**

Using RN 59.9 with onesignal 3.2.14 (npm) 
Android api lv 19

**Comment by rgomezp** [comment]
Thanks for your request. We will consider this for an upcoming release though we have not added a timeline to it.
