### ISSUE TITLE
onOpened,onReceived not fired with react-native-navigation v2

### ISSUE THREAD

**Issue by amirmahdinezhad** [OneSignal/react-native-onesignal#797]
**Environment**

1. react-native-onesignal version is : 3.2.13
2. react-native version is : 0.59.8
3. react-native-navigation version is : 2.21.1
2. installed it via yarn
3. Platform: Android
4. Device info : Sony Xperia ZR(C5502) and OS version is 5.1.1 and debug mode

**Steps to Reproduce Issue:**

  1. Install the OneSignal SDK using yarn into my project
  2. link the package
  3. Attempt to send a push notification
  4. receive the notification successfully when app is closed and when click the notification open the app but not fire the onOpened and onReceived method

App.js :
```
export default class App extends Component {
  constructor(props) {
    super(props);
    OneSignal.init('xxxxxxxxxxxxxxxx');
    OneSignal.addEventListener('received', this.onReceived);
    OneSignal.addEventListener('opened', this.onOpened);
    OneSignal.configure();
  }

  componentWillUnmount() {
    OneSignal.removeEventListener('received', this.onReceived);
    OneSignal.removeEventListener('opened', this.onOpened);
  }

  onReceived(notification) {
    console.log('Notification received: ', notification);
  }

  onOpened(openResult) {
    console.log('Message: ', openResult.notification.payload.body);
    console.log('Data: ', openResult.notification.payload.additionalData);
    console.log('isActive: ', openResult.notification.isAppInFocus);
    console.log('openResult: ', openResult);
  }

  render() {
    return <Router />;
  }
}

**Comment by rgomezp** [comment]
This is very strange. You are saying that by simply importing `react-native-navigation` our SDK doesn't fire the callbacks `onReceived` and `onOpened`?

**Comment by amirmahdinezhad** [comment]
@rgomezp 
It seems that it was a problem for react-native-navigation v1 with react-native-onesignal , which I noticed and reported , and it got resolved
https://github.com/geektimecoil/react-native-onesignal/issues/547

**Comment by rgomezp** [comment]
@Amir-M7 ,
Great. Can we close this issue then?

**Comment by amin3mej** [comment]
@rgomezp ,
I have the same problem. I guess @Amir-M7 wants to say you have the same problem with react-native-navigation v1 and you fixed the bug in that issue. 
Now you have the same problem with react-native-navigation v2. Can you check this please?

Thanks.

**Comment by amirmahdinezhad** [comment]
Thank you Amin.

But these problems are not the same. You've labled this issue with "Not OneSignal" as the problem with ract-native-navigation v1 is already solved.
In this case, I have the problem with react-native-navigation v2 which doesn't call "onOpened" and "onReceived" function.

**Comment by rgomezp** [comment]
Ah I see. Judging by the previous issue, it seems OneSignal is not even initializing. Can you please confirm this by turning on [logging](https://documentation.onesignal.com/docs/react-native-sdk#section--setloglevel-) and pasting the logs here? To summarize the previous issue:
>In some cases, especially with projects using the react-native-navigation dependency, the initial Activity would be null, preventing the SDK from initializing.

This may be happening again with version 2 of navigation

**Comment by rgomezp** [comment]
Closing due to no response. Try updating to the latest plugin version
