### ISSUE TITLE
onReceived is triggered only once on iOS after establishing internet connection

### ISSUE THREAD

**Issue by jahicDario** [OneSignal/react-native-onesignal#798]
**Description:**
When the internet connection is off on device, and we send several push notifications on that device, after establishing internet connection again, onReceived is triggered only once for the last notification.

**Environment**
  React Native Environment Info:
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
      react-native-onesignal: "^3.2.12",
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Steps to Reproduce Issue:**
1. On ios, turn off internet connection
2. Send 3 notification
3. turn on internet connection
4. onReceived is triggered only once, for the last one
5. Expected behavior: onReceived is triggered 3 times for each notification

**Anything else:**
This is working fine on Android devices.

**Comment by rgomezp** [comment]
This is a limitation of iOS and there is nothing that can be done here. Only the last notification will be shown in this scenario. Thanks for the question!
