### ISSUE TITLE
React link does nothing

### ISSUE THREAD

**Issue by vmurillo** [OneSignal/react-native-onesignal#799]
**Description:**

`react-native link react-native-onesignal` does not modify ios project files

**Environment**

1. What version of the OneSignal React-Native SDK are you using? `^3.2.14`
2. How did you add the SDK to your project (eg. npm) `yarn add react-native-onesignal`

**Steps to Reproduce Issue:**

1. react-native link react-native-onesignal
2. No files in ios directory are added

**Anything else:**

Since I am not using cocoapods, I need to install this manually; in the meantime could you provide me with instruction on how to manually install this library since linking does not work?

**Comment by chasemac** [comment]
@vmurillo are you using RN 60?

**Comment by vmurillo** [comment]
@chasemac the version I am using is "react-native": "0.59.3",

**Comment by rgomezp** [comment]
Howdy,
We provide manual linking steps in the linking section of our React Native setup guide.
https://documentation.onesignal.com/docs/react-native-sdk-setup#section-link-library-to-project

>add RCTOneSignal project into Libraries manually (screenshot):
Open node_modules/react-native-onesignal/ios
Then, drag and drop RCTOneSignal.xcodeproj into XCode project folder Libraries

**Comment by vmurillo** [comment]
I spent all day on this, to make it work I had to:
1. Add 
```
$(SRCROOT)/../node_modules/react-native-onesignal/ios  recursive
$(SRCROOT)/../node_modules/react-native-onesignal/ios/RCTOneSignal  recursive
```
to Header Search Paths
2. Add `libRCTOneSignal.a` to Link Binary With Libraries.

Are there no plans to fix this to make the integration seamless @rgomezp ?

**Comment by rgomezp** [comment]
Those instructions are included in our setup guide. Perhaps you missed them?

**Comment by vmurillo** [comment]
@rgomezp those instructions are for the `OneSignalNotificationServiceExtension` in docs. It is not mentioned this should be done for the main target.

**Comment by bstankowski** [comment]
> I spent all day on this, to make it work I had to:
> 
> 1. Add
> 
> ```
> $(SRCROOT)/../node_modules/react-native-onesignal/ios  recursive
> $(SRCROOT)/../node_modules/react-native-onesignal/ios/RCTOneSignal  recursive
> ```
> 
> to Header Search Paths
> 2. Add `libRCTOneSignal.a` to Link Binary With Libraries.

Thanks very much for this comment, couldn't make it work for two days. In addition to these, I had to add `WebKit.framework` to my main target. (An old app using on react-native 0.55.4.)

**Comment by rgomezp** [comment]
@vmurillo ,
This is done automatically by the linking step in RN

@bstankowski ,
Did you try `pod deintegrate && pod install` in the ios folder?
