### ISSUE TITLE
Notice for users

### ISSUE THREAD

**Issue by avishayil** [OneSignal/react-native-onesignal#80]
We're currently working on a big update to the latest SDK versions of OneSignal on iOS and Android.
In the meanwhile, Make sure that you're working on the 2.6.2 SDK version on Android, and 1.13.3 Pod version on iOS.

**Comment by tarunmarkose** [comment]
@avishayil Do you have an ETA for the new iOS SDK?

**Comment by avishayil** [comment]
No ETAs here, me and the OneSignal team are still trying to figure it out, just more patience :> I have a lot of work these days and couldn't find the time to keep working on this.

**Comment by avishayil** [comment]
Getting closer :>

**Comment by avishayil** [comment]
Closed in favor of #103
