### ISSUE TITLE
onIds, onOpened, onReceived can't called on AndroidX

### ISSUE THREAD

**Issue by msaifa** [OneSignal/react-native-onesignal#807]
**Description:**
Hi...
I am after install latest react natiave and latest onesignal too,
i am follow all instalation intruction. but after use onIds,onReceived,onOpened has not called. 
i have add OneSignal.configure() too. Please how to fix this

**Environment**
"react-native-onesignal": "^3.2.14",
"react-native": "0.60.4",
"react": "16.8.6",

**Steps to Reproduce Issue:**

1. Install react native
2. install onesignal and linking
3. implement onesignal
4. can't called

**Anything else:**

nothing response

thanks very much

**Comment by sara9i** [comment]
@rgomezp 
I am facing the same issue.
RN 0.60
OneSignal 3.3.0
AndriodX

the listeners for newly registered app are not getting fired. The fixes in onesignal new release (3.3.0) fixed the existing apps which were already using and were registered with onesignal.

**Comment by msaifa** [comment]
> @rgomezp
> I am facing the same issue.
> RN 0.60
> OneSignal 3.3.0
> AndriodX
> 
> the listeners for newly registered app are not getting fired. The fixes in onesignal new release (3.3.0) fixed the existing apps which were already using and were registered with onesignal.

thank for your answer, after upgrading react-native-onesignal, i found this problem 
`Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find androidx.cardview:cardview:28.0.0.
     Required by:
         project :app
   > Could not find androidx.cardview:cardview:28.0.0.
     Required by:
         project :app > project :react-native-onesignal
   > Could not find androidx.cardview:cardview:28.0.0.
     Required by:
         project :app > project :react-native-onesignal > com.onesignal:OneSignal:3.11.1`

are you found problem like that ?

**Comment by msaifa** [comment]
> > @rgomezp
> > I am facing the same issue.
> > RN 0.60
> > OneSignal 3.3.0
> > AndriodX
> > the listeners for newly registered app are not getting fired. The fixes in onesignal new release (3.3.0) fixed the existing apps which were already using and were registered with onesignal.
> 
> thank for your answer, after upgrading react-native-onesignal, i found this problem
> `Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
> 
> > Could not find androidx.cardview:cardview:28.0.0.
> > Required by:
> > project :app
> > Could not find androidx.cardview:cardview:28.0.0.
> > Required by:
> > project :app > project :react-native-onesignal
> > Could not find androidx.cardview:cardview:28.0.0.
> > Required by:
> > project :app > project :react-native-onesignal > com.onesignal:OneSignal:3.11.1`
> 
> are you found problem like that ?

i have fixed this. just add into file app/build.gradle, 
but there warning for remove manual linking.
https://github.com/geektimecoil/react-native-onesignal/issues/805#issuecomment-514217308

**Comment by sara9i** [comment]
> > > @rgomezp
> > > I am facing the same issue.
> > > RN 0.60
> > > OneSignal 3.3.0
> > > AndriodX
> > > the listeners for newly registered app are not getting fired. The fixes in onesignal new release (3.3.0) fixed the existing apps which were already using and were registered with onesignal.
> > 
> > 
> > thank for your answer, after upgrading react-native-onesignal, i found this problem
> > `Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
> > > Could not find androidx.cardview:cardview:28.0.0.
> > > Required by:
> > > project :app
> > > Could not find androidx.cardview:cardview:28.0.0.
> > > Required by:
> > > project :app > project :react-native-onesignal
> > > Could not find androidx.cardview:cardview:28.0.0.
> > > Required by:
> > > project :app > project :react-native-onesignal > com.onesignal:OneSignal:3.11.1`
> > 
> > 
> > are you found problem like that ?
> 
> i have fixed this. just add into file app/build.gradle,
> but there warning for remove manual linking.
> [#805 (comment)](https://github.com/geektimecoil/react-native-onesignal/issues/805#issuecomment-514217308)

in your android/app/build gradle go to dependencies and replace this line

**implementation(project(':react-native-onesignal'))**

with this

**implementation(project(':react-native-onesignal')){
      exclude group: 'com.google.android.gms'
      exclude group: 'com.android.support', module: 'cardview-v7'
    }**
