### ISSUE TITLE
post notification to external user id

### ISSUE THREAD

**Issue by AdrianZajkowski** [OneSignal/react-native-onesignal#808]
**Description:**

Hello, I want to post notification to specific user by external user id. 
Sending to user by one signal id is working correctly, but not with external user id.

    let contents = {
      en: "Confirm the game result"
    };
    let data = {};
    let playerId = { include_external_user_ids: ["4"] }; 

    OneSignal.postNotification(contents, data, playerId, {
      template_id: "b549c66e-261b-4245-aecf-69052e9cdb88"
    });
  };

Any help would be much appreciated. I read almost all threads and I couldn't find answer. Thanks for helping.

**Comment by rgomezp** [comment]
Howdy,
This should be 
```
let playerId = null;
OneSignal.postNotification(contents, data, playerId, {include_external_user_ids:[<external_id>, <external_id>, <external_id>], template_id: "b549c66e-261b-4245-aecf-69052e9cdb88"});
```

**Comment by camin-mccluskey** [comment]
@rgomezp I'm having the same problem with the latest (3.6.0) release. Here is the code in question
```
OneSignal.postNotification(contents, {}, null, {include_external_user_ids: ExternalIdArray, headings: {"en": user.name}});
```
This appeared to be working prior to a react-native update from 0.59 to 0.6x. Any advice would be great

**Comment by camin-mccluskey** [comment]
> @rgomezp I'm having the same problem with the latest (3.6.0) release. Here is the code in question
> 
> ```
> OneSignal.postNotification(contents, {}, null, {include_external_user_ids: ExternalIdArray, headings: {"en": user.name}});
> ```
> 
> This appeared to be working prior to a react-native update from 0.59 to 0.6x. Any advice would be great

actually 3.6.0 is not building so I had to downgrade. Push notifications to external ids still dont work though

**Comment by rgomezp** [comment]
@camin-mccluskey , 
Seems like an issue all on its own. Can you please open an issue and include details regarding your build issue?

**Comment by camin-mccluskey** [comment]
@rgomezp 

Turns out the build issue was unrelated - my bad. I still am having the same problem with external id push notifications though. It was working prior to react-native 0.61.5 upgrade. Any known issues there or should I open a new one? Thanks!

**Comment by rgomezp** [comment]
@camin-mccluskey ,
Would you be able to use our SetLogLevel method to Verbose and send us the full logcat from the device? 

More on this method in the SDK docs: https://documentation.onesignal.com/docs/sdk-reference#section--setloglevel-

If you could send these logs that would be much appreciated and help us better see what is happening in the app.

**Comment by camin-mccluskey** [comment]
@rgomezp Ah good tip! Here's the output 
```
VERBOSE: HTTP Request (OSRequestPostNotification) with URL: https://onesignal.com/api/v1/notifications, with parameters: {
  "include_external_user_ids" : [
    "<redacted>",
    "<redacted>"
  ],
  "data" : {
    "p2p_notification" : {

    }
  },
  "headings" : {
    "en" : "Camin"
  },
  "contents" : {
    "en" : "OneSignal Test Message"
  },
  "app_id" : "<redacted>"
}
2019-12-09 21:33:35.932228+0000 inHouse[41148:629308] VERBOSE: network response (OSRequestPostNotification): {
    errors =     (
        "Please include a case-sensitive header of Authorization: Basic <YOUR-REST-API-KEY-HERE> with a valid REST API key."
    );
    reference =     (
        "https://documentation.onesignal.com/docs/accounts-and-keys#section-keys-ids"
    );
}
2019-12-09 21:33:35.932522+0000 inHouse[41148:624947] ERROR: Create notification failed
2019-12-09 21:33:35.932795+0000 inHouse[41148:624947] INFO: Error Domain=OneSignalError Code=400 "(null)" UserInfo={returned={
    errors =     (
        "Please include a case-sensitive header of Authorization: Basic <YOUR-REST-API-KEY-HERE> with a valid REST API key."
    );
    reference =     (
        "https://documentation.onesignal.com/docs/accounts-and-keys#section-keys-ids"
    );
}}
```

I think it's pretty clear what's missing from the debug output. Although it was working before without an API key I believe. Where should I set this, with each request or on SDK initialisation? Also I thought that this type of notification did not require an api key. Thanks again for your help.

**Comment by rgomezp** [comment]
Howdy,
This is now required by all apps. Sorry for the inconvenience. You have a couple options here:

1) Target by `playerId` instead of external id
2) Make a call to your backend to then make a call to the same [endpoint](v) while including the key in the header

**Comment by ghost** [comment]
Any **Updates?**
