### ISSUE TITLE
Android: tapping notification re-opens app

### ISSUE THREAD

**Issue by yogiben** [OneSignal/react-native-onesignal#81]
When I tap on a notification, the app is re-opened.

This means the user sees splash screen even if app is open and still active.

I'd like the notification to switch to the active app opposed to re-open it. Is this possible?

**Comment by jkasten2** [comment]
@yogiben Make you have added `android:launchMode="singleTop"` to the activity in your `AndroidManifest.xml`. This noted towards the top of the readme guide.

**Comment by yogiben** [comment]
I had to add it to every `<activity>` tag.
