### ISSUE TITLE
Clarifications needed

### ISSUE THREAD

**Issue by Jalson1982** [OneSignal/react-native-onesignal#814]
Hello crew,

At first, thx for awesome notification have few questions struggling to make it:

1. The action button is it possible to customize the color of the text?
2. Action button should have a snooze ( press on this action button should not open the app )

I can not find ( I am sorry if I missed it ) in documentation to solve those not issues rather my needs.

Thx in advance for any help.

**Comment by rgomezp** [comment]
Howdy,
The color should be customizable for Android, but not iOS.
Android 8 or higher should have a snooze option if you swipe left.

Thanks for your questions
