### ISSUE TITLE
Android9.0, there is no message reminder after the screen is locked, the message pops up after unlocking

### ISSUE THREAD

**Issue by 1129530686** [OneSignal/react-native-onesignal#815]
Android9.0 and Android8.0，there is no message reminder after the screen is locked. After the unlocking, the message pops up, and the lock screen is accepted on the mobile phone to accept the notification. What is the reason? Very anxious, thanks。

**Comment by rgomezp** [comment]
Howdy,
Could you please follow our issue template so we can better assist you?

**Comment by rochapablo** [comment]
Notification only works when the app it's open (showing an alert, not a push notification). Minimized or closed (ended process) not working at all.

Testing on Android phone (not emulator).

```
"react": "16.8.6",
"react-native": "0.60.4",
"react-native-onesignal": "^3.3.0",
```

**Comment by rochapablo** [comment]
I forgot that for Zenfone it require extra steps to allow the notifications, now it's working partially. It still not working with the phone locked.

**Comment by jkasten2** [comment]
@rochapablo Can you check the setting noted below for the Asus Zenfone?
https://www.verizonwireless.com/support/knowledge-base-214566/

**Comment by 1129530686** [comment]
This problem has been solved, I set the permission to open the lock screen notification in the Android project:
1, <uses-permission android:name="android.permission.WAKE_LOCK"/>
2, final Window win = getWindow();
         win.addFlags(WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED / / display in lock screen state
                 | WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD //Unlock
                 | WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON); //Open the screen

**Comment by jkasten2** [comment]
@1129530686 Can you provide more detail on how this fixed your issue? Adding settings to the `window` doesn't fit into how this would affect a notification.

**Comment by rochapablo** [comment]
> @rochapablo Can you check the setting noted below for the Asus Zenfone?
> https://www.verizonwireless.com/support/knowledge-base-214566/

Already working with `Show all notification`
