### ISSUE TITLE
OneSignal.setSubscription(true) fails on android

### ISSUE THREAD

**Issue by yogiben** [OneSignal/react-native-onesignal#82]
I can successfully call

`OneSignal.setSubscription(false)`, but when I try to re-enable notifications, `OneSignal.setSubscription(true)` doesn't appear to work.

The web dashboard still shows 'No (User Opted Out)'

**Comment by yogiben** [comment]
This seems to be an issue with the development server.

Could there be a cache to prevent multiple attempts to register a device?

**Comment by bucketclan** [comment]
Have you tried reloading the page several times, it shouldn't take more than a minute to refresh on the dashboard.

**Comment by yogiben** [comment]
@TheGermanGuy Yes, I tried this.

Sometimes there seems to be a delay, but other times not.

Closing as am no longer actively working on this.
