### ISSUE TITLE
I am using react native 0.59.3 on ios and it is all auto linked and everything was working on an earlier version.

### ISSUE THREAD

**Issue by mannat26** [OneSignal/react-native-onesignal#821]
<img width="425" alt="Screenshot 2019-07-24 at 1 06 29 PM" src="https://user-images.githubusercontent.com/45625837/61875347-10533b00-af08-11e9-822b-3b7c3a9e2ba8.png">

**Description:**

 was using the git version of this repo yesterday and it was working normally, and now when I launch my app I get an error saying inAppMessageClicked is wrong.

(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by vforvasile** [comment]
Try release 3.3.1, the following issue was fixed recently.
[Changelog](https://github.com/geektimecoil/react-native-onesignal/releases)

**Comment by jkasten2** [comment]
@vforvasile Thanks for chiming in!
@mannat26 Closing this issue as resolved as this is now fixed.
