### ISSUE TITLE
Change url for api requests

### ISSUE THREAD

**Issue by dddrey** [OneSignal/react-native-onesignal#823]
**Description:**
Few days ago I've noticed that our users can't receive one signal user id and push notifications
in our app. I went to one signal's website and it didn't open without vpn. As it turned out, Roskomandzor banned [one signal IPs](https://reestr.rublacklist.net/record/1639616/) in Russia on 19th of July. The quickiest solution I found is to setup nginx server to proxy requests to one signal api, but after this I need to change urls in this library as well. Tried searching & exploring 
repository code but didn't find any hints. 
Any ideas how can I change url for api requests in this lib?

**Environment**
1. react-native-onesignal 3.2.14
2. yarn
3. Russian IP address

**Comment by mmxdr** [comment]
Same problem, did you find a solution?

**Comment by rgomezp** [comment]
Hi. We're aware of the issue and are working to resolve this. Thanks for your patience

**Comment by rgomezp** [comment]
This issue has been resolved. Cheers

**Comment by dmitriiivashko** [comment]
@rgomezp the app is still blocked in Russia. it would be really nice if the a URL of the api gateway could mod was officially supported

**Comment by rgomezp** [comment]
This issue has been re-resolved. Thanks for your patience
