### ISSUE TITLE
Setup documentation for react-native-link with RN 60

### ISSUE THREAD

**Issue by christhegrand** [OneSignal/react-native-onesignal#828]
**Description:**
The RNOnesignal documentation [here](https://documentation.onesignal.com/docs/react-native-sdk-setup) lists running `react-native link react-native-onesignal` as a step. Is this necessary now with React Native 60's autolinking behavior? If it is not, I think the documentation should be updated to make it clear which versions of RN and RNOnesignal require this command to be run.

**Environment**

react-native-onesignal 3.3.1
yarn

**Steps to Reproduce Issue:**

Visit https://documentation.onesignal.com/docs/react-native-sdk-setup.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Hi @christhegrand ,
It's a good question. After testing the new autolinking behavior, we found that it wasn't linking correctly. In our experience, you still need to call it. You can check if the linking step worked by doing the following:

Inside of MainApplication.java, make sure that you are now returning the RNOneSignal package like this. Other dependencies, such as react-native-navigation, will often override the default ReactApplication class, so it is important to make sure you are returning the OneSignal package if you've made changes to this class.

![Img](https://files.readme.io/d642f4a-ab162a1-Screen_Shot_2019-05-08_at_5.36.15_PM.png)

If you don't see these changes, the linking step did not work for some reason (same as what we're seeing) and you should run the command above. I'm curious to see if it is working automatically for you or not. Looking forward to your response!

**Comment by rgomezp** [comment]
Closing due to no response
