### ISSUE TITLE
include_external_user_ids

### ISSUE THREAD

**Issue by VesperDev** [OneSignal/react-native-onesignal#830]
**Description:**

i have a problem when send one notification push.

this example not working

`OneSignal.postNotification(contents, data, null, {include_external_user_ids:[<external_id>, <external_id>, <external_id>]});`

but when I do this example if it works
`OneSignal.postNotification(contents, data, playerId, otherParameters);`

the only way to send a notification to external users was from the api rest

`curl --include \
     --request POST \
     --header "Content-Type: application/json; charset=utf-8" \
     --data-binary "{\"app_id\": \"5eb5a37e-b458-11e3-ac11-000c2940e62c\",
\"contents\": {\"en\": \"English Message\"},
\"include_player_ids\": [\"6392d91a-b206-4b7b-a620-cd68e32c3a76\",\"76ece62b-bcfe-468c-8a78-839aeaa8c5fa\",\"8e0f21fa-9a5a-4ae7-a9a6-ca1f24294b86\"]}" \
     https://onesignal.com/api/v1/notifications
`

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Howdy,
What is the response you are getting?

Related: #808

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by camin-mccluskey** [comment]
@rgomezp I'm having the same problem with the latest (3.6.0) release. Here is the code in question
```
OneSignal.postNotification(contents, {}, null, {include_external_user_ids: ExternalIdArray, headings: {"en": user.name}});
```

This appeared to be working prior to a react-native update from 0.59 to 0.6x. Any advice would be great
