### ISSUE TITLE
User is unsubscribed after notification is sent 

### ISSUE THREAD

**Issue by meetyourdev** [OneSignal/react-native-onesignal#835]
**Description:**

Whenever a notification is sent to a specific player id, the user with that player id is unsubscribed. The status before sending the notification was subscribed in OneSignal dashboard. No notification is received either on the device. All corresponding notifications sent from REST API returns response as errors 

{ id: '',
  recipients: 0,
  errors:
   { invalid_player_ids: [ 'example_player_id' ] } }

**Environment**

OneSignal SDK - "react-native-onesignal": "^3.3.2"
React Native Version - "react-native": "^0.60.4",

**Anything else:**

Kindly suggest some approach in debugging this issue

**Comment by rajneet-kaur-48** [comment]
same issue here :(

**Comment by meetyourdev** [comment]
> same issue here 
@aneet48  did you find any solution ?

**Comment by rajneet-kaur-48** [comment]
> > same issue here
> > @aneet48  did you find any solution ?

nope, did you ? or any alternative

**Comment by rgomezp** [comment]
Howdy @meetyourdev @aneet48 ,
Please include the HTTP request you're making, if possible in cURL form.

**Comment by meetyourdev** [comment]
> > > same issue here
> > > @aneet48  did you find any solution ?
> 
> nope, did you ? or any alternative

I was using react-native-push-notification library in my project for scheduling notification ... which was using GCM and not FCM. Due to which my project had both GCM and FCM. Removing that library and clearing conflict in GCM - FCM solved this issue for me.
