### ISSUE TITLE
Error If Combine https://github.com/sbugert/react-native-admob

### ISSUE THREAD

**Issue by ajiehatajie** [OneSignal/react-native-onesignal#836]
WARNING: The onesignal-gradle-plugin MUST be before com.android.application!
   Please put onesignal-gradle-plugin first OR update to com.android.tools.build:gradle:3.0.0 or newer!
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
49 actionable tasks: 10 executed, 39 up-to-date
D8: Cannot fit requested classes in a single dex file (# methods: 66409 > 65536)

if I test without react native admob it is normal and if I combine it with react native admob it is error

**Comment by rgomezp** [comment]
This isn't really causing any issues that we're aware of. It's simply a warning at this point which you can just ignore. Unless this causes, say, a build failure, we will go ahead and close this issue.
