### ISSUE TITLE
Player id is not assigned after init

### ISSUE THREAD

**Issue by defigods** [OneSignal/react-native-onesignal#837]
**Description:**

The userId is null so ids event is not triggered.
On android: syncUserState function is never called to save assigned user id from OneSignal.

**Environment**
react-native: 0.55.4
react-native-onesignal: 3.3.2

**Anything else:**

It worked pretty well about a month ago, and after that, I tried to run the application again.
And it doesn't work well now.

I debugged the SDK code, and makeAndroidparams not working properly.
OneSignalRestClient.java at line 177
httpResponse = con.getResponseCode();
throws java.net.SocketTimeoutException: failed to connec to onesignal.com/104.16.35.63 (port 443) from /192.168.1.10 (port 35358) after 60000ms

Trying to call the same URL with Postman is working.

Who can fix this issue?

**Comment by rgomezp** [comment]
Howdy, 
Can you try visiting onesignal.com from the device?
Make sure you don't have any software such as adblock blocking the onesignal domain.

We haven't heard any other reports of this. Also please try to reproduce it on a different device or on the Android emulator.

**Comment by defigods** [comment]
This happened when Wifi speed is too low.
It's working on Android emulator.
Closing issue here.
