### ISSUE TITLE
Android change one signal library with cusomized library not working

### ISSUE THREAD

**Issue by H-Shafiei** [OneSignal/react-native-onesignal#839]
**Description:**

I am trying to tweak the original OneSignal SDK and use the react-native-onesignal module over it. I have tried the following:
1. I built an .aar library and added it to the react-native-onesignal/android folder. I then modified the build.gradle and changed `api 'com.onesignal:OneSignal:3.11.2'` to `api files('onesignal.aar')`
2. Same as No. 1 except I added `api files('onesignal.aar') { transitive = true }`
3. I added the onesignal module (inside OneSignal-Android-SDK github repo) to the android folder and modify the `api 'com.onesignal:OneSignal:3.11.2'` in build.gradle to `api(project(':onesignal'))`

**Result:** For approach No. 1, the build is successful but it does not work as it should and It logs it misses some (firebase) dependencies which I found out .aar files do not ship with their dependencies. This is why I went to implement approach No. 2.
For the second and third approach, there is a error in build when I run `react-native run-android` for the app:

```
/blahblahblah/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:17: erro
r: package com.onesignal does not exist
import com.onesignal.ReactNativeOneSignalPackage;
                    ^
/blahblahblah/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:69: erro
r: cannot find symbol
      new ReactNativeOneSignalPackage(),
          ^
  symbol:   class ReactNativeOneSignalPackage
  location: class PackageList
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by rgomezp** [comment]
Howdy,
I'm not sure what you're trying to accomplish here. Could you please provide further details? The react-native-onesignal module _is_ the SDK.

**Comment by H-Shafiei** [comment]
The react-native-onesignal uses the native OneSignal SDK for android. I have made some minor changes in the SDK and I want to build react-native-onesignal using my fork of OneSignal SDK for android.

In the build.gradle (inside react-native-onesignal android folder) we can see a `api 'com.onesignal:OneSignal:3.11.2'` as dependency. I am trying to use my own fork of the SDK instead of the official OneSignal SDK.

Is it clear enough?

**Comment by rgomezp** [comment]
Try putting your custom OneSignal SDK build as a project in your Android project and then reference it from your app `build.gradle` file as so: `implementation(project(':onesignal')) {}`

Android view:
![Screen Shot 2019-09-12 at 3 14 24 PM](https://user-images.githubusercontent.com/11739227/64824878-37290780-d570-11e9-8a92-41dc0d65b6dd.png)

Project view:
![Screen Shot 2019-09-12 at 3 14 46 PM](https://user-images.githubusercontent.com/11739227/64824892-44de8d00-d570-11e9-8606-666531a9d842.png)

**Comment by H-Shafiei** [comment]
Thanks for answering. I was busy with some stuff so it took a while to answer you and I'm sorry for the delay

I have imported the project as a module to the project and added it as an `api` dependecy to my app module; However, when I try to build the project it gives me an error as I have mentioned. 
Am I adding the project the right way or should I change the procedure?

**Comment by rgomezp** [comment]
Please see my previous response

**Comment by H-Shafiei** [comment]
I saw your previous response. I said that I have tried what you said and it is giving me this error:
```
/blahblahblah/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:17: erro
r: package com.onesignal does not exist
import com.onesignal.ReactNativeOneSignalPackage;
                    ^
/blahblahblah/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:69: erro
r: cannot find symbol
      new ReactNativeOneSignalPackage(),
          ^
  symbol:   class ReactNativeOneSignalPackage
  location: class PackageList
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

It is either for some weird reason or maybe I don't know the correct way to add the library to android studio. Can you please explain with more details?

**Comment by rgomezp** [comment]
Hmm. Can you please include your app `build.gradle` code?

**Comment by H-Shafiei** [comment]
Sure. Here is my `build.gradle` file:

```
apply plugin: 'com.android.library'

def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android {
    compileSdkVersion safeExtGet('compileSdkVersion', 26)
    buildToolsVersion safeExtGet('buildToolsVersion', '26.0.2')

    defaultConfig {
        minSdkVersion safeExtGet('minSdkVersion', 16)
    }
    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "com.facebook.react:react-native:${safeExtGet('reactNativeVersion', '+')}"

    // api is used instead of implementation so the parent :app project can access any of the OneSignal Java
    //   classes if needed. Such as com.onesignal.NotificationExtenderService
//     api 'com.onesignal:OneSignal:3.11.2'
    api project(path: ':onesignal')
    
    testImplementation 'junit:junit:4.12'
}

// Adds required manifestPlaceholders keys to allow mainifest merge gradle step to complete
// The OneSignal app id should be set in your JS code.
// Google project number / FCM Sender ID will be pulled in from the OneSignal dashbaord
class DefaultManifestPlaceHolders {
    static final MANIFEST_PLACEHOLDERS_DEFAULTS = [
        onesignal_app_id: '',
        onesignal_google_project_number: 'REMOTE'
    ]

    static void addManifestToAppProject(Project proj) {
        def androidApp = proj.android
        MANIFEST_PLACEHOLDERS_DEFAULTS.each { defKey, defValue ->
            if (!androidApp.defaultConfig.manifestPlaceholders.containsKey(defKey)) {
                androidApp.defaultConfig.manifestPlaceholders[defKey] = defValue

                androidApp.buildTypes.each { buildType ->
                    if (!buildType.manifestPlaceholders.containsKey(defKey))
                        buildType.manifestPlaceholders[defKey] = defValue
                }
            }
        }
    }
}

rootProject.childProjects.each { projName, proj ->

    if (projName != 'app' && projName != 'react-native-onesignal')
        return

    if (proj.hasProperty('android')) {
        DefaultManifestPlaceHolders.addManifestToAppProject(proj)
        return
    }

    proj.afterEvaluate {
        DefaultManifestPlaceHolders.addManifestToAppProject(proj)
    }
}


// Add the following to the top (Line 1) of your app/build.gradle if you run into any issues with duplicate classes.
// Such as the following error
//   Error: more than one library with package name 'com.google.android.gms.license'

/*
plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.8.1'
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
*/
```
And this is my `settings.gradle` file:

`include ':onesignal'`

This is my project structure:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/7532938/65596902-c2f55780-dfa4-11e9-8688-cd6fc5c8c2d7.png">

<img width="337" alt="image" src="https://user-images.githubusercontent.com/7532938/65596925-ce488300-dfa4-11e9-8455-f70b4d30d140.png">

<img width="965" alt="image" src="https://user-images.githubusercontent.com/7532938/65596958-e28c8000-dfa4-11e9-96d9-e281fa357058.png">

![Uploading image.png…]()

**Comment by rgomezp** [comment]
I want to make sure you're editing `app/build.gradle`. Also, try `implementation(project(':onesignal')) {}` instead of what you have

**Comment by H-Shafiei** [comment]
I think there is a misunderstanding.
I am trying to use a my own fork of `onesignal` library with `react-native-onesignal`. Therefore this is exactly what I have done:
1. forked [https://github.com/geektimecoil/react-native-onesignal](react-native-onesignal)
2. forked [https://github.com/OneSignal/OneSignal-Android-SDK](OneSignal-Android-SDK)
3. imported `onesignal` folder from `OneSignal-Android-SDK` to `react-native-onesignal`
4. changed `api 'com.onesignal:OneSignal:3.11.2'` to `api project(path: ':onesignal')` inside `react-native-onesignal`'s `build.gradle` file (there is only one `build.gradle` file in this project and there does not exist any `app/build.gradle`). I have also tried `implementation(project(':onesignal')) {}` as you said but it did not work.

After all the above, it gives me a build error as I have mentioned in the first comment here.

P.S. 1: I have also tried to build the library `OneSignal-Android-SDK` and use the `.aar` file and it builds successfully but when I try to run the app it gives me an error for Firebase not available (this error is not an android error. It is related to onesignal and it shows in onesignal logs) and after a little searching I found out I have to write this in my `build.gradle`: `api files('onesignal.aar') { transitive = true }`. After I write this in my `build.gradle` I get errors as same as the above method.

P.S. 2: The reason I want to do this is I want to make some changes to the onesignal android library. For this step I am using the library without any changes at all so the errors shouldn't refer the library itself and it should be related to linking these two repos together.

**Comment by mikechoch** [comment]
There are a few ways to go about doing this. I think the easiest route would be to create the `OneSignal-Android-SDK` `onesignal.aar` file and import it into the forked `react-native-onesignal` libs folder. 

This can be done with Android Studio using:
`right-click on app folder > New > Module > Import .JAR/.AAR Package`

You might also need to add:
`implementation(project(':onesignal'))` in replacement of the `api 'com.onesignal:OneSignal:X.X.X'` in the `react-native-onesignal` `build.gradle` file.

Then you would need to add the forked `react-native-onesignal` into your react native app. This can be done by changing the path within your `package.json` from 
`react-native-onesignal": "X.X.X"` to `react-native-onesignal": "<path_to_project>"`

**Comment by H-Shafiei** [comment]
Thanks for answering @mikechoch 
I have tried similar to what you said and I have explained it [https://github.com/geektimecoil/react-native-onesignal/issues/839#issue-488606916](here). I even tried exactly as you said and the results are the same. I get an error:

```
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1615 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

> Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Configure project :react-native-firebase
react-native-firebase: using React Native prebuilt binary from /Users/Shared/Work/Projects/Tatami/Project/Hamed/ogp-app/node_modules/react-native/android

> Configure project :react-native-orientation
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :react-native-webview
:react-native-webview:reactNativeAndroidRoot /Users/Shared/Work/Projects/Tatami/Project/Hamed/ogp-app/node_modules/react-native/android

> Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Task :app:processDebugGoogleServices
Parsing json file: /Users/Shared/Work/Projects/Tatami/Project/Hamed/ogp-app/android/app/google-services.json

> Task :react-native-firebase:compileDebugJavaWithJavac

> Task :react-native-gesture-handler:compileDebugJavaWithJavac

> Task :react-native-sound:compileDebugJavaWithJavac

> Task :react-native-webview:compileDebugJavaWithJavac

> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
106 actionable tasks: 96 executed, 10 up-to-date
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /blah/blah/blah/app/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandle
r/react/RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /blah/blah/blah/app/node_modules/react-native-sound/android/src/main/java/com/zmxv/RNSound/RNSoundModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /blah/blah/blah/app/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /blah/blah/blah/app/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/blah/blah/blah/app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:17: error: package com.onesignal does not exist
import com.onesignal.ReactNativeOneSignalPackage;
                    ^
/blah/blah/blah/app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:69: error: cannot find symbol
      new ReactNativeOneSignalPackage(),
          ^
  symbol:   class ReactNativeOneSignalPackage
  location: class PackageList
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s
```

Can you please try it yourself and tell me if you get the same results? It would be a great help if it would be possible

**Comment by rgomezp** [comment]
Hello,
This is not really an issue with our SDK so I will be closing the issue. If you would like further assistance, please consider upgrading your OneSignal account to get prioritized support.
