### ISSUE TITLE
onOpened not fired on release 

### ISSUE THREAD

**Issue by ratihshav** [OneSignal/react-native-onesignal#842]
**Description:**

I use AsyncStorage to store additionalData from OneSignal in App.js so I can get the data in Home, I use it to direct to the spesific page with the parameter from additionalData. It works on debug, but in doesn't work on release. 

**Environment**

1. React Native 0.59.10
2. react-native-onesignal 3.3.2

**Steps to Reproduce Issue:**

1. Installing onesignal for react-native
2. Setting up the SDK
3. Sending a push notification.
4. Clicking on the push notification opens up the app and it opens the spesific page 

It happens when the app is in background and when the app is killed (swiped away).

**Anything else:**

Here's my code in the App.js: 

```
async componentWillMount() {
    if (Platform.OS === "android") {
      StatusBar.setBackgroundColor(AppColors.brand.white)
    }
    StatusBar.setBarStyle("dark-content", true)

    OneSignal.init(APP_ID)
    OneSignal.inFocusDisplaying(2)
    OneSignal.addEventListener("received", this.onReceived)
    OneSignal.addEventListener("opened", this.onOpened)
    OneSignal.addEventListener("ids", this.onIds)
    OneSignal.configure()
  }

  componentDidMount() {
    SplashScreen.hide()
    this.getAnimateLoadingUpdaterText()
    this.onAppReady()
  }

  componentWillUnmount() {
    OneSignal.removeEventListener("received", this.onReceived)
    OneSignal.removeEventListener("opened", this.onOpened)
    OneSignal.removeEventListener("ids", this.onIds)
  }

  onReceived(notification) {
    console.log("Notification received: ", notification)
  }

  onOpened(openResult) {
    console.log("Message: ", openResult.notification.payload.body)
    console.log("Data: ", openResult.notification.payload.additionalData)
    console.log("isActive: ", openResult.notification.isAppInFocus)
    console.log("openResult: ", openResult)
    const additionalData = openResult.notification.payload.additionalData
    if (additionalData !== "") {
      const dataType = additionalData.type
      const dataId = additionalData.id

      AsyncStorage.setItem("datatype", dataType)
      AsyncStorage.setItem("dataid", JSON.stringify(dataId))
    }
  }
```
Home.js
```
componentDidMount() {
    this.getNotifStorage()
  }

getNotifStorage = async () => {
    let dataType = await AsyncStorage.getItem("datatype")
    let dataId = await AsyncStorage.getItem("dataid")

    console.log("dataaaa", dataType)
    console.log("dataId", dataId)

    if (dataType === "order_detail" && dataType !== null) {
      setTimeout(() => {
        this.props.navigation.navigate("DetailOrderFinished", { id: dataId })
      }, 100)
    }
    await AsyncStorage.removeItem("datatype")
    await AsyncStorage.removeItem("dataid")
  }
```

**Comment by ratihshav** [comment]
this issue #676 is same with my issue, but there's no closure about the issue

**Comment by rgomezp** [comment]
Thanks for opening this issue. We'll take a look and see what we can find. Thanks for your patience

**Comment by ratihshav** [comment]
> Thanks for opening this issue. We'll take a look and see what we can find. Thanks for your patience

Hey, I solved the issue by moving the eventListener to componentDidMount, but I still don't understand why componentWillMount not firing onOpened on release version

**Comment by rgomezp** [comment]
@ratihshav ,
Must be some strange low-level behavior. `componentWillMount` is deprecated so I would refrain from using it at all. Cheers

**Comment by rukmanary** [comment]
> > Thanks for opening this issue. We'll take a look and see what we can find. Thanks for your patience
> 
> Hey, I solved the issue by moving the eventListener to componentDidMount, but I still don't understand why componentWillMount not firing onOpened on release version

I put it in componentDidMount but I still have this issue in iOS. Android works well
