### ISSUE TITLE
OneSignal.sendTags() behaves differently on iOS and Android

### ISSUE THREAD

**Issue by iamacup** [OneSignal/react-native-onesignal#846]
**Description:**

OneSignal.sendTags() behaves differently on iOS and Android

**Environment**

Android: 

`OneSignal.sendTags({myName: 'oneSignalIsAmazeballs',  thing: false})`

iOS:

`OneSignal.sendTags({myName: 'oneSignalIsAmazeballs',  thing: false})`

on Android, the user will have thing set to false, on iOS, thing will not be set at all.

**Steps to Reproduce Issue:**

On Android:

```
OneSignal.sendTags({sumbit1: false});
OneSignal.sendTags({sumbit2: "false"});
```

User gets properties: `{sumbit1: false, sumbit2: false}`

On iOS

```
OneSignal.sendTags({sumbit1: false});
OneSignal.sendTags({sumbit2: "false"});
```

User gets properties: `{sumbit2: false}`

**Anything else:**

Workaround: Set everything to a string before saving it with OneSignal.sendTags

**Comment by rgomezp** [comment]
This will be resolved in the next release
