### ISSUE TITLE
iOS 13 and Xcode 11 bug clarification 

### ISSUE THREAD

**Issue by MoeMamdouh** [OneSignal/react-native-onesignal#847]
**Description:**
I've received **URGENT & IMPORT iOS 13 Update Changes** and I have a question just for clarification, Please.
what i got from the email if i currently building an app using **Xcode 11**, i have to update the **oneSignal SDK to the latest (3.3.2)** to avoid iOS bug.
but the question is if i already have an existing app already built it, or currently building it  using previous version of Xcode like **Xcode 10.***, don't i need to update any thing, and the iOS 13 users will not effect this bug and will receive the PNs normally, that's right?
thank you.

**Environment**

platform: iOS
react-native-onesignal: 3.2.*

**Comment by rgomezp** [comment]
You need to make sure you update the SDK to the latest version and make sure your app ships with this version. Otherwise, users will start to see issues as they begin updating to iOS 13.
