### ISSUE TITLE
Failed build after latest SDK update

### ISSUE THREAD

**Issue by nitish1099** [OneSignal/react-native-onesignal#848]
**Description:**

I'm failing to make a build after updating the npm version to 3.2.2. I get 
`No Unknown class method found for selector setExternalUserId:`
`No Unknown class method found for selector removeExternalUserId:`

**Environment**

1. What version of the OneSignal React-Native SDK are you using? 3.2.2
2. How did you add the SDK to your project (eg. npm) npm

**Steps to Reproduce Issue:**

1. Update the OneSignal SDK with npm to 3.2.2
2. Build the project in Xcode

**Anything else:**

(crash stacktraces, as well as any other information here)
`No Unknown class method found for selector setExternalUserId:`
`No Unknown class method found for selector removeExternalUserId:`

**Comment by OscarYuen** [comment]
would this be fixed if running `pod update && pod install` under ios folder?

**Comment by rgomezp** [comment]
We've released a new version. Please update and try again

**Comment by rgomezp** [comment]
Closing due to no response. (Note: we have update the SDK to version 3.4.0)
