### ISSUE TITLE
No badge count on iOS

### ISSUE THREAD

**Issue by flobiwankenobi** [OneSignal/react-native-onesignal#85]
My App isn't showing a badge with unopened notifications.

Like I understood that OneSignal handles the count by itself, so I have nothing to pay attetion to, right? I implemented OneSignal by this [guide](https://github.com/geektimecoil/react-native-onesignal#ios-installation).

Any ideas? 

![img_3725](https://cloud.githubusercontent.com/assets/239360/18551640/9349bc0e-7b59-11e6-9f76-69d6c98fffa0.PNG)
![img_3726](https://cloud.githubusercontent.com/assets/239360/18551641/934d833e-7b59-11e6-8061-fb75f95ced1b.PNG)

**Comment by fernsheldon** [comment]
@1ne8ight7even you should try setting the `ios_badgeType` and `ios_badgeCount`.  
Check out the [API documentation](https://documentation.onesignal.com/docs/notifications-create-notification) for it.  

If you are using the OneSignal console, it has the option to increase the badge count.

**Comment by breadadams** [comment]
I _thought_ I was having the same issue, but then I noticed the following setting in the **Options** section of the **New Message** page:

![image](https://cloud.githubusercontent.com/assets/5795227/18785289/b4074918-8197-11e6-8d76-d0ee903f1bfd.png)

Using "Set to" or "Increase by" and entering a number in the field makes it display the badge count (and it's reset when notification is read), maybe it's the same for you?
