### ISSUE TITLE
Error on android version 9 sdk 28

### ISSUE THREAD

**Issue by hieubtvinsofts** [OneSignal/react-native-onesignal#850]
**Description:**

Currently I am having this error on android 9, but the lower versions do not

>  java.lang.IllegalArgumentException
        at android.os.Parcel.createException(Parcel.java:1946)
        at android.os.Parcel.readException(Parcel.java:1910)
        at android.os.Parcel.readException(Parcel.java:1860)
        at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:1751)
        at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:541)
        at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:529)
        at com.onesignal.NotificationChannelManager.createChannel(NotificationChannelManager.java:177)
        at com.onesignal.NotificationChannelManager.processChannelList(NotificationChannelManager.java:218)
        at com.onesignal.OneSignal$4.complete(OneSignal.java:942)
        at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:92)
        at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:11)
        at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:58)
        at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:261)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:33)
        at com.android.server.notification.RankingHelper.createNotificationChannel(RankingHelper.java:607)
        at com.android.server.notification.NotificationManagerService$10.createNotificationChannelsImpl(NotificationManagerService.java:2227)
        at com.android.server.notification.NotificationManagerService$10.createNotificationChannels(NotificationManagerService.java:2242)
        at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:256)

**Environment**

react-native-onesignal: 3.3.3
react-native: 0.60.4

**Steps to Reproduce Issue:**

**Anything else:**
I think it was an error starting from Android 8

**Comment by rgomezp** [comment]
Howdy, thanks for reporting. We'll take a look at what could be happening here. Please provide reproduction steps so we can help you more easily @ hieubtvinsofts

**Comment by hieubtvinsofts** [comment]
hi @rgomezp , I found a person who had the same error as me in another library with the same error, with the same steps. however, I see that you have fixed the library, but I get the same error on this library https://github.com/OneSignal/OneSignal-Android-SDK/issues/733
[](https://github.com/OneSignal/OneSignal-Android-SDK/issues/733)

**Comment by hieubtvinsofts** [comment]
Previously it worked fine, but starting this week it didn't work anymore and crashed right from the start of the app.

**Comment by rgomezp** [comment]
Have you tried removing the **#** as mentioned in the issue you included?

**Comment by rgomezp** [comment]
I also found this one: https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/486

However, I don't see them being the same error. Am I missing something? 
@hieubtvinsofts

**Comment by hieubtvinsofts** [comment]
hi @rgomezp , 

> import React, { Component } from "react";
> import { View, Text, StyleSheet, AppState } from "react-native";
> import OneSignal from "react-native-onesignal";
> import constants from "libraries/utils/constants";
> import NavigationService from "routers/NavigationService";
> import screens from "res/screens";
> import { connect } from "react-redux";
> import { notification } from "../redux/actions/countNotiAction";
> 
> class RootView extends Component {
>   constructor(props) {
>     super(props);
>     this.state = {};
> 
>     OneSignal.init("920106d0-362c-467c-860e-9da4f544ae94");
>     OneSignal.inFocusDisplaying(2);
> 
>     OneSignal.addEventListener("received", this.onReceived(this.reload));
>     OneSignal.addEventListener("opened", this.onOpened(this.onNavigate));
>     OneSignal.addEventListener("ids", this.onIds);
>   }
> 
>   onReceived = reload => notification => {
>     // console.log("Notification received: ", notification);
>     if (
>       notification.payload.additionalData.type_notification !=
>       constants.typeNoti.MESSAGE
>     ) {
>       reload();
>     }
>   };
> 
>   componentWillUnmount() {
>     OneSignal.removeEventListener("received", this.onReceived);
>     OneSignal.removeEventListener("opened", this.onOpened(this.onNavigate));
>     OneSignal.removeEventListener("ids", this.onIds);
>   }
> 
>   onIds(device) {
>     // console.log('Device info: ', device);
>   }
> 
>   reload = () => {
>     this.props.notification(this.props.noNoti + 1);
>   };
> 
>   onOpened = onNavigate => openResult => {
>     //1 la ng cho vay, 2 la nguoi vay
>     const typeUser = openResult.notification.payload.additionalData.type_user;
>     const typeNoti =
>       openResult.notification.payload.additionalData.type_notification;
>     let id_booking = "";
>     let user_send = "";
>     switch (typeNoti) {
>       case constants.typeNoti.NOTIFICATION:
>         id_booking = openResult.notification.payload.additionalData.data.id;
>         onNavigate(screens.COUPON, { id_Coupon: id_booking });
>         break;
>       case constants.typeNoti.PROMOTION:
>         break;
>       case constants.typeNoti.BOOKING_APPROVED:
>       case constants.typeNoti.BOOKING_BUY:
>       case constants.typeNoti.BOOKING_BAD:
>       case constants.typeNoti.BOOKING_DISBURSEMENT:
>       case constants.typeNoti.BOOKING_EXPIRE:
>       case constants.typeNoti.BOOKING_EXPIRED:
>       case constants.typeNoti.BOOKING_SUCCESS:
>       case constants.typeNoti.BOOKING_CANCEL:
>         id_booking =
>           openResult.notification.payload.additionalData.data.booking_id;
>         onNavigate(screens.LOANDETAILS, { id_booking });
>         break;
>       case constants.typeNoti.BOOKING_MAP:
>         id_booking =
>           openResult.notification.payload.additionalData.data.booking_id;
>         onNavigate(screens.FORLOANDETAILS, { id_booking });
>         break;
>       case constants.typeNoti.MESSAGE:
>         user_send =
>           openResult.notification.payload.additionalData.data.user_send;
>         const name = openResult.notification.payload.additionalData.name;
>         onNavigate(screens.CHAT, {
>           id: user_send,
>           type: constants.chat.PEOPLE,
>           name
>         });
>         break;
>       default:
>         break;
>     }
>   };
> 
>   onNavigate = (routers, param) => {
>     if (AppState.currentState === "active") {
>       NavigationService.navigate(routers, param);
>     } else {
>       setTimeout(() => NavigationService.navigate(routers, param), 5000);
>     }
>   };
> 
>   render() {
>     return <View style={styles.container}>{this.props.children}</View>;
>   }
> }
> 
> function mapStateToProps(state) {
>   return {
>     noNoti: state.countNotiReducer.noNoti
>   };
> }
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1
>   }
> });
> 
> export default connect(
>   mapStateToProps,
>   { notification }
> )(RootView);
> 
> 

When I delete this code, the app I run, but when added, it fails again.

>  OneSignal.init("920106d0-362c-467c-860e-9da4f544ae94");
>     OneSignal.inFocusDisplaying(2);
>     OneSignal.addEventListener("received", this.onReceived(this.reload));
>     OneSignal.addEventListener("opened", this.onOpened(this.onNavigate));
>     OneSignal.addEventListener("ids", this.onIds);

 I check in AndroidStudio and running debugging then got an error 

> E/AndroidRuntime: FATAL EXCEPTION: Thread-7
>     Process: com.tviet.sanvay, PID: 5209
>     java.lang.IllegalArgumentException
>         at android.os.Parcel.readException(Parcel.java:1946)
>         at android.os.Parcel.readException(Parcel.java:1888)
>         at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:1418)
>         at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:446)
>         at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:434)
>         at com.onesignal.NotificationChannelManager.createChannel(NotificationChannelManager.java:177)
>         at com.onesignal.NotificationChannelManager.processChannelList(NotificationChannelManager.java:218)
>         at com.onesignal.OneSignal$4.complete(OneSignal.java:942)
>         at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:92)
>         at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:11)
>         at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:58)
>         at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:261)
>         at java.lang.Thread.run(Thread.java:764)

**Comment by rgomezp** [comment]
Hello,
What device are you testing this on?

**Comment by hieubtvinsofts** [comment]
> Hello,

> What device are you testing this on?

If I use Samsung Galaxy S7 (android 7, sdk 25) then the app will run but when using Samsung Galaxy S8 with android 8, sdk26 and devices with a higher sdk version, the app has problems with errors like on

**Comment by rgomezp** [comment]
Are you sending the value with a '#' or no?

**Comment by rgomezp** [comment]
Closing due to no response
