### ISSUE TITLE
How to change deviceInfo (pushToken, playerId) or how to disable onesignal and then reconnect again?

### ISSUE THREAD

**Issue by andreymyssak** [OneSignal/react-native-onesignal#851]
**Description:**
I have a mobile app. After the user has logged in, OneSignal is being initiated and I'm getting device info. Then I send device info to the backend. It's okay. 

1. But, when user has logged out I can't disable OneSignal and so the user still receives push notifications. How to disable OneSignal to then reconnect?
2. If we can disable OneSignal how to change device info (push token or player_id)? Example, the user has logged in with another account and now has the same device info, so he'll receive push notifications from the first account too.

**Environment**
"react-native": "0.60.5",
"react-native-onesignal": "^3.3.2"

**Example code:**
```
import React, {Component} from 'react';
import {View, Button} from 'react-native';
import OneSignal from 'react-native-onesignal';

export default class App extends Component {
  componentDidMount() {
    OneSignal.addEventListener('received', this.onReceived);
    OneSignal.addEventListener('opened', this.onOpened);
    OneSignal.addEventListener('ids', this.onIds);
  }

  componentDidUnmount() {
    OneSignal.removeEventListener('received', this.onReceived);
    OneSignal.removeEventListener('opened', this.onOpened);
    OneSignal.removeEventListener('ids', this.onIds);
  }

  onReceived(notification) {
    console.log('Notification received: ', notification);
  }

  onOpened(openResult) {
    console.log('Message: ', openResult.notification.payload.body);
    console.log('Data: ', openResult.notification.payload.additionalData);
    console.log('isActive: ', openResult.notification.isAppInFocus);
    console.log('openResult: ', openResult);
  }

  onIds(device) {
    console.log('Device info: ', device);
  }

// doesn't work
  onDisconnect = () => {
    OneSignal.init(null);
  };

  onConnect = () => {
    OneSignal.init('ONESIGNAL_APP_ID');
  };

  render() {
    return (
      <View>
        <Button title="dissconect" onPress={this.onDisconnect} />
        <Button title="connect" onPress={this.onConnect} />
      </View>
    );
  }
}
```

**Comment by rgomezp** [comment]
I recommend using `setExternalUserId` to keep track of the current user. Then you can use the external id from the backend to send the correct pushes.

https://documentation.onesignal.com/docs/react-native-sdk#section--setexternaluserid-
