### ISSUE TITLE
App crashes with error: Java.lang.NullPointerException

### ISSUE THREAD

**Issue by pierroo** [OneSignal/react-native-onesignal#852]
**Description:**
I see lots of crashes ANR in my google dashboard, with the following content:

java.lang.NullPointerException
com.onesignal.OneSignal.startLocationUpdate

Caused by: java.lang.NullPointerException: 
  at com.onesignal.OneSignal.startLocationUpdate (OneSignal.java:865)
  at com.onesignal.OneSignal.startRegistrationOrOnSession (OneSignal.java:846)
  at com.onesignal.OneSignal.doSessionInit (OneSignal.java:761)
  at com.onesignal.OneSignal.onAppFocus (OneSignal.java:1222)

**Environment**

Project was added through npm, using all the steps mentionned in official docs.
Using React Native 0.60.5
latest onesignal SDK v3.3.2

**Steps to Reproduce Issue:**

**Anything else:**

Everything else is working fine, notifications are working as expected, it just leads to crashes sometimes that I was unable to reproduce.

**Comment by rgomezp** [comment]
This should be fixed in `3.3.3`. Please update the version! Cheers

**Comment by pierroo** [comment]
> This should be fixed in `3.3.3`. Please update the version! Cheers

I just updated it; but now I get build error and cannot run pod install with iOS.

Apparently this 3.3.3 needs a minimum deployment target at 10, when I used to have it at 9.

Is there any way to go around this?

Here is the error:

UNMutableNotificationContent' is only available on iOS 10.0 or newer


and when I run pod install:

CocoaPods could not find compatible versions for pod "OneSignal":
  In snapshot (Podfile.lock):
    OneSignal (< 3.0, = 2.10.1, >= 2.9.3)

  In Podfile:
    OneSignal (< 3.0, >= 2.9.3)

    react-native-onesignal (from `../node_modules/react-native-onesignal`) was resolved to 3.3.3, which depends on
      OneSignal (= 2.11.0)

Specs satisfying the `OneSignal (< 3.0, >= 2.9.3), OneSignal (< 3.0, = 2.10.1, >= 2.9.3), OneSignal (= 2.11.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by rgomezp** [comment]
@pierroo ,
I would urge you to set a min deployment target of 10 so that you can use our latest features including In-App Messaging. 

>Specs satisfying the OneSignal (< 3.0, >= 2.9.3), OneSignal (< 3.0, = 2.10.1, >= 2.9.3), OneSignal (= 2.11.0) dependency were found, but they required a higher minimum deployment target.

Try running `pod update` from your `ios` directory
