### ISSUE TITLE
TypeError: RNOneSignal.didSetNotificationOpenedHandler is not a function RN 59.3

### ISSUE THREAD

**Issue by chiaberry** [OneSignal/react-native-onesignal#853]
**Description:**

I upgraded to 3.3.2 and now get the error message "TypeError: RNOneSignal.didSetNotificationOpenedHandler is not a function" when my app launches and sets event listeners. I've only tested it on ios so far. 

Does the new package work on RN < 60?

**Environment**

1. OneSignal version 3.3.2
2. npm installed the new version
3. RN 59.3

**Steps to Reproduce Issue:**

1. `rm -rf node-modules` update package and `npm install`
2. launch app
3. see red screen.

**Anything else:**

I saw this closed issue, (https://github.com/geektimecoil/react-native-onesignal/issues/834), but its a new version of RN than what we are using.

**Comment by chiaberry** [comment]
appears I'm not the only one: https://github.com/geektimecoil/react-native-onesignal/issues/682

**Comment by rgomezp** [comment]
Are you seeing this in Android or iOS? Also, there is a new version (3.3.3) so please update.

**Comment by williamswebworks** [comment]
I am seeing this on Android only

**Comment by rgomezp** [comment]
Please update to the latest version (3.3.3)

**Comment by chiaberry** [comment]
I updated to the latest version, and did a clean restart and the error messages went away. 

I tested on the ios simulator and a pixel 2.
