### ISSUE TITLE
Error trying to test inAppMessaging

### ISSUE THREAD

**Issue by ReneMarquez** [OneSignal/react-native-onesignal#857]
**Description:**

I'm trying to test the In app messaging feature with the latest update on iOS, I upgraded the npm package to the latest version (3.3.3) and it gives the next error trying to use the OneSignal.addTriggers(), if I comment that line, everything works

![Simulator Screen Shot - iPhone 6 - 2019-09-13 at 13 55 23](https://user-images.githubusercontent.com/6062044/64894295-2939bc00-d62e-11e9-9bba-74bebd71dac4.png)

**Environment**

1.- using version of library 3.3.3
2. I'm not using cocoapods, I installed just by linking and doing the extension part.

**Steps to Reproduce Issue:**

1. update package version to 3.3.3 using npm
2. try to use function OneSignal.addTrigger()
3. red screen comes up

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
What version of RN are you using? Also, you're likely not using the latest version of the OneSignal iOS native SDK. Can you make sure you're using 2.11.0?

From our docs:
> If you are not using Cocoapods AND react-native link react-native-onesignal does not work
Add RCTOneSignal project into Libraries manually ([screenshot](https://github.com/geektimecoil/react-native-onesignal/issues/604#issuecomment-443293568)):
Open node_modules/react-native-onesignal/ios
Then, drag and drop RCTOneSignal.xcodeproj into XCode project folder Libraries

**Comment by ReneMarquez** [comment]
> What version of RN are you using? Also, you're likely not using the latest version of the OneSignal iOS native SDK. Can you make sure you're using 2.11.0?
> 
> From our docs:
> 
> > If you are not using Cocoapods AND react-native link react-native-onesignal does not work
> > Add RCTOneSignal project into Libraries manually ([screenshot](https://github.com/geektimecoil/react-native-onesignal/issues/604#issuecomment-443293568)):
> > Open node_modules/react-native-onesignal/ios
> > Then, drag and drop RCTOneSignal.xcodeproj into XCode project folder Libraries

I'm using React native 0.59.9
How can I check which sdk version am I using? My problem is not the linking part, as I've been using onesignal for a while now, and when I comment the lines related to inAppMessaging, everything works as expected

**Comment by rgomezp** [comment]
I'm not sure what could be happening here. Could you try upgrading to the latest RN which does automatic linking?

**Comment by rgomezp** [comment]
Update: we have released version 3.4.1 that should fix this issue. If not, please comment and I will reopen. Cheers

**Comment by ReneMarquez** [comment]
just fyi, I updated react native to latest, and installed react native onesignal using cocoapods and that fixed it, it was a mess but oh well, just for anyone that encounters anything similar
