### ISSUE TITLE
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:font

### ISSUE THREAD

**Issue by QuYunFengg** [OneSignal/react-native-onesignal#860]
I use 'react-native': 0.43.3,     "react-native-onesignal": "3.0.4"
Suddenly this error occurred in today's operation
![image](https://user-images.githubusercontent.com/29081440/65111723-b8204d00-da0f-11e9-9e22-b0e23b6f8437.png)

Please help me analyze the problem.

**Comment by rgomezp** [comment]
Please update the SDK to version 3.4.1
