### ISSUE TITLE
_OBJC_CLASS_$_WKWebViewConfiguration

### ISSUE THREAD

**Issue by andiskim** [OneSignal/react-native-onesignal#861]
**Description:**
I was previously using react-native-onesignal 3.2.12 which worked fine, of which I followed the steps in the setup documentation.  However, libOnesignal.a used UIWebkit so I had to upgrade.  I am getting an error:

"_OBJC_CLASS_$_WKWebViewConfiguration"

**Environment**
1. react-native 0.57.4
2. react-native-onesignal 3.4.1
2. yarn add react-native-onesignal

**Steps to Reproduce Issue:**

1. Install OneSignal SDK using yarn
2. Run build

**Anything else:**

![image](https://user-images.githubusercontent.com/6220220/65143455-d5b4dd00-da36-11e9-8298-2b2aacf4f4ae.png)

Adding Webkit.framework:
![image](https://user-images.githubusercontent.com/6220220/65143524-04cb4e80-da37-11e9-9e38-dc5c8e05893c.png)

Resulting error from that:
![image](https://user-images.githubusercontent.com/6220220/65143544-0eed4d00-da37-11e9-8dfd-5d7ae9869d49.png)

Thanks for your help!

**Comment by rgomezp** [comment]
Can you please run `pod deintegrate && pod install` from your ios folder?

**Comment by sunnyarain** [comment]
Facing the same issue on below environment 
react-native 0.57.5
react-native-onesignal 3.4.1

**Comment by sunnyarain** [comment]
was facing the same issue and i resolved it by adding CoreGraphics.framework to OneSignalNotificationServiceExtension
<img width="637" alt="onesignal" src="https://user-images.githubusercontent.com/32029269/65214754-96cd6880-dac4-11e9-9fb1-b6d4a5f02f49.png">

**Comment by andiskim** [comment]
@sunnyarain Worked! Thank you!

**Comment by coderdave** [comment]
wow, this issue should have stayed open until the documentation is updated! I was previously using `3.3.2` and upgraded to `3.4.1` because iOS 13 notifications stopped working. After a few hours, I stumbled on this issue and to my surprise I had to add `CoreGraphics.framework` AND `WebKit.framework`.  :(

**Comment by rgomezp** [comment]
I'll reopen because those frameworks should be getting added automatically

**Comment by coderdave** [comment]
When you link it? I'm talking about the documentation here: https://documentation.onesignal.com/docs/react-native-sdk-setup-continued-without-cocoapods

**Comment by rgomezp** [comment]
@coderdave ,
Thanks for pointing that out. I went ahead and updated those docs for manual linking (no cocoapods)

**Comment by cinder92** [comment]
after done that @sunnyarain suggested im getting the following errors, for iOS 13

![Captura de Pantalla 2019-10-02 a la(s) 12 14 50](https://user-images.githubusercontent.com/4725556/66066033-5af7c180-e50e-11e9-843b-2600a957106d.png)

**Comment by rgomezp** [comment]
@cinder92 ,
It looks like your project is not using the latest version of the iOS SDK framework.
If you're using cocoapods, go into your `ios` directory and run `pod deintegrate && pod install`. 

If that doesn't work, follow this guide: https://documentation.onesignal.com/docs/react-native-sdk-setup#section-manually-updating-ios-onesignalnativesdk

**Comment by 77TecShaeer** [comment]
+++
