### ISSUE TITLE
Apply Onesignal Plugin Breaking the Build

### ISSUE THREAD

**Issue by njanice** [OneSignal/react-native-onesignal#869]
**Description:**

I am using @mauron85/react-native-background-geolocation library and it works fine but after putting `apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin' ` in app/build.gradle doing `./gradlew clean` or `react-native run-android` is failing

**Environment**

Here are my dependecies
```
"@mauron85/react-native-background-geolocation": "^0.6.3",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-onesignal": "3.3.3",
```

**Steps to Reproduce Issue:**

1. Create react native project 0.60.5 version
2. Install @mauron85/react-native-background-geolocation (follow installation guide from [installation guide](https://github.com/mauron85/react-native-background-geolocation#instalation))
3. Install & setup react native onesignal

**Error:**
```
* What went wrong:
A problem occurred configuring project ':@mauron85_react-native-background-geolocation'.
> Cannot change artifacts of configuration ':@mauron85_react-native-background-geolocation:default' after it has been included in dependency resolution.
```

**Comment by rgomezp** [comment]
Please update to the latest SDK version. Also, this doesn't seem to be an issue with OneSignal, but rather the other library

**Comment by njanice** [comment]
@rgomezp thank you for replying I will ask in the other library. But anyway do you have an idea why this happened so maybe I could find another work around?

**Comment by rgomezp** [comment]
Sorry, I'm not sure as I'm not familiar with that library. Hope you are able to resolve!
