### ISSUE TITLE
Onesignal restarts my bundle when my app is in foreground.

### ISSUE THREAD

**Issue by sarmad1995** [OneSignal/react-native-onesignal#874]
React native version `0.59.8`
react native onesignal `3.3.2`

When i open the notification while my app is in foreground. It runs the `onOpened` method as expected but it also restarts my react native bundle,
I have also explained everything here.

https://stackoverflow.com/questions/58218152/react-native-onesignal-bundle-is-restarted-when-app-is-in-foreground

Help would be appreciated. Either I am missing something or no one noticed this till now.

**Comment by rgomezp** [comment]
Howdy, 
Please make sure you follow our issue template. You're also running an old version of the SDK. Please update to the latest.
