### ISSUE TITLE
JobIntentService error

### ISSUE THREAD

**Issue by JinHoSo** [OneSignal/react-native-onesignal#879]
**Description:**

Hi, I got a crash report from firebase after upgrading one signal SDK.
Most errors occur in Galaxy S10(android 9)

> Caused by java.lang.IllegalArgumentException
> Given work is not active: JobWorkItem{id=2 intent=Intent { cmp=kr.co.hybridapps.meinhiapp/com.onesignal.GcmIntentJobService (has extras) } dcount=2}

```
android.app.job.JobParameters.completeWork (JobParameters.java:268)
android.support.v4.app.JobIntentService$JobServiceEngineImpl$WrapperWorkItem.complete (JobIntentService.java:268)
android.support.v4.app.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:394)
android.support.v4.app.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:383)
android.os.AsyncTask$2.call (AsyncTask.java:333)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:764)
```

**Environment**

    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-onesignal": "^3.4.2"

**Anything else:**

> Fatal Exception: java.lang.RuntimeException
> An error occurred while executing doInBackground()

android.os.AsyncTask$3.done (AsyncTask.java:354)
java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:383)
java.util.concurrent.FutureTask.setException (FutureTask.java:252)
java.util.concurrent.FutureTask.run (FutureTask.java:271)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:764)

**Comment by rgomezp** [comment]
This has been resolved by https://github.com/OneSignal/OneSignal-Android-SDK/pull/845 and will be included in the next release over the next few days. You can also[ update the native SDK version manually](https://github.com/OneSignal/OneSignal-Android-SDK/pull/845).

**Comment by JinHoSo** [comment]
@rgomezp Thanks!
