### ISSUE TITLE
Users get unsubscribe after sending a notification

### ISSUE THREAD

**Issue by Tuapplicacion** [OneSignal/react-native-onesignal#882]
**Description:**

The test user's subscription appears as inactive after seding the first notification.

(your description here)

**Environment**

`
{
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-onesignal": "^3.4.2",
}
`

**Steps to Reproduce Issue:**

When I run my app on development or even generating the APK, my users has an active subscription, but after sending the first notification, the user's subscription appears inactive, and If I compile the application again it appears active again.

**Comment by jeanlambert17** [comment]
I'm having the same issue, some fix?

**Comment by rgomezp** [comment]
Just confirming this is only on Android correct? Also what other plugins / SDKs are you using, since one of those could be unsubscribing the device. On Android, are you using more than one FCM project number in your app? This can unsubscribe the device. 

Does this occur for new test users?

If possible, please include the `player_id` and `notification_ids`. You can [encrypt](https://www.devglan.com/online-tools/rsa-encryption-decryption) them for privacy using this public key:

```
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC2Y323CAkYm0HrC/4IpJDRTYqUl8t2sk7j7fstbJ0mMr9OJfJC5PC6E2HnIRHonKJDzdiirikoVu+MExInXM1kzBg8CLpgMf9djmDzpKqPAVUqf3c909WzfKTdSBAZne22w5zaSxlyFftx2LYBZwGSP6gZZa15i9lI7XUykDenxwIDAQAB
```

**Comment by Jnlbr** [comment]
Yes, only Android, and it also happens for test users. I'm using `react-native-push-notification` with the same FCM number as OneSignal, but I thought that and I removed the library from my code but I didn't delete from Android, iOS or node_modules.

Should I removed the library completely?

**Comment by jeanlambert17** [comment]
Yes, only Android, and it also happens for test users. I'm using react-native-push-notification with the same FCM number as OneSignal, but I thought that and I removed the library from my code but I didn't delete from Android, iOS or node_modules.

Should I removed the library completely?

**Comment by rgomezp** [comment]
Yes, if you can remove the other library this is best. If not, take a look at this [thread](https://github.com/geektimecoil/react-native-onesignal/issues/605) for more info.

**Comment by jeanlambert17** [comment]
> Yes, if you can remove the other library this is best. If not, take a look at this [thread](https://github.com/geektimecoil/react-native-onesignal/issues/605) for more info.

Thanks. I'm gonna give it a try.

**Comment by rgomezp** [comment]
I'd like to close out this issue. Any results?

**Comment by jeanlambert17** [comment]
Yeah, it works for me, thanks!

**Comment by jeanlambert17** [comment]
> Yeah, it works for me, thanks!

The only problem I still have if I didn't find how to send local notifications with `react-native-onesignal`, so, instead of sending a local notification I use the method `OneSignal.postNotification` to send a remote notification to "myself". It works but I'd like to know if there's a better way.

**Comment by rgomezp** [comment]
You can see the better way in this [comment](https://github.com/OneSignal/react-native-onesignal/issues/605#issuecomment-496722134) in the above mentioned thread. It does require some iOS native experience

**Comment by jeanlambert17** [comment]
And for Android?

**Comment by amit13091992** [comment]
@Jnlbr You need to add a conditional check to prevent this for the app. [here I am subscribing to the notification services and email which I am using in the app.]
please follow the below code-snippet, it willhelp you. Thanks
The below code is for **monitoring the subscription**.

```
constructor(props) {
    super(props);
    this.state = {};
    OneSignal.init("YOUR_ONESIGNAL_ID", { kOSSettingsKeyAutoPrompt: true });
  }

  componentDidMount() {
    this.onEmailRegistrationChange = this.onEmailRegistrationChange.bind(this);
    OneSignal.addEventListener('received', this.onReceived);
    OneSignal.addEventListener('opened', this.onOpened);
    OneSignal.addEventListener('ids', this.onIds);
    OneSignal.addEventListener('emailSubscription', this.onEmailRegistrationChange);
    OneSignal.setSubscription(true);
  }

componentWillUnmount() {
    OneSignal.removeEventListener('received', this.onReceived);
    OneSignal.removeEventListener('opened', this.onOpened);
    OneSignal.removeEventListener('ids', this.onIds);
  }

  onEmailRegistrationChange(registration) {
    console.log('onEmailRegistrationChange: status ', registration);
  }
```

and when you want to **unsubscribe from the services** you can use the below 2 lines of code:

```
OneSignal.setSubscription(false);
OneSignal.removeEventListener('emailSubscription', this.onEmailRegistrationChange);
```

**Comment by hoaluu550** [comment]
hi @rgomezp 

i'm using @react-native-firebase/app: 14.9.1 and react-native-onesignal: 5.2.2
I also unsubscription when sending a notification
Please help me with any solution
