### ISSUE TITLE
Can't run `pod install`

### ISSUE THREAD

**Issue by jeanlambert17** [OneSignal/react-native-onesignal#883]
**Description:**

When I try to run `pod install` after installing one-signal it crashes with react-native-fbsdk dependencies.

**Environment**

React native: 0.60.4
OneSignal: 3.4.2
React-native-fbsdk: 1.0.1

**Steps to Reproduce Issue:**

  1. Install the OneSignal SDK using npm into your project.
  2. Run command `pod install` inside ios folder.
  3. Wait for it.

**Anything else:**

**Stacktrace:** 
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In snapshot (Podfile.lock):
    FBSDKCoreKit (= 5.0.2, ~> 5.0)

  In Podfile:
    react-native-fbsdk (from `../node_modules/react-native-fbsdk`) was resolved to 1.0.4, which depends on
      react-native-fbsdk/Core (= 1.0.4) was resolved to 1.0.4, which depends on
        FBSDKCoreKit (~> 5.5)**

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `FBSDKCoreKit` inside your development pod `react-native-fbsdk`.
   You should run `pod update FBSDKCoreKit` to apply changes you've made.

If I run `pod update FBSDKCoreKit` it crashes with the same error but instead of crashing for FBSDKCoreKit it crashes for `FBSDKShareKit`, If I do the same with ShareKit it crashes for `FBSDKLoginKit` and the last one crashes for the first one :// `FBSDKCoreKit`

Pls help.

**Comment by rgomezp** [comment]
This doesn't seem related to our SDK. Can you please try removing the other SDK and seeing if it works? If not, I recommend opening an issue directly with the maintainers of that package.

**Comment by jeanlambert17** [comment]
Well, I "fix" it, running `yarn add react-native-onesignal react-native-fbsdk` and then `pod install`.

Idk what's exactly happening, bc when I installed OneSignal it crashes like I said before, and if I install fbsdk it deletes OneSignal library, that's why I decided to install them both simultaneously.

**Comment by rgomezp** [comment]
Interesting. Thanks for the info. So it is resolved?

**Comment by jeanlambert17** [comment]
Yes, I guess it is.
