### ISSUE TITLE
pushToken is always null in IOS

### ISSUE THREAD

**Issue by Luckygirlllll** [OneSignal/react-native-onesignal#884]
**Description:**

I'm getting pushToken null, when testing on real device in IOS

(your description here)

```
 onIds = async (device) => {
    console.log("push token", device.pushToken)
    }
```

push Token is always null inside `onIds`

**Environment**

1. What version of the OneSignal React-Native SDK are you using? "react-native-onesignal": "^3.4.2",
2. How did you add the SDK to your project? nom

**Steps to Reproduce Issue:**

1. Add library 
2. Run app on real device

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by Luckygirlllll** [comment]
When I test the app from the TestFlight,  it works correctly

**Comment by rgomezp** [comment]
Please reach out to our support channel at OneSignal.com for further assistance

**Comment by hasgar-aot** [comment]
@Luckygirlllll @rgomezp same issue here.. any solution?

**Comment by Luckygirlllll** [comment]
@hasgarAOT not yet, @rgomezp just closed my issue without any solution

**Comment by rgomezp** [comment]
Try `pod deintegrate && pod install` from within your ios directory. Also, can you please include logs? Make sure to run `setLogLevel` (onesignal function)

**Comment by hasgar-aot** [comment]
My issue fixed after restarting. Maybe cache problem..i’m using 3.4.2

**Comment by rgomezp** [comment]
@hasgarAOT ,
Good to hear. 

For others, please note that OneSignal is blocked by Egypt right now, which may contribute to occurrences of this issue.

**Comment by hasgar-aot** [comment]
@rgomezp same issue again. 

These are the only warning I can find related onesignal:

```
[User Defaults] Couldn't read values in CFPrefsPlistSource<0x280fc0c00> (Domain: group.com.yepdesk.ydsaas.onesignal, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd

Attempted to send an event (OneSignal-idsAvailable) when no listeners were set.
```

It was working sometimes. I'm getting userId, but push token is null. 
working with test flight builds
tried manual and pods
v3.4.2
