### ISSUE TITLE
onIds not trigger only in iOS 13 & App not asking for permission at the beginning

### ISSUE THREAD

**Issue by mustafaskyer** [OneSignal/react-native-onesignal#890]
**Description:**

App not asking permissions for notifications at the beginning,
listener `onIds` not working,
also tried `getPermissionSubscriptionState`, but not working

**Environment**

package installed by `yarn`,
installed `without cocoapods`

```
OS: macOS 10.14.4
Platforms: iOS 13.0
react-native: ^0.59.10 
"react-native-onesignal": "^3.5.0"
```

**Steps to Reproduce Issue:**

1. installed the package by `yarn`
2. link the package && follow the installation from this link [without-cocoapods](https://documentation.onesignal.com/docs/react-native-sdk-setup-continued-without-cocoapods)

**Comment by rgomezp** [comment]
Hello, are you in Egypt?

**Comment by mustafaskyer** [comment]
Hi @rgomezp,  Saudi Arabia

**Comment by rgomezp** [comment]
Please see [this issue](https://github.com/OneSignal/react-native-onesignal/issues/887) @mustafaskyer 

You will need to follow the manual linking steps I link to in that issue. Cheers.

**Comment by blazk0** [comment]
> Hello, are you in Egypt?

@rgomezp 
I am and i am having the same problem
