### ISSUE TITLE
The methods received and opened not works in iOS if the app is closed

### ISSUE THREAD

**Issue by davidcort** [OneSignal/react-native-onesignal#891]
**Description:**
When the app is closed, the device received the push notification but when push on system notification popup or the task bar, the app only starts, nothing happen. 
If the app is open in the background or focus, the methods works fine.

**Environment**

1. What version of the OneSignal React-Native SDK are you using?
**react-native-onesignal@3.4.1**

2. How did you add the SDK to your project (eg. npm)
**Following the offical documentation https://documentation.onesignal.com/docs/react-native-sdk-setup**

3. What version of the react-native are you using?
**The latest 0.61.4**

**Steps to Reproduce Issue:**

  Example:

  1. Install the OneSignal SDK using npm into your project
  2. Initialize the SDK in the iOS AppDelegate
  3. Attempt to receive a push notification
  4. Using the example code from OneSignal:

```
constructor() {
    super();
    OneSignal.init("YOUR_ONESIGNAL_APPID");

    OneSignal.addEventListener('received', this.onReceived);
    OneSignal.addEventListener('opened', this.onOpened);
  }

  componentWillUnmount() {
    OneSignal.removeEventListener('received', this.onReceived);
    OneSignal.removeEventListener('opened', this.onOpened);
  }

  onReceived(notification) {
    console.log("Notification received: ", notification);
  }

  onOpened(openResult) {
    console.log('Message: ', openResult.notification.payload.body);
    console.log('Data: ', openResult.notification.payload.additionalData);
    console.log('isActive: ', openResult.notification.isAppInFocus);
    console.log('openResult: ', openResult);
  }
```
In Android works fine, this issue only happen in iOS.

**Comment by davidcort** [comment]
The problem was the settings in apps group. Sorry

**Comment by spacepotato** [comment]
I'm having a similar issue @davidcort - what setting was causing the problem?

**Comment by davidcort** [comment]
@spacepotato In release mode, the One Signal Extension needs specifical certificates and very important, in the Capability add the App Groups, which should activate in the certificate or profile.

**Comment by akos-bako** [comment]
@davidcort could you please elaborate on the fix?

I have found [this document](https://documentation.onesignal.com/docs/ios-sdk-app-groups-setup) regarding the App Groups, but doing only this, didn't solve the problem for me.

**Comment by akos-bako** [comment]
@spacepotato Did you manage to fix the issue?

**Comment by spacepotato** [comment]
@akos-bako for us the issue was being caused because react-native-splash-screen was messing with one signal in our app delegate.

**Comment by davidcort** [comment]
@akos-bako what version of RN are you using?
