### ISSUE TITLE
Cannot get devices id in some devices.

### ISSUE THREAD

**Issue by januarsmad** [OneSignal/react-native-onesignal#892]
My aplications is already on Productions,  but my aplication cannot most of the devices id from my user. So some of my user didnt receive notifications. I wonder what's wrong with my settings so some user didn't get the notification.

Here's are the config that i wrote in my app.js
```
OneSignal.init(env.oneSignalID, { kOSSettingsKeyAutoPrompt: true });
OneSignal.addEventListener('ids', this.onIds);
OneSignal.inFocusDisplaying(2);

onIds = device => {
    if (device.userId) {
      store.dispatch({
        type: Dispatches.SAVE_ONESIGNAL_ID,
          payload: {
          onesignal_token: device.userId,
        },
      });
    }
  };

componentWillUnmount() {
    OneSignal.removeEventListener('ids', this.onIds);
  }
```

and here's my package.json..
```
"dependencies": {
    "react": "16.8.3",
    "react-native": "^0.59.6",
    "react-native-appsflyer": "^1.4.5",
  },
```

Thanks for all the help and replies. I really appreciate it.

**Comment by rgomezp** [comment]
Howdy, 
Are you in Egypt? If so, please see this [issue](https://github.com/OneSignal/OneSignal-Android-SDK/issues/855)

**Comment by januarsmad** [comment]
@rgomezp Howdy sir, i'm in Indonesia..

**Comment by rgomezp** [comment]
@januarsmad please try to reproduce the issue with OneSignal setLogLevel set to VERBOSE. Also, log the device variable to see if it's arriving correctly
```
onIds(device) {
    console.log('Device info: ', device);
}
```

**Comment by rgomezp** [comment]
Closing due to no response
