### ISSUE TITLE
Could not determine the dependencies react-native-onesignal:compileDebugAidl

### ISSUE THREAD

**Issue by DevAelius** [OneSignal/react-native-onesignal#894]
My Package.json file

"dependencies": {
    "accordion-collapse-react-native": "^0.1.11",
    "moment": "^2.24.0",
    "native-base": "^2.12.1",
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-admob": "^2.0.0-beta.6",
    "react-native-af-video-player": "^0.2.1",
    "react-native-elements": "^1.2.0",
    "react-native-fbsdk": "^1.0.4",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-google-signin": "^2.1.0",
    "react-native-htmlview": "^0.14.0",
    "react-native-image-picker": "^1.1.0",
    "react-native-keep-awake": "^4.0.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-material-textfield": "^0.12.0",
    "react-native-modal": "^11.3.1",
    "react-native-onesignal": "^3.5.0",
    "react-native-orientation": "^3.1.3",
    "react-native-popup-menu": "^0.15.6",
    "react-native-searchbar": "^1.16.0",
    "react-native-simple-toast": "0.0.8",
    "react-native-swiper": "^1.5.14",
    "react-native-vector-icons": "^6.6.0",
    "react-native-video": "^5.1.0-alpha1",
    "react-native-video-controls": "^2.2.3",
    "react-navigation": "^3.11.0",
    "rn-fetch-blob": "^0.11.2"
  }

Project run file before adding one Signal after adding one Signal as per document its throw below error in terminal. 

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-onesignal:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-onesignal:debugCompileClasspath'.
   > Could not find any version that matches com.google.android.gms:play-services-ads-identifier:12.+.
     Versions that do not match:
       - 17.0.0
       - 16.0.0
       - 15.0.1
       - 15.0.0
     Required by:
         project :react-native-onesignal > com.onesignal:OneSignal:3.12.2

**Comment by rgomezp** [comment]
Howdy,
Are you using the [OneSignal Gradle Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues)?

**Comment by rgomezp** [comment]
Closing due to no response
