### ISSUE TITLE
Android App crashes on push notification

### ISSUE THREAD

**Issue by arnaud-albalat** [OneSignal/react-native-onesignal#898]
I developed a React Native app that crashes every time a push notification from OneSignal is received while the app is active.

The error is `java.lang.NoSuchMethodError: No static method zzc`.

If I receive the notification when the app is on background, there is no problem.

Here is my build.gradle file:

	buildscript {
		ext {
			googlePlayServicesLocationVersion = "17.0.0"
			buildToolsVersion = "28.0.3"
			minSdkVersion = 21
			compileSdkVersion = 28
			targetSdkVersion = 28
			supportLibVersion = "28.0.0"
			appCompatVersion = "1.0.2"
		}
		repositories {
			google()
			jcenter()
		}
		dependencies {
			classpath 'com.android.tools.build:gradle:3.3.0'
		}
	}

	allprojects {
		repositories {

			configurations.all {
				resolutionStrategy.eachDependency { DependencyResolveDetails details ->
				def requested = details.requested
			   if (requested.group == 'com.google.android.gms') {
				  details.useVersion '17.0.0'
			   }
			   if (requested.group == 'com.google.firebase') {
				  details.useVersion '17.0.0'
				 }
			   }
			 }
			google()
			mavenLocal()

			jcenter()
			maven {
				// All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
				url "$rootDir/../node_modules/react-native/android"
			}

			maven {
			   url "$rootDir/../node_modules/react-native-background-geolocation/android/libs"
			}

				maven {
					url "$rootDir/../node_modules/react-native-background-fetch/android/libs"
				}
		}
	}

	task wrapper(type: Wrapper) {
		gradleVersion = '4.10'
		distributionUrl = distributionUrl.replace("bin", "all")
	}

And my app/build.gradle file:

	apply plugin: "com.android.application"

	import com.android.build.OutputFile

	project.ext.react = [
		entryFile: "index.js"
	]

	apply from: '../../node_modules/react-native-unimodules/gradle.groovy'
	apply from: "../../node_modules/react-native/react.gradle"

	Project background_geolocation = project(':react-native-background-geolocation')
	apply from: "${background_geolocation.projectDir}/app.gradle"

	def enableSeparateBuildPerCPUArchitecture = false

	def enableProguardInReleaseBuilds = false

	android {
		compileSdkVersion rootProject.ext.compileSdkVersion
		buildToolsVersion rootProject.ext.buildToolsVersion

		defaultConfig {
			applicationId "XXX"
			minSdkVersion rootProject.ext.minSdkVersion
			targetSdkVersion rootProject.ext.targetSdkVersion
			versionCode 200
			versionName "24.10"
		}
		splits {
			abi {
				reset()
				enable enableSeparateBuildPerCPUArchitecture
				universalApk false  // If true, also generate a universal APK
				include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
			}
		}
		signingConfigs {
			release {
				if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
					storeFile file(MYAPP_UPLOAD_STORE_FILE)
					storePassword MYAPP_UPLOAD_STORE_PASSWORD
					keyAlias MYAPP_UPLOAD_KEY_ALIAS
					keyPassword MYAPP_UPLOAD_KEY_PASSWORD
				}
			}
		}
		buildTypes {
			release {
				minifyEnabled enableProguardInReleaseBuilds
				proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
				signingConfig signingConfigs.release
			}
		}
		// applicationVariants are e.g. debug, release
		applicationVariants.all { variant ->
			variant.outputs.each { output ->
				// For each separate APK per architecture, set a unique version code as described here:
				// http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
				def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3, "x86_64": 4]
				def abi = output.getFilter(OutputFile.ABI)
				if (abi != null) {  // null for the universal-debug, universal-release variants
					output.versionCodeOverride =
							versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
				}
			}
		}
		compileOptions {
			sourceCompatibility JavaVersion.VERSION_1_8
			targetCompatibility JavaVersion.VERSION_1_8
		}
	}

	dependencies {
		implementation project(':@react-native-community_netinfo')
		implementation project(':react-native-fast-image')
		implementation project(':react-native-device-info')
		implementation project(':react-native-orientation-locker')
		implementation project(':@react-native-community_slider')
		implementation project(':react-native-webview')
		implementation project(':react-native-splash-screen')
		implementation project(':@react-native-community_async-storage')
		implementation project(':react-native-sentry')
		implementation project(':react-native-background-fetch')
		implementation project(':react-native-maps')
		implementation project(':react-native-iap')
		implementation project(':react-native-gesture-handler')
		implementation project(':react-native-background-geolocation')
		implementation project(':react-native-webrtc')
		implementation project(':react-native-svg')
		implementation project(':react-native-onesignal')
		implementation project(':react-native-incall-manager')
		implementation project(':react-native-fs')
		implementation project(':react-native-reanimated')
		implementation fileTree(dir: "libs", include: ["*.jar"])
		implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
		implementation "com.facebook.react:react-native:+"  // From node_modules
		implementation 'com.android.support:multidex:1.0.3'
		implementation 'com.facebook.fresco:animated-gif:1.10.0'
		implementation "com.facebook.fresco:animated-base-support:1.3.0"
		addUnimodulesDependencies()
	}

	// Run this once to be able to run the application with BUCK
	// puts all compile dependencies into folder libs for BUCK to use
	task copyDownloadableDepsToLibs(type: Copy) {
		from configurations.compile
		into 'libs'
	}

	// [Added by react-native-background-geolocation] Purge debug sounds from release build.
	def purgeBackgroundGeolocationDebugResources(applicationVariants) {
		if ((rootProject.ext.has("removeBackgroundGeolocationDebugSoundsInRelease")) && (rootProject.ext.removeBackgroundGeolocationDebugSoundsInRelease == false)) return
		applicationVariants.all { variant ->
			if (variant.buildType.name == "release") {
				println("[react-native-background-geolocation] Purging debug resources in release build")
				variant.mergeResources.doLast {
					delete(fileTree(dir: variant.mergeResources.outputDir, includes: ["raw_tslocationmanager*"]))
				}
			}
		}
	}

Do you know where the problem could come from?

**Comment by vadermemo** [comment]
Which version of React native and Onesignal?

this is my conf:
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-onesignal": "^3.5.0"

I receive in app but not in background :(

**Comment by arnaud-albalat** [comment]
My conf:

    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-onesignal": "3.5.0",

**Comment by rgomezp** [comment]
Please include the full stack trace

**Comment by raphael-evolutap** [comment]
I'm was having this issue with Android 9 to, it was solved putting android:permission="android.permission.BIND_JOB_SERVICE" in **AndroidManifest.xml** 

https://documentation.onesignal.com/docs/service-extensions#section-notification-extender-service

compileSdkVersion 26
buildToolsVersion '26.0.2'

But with version 27 works too.

```
<service
        android:name="com.geektime.rnonesignalandroid.NotificationNotDisplayingExtender"
        android:permission="android.permission.BIND_JOB_SERVICE"
        android:exported="false">
        <intent-filter>
          <action android:name="com.onesignal.NotificationExtender" />
        </intent-filter>
      </service>
```

**Comment by rgomezp** [comment]
Thanks for the solution @raphael-evolutap ,
I will close since I received no reply from OP or others

**Comment by stefanoTron** [comment]
In case someone else still has this issue, I had to remove the this : 

```
configurations.all {
resolutionStrategy.eachDependency { DependencyResolveDetails details ->
 def requested = details.requested
     if (requested.group == 'com.google.android.gms') {
        details.useVersion '17.0.0'
     }
     if (requested.group == 'com.google.firebase') {
        details.useVersion '17.0.0'
       }
    }
```
in my `build.gradle` file.
