### ISSUE TITLE
DeviceIds Not being generated on Android for RN 61.4

### ISSUE THREAD

**Issue by onisaint** [OneSignal/react-native-onesignal#899]
**Description:**
Onids Is not being triggered for react native 0.61.4

**Environment**

rn: 61.4,
oneSignal: 3.5.0

works on ios (same source)

**Comment by onisaint** [comment]
also it there any way to get the deviceId stored in the OneSignal configuration to double 
check

**Comment by rgomezp** [comment]
Hello, 
Please provide further details as outlined by our issue template (stack trace, log set to VERBOSE, etc...) 

p.s. Is the id's event even firing? may be duplicate of https://github.com/OneSignal/react-native-onesignal/issues/892

**Comment by onisaint** [comment]
init script for OneSignal
```
oneSignal.setLogLevel(6, 0);
    oneSignal.init(API.config.oneSignalApi, {
      kOSSettingsKeyAutoPrompt: true,
      kOSSettingsKeyInFocusDisplayOption: 0,
    });
```

nothing is logging for ids, looks like the function is not being triggered


this occurred when I moved from 59.8 to 61.4, is there any linking stuff I am missing ?? (the linking was removed for 3.4.2 as I remember )

**Comment by onisaint** [comment]
1. unlink
2. remove node_modules
3. ./gradlew clean
4. yarn install
5. link again

solved !!!
