### ISSUE TITLE
Error 3.5.0 OneSignal-inAppMessageClicked is not a supported event type for RCTOneSignalEventEmitter

### ISSUE THREAD

**Issue by lenis96** [OneSignal/react-native-onesignal#900]
**Description:**

I have this error OneSignal-inAppMessageClicked is not a supporter event type for RCTOneSignalEventEmitter
![image](https://user-images.githubusercontent.com/8357209/68682958-faf43200-0533-11ea-820b-2472f8a25219.png)
I update de veersion from 3.2.8 to 3.5.0
I use react-native 0.57.5
I searched and said that with this version dont have problem

**Environment**

"react-native": "0.57.5",
I put the sdk with npm -->

**Steps to Reproduce Issue:**

  only update from react-native-onesignal from 3.2.8 to 3.5.0

This link said that I have to use the last version and dont work for me
https://github.com/OneSignal/react-native-onesignal/issues/812

**Comment by rgomezp** [comment]
You're on an old version of the SDK so make sure you update correctly. Try:

unlink
remove node_modules
yarn install
link again

**Comment by lenis96** [comment]
Already the project work the problem was that I have to add the CoreGraphics and WebKit Framework, this issue help me https://github.com/OneSignal/react-native-onesignal/issues/861
