### ISSUE TITLE
Building Android Fails

### ISSUE THREAD

**Issue by CarterBland** [OneSignal/react-native-onesignal#902]
**Description:**

Running `./gradlew installDebug` fails with this error `error: cannot find symbol
import com.onesignal.OneSignal.OutcomeCallback;`

**Environment**

react-native: 0.59
expo: 35.0.0 (ejected)
react-native-onesignal: 3.5.0

**Steps to Reproduce Issue:**

`npm install`
`npx jetify`
`cd android && ./gradlew installDebug`

**Anything else:**

`
> Task :react-native-onesignal:compileDebugJavaWithJavac FAILED
/Users/carterbland/apps/signing-day-sports-native-app/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:31: error: cannot find symbol
import com.onesignal.OneSignal.OutcomeCallback;
                              ^
  symbol:   class OutcomeCallback
  location: class OneSignal
/Users/carterbland/apps/signing-day-sports-native-app/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:38: error: cannot find symbol
import com.onesignal.OutcomeEvent;
                    ^
  symbol:   class OutcomeEvent
  location: package com.onesignal
/Users/carterbland/apps/signing-day-sports-native-app/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:485: error: cannot find symbol
      OneSignal.sendOutcome(name, new OutcomeCallback() {
                                      ^
  symbol:   class OutcomeCallback
  location: class RNOneSignal
/Users/carterbland/apps/signing-day-sports-native-app/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:498: error: cannot find symbol
      OneSignal.sendUniqueOutcome(name, new OutcomeCallback() {
                                            ^
  symbol:   class OutcomeCallback
  location: class RNOneSignal
/Users/carterbland/apps/signing-day-sports-native-app/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:511: error: cannot find symbol
      OneSignal.sendOutcomeWithValue(name, value, new OutcomeCallback() {
                                                      ^
  symbol:   class OutcomeCallback
  location: class RNOneSignal
Note: /Users/carterbland/apps/signing-day-sports-native-app/node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors

> Task :react-native-reanimated:compileDebugJavaWithJavac
Note: /Users/carterbland/apps/signing-day-sports-native-app/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
`

**Comment by rgomezp** [comment]
Howdy,
Can you please check that React Native linked the library correctly?
See our [docs](https://documentation.onesignal.com/docs/troubleshooting-react-native#section-check-link-step-worked-correctly) for more info

**Comment by CarterBland** [comment]
@rgomezp Hola, I ran `react-native link` and confirmed that my MainApplication was set up correctly, surely if that was the issue the error would be different?

**Comment by rgomezp** [comment]
The errors simply indicate that while the OneSignal SDK was updated correctly, but not the underlying native SDK it relies on

**Comment by CarterBland** [comment]
@rgomezp I fixed it, I updated my build.gradle.

**Comment by cfmitrah** [comment]
@CarterBland  , could you share how you fixed this issue. I am struck in this issue & not able to proceed further.

**Comment by CarterBland** [comment]
@cfmitrah It had something to do with the order in build.gradle, but I can't remember further.

**Comment by santiagomartinez** [comment]
For me the project was building fine and one day it stopped building with this error.
Just in case it is useful to someone, I fixed this after removing gradle cache (~/.gradle/cache on OSX).

**Comment by roysG** [comment]
Same issue, any update?

react-native-cli: 2.0.1
react-native: 0.58.3
"react-native-onesignal": "^3.4.2",

**Comment by othree** [comment]
@santiagomartinez Thanks, I followed your suggestion and it works. But the path is `~/.gradle/caches/`
