### ISSUE TITLE
ios/Pods/Target Support Files/react-native-onesignal/react-native-onesignal-dummy.m'

### ISSUE THREAD

**Issue by ldco2016** [OneSignal/react-native-onesignal#903]
**Description:**

I recently cloned a React Native 60.4 application with `"react-native-onesignal": "3.4.2",` into a MacBook Pro Mojave. I ran `npm install`. Then I ran `react-native run-ios --simulator="iPad Air 2" --verbose` and whereas the build is succeeding on an Xcode 10.2, it fails on this Xcode 11.1 with the following error:

```
/ios/Pods/Target Support Files/react-native-onesignal/react-native-onesignal-dummy.m'
clang: error: no input files
```

**Environment**

**Steps to Reproduce Issue:**

1. `git clone https://github.com/ldco2016/RNapp`
2. `npm install`
3. `react-native run-ios --simulator="iPad Air 2" --verbose`

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Howdy,
I'm really not sure where that file is coming from. You can look in this repository and see that it doesn't even exist. Any idea where it is coming from?

**Comment by ldco2016** [comment]
@rgomezp , this is really strange. In `Target Support Files/` I do not see a `react-native-onesignal` library, but in `Podfile.lock` I do see:

```
- react-native-onesignal (3.4.2):
   - OneSignal (= 2.11.2)
   - React (< 1.0.0, >= 0.13.0)
```

but in my `Podfile` itself, there is no `pod` for `react-native-onesignal`, should there be? I assumed with autolinking, we did not need it there. Its just strange its asking for a file that does not exist in your repo.

**Comment by rgomezp** [comment]
Howdy, it should be there. It doesn't hurt to run `react-native link react-native-onesignal` to make sure. Cheers

**Comment by ldco2016** [comment]
@rgomezp, it should be where? I looked in this very repo and I did not find a `react-native-onesignal-dummy.m'`, why would I expect to find it on my own project? Also, I am running React Native version 60.4 which now has autolinking, but you are asking me to run `react-native link react-native-onesignal`. I thought the point of autolinking is that we do not have to do that anymore. Furthermore, when I tried what you suggested I got another error saying `Linking "react-native-onesignal" failed.` I am still unclear as to why I would have to run that command for React Native 0.60.4

**Comment by rgomezp** [comment]
> looked in this very repo and I did not find a react-native-onesignal-dummy.m', why would I expect to find it on my own project?  

I'm saying there should be a pod for `react-native-onesignal` such as [here](https://github.com/OneSignal/react-native-onesignal/blob/master/examples/RNOneSignal/ios/Podfile#L39). 

>I am still unclear as to why I would have to run that command for React Native 0.60.4

In theory, you shouldn't need to (you're right) as this is supposedly done automatically. However, I have seen this fail sometimes. I'm saying it doesn't hurt to re-run the command

**Comment by rgomezp** [comment]
Closing due to no response
