### ISSUE TITLE
'onReceived' not fired when app is closed

### ISSUE THREAD

**Issue by OriAmir** [OneSignal/react-native-onesignal#904]
Hi, I follow this steps to initialise my app on iOS:
https://documentation.onesignal.com/docs/react-native-sdk-setup

The event 'onReceived' trigger well when my app is open / in background **BUT** the point that I have to do something in background when the push notification sent to my app .

The problem is when my app is **close**:

If my phone is not closed ( screen on but the app is closed, not in background) so it's actually 'turn on' the app and the first component but the event 'onReceived' not fired.
If my phone is **closed** and the app is closed so nothing happens on background  - app not getting started and of course event 'onReceived' not fired.

**Environment**
    ios 13
    "react-native": "0.61.4",
    "react-native-onesignal": "^3.5.0",

Thanks all!

**Comment by rgomezp** [comment]
The purpose of this event is not for starting background tasks. For this, take a look at our [docs here](https://documentation.onesignal.com/docs/silent-notifications)

**Comment by OriAmir** [comment]
@rgomezp tnx for your help but I still can't get the notification.

From your documentation :


```
App Force-killed / Swiped Away OneSignal Non-Native SDK (Cordova, Unity, React Native, etc.),
will need to handle this within the NSE using native code and send the data to your app to handle.
```
So in **NotificationService.m** , that I just copy from the react-native documentation(https://documentation.onesignal.com/docs/react-native-sdk-setup) I just try to log when I receive a notification inside function 'didReceiveNotificationRequest' in the same file.
*I set 'CONTENT AVAILABLE' and 'MUTABLE CONTENT' to true as wrote in function doc also

```
- (void)didReceiveNotificationRequest:(UNNotificationRequest *)request withContentHandler:(void (^)(UNNotificationContent * _Nonnull))contentHandler {
    self.receivedRequest = request;
    self.contentHandler = contentHandler;
    self.bestAttemptContent = [request.content mutableCopy];
    
    [OneSignal didReceiveNotificationExtensionRequest:self.receivedRequest withMutableNotificationContent:self.bestAttemptContent];

    // DEBUGGING: Uncomment the 2 lines below and comment out the one above to ensure this extension is excuting
    //            Note, this extension only runs when mutable-content is set
    //            Setting an attachment or action buttons automatically adds this
     NSLog(@"Running NotificationServiceExtension");
     self.bestAttemptContent.body = [@"[Modified] " stringByAppendingString:self.bestAttemptContent.body];
    
    self.contentHandler(self.bestAttemptContent);
}

```

First, It never logs the message, even if the app is open/in background. it's log here just on react-native side but not in the Xcode side.

If my app is closed so nothing happens and I get also error from Xcode when I close my app:

```
Can't end BackgroundTask: no background task exists with identifier 3 (0x3), or it may have already been ended. Break-in UIApplicationEndBackgroundTaskError() to debug.
Connection 9: encountered error(1:53).
Connection 9: received failure notification.
nw_connection_copy_connected_local_endpoint [C9] Connection has no local endpoint .
```

Did I need to implement something else in NotificationService.m or in AppDelegate.m ?

Thanks again

**Comment by rgomezp** [comment]
I'm not quite sure why your service extension isn't working correctly. Please double check you followed the directions closely. Read our docs on [background notifications](https://documentation.onesignal.com/docs/silent-notifications)

For the second error, this seems to be an iOS related issue: https://stackoverflow.com/questions/23882495/cant-endbackgroundtask-no-background-task-exists-with-identifier-or-it-may-ha

**Comment by OriAmir** [comment]
@rgomezp I success to debug and console inside 'didReceiveNotificationRequest' when my app is closed,  but now what ? I can I tell my react native app that I receive something and to start do something in background...?how can I implement that in native objective c?

I see this issue : https://github.com/OneSignal/react-native-onesignal/issues/312 but can't understand from comment : it's have to be VOIP notification and i must implement everything in myself?did you have any example ?

Tnx a lot for your help

**Comment by OriAmir** [comment]
@rgomezp I now implement VOIP notifications 
https://documentation.onesignal.com/docs/voip-notifications
I follow all instructions. I send a message and on the platform, I see 'delivered' but actually function 'didReceiveIncomingPushWithPayload' never called(debug and release mode)
same like:https://github.com/OneSignal/OneSignal-iOS-SDK/issues/553


tnx

**Comment by rgomezp** [comment]
Yes, we are working to resolve VOIP on new versions of iOS

**Comment by Dirui2** [comment]
I have the same problem and I was informed by support that the problem with voip had been fixed.
Just send "apns_push_type_override = voip"
We need an urgent solution to this problem.

**Comment by OriAmir** [comment]
@Dirui2 Tnx,
Can you please tell me how you implement the voip in react-native? I just use react native call keep library - https://github.com/react-native-webrtc/react-native-callkeep 
I add the necessary changes for my AppDelegate.m (for ios 13) but nothing happened ( also when I sent  "apns_push_type_override = voip"). I think that my problem is on my  AppDelegate.m and on on my oneSignel configuration.

**Comment by rarira** [comment]
I have same problem
rn: 0.61.5
react-native-onesignal: both 3.6.1 & 3.6.2
ios: 13.3

I setup correctly as doc guided,
my background notification with both content-available and mutable-content true fires 'received' event when app is in active but not in background

badge works successfully but when in background I had same error:
```
2020-01-13 01:04:14.740242+0900 myapp[46531:552284] VERBOSE: endBackgroundFocusTask called
2020-01-13 01:04:15.491193+0900 myapp[46531:552284] VERBOSE: oneSignalApplicationDidEnterBackground
2020-01-13 01:04:15.661469+0900 myapp[46531:552284] Can't end BackgroundTask: no background task exists with identifier 10 (0xa), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug
```

I thought it worked normally before.. But I don't know what happened..

@rgomezp 
Is a background notification able to fire received event with OneSignalNotificationServiceExtension setup correctly?

**Comment by rgomezp** [comment]
The "received" event only fires when the app is in the foreground. Please see our [docs for more info](https://documentation.onesignal.com/docs/react-native-sdk#section-events-listeners)

**Comment by MBY90** [comment]
hi everyone ,
using onesignal with react native 
having the same problem when app in foreground or background mode notification works fine but when it's closed no notification is received please help me
