### ISSUE TITLE
IOS: Delay requesting push notifications

### ISSUE THREAD

**Issue by yogiben** [OneSignal/react-native-onesignal#91]
Is it possible to choose when to request push notifications?

I've read it's best practice to request only after the user is invested in the app

**Comment by nickw** [comment]
@yogiben It looks like you can alter the method you pasted into `AppDelegate.m` and pass the `autoRegister:false` param:

```
self.oneSignal = [[RCTOneSignal alloc] initWithLaunchOptions:launchOptions appId:@"APP_ID" autoRegister:false];
```

**Comment by spencercarli** [comment]
Yeah after doing what @nickw mentioned you can then call the `registerPushNotifications` whenever it makes sense for your app.

Here's [an example](https://github.com/spencercarli/react-native-onesignal-example/blob/master/App.js#L27). Here's the [AppDelegate.m](https://github.com/spencercarli/react-native-onesignal-example/blob/master/ios/OneSignalExample/AppDelegate.m#L25) as well.

I touched on this part at the [end of a recent blog post](https://medium.com/differential/react-native-push-notifications-with-onesignal-9db6a7d75e1e).

**Comment by yogiben** [comment]
Thanks @spencercarli @nickw
