### ISSUE TITLE
PushToken is always null in iOS 12.0 [Official Repo Example]

### ISSUE THREAD

**Issue by veris-NikhilSrivastava** [OneSignal/react-native-onesignal#910]
**Description:**
I installed react-native-onesignal's example app. Linked it and got it running successfully, but it always has the pushToken as _null_ in iOS.

**Environment**

Platform : "iOS 12.0"
"react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-onesignal": "^3.5.0"

**Steps to Reproduce Issue:**

1. Clone the OneSignal repo and cd into the example folder.
2. Run Yarn install and react-native link react-native-onesignal.
3. On executing _OneSignal.addEventListener('ids', this.onIds);_, this gives pushToken as null.

**Comment by rgomezp** [comment]
Hello,
We just released a new version of the example app. Can you please test again?

**Comment by veris-NikhilSrivastava** [comment]
Hi @rgomezp 
Yes I tried the new version 3.6.0. The push token is still coming null. The first time the _/players_ API is hit, device ID comes as null in response.

**Comment by veris-NikhilSrivastava** [comment]
It always gives me this error "Apns Delegate Never Fired" in the dashboard, when building the debug/release app through Xcode(11.2.1).
But idk why it works great when the app is distributed through TestFlight.

**Comment by rgomezp** [comment]
Howdy,
It sounds like you may not have set up your certificates correctly. 
Please see our instructions [here](https://documentation.onesignal.com/docs/generate-an-ios-push-certificate) and make sure you select both Production AND Sandbox

**Comment by veris-NikhilSrivastava** [comment]
Hey @rgomezp ,
These certificates are configured. I've been using this for the past three months. And it was working great!
So, can you please tell me what changes are there from your end due to which maybe I need to reconfigure the certs?

**Comment by ryanhobsonsmith** [comment]
Hi @rgomezp, I'm also experiencing the same issue on iOS (token is always null / seeing Apns Delegate Never Fired in dashboard). Works great when I'm running on Android though. 

I've tried recreating the certificates several times (both manually and through the automated tool you provide). Is there anything I can do to help debug or otherwise verify that it is the certificate causing the issue? Been all through your troubleshooting docs last couple days to no success.

**Comment by ryanhobsonsmith** [comment]
Also, not sure if this is related or not, but after going through your automated certificate wizard, the final instructions in that tool for "Refreshing your provisioning profile" ([here is the link](https://spin.atomicobject.com/2013/11/21/xcode-5-team-provisioning-profiles/)), Seem very out of date and I couldn't follow them directly. I'm using an automatic signing in xcode and feels like it picked things up just fine without any kind of manual refresh though.

**Comment by ryanhobsonsmith** [comment]
Turns out was user error on my end. In xCode, while I did have the background mode -> remote notifications capability enabled, I had forgotten to explicitly add the Push Notification capability. 

The latest xcode UI makes it easier to forget this since it's different from the one shown in the onesignal docs, and in this new UI, the capabilities don't show up unless they are explicitly added. 

Probably would have caught this very quickly in the old UI where each capability was always explicitly shown with it's own on/off switch. Hopefully this will help you as well @veris-NikhilSrivastava.

**Comment by rgomezp** [comment]
Glad to hear you were able to resolve @ryanhobsonsmith 

@veris-NikhilSrivastava , could you please respond if this is the same issue you were having?

**Comment by veris-NikhilSrivastava** [comment]
@rgomezp this is not the issue I'm facing. And yes, I have the Push Notification capability added.
 As I mentioned, it works flawless in the production version when distributed through TestFlight or AppStore. But it does not works in debug or release build distributed through xCode.

**Comment by varuncarkey** [comment]
Fixed my issue by removing the call to the configure function. I was having the same issue when I updated to the latest version in order to support iOS 13. Was getting null for pushToken and the OneSignal dashboard Users section was displaying "Apns Delegate Never Fired". Turns out I never ended up removing the configure function that had been deprecated/removed from the SDK in one of the versions between my previous one and the latest.  Once I removed it, everything started working fine.

**Comment by rgomezp** [comment]
@veris-NikhilSrivastava , please try @varuncarkey 's solution. Thanks for that suggestion!

**Comment by veris-NikhilSrivastava** [comment]
@rgomezp  @varuncarkey Thanks. It worked!

**Comment by NikitaNeganov** [comment]
I have the same issue on IOS - pushToken is always null and APNS delegate never fired in the dashboard. Testing on iPhone Xr ios 13.3.1
System info
```
System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 31.15 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
```
`"react-native-onesignal": "3.7.2"`

Steps (all per docs):
1) `yarn add react-native-onesignal && react-native-link react-native-onesignal` (at first I relied on autolinking, but after several attemps tried this as well)
2) `cd ios && pod install && cd..`
Podfile: one-signal only added when linked through react-native link
```
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

def add_flipper_pods!
  version = '~> 0.33.1'
  pod 'FlipperKit', version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', version, :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitReactPlugin', version, :configuration => 'Debug'
end

# Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end
end

target 'eca' do
  # Pods for eca

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"

  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'

  pod 'react-native-ble-plx', :path => '../node_modules/react-native-ble-plx'

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  target 'ecaTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  add_flipper_pods!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'eca-tvOS' do
  # Pods for eca-tvOS

  target 'eca-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

```

3) Add the following code to App.js
```
React.useEffect(() => {
    OneSignal.init('MY-APP-ID', {});

    OneSignal.addEventListener('received', onReceive);
    OneSignal.addEventListener('opened', onOpen);
    OneSignal.addEventListener('ids', onIds);

    return () => {
      OneSignal.removeEventListener('received', onReceive);
      OneSignal.removeEventListener('opened', onOpen);
      OneSignal.removeEventListener('ids', onIds);
    };
  }, []);
```

It initializes correctly, but pushToken is always null and APNS delegate has never fired
