### ISSUE TITLE
Cannot Dismiss In-App Alert, will trigger onOpened() every time

### ISSUE THREAD

**Issue by hanshen-ng** [OneSignal/react-native-onesignal#915]
**Description:**

Hi, are there any ways to dismiss an in-app alert? I want to provide option to user where they can dismiss the alert via cancel or 'x' button, as well as acting on the alert by the default 'ok' button.

**Environment**
 1. react-native-onesignal@3.5.0
 2. react-native@0.60.3

**Comment by rgomezp** [comment]
For banners, you have to swipe it away. For center-modal and full screen, there's an X button you can press. Thanks for your question. Cheers
