### ISSUE TITLE
IOS can't get banner showing in app

### ISSUE THREAD

**Issue by serjbord** [OneSignal/react-native-onesignal#918]
**Description:**
I am trying to show a banner on IOS in the foreground but always have the alert. I tried many variants, but nothing helps me. On Android, all work as need it. Switching between kOSSettingsKeyInFocusDisplayOption: 1, 2 always show alert. 
If set to 0 - it has correct behavior. 

**Environment**
1. React-native-version 0.59
2. React-native-one-signal - 3.6.0

**Steps to Reproduce Issue:**
Initializing code below: 
```
OneSignal.init(ONE_SIGNAL_KEY, {
      kOSSettingsKeyAutoPrompt: true,
      kOSSettingsKeyInFocusDisplayOption: 2,
    })
    OneSignal.inFocusDisplaying(2)
```

**Comment by rgomezp** [comment]
Can you try removing `OneSignal.inFocusDisplaying(2)`?

**Comment by serjbord** [comment]
@rgomezp I tried that before :( the same result

**Comment by rgomezp** [comment]
1. Have you tried updating your react-native version?
2. Would you be able to share your project or a project that reproduces the issue?

**Comment by serjbord** [comment]
1. Yes. I've tried. Not helped.
2. Nope :(  
- It's ejected expo app

I am going to try to reproduce it on a new project and will back here soon.

**Comment by mikechoch** [comment]
How are you sending this notification? Dashboard, API, public method?

**Comment by serjbord** [comment]
HI @mikechoch, we sent this by Dashboard, and API. 
We solved the issue with own custom notification component in foreground.  ( don't have time to test on a new project) :(

**Comment by mikechoch** [comment]
I am unable to reproduce this issue, does this only happen on iOS?

Try removing the param from the init and just use `OneSignal.inFocusDisplaying(2)`.
Also try calling it before and after `init`

**Comment by mikechoch** [comment]
Let me know if this gets the notification to show while iOS app is in foreground

**Comment by rgomezp** [comment]
Appears to be a native issue. Please track this issue in the iOS repository: OneSignal/OneSignal-iOS-SDK#600
