### ISSUE TITLE
there is an alert appear  when I used react-native-onsignal ,it's appeare just for the first time that installed app  on device  and  not  appear  after that

### ISSUE THREAD

**Issue by fatmaRubaie** [OneSignal/react-native-onesignal#919]
**Description:**

(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by fatmaRubaie** [comment]
![image](https://user-images.githubusercontent.com/46133636/70903967-d8f54000-2008-11ea-9ab5-590b401e5526.png)
  how can I avoid this ?

**Comment by rgomezp** [comment]
Please reach out to our support channel at OneSignal.com for assistance
