### ISSUE TITLE
IOS: What needs to happen for device to receive notifications / be registered?

### ISSUE THREAD

**Issue by yogiben** [OneSignal/react-native-onesignal#92]
I've successfully set up Android.

I've tried to do the same for iOS with a production .p12 cert. Seems to be working: I get the prompt and the code runs.

However, the device does not show up in the one signal dashboard.

The app has not yet been submitted to the app store. Does this mean that the device cannot be registered?

**Comment by deepmehtait** [comment]
@yogiben : Make sure you are forking or some how initializing one signal setup function from React Native. Also make sure one signal ID is added in source code of ios.

**Comment by avishayil** [comment]
Seems like an account issue rather than library issue. Either way, i'm tagging @jkasten2 and closing this.
