### ISSUE TITLE
iOS Initialization Parameters in react-native-sdk

### ISSUE THREAD

**Issue by daheeahn** [OneSignal/react-native-onesignal#923]
**Description:**
https://documentation.onesignal.com/docs/react-native-sdk
*iOS Initialization Parameters* in this link , you said 'At the present time, none of these settings are available in the Android SDK.'
When can I use *iOS Initialization Parameters* on Android?
I'm looking forward that this feature will be included in Android someday! :)

**Comment by rgomezp** [comment]
Thanks for your suggestion. We have some big changes coming to the OneSignal initialization API and will consider your request. Cheers

**Comment by daheeahn** [comment]
Thanks!
