### ISSUE TITLE
Option to disable app redirection if inFocusDisplaying(0)

### ISSUE THREAD

**Issue by kelokchan** [OneSignal/react-native-onesignal#924]
**Description:**

We need an option to disable url redirection directly whenever `inFocusDisplaying` is `0`. I have deep linking setup using `react-navigation` and I do not want the navigation to happen by itself whenever the app is in foreground. I do not want to use the `Linking` approach to solve this issue either as it is a duplication to the existing deep linking implementation found in `react-navigation`

**Environment**

**Steps to Reproduce Issue:**

1. POST notification to targeted device when the app is in the foreground
2. App will navigate to the page specified in the notification url without user interaction

**Comment by rgomezp** [comment]
If you do not want to link to any page or url, you can add ?_osp=do_not_open to the end of a URL like this https://yoursite.com/page?_osp=do_not_open as the launch url, this will prevent the push from going to any url upon click and will just dismiss the push.

If you only have mobile app users, we recommend deep linking with [Additional Data](https://documentation.onesignal.com/docs/links#section-deep-linking).

**Comment by kelokchan** [comment]
Actually, I do need the launch url to work when the app is killed / not in the background. And I do not want it to navigate itself when the app is in the foreground. Is that not possible at the moment?

**Comment by rgomezp** [comment]
This isn't. It does seem like something you could do yourself however. Simply use the additional data to pass the destination to your routing mechanism if and only if the app was previously just killed/not in the foreground.
