### ISSUE TITLE
Mac Catalyst + RN

### ISSUE THREAD

**Issue by jasonivers** [OneSignal/react-native-onesignal#925]
**Description:**

When I try to build for Mac Catalyst, I get an error:

```
in /path/to/app/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-x86_64-master.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, file '/path/to/app/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'
```

I have updated to the latest version of react-native-onesignal (3.3.3), and updated my pods (currently 2.12.3).  According to this https://onesignal.com/blog/onesignal-supports-mac-catalyst-build/ 2.12.x should support Catalyst.

Am I missing something?

**Environment**

1. react-native-onesignal package is 3.3.3
1. Pod is 2.12.3
1. Added via  yarn, then pod install --update-repo

**Steps to Reproduce Issue:**

1. Attempt to build project including react-native-onesignal for Mac Catalyst

**Comment by rgomezp** [comment]
Howdy,
Please see this issue https://github.com/OneSignal/OneSignal-iOS-SDK/issues/534#issuecomment-563431891

**Comment by jasonivers** [comment]
I tried that, but setting it to x86_64h causes other (necessary) things to not compile, like DoubleConversion.  Unless I'm missing something else, that solution will not work with React Native.

**Comment by rgomezp** [comment]
I was able to reproduce. This may take some time to find a solution that works across all platforms. Thanks for your patience.

P.s. the latest version of the SDK is not 3.3.3 so just make sure you are updating correctly please

**Comment by ninacoder-info** [comment]
Same here, x86_64h make other library stop combine, is there anyway to disable onesignal on mac os and keep it working on ios?

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience y'all.

Please try the following:
1. Update your `react-native-onesignal` dependency to use `OneSignal/react-native-onesignal#ea3d2b521c`
2. Rebuild your project's node-modules
3. `cd ios && pod install --repo-update`

as so in your `package.json`:
```json
"dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-onesignal": "OneSignal/react-native-onesignal#ea3d2b521c"
  },
```

Cheers

**Comment by rgomezp** [comment]
Closing due to no response.
