### ISSUE TITLE
React Native 0.61.1 Can't include OneSignal Plugin For Android

### ISSUE THREAD

**Issue by osmannbozkurt** [OneSignal/react-native-onesignal#930]
Hi, 
I'm try to include OneSignal in my project but always same error occured.  
When Project sync with android the following error occured : 
**ERROR: The module 'react-native-onesignal' is an Android project without build variants, and cannot be built.
Please fix the module's configuration in the build.gradle file and sync the project again.** 

When run react-native run-android command the following error occured : 

 **com.geektime.rnonesignalandroid does not exist
import com.geektime.rnonesignalandroid.ReactNativeOneSignalPackage;**

My App/build.gradle code : 
`
 buildscript {
    repositories {
        maven { url "https://plugins.gradle.org/m2/" } // Gradle Plugin Portal 
    }
    dependencies {
        classpath "gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.1, 0.99.99]"
    }
}

apply plugin: "com.onesignal.androidsdk.onesignal-gradle-plugin"

  apply plugin: "com.android.application"

import com.android.build.OutputFile
 
project.ext.react = [
    entryFile: "index.js",
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"
 
def enableSeparateBuildPerCPUArchitecture = false
 
def enableProguardInReleaseBuilds = false
 
def jscFlavor = "org.webkit:android-jsc:+"
 
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {       
        applicationId "com.argonreact"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"     
       
        //   manifestPlaceholders = [onesignal_app_id: "e51c7ee9-c7da-493b-b1cc-bca05da36c74",
        //                         onesignal_google_project_number: "REMOTE"] 
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file("debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }

    packagingOptions {
        pickFirst "**/armeabi-v7a/libc++_shared.so"
        pickFirst "**/x86/libc++_shared.so"
        pickFirst "**/arm64-v8a/libc++_shared.so"
        pickFirst "**/x86_64/libc++_shared.so"
        pickFirst "**/x86/libjsc.so"
        pickFirst "**/armeabi-v7a/libjsc.so"
    }

}

dependencies { 

    implementation project(":react-native-vector-icons")
    implementation project(":react-native-gesture-handler")
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
 

    if (enableHermes) {
      def hermesPath = "../../node_modules/hermesvm/android/";
      debugImplementation files(hermesPath + "hermes-debug.aar")
      releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
      implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into "libs"
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
`

My bluild.gradle Code : 

` 
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
     
 
     }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.1")
   
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
    }
}
//`

**Comment by jkasten2** [comment]
@osmanbozkurt02 I recommend removing OneSignal from your project and try re-adding it as it seems it didn't get linked. React Native should link automatically but I recommend also running the following to link manually.
`react-native link react-native-onesignal`

Please also see our example project for reference
https://github.com/OneSignal/react-native-onesignal/tree/master/examples/RNOneSignal

**Comment by rgomezp** [comment]
Closing due to no response
