### ISSUE TITLE
IOS crashes in production

### ISSUE THREAD

**Issue by alex-trofimov** [OneSignal/react-native-onesignal#931]
Hi!
**Description:**
App's ios versions work fine in the simulator but the builds crash on devices right after the splash screen.
Crash logs make me think that this package has something to do with it.
Sidenote: android doesn't crash, notifications work just fine.

**Environment**
```
    "react-native": "0.61.5",
    "react-native-onesignal": "^3.6.1",
```
SDK was installed according to official instruction.
I tried removing the package and all its traces completely and installing fresh but the problem persists.

**Crash log:**
The crash log is partially symbolicated
[symbolicated.txt](https://github.com/OneSignal/react-native-onesignal/files/4022225/symbolicated.txt)

Here are missing pieces of stack trace symbolicated with `atos` command:
```
0 0x000000010012b98c (in Dev-Footinho)
1 0x00000001000060a4 (in Dev-Footinho)
4 0x0000000100131d90 (in Dev-Footinho)
5 0x0000000100001bd0 (in Dev-Footinho)
6 0x00000001000027a8 (in Dev-Footinho)
10 0xfffbb610 (in Dev-Footinho)
11 0xfffbc184 (in Dev-Footinho)
12 0xfff68464 (in Dev-Footinho)
13 0xfff68e58 (in Dev-Footinho)
14 0xfff72340 (in Dev-Footinho)
15 +[OneSignal addSubscriptionObserver:] (in Dev-Footinho) + 192
16 +[OneSignal setSubscription:] (in Dev-Footinho) + 136
```

Any ideas what it could be?

**Comment by jkasten2** [comment]
@Legi0n1138 Thanks for the stacktrace and log however we need a few more details to pinpoint the issue.

It looks like there are calls to` addSubscriptionObserver` and `setSubscription`. Can you provide the exact code that is being called that reproduces the crash? Does removing either of these calls prevent the crash?

**Comment by rgomezp** [comment]
Closing due to no response
