### ISSUE TITLE
userSubscriptionEnabled always set to false when restart iOS app

### ISSUE THREAD

**Issue by rachapong** [OneSignal/react-native-onesignal#934]
**Description:**                                                                                    
userSubscriptionEnabled always reset to false when restart an app.                                      
                                                                                                    
**Environment**                                                                                     
1. react-native-onesignal 3.6.2                                                                     
2. react-native 0.61.5                                                                              
3. react 16.9.0                                                                                     
4. iOS 13.3                                                                                         
                                                                                                    
**Steps to Reproduce Issue:**
I think the best way is to reproduce with an example comes with the package.                                       
1. Download react-native-onesignal                                                                  
2. `cd react-native-onesignal/examples/RNOneSignal`                                                 
3. `yarn`                                                                                           
4. Configure a proper key in OneSignal.init()                                                       
e.g.                                                                                                
`OneSignal.init('ce8572ae-ff57-4e77-a265-5c91f00ecc4c', ...`                                        
5. Add the following snippets inside `<ScrollView>` in App.js to allow subscription setting.          
```
          <View style={{flexDirection: 'row', overflow: 'hidden'}}>
            <View style={styles.buttonContainer}>
                <Button
                  style={styles.button}
                  onPress={() => {OneSignal.setSubscription(true)}}
                  title="Subscription:true"
                  color={this.state.buttonColor}
                />
            </View>
            <View style={styles.buttonContainer}>
                <Button
                  style={styles.button}
                  onPress={() => {OneSignal.setSubscription(false)}}
                      title="Subscription:false"
                  color={this.state.buttonColor}
                />
            </View>
          </View>                                                                                                 
```
6. `react-native run-ios`
7. Click on `Subscription:true` button
8. Click on `Print Subscription State` to check the userSubscriptionEnabled value => This should show `true`
9. Close app and make sure that you terminate it (no background running)
10. Re-Open the application
11. Click on `Print Subscription State`. At this state, the userSubscriptionEnabled value incorrectly shows `false` !! 

**Expected Behavior**
I would expect the userSubscriptionEnabled value keep as `true` after app restart.

**Others**
If I roll-back react-native-onesignal to 3.5.0, it seems to work fine as expected.

**Comment by rgomezp** [comment]
Thanks for the info. May be related to #545 

Thanks for your patience while we investigate.

**Comment by rgomezp** [comment]
This is fixed. Thanks
