### ISSUE TITLE
Could not find com.google.android.gms:play-services-ads-identifier:12.0.1

### ISSUE THREAD

**Issue by TreemboLuisDev** [OneSignal/react-native-onesignal#938]
**Description:**

Hi, im having trouble building with bundleRelease my Android production file, its giving this error.
<img width="727" alt="Screen Shot 2020-01-17 at 16 08 08" src="https://user-images.githubusercontent.com/19478245/72649694-f6893280-3943-11ea-8566-61bdf188c9b3.png">
But I cant find the 12.0.1 version on the maven repos, only 15.0.0 and forward. Any suggestions to how I can fix this? Running on RN.60, SDK 29. Latest OneSignal version 3.6.2. The error says required by OneSignal.

**Comment by jkasten2** [comment]
@R8Manzo Can you copy the log here? There is a section "Required by:" they should point out the dependency chain that is leading to the version result.

**Comment by TreemboLuisDev** [comment]
Here is the log, sorry for not responding along the weekend, I was away from the city.

`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.gms:play-services-ads-identifier:12.0.1.
     Searched in the following locations:
       - file:/Users/macbook/.m2/repository/com/google/android/gms/play-services-ads-identifier/12.0.1/play-services-ads-identifier-12.0.1.pom
       - file:/Users/macbook/.m2/repository/com/google/android/gms/play-services-ads-identifier/12.0.1/play-services-ads-identifier-12.0.1.jar
       - file:/Users/macbook/treembo-app-v1/node_modules/react-native/android/com/google/android/gms/play-services-ads-identifier/12.0.1/play-services-ads-identifier-12.0.1.pom
       - file:/Users/macbook/treembo-app-v1/node_modules/react-native/android/com/google/android/gms/play-services-ads-identifier/12.0.1/play-services-ads-identifier-12.0.1.jar
       - file:/Users/macbook/treembo-app-v1/node_modules/jsc-android/dist/com/google/android/gms/play-services-ads-identifier/12.0.1/play-services-ads-identifier-12.0.1.pom
       - file:/Users/macbook/treembo-app-v1/node_modules/jsc-android/dist/com/google/android/gms/play-services-ads-identifier/12.0.1/play-services-ads-identifier-12.0.1.jar
       - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads-identifier/12.0.1/play-services-ads-identifier-12.0.1.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads-identifier/12.0.1/play-services-ads-identifier-12.0.1.jar
       - https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/12.0.1/play-services-ads-identifier-12.0.1.pom
       - https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/12.0.1/play-services-ads-identifier-12.0.1.jar
       - https://jitpack.io/com/google/android/gms/play-services-ads-identifier/12.0.1/play-services-ads-identifier-12.0.1.pom
       - https://jitpack.io/com/google/android/gms/play-services-ads-identifier/12.0.1/play-services-ads-identifier-12.0.1.jar
     Required by:
         project :app > project :react-native-onesignal > com.onesignal:OneSignal:3.12.5

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
`

**Comment by TreemboLuisDev** [comment]
Found the problem, another dev in my team added this code a long time ago when we were at React 0.54, deleting the configurations.all {...} did the trick.

`allprojects {
    repositories {
        configurations.all {
            resolutionStrategy.eachDependency { DependencyResolveDetails details ->
                def requested = details.requested
                if (requested.group == 'com.google.android.gms') {
                    details.useVersion '12.0.1'
                }
                if (requested.group == 'com.google.firebase') {
                    details.useVersion '12.0.1'
                }
            }
        }
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}`
