### ISSUE TITLE
How can I add an action button direct reply?

### ISSUE THREAD

**Issue by wolrd** [OneSignal/react-native-onesignal#939]
How can I add an action button direct reply?
For example, as in WhatsApp, Telegram and etc.

I use React Native.

**Comment by wolrd** [comment]
???

**Comment by rgomezp** [comment]
You can find our documentation on Action Buttons here: https://documentation.onesignal.com/docs/action-buttons

**Comment by wolrd** [comment]
@rgomezp I saw. And I need Reply Button with input. Do you have this feature?
