### ISSUE TITLE
IOS install not success!

### ISSUE THREAD

**Issue by agumack** [OneSignal/react-native-onesignal#94]
Hey,

I have problem when install onesignal for ios. 
I don't know how fixed it .

Thank so much!
<img width="240" alt="screen shot 2016-10-20 at 1 33 41 pm" src="https://cloud.githubusercontent.com/assets/19372005/19548660/0e0504ea-96ca-11e6-9297-c4abe7457201.png">
<img width="227" alt="screen shot 2016-10-20 at 1 35 42 pm" src="https://cloud.githubusercontent.com/assets/19372005/19548679/22b1f0c4-96ca-11e6-8b53-6728c7965dbe.png">

**Comment by bucketclan** [comment]
Have you installed cocoa pods?

Check this [link](https://github.com/geektimecoil/react-native-onesignal/issues/59).

**Comment by spencercarli** [comment]
I had a similar issue as well. Ended up needing to remove the tests block from my Podfile so that it looked like this.

```
target 'OneSignalExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OneSignalExample
  pod 'OneSignal', '~> 1.13.3'
```

[source](https://github.com/spencercarli/react-native-onesignal-example/blob/master/ios/Podfile)

**Comment by arshavinho** [comment]
Hi,
same for me, and after tried with the file from @spencercarli i got more failed line:

![screen shot 2016-10-29 at 02 16 33](https://cloud.githubusercontent.com/assets/1016441/19825773/d9bf4dac-9d7d-11e6-9ff4-4a7a6c38b489.png)

xcode 8.1

**Comment by avishayil** [comment]
Let us know if you have any more problems.

**Comment by avishayil** [comment]
Another suggestion:
- Remove the `target 'AwesomeProjectTests' do` block from your Podfile.

**Comment by therahuls1ngh** [comment]
after solving that it shoots this
Cannot find protocol declaration for 'OSSubscriptionObserver'

**Comment by karamat** [comment]
Getting this error, any idea how it is solved?
