### ISSUE TITLE
Is executing same trigger show IAM again ?

### ISSUE THREAD

**Issue by rajatgalav** [OneSignal/react-native-onesignal#940]
I want to show messages to user every month. So before buying the onesignal inapp purchase i am testing it on my device. I am trying to add the same trigger after removing it.

`OneSignal.addTrigger("level", true);`

After it sets to true. it shows a in app message which has a button to remove the level key.

`OneSignal.removeTriggerForKey("level");`

So if i execute addTrigger command again will it work ? If not how can i achieve message every month condition ?

**Comment by mikechoch** [comment]
Showing IAMs more than once is a feature on our product path, going to close this as with our SDK there is no way to show an IAM more than once.
