### ISSUE TITLE
Users not visible on dashboard from iOS 

### ISSUE THREAD

**Issue by a7urag** [OneSignal/react-native-onesignal#942]
**Description:**
No users visible on dashboard in debug mode on device.

(your description here)

**Environment**

    "react-native": "^0.59.10",
    "react-native-navigation": "^2.18.3",
    "react-native-onesignal": "^3.6.3",

**Steps to Reproduce Issue:**
1. Integrate react native sdk using documentation
2. Onesignal.init('key');

**Anything else:**
No Stacktraces or logs.

**Comment by trin4ik** [comment]
same problem

**Comment by a7urag** [comment]
There is some problem, if you are using react-native less than 0.60. Bridge methods are not getting called. Please update your react-native version and use pod install.

**Comment by trin4ik** [comment]
stupid me ;) i failed with bundle id
