### ISSUE TITLE
How can I add a avatar and a Reply Button to push notification?

### ISSUE THREAD

**Issue by wolrd** [OneSignal/react-native-onesignal#943]
How can I add an **avatar (1)** and a **Reply Button (2)** to push notification?

The Reply Button is in firebase https://stackoverflow.com/questions/52505951/add-replies-to-android-notifications-while-using-react-native-firebase 
(const action = new firebase.notifications.Android.Action('reply', 'ic_launcher', 'Reply'))

I'm creating a chat app. And I need it.

**Image:**
![image](https://user-images.githubusercontent.com/35338702/73064036-58e8b280-3eb1-11ea-99f9-3b15a67815a1.jpeg)

**Comment by rgomezp** [comment]
You need to write native code for this in the [service extension](https://documentation.onesignal.com/docs/service-extensions). This is not a feature we currently offer, though we hope to build it in the future. Thanks for the request.
