### ISSUE TITLE
Issue in setEmail()

### ISSUE THREAD

**Issue by MoeMamdouh** [OneSignal/react-native-onesignal#945]
**Description:**

(your description here)

**Environment**

react-native: 0.61.5
react-native-onesignal: 3.5.0

**Steps to Reproduce Issue:**

1. Install the OneSignal SDK using npm into your project
2. Initialize the SDK in the iOS AppDelegate
3. Use `setExternalUserId` and `setEmail()` 

```

OneSignal.setEmail(email, err => console.log('error in setEmail()', err));
OneSignal.setExternalUserId(id);
```

in Dashboard `id` is stored fine, but the email is always empty.
and error is `undefined`

![Screen Shot 2020-01-27 at 9 07 21 PM](https://user-images.githubusercontent.com/16561058/73205124-088b8200-4149-11ea-9f5a-f850800d610c.png)

**Comment by MoeMamdouh** [comment]
some times log return 
`'error in setEmail()', The operation couldn’t be completed. (OneSignalError error 400.)`

**Comment by MoeMamdouh** [comment]
**Updates**

say user data = `{id: 513478 , email: moe@moe.moee}`

i noticed from Dashabord that oneSignal stores two users with different player ids

-one have the `External id` & `push token` but the `email` is empty:

![Screen Shot 2020-01-27 at 10 43 21 PM](https://user-images.githubusercontent.com/16561058/73212654-55765500-4157-11ea-937c-574eb5348661.png)


-the other have the `email` but `External id`  & `push token`  is empty:
![Screen Shot 2020-01-27 at 10 43 14 PM](https://user-images.githubusercontent.com/16561058/73212653-55765500-4157-11ea-9f80-3bd132c34dd9.png)

**Comment by MoeMamdouh** [comment]
https://documentation.onesignal.com/docs/email-faq#section-email-vs-push

**Comment by dmitrysklyarenko** [comment]
@MoeMamdouh Hi, have you solved the problem with error message `The operation couldn’t be completed. (OneSignalError error 400.)` ?
