### ISSUE TITLE
Different onesignal_app_id depending on environment

### ISSUE THREAD

**Issue by note89** [OneSignal/react-native-onesignal#95]
I would like to have different `onesignal_app_id` depending on environment `production`/`develop`
I want to have this to have a debug environment to not send unexpected notifications to users while developing.

```
    defaultConfig {
        ...
        manifestPlaceholders = [manifestApplicationId: "${applicationId}",
                                onesignal_app_id: "YOUR_ONESIGNAL_ID",
                                onesignal_google_project_number: "YOUR_GOOGLE_PROJECT_NUMBER"]
    }
```

I have tried some different approaches but I'm not really sure what the `manifestPlaceholders` do.
i have something called `buildTypes` and it has three modes (debug, staging, release), can I put something in there ? 
or do something in `AndroidManifest` ? 

Cheers!

**Comment by jkasten2** [comment]
@note89 You can try some of the suggestions in this issue.
https://github.com/OneSignal/OneSignal-Android-SDK/issues/9
