### ISSUE TITLE
Library with Firebase Performance Plugin

### ISSUE THREAD

**Issue by Mani528** [OneSignal/react-native-onesignal#950]
I have build a project with Firebase all features including Firebase Performance Plugin. Now we are trying to make it as Library, While trying to convert from Application to Library we are facing an issue from Firebase as 

ERROR: FirebasePerformancePlugin must only be used with Android application projects. Need to apply the 'com.android.application' plugin with this plugin.

May I know the reason why I am facing this issue. I am excepting a quick reply from the Team.

Thanks in advance

**Comment by ctomichael** [comment]
@Mani528, I'm not sure what this issue has to do with OneSignal.  I think you've posted this in the wrong spot.

**Comment by Mani528** [comment]
Sorry, I am in a wrong spot
