### ISSUE TITLE
compileSdkVersion 29 for android

### ISSUE THREAD

**Issue by rborn** [OneSignal/react-native-onesignal#955]
**Description:**

**This is a question, not a real issue (for now)**

RN moved to version 29 for android tools, any plans to upgrade for this? Right now is downgrading the whole project to 28.

**Environment**
"react-native": "0.61.4",
"react-native-onesignal": "^3.6.4",

Thank you.

**Comment by jkasten2** [comment]
@rborn We will look to see if we can auto detect this in the future.

In the meantime you can set the `compileSdkVersion` gradle variable to `29. See this in our example project on how to do so.
https://github.com/OneSignal/react-native-onesignal/blob/ad67778037b022cf40036603e07c39ca5007397e/examples/RNOneSignal/android/build.gradle#L4-L10

**Comment by rborn** [comment]
@jkasten2 that's my build.gradle

```
buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 23
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = "29.0.3"
        kotlinVersion = "1.3.21"
        detoxKotlinVersion = kotlinVersion
```

And I get this warning 
```
OneSignalPlugin: WARNING: OneSignalPlugin: Downgraded 'com.android.support:29.0.3' -> 28 to prevent compile errors! Recommend updating your project's compileSdkVersion!
```

Thanks

**Comment by jkasten2** [comment]
Thanks, the `OneSignalPlugin` message is from `OneSignal-Gradle-Plugin`. There is an issue open here for it.
https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/110

I believe your settings are applying correctly.

**Comment by rborn** [comment]
@jkasten2 😻

**Comment by cyberassemble** [comment]
https://nullbite.net/
