### ISSUE TITLE
Getting an error: play-services-ads-identifier

### ISSUE THREAD

**Issue by howitworks18** [OneSignal/react-native-onesignal#956]
**Description:**
I seem to be getting an error when building my project in Android (specifically android) related to OneSignal:

` Could not find com.google.android.gms:play-services-ads-identifier:12.0.1.
  Required by:
      project :app > com.onesignal:OneSignal:3.12.7
`

Ive looked at a lot of Stackoverflow and other articles on github and tried their resolutions but none seem to work for me. Im hoping im missing something simple. If anyone has input i would appreciate it. 

**Environment**
React Native v0.58.6
Installed via NPM

**Steps to Reproduce Issue:**
able to reproduce my running `react-native run-ios`

**Comment by mikechoch** [comment]
We did some version range upgrades in our Android SDK (play-services-ads-identifier uses a range from `15.0.0` to `16.0.99` (Pre-Android X). This seems to be dependency conflict and you could solve a lot of these problems by installing our grade plugin.

[Gradle Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin)
