### ISSUE TITLE
[ios 10] js not fully loaded when cold starting app from push notification center

### ISSUE THREAD

**Issue by weixingsun** [OneSignal/react-native-onesignal#96]
Firstly, thanks for this great module, it works for android and ios when app is running / background.
But when I tried to cold start(no app running/background) the app from the notification center , my app stays in a white screen all the time, native code in AppDelegate.m is working:
didFinishLaunchingWithOptions //is triggered
[launchOptions objectForKey:UIApplicationLaunchOptionsRemoteNotificationKey]; //notification data inside
didReceiveRemoteNotification //is triggered

I can see {reload...} popups when shaking it, but my components are not loaded, only white screen.
Any suggestion is highly appreciated, thanks

**Comment by weixingsun** [comment]
after I changed my index.ios.js instead of the components imported, the js is loaded properly now.

**Comment by Adesh** [comment]
@weixingsun can u elaborate it further. I am seeing the white screen after opening the notification when the app is killed.
