### ISSUE TITLE
Replacing previous notifications, e.g. "2 new messages" -> "3 new messages" as one notification

### ISSUE THREAD

**Issue by dancherb** [OneSignal/react-native-onesignal#961]
I'm aware of notification grouping for Android, where all of the individual notifications are kept (e.g. 10+) but put together in one swipeable group.

I'd like to just send the one notification, and then replace this one with any future notifications (with that ID or category). For example:

**"New message from Dan"** -> **"2 new messages from Dan"** -> **"3 new messages from Dan"**

_instead of the current system:_ 

"New message from Dan"

->

**"2 new messages from Dan"**
"New message from Dan"
"New message from Dan"

->

**"3 new messages from Dan"**
"New message from Dan"
"New message from Dan"
"New message from Dan"

---

I've seen this on other apps - is it possible with OneSignal on Android and/or iOS?

**Comment by jkasten2** [comment]
@dancherb Yes, notification replacement instead of grouping can be done with the "Collapse Key/ID" feature with OneSignal. See the following
https://documentation.onesignal.com/docs/how-notifications-work#section-notification-collapsing

**Comment by dancherb** [comment]
Love you Josh

**Comment by dancherb** [comment]
> @dancherb Yes, notification replacement instead of grouping can be done with the "Collapse Key/ID" feature with OneSignal. See the following
> https://documentation.onesignal.com/docs/how-notifications-work#section-notification-collapsing

Do you know if there any clever ways to track and display how many notifications have been collapsed (e.g. "3 new messages") without managing it yourself (e.g. storing when the user's last app open was and keeping track)? @jkasten2

**Comment by jkasten2** [comment]
@dancherb No, nothing built into the OneSignal SDK. When you set a "Collapse Key / Id" it also sets Collapse Key for Android devices on the FCM payload too. What this means if say the devices is offline and you send 2 notifications with they same key, only the most recent notification will ever get to the device when it comes back online.

Is there a reason you would not want to use grouping? As a user, I like to be able expand a group and read the contents without being required to open the app.
