### ISSUE TITLE
Do I need Firebase or Firebase Cloud Messaging to use OneSignal?

### ISSUE THREAD

**Issue by Steffi3rd** [OneSignal/react-native-onesignal#963]
Hi, 

I just follow the tutorial on React Native OneSignal for iOS : https://documentation.onesignal.com/docs/react-native-sdk-setup

I see somewhere on internet that they mentioned Firebase is needed with OneSignal. 

But I don't see it in your tutorial. 

Can OneSignal be replaced totally Firebase Cloud Messaging (and Firebase Notifications) ? 

Thanks 

PS : Is it possible to open a Github Discussions to avoid to open ticket not issues?

**Comment by jkasten2** [comment]
@Steffi3rd You only need to follow the Firebase setup if you need push for Android, you can skip this if you only need iOS push.

For Android push notifications you will need to create a Firebase Project and enter the Firebase Server Key and Firebase Sender ID key values from it with OneSignal. [Follow this guide](https://documentation.onesignal.com/docs/generate-a-google-server-api-key) to create the free Firebase project and how to get them into OneSignal.


`react-native-onesignal` automatically includes the FCM (Firebase Cloud Messaging) dependencies so don't have to follow any of the FCM docs to add it to your app.

PS: Github only has "Issues" but asking questions this way is fine.

**Comment by Steffi3rd** [comment]
@jkasten2 Great! Thanks a lot for this answer!

For now, I only use iOS for my app.
So as you said, I can skip Firebase part because I use iOS. 

So is that mean OneSignal deals directly with APNs (Apple Push Notifications)? 

Or does OneSignal use Firebase « under the hood » to communicate with APNs and my device? 

(I asked that someone told me that OneSignal is slow sometimes to deliver notifications. And I would like to know if it related to FCM...)

**Comment by jkasten2** [comment]
@Steffi3rd Correct, for iOS notifications OneSignal's backend servers connect directly to Apple's APN server to send notifications. Firebase isn't used for OneSignal iOS notifications at all (Client or Server).

For delivery speed we provide a status page the shows API response times and Transactional Delivery Latency.
https://status.onesignal.com/#system-metrics
The round trip time on average is under 100ms when targeting a single device.

I would need more details on what was slow to explain what might have happened in their cases of slow deliveries. However for iOS there are a few things that could result in slower sends in OneSignal's [Delays for notifications on iOS devices:](https://documentation.onesignal.com/docs/notifications-delayed#section-delays-for-notifications-on-i-os-devices) section. If you saw this before please also see points 4, 5, & 6, they were just added today.
