### ISSUE TITLE
User not subscribed (IOS)

### ISSUE THREAD

**Issue by abdallaemadeldin** [OneSignal/react-native-onesignal#966]
**Description:**

notification not working on ios but working well with android.
when i check subscribed users from onesignal dashboard i found android users only

**Environment**

-device: Iphone 5s.
-react native V0.61.5
-react native onesignal V^3.6.5
-use yarn to install package

**Comment by rgomezp** [comment]
Please reach out to our support channel at onesignal.com for help with this issue.
