### ISSUE TITLE
Error in android Build

### ISSUE THREAD

**Issue by alib1989** [OneSignal/react-native-onesignal#970]
hello 
i got error when i try 
react-native run-android
the error is 

node_modules/react-native-onesignal/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java:379: error: cannot find symbol
   public void setExternalUserId(@Nonnull final String externalId, @Nullable final Callback callback) {

My Package JSON is 

{
  "name": "app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.8.1",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/bottom-tabs": "^5.1.0",
    "@react-navigation/drawer": "^5.1.0",
    "@react-navigation/native": "^5.0.8",
    "@react-navigation/stack": "^5.1.0",
    "axios": "^0.19.2",
    "native-base": "^2.13.8",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-elements": "^1.2.7",
    "react-native-fast-image": "^8.1.5",
    "react-native-form-validator": "^0.3.2",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-i18n": "^2.0.15",
    "react-native-image-picker": "^2.3.1",
    "react-native-image-slider-box": "^1.0.12",
    "react-native-onesignal": "^3.7.0",
    "react-native-reanimated": "^1.7.0",
    "react-native-restart": "^0.0.14",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.2.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-vector-icons": "^6.6.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-axios-middleware": "^4.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "@babel/runtime": "^7.8.4",
    "@bam.tech/react-native-make": "^2.0.0",
    "@react-native-community/eslint-config": "^0.0.7",
    "babel-jest": "^25.1.0",
    "eslint": "^6.8.0",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

how can i fix this problem ?

**Comment by fritzfr** [comment]
Same issue.

**Comment by eli0te** [comment]
Same here

**Comment by fritzfr** [comment]
Try pinning the versions like I described here: https://github.com/OneSignal/react-native-onesignal/issues/969#issuecomment-608004061

**Comment by ssrG12** [comment]
> Try pinning the versions like I described here: [#969 (comment)](https://github.com/OneSignal/react-native-onesignal/issues/969#issuecomment-608004061)

I try this but didn't work.

**Comment by jkasten2** [comment]
This is now fixed in the 3.7.1 release
https://github.com/OneSignal/react-native-onesignal/releases
