### ISSUE TITLE
Do I need to follow setup Wordpress if I use React Native as front and Wordpress as API?

### ISSUE THREAD

**Issue by Steffi3rd** [OneSignal/react-native-onesignal#973]
Hi, 

I’m still figure it out how to use OneSignal in my project.

My project is a React Native app only for iOS.
The backend of this app is Wordpress, so I use it as my API.

I saw in OneSignal documentation that there is a tutorial for React Native and another for Wordpress.

I saw that Wordpress is for web notifications. Which is not my case but I only develop for iOS this time.

So do I need to follow Wordpress setup and React Native setup?
Or only React Native Setup or only Wordpress setup ?

Thank you 🙏

**Comment by rgomezp** [comment]
It sounds like you just need to follow the React Native setup if you don't actually have a Wordpress site. I have never heard of someone using Wordpress as a backend only but if it works for you then Godspeed!

**Comment by Steffi3rd** [comment]
@rgomezp Thanks! 

Yes indeed, you can just Wordpress as your API. If you combine it with React Native it's 🎉. 
It's very nice to play with : https://developer.wordpress.org/rest-api/

And if you want to recreate the entire wheel you even use some ready features like "Users / Login / Comments"
