### ISSUE TITLE
What happens with the token when two users are sharing same device?

### ISSUE THREAD

**Issue by Steffi3rd** [OneSignal/react-native-onesignal#974]
Hi,

I would like to know how to handle multiple users one same device.

If the USER A logs out of the app, and another USER B logs in, USER will receive notifications of USER A?

If yes, how to prevent that?
If no, how does it work?

Examples:

1 / This may happen when a user has personal account and profesionnal account.  When he logout and login to another account, it makes sense to « keep » notifications on both because he owns them

2 / This may happen if I would like on my friend phone then I log out, But he still receving notifications for me whereas i’m not using it anymore. What’s is the solution ?

Thanks

**Comment by Steffi3rd** [comment]
Found the answer in docs ✅

https://documentation.onesignal.com/docs/users#section-managing-multiple-users-on-one-device

**Comment by rgomezp** [comment]
Enjoy!
