### ISSUE TITLE
Is there a PHP way to send emails in OneSignal ?

### ISSUE THREAD

**Issue by Steffi3rd** [OneSignal/react-native-onesignal#975]
Hi 

I’m wondering if there is a PHP way now or in the future to send email with the API ?

In looking into docs but not find it (maybe it was forgot)
https://documentation.onesignal.com/v6.0/reference#section-send-email-based-on-one-signal-player-i-ds-create-notification

**Comment by rgomezp** [comment]
Those code snippets are simply examples. The API endpoint doesn't care how it receives the request as long it's a valid HTTP request.

The javascript example will be the closest syntactically to the PHP implementation which you can use as an example to form a typical PHP cURL call.

Hope this helps!

**Comment by Steffi3rd** [comment]
Okay got it! Thanks 👌
