### ISSUE TITLE
Using app-specific passwords doesn't work in Provisionator tool?

### ISSUE THREAD

**Issue by Steffi3rd** [OneSignal/react-native-onesignal#976]
Hi, 

I'm trying to use the Provisionator tool with my Apple ID and `app-specific password` but it looks like my id/password doesn't work : **"Invalid Username or Password."**

Provisionator
- https://onesignal.com/provisionator

Using app-specific passwords
- https://support.apple.com/en-us/HT204397

**Comment by rgomezp** [comment]
It seems we may not support this at the moment in our tool. I will mark this as a feature request. Sorry for the inconvenience!

**Comment by Steffi3rd** [comment]
Yes! It's a shame but I tried the manual tutorial and it worked like a charm 😊 

I really like your documentation. It's very well explain. 

---

The "ONLY" thing I found which was not enough detailed is the part about : 
["Finish Notification Service Extension Setup".](https://documentation.onesignal.com/docs/react-native-sdk-setup#section-finish-notification-service-extension-setup)

_In your Podfile, add the notification service extension:_

```
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end
```

**Problem: We don't know "exactly" where we have to add it in that Podfile.**
I added like 90% on people and I failed (I added it at the end of my main target) 

**Solution: We have to add it outside the main target.** 
I found the solution here : https://github.com/OneSignal/react-native-onesignal/issues/849#issuecomment-538004114 

Maybe you can update to be more precise, please?  🙏

**Comment by rgomezp** [comment]
Howdy @Steffi3rd ,
[Updated.](https://documentation.onesignal.com/docs/react-native-sdk-setup#section-finish-notification-service-extension-setup)

Thank you so much for your suggestion.

**Comment by rgomezp** [comment]
Will close for now. We will continue tracking internally.

**Comment by j4hangir** [comment]
Would be nice to have this feature! For me wasn't possible to share my password with OneSignal .
