### ISSUE TITLE
Images from firebase doesn't display in iOS Notification.

### ISSUE THREAD

**Issue by Steffi3rd** [OneSignal/react-native-onesignal#979]
Hello guys. I'm trying to display image on a iOS notification.

Here is the url : https://firebasestorage.googleapis.com/v0/b/xxxxxxx.appspot.com/o/DEV-2-Ronnie%2F2020-04-05-IMG_0006.HEIC?alt=media&token=xxxxxx.jpg (still works April 8, 2020)

(I can't remove `?token...`)

My push notification is created by API. It works for 99% of my images but except when it comes from Firebase. 

So to resume : My backend code can create push notification with or without images. But if images comes from Firebase it doesn't work. 

How can I solve that please ?

**Comment by rgomezp** [comment]
Howdy,
Can you please include a code snippet where you are setting this on the backend?

Also, are you sending to Android as well?

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by Steffi3rd** [comment]
Oops, I'm very sorry @rgomezp. 
I didn't see you have replied. How to reopened it?

---

I'm sending only to iOS devices.

Here is the snippet in my backend

```
function buildPayload($externalUserIds, $content, $title, $subtitle, $ios_attachments, $url, $customData) {
  $data_externalUserIds = isset( $externalUserIds ) ? $externalUserIds : array("34");
  $data_content         = isset( $content ) ? $content : "Tu as une nouvelle notification";
  $data_title           = isset( $title ) ? $title : null;
  $data_subtitle        = isset( $subtitle ) ? $subtitle : null;
  $data_url             = isset( $url ) ? $url : null;
  $data_imageUrl        = isset( $ios_attachments ) ? $ios_attachments : null;
  $data_customData      = isset( $customData ) ? $customData : null;

  $oneSignal_appID = "";

  $fields = array(
    'app_id' => $oneSignal_appID,
    'headings' => $data_title,
    'subtitle' => $data_subtitle,
    'contents' => $data_content,
    'include_external_user_ids' => $data_externalUserIds,
    'data' => $data_customData,
    'url' => $data_url,
    'ios_attachments' => $data_imageUrl,
    'ios_badgeType' => 'Increase', // 'SetTo',
    'ios_badgeCount' => 1
  );
  
  $fields = json_encode($fields);

  return $fields;
}

function sendToOneSignal ($fields) {
  $oneSignal_restAPI = "";

  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, "https://onesignal.com/api/v1/notifications");
  curl_setopt($ch, CURLOPT_HTTPHEADER, array(
      'Content-Type: application/json; charset=utf-8',
      'Authorization: Basic ' . $oneSignal_restAPI
  ));
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($ch, CURLOPT_HEADER, FALSE);
  curl_setopt($ch, CURLOPT_POST, TRUE);
  curl_setopt($ch, CURLOPT_POSTFIELDS, $fields);
  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
  
  $response = curl_exec($ch);
  curl_close($ch);
  
  return $response;
}
```

This code above works, in production. Users can receive notifications. 

But they cannot see images if image comes from firebase...

**Comment by jkasten2** [comment]
@Steffi3rd Can you generate a URL that has `.jpg` instead of `.HEIC` so the final URL looks like this?
https://firebasestorage.googleapis.com/v0/b/xxxxx.appspot.com/o/DEV-2-Ronnie%2F2020-04-05-IMG_0006.jpg?alt=media&token=xxxxxxxxxxxx.jpg

This has to due with iOS not automatically detecting the file type and the OneSignal-iOS-SDK taking an attempt at it based on the URL.
https://github.com/OneSignal/OneSignal-iOS-SDK/issues/134#issuecomment-285159398

I think there is so improvement the OneSignal-iOS-SDK can make in detection so your original URL works however hopely the work around for you works for now.

**Comment by Steffi3rd** [comment]
Hello

Thanks for you answer.

I’m’using the React Native SDK, and the REST API. 

So the solution is to rename as an .jpg instead of .HEIC, even the file is still a HEIC file ?

(@jkasten2 Can you please edit your comment and mais/hide the domain of my url please 🙏 i made a mistake by sharing it as public)

**Comment by jkasten2** [comment]
@Steffi3rd Yes correct, that should work around the issue for now.

Edit my last comment per your request.

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by Steffi3rd** [comment]
Hello here 👋

I wanna say that it works now (since yesterday) without any code change! 
Images from firebase (without extension) are now display in iOS Notifications. 

Did you made a release to fix that? I'm interested to see how it was fixed. 

Thanks!

**Comment by rgomezp** [comment]
Howdy @Steffi3rd ,
I'm not seeing anything done from our end that may have resolved the issue.

Most likely it was due to an issue covered in this [troubleshooting guide](https://documentation.onesignal.com/docs/notification-images-not-showing).

Enjoy!

**Comment by dochonglo** [comment]
Hey everyone! :)

For some reason, this is an issue for me now--where images hosted in Firebase are not being shown on my notifications. I correctly installed the OneSignalNotificationExtension for my ejected Expo project.

I can successfully send push notifications to test phones using Firebase Cloud Functions and from the OneSignal dashboard.

Currently, I'm running `"react-native-onesignal": "^4.3.0"` and the iOS deployment target for my Podfile, Xcode project, and OneSignalNotificationExtension are each iOS 13.

I'm having the same problem OP was experiencing with images stored in Firebase cloud storage not showing up on any notifications sent; only the text is shown.

Here's how I'm sending the notifications in my Cloud Function. (I'm following the example from OneSignal's documentation: https://documentation.onesignal.com/docs/firebase)

```
// ==========================================================================
//
// Cloud Functions File
//
// ==========================================================================


exports.sendNotificationFromOS = functions.https.onCall(
  async (data, context) => {
    const sendNotification = (data) => {
      const headers = {
        "Content-Type": "application/json",
        Authorization: "Basic [Redacted]",
      };

      const options = {
        host: "onesignal.com",
        port: 443,
        path: "/api/v1/notifications",
        method: "POST",
        headers: headers,
      };

      const https = require("https");
      const req = https.request(options, (res) => {
        console.log("(Cloud Function) StatusCode = ", res.statusCode);
        console.log("(Cloud Function) Headers = ", res.headers);
        res.on("data", (data) => {
          console.log("(Cloud Function) Response = " + JSON.stringify(data));
        });
      });

      req.on("error", (error) => {
        console.log("(Cloud Function) Error = " + error);
      });

      req.write(JSON.stringify(data));
      req.end();
    };

    const message = {
      app_id: [Redacted],
      contents: { en: data.contents },
      data: {
        postImageUrl: data.postImageUrl,
        imageUrl:
          "https://firebasestorage.googleapis.com/v0/b/xxxxx.com/o/groups%2FSJFkDkyjyB2FS0XHFOxL%2Factivities%2F0.c3hz8dblovc?alt=media&token=xxxxxxx",
      },

      channel_for_external_user_ids: "push",
      include_external_user_ids: [.....],
      ios_attachments: {
        id1: "https://firebasestorage.googleapis.com/v0/b/xxxxx.com/o/groups%2FSJFkDkyjyB2FS0XHFOxL%2Factivities%2F0.c3hz8dblovc?alt=media&token=xxxxxxx",
      },
      big_picture:
        "https://firebasestorage.googleapis.com/v0/b/xxxxx.com/o/groups%2FSJFkDkyjyB2FS0XHFOxL%2Factivities%2F0.c3hz8dblovc?alt=media&token=xxxxxxx",
      ios_badgeType: "Increase",
      ios_badgeCount: 1,
    };

    return sendNotification(message);
  }
);

// ==========================================================================
//
// Calling the Cloud Function on the client side
//
// ==========================================================================

        let data = {
          contents: "Just enjoying the outdoors.",
          postImageUrl:
         "https://firebasestorage.googleapis.com/v0/b/xxxxx.com/o/groups%2FSJFkDkyjyB2FS0XHFOxL%2Factivities%2F0.c3hz8dblovc?alt=media&token=xxxxxxx",
        };

        cloudFunctions()
          .httpsCallable("sendNotificationFromOS")(data)
          .then((response) => {
            console.log(
              "Successfully sent push notification."
            );
          })
          .catch((error) => {
            console.log(
              "Error sending push notification."
            );
          });
```

What could be the issue here? 

Really appreciate any help on this! Thanks in advance! :)

**Comment by jkasten2** [comment]
@ismaelbarry If you send a notification from the OneSignal dashboard and upload an image does it display on the notification? Doing so will confirm your OneSignalNotificationExtension is setup correctly.

If the above works it is possible your images on firebase storage are not setup to return the correct MIME type in the HTTP response. If you are not able to correct this one way to work around this is noted above, where you can ensure the correct file type is included in the URL.
[OneSignal-iOS-SDK source](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/3.10.2/iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m#L835-L840) for more details.

**Comment by dochonglo** [comment]
@jkasten2 - Thanks for your quick response!

I tried sending an image through the OneSignal Dashboard. Interestingly, only the text gets sent (e.g., title, subtitle, and message). However, the image (whether it's uploaded as a JPEG image from my desktop or a URL from my Firebase cloud storage) does not show when it's received on devices.

As per your suggestion, the issue must be with the installation of the OneSignalNotificationExtension. Now, I assume that it's installed correctly to some degree, given that I can send and receive notifications. With that, what have you come to understand to be common reasons why people have not installed the extension properly, and therefore images don't show?

Thanks!

**Comment by jkasten2** [comment]
@ismaelbarry You can try the iOS notification service extension troubleshooting guide here:
https://documentation.onesignal.com/docs/service-extensions#troubleshooting-the-ios-notification-service-extension

We also have an expo plugin which will setup the notification service extension for you so you no longer have to eject as well:
https://github.com/OneSignal/onesignal-expo-plugin

**Comment by dochonglo** [comment]
@jkasten2  - I appreciate you sharing these resources. Unfortunately, we had ejected from Expo almost 2 years ago and the `onesignal-expo-plugin` was not available at the time.

Given that this is a large project, would you suggest keeping the OneSignal implementation that we currently installed from ejecting or could we possibly install the `onsignal-expo-plugin` and run with that--if it will help resolve the issue with images not showing up? What are your thoughts?

**Comment by jkasten2** [comment]
@ismaelbarry You can try debugging (the first link) since that one would probably be faster than rebuilding the full react project. But if you get stuck spinning your wheels on debugging you may want to give the `onsignal-expo-plugin` a try next.

**Comment by dochonglo** [comment]
@jkasten2 - out of curiosity, what would make the OneSignalNotificationExtension work with sending notifications with text but not images?

**Comment by jkasten2** [comment]
@ismaelbarry  `OneSignalNotificationExtension` doesn't need to run, or be present, for basic text only notifications.

The following features requires the Notification Service Extension:
* [Confirmed Deliveries](https://documentation.onesignal.com/docs/confirmed-deliveries)
* [Badges](https://documentation.onesignal.com/docs/badges#setting-and-clearing-badge-numbers)
* [Media Attachments](https://documentation.onesignal.com/docs/rich-media#rich-notifications) (images, video, & audio clip)
* [Action Buttons](https://documentation.onesignal.com/docs/action-buttons)
* [Influenced Opens with Firebase Analytics](https://documentation.onesignal.com/docs/google-analytics-for-firebase)

_Source: https://documentation.onesignal.com/docs/service-extensions#ios-notification-service-extension_

**Comment by dochonglo** [comment]
@jkasten2 - Understandably, I had the OneSignalNotificationExtension installed when I completed the set up. Interestingly, I'm able to get badge information. However, media attachments are not showing for some reason.

Now if we were to choose the `onesignal-expo-plugin`, would we have to remove and delete any previous OneSignal installation/set-up? Or could we just simply install it at the command line like so `expo install onesignal-expo-plugin` and start using it immediately?

**Comment by dochonglo** [comment]
Also @jkasten2 - I upgraded to the latest version of `react-native-onesignal` (as well as doing a `pod install`) and reviewed the documentation regarding the installation and went through to ensure everything was installed correctly. Unfortunately, I'm still having no luck. This issue is happening in development when testing it on my physical iPhone. What's more, trying to send notifications with images from the OneSignal dashboard only sends notifications with text and not any media.

Here's the `OneSignalNotificationServiceExtension` installed in Xcode:

![Group 46](https://user-images.githubusercontent.com/13290756/166617056-2e0cbc31-ae2c-4b47-a846-ee43561e7297.png)

These are the current versions of OneSignal in my package.json:

-  `"onesignal-expo-plugin": "^1.0.2",`
-   `"react-native-onesignal": "^4.3.8",`

Here's the Podfile where the extension is outside the main target (but at the same level as the main target):

```
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end
```

What do you think may be the issue given that I did the installation correctly? Also, why do you think OP is having success being able to have images stored in Firebase showing up in notifications, without renaming them to either `jpg` or `png` given that I'm using the latest version of the library?

**Comment by jkasten2** [comment]
> @jkasten2 - Understandably, I had the OneSignalNotificationExtension installed when I completed the set up. Interestingly, I'm able to get badge information. However, media attachments are not showing for some reason.

For badges, it is only the increase feature that needs to the NSE, set don't require it.

> Now if we were to choose the onesignal-expo-plugin, would we have to remove and delete any previous OneSignal installation/set-up? Or could we just simply install it at the command line like so expo install onesignal-expo-plugin and start using it immediately?

Since you already have `react-native-onesignal` installed you don't need to remove and re-add. You can run `expo install onesignal-expo-plugin` per the instructions and follow the rest of the steps there.


> What do you think may be the issue given that I did the installation correctly?

Did you get anything in the log outlined here?:
https://documentation.onesignal.com/docs/service-extensions#troubleshooting-the-ios-notification-service-extension


>  Also, why do you think OP is having success being able to have images stored in Firebase showing up in notifications, without renaming them to either jpg or png given that I'm using the latest version of the library?

I think the OP's NSE is working correct, where the issue you are having is it isn't running or is crashing possibly.

**Comment by dochonglo** [comment]
Hi @jkasten2 - thanks for following up.

I went through the troubleshooting guide for the iOS Notification Service Extension and interestingly, there are no logs showing up when searching for the OneSignalNotificationServiceExtension as the Category.

Why do you think this is the case? And what do you think is the issue now given the result of the troubleshooting?

**Comment by jkasten2** [comment]
@ismaelbarry This provides some info, it means it isn't even getting to the part to execute the OneSignal code, since the log statement in the instructions has you added before the code.

We will need logs from ANY "NotificationServiceExtension" instead to see what iOS itself is trying to do to start your NSE.


It should be about 500 lines log and look something like this:
<img width="930" alt="image" src="https://user-images.githubusercontent.com/645861/167270105-b2bf54d0-2569-475d-bee7-69c755920392.png">

Upload it as a file like this example (forgot to filter by NotificationServiceExtension, so this is more than needed):
[example_log_of_capturing_any_NSE.log](https://github.com/OneSignal/react-native-onesignal/files/8645878/example_log_of_capturing_any_NSE.log)

**Comment by dochonglo** [comment]
@jkasten2 - Here's a screenshot of the logs that I get when I send a notification to my device. These are the only logs that show up when searching for ANY "NotificationServiceExtension". For some reason, I'm not getting as many logs as you are.

![Group 1](https://user-images.githubusercontent.com/13290756/167272121-a0bedb40-0545-4c11-b82b-c512d0a80fb5.png)

**Comment by jkasten2** [comment]
@ismaelbarry You may need to capture the log without any filters. iOS throws a lot of entries so I would recommend clearing it then sending your notification immediately, then also immediately capture the log after you see the notification. 
If you don't want to post the log here, feel free to contact OneSignals support and link them to your exact comment here.


Here is some more details on some specific parts of the log to look for with the NSE working and NOT working:

Not working - NSE target not setup:
Important part is "No extension available for bundle".
```
default	17:27:11.700661-0700	SpringBoard	[com.onesignal.example] Received remote notification request 32DA-ADB7 [ waking: 0, hasAlertContent: 1, hasSound: 1 hasBadge: 0 hasContentAvailable: 0 hasMutableContent: 1 pushType: Alert]
default	17:27:11.700747-0700	SpringBoard	[com.onesignal.example] Remote notification request 32DA-ADB7 can be modified: 1
error	17:27:11.700881-0700	SpringBoard	[com.onesignal.example] No extension available for bundle
error	17:27:11.700973-0700	SpringBoard	[com.onesignal.example] Error was encountered trying to find service extension: error=Error Domain=UNErrorDomain Code=1904 "Unknown application" UserInfo={NSLocalizedDescription=Unknown application}
```

Working - NSE target is found:
Importing part here is "NSExtensionIdentifier ="
```
default	13:14:36.067312-0700	SpringBoard	[com.onesignal.example] Received remote notification request A664-2EB3 [ waking: 0, hasAlertContent: 1, hasSound: 1 hasBadge: 0 hasContentAvailable: 0 hasMutableContent: 1 pushType: Alert]
default	13:14:36.067411-0700	SpringBoard	[com.onesignal.example] Remote notification request A664-2EB3 can be modified: 1
default	13:14:36.067804-0700	SpringBoard	[d <private>] <PKHost:0x282822840> Beginning discovery for flags: 1024, point: (null)
info	13:14:36.067854-0700	SpringBoard	[d <private>] <PKHost:0x282822840> Query: {
    NSExtensionIdentifier = "com.onesignal.example.OneSignalNotificationServiceExtensionA";
}
```
Your NSE might get this far and still not work, there could be some other failure below.

**Comment by dochonglo** [comment]
@jkasten2 - thanks for this tip. With your advice, I got the following output when trying to send a push notification to my device. The push notification is successfully received. However, the image doesn't show and the following logs appear.

![Screen Shot 2022-05-07 at 9 26 18 PM](https://user-images.githubusercontent.com/13290756/167278013-2739d83c-7d6e-4764-bd20-e59b5ffc4439.png)

**Comment by jkasten2** [comment]
@ismaelbarry Looks like it isn't find the notification service extension (NSE) at all in the app. some other things to check are:
1. Make sure you NSE is set to a lower enough iOS version and type of devices (iPhone & iPad) you are testing on:
<img width="686" alt="image" src="https://user-images.githubusercontent.com/645861/167278264-f6c4f910-3267-492e-afae-f53bc1859091.png">

2. Make sure you have an `com.apple.usernotifications.service` entry in the `.plist` for the NSE target
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/645861/167278295-eae67fbe-ddef-428c-ac5d-8f47abbe19ff.png">

If you don't have this plist entry, you can attempt to add it but other things could be wrong so you may just want to delete and recreate the target.

**Comment by dochonglo** [comment]
@jkasten2 - for some reason, this is how my info.plist for my extension is set. Note the NSExtensionPrincipalClass key is different from yours.

![Screen Shot 2022-05-07 at 9 48 16 PM](https://user-images.githubusercontent.com/13290756/167278493-d68ef597-ad34-41a5-af0d-1d387c47a4ce.png)

Also, the documentation states that the deployment target for the extension must match the main target's deployment as well as the deployment set in the Podfile. As per your suggestion, should I set the extension's target to be lower, and therefore different, from the main target?

**Comment by jkasten2** [comment]
The `$(PRODUCT_MODULE_NAME).` prefix is only for Swift, Objective-C shouldn't have this and it should just be `NotificationService` as you have it.

**Comment by jkasten2** [comment]
> Also, the documentation states that the deployment target for the extension must match the main target's deployment as well as the deployment set in the Podfile. As per your suggestion, should I set the extension's target to be lower, and therefore different, from the main target?

With Cocoapods it has to be the same iOS version and type as the main target.

Even with everything above correct you may want to delete the NSE target and recreate it following the [OneSignal instructions](https://documentation.onesignal.com/docs/react-native-sdk-setup#step-4-install-for-ios-using-cocoapods-for-ios-apps), as something else may still be off and this will get Xcode to fully regenerate the correct settings.

**Comment by dochonglo** [comment]
@jkasten2 - Got it, I'll delete and do a full recreation.

Now for the OneSignalNotificationServiceExtension, should the version and build on the "Generals" tab be the same as the main target?

**Comment by jkasten2** [comment]
> Now for the OneSignalNotificationServiceExtension, should the version and build on the "Generals" tab be the same as the main target?

It doesn't need to be to run, but for Apple to accept it when you submit it it will.

**Comment by dochonglo** [comment]
@jkasten2 - Thanks so much for your continued help!! 

I did a full delete and recreation. This time with Swift rather than Objective-C. Now, I'm running into the same issue it seems. Here are the logs: 

![Group 1](https://user-images.githubusercontent.com/13290756/167280433-8bc6fff7-304e-474c-a9c7-98c8a813b160.png)

Given that I did a fresh creation, what do you think could be the issue?

**Comment by dochonglo** [comment]
@jkasten2 - Thanks for your help in debugging this issue. I think I may have found the solution.

After doing some Googling, I found the following post: https://developer.apple.com/forums/thread/674620

As one the posters mentioned, doing the following helps resolve the issue. TARGETS (main) -> Build Phases -> Embed App Extensions -> Uncheck "Copy only when installing"

After doing the above, my images ended up showing in push notifications. I don't know why my extension was being installed with the box checked.

Furthermore, I checked the logs and found that there are no errors. What's more the images show in the notifications whether they are being triggered from cloud functions or from the OneSignal dashboard.

Thank you so much for helping and being proactive in responding and pointing me in the right direction!! :)

**Comment by jkasten2** [comment]
> As one the posters mentioned, doing the following helps resolve the issue. TARGETS (main) -> Build Phases -> Embed App Extensions -> Uncheck "Copy only when installing"

O interesting, I never ran into that one before, nice find! We will look into adding that to OneSignal troubleshooting guide.


> Thank you so much for helping and being proactive in responding and pointing me in the right direction!! :)

Glad I could help!

**Comment by isaacHuh** [comment]
> @jkasten2 - Thanks for your help in debugging this issue. I think I may have found the solution.
> 
> After doing some Googling, I found the following post: https://developer.apple.com/forums/thread/674620
> 
> As one the posters mentioned, doing the following helps resolve the issue. TARGETS (main) -> Build Phases -> Embed App Extensions -> Uncheck "Copy only when installing"
> 
> After doing the above, my images ended up showing in push notifications. I don't know why my extension was being installed with the box checked.
> 
> Furthermore, I checked the logs and found that there are no errors. What's more the images show in the notifications whether they are being triggered from cloud functions or from the OneSignal dashboard.
> 
> Thank you so much for helping and being proactive in responding and pointing me in the right direction!! :)

You have no idea how long I've been trying to fix this! Your a life saver🙏
