### ISSUE TITLE
ld: framework not found OneSignal

### ISSUE THREAD

**Issue by SERGEIBARATS** [OneSignal/react-native-onesignal#981]
Hi there

I have an error when try to execute my app in iOS phone or simulator.

I followed the instructions with the page (https://documentation.onesignal.com/docs/react-native-sdk-setup). But the error persists.

![Screen Shot 2020-04-09 at 21 58 39](https://user-images.githubusercontent.com/38927319/78930749-47c14200-7aad-11ea-9f8d-4adfbfb8e2fc.png)
![Screen Shot 2020-04-09 at 21 59 52](https://user-images.githubusercontent.com/38927319/78930844-73dcc300-7aad-11ea-9f47-d30e2cac928a.png)

Also, I clean, build, set the commands pod Install, Pod deintegrate, delete Pod folder, PodFile.lockfile, delete files in ~/Library/Developer/Xcode/DerivedData, delete Target OneSignalNotificationServiceExtension and create it again. But the error continues.

I'm using the package react-native-onesignal: ^3.7.1

RN 60+

Thanks

**Comment by tmaly1980** [comment]
I saw the same problem but got it to work. I noticed when running pod install it warned me about FRAMEWORK_SEARCH_PATHS being modified, so I added $(inherit) to that (search for 'Framework Search Paths' under your Target's Build Settings), and it worked. Seemed that Framework Search Paths was left blank.

**Comment by SERGEIBARATS** [comment]
The issue is not resolved..
The warning disappeared, but the error is still there.

**Comment by RoTTex** [comment]
Same here. As I noticed, It happened after OneSignal updates from 2.13.0 to 2.13.1.
I'm not sure that I have got the same issue. My OneSignal folder in Pods is empty.
<img width="261" alt="Screenshot 2020-04-11 at 20 36 59" src="https://user-images.githubusercontent.com/3602801/79050654-39516280-7c34-11ea-8873-1e0d7282b99a.png">
I will get the same result if I use `pod 'OneSignal', '>= 2.11.2', '< 3.0'` instead of  `pod 'react-native-onesignal', path: "#{$npm_path}/react-native-onesignal"` in my Podfile.

**Comment by arnoldpassly** [comment]
+1 please help.

**Comment by rgomezp** [comment]
Howdy,
We haven't been able to reproduce on our side.

Have y'all run `pod deintegrate && pod install` ???

**Comment by RoTTex** [comment]
`pod cache clean --all` helped me!

**Comment by roysG** [comment]
I have the same issue any update?

**Comment by pyjun01** [comment]
```
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end
```

helped me

**Comment by roysG** [comment]
Guys, go to "Build Settings" -> "Search Paths" 
change the value of $(PROJECT_DIR) to recursive

and Wolla! now it should work!

**Comment by rgomezp** [comment]
Howdy,
It sounds like this issue is solved. 

Enjoy!

**Comment by ecgreb** [comment]
Solution recommended by @tmaly1980 ultimately worked for me.

This post also helped me figure out exactly _where_ to make this change -> https://stackoverflow.com/questions/26445784/target-overrides-the-framework-search-paths-build-settings

This is not an issue unique to the One Signal SDK, rather it is a hurdle you can run into with any pod that uses a dynamic framework and not a static library. Still it might be helpful to add a note to the iOS & React Native getting started guides in case others run into this issue 🙏
