### ISSUE TITLE
iOS can't fire receive action when app go background

### ISSUE THREAD

**Issue by FansPro** [OneSignal/react-native-onesignal#982]
**Description:**
iOS can't fire receive action when app go background

**Environment**
iOS

**Anything else:**
  OneSignal.addEventListener("received", this.onReceived);

**Comment by rgomezp** [comment]
Howdy,
Good question. The iOS Native SDK calls this method when the app receives a notification while in focus only. If you need this to be called when your app is in the background, set `content_available` to true when you create your notification. The "force-quit" state (i.e app was swiped away) is not currently supported.

**Comment by rukmanary** [comment]
> Howdy,
> Good question. The iOS Native SDK calls this method when the app receives a notification while in focus only. If you need this to be called when your app is in the background, set `content_available` to true when you create your notification. The "force-quit" state (i.e app was swiped away) is not currently supported.

can you tell how to set `content_available` please? I'm not sure how to do it, is it in our app code or settings in dashboard?

**Comment by rgomezp** [comment]
Howdy,
This is set during notification creation on the dashboard or via the REST API.

[Reference](https://documentation.onesignal.com/reference/create-notification#content--language)
---

Enjoy!
