### ISSUE TITLE
How to increment badge count when badge count is set from local notification ?

### ISSUE THREAD

**Issue by Steffi3rd** [OneSignal/react-native-onesignal#983]
Hi, 

I successfully install React Native One Signal on my iOS. I’m very glad about it, because docs was very good to follow. 🥳

My badge count is normally on new push notification.

But I found that my push (remote) notification do not increase badge when badge is already set by local notification. 

Instead, it reset it to 1 then increase only IF another push (remote) notification is received.

Otherwise, Local notification do the same thing. If I a « 3 » on badge count, it will reset to 1 if a Local notification is received.

Is there a way to solve that please?

—

Local Notification : https://github.com/react-native-community/push-notification-ios

Remote Notification : https://github.com/OneSignal/react-native-onesignal

**Comment by rgomezp** [comment]
Howdy,
Thanks for your comments.

Take a look at this open issue with [React Native](https://github.com/facebook/react-native/issues/26199). If you comment over there, hopefully we can get this issue resolved!

**Comment by rgomezp** [comment]
Closing this issue since it is dependent on the issue noted above. Please follow the status of it there.

Enjoy!
