### ISSUE TITLE
setSubscription(false) not working on android

### ISSUE THREAD

**Issue by BogdanRad** [OneSignal/react-native-onesignal#984]
![image](https://user-images.githubusercontent.com/40359109/79429732-9badb880-7fd0-11ea-9be5-264c36d7f11f.png)

I added these lines on logout:
 OneSignal.setSubscription(false);
 OneSignal.removeExternalUserId(); 
But I receive the notifications when I am logout. Where is the problem?

**Comment by mikechoch** [comment]
Is the subscription change reflected on our dashboard for that device?
What version of the react OneSignal SDK are you using?
How are you sending these notifications?

**Comment by BogdanRad** [comment]
> Is the subscription change reflected on our dashboard for that device?
> What version of the react OneSignal SDK are you using?
> How are you sending these notifications?

Hey @mikechoch, 
1. I sent the notification from OneSignal on testing device
2. "react-native-onesignal": "^3.4.1",
3. from 'Send To Test Device'

**Comment by rgomezp** [comment]
Can you please make sure you are using the latest npm module?

**Comment by BogdanRad** [comment]
@rgomezp Yes, I have latest version. I will update react native onesignal at latest version.. I will come back with message after make this. Thanks for help

**Comment by rgomezp** [comment]
Any update? Would like to close this issue

**Comment by BogdanRad** [comment]
I fixed this problem. Thanks!

**Comment by EmilianoKalujerovich** [comment]
@BogdanRad how did you resolve it? I have the same problem. 
Thank you!
