### ISSUE TITLE
APNS delegate never fired - incorrect docs. Help not needed

### ISSUE THREAD

**Issue by nikitawolfik** [OneSignal/react-native-onesignal#985]
#910 - not it, tried
#880 leads to #503 where is the [answer](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/503#issuecomment-548847919). Apparently, the docs got updated and no longer say to manually add `  pod 'OneSignal', '>= 2.6.2', '< 3.0'` to Podfile

**Description:**

After following every required step in the installations docs
```
yarn add react-native-onesignal
cd ios && pod install && cd ..
```
and then adding required capabilities in Xcode, I was able to initialize the service, but pushToken from `onIds` was always null and Dashboard always showed `APNS delegate never fired` error. After traversing issues I found out that former docs included [these lines](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/503#issuecomment-548847919).

That was not really straightforward and should be added back to the documentation.

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Howdy,
It is in our documentation as you can see [here](https://documentation.onesignal.com/docs/react-native-sdk-setup#section--finish-notification-service-extension-setup-).

**Comment by nikitawolfik** [comment]
@rgomezp yeah, it indeed is, but the section starts with this
![image](https://user-images.githubusercontent.com/28301667/79944334-afe82e80-8484-11ea-9a3b-faa177175bc9.png)
`This step is optional but highly recommended. The OneSignalNotificationServiceExtension allows your application (in iOS) to receive rich notifications with images and/or buttons, along with Badges and advanced analytics like Outcomes.`

This is the kind of the section you skip when you are going for the quick setup with minimal functionality and I think it shouldn't be marked `optional` if not following these steps screws the whole notification thing :)

**Comment by rgomezp** [comment]
Thanks for your suggestion. We will try to make this section a bit clearer.

Enjoy!
