### ISSUE TITLE
Google Play Services Library Error

### ISSUE THREAD

**Issue by dungnguyentri3110** [OneSignal/react-native-onesignal#986]
Hi guys.
I facing with this problem. I know this problem already exists, but I only encounter it on android devices like Xiaomi, Huawei, oppo... I wanna fix this once in for all. Thanks you!

![Screen Shot 2020-04-20 at 2 49 08 PM](https://user-images.githubusercontent.com/54011066/79737717-ed827580-8325-11ea-9068-2e279ec7a4c4.png)

compileSdkVersion 28
buildToolsVersion '28.0.3'

**Comment by rgomezp** [comment]
Howdy,
Please reach out to our support channel at OneSignal.com for this type of issue.

Thank you!

**Comment by axios-tech** [comment]
I solved this by upgrading to version 3.9.4
