### ISSUE TITLE
Android not running custom sound in notification.

### ISSUE THREAD

**Issue by louzada01** [OneSignal/react-native-onesignal#988]
**Description:**
I'm created a app using `"react-native-onesignal": "^3.7.2"`and create a push notification in [App OneSignal](https://app.onesignal.com/) and send notification with sound for `donkey_kong.wav`. (`donkey_kong.wav` for iOs and `donkey_kong` for Android). 

My notification in iOs is running my custom sound, Ok. My notification on Android Os is played but my customized sound, the sound played is the default of the device.

Is sound file dir: `<dir_project>/android/app/res/raw/donkey_kong.wav`

(your description here)

**Steps to Reproduce Issue:**
  1. Install the OneSignal SDK using npm into your project
  2. Initialize the SDK in the iOS AppDelegate
  3. Attempt to receive a push notification

--- 

1. Create a notification push in OneSignal (app.onesignal)
2. Select invite for Android
3. Insert sound name without file extension (.wav) 
4. Send notification for device testing

**Anything else:**

Sound `donkey_kong` is not play with push notification

**Comment by rgomezp** [comment]
Howdy,
Please take a look at [this issue](https://github.com/OneSignal/react-native-onesignal/issues/753) for details. Perhaps the problem is similar.

Here are [all the issues ](https://github.com/OneSignal/react-native-onesignal/search?q=custom+sound&type=Issues) about this topic

**Comment by louzada01** [comment]
Thanks!!
