### ISSUE TITLE
Voip notifications for android

### ISSUE THREAD

**Issue by ankitmeddo** [OneSignal/react-native-onesignal#990]
I am using react-native-onesignal@3.7.2 and was sending VOIP on both platforms. I was successfully able to do on ios as it was well explained on documentation but dont know how to send over android.
As on ios, we need to send apns_push_type_override which is for ios only.
Can you please help us to send VOIP on android. It was missing on documentation.

**Comment by rgomezp** [comment]
Howdy,
There is no VOIP for Android like there is for iOS. You can still accomplish the same thing though. Please read our documentation [here](https://documentation.onesignal.com/docs/voip-notifications)
