### ISSUE TITLE
GooglePlay Dev alert: Your app contains exposed Google Cloud Platform (GCP) API keys

### ISSUE THREAD

**Issue by jason-ce** [OneSignal/react-native-onesignal#991]
**Description:**
> Security alert
> 
> Your app contains exposed Google Cloud Platform (GCP) API keys. Please see this Google Help Center article for details.
> 
> Vulnerable locations:
> 
> com.onesignal.PushRegistratorFCM->getApiKey

**Environment**
"react": "16.9.0",
"react-native": "0.61.5",
"react-native-onesignal": "^3.6.5",
added via NPM

This security alert shows up in the Google Play Console.

This issue is identical to this issue in the Unity SDK, except it appears in the react-native library: https://github.com/OneSignal/OneSignal-Unity-SDK/issues/278 

The Unity SDK fix was released approximately 21 days ago, and I have read the release notes for the past 21 days and have not seen any mention of this issue. Is this issue fixed in the underlying android library as well as the react-native library?

**Comment by rgomezp** [comment]
Howdy, this is a false positive. Simply update to the latest SDK to resolve. Enjoy!
