### ISSUE TITLE
React-native: Mobile Push notification: Action buttons are not showing until long press it

### ISSUE THREAD

**Issue by rikinshah23** [OneSignal/react-native-onesignal#993]
When I receive notification it shows action buttons only when long press the notification.

As shown below: When I receive it looks like this:

![image](https://user-images.githubusercontent.com/26806597/82008896-2236d380-962b-11ea-82fd-54b6a3aea5c5.png)

If I long press the notification then only it shows action buttons:

![image](https://user-images.githubusercontent.com/26806597/82008913-2cf16880-962b-11ea-95f5-b1f0b5132faf.png)

This is how I send notification with action buttons.

```
{
                contents: {
                    en: "Are you coming to work today?"
                },
                app_id: OneSignalAppID,
                // included_segments: ["Subscribed Users"],
                include_player_ids: [...],
                priority: 10,
                buttons: [{
                    id: "yes-feedback", text: "Yes"
                },
                { id: "no-feedback", text: "No" }
                ]

            },
```

I Have tried to look on how to make custom buttons but could not find anything yet. 

Also I have seen some apps' notifications shows button popped out already without pressing it so its probably doable but not sure where to start.

Android and iOS notifications working as expected but both needs to be long pressed to show the buttons.

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience. Notification customization requires writing native code through our [Notification Service Extensions](https://documentation.onesignal.com/docs/service-extensions#troubleshooting-the-ios-notification-service-extension). The limitations on what you can do varies from operating systems to operating systems but in either case you will need to customize the notifications yourself.

**Comment by rgomezp** [comment]
Closing due to no response.
