### ISSUE TITLE
iOS removeExternalUserId and setExternalUserId callbacks not called

### ISSUE THREAD

**Issue by ADjenkov** [OneSignal/react-native-onesignal#994]
On iOS both OneSignal.removeExternalUserId(callback) and OneSignal.setExternalUserId(callback) callbacks are not called back. I've checked that their internal `checkIfInitialized` passes but RNOneSignal.removeExternalUserId(callback); does not call the callback. For Android the callback is called after sometime. 

Callbacks get called if I made some random change in the same file but never called on called start.

PS: I'm calling both methods after OneSignal.Init and  OneSignal.setSubscription(true); 
Will removeExternalUserId work if don't call setSubscription(true) before that?

"react-native-onesignal": "^3.7.2"

**Comment by ADjenkov** [comment]
If I understand the event 'ids' is the one that tells me whether or not device is ready/registered in OneSignal and then I can call `setExternalUserId` safely? `Ids` event results have some strange (for me) body since sometimes it holds all the information (userSubscriptionSetting, subscribed, pushToken, userId) and sometimes just pushToken and userId. 

What would be the proper workflow to set external_user_id ?:
1. Init 
2. Listen for `ids` event and check for both userSubscriptionSetting and userId are true
3. Call `removeExternalUserId` (since it might be already set to the same one)
4. In the success callback of `removeExternalUserId` call setExternalUserId

**Comment by rgomezp** [comment]
Howdy, thanks for the question and your patience.

The 'ids' event now gets triggered automatically when `addEventListener` gets called. I didn't quite understand why you want to remove external user id. The standard practice is you should only call `setExternalUserId` when a user first opens the app or logs in. And you should only remove the id after they log out. Hope this helps.

**Comment by rgomezp** [comment]
Closing due to no response
