### ISSUE TITLE
[iOS] external_user_id is not set "Attempted to set external user id, but %@ is already set"

### ISSUE THREAD

**Issue by ADjenkov** [OneSignal/react-native-onesignal#995]
On iOS I'm unable to set external_user_id since an error is thrown that this external user id is already set, but there is no other device registered with that external_user_id in the OneSignal UI.

Should I call removeExternalUserId before setting it again? According to the docs I can have multiple devices with the same external_user_id _"Multiple device records in OneSignal can have the same external_user_id but will each have a unique player_id._" 

"react-native-onesignal": "^3.7.2"

**Comment by rgomezp** [comment]
You can have multiple devices have the same external id, in essence "tying" these devices together under the same "profile/account." However, it sounds like you're trying to set multiple external ids for the _same_ device. Make sure you're not setting this twice. Perhaps take a look at the logging with OneSignal verbose logging turned on or simply add some logging yourself to make sure it isn't happening twice on the same device.

**Comment by ADjenkov** [comment]
Sorry I've mislead you. My question should be "Is it possible to set external_user_id to device record that already has external_user_id set? Will it overwrite it or it will throw exception?"

**Comment by rgomezp** [comment]
Oh. Yeah it will just override it. Enjoy!

**Comment by jrahma** [comment]
It is not overriding in my case.

2021-04-15 22:53:04.030 Mawaqeet.iOS[940:162784] WARNING: Attempted to set external user id, but is already set


Also I am not getting any ExternalUserID when I go to the users report on your portal.

**Comment by hellogerard** [comment]
I am seeing the same issue. 

I have deleted all users with this external ID in the OneSignal dashboard. I am calling `setExternalUserId` and logging the results (copied from the docs). The call is successful, but the user does not appear in the OneSignal dashboard.

**Comment by hellogerard** [comment]
Okay, well, no sooner than leaving the above comment did I solve it by first removing the external user ID before setting it. But the call is async, so I had to put the call to `setExternalUserId` in the callback:

```js
  OneSignal.removeExternalUserId((results) => {
    console.log('Results of removing external user id');
    console.log(results);

    OneSignal.setExternalUserId(props.userId, (results) => {
      console.log('Results of setting external user id');
      console.log(results);
    });
  });
```

**Comment by hellogerard** [comment]
After further digging, the above solution works, but of course it's probably not great to leave in this state. Turns out I was running `react-native-onesignal` version `4.0.5` and upgrading to `4.0.6` (which upgrades the underlying iOS library to `3.3.0`) fixes this issue.
